### ISSUE TITLE
Unable to map <S-Space> in Neovide

### ISSUE THREAD

**Issue by Hubro** [neovide/neovide#1001]
**Describe the bug**

As Neovide is a GUI and not limited by terminal emulators, I would expect any combination of keys to be bindable. For example, `<S-Space>` (Shift+Space) is a key combination I have used a lot in GVim, but it doesn't appear to work in Neovide. Instead, the keybinding for `<Space>` is executed.

**To Reproduce**
1. Open Neovide
2. `nnoremap <S-Space> :echom "Test!"<CR>`
3. Press Shift+Space

**Expected behavior**

I would expect this to write the message "Test!".

**Screenshots**

\-

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Neovide Version Neovide 0.8.0
 - Neovim Version 0.5.1

**Please run `neovide --log` and paste the contents of the `.log` file here:**

https://gist.githubusercontent.com/Hubro/24b1a455ef1d12401614c96d5e7101ee/raw/5a73005b3c0582ac53a0b6240d8536f1a12d23f0/neovide_rCURRENT.log

**Additional context**

- `<C-Space>` and `<A-Space>` works fine
- `<S-CR>` also doesn't work (although `<C-CR>` and `<A-CR>` works fine)

**Comment by Kethku** [comment]
As some context, I believe this is an upstream issue. I have talked with the winit folks about this and their current stance is that they won't work on the interface which fixes this until the new keyboard APIs are merged https://github.com/rust-windowing/winit/pull/1890#issuecomment-886164186. I believe that we can't really fix this modifier issues with keybindings until this problem is addressed upstream.

@clason @smolck I believe you looked into this a while back and came to a somewhat similar conclusion but correct me if I'm wrong.

**Comment by technicalpickles** [comment]
🤦🏻‍♂️  I had tried several variations and must have caught it at a bad time. I did confirm I reproduced with p vs P though. Updated original comment.

**Comment by james2doyle** [comment]
Seems like this still an issue? Having trouble with `<D-p>` and `<D-P>` or `<D-S-p>`

**Comment by tombruijn** [comment]
It's fixed in the next release (PR https://github.com/neovide/neovide/pull/1483, [related comment](https://github.com/neovide/neovide/issues/1309#issuecomment-1222880805)). I [built it locally](https://neovide.dev/installation.html#mac-source) as described in that last issue and it fixed it for me.

**Comment by fredizzimo** [comment]
The new winit keyboard API is now merged in https://github.com/neovide/neovide/pull/1789. But I don't think it completely fixes the issue. 
See:
#994
#1646
https://github.com/neovide/neovide/issues/1862

**Comment by fredizzimo** [comment]
This should be fixed by #1899, it would be great if you can test that.

**Comment by Hubro** [comment]
@fredizzimo I can now map `<S-Space>` in Neovide (`0.10.4.r17.gf412399-2`) :rocket: 

Unrelated issue I stumbled into, when in terminal mode, accidentally pressing shift+space will exit terminal mode in the terminal and delete the entire current line, which I accidentally did about 50 times last night. This happens even though I have nothing mapped to `<S-Space>`.

I then realized I can easily work around it by mapping it to a normal space:

```
:tnoremap <S-Space> <Space>
```

Which fixes the issue, but probably worth looking into what causes the weird and annoying default behavior.

**Comment by fredizzimo** [comment]
@Hubro, which shell are you using. Maybe that's a feature or a mapping of that?

**Comment by Hubro** [comment]
> @Hubro, which shell are you using. Maybe that's a feature or a mapping of that?

I'm using zsh, but `<S-Space>` takes me out of terminal mode in Neovim, and I don't see how the shell can affect that :thinking:

**Comment by fredizzimo** [comment]
Yes, it should not be able to affect that. The only thing I can think of is that either you or some plugin has added a `<S-space>` mapping previously. You can check that by running just `:tmap`, but you probably already have.

**Comment by Hubro** [comment]
@fredizzimo Indeed, there is no such mapping. I have also tried to unmap my workaround-mapping (`:tunmap <S-Space>`), which triggers the weird behavior again.

**Comment by fredizzimo** [comment]
I guess one thing you could do is to run `neovide --log` It should show things like `Key pressed` and show what's sent to Neovim, to see if there's something strange there.

**Comment by Hubro** [comment]
@fredizzimo Sorry I was wrong, `<S-Space>` does not exit terminal mode, I only thought so because of another weird issue. Whenever I move my mouse over my Neovide window, it immediately exits terminal mode :sweat_smile: 

Instead, after some more experimentation, the default `<S-Space>` appears to be equivalent to hitting `<Esc>` followed by `u`. This happens in both bash and zsh, and I use vi bindings in both. The resulting behavior is leaving insert mode and undoing the last insert.

Indeed, if I disable vi bindings in bash (`set +o vi`) then this happens when I press `<S-Space>`:

![image](https://github.com/neovide/neovide/assets/597206/b71fd9b0-545c-4811-b4f8-07d68dcda039)

**Comment by technicalpickles** [comment]
I think there's been a regression on this. I've had different mappings for `<D-p>` and `<D-S-p>` for awhile, but after updating neovime and neovide to HEAD this week, only the `<D-p>` is working

**Comment by fredizzimo** [comment]
The correct mapping is `<D-P>`. 

It works on the other platforms, but on macOS there’s indeed a regression
https://github.com/neovide/neovide/issues/1237. Which to me looks like a Winit bug. But I don’t own a mac, so I have been waiting for someone else to continue testing and either fix it or report the bug to the winit team.

**Comment by technicalpickles** [comment]
@fredizzimo thanks for confirming! I always have a hard time remembering if it's supposed to include `S`, or just the value of the capitalized thing.
