### ISSUE TITLE
Chat Client

### ISSUE THREAD

**Issue by Kethku** [neovide/neovide#1002]
Gitter has let their certificate expire and has been offline twice in the last month. I'm looking into alternatives.

In the past when this has come up, folks have suggested:
- irc
- matrix
- discord

I personally use discord quite a lot for other work, and have disliked gitter for its lack of polish, but I'm interested to here if other folks have had differing experience. My inclination is to just make a discord channel and be done with it, but I have definitely gotten pushback when proposing this route in the past.

Any thoughts?

**Comment by clason** [comment]
(and Element -- the de facto standard web-based Matrix client -- is _much_ better than Gitter; the only thing I miss is the Github feed.)

**Comment by Kethku** [comment]
I have updated the readme. Thanks for the input folks

**Comment by Kethku** [comment]
good to know! I'll take a look at doing something like that
