### ISSUE TITLE
Crash when running "neovide --multiGrid" on Windows 10 

### ISSUE THREAD

**Issue by tex** [neovide/neovide#1008]
0.7.0 downloaded from your releases. Windows 10.
neovide doesn't start
started with:
neovide --multigrid --log

This is in the --log file:
ERROR [neovide::bridge] Cannot get neovim api info, either neovide is launched with an unknown command line option or neovim version not supported!

**Comment by tex** [comment]
Running just neovide without any flags works.

**Comment by PyGamer0** [comment]
In the earlier version it was --multiGrid
