### ISSUE TITLE
Modifiers are per frame not per key

### ISSUE THREAD

**Issue by mahkoh** [neovide/neovide#1023]
**Describe the bug**

In https://github.com/neovide/neovide/blob/7f76ad4764197ba75bb9263d25b265d801563ccf/src/window/window_wrapper/keyboard_manager.rs#L55-L65 the keyboard modifiers are changed. This change also incorrectly affects all keys received prior to this unless they have been cleared in https://github.com/neovide/neovide/blob/7f76ad4764197ba75bb9263d25b265d801563ccf/src/window/window_wrapper/keyboard_manager.rs#L66

**To Reproduce**

Rapidly press and release modifier keys.

**Expected behavior**

Changes in modifier keys only affect keys pressed after the change.

**Comment by Kethku** [comment]
Trying to understand the details here. Can you give an example usecase where this causes problems?

**Comment by mahkoh** [comment]
When A is pressed and Shift is pressed afterwards within the same frame, it will be treated as Shift+A.

**Comment by Kethku** [comment]
Uh. I assume this is due to macros? I can't get this to happen in a way that feels incorrect. Please reopen if you have more details and or the problem persists.
