### ISSUE TITLE
The ability to use different fonts for bold, italic, bold italic

### ISSUE THREAD

**Issue by quantum-booty** [neovide/neovide#1024]
Kitty terminal has the ability to set multiple fonts, for example in the kitty.conf:
font_family         FiraCode Nerd Font
bold_font           FiraCode Nerd Font
italic_font          JetBrains Mono Italic
bold_italic_font JetBrains Mono Bold Italic

Can we do something similar in neovide?

**Comment by Kethku** [comment]
This would require designing how that would work with the guifont format. Currently we have an extension where you can specify fonts for fallback by separating the names by commas, but It's not clear to me how this would work to specify fonts for each combination of bold and italic.

Anybody got any ideas

**Comment by PyGamer0** [comment]
@quantum-booty Is there any other neovim gui that does this?

**Comment by quantum-booty** [comment]
> @quantum-booty Is there any other neovim gui that does this?

I have only tried neovide so I'm not sure.

**Comment by augustocdias** [comment]
I know alacritty is able to render italics in neovim. No idea how

**Comment by Slotos** [comment]
Wezterm (likely a more useful comparison, being a rust terminal) offers [font_rules](https://wezfurlong.org/wezterm/config/lua/config/font_rules.html) declarations to choose fonts based on text attributes.

Although its basic [font](https://wezfurlong.org/wezterm/config/lua/wezterm/font.html) and [font_with_fallback](https://wezfurlong.org/wezterm/config/lua/wezterm/font_with_fallback.html) tend to choose matching italic and bold font variants quite well. E.g. selecting `{family = "SF Mono", weight = 'Light'}` chooses semibold variant for bold text.

**Comment by augustocdias** [comment]
From the little research I did, it seems it is up to the GUI to parse this, so we could just add a new option in the font definition. Something like `Font Family:oITALIC` -> the `oITALIC` meaning to match only when italic. Not sure if should be composable to set multiple of them like `Font Family:oITALIC|BOLD` or `Font Family:oITALIC&BOLD`

**Comment by fredizzimo** [comment]
This was added by
* https://github.com/neovide/neovide/pull/2213
* https://github.com/neovide/neovide/pull/2246
