### ISSUE TITLE
Looking for Maintainers

### ISSUE THREAD

**Issue by Kethku** [neovide/neovide#1028]
# Pulling back

About a month ago, a family emergency turned my life upside down. Its made prioritizing work on neovide and maintaining the various issues extremely difficult and has forced me to push the immediate changes I want to make to the backburner.

So I would like to put out the call for people who would like to contribute and help maintain this project. I am not planning on leaving permanently or abandoning the project. On the contrary I think more support from a maintenance point of view would open up the ability to build more end user features rather than just bug fixes.

# What I am looking for

There have been some fantastic contributions from many people and some amazing maintenance of issues from many others. Up till now I've acted as a sort of second line of defense for prioritizing and responding to issues. Due to above events, I can't do that anymore in a consistent way at least for a while. So I'm looking for any or all of the following:

1. Somebody interested in maintaining platform specific issues. Historically windows specific problems are easy for me to address because I'm a windows shop. Linux and mac issues are much harder. Having goto experts for each of the supported platforms would make a big difference (including windows)
2. Somebody interested in iterating on the design or architecture. I've worked hard to make the architecture of the app as simple as possible, but there's a lot of work left to do. If somebody is interested in iterating on that, I would love to discuss and help brain dump what's currently locked in my head so that such a person might feel enabled to make improvements as they see fit.
3. Feature work or maintenance of priorities. Thus far releases have sorta been "whenever I feel like it" and also have been defacto blocked by me being slow about it. If somebody is interested in pushing some sort of release cadence, I'm all ears.
4. Any other help or fixes! This is mostly a call for help building Neovide into something useful for the community. I won't be able to drive this in the same way as I have for the past two years for an unknown amount of time, so if anyone has a passion for the project and wants to use neovide as a starting point, I'm all there.

If you are interested in pitching in or have ideas for ways to make contributing simpler, feel free to discuss in this thread, on [discord](https://discord.gg/SjFpZdQys6), or in the [matrix](https://matrix.to/#/#neovide_community:gitter.im) channel. I don't think it is wise to give blanket admin rights to everyone, but it won't be hard to get onboarded. Just want to chat and or work a bit first :)

# Moving forward

The project won't die if nobody shows up, it will just slow down a bit. I've used neovide for personal and day job work since I started it, and that won't stop any time soon. So at the very least I will iterate on Neovide as a "works on my machine" basis for the foreseeable future. And I hope to be able to lend more full fledged support when my life calms down, but for now I can't. So please help! I think the project is worth while and fills an interesting niche :)

# PS

Mental health is a huge deal. If you or somebody you love is acting depressed or has withdrawn, please talk about it. Its better to address the hard problems than to leave them unspoken.

**Comment by TornaxO7** [comment]
Oh boy, that doesn't sounds good... I wish you all the best! Take your time to assimilate your current circumstances...

**Comment by LoipesMas** [comment]
I probably don't have the expertise to be a maintainer, but I will gladly help as much as I can. 
I can also help manage the discord server if needed. 
Thank you for all your work. 
Take care.

**Comment by dineshKumar777** [comment]
Please take your time. Family and heath comes first than anything.

Coming to project support:
- I am c# guy, so I wont be able to provide technical support, till I complete my Rust learning. But I can support build related issues or generic vim configuration related. Also I am a windows and linux user, so for any dev who needs help in testing specific platform, i can help with that too.
- Are you planning to post this thread in neovim and rust reddit community, so that interested ppl can come forward.

**Comment by TornaxO7** [comment]
> Are you planning to post this thread in neovim and rust reddit community, so that interested ppl can come forward.

That's a good idea! I can da that quickly.

**Comment by jonvaldes** [comment]
Sad to hear you're going through this, @Kethku 😔

I contributed some things in the early days, but I also had to withdraw because of family issues. My life is (a bit) more calm now, so I'll try to be more involved again. I won't be able to act as a maintainer or anything close to that, but I'll try to help out offloading some work where I can.

Hope things get better soon

**Comment by shaunsingh** [comment]
Sad to hear about the issues @Kethku, I've lost friends and family to mental health before. Take as long as it takes to properly recover. 

My studies picked up a bit a while back, so I haven't had as much time to work on the project. Now that its died down, I'll get to work fixing a few macOS related bugs.

**Comment by Kethku** [comment]
Thank you all for the well wishes :)

**Comment by TheConfuZzledDude** [comment]
I'd really love to help if I can, just need to be pointed at some stuff :)

**Comment by augustocdias** [comment]
Hi. I’d be willing to help with some stuff. 

I’m a rust developer, but have used it only for backend. That means I have no idea (and experience) how neovide does what it does.

I believe that most people that would be willing to take part in maintaining the repo don’t have rust knowledge or experience. I can definitely help with that.

Implementing new features could be tricky for me because of timing. I have a newborn at home and also work. If they’re small, then I can find time for it, otherwise it will be hard.  I can definitely find time to review code and guide people with development though.

let me know if I can be of any help.

**Comment by Kethku** [comment]
I've seen the two most recent responses and will respond with details soon!

**Comment by Mordanis** [comment]
I'll throw in my hat as well. I've never done any open-source stuff and only have a couple months of rust under my belt (with no gui :C), but happy to help and willing to learn.

Best wishes to you and your family

**Comment by da-moon** [comment]
while my main backend programming language is Go, I have been working with rust on and off for close to two years now. I am a bit rusty, since I haven't worked on any +10,000 lines of code rust projects since February; I have been meaning to get back to working with rust and I would love to help this project as neovide is my daily driver. 
Timewise, I can squeeze around 5-10 hours a week; I have a day job and I am also acting as a reasercher for a startup so I probably wouldn't be able to work on this more than 10 hours a week. 
Hope everything works out for you and your family.

**Comment by Kethku** [comment]
I have sent out invites to folks here to join the neovide org. I will then add those people to maintainers of the repo itself after that goes through.

Organization wise I'm not sure what the best course of action is. Some things I will do in the coming days that might help:
1. Create a list of outstanding areas which need help. This includes things like floating windows, some open issues with crashes, potentially features that are commonly requested
2. I can spend some time working on the documentation for how the system works today. I believe the best way to do that is to add rustdocs to everything and make sure the docs generate properly. After that I may take a look at what is blocking publishing neovide as a crate so that we can host the docs on crates.io

Beyond that, its open. I've never managed a project like this before so if folks have ideas for how maintenance or planning should work, I'm all ears.

**Comment by Kethku** [comment]
(apologies for the slow response rate btw. I'm still very much struggling with the stuff outlined above, but hope to be taking a break soon from my day job which should improve things)

**Comment by Kethku** [comment]
Step 1 is at least partially covered by #1061 which lists issues of note including a prioritization and difficulty categorization. However this mostly highlights current issues and not next steps in terms of new features. So any ideas are welcome for how to address those or features we should consider prioritizing as well.

**Comment by jonvaldes** [comment]
> (apologies for the slow response rate btw. I'm still very much struggling with the stuff outlined above, but hope to be taking a break soon from my day job which should improve things)

I don't think anyone can reasonably expect you to prioritize Neovide over your family. You're dealing with enough stuff already, so don't feel bad about not being able to spend more of your energy on this. Take care of the important stuff first.

**Comment by last-partizan** [comment]
@Kethku could you also move winit fork to neovide org, so we can handle it without bothering you?

**Comment by Kethku** [comment]
@last-partizan done. Should have done that a while ago...

**Comment by Kethku** [comment]
However its possible I will have to add people to the individual repos. I don't fully understand github's permissions structure

**Comment by last-partizan** [comment]
@Kethku yeah, looks like it works on per-project basis.

**Comment by Kethku** [comment]
Ok I think I fixed it. Turns out you can set base permissions for the org as a whole. Should be fixed now.

**Comment by last-partizan** [comment]
Yes, it fixed now. Thanks!

**Comment by fredizzimo** [comment]
@Kethku, I finally accepted the invitation! I have done considerably more here during the last week than I actually planned, so I thought I probably should accept it 🙂

**Comment by Kethku** [comment]
I never want anybody to feel like they have to do anything. That said your changes have been greatly appreciated :) Welcome aboard.

**Comment by kaiuri** [comment]
I intend to help out as much as I can.

**Comment by JryChn** [comment]
Hello, I wanna join, I am an engineer of a EE company, and have a lot of time on open source development. Now I am writing major in JAVA and Go, but I like rust and have learned for some time.

**Comment by AlexvZyl** [comment]
Hi @Kethku, I would be keen to lend a helping hand if it is still required.  I have written a graphics enine in OpenGL so I would say my knowledge thereof is decent.  Still learning Rust, but I should get the hang of it fairly quickly.

**Comment by Kethku** [comment]
Closing this as things have changed significantly.

Unsolicited update:
My family things have calmed down significantly over the last two years. I am no longer in crisis and am devoting some more time towards Neovide again. Thanks so much to the contributors that have stepped up and continue to work on the project. This is no longer my thing and instead owned and driven by the you all. That feels really great <3
