### ISSUE TITLE
Error building on ARM64 debian linux.

### ISSUE THREAD

**Issue by yashamon** [neovide/neovide#1029]
**Describe the bug**
Building on ARM64 debian produces an error near the end, apparently in getting skia-bindings. It also complains about ninja but this is in path at ~/ninja/.  

**To Reproduce**

Attached is the full backtrace:

RUST_BACKTRACE=full /snap/bin/cargo build --release
   Compiling skia-bindings v0.40.2
error: failed to run custom build command for `skia-bindingsv0.40.2`

Caused by:
  process didn't exit successfully: `/home/yashasavelyev/neovide/target/release/build/skia-bindings-5222d4f4d8d9f028/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-env-changed=SKIA_DEBUG
  cargo:rerun-if-env-changed=SKIA_SOURCE_DIR
  cargo:rerun-if-env-changed=FORCE_SKIA_BUILD
  cargo:rerun-if-env-changed=FORCE_SKIA_BINARIES_DOWNLOAD
  TRYING TO DOWNLOAD AND INSTALL SKIA BINARIES: 0.40.2/5c96670703e06e64f6fd-aarch64-unknown-linux-gnu-gl
  cargo:rerun-if-env-changed=SKIA_BINARIES_URL
    FROM: https://github.com/rust-skia/skia-binaries/releases/download/0.40.2/skia-binaries-5c96670703e06e64f6fd-aarch64-unknown-linux-gnu-gl.tar.gz
  DOWNLOAD AND INSTALL FAILED: https://github.com/rust-skia/skia-binaries/releases/download/0.40.2/skia-binaries-5c96670703e06e64f6fd-aarch64-unknown-linux-gnu-gl.tar.gz: status code404
  STARTING A FULL BUILD
  HOST: aarch64-unknown-linux-gnu
  cargo:rerun-if-env-changed=OPT_LEVEL
  cargo:rerun-if-env-changed=CC
  cargo:rerun-if-env-changed=CXX
  cargo:rerun-if-env-changed=SKIA_USE_SYSTEM_LIBRARIES
  cargo:rerun-if-env-changed=SDKROOT
  cargo:rerun-if-env-changed=SKIA_NINJA_COMMAND
  cargo:rerun-if-env-changed=SKIA_GN_COMMAND
  Probing 'python'
  Python 2 found: "python"
  Synchronizing Skia dependencies
  Skipping "../src".
  skia/third_party/externals/expat     @ e976867fb57a0cd87e3b0fe05d59e0ed63c6febb
  skia/third_party/externals/freetype  @ dfa7cca5f3b4f494aae785891ab4a42e66db77ef
  skia/third_party/externals/d3d12a... @ 169895d529dfce00390a20e69c2f516066fe7a3b
  skia/third_party/externals/libjpe... @ 64fc43d52351ed52143208ce6a656c03db56462b
  skia/third_party/externals/piex      @ bb217acdca1cc0c16b704669dd6f91a1b509c406
  skia/third_party/externals/harfbuzz  @ 3a74ee528255cc027d84b204a87b5c25e47bff79
  skia/third_party/externals/libpng    @ 386707c6d19b974ca2e3db7f5c61873813c6fe44
  skia/third_party/externals/zlib      @ c876c8f87101c5a75f6014b0f832499afeb65b73
  skia/third_party/externals/icu       @ dbd3825b31041d782c5b504c59dcfb5ac7dda08c
  skia/third_party/externals/libgif... @ fd59fa92a0c86788dcdd84d091e1ce81eda06a77
  skia/third_party/externals/libwebp   @ fedac6cc69cda3e9e04b780d324cf03921fb3ff4
  skia/third_party/externals/spirv-... @ bdbef7b1f3982fe99a62d076043036abe6dd6d80
  Skia args: is_official_build=true is_debug=false skia_enable_gpu=true skia_use_gl=true skia_use_egl=false skia_use_x11=false skia_use_system_libpng=false skia_use_libwebp_encode=false skia_use_libwebp_decode=false skia_use_system_zlib=false skia_use_xps=false skia_use_dng_sdk=false cc="clang" cxx="clang++" skia_use_icu=false skia_use_system_libjpeg_turbo=false target_os="linux" target_cpu="arm64" skia_use_expat=true skia_use_system_expat=false extra_cflags=["-O3","--target=aarch64-unknown-linux-gnu"] extra_asmflags=["--target=aarch64-unknown-linux-gnu"]
  Done. Made 76 targets from 28 files in 216ms
  Unknown architecture (aarch64) -- unable to run ninja.
  No prebuilt ninja binary was found for this system.
  Try building your own binary by doing:
    cd ~
    git clone https://github.com/ninja-build/ninja.git -b v1.8.2
    cd ninja && ./configure.py --bootstrap
  Then add ~/ninja/ to your PATH.

  --- stderr
  thread 'main' panicked at '`ninja` returned an error, please check the output for details.', /home/yashasavelyev/.cargo/registry/src/github.com-1ecc6299db9ec823/skia-bindings-0.40.2/build_support/skia/config.rs:385:5
  stack backtrace:
     0:       0x5f319451d8 - std::backtrace_rs::backtrace::libunwind::trace::h957e96d49366090c
                                 at /rustc/308dffd25cb55bbb4a1fbee9822cf82c6a5d012d/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
     1:       0x5f319451d8 - std::backtrace_rs::backtrace::trace_unsynchronized::hd4cdbf7ea8adf322
                                 at /rustc/308dffd25cb55bbb4a1fbee9822cf82c6a5d012d/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
     2:       0x5f319451d8 - std::sys_common::backtrace::_print_fmt::had06ae7a06ebf5af
                                 at /rustc/308dffd25cb55bbb4a1fbee9822cf82c6a5d012d/library/std/src/sys_common/backtrace.rs:67:5
     3:       0x5f319451d8 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hf43b7c63899df886
                                 at /rustc/308dffd25cb55bbb4a1fbee9822cf82c6a5d012d/library/std/src/sys_common/backtrace.rs:46:22
     4:       0x5f31968e84 - core::fmt::write::h3c9d33f22b6780a9
                                 at /rustc/308dffd25cb55bbb4a1fbee9822cf82c6a5d012d/library/core/src/fmt/mod.rs:1126:17
     5:       0x5f3193dba0 - std::io::Write::write_fmt::h3b49109c4ef1b326
                                 at /rustc/308dffd25cb55bbb4a1fbee9822cf82c6a5d012d/library/std/src/io/mod.rs:1667:15
     6:       0x5f31947324 - std::sys_common::backtrace::_print::he985e59647b19139
                                 at /rustc/308dffd25cb55bbb4a1fbee9822cf82c6a5d012d/library/std/src/sys_common/backtrace.rs:49:5
     7:       0x5f31947324 - std::sys_common::backtrace::print::h42b4798925d03705
                                 at /rustc/308dffd25cb55bbb4a1fbee9822cf82c6a5d012d/library/std/src/sys_common/backtrace.rs:36:9
     8:       0x5f31947324 - std::panicking::default_hook::{{closure}}::hb99e0ac7628cce4f
                                 at /rustc/308dffd25cb55bbb4a1fbee9822cf82c6a5d012d/library/std/src/panicking.rs:210:50
     9:       0x5f31946ec4 - std::panicking::default_hook::h4fc640ed1f174f9f
                                 at /rustc/308dffd25cb55bbb4a1fbee9822cf82c6a5d012d/library/std/src/panicking.rs:227:9
    10:       0x5f31947998 - std::panicking::rust_panic_with_hook::he7a65a7cf18f3b6d
                                 at /rustc/308dffd25cb55bbb4a1fbee9822cf82c6a5d012d/library/std/src/panicking.rs:624:17
    11:       0x5f31430d9c - std::panicking::begin_panic::{{closure}}::hf82e1606dedcafd7
                                 at /rustc/308dffd25cb55bbb4a1fbee9822cf82c6a5d012d/library/std/src/panicking.rs:544:9
    12:       0x5f31430c6c - std::sys_common::backtrace::__rust_end_short_backtrace::hfe7805d19d8ac7fc
                                 at /rustc/308dffd25cb55bbb4a1fbee9822cf82c6a5d012d/library/std/src/sys_common/backtrace.rs:141:18
    13:       0x5f31430cf0 - std::panicking::begin_panic::ha95488ef138b9f0d
                                 at /rustc/308dffd25cb55bbb4a1fbee9822cf82c6a5d012d/library/std/src/panicking.rs:543:12
    14:       0x5f312bf474 - build_script_build::build_support::skia::config::build_skia::hfcdeabd869415d53
                                 at /home/yashasavelyev/.cargo/registry/src/github.com-1ecc6299db9ec823/skia-bindings-0.40.2/build_support/skia/config.rs:385:5
    15:       0x5f312be8ec - build_script_build::build_support::skia::config::build::h0be25537892d0cee
                                 at /home/yashasavelyev/.cargo/registry/src/github.com-1ecc6299db9ec823/skia-bindings-0.40.2/build_support/skia/config.rs:331:5
    16:       0x5f312bf91c - build_script_build::build_from_source::he62d3d9abb1703c9
                                 at /home/yashasavelyev/.cargo/registry/src/github.com-1ecc6299db9ec823/skia-bindings-0.40.2/build.rs:38:5
    17:       0x5f312bfda0 - build_script_build::main::h1c80e438e4eab245
                                 at /home/yashasavelyev/.cargo/registry/src/github.com-1ecc6299db9ec823/skia-bindings-0.40.2/build.rs:126:13
    18:       0x5f312af7b4 - core::ops::function::FnOnce::call_once::hdccff02917509e93
                                 at /rustc/308dffd25cb55bbb4a1fbee9822cf82c6a5d012d/library/core/src/ops/function.rs:227:5
    19:       0x5f312c9d88 - std::sys_common::backtrace::__rust_begin_short_backtrace::he3a3aac74f28035d
                                 at /rustc/308dffd25cb55bbb4a1fbee9822cf82c6a5d012d/library/std/src/sys_common/backtrace.rs:125:18
    20:       0x5f312c0458 - std::rt::lang_start::{{closure}}::h44bf3cf62495babe
                                 at /rustc/308dffd25cb55bbb4a1fbee9822cf82c6a5d012d/library/std/src/rt.rs:64:18
    21:       0x5f31947dec - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h013b6f13df35dfb6
                                 at /rustc/308dffd25cb55bbb4a1fbee9822cf82c6a5d012d/library/core/src/ops/function.rs:259:13
    22:       0x5f31947dec - std::panicking::try::do_call::ha880f48a06c1efd8
                                 at /rustc/308dffd25cb55bbb4a1fbee9822cf82c6a5d012d/library/std/src/panicking.rs:403:40
    23:       0x5f31947dec - std::panicking::try::h1b9c45196dc3f1b3
                                 at /rustc/308dffd25cb55bbb4a1fbee9822cf82c6a5d012d/library/std/src/panicking.rs:367:19
    24:       0x5f31947dec - std::panic::catch_unwind::h87fb50e4370b7456
                                 at /rustc/308dffd25cb55bbb4a1fbee9822cf82c6a5d012d/library/std/src/panic.rs:133:14
    25:       0x5f31947dec - std::rt::lang_start_internal::{{closure}}::hf1fd0e0b8427588c
                                 at /rustc/308dffd25cb55bbb4a1fbee9822cf82c6a5d012d/library/std/src/rt.rs:46:48
    26:       0x5f31947dec - std::panicking::try::do_call::he18ae66c06c9827d
                                 at /rustc/308dffd25cb55bbb4a1fbee9822cf82c6a5d012d/library/std/src/panicking.rs:403:40
    27:       0x5f31947dec - std::panicking::try::h8f7b857eafe85360
                                 at /rustc/308dffd25cb55bbb4a1fbee9822cf82c6a5d012d/library/std/src/panicking.rs:367:19
    28:       0x5f31947dec - std::panic::catch_unwind::h5d9e9a243bebf695
                                 at /rustc/308dffd25cb55bbb4a1fbee9822cf82c6a5d012d/library/std/src/panic.rs:133:14
    29:       0x5f31947dec - std::rt::lang_start_internal::h8d2c153849175d6a
                                 at /rustc/308dffd25cb55bbb4a1fbee9822cf82c6a5d012d/library/std/src/rt.rs:46:20
    30:       0x5f312c0428 - std::rt::lang_start::h9955184947e3cd9d
                                 at /rustc/308dffd25cb55bbb4a1fbee9822cf82c6a5d012d/library/std/src/rt.rs:63:17
    31:       0x5f312c038c - main
    32:       0x77e7c898b8 - __libc_start_main
                                 at ./csu/../csu/libc-start.c:314:16
    33:       0x5f312a5af8 - _start
    34:                0x0 - <unknown>

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. macOS 11.4]
 - Neovide Version [e.g. 0.6.0]
 - Neovim Version [e.g. 0.5.0]

**Please run `neovide --log` and paste the contents of the `.log` file here:**

**Additional context**

**Comment by Kethku** [comment]
I think this is an upstream issue in skia-safe. Can you try building and running the examples over here https://github.com/rust-skia/rust-skia if that fails, could you create an issue on that repo?

**Comment by ChristopherLR** [comment]
This may be useless information, but doing cargo update -p skia-bindings and updating the skia dependencies in the Cargo.toml solved my issue

**Comment by PyGamer0** [comment]
So ig this is fixed? Closing (reopen if you still face problems)
