### ISSUE TITLE
Center window position on startup

### ISSUE THREAD

**Issue by etienne-k** [neovide/neovide#1030]
**Describe the bug**
When neovide is started, the window appears somewhere between the center and the bottom right corner of my screen (see screenshot).
This also means that the window appears smaller than the requested --geometry, because I tend to specify a geometry that takes about 75% screen height and width.
This effect appears in the latest git build (0.7.0.r185.g491973f-1). With the latest stable version, the window was centered at startup. This leads me to believe that this is a regression.

**To Reproduce**
Start neovide using a build of the latest sources.

**Expected behavior**
The window appears centered (or at least, that behavior is optionally configurable).

**Screenshots**
![image](https://user-images.githubusercontent.com/2804556/139603220-3f195a30-c251-4bae-9576-3245ab5f15e5.png)

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Neovide Version: 0.7.0.r185.g491973f-1
 - Neovim Version: 0.5.1 stable release (also tested with 0.5.0 - no difference)

Probably not relevant, but these are the GUI-related options I have set:
```lua
vim.o.guifont = "SauceCodePro Nerd Font Mono:h10" -- <font>:h<size>
vim.g.neovide_cursor_vfx_mode = "pixiedust"
vim.g.neovide_remember_window_size = false
```
[neovide_rCURRENT.log](https://github.com/neovide/neovide/files/7449893/neovide_rCURRENT.log)

**Comment by Kethku** [comment]
Window position is now remembered by default fixing this issue.
