### ISSUE TITLE
set wildmode=list:full still breaks completion

### ISSUE THREAD

**Issue by xakep71k** [neovide/neovide#1033]
**Describe the bug**
 set wildmode=list:full makes display of selected completion option to be written in a line below its correct placement.

**To Reproduce**
1. No init.vim
2. :set wildmode=list:full
3. :cd ~/.con + `<tab>`
4. delete n -> :cd ~/.co + `<tab>`
5. repeat 3-4 a few times (may be pressing `<tab>` multiple times)

**Expected behavior**
 Completion is displayed and highlighted on the same row

**Screenshots**
![Peek 2021-11-04 12-01](https://user-images.githubusercontent.com/26022428/140287506-9b833edc-4a53-4ad2-b274-0845a77fd956.gif)

![Peek 2021-11-04 12-02](https://user-images.githubusercontent.com/26022428/140287530-07959918-c376-41dc-9451-bcbb317f0baf.gif)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Neovide Version 0.5.1

**Comment by dineshKumar777** [comment]
@xakep71k I am not able reproduce it exactly.
But did you try this in terminal ?

https://user-images.githubusercontent.com/21097695/143016326-6bba264a-54a4-476f-bd5f-8e3aa597470b.mp4

**Comment by xakep71k** [comment]
@dineshKumar777 
Yes, I did. But in terminal this bug not reproducible. It is only reproducible in neovide.

**Comment by Kethku** [comment]
I cannot reproduce this issue in current main. The only difference is the lack of a border line above the completions which is a minor design choice in neovide's implementation of the multigrid ui extension.

Please reopen with more specific examples of the issue if the problem persists.

**Comment by fredizzimo** [comment]
I'm not sure, but I think it was the event ordering fix, that fixed this too https://github.com/neovide/neovide/pull/1132
