### ISSUE TITLE
Neovide ignores Numlock

### ISSUE THREAD

**Issue by usagi-flow** [neovide/neovide#1035]
**Describe the bug**
When starting Neovide with Numlock *on*, Neovide acts as if Numlock is *off*.
You have to disable Numlock, and then turn it back on. Then, it works, until neovide is closed and opened again.

**To Reproduce**
1. Enable Numlock (if it's not turned on).
2. Start neovide.
3. Start an empty buffer and switch to INSERT mode.
4. Enter some text, e.g. "abc".
5. Press the [7] key on the numpad. => The cursor moves to the beginning of the line, because the [7] key is interpreted as [Pos1] (as if Numlock were turned off).

**Expected behavior**
A "7" is appended to the text.

**Screenshots**
N.a.

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Neovide Version: main @ 491973f64555704bace19daf4c23395318a4a222
 - Neovim Version: 0.5.1 (stable)

**Please run `neovide --log` and paste the contents of the `.log` file here:**

**Additional context**
Tested using a keyboard with a German layout.

**Comment by fredizzimo** [comment]
This should be fixed by Neovide 0.11, maybe earlier.
