### ISSUE TITLE
Option to disable ligature rendering

### ISSUE THREAD

**Issue by Dareka826** [neovide/neovide#1037]
**Is your feature request related to a problem? Please describe.**
I know a lot of people like ligatures, but personally I don't really vibe with them.

**Describe the solution you'd like**
I'd like for an option to be added like g:neovide_ligatures_enabled or something of that sort which defaults to 1, but can be disabled.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by Kethku** [comment]
Use a font which doesn't have them. Ligatures aren't forced on you and not rendering them would be incorrect. Its based on the font

**Comment by Dareka826** [comment]
You wrote that rendering ligatures is the "correct" behavior, however I disagree. I'm of the opinion that whether ligatures should be rendered is personal preference and it would be unreasonable to expect someone to switch to a different font (from the one they are used to working with) just because they don't like ligatures.

**Comment by Dareka826** [comment]
@Kethku Could you take another look into this or should I open a separate issue with a clearer goal and reason?

**Comment by sisrfeng** [comment]
I'm using:
                set guifont=Hack\ Nerd\ Font\ Mono:h14
                set guifontwide=微软雅黑

I can't find "Hack Nerd Font Mono" without ligature.
It is annoying to switch to another font, because I have create lots of conceal characters with unicode special characters.

**Comment by Cthutu** [comment]
Has anything been done with this issue?  Ligatures in code is obnoxious as it joins characters that belong to separate entities.  For example: ":m .+1<CR>==" should not join the == to the >.  Also it's not clear how many = signs there are!  It would be preferable to have a global variable to turn this off.

And please don't say "change your font" - that's a lazy solution.

**Comment by 9mm** [comment]
I am also wanting to disable this insanity. These are just the worst.

I see some people say you can disable it in the "font settings", and i found another issue about configuring font settings. 

https://github.com/microsoft/terminal/issues/12213#issuecomment-1019648108

Is this something neovim supports?

**Comment by fredizzimo** [comment]
Ligatures are a part of the font, so switching the font is the correct thing to do. Some fonts however need options to disable one or more ligatures, this will be supported by https://github.com/neovide/neovide/pull/1920

Re-opening this until that is merged.

**Comment by 9mm** [comment]
Currently I'm using Nerd Fonts. I've used Anonymice pro for awhile which didnt have them, and I like JetBrains which does have them.

I've heard that using the 'mono' version of the font will disable it, except in that case I think all the icons are very small

I was hoping nerdfonts support that option but maybe they dont. i dont really know much about fonts, just trying to get it working without side effects

**Comment by fredizzimo** [comment]
@9mm, each nerd font is different, you have to check the specific readme for that actual font you are using to see how it's configured and if you can disable the ligatures.

**Comment by REmerald** [comment]
@9mm JetBrainsMonoNL version doesn't have ligatures. It is in the nerd font package as well.

**Comment by 9mm** [comment]
@REmerald thanks... im actually glad i was forced to use these ligatures because now I love them. There are 1 or 2 I don't care for, like `!=` but overall, they're awesome now 😎

**Comment by fredizzimo** [comment]
Font feature support was added, so you can now disable ligatures using that for fonts that support it.
* https://github.com/neovide/neovide/pull/2213

But it appears like some fonts like Hack does not support it, so we likely still need a font specific option of our own, which is now possible to add due to our config file. I don't think it can be a global option, since that would break rendering of some scripts that require ligatures.

**Comment by fredizzimo** [comment]
Hm.. my comment about the Hack font seems to be wrong. That font does not even support ligatures at all https://github.com/source-foundry/Hack, but there are some feature requests for it, and I was just going with what @sisrfeng said.

Are there any examples of a font that doesn't provide an official alternative, either through an alternative font name or font features? If not, I'm going to close this issue.

**Comment by fredizzimo** [comment]
If anyone is wondering, then the correct way to disable the ligatures for `FiraCode` is
```toml
[font.features]
"FiraCode Nerd Font" = ["-calt"]
```

And there are some talks in the issue list to make it more fine grained.

**Comment by erlangparasu** [comment]
Any updates?

**Comment by fredizzimo** [comment]
@erlangparasu 

I wrote this a couple of months ago? From my perspective there's nothing we need to do.
> Are there any examples of a font that doesn't provide an official alternative, either through an alternative font name or font features? If not, I'm going to close this issue.

**Comment by erlangparasu** [comment]
> @9mm JetBrainsMonoNL version doesn't have ligatures. It is in the nerd font package as well.

@fredizzimo u are right
I just tried using a font with the suffix NL, maybe it means "no ligatures" :D
`JetBrainsMonoNL` this works.

**Comment by fredizzimo** [comment]
I'm closing this for now, but it can be re-opened, if it turns out that some font can't be configured.

**Comment by ClaireCJS** [comment]
I think the ligatures are amazing, but I want to disable the "***" one, which raises the height of the middle asterisk.  That's the only one I don't like.  

So how would I do that? 😅

p.s. this thanksgiving be thankful there aren't emoji ligatures

**Comment by fredizzimo** [comment]
@ClaireCJS, 

That depends on the font. Some fonts can be configured, others can't. For example here's a feature request for FiraCode https://github.com/tonsky/FiraCode/issues/1461
