### ISSUE TITLE
Strip binary for reduce size

### ISSUE THREAD

**Issue by cathaysia** [neovide/neovide#1041]
Let's see it's size:

![图片](https://user-images.githubusercontent.com/42114817/140638210-aea717c1-71c2-4f00-ad32-7fee1c93a93e.png)

just run `strip neovide`

**Comment by Kethku** [comment]
I'd take a PR for this, but honestly its not a super high priority imho

**Comment by cathaysia** [comment]
understand, just a suggestion
________________________________
