### ISSUE TITLE
Animations don't update on a third party windows classic theme.

### ISSUE THREAD

**Issue by hgup** [neovide/neovide#1045]
**Describe the bug**
I love using Neovide. However, I wanted to use windows classic theme (don't ask me why, I just wanted to) on Windows 10.
And the animations don't update.
For example, when I press j or k to move up and down a line while editing a file. The display doesn't update unless you drag and drop the window. I think it may be because the windows classic theme disables some sort of animations but other apps seem to work correctly.
**It is not a very critical bug and immediate action is not required**

**To Reproduce**
1. Download the windows classic theme from this [Deviant Art User](https://www.deviantart.com/kizo2703/art/Windows-classic-theme-for-Windows-8-RTM-8-1-10-325642288)
2. Install it
3. Open Neovide and try using it.

**Expected behavior**
Animations are supposed to appear

**Screenshots**
Not applicable as animations are not shown on static images.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Neovide Version 0.8.0
 - Neovim Version 0.5.1

**Comment by Kethku** [comment]
This is very much not a supported use case. Apologies but without a PR, this isn't happening.
