### ISSUE TITLE
Remove cursor jump animation

### ISSUE THREAD

**Issue by aliaksei-karneyeu** [neovide/neovide#1048]
**Is your feature request related to a problem? Please describe.**
Cursor jumping animation distracts attention.

**Describe the solution you'd like**
Make option to disable completely animation.

**Describe alternatives you've considered**
N/A

**Comment by mxdevmanuel** [comment]
you can disable the animation by setting the animation legth to 0 

`g.neovide_cursor_animation_length = 0`

**Comment by mxdevmanuel** [comment]
You can disable the animation by setting the animation length to 0

`g.neovide_cursor_animation_length = 0`
