### ISSUE TITLE
A terminal based on this project?

### ISSUE THREAD

**Issue by jikkujose** [neovide/neovide#1049]
Is it feasible to use this as a base for building a terminal? It looks super snappy and having such an experience in the terminal may be cool

**Comment by PyGamer0** [comment]
> Is it feasible to use this as a base for building a terminal?

Should be possible. 

Related: #173

**Comment by Kethku** [comment]
Note: I currently run my terminal from inside neovide via the terminal command. It works great and gives nice text manipulation commands for selecting from the terminal history.

**Comment by Kethku** [comment]
However I think I'm going to close this as out of scope for now.
