### ISSUE TITLE
Window Scaling in Xmonad

### ISSUE THREAD

**Issue by nibirrayy** [neovide/neovide#1053]
I am running neovide with space vim on my laptop and I have tried everything that I can find on the internet regarding vim scaling from setting fonts heights to setting guifont but nothing works. I tested in two window manager Xmonad and openbox but no difference

![image](https://user-images.githubusercontent.com/12048453/142857924-e9d55fc0-e150-47ab-9f4a-483f256f579f.png)

I am attaching a screenshot to show the scaling issue I am having

my system:
  OS: arch linux
  WM: Xmonad, Openbox
  Resolution: 1920x1080

**Comment by dineshKumar777** [comment]
it would be helpful if you log bug as in issue template like adding logs, neovide version and all.
Could you share your guifont setting ?? 

I am also using arch with wayland(sway). I use following setting in my init.vim. 
```vim
if exists('g:neovide')
	"set guifont=DejaVu\ Sans\ Mono:h10
	set guifont=Hack\ NF:h10
en

**Comment by nibirrayy** [comment]
> 

Don't think it is going to help
Here is my nvim config

```
 Configuration for neovide
set guifont=MonoLisa\Nerd\Font:h8

" this file has all base sane settings
source $HOME/.config/nvim/settings.vim

" this loads the base-keymaps for vim
source $HOME/.config/nvim/keymappings/base-mappings.vim

" this file laod all plugins using vim-plug
source $HOME/.config/nvim/plugins/load-plug.vim

" sourcing vim-floaterm settings
source $HOME/.config/nvim/plugins/vim-floaterm.vim
" sourcing vim-floaterm keybindings
source $HOME/.config/nvim/keymappings/vim-floaterm.vim
```

I am using neovim and not vim can it be the problem? It it that it just loads vim config and not neovim config

**Comment by LoipesMas** [comment]
>`set guifont=MonoLisa\Nerd\Font:h8`
Shouldn't it be `set guifont=MonoLisa\ Nerd\ Font:h8`?
`\` used to escape the space. Or if there isn't a space between the words then just `set guifont=MonoLisaNerdFont:h8`.

**Comment by nibirrayy** [comment]
> > `set guifont=MonoLisa\Nerd\Font:h8`
> 
> Shouldn't it be `set guifont=MonoLisa\ Nerd\ Font:h8`? `\` used to escape the space. Or if there isn't a space between the words then just `set guifont=MonoLisaNerdFont:h8`.

Tried both 
```
set guifont=MonoLisaNerdFont:h8
```
and 
```
set guifont=MonoLisa\Nerd\Font:h8
```

No affect

**Comment by dineshKumar777** [comment]
Please try
set guifont=MonoLisa\ Nerd\ Font:h8 (backslash with space)

Or if you have nvim-qt installed in command line try set guifont=*
This will open font selector, and select your font. Then in commandline try :echo guifont which gives exact font config you can use.

 try with different system font also.

**Comment by nibirrayy** [comment]
I worked thanks closing the issue 

just summing up the issue
don't be stupid like me and use a \<space> to put spaces in the config
