### ISSUE TITLE
I Can't to Install neovide on Mac M1

### ISSUE THREAD

**Issue by ChenZhiYongA** [neovide/neovide#1054]
`
error: failed to run custom build command for `skia-bindings v0.45.0 (/Users/linnaishierhuachuan/rust-skia-0.45.0/skia-bindings)`

Caused by:
  process didn't exit successfully: `/Users/linnaishierhuachuan/rust-skia-0.45.0/target/release/build/skia-bindings-3931c54b55dfce9c/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-env-changed=SKIA_DEBUG
  cargo:rerun-if-env-changed=SKIA_SOURCE_DIR
  cargo:rerun-if-env-changed=FORCE_SKIA_BUILD
  cargo:rerun-if-env-changed=FORCE_SKIA_BINARIES_DOWNLOAD
  STARTING A FULL BUILD
  HOST: aarch64-apple-darwin
  cargo:rerun-if-env-changed=OPT_LEVEL
  cargo:rerun-if-env-changed=CC
  cargo:rerun-if-env-changed=CXX
  cargo:rerun-if-env-changed=SKIA_USE_SYSTEM_LIBRARIES
  cargo:rerun-if-env-changed=SDKROOT
  cargo:rerun-if-env-changed=MACOSX_DEPLOYMENT_TARGET
  cargo:rerun-if-env-changed=SKIA_NINJA_COMMAND
  cargo:rerun-if-env-changed=SKIA_GN_COMMAND
  Probing 'python'
  Python 2 found: "python"
  Synchronizing Skia dependencies

  --- stderr
  fatal: not a git repository (or any of the parent directories): .git
  thread 'main' panicked at '`git submodule update` failed', skia-bindings/build_support/binary_cache/download.rs:21:9
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
`

### I Try to Useing Evething In Github But I Can't Find The method that suits my computer

> macOS Monterey
> vserion 12.0.1

**Comment by dineshKumar777** [comment]
It would be helpful if you provide more info like as in issue template.
How did you try to get neovide. building from source or any installation package.
neovide version???

you can download executable directly from github actions page
https://github.com/neovide/neovide/actions/runs/1446953462

**Comment by ChenZhiYongA** [comment]
> 

thank you so much you help!  I think,I should try first.

**Comment by dineshKumar777** [comment]
> 
> I tried this, but when I download the executable and try to run I get a message saying `"Neovide.app" is damaged and can't be openend. You should eject the disk image."`
> 
> i've tried multiple builds, all say the same.

I never used mac device. so I am not be able to help on this. But you can try to build from source following these steps
https://github.com/neovide/neovide#mac-from-source

**Comment by ChenZhiYongA** [comment]
> 

me too , i try to install neovide.app But Also like this. Now, I try to build from source , i think we can together discuss.

**Comment by emielvangoor** [comment]
> > I tried this, but when I download the executable and try to run I get a message saying `"Neovide.app" is damaged and can't be openend. You should eject the disk image."`
> > i've tried multiple builds, all say the same.
> 
> I never used mac device. so I am not be able to help on this. But you can try to build from source following these steps https://github.com/neovide/neovide#mac-from-source

Thanks! This works just fine, i was able to build from source and run the executable (Apple Silicon version).

For me the problem is solved, but i think you will need to update the build action.

**Comment by cyz1901** [comment]
I think our compilation depends on  skia-binaries-5c96670703e06e64f6fd-aarch64-apple-darwin
However, This file does not exist in version 0.40.2.
https://github.com/rust-skia/skia-binaries/releases

I think we need to upgrade our dependency
neovide/Cargo.toml 57-63
```[target.'cfg(linux)'.dependencies.skia-safe]
features = ["gl", "egl"]
version = "^0.40.2"

[target.'cfg(not(linux))'.dependencies.skia-safe]
features = ["gl"]
version = "^0.40.2"```

**Comment by Sduby22** [comment]
> I think our compilation depends on skia-binaries-5c96670703e06e64f6fd-aarch64-apple-darwin However, This file does not exist in version 0.40.2. https://github.com/rust-skia/skia-binaries/releases
> 
> I think we need to upgrade our dependency neovide/Cargo.toml 57-63
> 
> ```
> features = ["gl", "egl"]
> version = "^0.40.2"
> 
> [target.'cfg(not(linux))'.dependencies.skia-safe]
> features = ["gl"]
> version = "^0.40.2"
> ```
> 
> I have successfully built it this way. 0.40.2 -> 0.42.1 (also cargo.lock I recommend using an IDE like idea so that it can be built automatically) If you encounter a timeout, you can change the network and try again several times.

I confirm this works. Successfully built on m1 mac air, Big Sur 11.4
