### ISSUE TITLE
neovide macOS --nofork flag issue

### ISSUE THREAD

**Issue by michalspano** [neovide/neovide#1055]
**Describe the bug**
`--nofork` flag issue - neovide gets detached from current terminal sesssion.

**To Reproduce**
1. Open __neovide__ through the console. 
```bash
$ nv --nofork foo.sh
```
Note: `nv` alias is set-up to automatically invoke the latest release in `.zshrc` / `.bashrc`
2. __neovide__ is not opened inside the console after using the `--nofork` flag, i.e. it gets detached from the current terminal session (default behaviour).

**Expected behavior**
Integrate NoeVide inside the console with the `--nofork` flag properly.
[](url)
**Screenshots**
None.

**Desktop (please complete the following information):**
 - OS: macOS 11.6.1 20G224 x86_64
 - Neovide Version 0.8.0

`.log`

```
TRACE [neovide] Neovide version: 0.8.0
```

**Comment by dineshKumar777** [comment]
some of the command line options are not working.
I think its related to this "bug command line options not working" #1004

**Comment by michalspano** [comment]
Still no update on this as of July 21st. I'd greatly appreciate an adequate support of this functionality. 🙂

**Comment by dineshKumar777** [comment]
@michalspano I think this is working now. Can you try with latest neovide version!!

**Comment by michalspano** [comment]
Still no luck in here. The process gets __detached__. I did build __neovide__ from the source - `Neovide 0.9.0` (to be exact).

OS: `macOS Monterey 12.4 (21F79)`

`neovide --log`:
```
TRACE [neovide] Neovide version: 0.9.0
```

Moreover, upon each call of __neovide__ from the command line, a new error message appears, linked [here](https://github.com/neovide/neovide/issues/1369).

**Comment by michalspano** [comment]
Even though these issues have (virtually) not that much in common, though they seem to be __platform specific__.

**Comment by sgoudham** [comment]
Hi, I've tested this on `macOS Monterey 12.3.1` and it looks to be working fine for me? 

However, the way that I've interpreted `--nofork` is that while a neovide window does open, the process is ultimately linked to the terminal. Neovide correctly quits for me when `Ctrl-c` is pressed in the terminal. I've just noticed that in the original issue, you mention that neovide doesn't open in the console. As far as I'm aware... that's not supposed to happen? 

Am I correct in my understanding?

**Comment by michalspano** [comment]
You are right, @sgoudham, I believe that's, indeed, the expected behavior. I must have mistunderstood the purpose of the __flag__. With that in mind, the `--nofork` flag works as 'expected'.

**Comment by michalspano** [comment]
I reckon adding a __more concise explanation__ of the __flag__ within `--help`, so that people won't get confused, like myself, in the future (and therefore avoid duplicated/unnecessary issues).

However, I feel certain that being able to embed __neovide__ directly into a __terminal session__ (just like regular `vim`/`nvim`) would be pretty cool (that's how I interpreted this __flag__ back then).

I haven't myself looked at the source, and thus cannot determine the feature's feasibility - it could be considered as an additional feature in the upcoming versions.

I'm closing the issue, thanks for every participation! 😃

**Comment by MultisampledNight** [comment]
Thank you! Embedding Neovide into a terminal emulator isn't really possible, as Neovide does its own drawing and window creation. Though I'll change the help text to something along the lines of

```
Depend on the shell process as parent process, and be "blocking". Not specifying this will spawn a child process and leak it
```

**Comment by michalspano** [comment]
Perfect, @MultisampledNight, that's a reasonable approach!
