### ISSUE TITLE
Can't exit fullscreen on MacOS

### ISSUE THREAD

**Issue by yanchenm** [neovide/neovide#1062]
**Describe the bug**
After entering full screen mode on Mac, the title/menu bar do not come back when you move the mouse to the top of the screen, leaving no way to exit full screen mode.

**To Reproduce**
1. Click the green full screen button in the top left corner of the title bar.
2. Move your mouse to the top of the screen.
3. Title bar and menu bar do not appear.

**Expected behavior**
When you move your mouse to the top of the screen, the title bar and MacOS menu bar should reappear, allowing you to exit full screen.

**Desktop (please complete the following information):**
 - OS: MacOS 12.0.1
 - Neovide Version 0.8.0
 - Neovim Version 0.5.1

**Comment by lethanix** [comment]
This was an issue in winit, it was solved and merged ([see here](https://github.com/rust-windowing/winit/pull/2053)). Nevertheless, neovide is using a fork of winit. 

One possible solution is to use the main branch of winit and create the necessary modules/crates from the fork. This could help distribute the work (i.e., the winit team could solve this kind of issues and more people could help out porting/creating the code needed from the fork).  Is this viable @Kethku ?

**Comment by darcyparker** [comment]
I have the same issue... but found :NeovideToggleFullscreen defined in #923 helps as a workaround.

**Comment by Kethku** [comment]
@lethanix unfortunately no. The fork of winit doesn't have any extractable components but rather is a combination of multiple still open PRs to winit which implement a new keyboard API. Those PRs are making slow but steady progress but don't have an eta for when they will be merged.

So the only real option we have is to recreate the fork on a more recent version of winit. This is a bunch of work that honestly I have mostly forgotten all the details for... So I have been putting it off until a show stopper bug arrives which forces me to do it :(

**Comment by worldwalker2000** [comment]
One work around I found is that if you hit the F3 key (Mission Control) and move your mouse up to the desktops bar and hover on neovide you will get a button to take it out of full screen.

**Comment by rrohrer** [comment]
Adding to this bug, the macOS Dock doesn't slide down like it's supposed to in fullscreen. Definitely not the end of the world, but would be nice if it worked correctly.

**Comment by spu95** [comment]
Cant also not see my commands, so neovide is breaking out of the bottom

**Comment by speelbarrow** [comment]
> This was an issue in winit, it was solved and merged ([see here](https://github.com/rust-windowing/winit/pull/2053)). Nevertheless, neovide is using a fork of winit.

The actual changes made in the PR don't interfere with [`neovide/winit@new-keyboard-all`](https://github.com/neovide/winit/tree/new-keyboard-all). I tested it, and cherry-picking the [merge-commit from the PR](https://github.com/rust-windowing/winit/commit/f2de8475fc4703d03a2ecc2cda627b017202e623) doesn't break anything while also providing the desired fixes. See below for the process I used to test this.

[![asciicast](https://asciinema.org/a/AcBw3yPZwkhOzCpxwFJpBOEon.svg)](https://asciinema.org/a/AcBw3yPZwkhOzCpxwFJpBOEon)

I'm going to go ahead and open a PR in `neovide/winit`, if it gets merged then this issue can be resolved.

**Comment by fredizzimo** [comment]
If @speelbarrow's fix fixes the issue Neovide 0.11.0 should also be fixed, since it uses a Winit version with the patch applied.

**Comment by speelbarrow** [comment]
@fredizzimo can I close the PR in that case?

**Comment by fredizzimo** [comment]
@speelbarrow

Yes, we don't use our own fork of winit anymore and no one has reported that this is a problem after 0.11.0.
