### ISSUE TITLE
Cursor movement auto-entering visual mode

### ISSUE THREAD

**Issue by kylechui** [neovide/neovide#1063]
**Describe the bug**
When the cursor hovers over the Neovide window (without left mouse button held), the cursor automatically moves to select text in visual mode, as if `set mouse=a` has been set and the left mouse button is being held down.

**To Reproduce**
1. Open Neovide.
2. Populate the buffer with some text, then hit `<Esc>` to enter normal mode.
3. Set the mouse option via `set mouse=n`.
4. Click and drag over an area in the Neovide window, then release.
5. Move the cursor around.
5. Observe the error.

**Expected behavior**
The selection stops, and the cursor is free to move around without affecting the buffer.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Neovide Version: 0.8
 - Neovim Version: 0.6

**Please run `neovide --log` and paste the contents of the `.log` file here:**
[neovide_rCURRENT.log](https://github.com/neovide/neovide/files/7644310/neovide_rCURRENT.log)

**Additional context**
After pressing `<Esc>`, the cursor reverts to normal mode and I expect that moving the cursor doesn't affect the buffer anymore. Instead the cursor goes back into visual mode without me clicking, and merely moving the cursor across the screen will change my cursor position and send me to visual mode.

**Comment by Kethku** [comment]
Fixed.

**Comment by DimitrisMilonopoulos** [comment]
@Kethku now I have to go back to neovide, goodbye kitty terminal!!!!

Tried the build as soon as I saw the message that the issue was closed. It's amazing how many bugs have been fixed for `Neovide` in the last few weeks. Thank you all for your contributions on this amazing Nvim client :D
