### ISSUE TITLE
vim.lsp.buf.hover() floating window goes outside the neovide window

### ISSUE THREAD

**Issue by Uefair** [neovide/neovide#1070]
**Describe the bug**

**To Reproduce**

1. Launch neovide with `--multigrid` option
2. Open hover doc(`lua vim.lsp.buf.hover()`) on function with huge doc, e.g. pcall in lua.
3. The floating window goes out of the neovide window.

**Expected behavior**
The floating window adjusts itself to fit in(like in neovim launched in terminal)

**Screenshots**
how it looks in terminal
![2021-12-05_18-12-1638719742](https://user-images.githubusercontent.com/62612309/144753807-c41c8f70-d554-405d-b238-b19dd523cc08.png)
and in neovide
![2021-12-05_18-12-1638719701](https://user-images.githubusercontent.com/62612309/144753814-f0305734-8126-4485-9f31-80e51df9f5e0.png)

**Desktop (please complete the following information):**
 - OS: Arch Linux with sway
 - Neovide Version 0.8.0
 - Neovim Version v0.7.0-dev+669-g76af219e3

**Please run `neovide --log` and paste the contents of the `.log` file here:**
[neovide_rCURRENT.log](https://github.com/neovide/neovide/files/7656299/neovide_rCURRENT.log)

**Additional context**
no additional context

**Comment by Uefair** [comment]
Solved the issue, many thanks, @LoipesMas!
![2021-12-09_21-12-1639073454](https://user-images.githubusercontent.com/62612309/145452417-44da0d77-8f4d-4a05-b97a-59d1359bf6b5.png)

**Comment by melkster** [comment]
I'm seeing the same issue now. I'm on Neovide version 0.10.1-1, and Neovim version v0.8.0-dev-1117-g7bd4c8e8e.

To reproduce:

```sh
neovide -- -u NONE -c "call nvim_open_win(0, v:true, {'width': 200, 'height': 10, 'relative': 'editor', 'row': 10, 'col': 70})" *path/to/any/file*
```

In this example the floating window ends up sticking out outside the right of the screen. If you have a larger screen (mine right now is 1080p) you can try increasing the `width`.
