### ISSUE TITLE
How to change font and change behavior of icon in neovide

### ISSUE THREAD

**Issue by HungPham3112** [neovide/neovide#1082]
![image](https://user-images.githubusercontent.com/75968004/145500532-6d08964e-3b16-4082-841b-448ba7963cf8.png)

I'm new with neovide and [icon](https://github.com/ryanoasis/vim-devicons) doesn't work and also I can't change the font to Nerd Font

**Comment by lethanix** [comment]
You might need to escape the space in the name of your font:
```
Cousine\ Nerd\ Font\ Mono:h11
```
or you can try the following in your init.vim : 
```
set guifont=Cousine\ Nerd\ Font\ Mono:h11
```

See [here](https://vim.fandom.com/wiki/Change_font).

**Comment by CadeMichael** [comment]
i'm trying to set this in lua with 
`vim.cmd([[set guifont=SauceCodePro\ Nerd\ Font:h11]])`
but I am getting the wrong font in neovide, the spacing is off and still only glyphs for icons. I am not sure if it is because I'm trying to finagle  vimscript into lua or if the font isn't being recognized.

**Comment by HungPham3112** [comment]
Thank you very much

**Comment by dineshKumar777** [comment]
Closing this.
