### ISSUE TITLE
Neovide does not change keyboard layout when the system keyboard layout gets changed, while neovide is open

### ISSUE THREAD

**Issue by tecbeast42** [neovide/neovide#1084]
**Describe the bug**
Open Neovide with e.g. the us keyboard layout. Change the keyboard layout to e.g. de. Neovide still behaves as if the keyboard is set to us. 

**To Reproduce**
use `setxkbmap us` to set to us layout
Open Neovide type 'y'
use `setxkbmap de` to set to de layout
type 'y' it will output 'z'

**Expected behavior**
Keyboard layout changes should apply to neovide.

**Desktop (please complete the following information):**
 - OS: Archlinux with X Server
 - 0.7.0.r227.g4131c50-1

**Please run `neovide --log` and paste the contents of the `.log` file here:**
No output from log

**Comment by Kethku** [comment]
Which version of neovide are you running? Is it from main?

**Comment by tecbeast42** [comment]
yes but i moved on

i have the same problem with

```
neovide -V
Neovide 0.8.0
```

**Comment by last-partizan** [comment]
What desktop environment are you using? Does it work for other apps, besides neovide?

I'm using Gnome, and it has option for per-window input switching.

**Comment by Shatur** [comment]
I have the same issue on KDE. I also use per-window input switching, but when switching to another app and switching the layout from US to, say, RU, after returning to Neovide, my system reports that I am using US (this is correct!), but Neovide has Russian input.

**Comment by tecbeast42** [comment]
I use bspwm on arch.

Neovide is the only app that has this problem on my system.

**Comment by Kethku** [comment]
This is likely a winit issue. I'm curious if its been fixed upstream

**Comment by Kethku** [comment]
A quick search doesn't show up anything...

**Comment by tecbeast42** [comment]
FYI this issue still persist. Should I open an Issue on winit? 

@Kethku not sure how certain you are that it is related to winit.

**Comment by MultisampledNight** [comment]
No, we use a fork of winit which is way behind upstream. You can try reproducing it with winits examples, however.

**Comment by Sinono3** [comment]
This happens to me as well on bspwm on Void Linux.

**Comment by coordinatio** [comment]
I also observe the same issue on Arch Linux with KDE and the recent neovide from git.

**Comment by Strongleong** [comment]
Arch linux with qtile. 
Nvim version: 0.7.0
Neovide version: 0.9.0
Same behavior.

Also I have plugin lyokha/vim-xkbswitch installed

**Comment by IWYpPtD49k1OHyy3AqwT9vOBJEaZ4S** [comment]
Same happens on NixOS Unstable with nvim 0.7.2 and neovide 0.9.0.

**Comment by TomLebeda** [comment]
Same behavior on Manjaro XFCE with nvim 0.7.2 and neovide 0.9.0-3

**Comment by Strongleong** [comment]
Any update on this? I am still have this error

**Comment by evenbrenden** [comment]
Same behavior using `setxkbmap` with `NVIM v0.8.1`, `neovide 0.10.3` and `X.Org version: 1.20.14`.

**Comment by fredizzimo** [comment]
We likely need to wait for https://github.com/rust-windowing/winit/issues/2678

**Comment by fredizzimo** [comment]
I don't think this is an issue on either Wayland and X11 anymore. At leas I have been able to toggle layouts correctly. But it would be good to a confirmation from others before closing.

**Comment by MultisampledNight** [comment]
Unable to reproduce it anymore either.

**Comment by tecbeast42** [comment]
I am not able to reproduce it anymore either :+1:
