### ISSUE TITLE
lazygit.nvim fails to find `lazygit`: "Please install lazygit."

### ISSUE THREAD

**Issue by luiz00martins** [neovide/neovide#1086]
**Describe the bug**
The [lazygit.nvim](https://github.com/kdheepak/lazygit.nvim) plugin finds the `lazygit` command in neovim terminal, but not in neovide, erroring out with `"Please install lazygit. Check documentation for more information."`

**To Reproduce**
1. Install [lazygit](https://github.com/jesseduffield/lazygit)
2. Install the [lazygit.nvim](https://github.com/kdheepak/lazygit.nvim) plugin
3. Open neovide
3. Run `:LazyGit`

**Expected behavior**
The lazygit terminal appears. Here's an example from the kitty terminal:
![Screenshot from 2021-12-10 21-24-57](https://user-images.githubusercontent.com/43142209/145656608-3ee0abe8-114a-472e-a303-b4402ac8150d.png)

In neovide, it fails to find the command:
![Screenshot from 2021-12-10 21-25-39](https://user-images.githubusercontent.com/43142209/145656797-66b326f9-5d19-4c36-a772-6b5ea123840b.png)

**Desktop:**
 - Pop!_OS 21.04
 - Neovide 0.8.0
 - Neovim v0.7.0-dev+688-g5abd7c2c1

**Please run `neovide --log` and paste the contents of the `.log` file here:**
No `.log` file is shown upon running `neovide --log`.

**Comment by cljoly** [comment]
It might be an issue with the `$PATH` being different from 1) your shell of choice and 2) your desktop environment. Have you tried starting neovide from kitty, as you would start `nvim`?

Also, with the latest commit of branch main, `neovide --log` does create a log file (that looks like neovide_r2021-12-12_12-54-19.log`) for me.

(FYI I’m not a neovide developer, just trying to help out as I faced a similar issue in the past with the `$PATH`)

**Comment by luiz00martins** [comment]
@cljoly Indeed, it created the log file at `$HOME`. I thought `--log` would open the file on `neovide` (◡‿◡;)

Your diagnosis is correct though, the `$PATH` is different, and launching from a terminal works fine. The problem happens when I launch from the `.desktop`.

Do you know how I can fix this problem? (i.e. launch from the `.desktop` but with the correct `$PATH`)

I'm currently using this `neovide.desktop`:
```
[Desktop Entry]
Name=Neovide
Comment=No Nonsense Neovim Client in Rust.
GenericName=Text Editor
Exec=/home/luiz00martins/Programs/neovide/target/release/neovide %f
Icon=/home/luiz00martins/Programs/neovide/assets/neovide-256x256.png
Type=Application
```

**Comment by cljoly** [comment]
I guess you could change the [global](https://wiki.archlinux.org/title/Environment_variables#Globally) variables or simply create a symlink to the `lazygit` binary in one of the folders already present in your `$PATH`. Finally, you could change your desktop file as outlined in https://askubuntu.com/a/144971

**Comment by luiz00martins** [comment]
Found out a solution that works in my case. I had put some of my `$PATH` settings in my `.bashrc`. I put them in my `.profile` instead, now `neovide` loads all of them.

Thanks a lot for your help!
