### ISSUE TITLE
Window 10 mouse problem on splited windows

### ISSUE THREAD

**Issue by okanakyuz** [neovide/neovide#1087]
**Describe the bug**
Today I pull from girt and build with cargo for getting fresh new release.
 But neovide could not manage the mouse on splitting windows.

**To Reproduce**
Steps to reproduce the behaviour:
1. Open newly built neovide on Windows 10 environment
2. : sp to split to window
3. Click the passive window on the screen  (It cant sense what i do with mouse)

**Expected behavior**
An active window should change when i click on

**Desktop (please complete the following information):**
 - OS: [Windows 10 Pro]
 - Neovide Version [Latest from source]
 - Neovim Version [v0.5.1 RelWithDebInfo build LuaJit 2.1.0-beta3]

**Please run `neovide --log` and paste the contents of the `.log` file here:**
I Attached as separate file 
[neovide_rCURRENT.log](https://github.com/neovide/neovide/files/7696728/neovide_rCURRENT.log)

**Comment by dineshKumar777** [comment]
@okanakyuz  its working fine for me.

did you enabled mouse in vim settings??
set mouse=a

**Comment by LoipesMas** [comment]
I think it's the same as [this](https://github.com/neovide/neovide/pull/979#issuecomment-988681502)

**Comment by dineshKumar777** [comment]
> I think it's the same as [this](https://github.com/neovide/neovide/pull/979#issuecomment-988681502)

Ok. so you enabled neovide with multigrid?? 

"It cant sense what i do with mouse"
- I thought mouse operations were not working completely with neovide.

**Comment by okanakyuz** [comment]
https://github.com/neovide/neovide/issues/1087#issuecomment-991619628

i set mouse .. It is working well.. Sorry guys..
