### ISSUE TITLE
Create a website

### ISSUE THREAD

**Issue by Kethku** [neovide/neovide#1089]
This issue is to discuss pros and cons for building a website and what it might contain.

Some pros:
- Can make a slick landing page which sells the key ideas behind neovide
- Simple easy to read place for FAQs and initial setup instructions
- Feels more official

Some cons:
- Extra thing to maintain
- Not clear what it gives over just improving the existing readme
- Requires somebody with experience to design it

I personally don't have much opinion either way other than that I don't feel confident I could design something better than what we already have, so this is sorta up to whoever wants to take it on.

**Comment by dineshKumar777** [comment]
This we can do. It will be most likely a static website so maintaining won't be that hard once project got stabilized.
Also you don't need to do maintain both Readme and website contents. We can parse contents from Github markdown automatically.

**Comment by cljoly** [comment]
> We can parse contents from Github markdown automatically.

In case you don’t already have a tool in mind @dineshKumar777, I use [RISS][] to reuse a Readme on a static website.

*disclaimer*: I wrote RISS

[RISS]: https://cj.rs/readme-in-static-site/

**Comment by cljoly** [comment]
Also, this may be a good theme (even though I haven’t used Zola much): https://juice.huhu.io/

**Comment by Kethku** [comment]
I have used and really like Zola. Good find

**Comment by cljoly** [comment]
I’ve put together a website in a subdirectory [on this branch](https://github.com/cljoly/neovide/tree/site). There may be some rough edges still, but this should give an idea of a possible way forward on this. The way it is set up, update to images in assets and README.md should be propagated automatically.

Let me know if you want me to open a PR to discuss this further.

![image](https://user-images.githubusercontent.com/7347374/147296543-e5202948-c7f3-4b8b-9974-6de00d31755a.png)

![image](https://user-images.githubusercontent.com/7347374/147296570-ced2eb7c-da7d-4a3d-ab4b-f00ceb23c48d.png)

**Comment by PyGamer0** [comment]
That looks amazing

**Comment by cljoly** [comment]
Thanks, I’ll try to finish documenting the code and to make a PR over the weekend.

**Comment by cljoly** [comment]
I’ve made the PR, we can of course further refine the website look and content, but hopefully that’ll be a starting point.
