### ISSUE TITLE
0.6 mouse issues 

### ISSUE THREAD

**Issue by Kethku** [neovide/neovide#1091]
Neovide has extensive hacks in place to work around a series of bugs in neovim 0.5 with regards to mouse positioning when multigrid is enabled. I believe most of the issues have been fixed in 0.6, so we need to update the readme to specify a new minimum version, and remove the hacks. Should mostly be deleting code.

**Comment by DimitrisMilonopoulos** [comment]
Hey @Kethku, could this https://github.com/neovide/neovide/issues/1063 be related to the hacks for 0.5?

**Comment by Kethku** [comment]
It is possible that these are related. Not sure.

**Comment by Kethku** [comment]
This is fixed.
