### ISSUE TITLE
AARCH64 version?

### ISSUE THREAD

**Issue by realtica** [neovide/neovide#1094]
ARMv7 it's ok too.

**Comment by realtica** [comment]
OS: Debian GNU/Linux 10 (buster) aarch64 
Host: Raspberry Pi 4 Model B Rev 1.4 

I trying to install and I got this error:
E: Package 'gcc-multilib' has no installation candidate
E: Unable to locate package g++-multilib
E: Couldn't find any package by regex 'g++-multilib'

**Comment by Kethku** [comment]
This is not a supported platform. If somebody wants to push this forward, thatd be fine, but its very much not high priority.

**Comment by Kethku** [comment]
Closing as out of scope. If somebody wants to push this, please reopen

**Comment by fredizzimo** [comment]
I’m reopening this to investigate if we can produce m1 builds for macOS in our CI.

I think the other platforms are out of scope,  but newer macbooks should not be.

**Comment by breneser** [comment]
Maybe I didn't explain it very well. I wasn't really installing on macOS but in a linux VM ( Manjaro aarch64 ) that was installed on macOS.

**Comment by fredizzimo** [comment]
In that case I think it's out of scope, at least until there are other laptops with those chips.

Asahi Linux uses the Arm packages of arch linux https://archlinuxarm.org/packages. And since Arch Linux already has a neovide package, I think the right route here is to ask the maintainers to provde arm packages for it as well.

What we can do, is to help fixing any issues with the code if there are any.

**Comment by Kethku** [comment]
Ya I agree. We don't have a way to have an arm Linux build machine so there's not really anything we can do

**Comment by fredizzimo** [comment]
I'm closing this again. But feel free to new issues for any bugs you encounter when running or building from source yourself. At least if the base system is Linux, macOS or Windows, with a reasonable modern and powerful hardware (GPU), raspberry PI is probably not powerful enough.

We won't promise anything, but if there's something simple, we can probably help with getting it up and running.

**Comment by ZerdoX-x** [comment]
Neovide itself doesn't have any limitations on AArch64 and 16K pages, I can install it on Asahi Linux just by running `cargo install --git https://github.com/neovide/neovide`, rust compiles it and all dependencies with no problem.

I didn't really get it. Is this [the problem](https://github.com/actions/runner-images/issues/5631)?
I also found actuated with their blog post: https://actuated.dev/blog/native-arm64-for-github-actions
Not sure which pricing do they have. They mentioned alternatives like VM and some other providers.

> In that case I think it's out of scope, at least until there are other laptops with those chips.

But there are more laptops and devices except Raspberry Pi and M1/M2 chips afaik.. Like:
Chromebooks, Pinebook, other linux and windows arm64 laptops?
https://www.pine64.org/pinebook-pro/
https://www.xda-developers.com/best-windows-on-arm/

Please let me know what you think :)

**Comment by breneser** [comment]
@ZerdoX-x It really isn't a neovide issue. Normally I would be able to build using the arch page or just do `cargo install --git https://github.com/neovide/neovide` as you suggested. The company policy just blocks some dependency urls. So it fails to download https://static.crates.io/crates/libloading/libloading-0.8.0.crate?_sm_nck=1 when I install with arch package or cargo install. 

I will find a way to work around it. Thanks for all the help though, I just opened it in the hopes of getting the discussion going to see if it is an easy solution on Neovide's side. 

I might go ahead and try and maintain my first arch package, will see how it goes :) Appreciate the help
