### ISSUE TITLE
Neovide opens in a black window, errors out on every keypress

### ISSUE THREAD

**Issue by tralph3** [neovide/neovide#1095]
**Describe the bug**
I just installed Neovide both on my notebook and my desktop. On both systems it behaves exactly the same. I open up the program and I'm greeted with a black window, I can't type anything, except commands, and every keypress throws errors in the terminal: 

https://user-images.githubusercontent.com/41462117/146061037-2eb36c4d-bd0b-44d1-b7af-c55a73ec7809.mp4

The whole time in that video I was pressing keys. Every error you see in the terminal was appearing each time I pressed a key on my keyboard. Here's a transcript of the errror:

    ERROR [neovide::error_handling] Could not parse event from neovim: invalid event format
    thread 'tokio-runtime-worker' panicked at 'Could not parse event from neovim: invalid event format', src/error_handling.rs:5:5

I've tried the `neovide-bin` package from the aur, as well as `neovide`, both behave the exact same on both systems, completely broken.

**To Reproduce**
1. Install neovide
2. ???
3. Profit

**Expected behavior**
Neovide working normally

**Desktop (please complete the following information):**
 - OS: Arch Linux 5.15.7-arch1-1
-  Neovide 0.7.0
 - Neovim 0.6.0

**Please run `neovide --log` and paste the contents of the `.log` file here:**

    Ignored client type property: "methods"
    Ignored client type property: "attributes"
    ERROR [neovide::error_handling] Could not parse event from neovim: invalid event format
    thread 'tokio-runtime-worker' panicked at 'Could not parse event from neovim: invalid event format', src/error_handling.rs:5:5
    note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Additional context**
These are the specs on both of my system:

### Notebook
* Intel i5 3320m
* Intel HD 4000
* 8GB RAM

### Desktop
* Ryzen 5 3400G
* Vega 11
* 16GB RAM

Both systems are running the same version of Arch with mostly the same packages. AMD system is using open source drivers.

**Comment by paul0258** [comment]
Also getting this on Manjaro with an Intel i7-4700MQ and a NVIDIA GeForce GTX 780M. I believe I am up to date as well.

**Comment by Herschenglime** [comment]
Also getting this on Manjaro with an Intel i7-4700MQ and a NVIDIA GeForce GTX 780M. I believe I am up to date as well.

**Comment by dineshKumar777** [comment]
@tralph3 Can  you try building from source since you are using old version of neovide(latest 0.8.0)

**Comment by tralph3** [comment]
I said I did try the `neovide` package, which builds from source. Still the same.

**Comment by tralph3** [comment]
Well, the git package seems to be working fine. I guess the other AUR packages need to be updated then.

**Comment by tralph3** [comment]
Oh, and by the way, the neovide git package should get the version number updated: https://i.imgur.com/2wjRlhB.png

**Comment by deisi** [comment]
I have the same on Ubuntu 20.04 I use latest release binary from github and nvim

```
NVIM v0.6.1
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by team+vim@tracker.debian.org
```

**Comment by tralph3** [comment]
You have to compile it from git, the latest release has this issue.

**Comment by deisi** [comment]
Ah okay, then I just wait until there is a new release binary. Thx for the info.

**Comment by Kethku** [comment]
The release binaries are taken from https://github.com/neovide/neovide/actions so you can get a build now if you like
