### ISSUE TITLE
How to contribute to the wiki?

### ISSUE THREAD

**Issue by adrianoviana87** [neovide/neovide#1098]
Not a bug. I just edited the wiki repository and I'd like to push the changes back by creating a PR or something.

**Comment by PyGamer0** [comment]
You directly edit the wiki (there is an edit button), no need to create a fork.

**Comment by Kethku** [comment]
Is it open permissions? Wild if so

**Comment by PyGamer0** [comment]
Hm I think all wikis are editable by anyone
