### ISSUE TITLE
Can not paste anything in neovide from another apps

### ISSUE THREAD

**Issue by balroggg** [neovide/neovide#1106]
**Describe the bug**

Can not paste anything in neovide from another apps

**To Reproduce**

1. Open neovide
2. Try to paste with combination `Ctrl-Shift-V`
3. Insert mode show `^V` and then for example press `Right` insert `<Right>`

**Expected behavior**
Text is copied to editor

**Screenshots**

**Desktop (please complete the following information):**
 - OS: ArchLinux, Wayland, Sway
 - Neovide Version 0.8.0 (aur)
 - Neovide Version 0.8.0 (f563360735c00eef2e197102901d75393ba554e1)

**Please run `neovide --log` and paste the contents of the `.log` file here:**
No output at all

**Additional context**
Just try to copy/paste text from another app

**Comment by Kethku** [comment]
this is working as intended.

https://vi.stackexchange.com/questions/84/how-can-i-copy-text-to-the-system-clipboard-from-vim

**Comment by balroggg** [comment]
I think you don't understand me or I describe problem in a wrong way.

I try to insert some text from system clipboard in insert mode, not by paste command from star or plus register(if I right).

Overall I expecting same behaviour like in other app or situation. On my system it's working perfectly, insert copy text from nvim to nvim, alacritty to nvim or etc.

**Comment by LoipesMas** [comment]
AFAIK `Ctrl-Shift-V` is a terminal shortcut for pasting. Neovide doesn't have such shortcut, because you configure your "shortcuts" by configuring your nvim mappings. You can do `:inoremap <C-v> ^R+` to paste your clipboard in input mode on `Ctrl-v`. You probably also can do middle mouse click (not sure if this works on wayland, but it should), but this pastes primary clipboard which sometimes isn't what you expect it to be.
When you say *"insert copy text from nvim to nvim, alacritty to nvim or etc"* you mean nvim in terminal, right?

**Comment by balroggg** [comment]
Yes, copy text from nvim in alacritty to nvim in gnome-terminal for example or insert by middle mouse click work too.

**Comment by balroggg** [comment]
I'm just curious how you work with copy/paste text, by clipboard manager maybe or something else?

**Comment by LoipesMas** [comment]
I don't do much copypasting between neovide and other apps. If I do, I do `"+p`/`^R+`/middle click, whichever feels closer at the moment.

**Comment by balroggg** [comment]
What I found in neovide from current master 
```
:checkhealth
No optional provider
Clipboard registers ("+ and "*) will not work.

:reg
...
clipboard: No provider
clipboard: No provider
...
```

**Comment by LoipesMas** [comment]
Do you have `wl-clipboard` installed?

**Comment by balroggg** [comment]
No. Copy/paste works for me in all apps I think, `firefox->gedit`, `alacritty->alacritty` for example.
`wl-clipboard` is need to save clipboard text, after app is closed, maybe. I just want only base behavior :)

From nvim docs:
```
==============================================================================
Paste                                                   provider-paste paste

"Paste" is a separate concept from clipboard: paste means "dump a bunch of
text to the editor", whereas clipboard provides features like quote-+ to get
and set the OS clipboard directly.  For example, middle-click or CTRL-SHIFT-v
(macOS: CMD-v) in your terminal is "paste", not "clipboard": the terminal
application (Nvim) just gets a stream of text, it does not interact with the
clipboard directly.
 
                                                        ui-paste
GUIs can paste by calling nvim_paste().
```

**Comment by LoipesMas** [comment]
Didn't know that it's separate like that.
Then, yes, neovide doesn't have that functionality. Not sure if it should be added, since you can paste with other methods. But it shouldn't be too hard to add.
