### ISSUE TITLE
Having a issue when trying to install Neovide

### ISSUE THREAD

**Issue by ayushtheprogrammer** [neovide/neovide#1108]
**Describe the bug**
when i was bulid neovide form source i encountered the error which was 

 Compiling skia-bindings v0.42.1
error: failed to run custom build command for `skia-bindings v0.42.1`

Caused by:
  process didn't exit successfully: `F:\Software\neovide\target\release\build\skia-bindings-f2211e07b6c1bb9e\build-script-build` (exit code: 101)
  --- stdout
  cargo:rerun-if-env-changed=SKIA_DEBUG
  cargo:rerun-if-env-changed=SKIA_SOURCE_DIR
  cargo:rerun-if-env-changed=FORCE_SKIA_BUILD
  cargo:rerun-if-env-changed=FORCE_SKIA_BINARIES_DOWNLOAD
  TRYING TO DOWNLOAD AND INSTALL SKIA BINARIES: 0.42.1/8b53a6e3e746b7456997-x86_64-pc-windows-msvc-gl
  cargo:rerun-if-env-changed=SKIA_BINARIES_URL
    FROM: https://github.com/rust-skia/skia-binaries/releases/download/0.42.1/skia-binaries-8b53a6e3e746b7456997-x86_64-pc-windows-msvc-gl.tar.gz
  DOWNLOAD AND INSTALL FAILED: https://github.com/rust-skia/skia-binaries/releases/download/0.42.1/skia-binaries-8b53a6e3e746b7456997-x86_64-pc-windows-msvc-gl.tar.gz: Dns Failed: No such host is known. (os error 11001)
  STARTING A FULL BUILD
  HOST: x86_64-pc-windows-msvc
  cargo:rerun-if-env-changed=OPT_LEVEL
  cargo:rerun-if-env-changed=CC
  cargo:rerun-if-env-changed=CXX
  cargo:rerun-if-env-changed=SKIA_USE_SYSTEM_LIBRARIES
  cargo:rerun-if-env-changed=SDKROOT
  cargo:rerun-if-env-changed=VCINSTALLDIR
  cargo:rerun-if-env-changed=LLVM_HOME
  cargo:rerun-if-env-changed=USERPROFILE
  cargo:rerun-if-env-changed=SKIA_NINJA_COMMAND
  cargo:rerun-if-env-changed=SKIA_GN_COMMAND
  Probing 'python'
  Probing 'python2'

  --- stderr
  Checking for "C:\\Program Files\\LLVM\\bin\\clang-cl.exe"
  thread 'main' panicked at '>>>>> Probing for Python 2 failed, please make sure that it's available in PATH, probed executables are: ["python", "python2"] <<<<<', C:\Users\Ayush\.cargo\registry\src\github.com-1ecc6299db9ec823\skia-bindings-0.42.1\build_support\skia\config.rs:410:9
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

i didn't pasted the other compling statements coz is just useless i geuss 

**Expected behavior**
I want it to install correctly because i have the visual studio 2019 c++

**Desktop (please complete the following information):**
![snio jpg](https://user-images.githubusercontent.com/89779084/147411116-96a30ed4-bb9c-48bf-92a6-efe4fc430af1.png)

 - OS: Windows 10 home 
 - Neovide Version = latest because i was building it form source
 - Neovim Version [e.g. 0.6.0]

**Comment by ayushtheprogrammer** [comment]
If anyone know how to solve it then it would be grateful to get the solution

**Comment by SyedAhkam** [comment]
From what I understand:

1. Skia build script attempts to download skia binary through the link specified.
2. A `Dns Failed: No such host is known. (os error 11001)` occurs right then. Which might indicate a lack of internet connectivity?
3. When that fails, It resorts to building the binary locally.
4. Which depends on a clang compiler + a python installation as mentioned on their README (which it cannot find).

Possible solutions:

- Try and visit the [download link](https://github.com/rust-skia/skia-binaries/releases/download/0.42.1/skia-binaries-8b53a6e3e746b7456997-x86_64-pc-windows-msvc-gl.tar.gz) manually using a browser and check if that's working. If it works, it is not an issue with your internet/DNS configuration.
- Install clang + python2 (with them being in your PATH variable) and try compiling again.

Besides, this is not an issue with neovide itself. But with [skia-bindings](https://github.com/rust-skia/skia-binaries) instead.

**Comment by Kethku** [comment]
This matches my understanding as well. Thanks for the summary

**Comment by Kethku** [comment]
I'm going to close this as an upstream issue/connection problem. But feel free to reopen if you want more help
