### ISSUE TITLE
Scoop | Update version for scoop package manager

### ISSUE THREAD

**Issue by Aukstkalnis** [neovide/neovide#1109]
**Describe the bug**
When installing neovide with scoop install neovide, 0.5.0 version is installed, but 0.7.0 already is released.

**To Reproduce**
1. Use windows 10 machine.
2. Install scoop
3. In terminal execute command "scoop install neovide"
4. Installed version is 0.5.0

**Expected behavior**
Scoop should install 0.7.0 version

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Neovide Version [e.g. 0.5.0]
 - Neovim Version [e.g. 0.6.0]

**Comment by fredizzimo** [comment]
The latest version seems to be available on Scoop now.
