### ISSUE TITLE
release binary not working as intended

### ISSUE THREAD

**Issue by Vaimer9** [neovide/neovide#1110]
![image](https://user-images.githubusercontent.com/81609819/147663814-d885ec59-a021-4f66-999c-3eb4ae68f60c.png)

**Comment by SyedAhkam** [comment]
Mind telling us how did you install it?

**Comment by Vaimer9** [comment]
I had install used the binary provided in the release page

**Comment by SyedAhkam** [comment]
Try to install libsndio 6.1/compat version using your distro's package manager. I believe I also had this issue and fixed it this way.

If you're on arch:
```sh
yay -S libsndio-61-compat
```

**Comment by Vaimer9** [comment]
Im using ubuntu, and `libsndio-61-compat` isn't available on aptitude

**Comment by imansour12** [comment]
compile it from source and try again
