### ISSUE TITLE
Enable Multigrid from vimscript

### ISSUE THREAD

**Issue by Lite5h4dow** [neovide/neovide#1113]
**Is your feature request related to a problem? Please describe.**
I am very much against setting global variables for individual programs outside of docker.

**Describe the solution you'd like**
It would possibly be better to be able to set things like multigrid from vimscript like font,opacity and so on.

**Comment by LoipesMas** [comment]
I think it's currently not possible because things like multigrid need to be set before the start of neovide and can't be changed on the fly (or at least without restarting neovide).
Maybe a config file for neovide would be a good solution?

**Comment by Lite5h4dow** [comment]
i would definately be amicable to a config script. i was hoping that there would be one by now but it seems to have been ignored till now

**Comment by PyGamer0** [comment]
Pretty sure multiGrid is enabled by default now?

**Comment by Kethku** [comment]
multigrid can not be configured via vimscript as stated above. So far we have avoided a config file as there aren't THAT many changes that require it that can't be configured from vimscript. As @PyGamer0 has mentioned, multigrid is enabled by default in current main (or should be) so this is a non issue. Further multigrid can also be disabled by an environment variable which is simpler than having a dedicated config file.

Idk a config file likely wouldn't cause problems, but I sort of don't really understand the desire for one especially when most features can be enabled in vimscript. I'm probably missing something?

**Comment by Kethku** [comment]
Closing as this issue has been described elsewhere
