### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by afdsgihfjl** [neovide/neovide#1115]
when I start nvide from the exe file I don't have any error but when I try to start nvide from the path var I have this error showing up:
`ERROR [neovide::bridge] Cannot get neovim API info, either neovide is launched with an unknown command-line option or neovim version not supported!`

**Comment by afdsgihfjl** [comment]
I have neovim version: 0.6.1
and neovide version: 0.8.0

**Comment by dineshKumar777** [comment]
@afdsgihfjl I think this is resolved now. Can you get latest and retry again??

**Comment by Kethku** [comment]
Closing from no response.
