### ISSUE TITLE
Suspend Corruption

### ISSUE THREAD

**Issue by enderger** [neovide/neovide#1120]
**Describe the bug**
Although Neovide no longer crashes on suspend, it now shows garbage on waking (can be fixed by changing lines).

**To Reproduce**
1. Load Neovide Master
2. Put your computer into suspend (on Linux, `systemctl suspend`)
3. Wake the computer after a few seconds

**Expected behavior**
Neovide should refresh the screen on wake, preventing garbage from (I assume) unpreserved GPU memory)

**Screenshots**
![Screenshot from 2022-01-03 16 10 13](https://user-images.githubusercontent.com/36283171/147993540-8b8a66f3-27e1-49bb-ad6d-5e22098660a1.png)

**Desktop (please complete the following information):**
 - OS: Elementary OS 6.1
 - Neovide Version:0.8.0 (d220477)
 - Neovim Version: 0.7.0-dev

Please run `neovide --log` and paste the contents of the `.log` file here: given that the application is completely unaware of the corruption the log is not helpful here.

**Additional context**
Uncovered by the suspend crash fix.

**Comment by Kethku** [comment]
woah thats a very cool bug

**Comment by Kethku** [comment]
I have a plan for fixing this but due to some architecture issues it's not as easy as I first expected. So it's going to be a bit

**Comment by Kethku** [comment]
Okeydokey https://github.com/neovide/neovide/pull/1124 @enderger can you try this branch? This adds a refresh on the Winit resume event which I think should redraw the editor windows fixing the issue. I can't repro on my machine so I'll need you to try it out to verify if that worked or not.

**Comment by Kethku** [comment]
Actually this is a big enough improvement to the code that I just merged this. Closing for now, but please reopen if the issue persists.

**Comment by enderger** [comment]
Can confirm that it is fixed! Probably was driver dependent, given that other applications sometimes show temporary artifacts which go away after a few seconds upon waking).
