### ISSUE TITLE
Panicked:  Os { code: 21, kind: IsADirectory, message: "Is a directory" }

### ISSUE THREAD

**Issue by coderek** [neovide/neovide#1121]
**Describe the bug**
Whenever I quit neovide, the terminal show the error
```thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 21, kind: IsADirectory, message: "Is a directory" }', src/settings/window_geometry.rs:95:41 ```
It doesn't prevent me from using neovide, but i just think this should be fixed anyway.

**To Reproduce**
1. Clone neovide from this repo (36479dd) and build from source according readme
2. launch neovide from terminal `./target/release/neovide `
3. quit neovide using vim comment `:q`
4. the error jump out from the terminal which launched the neovide

**Expected behavior**
It shouldn't show any error.

**Screenshots**
![image](https://user-images.githubusercontent.com/2993834/148003269-f14faaae-f11c-43f4-8ac3-6d1773dab54d.png)

**Desktop (please complete the following information):**
 - OS: MacOS 11.5.1
 - Neovide Version: built from source commit  36479dd
 - Neovim Version: 0.5.0

**Please run `neovide --log` and paste the contents of the `.log` file here:**
Sorry, i can't find the .log file

**Additional context**
Run with `RUST_BACKTRACE=1`
neovide on  main is 📦 v0.8.0 via 🦀
❯ thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 21, kind: IsADirectory, message: "Is a directory" }', src/settings/window_geometry.rs:95:41                                                             01/ 4 10:44 Tue
stack backtrace:
   0: rust_begin_unwind
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:517:5
   1: core::panicking::panic_fmt
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/panicking.rs:100:14
   2: core::result::unwrap_failed
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/result.rs:1616:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/result.rs:1298:23
   4: neovide::settings::window_geometry::maybe_save_window_position
             at ./src/settings/window_geometry.rs:95:5
   5: neovide::window::create_window::{{closure}}
             at ./src/window/mod.rs:329:13
   6: <winit::platform_impl::platform::app_state::EventLoopHandler<T> as winit::platform_impl::platform::app_state::EventHandler>::handle_nonuser_event::{{closure}}
             at /Users/derekzeng/.cargo/git/checkouts/winit-cdba476763ae8f28/3b5462e/src/platform_impl/macos/app_state.rs:100:13
   7: winit::platform_impl::platform::app_state::EventLoopHandler<T>::with_callback
             at /Users/derekzeng/.cargo/git/checkouts/winit-cdba476763ae8f28/3b5462e/src/platform_impl/macos/app_state.rs:78:13
   8: <winit::platform_impl::platform::app_state::EventLoopHandler<T> as winit::platform_impl::platform::app_state::EventHandler>::handle_nonuser_event
             at /Users/derekzeng/.cargo/git/checkouts/winit-cdba476763ae8f28/3b5462e/src/platform_impl/macos/app_state.rs:99:9
   9: winit::platform_impl::platform::app_state::Handler::handle_nonuser_event
             at /Users/derekzeng/.cargo/git/checkouts/winit-cdba476763ae8f28/3b5462e/src/platform_impl/macos/app_state.rs:205:21
  10: winit::platform_impl::platform::app_state::AppState::cleared
             at /Users/derekzeng/.cargo/git/checkouts/winit-cdba476763ae8f28/3b5462e/src/platform_impl/macos/app_state.rs:382:13
  11: winit::platform_impl::platform::observer::control_flow_end_handler::{{closure}}
             at /Users/derekzeng/.cargo/git/checkouts/winit-cdba476763ae8f28/3b5462e/src/platform_impl/macos/observer.rs:180:21
  12: winit::platform_impl::platform::observer::control_flow_handler::{{closure}}
             at /Users/derekzeng/.cargo/git/checkouts/winit-cdba476763ae8f28/3b5462e/src/platform_impl/macos/observer.rs:142:57
  13: std::panicking::try::do_call
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:403:40
  14: std::panicking::try
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:367:19
  15: std::panic::catch_unwind
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panic.rs:133:14
  16: winit::platform_impl::platform::event_loop::stop_app_on_panic
             at /Users/derekzeng/.cargo/git/checkouts/winit-cdba476763ae8f28/3b5462e/src/platform_impl/macos/event_loop.rs:216:11
  17: winit::platform_impl::platform::observer::control_flow_handler
             at /Users/derekzeng/.cargo/git/checkouts/winit-cdba476763ae8f28/3b5462e/src/platform_impl/macos/observer.rs:142:5
  18: winit::platform_impl::platform::observer::control_flow_end_handler
             at /Users/derekzeng/.cargo/git/checkouts/winit-cdba476763ae8f28/3b5462e/src/platform_impl/macos/observer.rs:175:9
  19: <unknown>
  20: <unknown>
  21: <unknown>
  22: <unknown>
  23: <unknown>
  24: <unknown>
  25: <unknown>
  26: <unknown>
  27: <unknown>
  28: <unknown>
  29: <() as objc::message::MessageArguments>::invoke
             at /Users/derekzeng/.cargo/registry/src/github.com-1ecc6299db9ec823/objc-0.2.7/src/message/mod.rs:128:17
  30: objc::message::platform::send_unverified
             at /Users/derekzeng/.cargo/registry/src/github.com-1ecc6299db9ec823/objc-0.2.7/src/message/apple/mod.rs:27:9
  31: objc::message::send_message
             at /Users/derekzeng/.cargo/registry/src/github.com-1ecc6299db9ec823/objc-0.2.7/src/message/mod.rs:178:5
  32: winit::platform_impl::platform::event_loop::EventLoop<T>::run_return
             at /Users/derekzeng/.cargo/git/checkouts/winit-cdba476763ae8f28/3b5462e/src/platform_impl/macos/event_loop.rs:177:22
  33: winit::platform_impl::platform::event_loop::EventLoop<T>::run
             at /Users/derekzeng/.cargo/git/checkouts/winit-cdba476763ae8f28/3b5462e/src/platform_impl/macos/event_loop.rs:144:9
  34: winit::event_loop::EventLoop<T>::run
             at /Users/derekzeng/.cargo/git/checkouts/winit-cdba476763ae8f28/3b5462e/src/event_loop.rs:154:9
  35: neovide::window::create_window
             at ./src/window/mod.rs:326:5
  36: neovide::main
             at ./src/main.rs:176:5
  37: core::ops::function::FnOnce::call_once
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

**Comment by fredizzimo** [comment]
Please update to the latest, you are on an unfortunate version, where two conflicting pull requests caused issues, but were fixed again in https://github.com/neovide/neovide/pull/1112

**Comment by coderek** [comment]
Right, it's resolved. Thanks.
