### ISSUE TITLE
Font issues

### ISSUE THREAD

**Issue by Uefair** [neovide/neovide#1125]
**Describe the bug**
After compiling the neovide with [1116](https://github.com/neovide/neovide/pull/1116#issue-1092118434) included i started noticing several issues:
1. The height value(h11) before and now are not setting the font for the same size, it became noticeably bigger.
2. Trying to reduce the size to h10 makes the font utterly smaller and almost eyebleaching as in my case(768x1366 15" screen)
3. (and one weird) The bottom chars of [toggleterm](https://github.com/akinsho/toggleterm.nvim) popup became kinda compressed/shifted(see screenshot 1)

**To Reproduce**
1. Build latest neovide as of 2022.01.05
2. Set the font to monospaced one (tried with "DejaVu Sans Mono" and "JetBrainsMono Nerd Font Mono")
3. Set font size(height) to 11
4. Set font size to 10
5. See hugeness of font at h11 and littleness of h10

**Expected behavior**
1. Font is displayed with normal size
2. No font corruption in toggleterm

**Screenshots**
vim.o.guifont = [[JetBrainsMono Nerd Font Mono:h11]]
151 columns and 40 lines viewable
(notice font compression at bottom)
![2022-01-05_14-01-1641382721](https://user-images.githubusercontent.com/62612309/148212047-74a10247-c1b5-46b6-abc4-27a1318bf405.png)

vim.o.guifont = [[JetBrainsMono Nerd Font Mono:h10]]
170 columns and 43 lines viewable
(no font corruption for some reason)
![2022-01-05_14-01-1641382710](https://user-images.githubusercontent.com/62612309/148212060-d037be45-aa08-4166-9dcf-1d6b27028622.png)

vim.o.guifont = [[JetBrainsMono Nerd Font Mono:h11]]
170 columns and 42 lines viewable
commit 36479dd
(no font issues)
![2022-01-05_15-01-1641385212](https://user-images.githubusercontent.com/62612309/148216784-adf1c1ce-bde4-4fe0-82bb-3a274857a2ce.png)

**Desktop:**
 - OS: Arch Linux with sway
 - Neovide Version latest commit at master
 - Neovim Version v0.7.0-dev+835-gf65b0d423

**The `.log` file:**
[neovide_rCURRENT.log](https://github.com/neovide/neovide/files/7814633/neovide_rCURRENT.log)

**Additional context**
1. I had no issue with ligatures like [here](https://github.com/neovide/neovide/issues/1096), ligatures rendered properly
2. Setting font height to value between 10 and 11 is rounded (10.7< is floored to 10 >=10.7 is ceiled to 11)
3. Amount of lines/columns are checked through `:set lines columns`

**Comment by fredizzimo** [comment]
I also see a quite big size difference for that font, but it's consistent with other programs, like the windows notepad for example. The font is quite narrow, and since #1116 rounds to the nearest horizontal width, there's a quite big height difference. I don't see any corruption here either, so that could be 

![image](https://user-images.githubusercontent.com/9946255/148225337-32d7e848-3ef4-4542-ba8b-308af580315c.png)

I also tried WSLg, so running inside Linux through WSL, and there it looks like the height gets set to one pixel less, and it looks smaller and the proportions are wrong. The width stays the same. I will check what's going on there
![image](https://user-images.githubusercontent.com/9946255/148228504-d17a123f-0c5f-4d5e-8024-970c734065b9.png)

It's hard to tell if that's different from what you are seeing or not, since the resolution of the images are so low.

**Comment by fredizzimo** [comment]
For me the difference seems to be a slightly different version of nerd font installed. On Windows I have the latest git release and when uploading it to https://opentype.js.org/font-inspector.html, I can see the following in the horizontal header

ascender:  1020
descender:  -300

While on WSL I installed the Arch aur package nerd-fonts-complete, which is the latest release but almost two years old v2.1.0, and the values are the following
ascender:  980
descender: -240

Can you check those values for your version as well? And also verify that both those sizes renders correctly in other programs.

**Comment by Uefair** [comment]
opentype claims:
![2022-01-05_17-01-1641393471](https://user-images.githubusercontent.com/62612309/148235531-982f4721-f378-424c-9f82-e145bfd0c182.png)
Though the Ubuntu Nerd Font is used, the time i tried same jetbrains nerd font it had no issues, guess it's rendered correctly.
Do you still need the log files of new/old versions with different font sizes?

**Comment by Uefair** [comment]
[current h11.log](https://github.com/neovide/neovide/files/7815675/curH11.log)
[current h10.log](https://github.com/neovide/neovide/files/7815677/curH10.log)
[old h10.log](https://github.com/neovide/neovide/files/7815679/oldH10.log)
[old h11.log](https://github.com/neovide/neovide/files/7815680/oldH11.log)

**Comment by fredizzimo** [comment]
Those values seems to match the old 2.1.0 release of nerd fonts. They have increased the line spacing since then, so there's a good chance that the latest git version fixes the issues. However, it does not explain why it looks much worse on your system, than on mine, as you can see in my screenshots only the h10 version is slightly compressed.

I also checked your log files, and the numbers match the ones I got on the Linux system.

Can you take some more screenshots, comparing it to some other program, and crop the image so that github uploads the full resolution image?

**Comment by Uefair** [comment]
yeah, sure, would take some time
any special apps you'd like me to try? i suggest either kate or gedit

**Comment by fredizzimo** [comment]
Not really, you can try in a few, but if they are the same, you only need to take screenahots from one.

**Comment by Uefair** [comment]
(i see no artifacts)
* gedit
![gedit](https://user-images.githubusercontent.com/62612309/148240782-e10d1ca9-41f5-4e1f-8f54-1d222833167b.png)

(same here)
* kate
![kate](https://user-images.githubusercontent.com/62612309/148240938-7c6d9df4-32ba-4039-be60-054651497a41.png)

(same here, and that's what i didn't see at the beginning)
* neovide without multigrid
![neovide without multigrid](https://user-images.githubusercontent.com/62612309/148241650-dbd7686f-464b-4226-b5a9-421dfaaf79b6.png)

(and here the noise appears)
* neovide multigrid, the image is cropped from neovim launched inside toggleterm
![neovide multigrid, the image is cropped from neovim launched inside toggleterm](https://user-images.githubusercontent.com/62612309/148241869-81c30bb5-4ab2-4260-9305-b39cb6c8eec0.png)

**Comment by fredizzimo** [comment]
GEdit, seems to be smaller, but the rest seems to at least have the same size and line spacing. Is that the case for the h10 size as well?

So the font corruption only happens with multigrid? And I think all the screenshots have shown something from the built-in terminal, does it happen outside that as well?

**Comment by Uefair** [comment]
Size 10 still looks good in kate/gedit. Wanna mention that gedit have larger font size even though i set 10 in both(anyways that's not the point)

Characters are displayed correctly in the main window of neovim with multigrid, neither nvim-cmp, telescope, lspconfig have the issue. So yeah, guess it's multigrid's fault.

**Comment by fredizzimo** [comment]
I don't think there's anything wrong with the font sizes, I put your original screenshot next to mine (font size 10). And at least to my eyes it looks the same as the middle image, the WSLg version with the 2.1.0 version of Nerd Fonts. 

![image](https://user-images.githubusercontent.com/9946255/148257673-45c11148-1fbc-4374-aedc-fea4eed1cd1f.png)

After that, I have installed the latest git version of nerd-fonts inside WSL too, and now both the 10 and 11 sizes looks the same as Windows Notepad and other windows programs. So if you prefer the slightly bigger size 10, you can install the latest version.

I'm not sure if there are clarity issues or something else that makes the 10 version seem too small on your screen, but for me on my screen when I open your screenshot it looks good, and very easily readable.

I'm also able to reproduce something similar to the font corruption now. I was using a floating terminal before, but as soon as I tried the normal one there started to be problems. I ran `cat` on the logfile, and the output was completely messy. It looks like the screen was not cleared properly before outputting more characters. For examples, sometimes when scrolling by the mouse the right side of the screen stayed in place, while the the left side scrolled up, causing something like this 
![image](https://user-images.githubusercontent.com/9946255/148260976-4d80d0e4-e0bd-40bb-bb26-1cbc29aa5da1.png)

Obviously that's not exactly the same as you are seeing, but I think the two things are related.

**Comment by Uefair** [comment]
Did as you advised(last nerdfonts and h10), looks good now.
Thanks! closing the issue
