### ISSUE TITLE
fails to build (failed requirement: quote = =1.0.14)

### ISSUE THREAD

**Issue by eudoxos** [neovide/neovide#1126]
**Describe the bug**
A build from the fresh checkout of the main branch fails with:
```
$ cargo build --release
    Updating crates.io index
error: failed to select a version for the requirement `quote = "=1.0.14"`
candidate versions found which didn't match: 1.0.10, 1.0.9, 1.0.8, ...
location searched: crates.io index
required by package `neovide-derive v0.1.0 (/home/eudoxos/build/neovide/neovide-derive)`
```

**To Reproduce**
Following instruction to build [From source](https://github.com/neovide/neovide/#from-source-1), except of using package version of cargo and rustc (1.53.0), on Ubuntu 20.04.

**Expected behavior**
Build should succeed (it indeed did a few months back).

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04 
 - Neovide Version: aa340c5e41e1011c663ef0cfd6bd712e0e616c0f
 - Neovim Version: `v0.5.0-dev`

**Please run `neovide --log` and paste the contents of the `.log` file here:**
(does not run)

**Additional context**
Perhaps I am misunderstanding how cargo works. I can see quote 1.0.14 [at cargo.io](https://crates.io/crates/quote).

**Comment by fredizzimo** [comment]
Most likely your rust version is too old. Try uninstalling the Ubuntu version, and install the newest release through rustup instead.
