### ISSUE TITLE
Guifont W option

### ISSUE THREAD

**Issue by obmutescences** [neovide/neovide#1130]
like vscode: editor.letterSpacing to set char width
set guifont=CodeNewRoman\ Nerd\ Font:h15:b:w5 is not working.

**Comment by guolimin1995** [comment]
also set linespace=15 it`s not working.

**Comment by Kethku** [comment]
Line height customization is tracked here https://github.com/neovide/neovide/issues/481

Guifont does not support customizing the font width at the moment, but I would be happy to help somebody if they are interested in implementing the feature. Its not very high priority currently

**Comment by guolimin1995** [comment]
thanks for reply.

**Comment by fredizzimo** [comment]
Closing an favor of
* #2251
