### ISSUE TITLE
Add subpixel antialiasing option

### ISSUE THREAD

**Issue by Kethku** [neovide/neovide#1133]
Currently you can turn off antialiasing (haven't tested in a while. May not actually work) but you can't change what kind. Turns out on some systems subpixel antialiasing makes the text look significantly worse with gaps and such.

It would be good to give the user the option to pick which they prefer.

**Comment by jsosulski** [comment]
FWIW on my machine disabling Subpixel antialiasing produces lines that look "cut off" (I am using JetBrainsMono)

Without Subpixel AA:
![disabled_subpixel](https://user-images.githubusercontent.com/2545339/148644438-58d48141-6a65-4340-b5ea-0cc8a0f1aeac.png)

With Subpixel AA:
![enabled_subpixel](https://user-images.githubusercontent.com/2545339/148644452-41799290-3fc1-4cef-abb9-73ebd594b28f.png)

**Comment by fredizzimo** [comment]
That's very strange, which operating system are you on, and do you have a high DPI display with some kind of scaling on?

**Comment by jsosulski** [comment]
I am on Ubuntu 20.04 with KDE Plasma using a 1440p 27" monitor. But I do have fractional scaling, i.e. 125%, activated. However, I just tried setting this to 100% and I still have the same issue, but only with the JetBrainsMono font. Changing my font to SourceCodePro fixes both issues, so maybe this is a font issue?

**Comment by fredizzimo** [comment]
Yes, I was just going to say that, I consider the version of JetBrainsMono included in the release 2.1.0, of Nerd fonts broken. The 2.1.0 release is the latest, but almost 2 years old, and JetBrainsMono 2.0 came out at around the same time. And there's a lot of fixes releated to height alignment and sizes https://github.com/JetBrains/JetBrainsMono/releases?page=1

The solution is to install the latest git release of Nerd fonts, which includes the latest version of JetBrainsMono. 

Also see this issue, with a similar discussion https://github.com/neovide/neovide/issues/1125.

**Comment by jsosulski** [comment]
I see, thanks for the heads up! I just updated my local fonts.

**Comment by fredizzimo** [comment]
We support 
* antialias (default)
* subpixelantialias
* alias

now, and as far as I'm aware they work properly and the fonts are crisp
