### ISSUE TITLE
Control key stuck when change workspace

### ISSUE THREAD

**Issue by keigon** [neovide/neovide#1142]
**Describe the bug**
I am using Archcraft + BSPWM, and I change between my workspace with CTRL+ALT+<Left arrow, Right Arrow>
When Neovide open and change my workspace with CTRL+ALT+<Left Arrow, Right Arrow>, and come back to Neovide, CTRL key is stuck. Every key stroke is acting like CTRL is pressed. There is no way to release CTRL..

**To Reproduce**
1. Open Neovide
2. Change workspace(window) focus with CTRL + ALT + ARROW KEY, Neovide recognize CTRL key pressed, but not released.
3. Come back window focus into Neovide, and Neovide recognize EVERY KEY STROKE with PRESSED CTRL key

**Expected behavior**
Recognize key stroke normally.

**Desktop (please complete the following information):**
 - OS: Archcraft + BSPWM
 - Neovide Version 0.6.0
 - Neovim Version 0.5.0

**Additional context**
 When I using Super key to change focus, It behaves normally and Neovim in terminal has no problem.

**Comment by fredizzimo** [comment]
This looks like a variation of https://github.com/neovide/neovide/issues/958, but not exactly the same.

**Comment by Kethku** [comment]
Interesting. So might be fixed with a new new-keyboard fork

**Comment by fredizzimo** [comment]
Yes, I think that will happen quite soon. As far as I understand, they will first check the new rebased Windows version and merge that, then they will rebase the other ones on top of it. The Linux version has a comment on the bottom saying it's essentially ready, but I'm not sure about the Mac one.

If they don't merge the other platforms yet, I guess we should just rebuild our fork on top of the new rebased windows version.

**Comment by Kethku** [comment]
Agreed. Sounds like a plan.

**Comment by last-partizan** [comment]
I think this is the same bug i was fixing in `fix-stuck-shift` branch, plese check it out.

**Comment by songww** [comment]
It works for me.

**Comment by last-partizan** [comment]
That's great, thanks for testing.

**Comment by stefanwatt** [comment]
I have the same issue on AwesomeWM and LeftWM. 

Also (not sure if related) on launch it doesn't take any keyboard commands until I change focus back and forth.

**Comment by shadyalfred** [comment]
Switching between apps using alt+tab tho doesn't have this weird behavior

**Comment by cacilhas** [comment]
I’m using i3 on ArchLinux, and I have the same issue: control gets stuck when switching between workspaces. It comes back to normal if I switch between windows in the same workspace though.

**Comment by fredizzimo** [comment]
I think that the new winit keyboard api might fix this https://github.com/neovide/neovide/pull/1789. Could you try again with the latest master?

**Comment by shadyalfred** [comment]
Is there a release for it or I'm gonna have to build it from source, @fredizzimo?

**Comment by fredizzimo** [comment]
We don't have a proper release, but the CI image produces some binaries that you should be able to use https://github.com/neovide/neovide/actions/runs/5272313380.

**Comment by shadyalfred** [comment]
I've tested it, and it seems that the problem has been fixed! Thanks a lot!
