### ISSUE TITLE
Setting colorscheme and font causes scaling issues on HiDPI setup

### ISSUE THREAD

**Issue by MultisampledNight** [neovide/neovide#1143]
**Describe the bug**

Neovide with an empty config, setting only `color` or only `guifont` behaves normally, while setting both (often) causes a blurred window like this if you don't resize it, also cmdline and tabline scaling are messed up while the cursor is not (see the comment later for an image).

A quite reliable init.vim would be
```vim
colo morning
set guifont=Source\ Code\ Pro:h11
```

**To Reproduce**
1. Put the stuff above in your init.vim
2. Launch neovide with `neovide --multigrid`
3. See issues

**Expected behavior**
To scale everything correctly. Surprisingly this can be done with `set guifont=&guifont` at runtime, which just re-sets the font.

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Neovide: Local build (0.8.0)
 - Neovim Version (0.6.1)

**Comment by fredizzimo** [comment]
The image does not work for me. Try uploading again, I usually just copy and paste here, and github handles the rest.

**Comment by Kethku** [comment]
![image](https://user-images.githubusercontent.com/3323631/149233684-416baf3b-e2ea-4908-8c13-55a8a422ee5b.png)

**Comment by Kethku** [comment]
^ from the discord. I think somehow the guifont is getting set late or something after the initial render, and the background window isn't getting redrawn, but thats just a guess.

**Comment by MultisampledNight** [comment]
Here is the logfile. I apologize for the delay.

[neovide_rCURRENT.log](https://github.com/neovide/neovide/files/7863812/neovide_rCURRENT.log)

**Comment by fredizzimo** [comment]
I quickly checked the log. There appears to be some text that’s shaped after the font is set, but before the scalefactor is updated. And it looks like that text is never shaped again. 

But I don’t know why, the scale factor update should reset the cache.

**Comment by fredizzimo** [comment]
And now I have quickly checked the code. I believe that we need to call `redraw_screen` when the scale factor is changed, like we do for setting the GUI font.

**Comment by Kethku** [comment]
You're a machine. That should be a very simple fix :)

**Comment by Kethku** [comment]
@MultisampledNight can you try from main? I believe this is fixed now
