### ISSUE TITLE
Uncouple multigrid and opacity

### ISSUE THREAD

**Issue by qeisar** [neovide/neovide#1147]
1. Is it possible to enable Multigrid but not the floating window transparency? The text becomes blurry. Setting `neovide_floating_opacity = 1 `doesn't seem to work for me.

2. How to set multigrid for the osx app? I can set an alias with --multigrid for CLI access. The instructions mention declaring an environment variable named "NEOVIDE_MULTIGRID" but how to do this for the osx app?

Awesome work! I am switching from vscode because of this beauty.

**Comment by LoipesMas** [comment]
1. What neovide version are you using? I think it's something that was fixed recently.

**Comment by qeisar** [comment]
Version 0.8.0 
I cloned the main and compiled it before writing this message. Here is a screenshot. The top one is Neovide; the below is neovim.

Maybe this is how it should look, but I would rather have it without transparency.
Either way, is it possible to enable the multigrid when I start Neovide from the osx app since it is disabled by default or now.

![image](https://user-images.githubusercontent.com/36160895/149584323-85909501-bc77-47bb-9158-11dcd6e98ebb.png)

**Comment by LoipesMas** [comment]
Then I don't know why setting opacity isn't working. Have you made sure that you are setting it correctly
 (`let g:neovide_floating_opacity=1` or lua equivalent)?
 As for the environment variable, you need to set it for the whole system (or a session to be precise). I don't use a Mac, so I don't know how it should be done, but I've seen something about `launchctl setenv`. But I'm not sure if you need to make it persistent somehow.

**Comment by qeisar** [comment]
Oh, I hope I am doing it wrong. I am using lua equivalent. Which I am not sure correct!
But I know the font is working correctly.

![image](https://user-images.githubusercontent.com/36160895/149586694-5bd9889d-5f75-49c2-b220-cf14e7696500.png)

**Comment by fredizzimo** [comment]
The settings should be named `vim.g.neovide_*`. But for some reason that does not seem to work for me. It correctly updates the variable and can be seen by `let g:neovide_*`, but neovide does not react to it.

**Comment by qeisar** [comment]
Phew! Now it is working with your lua suggested setting.
Many thanks :)

![image](https://user-images.githubusercontent.com/36160895/149589196-176cab21-b239-471b-9ae2-840bd9b0d1c3.png)

**Comment by caeu** [comment]
For those who can't wait for the multigrid option to come back as default and want to set it in a persistent way on macOs.

The below will run the startup, and this worked for me on Big Sur:

create a file inside `/Library/LaunchAgents/` and name it something relevant. e.g. `com.Neovide.set-multigrid.plist`
and paste this inside:
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>setenv.NEOVIDE_MULTIGRID</string>
  <key>ProgramArguments</key>
  <array>
    <string>sh</string>
    <string>-c</string>
    <string>launchctl setenv NEOVIDE_MULTIGRID 1</string>
  </array>
  <key>RunAtLoad</key>
  <true/>
  <key>KeepAlive</key>
  <true/>
</dict>
</plist>
```

The gist of it is when you login or restart, this will run `sh -c launchcetl setenv NEOVIDE_MULTIGRID 1`

Not sure if this is the best solution or if there are any risks, but it worked for me. You can check by calling `printenv` from terminal to see that the variable is set. If so, then multigrid should work when starting Neovide.app from finder or spotlight.
