### ISSUE TITLE
Support `:cquit`

### ISSUE THREAD

**Issue by statiolake** [neovide/neovide#1151]
**Is your feature request related to a problem? Please describe.**

I usually use Neovim to edit git commit messages. When I'm editing a commit message and want to stop the commit, I can use `:cq` to abort the commit with terminal Neovim, Neovim-qt and gvim.

**Describe the solution you'd like**

Set 1 as an exit status of Neovide when `:cquit`. It's better if `:2cq` or other exit status are supported, but I need simple `:cq` for now.

**Describe alternatives you've considered**

Any kind of method is OK as long as it can differenciate normal exit and abnormal exit.

**Comment by Kethku** [comment]
I have a fix in the works for this. It will take some time though because the exit code isn't surfaced easily on the gui side.

**Comment by Kethku** [comment]
Fixed in main.
