### ISSUE TITLE
Panic with `SDL_VIDEODRIVER=wayland` (Sway)

### ISSUE THREAD

**Issue by itaranto** [neovide/neovide#1153]
**Describe the bug**
Neovide panics when running with `SDL_VIDEODRIVER=wayland`.

**To Reproduce**
1. Run `neovide` from the terminal
2. See the error

**Expected behavior**
Neovide launches successfully.

**Desktop (please complete the following information):**
 - OS: Arch Linux with
 - DE/WM: Sway
 - Neovide Version 0.7.0
 - Neovim Version 0.6.1

The error message:

```sh
$ neovide
Ignored client type property: "methods"
Ignored client type property: "attributes"
thread 'main' panicked at 'Failed to create sdl video subsystem: "wayland not available"', src/window/sdl2/mod.rs:432:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by Kethku** [comment]
Please run from main. We have moved away from sdl

**Comment by itaranto** [comment]
> Please run from main. We have moved away from sdl

OK, good to know. Since I'm using the AUR I'm gonna try the `neovide-git` package.

Thanks.
