### ISSUE TITLE
[Linux] Alt+Tab switches from Insert mode to Normal

### ISSUE THREAD

**Issue by jonvaldes** [neovide/neovide#1154]
**Describe the bug**
On linux, pressing Alt+Tab while in Insert mode changes mode to Normal.
This does not happen on nvim in a terminal, or on neovide on Windows.

**To Reproduce**
1. Run neovide, press 'i' to enter Insert mode and type something
2. Press Alt+Tab
3. See neovide is now in normal mode

**Expected behavior**
Neovide should not switch modes when Alt-tabbing

**Desktop (please complete the following information):**
 - OS: Manjaro Linux, Cinnamon desktop environment
 - Neovide Version git main branch head
 - Neovim Version 0.6.1

Output in the log:
```
TRACE [neovide::channel_utils] ui_command Serial(Keyboard("<M-Tab>"))
TRACE [neovide::bridge::ui_commands] Keyboard Input Sent: <M-Tab>
TRACE [neovide::redraw_scheduler] Next frame queued
TRACE [neovide::redraw_scheduler] Next frame queued
TRACE [neovide::redraw_scheduler] Next frame queued
TRACE [neovide::channel_utils] ui_command Parallel(FocusLost)
TRACE [neovide::bridge::handler] Neovim notification: "redraw"
TRACE [neovide::bridge::handler] Neovim notification: "redraw"
TRACE [neovide::channel_utils] redraw_event GridLine { grid: 1, row: 48, column_start: 0, cells: [GridLineCell { text: " ", highlight_id: Some(126), repeat: None }, GridLineCell { text: "N", highlight_id: None, repeat: None }, GridLineCell { text: " ", highlight_id: None, repeat: None }, GridLineCell { text: "\u{e0b0}", highlight_id: Some(124), repeat: None }, GridLineCell { text: "\u{e0b0}", highlight_id: Some(134), repeat: None }, GridLineCell { text: " ", highlight_id: Some(145), repeat: None }, GridLineCell { text: "[", highlight_id: None, repeat: None }, GridLineCell { text: "N", highlight_id: None, repeat: None }, GridLineCell { text: "o", highlight_id: None, repeat: None }, GridLineCell { text: " ", highlight_id: None, repeat: None }, GridLineCell { text: "N", highlight_id: None, repeat: None }, GridLineCell { text: "a", highlight_id: None, repeat: None }, GridLineCell { text: "m", highlight_id: None, repeat: None }, GridLineCell { text: "e", highlight_id: None, repeat: None }, GridLineCell { text: "]", highlight_id: None, repeat: None }, GridLineCell { text: " ", highlight_id: Some(145), repeat: Some(2) }, GridLineCell { text: "\u{e0b0}", highlight_id: Some(143), repeat: None }, GridLineCell { text: " ", highlight_id: Some(116), repeat: Some(69) }, GridLineCell { text: "\u{e0b2}", highlight_id: Some(143), repeat: None }, GridLineCell { text: "\u{e0b2}", highlight_id: Some(134), repeat: None }, GridLineCell { text: "\u{e0b2}", highlight_id: Some(124), repeat: None }, GridLineCell { text: " ", highlight_id: Some(126), repeat: None }, GridLineCell { text: "\u{e0a1}", highlight_id: None, repeat: None }, GridLineCell { text: " ", highlight_id: Some(126), repeat: Some(3) }, GridLineCell { text: "1", highlight_id: None, repeat: None }, GridLineCell { text: ":", highlight_id: None, repeat: None }, GridLineCell { text: "1", highlight_id: None, repeat: None }, GridLineCell { text: " ", highlight_id: Some(126), repeat: Some(2) }] }
TRACE [neovide::channel_utils] redraw_event WindowViewport { grid: 2, top_line: 0.0, bottom_line: 2.0, current_line: 0.0, current_column: 0.0, line_count: Some(1.0) }
TRACE [neovide::channel_utils] redraw_event CursorGoto { grid: 2, row: 0, column: 4 }
TRACE [neovide::channel_utils] redraw_event ModeChange { mode: Normal, mode_index: 0 }
TRACE [neovide::channel_utils] redraw_event Flush
TRACE [neovide::editor] Image flushed
```

**Comment by MultisampledNight** [comment]
Uh... well, the exact same thing happens for me in terminal NeoVim, even in Vim and `vi`. This seems more of a configuration issue, can you confirm with `neovide -- -u NORC`? If the problem does not appear there, would you mind sharing your configuration line where you might remap Alt + Tab?

**Comment by fredizzimo** [comment]
Do you have any `<C-i>` mappings in insert mode? Ctrl+i and tab has the same escape code, so that might be a reason, I assume that you have already checked that you don't have <M-Tab> mapped

To check all your insert mappings you can do 
```
:redir @a
:verbose imap
:redir END
:enew|put a
```
Press space if the `imap` command list several pages until you are at the end. You can also list other mappings with just `map`, `cmap` and so on.

**Comment by LoipesMas** [comment]
For me it also happens in terminal neovim and vim. Even with `-u NONE`. So I don't think it's a neovide issue.
I'll try on Windows later, but if it doesn't happen there I would assume it's because Windows doesn't pass `Alt+Tab` to applications (not sure tho).

**Comment by fredizzimo** [comment]
It appears that this is actually by design in Neovim from https://neovim.io/doc/user/vim_diff.html

> Input/Mappings:
  ALT (|META|) chords always work (even in the |TUI|). Map |<M-| with any key:
  <M-1>, <M-BS>, <M-Del>, <M-Ins>, <M-/>, <M-\>, <M-Space>, <M-Enter>, etc.
  Case-sensitive: <M-a> and <M-A> are two different keycodes.
>
> ALT behaves like <Esc> if not mapped. |i_ALT| |v_ALT| |c_ALT|

So according to that, I think that you can work around the problem by making a dummy mapping

**Comment by jonvaldes** [comment]
Interesting. For me it doesn't happen at all on terminal nvim, and on neovide it happens only about  50% of the time.

In any case, @fredizzimo's suggestion does solve the issue. I just added this to my config and the problem is gone:

    vim.api.nvim_set_keymap('i',` '<M-Tab>', '', { noremap = true, silent = true})

**Comment by Kethku** [comment]
There seems to be some modifier shenanigans going on... Seems related

**Comment by fredizzimo** [comment]
@jonvaldes, Does your terminal emulator handle alt at all? I don't think all of them do.

The about 50% of time thing might depend on if Neovim sees just alt or alt-tab at the same time. But that should be easy enough to test, but pressing alt alone to see if you get the described behaviour. After all that's how it's supposed to work according to Neovim's documentation.

**Comment by jonvaldes** [comment]
@fredizzimo just tried Alacritty, Kitty and XFCE Terminal (all the terminals I have on this system), and none of them show this.

As for the 50% thing, no idea what's going on, to be honest. Maybe some window manager thing? Seems completely random.

In any case, the M-Tab binding workaround works well, so if this is indeed an intended neovim behavior, I think we can just use the workaround and focus on other things.

**Comment by fredizzimo** [comment]
Yes, that's indeed the intended behaviour and it was done in https://github.com/neovim/neovim/pull/8226 and https://github.com/neovim/neovim/pull/13042. The reason for that is that terminals and also Vim behaves this way, see here fore example https://vim.fandom.com/wiki/Avoid_the_escape_key. I have no idea why your terminal emulators don't do it, or maybe you only tested with alt-tab, and not with other ALT combinations.

On the other hand, now when reading those in more detail, alt alone should not send an escape. And alt-tab should be captured by the operating system before passed on to Neovide, so there's indeed a bug in Neovide still. I also tested it on my Windows system, and on my system it works as it should, so Neovide stays in insert mode.
