### ISSUE TITLE
Window setting position bounds check

### ISSUE THREAD

**Issue by nganhkhoa** [neovide/neovide#1157]
I don't know what really happened, but I just got

```
{"window":{"Windowed":{"position":{"x":-32000,"y":-32000},"size":{"width":100,"height":50}}}}
```

where x, y is off the grid? This buggy the render into a non-existing window but neovide still runs. No error with `--log`.

Took me severals downgrades and upgrades neovim to ensure that it's not a bug of neovim. I have to manually clear the setting files, located in `nvim-data/neovide-settings.json` which is not documented too.

To prevent other users from getting into this weird behaviour, how about we **check for x, y bounds** and reset if the numbers in neovide-settings.json is wrong.

https://github.com/neovide/neovide/blob/95378fc8c2b83e9c113b76cbbf057aa2914a3c1a/src/settings/window_geometry.rs#L65-L69

**Comment by Kethku** [comment]
Fixed in main. Thanks for the report.

**Comment by Kethku** [comment]
The fix was to check if the window overlaps with the reported current monitor. If it doesn't, assume its off screen and reposition to the top left corner. All other times, the recorded previous position when closed will be used instead.
