### ISSUE TITLE
It does not open

### ISSUE THREAD

**Issue by beari22** [neovide/neovide#1160]
**Describe the bug**
when I run the .exe or use neovide it does not open 

**To Reproduce**
1.run neovide.exe or do <code>neovide</code>

**Expected behavior**
it opens

**Desktop (please complete the following information):**
 - OS: Windows 10 21H1
 - Neovide Version : 0.5.0 and 0.7.0 ( binary and Chocolatey[only 0.5.0] ) 
 - Neovim Version : 0.6.1 ( chocolatey )

**Please run `neovide --log` and paste the contents of the `.log` file here:**
for 0.5.0
INFO [neovide::bridge] Close watcher started

for 0.7.0
WARN [neovide::renderer::fonts::font_loader] Tried to load Extra Symbols.otf from assets but build didn't include embed-fonts feature
WARN [neovide::renderer::fonts::font_loader] Tried to load Missing Glyphs.otf from assets but build didn't include embed-fonts feature
WARN [neovide::renderer::fonts::font_loader] Tried to load Extra Symbols.otf from assets but build didn't include embed-fonts feature
WARN [neovide::renderer::fonts::font_loader] Tried to load Missing Glyphs.otf from assets but build didn't include embed-fonts feature
WARN [neovide::renderer::fonts::font_loader] Tried to load Extra Symbols.otf from assets but build didn't include embed-fonts feature
WARN [neovide::renderer::fonts::font_loader] Tried to load Missing Glyphs.otf from assets but build didn't include embed-fonts feature

**Additional context**
it does open for like 1/2 sec, it does not show anything but the process is in task manager

**Comment by Kethku** [comment]
Please try a build from main. This issue has been fixed

**Comment by beari22** [comment]
Build like "binary"?
Or 
Build like to "build from source"?

**Comment by Kethku** [comment]
Download a build from here https://github.com/neovide/neovide/actions

Also make sure that neovim is on your path.

**Comment by beari22** [comment]
it works
