### ISSUE TITLE
Cmd buffer is not rendered on startup

### ISSUE THREAD

**Issue by TENX-S** [neovide/neovide#1167]
**Describe the bug**
Cmd buffer is not rendered on startup

**To Reproduce**
open neovide

**Screenshots**
![bug](https://user-images.githubusercontent.com/40336192/150640835-68af0da7-5bfb-4166-b672-f53823dffd93.gif)

**Desktop (please complete the following information):**
 - OS: Windows 11 21H2
 - Neovide Version: current latest commit (build with rust 1.58.1)
 - Neovim Version: v0.7.0-dev+913-ge07a4b97f

**Please run `neovide --log` and paste the contents of the `.log` file here:**
[neovide_rCURRENT.log](https://github.com/neovide/neovide/files/7918446/neovide_rCURRENT.log)

**Additional Context**
[init.vim.txt](https://github.com/neovide/neovide/files/7918475/init.vim.txt)

**Comment by Kethku** [comment]
I can't reproduce this on main with today's neovim version.

Is it possible its due to something in your nvim config?

**Comment by TENX-S** [comment]
I rebuild the neovide again and replace the `init.vim` with the following:
```vim
call plug#begin('~/.vim/plugged')
Plug 'morhetz/gruvbox'
call plug#end()

colorscheme gruvbox
```
no lucky:
![image](https://user-images.githubusercontent.com/40336192/150661847-c4fe2da4-d659-4c29-8d4b-0e0f2ef03671.png)

**Comment by TENX-S** [comment]
and there's more to come :( The close button is broken:
![bug](https://user-images.githubusercontent.com/40336192/150661964-b126a676-ea73-4d83-942b-bd5aaac53e79.gif)

I will do the same test on the new VM machine

**Comment by Kethku** [comment]
Thats super strange. Could you get the log and upload it? `neovide --log`

**Comment by dineshKumar777** [comment]
this is a bug I encountered in older version of neovide. But latest neovide resolved this issue for me.

Can you try downloading latest executable from github actions and retry ?
https://github.com/neovide/neovide/actions/runs/1731838739

**Comment by TENX-S** [comment]
> this is a bug I encountered in older version of neovide. But latest neovide resolved this issue for me.
> 
> Can you try downloading latest executable from github actions and retry ? https://github.com/neovide/neovide/actions/runs/1731838739

still no lucky ... I've been using neovide for a while, but never had this problem before.
![image](https://user-images.githubusercontent.com/40336192/150667253-c678d551-e771-4e7d-baae-eda77cf811af.png)

**Comment by TENX-S** [comment]
> Thats super strange. Could you get the log and upload it? `neovide --log`
[neovide_rCURRENT.log]

(https://github.com/neovide/neovide/files/7919910/neovide_rCURRENT.log)

**Comment by fredizzimo** [comment]
@Kethku I think that `DefaultStyleChanged` needs a redraw.

**Comment by Kethku** [comment]
Done in main. @TENX-S can you try a build from the most recent commit in the main branch?

**Comment by TENX-S** [comment]
It works!
