### ISSUE TITLE
Add cursor animation options

### ISSUE THREAD

**Issue by kiuKisas** [neovide/neovide#117]
The cursor animation is very eye-catching when switching from normal/insert mode to the bottom command line.
As stated in this issue: https://github.com/Kethku/neovide/issues/85 , being able to disable animation would be a great feature, but it might be even cooler to have a less flashy effect for this transition, like fade in or something.

What do you think about that?

**Comment by Kethku** [comment]
Sounds good to me. I am definitely planning on multiple configuration options for the cursor. Its on the list once we figure out how to implement settings correctly. Its coming!

**Comment by Kethku** [comment]
This is partially solved now by @jonvaldes solution. The framework is set, just need to add a way to disable the trail in various circumstances

**Comment by Kethku** [comment]
This has been solved for a while now. We dont necessarily have a fade animation but the animation is configurable in a variety of ways
