### ISSUE TITLE
Mouse selection requires shifted cursor position 

### ISSUE THREAD

**Issue by vbrinnel** [neovide/neovide#1173]
First, thanks a lot for Neovide, it's both refreshing and fun to use :)

**Describe the bug**
Selecting text by moving the mouse while maintaining the left mouse button pressed requires the cursor to be placed almost above the text to be targeted.
A GIF probably describes this better than me:

![mouse_sel2](https://user-images.githubusercontent.com/17532220/150784748-40b0e3af-8f22-474a-9d0d-c24c5244ae2d.gif)

**Desktop (please complete the following information):**
- OS: macOS 10.15.6
- Neovide Version 0.8.0 (20220122.190411)
- Nvim v0.6.1

**Comment by TENX-S** [comment]
I can reproduce this with the latest commit

**Comment by Kethku** [comment]
Does it happen with and without multigrid enabled?

**Comment by vbrinnel** [comment]
It happens without multigrid.
Starting neovim with `--multigrid` solves indeed the issue !

**Comment by Kethku** [comment]
Ok I think the fix here is to just move to multigrid. Its better in almost every way.

I will make a change soon swaps multigrid to the default and add a setting to disable smooth scrolling (which is the main issue remaining with it)

**Comment by vbrinnel** [comment]
For mac people desiring to enable `multigrid` by default, please have a look at: https://github.com/neovide/neovide/issues/1147#issuecomment-1013615070.
Though please note that there is a typo in the last command in this comment, it should be `launchctl setenv NEOVIDE_MULTIGRID 1`

It sets the env variable `NEOVIDE_MULTIGRID` (https://github.com/neovide/neovide/wiki/Configuration#multigrid)

@Kethku  Thank you and please feel free to close this issue.

**Comment by StephanRoemer** [comment]
How do you set this environment variable in Windows?

**Comment by MultisampledNight** [comment]
Haven't used Windows in a long time, but you should be able to search for `Set environment variables` or something like that in the taskbar. In the popup, you may be able to set it under `User environment` or similar, NOT the system one.

However, this might be overkill. You could probably just set it through the CMD or Powershell, or even just run/alias `neovide --multigrid` when opening a file.

**Comment by StephanRoemer** [comment]
True, that might be the most streamlined solution, thanks!
