### ISSUE TITLE
Neovide thinks neovim is below version 0.4 only when passing a file name as parameter

### ISSUE THREAD

**Issue by LordMZTE** [neovide/neovide#1176]
**Describe the bug**
When starting neovide with `neovide` it works fine.
Starting it with `neovide test.txt` however, will result in an error (see log file).

**To Reproduce**
1. open neovide with `neovide`
2. check the log file

**Expected behavior**
Neovide opens up fine and opens the file

**Desktop (please complete the following information):**
- OS: ArchLinux, kernel 5.16.2
- Neovide Version 0.8.0, commit `gdd74ff4`
- Neovim Version 0.6.1

**Please run `neovide --log` and paste the contents of the `.log` file here:**
<details>
<summary>with file argument</summary>

```log
INFO [neovide::bridge::command] Starting neovim with: Command { std: "/sbin/nvim" "--embed test.txt", kill_on_drop: false }
ERROR [neovide::bridge] Neovide requires nvim version 0.4 or higher. Download the latest version here https://github.com/neovim/neovim/wiki/Installing-Neovim
```

</details>

<details>
<summary>without file argument (TRACE messages removed because of GH length limit)</summary>

```log
INFO [neovide::bridge::command] Starting neovim with: Command { std: "/sbin/nvim" "--embed", kill_on_drop: false }
DEBUG [neovide::bridge::events] Ignored client type property: "version"
DEBUG [neovide::bridge::events] Ignored client type property: "type"
DEBUG [neovide::bridge::events] Ignored client type property: "methods"
DEBUG [neovide::bridge::events] Ignored client type property: "attributes"
INFO [neovide::bridge::setup] Neovide registered to nvim with channel id 1
INFO [neovide::bridge] Neovim process attached
DEBUG [neovide::settings::window_geometry] Loaded window settings: Windowed { position: PhysicalPosition { x: 20, y: 112 }, size: Dimensions { width: 148, height: 99 } }
INFO [neovide::window] window created (scale_factor: 1.0000, font_dimensions: Dimensions { width: 11, height: 22 })
INFO [neovide::running_tracker] Quit with code 0: Quit from neovim
INFO [neovide::running_tracker] Quit neovim processed failed
DEBUG [neovide::settings::window_geometry] Saved Window Settings: {"window":{"Windowed":{"position":{"x":20,"y":112},"size":{"width":148,"height":99}}}}
```

</details>

**Comment by fredizzimo** [comment]
Hm.. 

This seems to be the same as this https://github.com/neovide/neovide/issues/1175, or at least the same error. So it looks like  it's not the new Mac specific behaviour that has changed, but something else. But still likely related to the command line processing.

**Comment by Kethku** [comment]
Yeah I think this was introduced in my most recent PR. I encountered this exact issue when embedding in wsl but in reverse.

I think the arguments issue should be pretty easily fixable. I'll try to take a look tonight.

**Comment by fredizzimo** [comment]
This is fixed by https://github.com/neovide/neovide/pull/1180.

And it looks like the MacOS problem is something else.
