### ISSUE TITLE
CI: Tests are broken, but CI does not fails

### ISSUE THREAD

**Issue by last-partizan** [neovide/neovide#1182]
https://github.com/neovide/neovide/runs/4957560471?check_suite_focus=true

For example, look here:

> error: could not compile `neovide` due to 4 previous errors

But pipeline passing like everything is okay.

My first thought was maybe output redirection breaks return codes, but no:
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#exit-codes-and-error-action-preference

Looks like github already setting pipefail option, so it should work.

But maybe this is not working for some reason?

#### Problems:

- [x] CI does not fails
- [x] `--format json` argument for `cargo test` is not working
- [ ] One broken test left

**Comment by last-partizan** [comment]
@Kethku @LoipesMas 

Maybe you have some idea why running `cargo test -- -Z unstable-options --format json` in winit repo makes it produce json, while in neovide it does not?

I'm puzzled. It is the same cargo `1.58.0`

**Comment by Kethku** [comment]
You beat me to the punch, I was going to create an issue for this, but haven't had the time to dig in. No idea whats going on here but I'm invested in fixing it

**Comment by last-partizan** [comment]
```
failures:

---- editor::window::tests::window_separator_modifies_grid_and_sends_draw_command stdout ----
thread 'editor::window::tests::window_separator_modifies_grid_and_sends_draw_command' panicked at 'Could not receive commands: RecvError', src/editor/window.rs:351:33
stack backtrace:
   0: rust_begin_unwind
             at /rustc/6abb6385b2cb7249f67b9b3ce7522527767dd907/library/std/src/panicking.rs:577:5
   1: core::panicking::panic_fmt
             at /rustc/6abb6385b2cb7249f67b9b3ce7522527767dd907/library/core/src/panicking.rs:135:14
   2: core::result::unwrap_failed
             at /rustc/6abb6385b2cb7249f67b9b3ce7522527767dd907/library/core/src/result.rs:1737:5
   3: core::result::Result<T,E>::expect
             at /rustc/6abb6385b2cb7249f67b9b3ce7522527767dd907/library/core/src/result.rs:1022:23
   4: neovide::editor::window::tests::window_separator_modifies_grid_and_sends_draw_command
             at ./src/editor/window.rs:351:9
   5: neovide::editor::window::tests::window_separator_modifies_grid_and_sends_draw_command::{{closure}}
             at ./src/editor/window.rs:340:5
   6: core::ops::function::FnOnce::call_once
             at /rustc/6abb6385b2cb7249f67b9b3ce7522527767dd907/library/core/src/ops/function.rs:227:5
   7: core::ops::function::FnOnce::call_once
             at /rustc/6abb6385b2cb7249f67b9b3ce7522527767dd907/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

CI itself is fixed now, and only one broken test left.

@Kethku this one i'm leaving for you. As i understand, there was something change in how those senders/receivews work, but test aren't updated.

**Comment by Kethku** [comment]
Fixed. Thanks for pushing this forward.
