### ISSUE TITLE
Detect macOS Command(Meta) keys such as Command+c, Command+v, Command+s, Command+z?

### ISSUE THREAD

**Issue by linrongbin16** [neovide/neovide#1184]
Hi, I'm using neovide in macOS 10.15.7, compiled with rustc 1.58.1.

It seems that Ctrl keys are working, while Command(Meta) keys not working.

Is it available to detect macOS Command(Meta) keys?

**Comment by akio-ito** [comment]
It seems it works for me:

```
    let g:neovide_input_use_logo=v:true
    noremap <D-s>  :w<CR>
    noremap <D-c>  y
    noremap <D-v>  hp   
```

**Comment by linrongbin16** [comment]
thanks a lot
