### ISSUE TITLE
Add this project to github topics pages *neovim-guis* and *rust*

### ISSUE THREAD

**Issue by iurev** [neovide/neovide#1187]
Hi!
Would that be possible to add several tags on github for this project, especially:
- neovim-guis
- rust

I believe that by adding these tags more people would be able to find neovide from pages:
- [github.com/topics/rust](https://github.com/topics/rust)
- [github.com/topics/neovim-guis](https://github.com/topics/neovim-guis)

Here's the link with the instruction how to do that:
[docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/classifying-your-repository-with-topics](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/classifying-your-repository-with-topics)

Based on what I see it'll take 10 minutes approximately.

**Comment by Kethku** [comment]
Done.
