### ISSUE TITLE
Command line height too larger

### ISSUE THREAD

**Issue by medwatt** [neovide/neovide#1190]
I have noticed that when I set the font size to something like 11, the command line height is too larger in neovide. See the image below. Neovide is on the right.

![](https://i.imgur.com/a4REa1x.png)

**Comment by emmanueltouzery** [comment]
I'm seeing this too.

**Comment by Kethku** [comment]
This isn't a bug. Your window is not a set multiple of the line height. So neovide allocates all of the lines it can and then leaves the remainder of the window to be whatever the default background color is. If neovide allocated another line there, it would be cut off.

I'm not sure what neovide should do instead. Your other app Appears to split the difference between the top and bottom, but this isn't a good solution if you have a tab line formatter as it would leave a weird gap at the top. The commandline in contrast is pretty tolerant to extra space.

I'm going to close this as won't fix, but if you have suggestions here for a way we should handle this better, feel free to let me know and reopen.

**Comment by dandrestor** [comment]
I noticed other programs set that extra space to black. In certain situations (such as full-screen windows where the window border is not rendered) the extra space blends into the screen bezel and this gives more consistent visuals imo.
