### ISSUE TITLE
How to config to render font italic or bold?

### ISSUE THREAD

**Issue by defpis** [neovide/neovide#1191]
**Describe the bug**
Font render on neovide is different with iterm2

**Expected behavior**
Font rendering should render font italic or bold config by theme

**Screenshots**
![image](https://user-images.githubusercontent.com/48018016/151744894-1963c2e8-26c4-4eaf-ba85-a3ca798e24b5.png)

**Desktop (please complete the following information):**
 - OS: macOS 11.6.1
 - Neovide Version 0.6.0
 - Neovim Version 0.6.0

**Comment by defpis** [comment]
I don't have any extra configuration except setting guifont in nvim config
```lua
-- options.lua
guifont = "Hack Nerd Font Mono:h14",
```

**Comment by defpis** [comment]
I tried compiling with the latest code, but it cannot startup, and the downloaded installation package cannot startup too, program crashes when opened

**Comment by MultisampledNight** [comment]
Would you mind sharing the exact error? Guessing is quite difficult in a program where crashes might come from rendering, the window manager, running out-of-bounds...

**Comment by defpis** [comment]
![屏幕录制2022-02-01 下午7 20 36](https://user-images.githubusercontent.com/48018016/151960006-cc8df880-6f89-4eaa-b69c-a4057f5997ec.gif)

**Comment by defpis** [comment]
Nothing else happened, just quit

**Comment by MultisampledNight** [comment]
Hm, that's odd. I'm not too sure about Mac OS as I barely use it, but maybe more information is in the terminal output. Could you run `open -a Neovide.app` in a terminal of your choice?

**Comment by defpis** [comment]
![image](https://user-images.githubusercontent.com/48018016/152082753-5a1f7281-9170-4327-aed9-9f868cbcda3c.png)

Nothing else too...

**Comment by defpis** [comment]
Maybe I can update MacOS to have a try again

**Comment by Kethku** [comment]
Please let me know if that works. I think this is related to the recent macos issues we've been running into where neovide can't find the neovim executable when run from finder.

**Comment by clason** [comment]
Are you sure that your font supports bold and italic?

**Comment by TENX-S** [comment]
@defpis build neovide at https://github.com/neovide/neovide/commit/db53e94db928946a1df06c88dd68bd80ac443758 may work

**Comment by defpis** [comment]
@TENX-S Nice Work! Amazing👍🏻, success startup by compiling with the latest code without update macos

**Comment by defpis** [comment]
Font rendering is work fine too!

![image](https://user-images.githubusercontent.com/48018016/152644327-9a2543b3-5a70-4338-a03d-d92bf9c9cdeb.png)

**Comment by defpis** [comment]
But unfortunately, except for the first time it can be startup, it does not work after that.

https://user-images.githubusercontent.com/48018016/152644824-d31e039b-a221-4135-85f6-39a7dd28774b.mov

**Comment by defpis** [comment]
I guess something not closed, so can't restart again.

**Comment by TENX-S** [comment]
@defpis Will rebooting the mac fix this problem?

**Comment by defpis** [comment]
No effect by rebooting the mac

**Comment by TENX-S** [comment]
That's weird. https://github.com/neovide/neovide/commit/db53e94db928946a1df06c88dd68bd80ac443758 works fine on my mac. Try a full rebuild: delete `target/` and `cargo build --release`

**Comment by defpis** [comment]
Except for the first time it can be startup, it does not work after that.

I have deleted the whole repo, reclone and rebuild it.

![屏幕录制2022-02-07 上午11 20 02](https://user-images.githubusercontent.com/48018016/152719482-6c45b715-2427-4607-8a90-025bd915dd3f.gif)

**Comment by TENX-S** [comment]
@defpis It's on 92bc12? Should build on https://github.com/neovide/neovide/commit/db53e94db928946a1df06c88dd68bd80ac443758 I guess

**Comment by TENX-S** [comment]
@defpis I see your commit stays at 92bc172 which is the current latest. Do  you build neovide on https://github.com/neovide/neovide/commit/db53e94db928946a1df06c88dd68bd80ac443758? If https://github.com/neovide/neovide/commit/db53e94db928946a1df06c88dd68bd80ac443758 still not works, try another backwards?

**Comment by dineshKumar777** [comment]
> Except for the first time it can be startup, it does not work after that.
> 
> I have deleted the whole repo, reclone and rebuild it.
> 
> ![屏幕录制2022-02-07 上午11 20 02](https://user-images.githubusercontent.com/48018016/152719482-6c45b715-2427-4607-8a90-025bd915dd3f.gif)

Please attach log file

**Comment by defpis** [comment]
@TENX-S It work, much appreciate👍🏻
