### ISSUE TITLE
Cannot neovide start in arch linux

### ISSUE THREAD

**Issue by AlphaTechnolog** [neovide/neovide#1193]
**Describe the bug**
I install neovide using the aur package `neovide-bin` and `neovide`, and non of it is working (I tried recompiling too)

**To Reproduce**
1. Have a new and fresh arch linux installation
2. Install yay `git clone https://aur.archlinux.org/yay.git yay && cd yay && makepkg -si`
3. Then install neovide (in this case with `neovide-bin`): `yay -S neovide-bin`

**Expected behavior**
The neovide window opening

**Screenshots**
![Screenshot from 2022-02-02 16-03-19](https://user-images.githubusercontent.com/54639968/152228639-ca1d94e9-b7e4-4dbe-bdee-6a597611107b.png)

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Neovide Version 0.7.0
 - Neovim Version 0.6.1

**Please run `neovide --log` and paste the contents of the `.log` file here:**
```
Ignored client type property: "methods"
Ignored client type property: "attributes"
thread 'main' panicked at 'Failed to create renderer: CreateInstanceError(InstanceError(VkError(ERROR_OUT_OF_HOST_MEMORY)))',
src/window/sdl2/mod.rs:459:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by MultisampledNight** [comment]
Judging from `@samsung` at the upper left corner in your screenshot and from the out-of-memory error I think you may have very limited hardware, which device + which GPU are you running on?

**Comment by AlphaTechnolog** [comment]
Yes

> Judging from `@samsung` at the upper left corner in your screenshot and from the out-of-memory error I think you may have very limited hardware, which device + which GPU are you running on?

Yes, you are absolutelly right, I am in a very limited hardware, but it works on my old debian installation :(

According to my neofetch output, this is my specifications:

![Screenshot from 2022-02-02 16-11-33](https://user-images.githubusercontent.com/54639968/152229893-d8a9e14d-d5a5-406f-9ad3-b0fab9382369.png)

**Comment by AlphaTechnolog** [comment]
I think it's a problem in my intel drivers, or some arch linux missing packages issues... Anyone can help me? Exists some package that is missing in the `neovide-bin` package, or any package that I don't install to make neovide works in arch linux?

I have a very clean arch linux blank installation with some packages, like:

- `intel-ucode`
- `xf86-video-intel`

**Comment by MultisampledNight** [comment]
In my opinion that's a bit far off for a GitHub issue, but you may be missing Vulkan support, provided through the packages `vulkan-intel` according to https://wiki.archlinux.org/title/Vulkan and my system. You could install `vulkan-tools` and run `vulkaninfo` to see whether your system configuration supports Vulkan. On the quick I found nothing specific about the `i3-2330M`.

**Comment by AlphaTechnolog** [comment]
Oh, Ok. Thank you very much anyway for the quick response and for the help

**Comment by MultisampledNight** [comment]
Well, feel free to write on Discord in case you keep hitting this. But sure, no worries!

**Comment by AlphaTechnolog** [comment]
Thank so much, were I found the discord invitation link? I want to join to it :D

**Comment by AlphaTechnolog** [comment]
Oh, I found it jajaja, Thank you very much!

**Comment by Kethku** [comment]
Note: we don't use vulkan anymore so vulkan support isn't a part of the problem. We only use opengl. Counter intuitively that might still be a gpu issue, but dunno

**Comment by fredizzimo** [comment]
@AlphaTechnolog, I can see that you are using the now quite outdated release version of Neovide. So, you might want to try the latest master version instead. It uses skia instead of sdl for the renderer, so there's a good chance it works with that.

**Comment by Kethku** [comment]
We helped AlphaTechnolog in the discord, so they should be good now :)
