### ISSUE TITLE
Small Icons

### ISSUE THREAD

**Issue by things-markj** [neovide/neovide#1196]
**Describe the bug**
Icons from the font awesome I'm using in are being rendered very small compared to when I run neovim in the terminal, which render them full size.

**To Reproduce**

**Expected behavior**
Full sized Icons

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Arch
 - Neovide Version: 0.8.0
 - Neovim Version: 0.7

**Please run `neovide --log` and paste the contents of the `.log` file here:**

**Additional context**
[neovide_r2022-02-04_20-36-12.log](https://github.com/neovide/neovide/files/8005413/neovide_r2022-02-04_20-36-12.log)
[neovide_rCURRENT.log](https://github.com/neovide/neovide/files/8005414/neovide_rCURRENT.log)

**Comment by Kethku** [comment]
Can you show a screen cap?

**Comment by fredizzimo** [comment]
You are using `JetBrainsMono Nerd Font Mono` which forces all the glyphs to be single width, if you change the font to `JetBrainsMono Nerd Font` it should be fine. 

I can't seem to find the information in the Nerd fonts documentation, but that's how they work.

**Comment by things-markj** [comment]
Ohh didn't know about that, yeah changing the font to `JetBrainsMono Nerd Font` fixed the issue, thank you both for your time.
