### ISSUE TITLE
Font Symbols/Glyphs not displaying correctly in Windows

### ISSUE THREAD

**Issue by jeffdadamo1** [neovide/neovide#1202]
**Describe the bug**
Font Symbols/Glyphs don't display correctly. 

**To Reproduce**
1. Start Neovide

**Expected behavior**
Expect the font symbols/glyphs to load and display correctly. 

**Screenshots**
![image](https://user-images.githubusercontent.com/94927699/152806029-6f8b6990-c488-4e6f-bb09-c0f91ceecdae.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Neovide Version: 0.8.0 (Build-and-Test number693)
 - Neovim Version: v0.7.0-dev+717-gf37c5f18.

**Please run `neovide --log` and paste the contents of the `.log` file here:**
rCURRENT.log was way too large to post here, I can drop in Debian Pastezone if needed.

**Additional context**
I am using the latest Neovide from the github actions page since I'm on a windows pc with restricted privaleges, I can't build or install from scoop. While I am currently using Cascadia Code PL, this issue occurs with every font I've tried to use. For context, glyphs for all fonts I've tried (Fira Code, JetBrains Mono, etc) work and display fine in the lastest release version of Neovide found on the "Releases" page here. The screenshot shows the placeholders that shows up in every spot I would expect to see a symbol/glyph.  I should also note that my current settings work fine in when I run nvim in Alacritty...Please let me know if there is any other information I can provide that would be helpful. Thanks!

**Comment by dineshKumar777** [comment]
you need to use nerd font as fallback.

```lua
if vim.g.neovide == true then
    -- vim.cmd 'set guifont=Hack\ NF:h10'
    -- vim.o.guifont='Consolas:h10'
    -- vim.o.guifont='FiraCode NF:h14'
    vim.o.guifont='Operator Mono,FiraCode NF:h14'
    vim.api.nvim_set_keymap('n', '<F11>', ":let g:neovide_fullscreen = !g:neovide_fullscreen<CR>", {})
end
```

**Comment by jeffdadamo1** [comment]
oh wow, that worked. I apologize I didn't realize it was so simple. Thanks!
