### ISSUE TITLE
"+p system clipboard paste not working

### ISSUE THREAD

**Issue by Lite5h4dow** [neovide/neovide#1205]
**Describe the bug**
I cannot paste with `"+p` in neovide.

**To Reproduce**
1. open neovide
2. go to another program e.g. firefox and copy text
3. paste to terminal to ensure that the text is in the system clipboard
4. go into neovide and press `<ESC>"+p<CR>`

**Expected behavior**
paste from system clipboard once sequence is complete

**Desktop (please complete the following information):**
 - OS: Arch Linux.
 - Neovide Version: 0.8.0
 - Neovim Version: 0.6.1

**Please run `neovide --log` and paste the contents of the `.log` file here:**
https://0bin.net/paste/QhBmNXZg#X6GHkPfmpOGIofmWXUIDCttyN6X-931sZKGfDPFZud2

**Comment by gh4n** [comment]
+1 on macos

**Comment by ecks** [comment]
Make sure you have a tool such as "xclip" or something similar installed. 

I just reinstalled my os and pasting stopped working for me as well, then I read the helpfile on clipboard and after some back and forth realized that's what was missing for me. Once I installed xsel, it worked okay for me.

**Comment by Lite5h4dow** [comment]
I do have xclip installed.

**Comment by Kethku** [comment]
I can't repro this on windows or macos. Can you try setting clipboard to unnamedplus? `set clipboard=unnamedplus` A recent PR went in to add better clipboard support which may be causing issues.

**Comment by Lite5h4dow** [comment]
yeah ill give that a go

**Comment by Lite5h4dow** [comment]
@Kethku i just got around to adding it to my configs, and that does indeed fix the problem, thankyou.
