### ISSUE TITLE
No Path import when launch outside of terminal (E.g. rofi)

### ISSUE THREAD

**Issue by Lite5h4dow** [neovide/neovide#1206]
**Describe the bug**
When i launch Neovide from rofi, Coc warns me it cannot find node in path. it can when i launch from terminal however
(this is because i have nvim settings applied in terminal, however, there is no way to add anything to neovides path, there is no config,and it does not run / source .zshrc)

**To Reproduce**
1. setup Coc in nvim with nvm providing node
2. open neovide via terminal
3. no issue
4. open neovide from rofi, no path import.

**Expected behavior**
imports nvm node path

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Neovide Version 0.8.0
 - Neovim Version 0.6.1

**Comment by MultisampledNight** [comment]
Do you start i3 from your `.zprofile`? I think in that case your `.zshrc` is not run at all before rofi starts up, so rofi can't inherit environment variables it does not know about. You could try sourcing your `.zshrc` in your `.zprofile` before executing i3 (lol) or setting your nvim stuff in `.zprofile` instead of `.zshrc`.

**Comment by Lite5h4dow** [comment]
i use bspwm, and i launch it with x

**Comment by MultisampledNight** [comment]
(where did I get that thing with i3 from) Then the issue is the same I guess, except that I don't have any idea of where to set environment variables for GDM.

**Comment by aneesh-dandime** [comment]
Hi, I am using xfce and when I launch Neovide from xfce applications menu, I am observing the same issue. When I launch from applications menu, neovim tells me that it cannot find my installation of ghc but when I launch from terminal it works just fine.

**Comment by MultisampledNight** [comment]
@aneesh-dandime You need to set your PATH somehow globally, depending on your display manager you probably need to configure it in `~/.xprofile`. Your graphical environment probably doesn't source the startup files of the current shell.

**Comment by fredizzimo** [comment]
This is documented here https://neovide.dev/faq.html#neovide-is-not-picking-up-some-shell-configured-information
