### ISSUE TITLE
invisible cursor on rename in nvim-tree when multigrid is enabled

### ISSUE THREAD

**Issue by emmanueltouzery** [neovide/neovide#1207]
**Describe the bug**
~~This is a regression due to the recent https://github.com/neovide/neovide/pull/1195/files pull request: it causes the cursor to be invisible also in cases where we do NOT want it to be invisible.~~

When multigrid is enabled, when renaming a file with nvim-tree, you can't see the cursor.

**To Reproduce**
1. open neovide with multigrid, and thr nvim-tree plugin
2. place the cursor over a file in the tree
3. press `r` to rename the file
4. you are taken to the nvim "ex command line" where you can edit the filename, but the cursor is invisible.

**Expected behavior**
The cursor should be visible when you're editing the filename. It is correctly visible is multigrid is disabled. ~~if we revert the recent PR #1195.~~

**Desktop (please complete the following information):**
 - OS: fedora linux 35
 - Neovide 92bc172
 - Neovim 0.5.1

**Comment by Kethku** [comment]
Do you have a highlighting theme enabled? I'm suspicious that the theme sets blend to an incorrect value.

**Comment by emmanueltouzery** [comment]
The issue seems logical to me since the PR explicitely mentioned that it'll achieve hiding the cursor for nvim-tree, and I'm exactly reporting the issue with nvim-tree. But to make 100% sure, I just tested a minimal configuration of plain nvim 0.6.1 with only nvim-tree to reproduce the issue. Here are the steps:

```lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvim/site]]
local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'
local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      {
	     'kyazdani42/nvim-tree.lua',
	     requires = {
		     'kyazdani42/nvim-web-devicons', -- optional, for file icon
	     },
	     config = function() require'nvim-tree'.setup {} end
      }
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. '/plugin/packer_compiled.lua',
      display = { non_interactive = true },
    },
  }
end
_G.load_config = function()
  -- ADD INIT.LUA SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
  require'nvim-tree'.setup {}
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing Telescope and dependencies.")
  vim.fn.system { 'git', 'clone', '--depth=1', 'https://github.com/wbthomason/packer.nvim', install_path }
end
load_plugins()
require('packer').sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]]
```

save this to `minimal.lua`

then run:
```
neovide --multigrid --  -nu minimal.lua
```

Then open a file, launch `:NvimTreeToggle`, go over a file in the sidebar, press `r` to rename it => you don't have a cursor when modifying the filename to edit.

Now if you do the same thing with the code as it was before that PR was merged, you have a cursor.

**Comment by emmanueltouzery** [comment]
hmm hold on. actually in that minimal setup i can reproduce the issue even with the commit before the PR?

**Comment by MultisampledNight** [comment]
I spontaneously found this is even simpler reproduceable, just by `:source`ing this Vim script:

```vim
call timer_start(200, {-> execute('echo input("wow: ")')})
```

**Comment by Liverm0r** [comment]
Here how it looks when I am adding/renaming with nerdtree (real invisible cursor is on the `...tree.fnl|`:

<img width="462" alt="image" src="https://user-images.githubusercontent.com/14236531/167727819-f6f1c52c-9ea4-486d-946e-8e565213e6c8.png">

Osx monteray, nvim 0.7.0. fresh master neovide sha 4c0b5f5e335e7cb258364d0a79ef080a38b174b0

**Comment by firai** [comment]
On Windows 11, Neovide 0.8 and Neovim 0.7.0, the drawn cursor is stuck in the top left corner with the scenario described in the OP:

- `multigrid` is on, and
- Nvim-tree is prompting for a file name, when creating a file or renaming a file.

The drawn cursor in the upper left reflects how it would look if it was drawn where the real cursor is (i.e. it can switch between the `|` cursor and the block cursor depending on where the real cursor is), but it's confined to the first character (the C in this case).

![image](https://user-images.githubusercontent.com/23555/170516586-56aa762b-32ee-4178-abd4-2b72d9a73ff4.png)

The cursor is drawn at the correct location when Neovide (and every other terminal) when `multigrid` is off:

![image](https://user-images.githubusercontent.com/23555/170516549-db9445b2-6508-4c38-b5eb-bc2bb80fa21f.png)

**Comment by MultisampledNight** [comment]
Thank you all for reporting! The issue was far easier to track down than I had imagined.
