### ISSUE TITLE
How to change the font size if you're using init.lua (lua environment) and not .vimrc file

### ISSUE THREAD

**Issue by nishu-murmu** [neovide/neovide#1211]
I wanted to use Neovide but am not using standard .vimrc file.
my source file is a lua file.
Can we get a feature to edit fonts in lua environment.

[Neovide](https://github.com/nishu-murmu/dotfiles/blob/main/assets/neovide%20(1).png)

**Comment by MultisampledNight** [comment]
The option Neovide uses for this is builtin in NeoVim, it's called `guifont`. So that has nothing to do with Neovide itself. According to `:h lua-vim-opt`, you could just use

```lua
vim.opt.guifont = { "Source Code Pro", "h12" }
```

where `Source Code Pro` sets the font family and `h12` sets the font size. See `:h 'guifont'` for more configuration options.

**Comment by nishu-murmu** [comment]
I know about `guifont`
I have used it in my config in `settings.lua` file
**Here's the settings.lua file**
```
vim.cmd([[
let g:mapleader = " "

set nocompatible
syntax enable
filetype plugin indent on
set encoding=utf-8
set fileencoding=utf-8
set showcmd
set cmdheight=1
set scrolloff=10
set splitbelow
set splitright
set conceallevel=0
set title
set tabstop=2
set shiftwidth=2
set autoindent
set smarttab
set expandtab
set showtabline=2
set noshowmode
set nobackup
set nowritebackup
set updatetime=300
set timeoutlen=500
set clipboard=unnamedplus
set laststatus=0
set number
set ruler
set cursorline
set hidden
set nowrap
set backspace=start,eol,indent
set mouse=a
set lazyredraw
set wildignore+=*/node_modules/*
set termguicolors
set guifont=Hack:h12
set background=dark 
colorscheme onedark

au BufNewFile,BufRead *.es6 setf javascript
au BufNewFile,BufRead *.tsx setf typescriptreact
]])

```
Still the font size doesn't change

Then I read for fonts to work properly and not breaking, you need to use `guifont` in the init file so I also added it in `init.lua` file but still it isn't working

**Here's the init.lua file**
```
require("user.settings")
vim.opt.guifont = { "Source Code Pro", "h12" }
require("user.mappings")
require("user.plugins")
require("user.lsp-config")
require("user.lsp-saga")
require("user.auto-pairs")
require("user.Comment")
require("user.lualine")
require("user.treesitter")
require("user.telescope")
require("user.gitsigns")
require("user.nvim-tree")
require("user.nvim-cmp")
require("user.web-devicons")
require("user.bufferline")
require("user.alpha")
require("user.scroll")
require("user.colorizer")
require("user.whichkey")

```

**Comment by MultisampledNight** [comment]
That's truly difficult to tell, as any of those imported files could contain a new value for `guifont`. While you could check your final value with `:set guifont?` and then search in all your config files for it, that's still not an issue with Neovide itself.

**Comment by Kethku** [comment]
> The option Neovide uses for this is builtin in NeoVim, it's called `guifont`. So that has nothing to do with Neovide itself. According to `:h lua-vim-opt`, you could just use
> 
> ```lua
> vim.opt.guifont = { "Source Code Pro", "h12" }
> ```
> 
> where `Source Code Pro` sets the font family and `h12` sets the font size. See `:h 'guifont'` for more configuration options.

I'd be surprised if this works. We currently parse the guifont manually, and I don't know how lua objects get converted. I use vim.o.guifont = "Cascadia Code PL,Delugia Nerd Font:h11" in my config. (I think thats right. I'm translating from fennel and don't remember precisely what the lua syntax is). If you wanted to make this dynamic, or bind to a function, I'd achieve that with string concatenation.

**Comment by MultisampledNight** [comment]
Well, I just followed the example in `:h lua-vim-opt`. But if we don't support it, I've got another thing to tackle.

**Comment by nishu-murmu** [comment]
@MultisampledNight your code `(vim.opt.guifont = )` didn't seem to work
but @Kethku yours (`vim.o.guifont =`)actually did work but i need to reduce my fontsize a bit less than my Neovim config comparatively.
For example fontsize 8 in neovide is equivalent font size 12 in neovim

**Comment by alai** [comment]
> > The option Neovide uses for this is builtin in NeoVim, it's called `guifont`. So that has nothing to do with Neovide itself. According to `:h lua-vim-opt`, you could just use
> > ```lua
> > vim.opt.guifont = { "Source Code Pro", "h12" }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > where `Source Code Pro` sets the font family and `h12` sets the font size. See `:h 'guifont'` for more configuration options.
> 
> I'd be surprised if this works. We currently parse the guifont manually, and I don't know how lua objects get converted. I use vim.o.guifont = "Cascadia Code PL,Delugia Nerd Font:h11" in my config. (I think thats right. I'm translating from fennel and don't remember precisely what the lua syntax is). If you wanted to make this dynamic, or bind to a function, I'd achieve that with string concatenation.

For those who did this, and see font family setting both works in nvim and neovide, but the **font size setting doesn't work** for neovide, add a `:` before your font size in your _options.lua_ like
```lua
vim.opt.guifont = { "Source Code Pro", ":h12" }
```

**Comment by mbledkowski** [comment]
@alai Thank you <3

**Comment by umop3plsdn** [comment]
this was exactly my problem! no matter what I did neovide was just HUGE all the time and I was racking my brain but this does the trick!

**Comment by jjaimealeman** [comment]
> For those who did this, and see font family setting both works in nvim and neovide, but the **font size setting doesn't work** for neovide, add a `:` before the font size in your _options.lua_ like:

👍 Thanks, this worked for me!

**Comment by Shaolo** [comment]
On Win10 I had to use an "_" in place of spaces and the colon in the height to make it work.

vim.opt.guifont = { "JetBrains_Mono", ":h10" }

**Comment by DominicCronin** [comment]
On neovim-qt on Windows 11, this worked: 
vim.o.guifont='MesloLGL NFM:h12'

Note the unescaped space, and having to set the height option as a colon-separated element in the string. vim.opt.guifont didn't work, although it would have looked prettier IMO.
