### ISSUE TITLE
Configure Neovide to invoke `lvim` (LunarVim) instead of Neovim

### ISSUE THREAD

**Issue by ruby-rust-perl** [neovide/neovide#1219]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I have installed LunarVim in Windows. So, I'd like `Neovide` to invoke `lvim` instead of `nvim` on startup.

**Comment by clason** [comment]
I'm sorry, but Neovide is a Neovim GUI. If LunarVim is so different from Neovim that it identifies as a different program, I would respect that choice and not try to start it.

**Comment by clason** [comment]
That being said, Neovide already has a `--neovim-bin` option that allows you to specify the location of the Neovim binary to attach to. Depending on what `lvim` actually is, you could try pointing to that.

**Comment by MultisampledNight** [comment]
Actually, that option was not even documented in the Wiki, I'll take care of it.

**Comment by dineshKumar777** [comment]
@ruby-rust-perl You need to edit powershell script as mentioned in https://github.com/LunarVim/LunarVim/issues/1553#issuecomment-920247252

**Comment by Asthestarsfalll** [comment]
Hi, I'm wondering that if neovide is able to run on Windows terminal instead of pop up a new window 
![example](https://user-images.githubusercontent.com/72954905/209425231-0960f5a4-4e94-46df-a965-41c02b84b49e.gif)
expect this:
![example](https://user-images.githubusercontent.com/72954905/209425293-964aec9e-fdf9-4b3f-a3a7-2cd7c6e55767.gif)

**Comment by alber70g** [comment]
Easiest way to do this is to get the config from `lvim` symlinked to `nvim`

Make sure to backup/remove existing config in `~/.config/nvim`

```
ln -s ~/.local/share/lunarvim/lvim ~/.config/nvim
```

**Comment by MultisampledNight** [comment]
@Asthestarsfalll Nope, unfortunately that's not cleanly possible. Neovide creates a whole new GUI window with its own renderer, otherwise cursor effects, smooth scrolling and the like would be very difficult or impossible to implement.

**Comment by xbladesub** [comment]
To run `Neovide` with `lunarvim` you can use shell script. 

```sh
#!/bin/bash
SERVICE="Neovide"
if pgrep -f "$SERVICE" >/dev/null
then
	open /Users/nshv/Repos/neovide/target/release/bundle/osx/Neovide.app
else
	export LUNARVIM_RUNTIME_DIR="${LUNARVIM_RUNTIME_DIR:-"$HOME/.local/share/lunarvim"}"
	export LUNARVIM_CONFIG_DIR="${LUNARVIM_CONFIG_DIR:-"$HOME/.config/lvim"}"
	export LUNARVIM_CACHE_DIR="${LUNARVIM_CACHE_DIR:-"$HOME/.cache/lvim"}"

	cd $HOME

	exec /Users/nshv/Repos/neovide/target/release/bundle/osx/Neovide.app/Contents/MacOS/neovide --frame=none -- -u "$LUNARVIM_RUNTIME_DIR/lvim/init.lua" "$@"
fi
```

Make some keymap on this script and it will open neovide with lunarvim config if neovide instance is not running, otherwise it will bring you to neovide without opening new instance

**Comment by clason** [comment]
If LunarVim used a consistent app name, you could simplify this with `$NVIM_APPNAME` on master.

**Comment by Natzgun** [comment]
In the case of Arch and derivatives there is a neovide AUR package for Lunarvim:
https://aur.archlinux.org/packages/neovide-lunarvim

**Comment by theherk** [comment]
For posterity, there is [How do I use LunarVim in Neovide?](https://www.lunarvim.org/docs/faq#how-do-i-use-lunarvim-in-neovide) in the FAQ.

**Comment by alexlai97** [comment]
this is how i do it
![image](https://github.com/neovide/neovide/assets/17771269/c2fc86c6-b06e-43fa-bfc1-a550300be14b)
