### ISSUE TITLE
Neovide Crashes on opening MacOS

### ISSUE THREAD

**Issue by kaem-e** [neovide/neovide#1229]
**Describe the bug**
Neovide seems to crash if there is anything in your .zshrc file that prints/deletes something in the prompt (in my case i have clear and pfetch statements aswell as a command for iterm2 integration that seem to cause the crash)

**To Reproduce**
1. Go to your .zshrc file
2. Add something like neofetch or smth that outputs something in the terminal
3. Start neovide either via the command neovide or via neovide.app 

**Expected behavior**
neovide should start regularly

**Screenshots**
![image](https://user-images.githubusercontent.com/46230985/155493610-3b20a59c-5be5-4b09-942c-b0bb906b7804.png)
![image](https://user-images.githubusercontent.com/46230985/155493685-b7a71af0-7392-48d8-9114-b86e72ff4534.png)

**Desktop (please complete the following information):**
 - OS: MacOS 12.2.1
 - Neovide Version: 0.6.1
 - Neovim Version 0.8.0

**Please run `neovide --log` and paste the contents of the `.log` file here:**
(neovim is installed and is located in /usr/share/bin and does run as expected, infact with the if statements in .zshrc neovide even runs properly and reports neovide version 0.6.1)

[neovide_rCURRENT.log](https://github.com/neovide/neovide/files/8131306/neovide_rCURRENT.log)
[neovide_r2022-02-24_14-25-43.log](https://github.com/neovide/neovide/files/8131316/neovide_r2022-02-24_14-25-43.log)

**Additional context**
(this log output is after ive disabled the if statements in .zshrc so that the error *does* happen, the if statements are just to work around this specific bug)
![image](https://user-images.githubusercontent.com/46230985/155496044-faa87e4b-dfc0-4108-be54-c2688b504f0e.png)
![image](https://user-images.githubusercontent.com/46230985/155496132-4788c207-83b7-4153-bbd0-a4b9e308609e.png)

**Comment by codeitlikemiley** [comment]
I am also facing this issue, neovide after building from source just crash.
I launch the app from Applications folder, on iterm2, on alacritty
all crash... 
Any fix on this yet?

**Comment by MultisampledNight** [comment]
To be clear: You probably meant Neovide is on version `0.8.0`, at least that's what the log says.

Looking at the log, this line is pretty obvious:

```
INFO [neovide::bridge::command] Starting neovim with: Command { std: "/bin/zsh" "-lc" "\x1bc\x1b[3J\x1b[?7l\x1b[1m\x1b[31m       .:\'\n\[stuff cut out because it's not relevant]shell=zsh\x07/usr/local/bin/nvim --embed", kill_on_drop: false }
```

So stdout gets garbled, confirming the initial cause issued by the OP.

But this is difficult to fix correctly. We can't just rely on stderr instead as that may be affected by any stuff in your shell resource file, too. We cannot not ask the shell for where the binary is, either, as custom $PATH stuff is ignored then.

**Comment by kaem-e** [comment]
yeah sorry haha I confused the neovim and neovide versions, well at least for now I guess encapsulating everything in an if statement in .zshrc does seem to work (though it is a hacky workaround).

hopefully this can be fixed soon tho, it took alot of trial and error to identify the cause

**Comment by kaem-e** [comment]
> I am also facing this issue, neovide after building from source just crash.
> 
> I launch the app from Applications folder, on iterm2, on alacritty
> 
> all crash... 
> 
> Any fix on this yet?

currently you could just delete or comment out your zshrc file or (what i did) put most of it inside an if statement that checks for "safe" terminal emulators (easiest way to do this is to just see what the outputs of $SHELL_PROGRAM and $SHELL) and then only allow them to run if a identified emulator is used (so things like alacrity iterm etc)

**Comment by codeitlikemiley** [comment]
after scanning my .zshrc this is the culprit

```
echo -ne '\e[5 q'
```

**Comment by goldcoders** [comment]
you can try my solution #1230 
to avoid crashing of neovide :)
hope it help you guys!

**Comment by MultisampledNight** [comment]
While your issue solves a lot, @goldcoders, this is an issue with the shell resource file and not with shortcuts or Neovide being bundled.

**Comment by MultisampledNight** [comment]
Actually, nevermind, sorry. It might be a viable workaround.

**Comment by AlQa-hOlic** [comment]
After browsing through a lot of issues and suggestions, I still could not find a solution... However I have confirmed the error is because the PATH variable is dropped when we double click the app from the finder.

I finally ended up creating an Automator application that runs the below script. It finally works when I double click. When I remove the PATH export it shows the same behaviour as before. I understand that this is not the right way to bundle an application but it worked for me.. So maybe wrapping the final executable with a shell script is the way to go?
```zsh
export PATH=/usr/local/bin:$PATH

~/.local/bin/neovide $@
```

**Comment by kaem-e** [comment]
this is a great solution but yeah like you said isn't very useful for launching neovide from within a terminal.

though i imagine most people using neovide also have some form of file browser plugin in their neovim config

**Comment by codeitlikemiley** [comment]
You can try to ser path on. .zshenv since its loaded everytime assuming
your default Shell is zsh

**Comment by scarin** [comment]
you can try this cmd:
neovide --geometry 10x10

it work for me ... save my life

**Comment by lodisy** [comment]
Same ... Neovide quit unexpectedly.

neither the homebrew cask nor the downloaded dmg works..
