### ISSUE TITLE
Cursor is misaligned when using gaps

### ISSUE THREAD

**Issue by Moncheeta** [neovide/neovide#1232]
When I use gaps, the cursor highlighting is offset. So, halfway through the line, you start selecting the line above.

I'm on Neovide Version 0.8.0 and Neovim Version 0.6.1.

You can only see this when you have gaps enabled in your window manager. (I'm currently using DWM)

**Comment by Moncheeta** [comment]
I don't really use gaps anymore but this might be an issue for others.

**Comment by Kethku** [comment]
Can you show a screen cap of this issue? Also whats gaps?

**Comment by Moncheeta** [comment]
The gaps is where there are gaps between the edge of the screen and the application. It is only for customization. I have linked a video. At the beginning, I point the cursor to the gaps. The rest shows how the cursor is misaligned and is highlighting the line below. 

https://user-images.githubusercontent.com/72705603/156908603-d771f359-678b-4802-8e8c-99eb5fb0ac30.mp4

**Comment by Kethku** [comment]
Ah I see. can you try running with multigrid by passing --multigrid as an argument? I don't think this is related to gaps.

**Comment by Moncheeta** [comment]
Yes, that works! Shouldn't multigrid be default?

**Comment by Kethku** [comment]
There's an open pr to enable multigrid by default but it's waiting on fixing a couple more issues. It's a little too slow still unfortunately.

You can enable multigrid semi permanently by setting the NEOVIDE_MULTIGRID environment variable

**Comment by Moncheeta** [comment]
Ok. Thank you!
