### ISSUE TITLE
Crash on startup. Windows 11 Nvidia 511.79

### ISSUE THREAD

**Issue by feature-not-a-bug** [neovide/neovide#1233]
**Describe the bug**
I'm experiencing a crash immediately after startup on Windows 11. Nvidia driver version 511.97

**To Reproduce**
1. Start application
2. App window stops responding immediately

**Expected behavior**
App works normally

**Desktop (please complete the following information):**
 - OS: Version Windows 11 (10.0.22000 Build 22000)
 - Neovide Version 0.8.0
 - Neovim Version 0.6.1

**Please run `neovide --log` and paste the contents of the `.log` file here:**
TRACE [neovide] Neovide version: 0.8.0
INFO [neovide::bridge::command] Starting neovim with: Command { std: "C:\\Users\\Public\\PublicBin\\Neovim\\bin\\nvim.EXE" "--embed", kill_on_drop: false }
DEBUG [neovide::bridge::events] Ignored client type property: "version"
DEBUG [neovide::bridge::events] Ignored client type property: "type"
DEBUG [neovide::bridge::events] Ignored client type property: "methods"
DEBUG [neovide::bridge::events] Ignored client type property: "attributes"
INFO [neovide::bridge::setup] Neovide registered to nvim with channel id 1
INFO [neovide::bridge] Neovim process attached
DEBUG [neovide::settings::window_geometry] Loaded window settings: Windowed { position: PhysicalPosition { x: -1374, y: 1087 }, size: Dimensions { width: 100, height: 30 } }
TRACE [neovide::bridge::handler] Neovim notification: "redraw"
TRACE [neovide::settings] Initial value load failed for cursor_animate_in_insert_mode: Error processing request: 1 - 'Key not found: neovide_cursor_animate_in_insert_mode')
TRACE [neovide::channel_utils] neovide::editor::EditorCommand NeovimRedrawEvent(OptionSet { gui_option: ArabicShape(true) })
TRACE [neovide::channel_utils] neovide::editor::EditorCommand NeovimRedrawEvent(OptionSet { gui_option: AmbiWidth("single") })
TRACE [neovide::channel_utils] neovide::editor::EditorCommand NeovimRedrawEvent(OptionSet { gui_option: Emoji(true) })
TRACE [neovide::editor] Option set ArabicShape(true)
TRACE [neovide::editor] Option set AmbiWidth("single")
TRACE [neovide::editor] Option set Emoji(true)
TRACE [neovide::channel_utils] neovide::editor::EditorCommand NeovimRedrawEvent(OptionSet { gui_option: GuiFont("") })
TRACE [neovide::channel_utils] neovide::editor::EditorCommand NeovimRedrawEvent(OptionSet { gui_option: GuiFontWide("") })
TRACE [neovide::editor] Option set GuiFont("")
TRACE [neovide::channel_utils] neovide::editor::EditorCommand NeovimRedrawEvent(OptionSet { gui_option: LineSpace(0) })
TRACE [neovide::editor] Option set GuiFontWide("")
TRACE [neovide::channel_utils] neovide::editor::EditorCommand NeovimRedrawEvent(OptionSet { gui_option: Unknown("mousefocus", Boolean(false)) })
TRACE [neovide::channel_utils] neovide::editor::EditorCommand NeovimRedrawEvent(OptionSet { gui_option: Pumblend(0) })
TRACE [neovide::editor] Option set LineSpace(0)
TRACE [neovide::editor] Option set Unknown("mousefocus", Boolean(false))
TRACE [neovide::editor] Option set Pumblend(0)
TRACE [neovide::channel_utils] neovide::editor::EditorCommand NeovimRedrawEvent(OptionSet { gui_option: ShowTabLine(1) })
TRACE [neovide::channel_utils] neovide::editor::EditorCommand NeovimRedrawEvent(OptionSet { gui_option: TermGuiColors(true) })
TRACE [neovide::editor] Option set ShowTabLine(1)
TRACE [neovide::editor] Option set TermGuiColors(true)
TRACE [neovide::channel_utils] neovide::editor::EditorCommand NeovimRedrawEvent(OptionSet { gui_option: Unknown("ttimeout", Boolean(true)) })
TRACE [neovide::channel_utils] neovide::editor::EditorCommand NeovimRedrawEvent(OptionSet { gui_option: Unknown("ttimeoutlen", Integer(PosInt(50))) })
TRACE [neovide::channel_utils] neovide::editor::EditorCommand NeovimRedrawEvent(OptionSet { gui_option: Unknown("ext_linegrid", Boolean(true)) })
TRACE [neovide::channel_utils] neovide::editor::EditorCommand NeovimRedrawEvent(OptionSet { gui_option: Unknown("ext_multigrid", Boolean(false)) })
TRACE [neovide::channel_utils] neovide::editor::EditorCommand NeovimRedrawEvent(OptionSet { gui_option: Unknown("ext_hlstate", Boolean(false)) })
TRACE [neovide::channel_utils] neovide::editor::EditorCommand NeovimRedrawEvent(OptionSet { gui_option: Unknown("ext_termcolors", Boolean(false)) })
TRACE [neovide::channel_utils] neovide::editor::EditorCommand NeovimRedrawEvent(DefaultColorsSet { colors: Colors { foreground: Some(Color4f { r: 1.0, g: 1.0, b: 1.0, a: 1.0 }), background: Some(Color4f { r: 0.0, g: 0.0, b: 0.0, a: 1.0 }), special: Some(Color4f { r: 1.0, g: 0.0, b: 0.0, a: 1.0 }) } })
TRACE [neovide::editor] Option set Unknown("ttimeout", Boolean(true))
TRACE [neovide::editor] Option set Unknown("ttimeoutlen", Integer(PosInt(50)))
TRACE [neovide::editor] Option set Unknown("ext_linegrid", Boolean(true))
TRACE [neovide::editor] Option set Unknown("ext_multigrid", Boolean(false))
TRACE [neovide::editor] Option set Unknown("ext_hlstate", Boolean(false))
...

Full log [neovide_rCURRENT.log](https://github.com/neovide/neovide/files/8155684/neovide_rCURRENT.log)

**Additional context**
The application was working previously and this is most likely due to a driver update. I've attempted to rebuild with the latest packages from cargo without success

**Comment by Kethku** [comment]
Can you try building and running a debug build and looking if anything prints to console? Seems like a panic message might help explain whats going on.

**Comment by feature-not-a-bug** [comment]
Tried again with a debug build from a console window, but I'm not getting any output to the console. The GUI window will open and freeze, and CTRL+C will force close the window successfully.

[neovide_rCURRENT.log](https://github.com/neovide/neovide/files/8196237/neovide_rCURRENT.log)
.

**Comment by feature-not-a-bug** [comment]
I was able to do some additional testing and confirm it's related to the latest driver version

1. A build on another computer with the Studio driver worked as expected (this also downgraded to 511.65)
2. Rolling back on the computer where I originally noticed the issue (with Game Ready Driver) also seems to work as expected.

I'm able to retest if a new driver is released

**Comment by feature-not-a-bug** [comment]
Tested with the 512.15 driver and it seems everything is working correctly
