### ISSUE TITLE
Neovide hanging in xorg, seems resolved by using neovide-x11-nt branch in glutin, winit

### ISSUE THREAD

**Issue by manfredlotz** [neovide/neovide#1236]
It happens that neovide hangs in xorg when switching to neovide in Gnome xorg with Super-<num> or in Cinnamon using some other keyboard shortcut. This is not happening in Wayland.

Now I rebuilt neovide by changing `Cargo.toml` like this:

```
glutin = { git = "https://github.com/neovide/glutin", branch = "neovide-x11-nt", features=["serde"] }
winit = { git = "https://github.com/neovide/winit", branch = "neovide-x11-nt" } 
```
and the hang situation is gone.

I thought it might be good to report back here.

**Comment by shekohex** [comment]
Hey any updates on this? any why it is not fixed already?

**Comment by fredizzimo** [comment]
Does this MR fix it https://github.com/neovide/neovide/pull/1789? 

Unfortunately Neovide relies on the new winit keyboard API, which has been work in progress for a long time. So we have not been able to merge in new winit versions. Now there's finally some light in the tunnel, that MR uses a a newer work in progress versions of the keyboard API based on a much newer version of winit. If it works well enough we will probably merge it rather soon, but the branch is not well enough tested yet.

In any case the new keyboard API is planned to be released with the next winit version, with a soft deadline of end of July beginning of August. So at least at that point it should be stable enough for us to switch over to it.

**Comment by shekohex** [comment]
Sounds good, hopefully by that time it would be fixed.
For now, it hangs when I use Super key (while Neovide is focused) to switch to other applications or workspace and then go back to Neovide, it hangs and I have to just switch focus to other application and focus back to Neovide to get it to work again; Which, to be honest, is annoying and not convenient 😔

**Comment by fredizzimo** [comment]
https://github.com/neovide/neovide/pull/1789 has been merged to master. Could you try with that?
