### ISSUE TITLE
Cursor animation is glitchy on the right window with multigrid enabled

### ISSUE THREAD

**Issue by kuba-gaj** [neovide/neovide#1239]
**Describe the bug**
Cursor animation is glitchy on the right window with multigrid enabled, works fine without multigrid.

**To Reproduce**
1. Open 2 vertical splits
2. Focus right split
3. Move up&down using `j` and `k`

**Expected behaviour**
Cursor animation within the right split

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Neovide Version 0.8.0
 - Neovim Version: 0.7.0-dev+1192-g8ed9c84481

https://user-images.githubusercontent.com/3915056/156933754-cf119cd3-dd2b-49b1-a72e-ed37a764d126.mp4

**Comment by kuba-gaj** [comment]
still happening with the latest version. I noticed it also happens in vertical splits. I'm using Wayland (if that helps)

**Comment by s-cerevisiae** [comment]
Also happening on Windows (v0.9).

**Comment by Kethku** [comment]
Closing as I think this is old.
