### ISSUE TITLE
 Neovide is ignoring guifont option

### ISSUE THREAD

**Issue by korsmakolnikov** [neovide/neovide#1241]
Cannot set the font size. It seems neovide is ignoring guifont option. It works in ubuntu ma now I am on arch-based (Manjaro KDE).
In the init.lua I set: 
```lua
local set = vim.opt

set.guifont = 'Fira Code JetBrains Mono Nerd Font:h14'
```

**Expected behavior**
I was expecting changing the size will reflect on neovim... 

**Screenshots**
This is a normal nvim screenshot 
![image](https://user-images.githubusercontent.com/13141364/157658729-27617f34-146d-4bc1-a25a-fe95bd181e6e.png)

And this is neovide 
![image](https://user-images.githubusercontent.com/13141364/157658833-8cb8d985-c051-4960-afcb-98af5c180c7a.png)

 - OS: Linux 5.9.16-1-MANJARO #1 SMP PREEMPT Mon Dec 21 22:00:46 UTC 2020 x86_64 GNU/Linux
 - Neovide Version 0.8.0
 - Neovim Version: NVIM v0.6.1 Build type: Release LuaJIT 2.1.0-beta3 Compiled by builduser Features: +acl +iconv +tui

In the logs, I've spotted these...
```
DEBUG [neovide::renderer::fonts::caching_shaper] Updating font: Fira Code JetBrains Mono Nerd Font:h14
TRACE [neovide::renderer::fonts::font_loader] Loading font FontKey { bold: false, italic: false, family_name: Some("Fira Code JetBrains Mono Nerd Font") }
DEBUG [neovide::renderer::fonts::caching_shaper] Font can't be updated to: Fira Code JetBrains Mono Nerd Font:h14
TRACE [neovide::renderer::grid_renderer] Updated font dimensions: Dimensions { width: 17, height: 34 }
...

**Comment by MultisampledNight** [comment]
I can't seem to find a font called literally `Fira Code JetBrains Mono Nerd Font`, maybe you meant `Fira Code` **or** `JetBrains Mono Nerd Font`? Neovide ignores any font options like font size if it can't find the font.
In normal NeoVim without any frontend, the terminal is responsible for choosing the font, so the `guifont` option has no effect. Which font did you set in your terminal emulator, and which terminal emulator do you use?

**Comment by korsmakolnikov** [comment]
Fira Code definitely. And you were right. 'Fira Code:h10' show me it has now effect. Thank you so much. This app is great. Thank you for your work.
