### ISSUE TITLE
Neovide will not go fullscreen

### ISSUE THREAD

**Issue by cpdf98** [neovide/neovide#1243]
Before going on i would like to preface that I am not entirely sure if this is a bug or a feature that has not been added. I have looked online and have not been able to see anyone talking about this. When pressing F11, Neovide will NOT go fullscreen. It will maximize, sure, but fullscreen doesnt work. It's a small feature, but it is the only thing standing in the way of me using this instead of the terminal version of neovim. If it's a bug, is there any way to fix it? If it is a feature that hasnt been added, are there any plans to add this soon?

**Comment by dineshKumar777** [comment]
Can you try with this

```lua
if vim.g.neovide == true then
    -- vim.cmd 'set guifont=Hack\ NF:h10'
    -- vim.o.guifont='Consolas:h10'
    -- vim.o.guifont='FiraCode NF:h14'
    vim.o.guifont='Operator Mono,FiraCode NF:h14'
    vim.api.nvim_set_keymap('n', '<F11>', ":let g:neovide_fullscreen = !g:neovide_fullscreen<CR>", {})
end
```

**Comment by cpdf98** [comment]
> Can you try with this
> 
> ```lua
> if vim.g.neovide == true then
>     -- vim.cmd 'set guifont=Hack\ NF:h10'
>     -- vim.o.guifont='Consolas:h10'
>     -- vim.o.guifont='FiraCode NF:h14'
>     vim.o.guifont='Operator Mono,FiraCode NF:h14'
>     vim.api.nvim_set_keymap('n', '<F11>', ":let g:neovide_fullscreen = !g:neovide_fullscreen<CR>", {})
> end
> ```

This worked. Thank you!

**Comment by MultisampledNight** [comment]
Yeah, not too sure if Neovide should handle that keybinding while blocking it for NeoVim. Technically someone could have bound their F11 key in their config to something else, and would have no option then to regain that.

**Comment by dineshKumar777** [comment]
@MultisampledNight actually this was discussed before in both discord and discussions. We need some command like fullscreentoggle so that user can bind to keys to there preference.
