### ISSUE TITLE
Renderer screwes up if another application (Discord) hooks into Neovide

### ISSUE THREAD

**Issue by dakyskye** [neovide/neovide#1245]
**Describe the bug**
I wanted to share my Neovide window over Discord but the moment I did that, the moment everything started pixelating and blurring out in Neovide

**To Reproduce**
1. Open Neovide
2. Open "Share Screen" menu in Discord
3. Select Neovide window
4. Move around in Neovide

**Expected behavior**
Neovide should have behaved normally.

**Screenshots**
![neovide_0Q8Cki5SZq](https://user-images.githubusercontent.com/32128756/158483671-08847fb2-308f-45be-b80f-5c4a8499ef2c.gif)

**Desktop (please complete the following information):**
 - OS: Windows 11 (Version 21H2 - OS Build 22000.556)
 - Neovide Version: Neovide 0.8.0 (I have built it from source without any modification)
 - Neovim Version: NVIM v0.6.1

**Please run `neovide --log` and paste the contents of the `.log` file here:**
[neovide_rCURRENT.log](https://gist.github.com/dakyskye/571994616f72bd648c6ddceb90d16d86)

**Comment by TheButlah** [comment]
I also have this bug. I am on windows 11 btw.

**Comment by Kethku** [comment]
I can't reproduce this on current main and updated discord. Please reopen if issues persist.
