### ISSUE TITLE
unable to start neovide

### ISSUE THREAD

**Issue by Felix-Kyun** [neovide/neovide#1248]
**Describe the bug**
unable to open neovide after installing

**To Reproduce**
1. install neovide (i installed it from snap store)
2. open neovide 

**Expected behavior**
it should start normally

**Desktop (please complete the following information):**
 - OS: ubuntu 20.04
 - Neovide Version: 0.8.0
 - Neovim Version: 0.6.0

``
 thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: CreationErrors([NoAvailablePixelFormat, OsError("Couldn't find any available vsync extension")])', src/window/window_wrapper/mod.rs:287:10
``

i do get some other error but that doesnt seen to be the problem here anyways complete logs:
```xkbcommon: ERROR: /snap/neovide/132/usr/share/X11/locale/iso8859-1/Compose:84:34: string literal is not a valid UTF-8 string
xkbcommon: ERROR: /snap/neovide/132/usr/share/X11/locale/iso8859-1/Compose:85:29: string literal is not a valid UTF-8 string
xkbcommon: ERROR: /snap/neovide/132/usr/share/X11/locale/iso8859-1/Compose:86:29: string literal is not a valid UTF-8 string
xkbcommon: ERROR: /snap/neovide/132/usr/share/X11/locale/iso8859-1/Compose:87:29: string literal is not a valid UTF-8 string
xkbcommon: ERROR: /snap/neovide/132/usr/share/X11/locale/iso8859-1/Compose:88:29: string literal is not a valid UTF-8 string
xkbcommon: ERROR: /snap/neovide/132/usr/share/X11/locale/iso8859-1/Compose:89:27: string literal is not a valid UTF-8 string
xkbcommon: ERROR: /snap/neovide/132/usr/share/X11/locale/iso8859-1/Compose:90:27: string literal is not a valid UTF-8 string
xkbcommon: ERROR: /snap/neovide/132/usr/share/X11/locale/iso8859-1/Compose:91:27: string literal is not a valid UTF-8 string
xkbcommon: ERROR: /snap/neovide/132/usr/share/X11/locale/iso8859-1/Compose:92:27: string literal is not a valid UTF-8 string
xkbcommon: ERROR: /snap/neovide/132/usr/share/X11/locale/iso8859-1/Compose:93:29: string literal is not a valid UTF-8 string
xkbcommon: ERROR: /snap/neovide/132/usr/share/X11/locale/iso8859-1/Compose:94:29: string literal is not a valid UTF-8 string
xkbcommon: ERROR: /snap/neovide/132/usr/share/X11/locale/iso8859-1/Compose:94:29: too many errors
xkbcommon: ERROR: /snap/neovide/132/usr/share/X11/locale/iso8859-1/Compose:94:29: failed to parse file

thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: CreationErrors([NoAvailablePixelFormat, OsError("Couldn't find any available vsync extension")])', src/window/window_wrapper/mod.rs:287:10```

**Comment by MultisampledNight** [comment]
Thanks for reporting! What GPU and which driver version do you run on?

**Comment by Felix-Kyun** [comment]
i am using intel integrated gpu.

**Comment by MultisampledNight** [comment]
That's unfortunately still quite a large range of possible GPUs; would you mind mentioning the exact CPU?

**Comment by Felix-Kyun** [comment]
```❯ lscpu
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   36 bits physical, 48 bits virtual
CPU(s):                          2
On-line CPU(s) list:             0,1
Thread(s) per core:              1
Core(s) per socket:              2
Socket(s):                       1
NUMA node(s):                    1
Vendor ID:                       GenuineIntel
CPU family:                      6
Model:                           23
Model name:                      Pentium(R) Dual-Core  CPU      E6700  @ 3.20GHz
Stepping:                        10
CPU MHz:                         3191.810
CPU max MHz:                     3200.0000
CPU min MHz:                     1596.0000
BogoMIPS:                        6383.62
Virtualization:                  VT-x
L1d cache:                       64 KiB
L1i cache:                       64 KiB
L2 cache:                        2 MiB
NUMA node0 CPU(s):               0,1
Vulnerability Itlb multihit:     KVM: Mitigation: VMX disabled
Vulnerability L1tf:              Mitigation; PTE Inversion; VMX EPT disabled
Vulnerability Mds:               Vulnerable: Clear CPU buffers attempted, no microcode; SMT disabled
Vulnerability Meltdown:          Mitigation; PTI
Vulnerability Spec store bypass: Vulnerable
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Retpolines, STIBP disabled, RSB filling
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat ps
                                 e36 clflush dts acpi mmx fxsr sse sse2 ht tm pbe syscall nx lm const
                                 ant_tsc arch_perfmon pebs bts rep_good nopl cpuid aperfmperf pni dte
                                 s64 monitor ds_cpl vmx est tm2 ssse3 cx16 xtpr pdcm xsave lahf_lm pt
                                 i tpr_shadow vnmi flexpriority vpid dtherm```

**Comment by Flawm** [comment]
I had issues as well, but I was able to cobble together a cheap fix. Admittedly I didn't look into glutin to know why it's happening, I'm just happy it's working.

I think #643 #1081 and a few others could benefit from this dummy retry, although it's a very non-rust-like way of error handling. What I mean is: it string matches an error from glutin. See https://github.com/Flawm/neovide/commit/1a7a524991e5b7b45c22b43db5b85ed8357bfaa1 for the patch, I can make a PR as well but I don't think this is the 'proper' fix

**Comment by IS2511** [comment]
Still crashes! Why is there no error handling for vsync failing? 
This is a major problem, a good install can just not work and print no errors. This should be critical.

Generally same logs:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: CreationErrors([NoAvailablePixelFormat, OsError("Couldn't find any available vsync extension")])', src/window/mod.rs:352:10
```
Graphics hardware: `AMD Ryzen 5 4500U with Radeon Graphics`

**Comment by Flawm** [comment]
@IS2511 did you try my patch? It fixes it on my machine ¯\\_(ツ)\_/¯

**Comment by MultisampledNight** [comment]
> I had issues as well, but I was able to cobble together a cheap fix. Admittedly I didn't look into glutin to know why it's happening, I'm just happy it's working.
> 
> I think #643 #1081 and a few others could benefit from this dummy retry, although it's a very non-rust-like way of error handling. What I mean is: it string matches an error from glutin. See [Flawm@1a7a524](https://github.com/Flawm/neovide/commit/1a7a524991e5b7b45c22b43db5b85ed8357bfaa1) for the patch, I can make a PR as well but I don't think this is such a 'proper' fix.
> 
> cc @MultisampledNight for triage

Thank you! I'll try to create a more fleshed out version of that now and PR it in.

**Comment by MultisampledNight** [comment]
All users who are affected by this issue, could you please test out PR #1523 and report back? Maybe you also need to pass `--nosrgb` to Neovide.

**Comment by golanguage** [comment]
@MultisampledNight Thanks! This PR works for me.

**Comment by MultisampledNight** [comment]
Alright, thank you! I'll merge it (after preparing some other things).
