### ISSUE TITLE
Fontfeatures support

### ISSUE THREAD

**Issue by Avimitin** [neovide/neovide#1249]
**Is your feature request related to a problem? Please describe.**

I've enabled font features for Cascadia Code through the fontconfig.

![image](https://user-images.githubusercontent.com/30021675/159198278-5f1388fc-9165-4637-9a66-2e00c574548a.png)

So when using cascadia code italic font, I can get this cursive style.

However it seems like neovide doesn't recognize those feature yet.

![image](https://user-images.githubusercontent.com/30021675/159198439-80c84850-9033-4078-b6c0-702bd833683b.png)

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by dineshKumar777** [comment]
Provide the neovide font config which you used. I will try to reproduce this in my local and update the status

**Comment by Avimitin** [comment]
Try this: https://github.com/Avimitin/Avimitin/blob/master/fontconfig/conf.d/47-font-features.conf

**Comment by MultisampledNight** [comment]
Just a note, Neovide doesn't interact with `freetype2` and not with `fontconfig`, either. It uses `swash` for text rendering instead, so your `fontconfig` stuff won't be applied.

**Comment by Avimitin** [comment]
So will neovide support fontconfig? Fontconfig is widely used in Linux.

**Comment by Avimitin** [comment]
It seems like swash itself did support opentype fontfeature: https://github.com/dfrg/swash/blob/master/src/feature/util.rs#L46

**Comment by khjorth** [comment]
Are there any workarounds for this issue?

**Comment by Kethku** [comment]
This was implemented in https://github.com/neovide/neovide/pull/2213
