### ISSUE TITLE
Neovide dosent take xdotool input / windows emoji input

### ISSUE THREAD

**Issue by Lite5h4dow** [neovide/neovide#1252]
**Describe the bug**
nothing happens when trying to type something into neovide via xdotool e.g. emoji from an emoji picker like rofimoji

nothing happens when trying to input an emoji with the emoji picker in windows (start+;) interestingly, 0.5.0 works fine with the emoji input

**To Reproduce**
1. Open Neovide
2. Switch to Insert mode
3. Insert something with xdotool (in my case an emoji)
4. nothing happens

**Expected behavior**
character is placed just like it is in the terminal using nvim.

**xdo Arch Linux:**
 - OS: Arch Linux (xdo)
 - Neovide Version: 0.8.0
 - Neovim Version: 0.6.1

**Windows Emoji Picker:**
- OS: Windows 11 (windows emoji picker)
- Neovide Version: 0.7.0
- Neovim Version: 0.6.1

**Please run `neovide --log` and paste the contents of the `.log` file here:**
https://0bin.net/paste/RoEhlWls#BmdVm1pvXyEkK6G19IUdpl7KCu6DfNE2Vmtk4gVXzwh

**Additional context**

**Comment by Lite5h4dow** [comment]
@Hubro no im using x. im in BSPWM

**Comment by fredizzimo** [comment]
I'm pretty sure this is fixed in 0.11 and 0.12 with the winit and input updates, but if not, please re-open.
