### ISSUE TITLE
telescope.nvim preview window disappeared

### ISSUE THREAD

**Issue by Rongjianying** [neovide/neovide#1256]
**Describe the bug**
telescope.nvim preview window disappeared when I set `layout_strategy = "vertical"`, it has no problem when `layout_strategy = "horizontal"`

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS 12.2.1
 - Neovide Version 0.8.0
 - Neovim Version v0.7.0-dev+1280-gf2e5f509d

**Please run `neovide --log` and paste the contents of the `.log` file here:**

**Additional context**

**Comment by Hubro** [comment]
I assume you've tested that the same thing doesn't happen in Neovim in the terminal?

**Comment by Rongjianying** [comment]
this only appears several times, not a stable issue, I will close this one, thx~~~
