### ISSUE TITLE
Neovide does not load after AUR update

### ISSUE THREAD

**Issue by Suyashtnt** [neovide/neovide#1258]
**Describe the bug**
After running a full system upgrade including the AUR version of neovide (compiled from source) I get this error now:

```
nvim on  main [!?] via 🌙 v5.4.4
❯ RUST_BACKTRACE=full neovide --nofork
libEGL warning: DRI3: Screen seems not DRI3 capable
libEGL warning: DRI2: failed to authenticate
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: CreationErrors([NoAvailablePixelFormat, OsError("GL context creation failed")])', src/window/mod.rs:330:10
stack backtrace:
   0:     0x556837d6629a - <unknown>
   1:     0x556837bc24fc - <unknown>
   2:     0x556837d38e44 - <unknown>
   3:     0x556837d67505 - <unknown>
   4:     0x556837d6837a - <unknown>
   5:     0x556837d67e58 - <unknown>
   6:     0x556837d67dd6 - <unknown>
   7:     0x556837d67d92 - <unknown>
   8:     0x556837b3b990 - <unknown>
   9:     0x556837b3bc62 - <unknown>
  10:     0x556837c3903c - <unknown>
  11:     0x556837c345c7 - <unknown>
  12:     0x556837c84293 - <unknown>
  13:     0x556837c67a23 - <unknown>
  14:     0x556837c82ee1 - <unknown>
  15:     0x7f23b8a78310 - __libc_start_call_main
  16:     0x7f23b8a783c1 - __libc_start_main@GLIBC_2.2.5
  17:     0x556837b54065 - <unknown>
  18:                0x0 - <unknown>
```

**To Reproduce**
1. install "neovide-git" from the AUR
2. run neovide with `--nofork` to see error

**Expected behavior**
It to launch properly

**Screenshots**

**Desktop (please complete the following information):**
 - Arch running kernel 5.16.16
 - Neovide Version 0.8.0 (build from source)
 - Neovim Version v0.7.0-dev+1328-gfb5587d2b

**Please run `neovide --log` and paste the contents of the `.log` file here:**
*empty log*

**Additional context**
This only happened after I upgraded

**Comment by Suyashtnt** [comment]
it just fixed itself somehow

**Comment by LoipesMas** [comment]
I think some applications fail to open after upgrading graphics drivers. I don't think it's specific to Neovide, probably just a quirk of linux/x11/nvidia linux drivers. However, a reboot always fixes this for me.
