### ISSUE TITLE
Input does not work after window align on GNOME

### ISSUE THREAD

**Issue by KonradHoeffner** [neovide/neovide#1260]
**To Reproduce**
1. open neovide
2. press <kbd>ALT</kbd>+<kbd>Left</kbd> or <kbd>ALT</kbd>+<kbd>Right</kbd>
3. press any keys
4. nothing happens

**Expected behavior**
As the window is still in focus, as shown by the cursor that is fully filled with white, the cursor should react.

**Desktop (please complete the following information):**
 - OS: Arch Linux with GNOME Shell 41.5 on X11
 - Neovide Version 0.8.0 from the AUR package neovide-git
 - Neovim Version 0.6.1

**Please run `neovide --log` and paste the contents of the `.log` file here:**
[neovide_rCURRENT.log](https://github.com/neovide/neovide/files/8424756/neovide_rCURRENT.log)

**Comment by kirillrdy** [comment]
I can confirm that this is still an issue with 0.8.0 but only when using X11, but not when using wayland

**Comment by tobealive** [comment]
Yes, it's a pain.

Using a window manager most of the time whenever switch a window and coming back to a neovide instance it's just this issue.
I mean it's working again after quickly e.g. alt-tabbing in / out of the window or even quicker toggling a launcher on and off.   

That's still some hundred unnecessary extra key presses daily. Wayland is unfortunately not that far to support all the features I would like to have for a good workflow experience. Hope there is a fix for this!

**Comment by Alex-vZyl** [comment]
Still an issue for me too.

**Comment by fredizzimo** [comment]
I think the new winit update that we just merged in https://github.com/neovide/neovide/pull/1789 might have fixed the problem. Could you try again with Neovide master?

**Comment by tobealive** [comment]
> I think the new winit update that we just merged in #1789 might have fixed the problem. Could you try again with Neovide master?

Fixes it for me. Thanks for your work!
