### ISSUE TITLE
Windows 11 crash if launched with a negative X coordinate in neovide-settings.json

### ISSUE THREAD

**Issue by feature-not-a-bug** [neovide/neovide#1261]
**Describe the bug**
I'm getting a consistent crash when neovide tries to start on my second or third monitors, both of which are to the left of my primary monitor. This creates a neovide-settings.json file that contains a negative X coordinate which seems to be the cause of the issue.

`{"window":{"Windowed":{"position":{"x":-1663,"y":394},"size":{"width":100,"height":40}}}}`

If I delete this file or change the value to a positive number neovide will start on my primary monitor without a problem.

**To Reproduce**
1. Move the neovide window to the left of the primary display
2. Close neovide so that the neovide-settings.json file is written with a negative X coordinate
3. Open neovide
4. Window for neovide appears but doesn't conform to the geometry in neovide-settings.json and the main window is completely white. Interacting will cause the window to disable and title bar to show **Not Responding**

**Expected behavior**
Neovide should be able to launch on any monitor

**Desktop (please complete the following information):**
 - OS: Windows 11 Version 10.0.22000 Build 22000
 - Neovide Version 0.8.0
 - Neovim Version 0.6.1

**Please run `neovide --log` and paste the contents of the `.log` file here:**
[neovide_rCURRENT.log](https://github.com/neovide/neovide/files/8429538/neovide_rCURRENT.log)

**Comment by feature-not-a-bug** [comment]
I did a little debugging and it seems like this is happening in the `src/window/mod.rs` call to `swap_buffers`. Specifically the unsafe call to `SwapBuffers(self.hdc)` fails to return in the following glutin function:

```
    #[inline]
    pub fn swap_buffers(&self) -> Result<(), ContextError> {
        // TODO: decide how to handle the error
        // if unsafe { SwapBuffers(self.hdc) } != 0 {
        // Ok(())
        // } else {
        // Err(ContextError::IoError(std::io::Error::last_os_error()))
        // }
        unsafe { SwapBuffers(self.hdc) };
        Ok(())
    }
```

**Comment by MultisampledNight** [comment]
Yeah, I can imagine this being yet another issue which could be solved by using upstream winit/glutin. Unfortunately we can't just deny a negative X coordinate though, theoretically some X on Linux setups could set their `0,0` point to be somewhere in the middle of the (virtual) screen.

**Comment by feature-not-a-bug** [comment]
I think in my case the negative coordinate is valid too. The following rough diagram shows how my monitors are oriented:
![monitors](https://user-images.githubusercontent.com/19642535/168316598-4822e9f9-6c9f-4ea1-9151-c7cb2475655c.png)

So the `(0,0)` origin point is at the top left of monitor 1. Any position on monitor 1 will have zero or positive coordinates and the app starts correctly. Monitor 2 will always produce a negative x position and monitor 3 will have a negative x and y position and on either of these the app will not start successfully.

My preference would be to always have neovide running on monitor 2, but currently I have to move it back to monitor 1 before closing or wipe the settings file then move it back to monitor 2 on the next run. I don't have a windowed Linux environment I can test on right now, but I can try to get one set up in the next few days to see if I can recreate this there. That said, the workaround is only a minor annoyance now that I know how to reproduce the crash.

**Comment by LoipesMas** [comment]
> but currently I have to move it back to monitor 1 before closing or wipe the settings file then move it back to monitor 2 on the next 

A better (but still temporary) fix would be to just add `let g:neovide_remember_window_position=v:false` to your nvim config.

**Comment by feature-not-a-bug** [comment]
Thank you - this really simplifies the issue. Now I can start neovide and use an autohotkey script to move it into the correct position

**Comment by feature-not-a-bug** [comment]
I just updated to main and it seems like this is no longer happening.
