### ISSUE TITLE
[Windows 10] Neovide does literally nothing

### ISSUE THREAD

**Issue by itsrxmmy** [neovide/neovide#1264]
**Describe the bug**
When opened through the commandline (I moved it to the same directory as my neovim, so system path shouldnt be an issue) via "neovide" or alias "nvide", it just prints a new line and does nothing. When opened via file explorer, nothing opens.

**To Reproduce**
1. Type binary name "neovide" in command prompt or alias (i duplicated neovide and named the copy nvide for convenience) "nvide" 

**Expected behavior**
Neovide opens

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10 Home Version 21H2 OS Build 19044.1586
 - Neovide Version [0.5.0](https://github.com/neovide/neovide/releases/tag/0.5.0)
 - Neovim Version 0.6.1

**Please run `neovide --log` and paste the contents of the `.log` file here:**
Cant because neovide doesnt open

**Additional context**

**Comment by dineshKumar777** [comment]
@itsrxmmy Neovide 0.5 is older version. Please try out latest neovide(0.8) by building from source or download executable for following actions page.
https://github.com/neovide/neovide/actions/runs/2091094263

**Comment by itsrxmmy** [comment]
It worked. But may I ask; if 0.5 is the older version why is 0.5 the latest release?

![chrome_ZOaUHx63qU](https://user-images.githubusercontent.com/81774732/162843973-d92f59f3-603d-4dbc-b0d0-6c3044c7f34c.png)

**Comment by MultisampledNight** [comment]
We've been trying to get a new release for a while, but we always hung up on features we "just wanted to get in". This time we seem to be coming to a conclusion though, a new release is incoming.
