### ISSUE TITLE
Make floating blur amount configurable

### ISSUE THREAD

**Issue by Hubro** [neovide/neovide#1265]
**Is your feature request related to a problem? Please describe.**

I've recently started using the zen-mode.nvim plugin, which (when enabled) places the current buffer as a floating window covering the entire screen.

Unfortunately, since Neovide makes the background of floating windows transparent, I can still see everything, although it's slightly blurred:

![image](https://user-images.githubusercontent.com/597206/162729398-cfbc2b16-1e9c-48b6-8930-59b6bca7aee6.png)

**Describe the solution you'd like**

This would probably look awesome if I could just increase the blur amount so the background contents were less distracting. At this blur amount, I can basically still read the background text.

**Describe alternatives you've considered**

I could disable transparency altogether, but that means I would lose out on some of the eye candy that I use Neovide for.

**Additional context**

Would this involve just adding another config option (i.e. `g:neovide_floating_blur_amount = x`) and passing it in here?

https://github.com/neovide/neovide/blob/main/src/renderer/rendered_window.rs#L258

Would there be any reason to expose both blur values? (I assume they mean blur amount in the X and Y axes.) Would that enable some cool effects?

**Comment by MultisampledNight** [comment]
The facility is there:

https://github.com/neovide/neovide/blob/e2e4f5a74477692596c36d31bd19ba841c12f870/src/renderer/rendered_window.rs#L258

And it may just be another config value. About separate config values for X and Y blur, try it out in GIMP, this is with 5px on X and 25 px blur on Y:

![blur-directions](https://user-images.githubusercontent.com/80128916/166269815-768e3c27-fc1c-432c-b3ae-38ff0ddac4ba.png)

If it looks good to you, it'd be no problem to implement it. But I'm not sure how usable that actually is.

**Comment by Hubro** [comment]
@MultisampledNight That looks funky :smile: Might look cool if the blur was stronger and the background was less transparent though.

In any case, I primarily just want to increase the blur amount.

**Comment by MultisampledNight** [comment]
Alright, sorry for the delay, I'll do a quick (5 line) implementation, upload it on my fork and do a quick PR.
