### ISSUE TITLE
Neovide using UNC paths that cant be understood or executed by WSL

### ISSUE THREAD

**Issue by Lite5h4dow** [neovide/neovide#1271]
**Describe the bug**
Neovide Passing windows UNC Paths to nvim plugins

**To Reproduce**
1. install [LspInstall](https://github.com/williamboman/nvim-lsp-installer)
2. attempt to install a package that relies on node (typescript server for example)
3. See error

**Expected behavior**
installation should recieve local wsl path, not windows UNC Path, nothing outside explorer has permissions to UNC paths.

**Screenshots**
cannot install to path
![image](https://user-images.githubusercontent.com/18059545/162980519-44eaf863-7d89-4da5-afc9-c25e54ab0e1f.png)

cannot read from path (installed via nvim in wsl confirming this isnt an issue with the plugin or wsl)
![image](https://user-images.githubusercontent.com/18059545/162980688-00546ce9-5075-49cd-96c7-a4f71fd2c656.png)

**Desktop (please complete the following information):**
 - OS: Windows 11 (Microsoft Windows [Version 10.0.22000.556])
 - Neovide Version: 0.8.0
 - Neovim Version: 0.6.0

**Please run `neovide --log` and paste the contents of the `.log` file here:**
[neovide_rCURRENT.log](https://github.com/neovide/neovide/files/8473670/neovide_rCURRENT.log)

**Additional context**
i was able to replicate the error from powershell as linux does not see backslash paths as paths (this may be part of the issue?)
powershell log:
```
╭─    ~                                                                                                                                                       ERROR  15:02:33  ─╮
╰─ cd '\\wsl.localhost\Arch\mnt\c\Users\storm\scoop\apps\nvm\current\nodejs\nodejs\node_modules\npm\bin'                                                                                ─╯
Set-Location: Access to the path '\\wsl.localhost\Arch\mnt\c\Users\storm\scoop\apps\nvm\current\nodejs\nodejs\node_modules\npm\bin' is denied.
Set-Location: Cannot find path '\\wsl.localhost\Arch\mnt\c\Users\storm\scoop\apps\nvm\current\nodejs\nodejs\node_modules\npm\bin' because it does not exist.
```

either way we shouldnt be using UNC Paths....

**Comment by Lite5h4dow** [comment]
this is not urgent, i did manage to hardcode a installation directory circumventing this issue, but its worth a look.

**Comment by fredizzimo** [comment]
You need to ensure that your paths are configured correctly. Generally, you can't run a windows lsp from WSL, nor Windows npm, as is the case here. The WSL npm needs priority, see this general discussion for more information
* https://github.com/neovide/neovide/discussions/2267

This is a configuration problem, not a Neovide bug, so closing.
