### ISSUE TITLE
[Question] How to resize font

### ISSUE THREAD

**Issue by TornaxO7** [neovide/neovide#1272]
As the title says, I'm wondering how I can resize the font dynamically in neovide. I can use `Ctrl` + `+` in order to increase the font size in my terminal. Is that also possible in neovide?

**Comment by MultisampledNight** [comment]
In #856 the OP had this snippet for the resize function itself:

```vim
let s:guifontsize = 10
let s:guifont = "JetBrainsMono\\ Nerd\\ Font"

function! AdjustFontSize(amount)
  let s:guifontsize = s:guifontsize+a:amount
  exe "set guifont=" .. s:guifont .. ":h" .. s:guifontsize
endfunction
```

Is that enough for your purposes? You could map that function to `<C-+>` or `<C-minus>` I guess.

**Comment by TornaxO7** [comment]
> Fair enough, I referred to the function.

Oh, well since I can't use a string it doesn't look like that I can use this function.

**Comment by MultisampledNight** [comment]
You can use a string. The `\` in there are only for escaping purposes. Your working example will work just fine, the variable is only about having the option locally available.

**Comment by MultisampledNight** [comment]
(offloaded the discussion to Discord, closing)

**Comment by TornaxO7** [comment]
Alright, I have the following settings:

```vim
let s:guifontsize=10
let s:guifont="Fira\\ Code\\ SemiBold"
set guifont=Fira\ Code\ SemiBold:h13

let g:neovide_refresh_rate=60
let g:neovide_transparency=0.8
let g:neovide_no_idle=v:false
let g:neovide_fullscreen=v:false
let g:neovide_cursor_animation_length=0.20
let g:neovide_cursor_trail_length=0.5
let g:neovide_cursor_antialiasing=v:true
let g:neovide_cursor_vfx_mode = "ripple"
let g:neovide_cursor_vfx_opacity=200.0
let g:neovide_cursor_vfx_particle_lifetime=1.2
let g:neovide_cursor_vfx_particle_density=7.0
let g:neovide_cursor_vfx_particle_speed=10.0
let g:neovide_cursor_vfx_particle_phase=1.5
let g:neovide_cursor_vfx_particle_curl=1.0

function! AdjustFontSize(amount)
    let s:guifontsize = s:guifontsize + a:amount
    execute "set guifont=" .. s:guifont .. ":h" .. s:guifontsize
endfunction

nnoremap <C-+> <cmd>call AdjustFontSize(+1)<cr>
nnoremap <C--> <cmd>call AdjustFontSize(-1)<cr>
```
thanks!

**Comment by distek** [comment]
Not sure if this was a thing at the time of this issue, but this is how I'm doing it now:
```lua
local map = vim.keymap.set

local function neovideScale(amount)
	local temp = vim.g.neovide_scale_factor + amount

	if temp < 0.5 then
		return
	end

	vim.g.neovide_scale_factor = temp
end

map("n", "<C-=>", function()
	neovideScale(0.1)
end)

map("n", "<C-->", function()
	neovideScale(-0.1)
end)
```

**Comment by Palsmo** [comment]
This works flawlessly and is the simplest solution, hope it helps!
```lua
if vim.g.neovide then
    map.set({ "n", "v" }, "<C-+>", ":lua vim.g.neovide_scale_factor = vim.g.neovide_scale_factor + 0.1<CR>", { silent = true })
    map.set({ "n", "v" }, "<C-->", ":lua vim.g.neovide_scale_factor = vim.g.neovide_scale_factor - 0.1<CR>", { silent = true })
    map.set({ "n" , "v" }, "<C-0>", ":lua vim.g.neovide_scale_factor = 1<CR>", { silent = true })
end
```

**Comment by max2000warlord** [comment]
> This works flawlessly and is the simplest solution, hope it helps!
> 
> ```lua
> if vim.g.neovide then
>     map.set({ "n", "v" }, "<C-+>", ":lua vim.g.neovide_scale_factor = vim.g.neovide_scale_factor + 0.1<CR>")
>     map.set({ "n", "v" }, "<C-->", ":lua vim.g.neovide_scale_factor = vim.g.neovide_scale_factor - 0.1<CR>")
>     map.set({ "n" , "v" }, "<C-0>", ":lua vim.g.neovide_scale_factor = 1<CR>")
> end
> ```

What file is that in?
