### ISSUE TITLE
[Question] How to do this in Neovide?

### ISSUE THREAD

**Issue by Fizzify** [neovide/neovide#1273]
So basically, I am using Windows 11 with Windows Terminal. For some reason when I run the command "neovide", it opens a separate window for Neovide, but in Neovim it runs in terminal and not in a separate window, anyone know how to make Neovide be able to run in terminal without making it run in a separate window?

First picture = Neovide
Second picture = Neovim in terminal

![image](https://user-images.githubusercontent.com/79361847/163120994-8cf93239-bc1c-46fa-90a4-84a33fbd1633.png)

![image](https://user-images.githubusercontent.com/79361847/163120971-12d3dd2e-4d5c-448e-9585-633bbcea96c0.png)

**Comment by MultisampledNight** [comment]
Neovide is a graphical application, not a TUI one. A TUI would make it impossible/very difficult to implement visual features such as cursor trails and particles. As such, unfortunately that's impossible.

As a workaround (if your workflow allows it), you can use `:terminal` to let Neovide act as Terminal.

**Comment by Fizzify** [comment]
That's unfortunate, oh well. Is there any way to lower or decrease the opacity of the window or the background to make it look like the one in my terminal?

**Comment by MultisampledNight** [comment]
There is a setting called `neovide_transparency`, see https://github.com/neovide/neovide/wiki/Configuration#transparency. As far as I'm aware that won't issue the fancy background blur effect which the Windows Terminal has though.

**Comment by MultisampledNight** [comment]
Can I close this issue? Or is there anything else open?

**Comment by Fizzify** [comment]
Alright thanks. You can close it now.
