### ISSUE TITLE
neovide UI is very big

### ISSUE THREAD

**Issue by rudrrayan** [neovide/neovide#1274]
**Describe the bug**
The UI in neovide is very big, even if I don't use an init.vim or if I set a guifont

**To Reproduce**
run the latest version of neovide

**Expected behavior**
it should have a reasonable UI size or follow the font size set. even without any set font size its huge

**Screenshots**
![image](https://user-images.githubusercontent.com/47331292/163380066-c40311ca-fadf-4840-8afb-9c8f8ef923c9.png)

**Desktop (please complete the following information):**
 - OS: [e.g. macOS 11.4]
 - Neovide Version [e.g. 0.6.0]
 - Neovim Version [e.g. 0.5.0]

**Please run `neovide --log` and paste the contents of the `.log` file here:**
*This one is without any init.vim*
https://pastebin.com/nqgYC0MW

**Additional context**
I have a pretty lengthy nvim config, and a hacky way of implementing transparency.

**Comment by MultisampledNight** [comment]
Changing the default font is pretty difficult, unfortunately. Some people might be fine with the way the current default is (me, for example).

Your issue description is a bit confusing, though. You mention that Neovide should follow the font size set: but it already does, try out `Fira_Code:h8`. Or did you try that and it didn't work?

**Comment by dineshKumar777** [comment]
As per following code , default size is set to 14. Maybe we can set it to 12, as a default.
![image](https://user-images.githubusercontent.com/21097695/163595095-12901c39-d80b-492d-877e-cb235a32c012.png)

But you mentioned even after custom guifont configuration you are facing this issue. Can you share your neovide font config??

Also you are using old version of neovide. Please use latest (0.8.0)

**Comment by taylor85345** [comment]
I can confirm this same issue using a freshly installed neovide-git 0.8.0 from the AUR

**Comment by taylor85345** [comment]
disregard. I'm using doom-vim, and apparently they had size 15 font as the guifont default

**Comment by rudrrayan** [comment]
> As per following code , default size is set to 14. Maybe we can set it to 12, as a default. ![image](https://user-images.githubusercontent.com/21097695/163595095-12901c39-d80b-492d-877e-cb235a32c012.png)
> 
> But you mentioned even after custom guifont configuration you are facing this issue. Can you share your neovide font config??
> 
> Also you are using old version of neovide. Please use latest (0.8.0)

I am using this font setting `set guifont=Terminus\ 12`.
The issue still persists with this setting and numerous other guifonts I have tried, and know, are available on my PC. 
Hope this gets fixed soon :D

**Comment by MultisampledNight** [comment]
You're using `guifont` not in the way Neovide expects, read `:h guifont`. You probably meant to use `set guifont=Terminus:h12` instead.

**Comment by rudrrayan** [comment]
Apologies everyone! @MultisampledNight 's suggestion was the root behind this!
However, the error with having such a large default ui scale/font size is still quite odd though, so perhaps the issue should still be left open?

**Comment by MultisampledNight** [comment]
See the previous messages. The default font works fine for some, and changing the default introduces inconsistency.

**Comment by dineshKumar777** [comment]
@rudrrayan  noticed you are using older version of neovide. use 0.8.0. 
Font size may look different based on your  monitor resolution and DPI settings etc. as @MultisampledNight said deafult font size works fine with me too.

**Comment by dineshKumar777** [comment]
closing this.
