### ISSUE TITLE
Window is empty after suspending and awakening

### ISSUE THREAD

**Issue by Robertleoj** [neovide/neovide#1277]
**Describe the bug**
After suspending my computer and reawaken it, nothing is rendered inside neovide, the whole window is the background color. 

However, when I move the cursor, the line that the cursor is on is re-rendered, but the rest remains unrendered. 

I am on Ubuntu 20.04 LTS, using the default Gnome that comes with it. 

**To Reproduce**
1. Open neovide, and open any buffer.
2. Suspend the machine.
3. Awaken the machine.

**Expected behavior**
Neovide is rendering the same content as before I suspended.

**Screenshots**
This is neovide before suspending:
![neovide_bug_1](https://user-images.githubusercontent.com/47485105/163734868-0d17335c-b504-42cc-92ec-39f276e40c70.png)

After suspending and reawakending:
![neovid_bug_2](https://user-images.githubusercontent.com/47485105/163734909-48f9a814-ae06-46a8-a4dc-8e0d96aeb282.png)

After moving the cursor a bit:
![Screenshot from 2022-04-17 22-40-47](https://user-images.githubusercontent.com/47485105/163734928-19cd4de6-dd3a-4a71-a831-ceee6c73b7a3.png)

**Desktop (please complete the following information):**

 - OS: Ubuntu 20.04 LTS
 - Neovide Version 0.8.0
 - Neovim Version v0.7.0-dev

**Log**
[neovide_rCURRENT.log](https://github.com/neovide/neovide/files/8502597/neovide_rCURRENT.log)

**Comment by MultisampledNight** [comment]
Can sometimes reproduce, sway (Wayland) on Arch.

**Comment by eprst** [comment]
Reproduces every time for me: Gentoo, Xorg

**Comment by BHatGuy** [comment]
Reproduces every time for me as well: Arch, Xorg an i3

**Comment by fredizzimo** [comment]
This is very likely fixed with the winit upgrades in Neovide 0.11 and 0.12, but if not please re-open.
