### ISSUE TITLE
Neovide crashing or freezing instantly on Arch guest with Windows 10 host (virtualbox)

### ISSUE THREAD

**Issue by hatemets** [neovide/neovide#1281]
**Describe the bug**
When launching `neovide` on Arch Linux on VirtualBox (host machine: Windows 10), neovide opens the window and freezes (or crashes) right away. In case of freezing, the only way to close the neovide instance is to run `kill <neovide_pid>`.

**To Reproduce**
1. Install Arch Linux on VirtualBox
2. Follow step-by-step the installation guide for building from source on Neovide's GitHub page (install dependencies, clone the repo, run `cargo build --release`)
3. Navigate to `neovide/target/release` and run `./neovide`

**Expected behavior**
Neovide would be responsive and let me use the neovim interface.

**Desktop (please complete the following information):**
 - OS: [Arch Linux x86_64, kernel release 5.17.1-arch1] (running on Windows 10 host machine, using Oracle VM VirtualBox)
 - Window manager: i3wm
 - Neovide Version [0.9.0]
 - Neovim Version [0.7.0]
 - Processor: Intel Core (TM) i7-8700 @ 3.20GHz

**Please run `neovide --log` and paste the contents of the `.log` file here:**
- The contents of the log file can be found from this link (the logfile was way too large to be pasted here)
https://pastebin.com/khKtJmtB

**Additional context**
When launching neovide with `neovide .` (opens neovide in the current directory), it doesn't crash immediately. However, when pressing any key (e.g. J to navigate down), neovide crashes. When running with `--nofork`, the terminal shows `segmentation fault (core dumped)` after crashing.
It is also worth noting that I've tried other methods for installing neovide as well, including `neovide`, `neovide-git`, `neovide-bin` from the arch user repository.

**Comment by SergioRibera** [comment]
Hi, have you installed all the intell virtual box drivers? How many cores did you allocate for that virtual machine? How much video memory did you allocate for the virtual machine?

**Comment by MultisampledNight** [comment]
I doubt that `vulkan-intel` is useful inside of a VM, probably you're looking for a (para)virtualized video drive which supports OpenGL (like `xf86-video-vmware` if you run on X, then you could set `vmware` as GPU driver inside of VirtualBox. Too long ago that I've done this, though).

Also, do other OpenGL clients like `glxgears` from the `mesa-demos` package work? If not, you may be better off with taking this to the Arch forums, even though I use Arch, too.

**Comment by hatemets** [comment]
I'm sorry, I should've specified that I also have `xf86-video-vmware`. This is my `lspci` output:
```00:00.0 Host bridge: Intel Corporation 440FX - 82441FX PMC [Natoma] (rev 02)
00:01.0 ISA bridge: Intel Corporation 82371SB PIIX3 ISA [Natoma/Triton II]
00:01.1 IDE interface: Intel Corporation 82371AB/EB/MB PIIX4 IDE (rev 01)
00:02.0 VGA compatible controller: VMware SVGA II Adapter
00:03.0 Ethernet controller: Intel Corporation 82540EM Gigabit Ethernet Controller (rev 02)
00:04.0 System peripheral: InnoTek Systemberatung GmbH VirtualBox Guest Service
00:05.0 Multimedia audio controller: Intel Corporation 82801AA AC'97 Audio Controller (rev 01)
00:06.0 USB controller: Apple Inc. KeyLargo/Intrepid USB
00:07.0 Bridge: Intel Corporation 82371AB/EB/MB PIIX4 ACPI (rev 08)
00:0d.0 SATA controller: Intel Corporation 82801HM/HEM (ICH8M/ICH8M-E) SATA Controller [AHCI mode] (rev 02)```

It's also worth noting that I used to be able to run Neovide without problems approximately a month ago, with the exact same setup. This led me to think that some update might've caused the problems, but I've tried several older commits/releases, and the problem persists.

**Comment by MultisampledNight** [comment]
If at all, probably the switch to OpenGL from Vulkan. Pardon, but again the question: Do other OpenGL programs run fine? You can try it out with `glxgears` from the `mesa-demos` package.

**Comment by hatemets** [comment]
Are there any updates on this? I tested Neovide and it's still crashing on my machine.

**Comment by Kethku** [comment]
I don't think that running in a vm is something we can easily support closing as stale.
