### ISSUE TITLE
Unable To Paste from system clipboard to a buffer/terminal window in neovide

### ISSUE THREAD

**Issue by Korokoukousei** [neovide/neovide#1282]
**Describe the bug**
Unable to paste from system clipboard to a buffer/terminal.

**To Reproduce**
1. Open neovide (using AstroNvim config pack)
2. Try to copy something from system keyboard to buffer/terminal using Ctrl + Shift + V or Ctrl + V

**Expected behavior**
I would like it to paste text from my system clipboard into the target location (i.e a buffer or a terminal opened within nvim)

**Screenshots**
![image](https://user-images.githubusercontent.com/70006643/164527112-96fd742d-a09b-417f-bb09-4e329a17b4f3.png)
Pressing Paste inserts a ^ character and changes the text to whatever button press follows.
For example, pressing Ctrl + Shift + V and then hitting Backspace -
![image](https://user-images.githubusercontent.com/70006643/164527281-c2c7f0f4-13f1-4d06-ba82-57b431260a11.png)
<BS> being backspace

**Desktop:**
 - OS: [Ubuntu 21.04]
 - Neovide Version [e.g. 0.8.0]
 - Neovim Version [e.g. 0.7.0]

**Unable to run "neovide --logs" because it just opens neovide instead of showing logs.**

**Comment by Korokoukousei** [comment]
Nope this is still not working, I followed the instructions to add keybinds to init.lua (im using AstroNVim) but it still fails to paste from and copy to the system clipboard.

**Comment by MultisampledNight** [comment]
Then, could you run `:checkhealth` and see whether under `## Clipboard (optional)` a clipboard tool is present?

**Comment by Korokoukousei** [comment]
![image](https://user-images.githubusercontent.com/70006643/164988435-e912351c-f140-4d4d-bc32-4c80e8922136.png)
Doesn't look like it is. How do I fix this?

**Comment by MultisampledNight** [comment]
Take a look at `:help clipboard`, as the advice suggests.

...enough of the salt. I don't know what operating system you are running on, but most probably you just need to install a tool like `xclip` if you're on Linux.

**Comment by Korokoukousei** [comment]
I installed Xclip, I am on Kubuntu. What do i do next?

**Comment by MultisampledNight** [comment]
Oh, you're on KDE. In that case you're probably looking for the `wl-copy` and `wl-paste` tools then instead, on my distro (Arch Linux) they're under the `wl-clipboard` package, seems like the same for Ubuntu flavors.

For context, KDE can run under X11 xor Wayland, only one at a time. But as a person which is not familiar with your exact system configuration (like, Nvidia GPUs _usually_ force an X11 session), I have to guess what display protocol (that's how X and Wayland are called) you use.

So in case installing `wl-clipboard` doesn't help and you seem to be running on X11, try to run `:!echo $PATH` in Neovide and `echo $PATH` in your shell and compare the outputs. Probably NeoVim (behind Neovide) can't find xclip then.

**Comment by Korokoukousei** [comment]
Clipboard health says OK now, It found xclip. What should I do next?

**Comment by MultisampledNight** [comment]
Then the clipboard should work just fine. Try out forming a visual selection over text and typing `"+y`, then pasting in another application. If that works, you can rebind `"+y` and `"+p` to your wishes.

**Comment by Korokoukousei** [comment]
Yep, works now thanks a tonne!

**Comment by ystyle** [comment]
I am also on Linux (archlinux) and using neovim/astrovim. How do I write this key binding specifically? I found a configuration on vim, but it can only be pasted in the main editing area, and is invalid in command mode and other floating windows.

**Comment by mrded** [comment]
```lua
if vim.g.neovide then
  vim.keymap.set('n', '<D-s>', ':w<CR>') -- Save
  vim.keymap.set('v', '<D-c>', '"+y')    -- Copy
  vim.keymap.set('n', '<D-v>', '"+P')    -- Paste normal mode
  vim.keymap.set('v', '<D-v>', '"+P')    -- Paste visual mode
  vim.keymap.set('c', '<D-v>', '<C-R>+') -- Paste command mode
  vim.keymap.set('i', '<D-v>', '<C-R>+') -- Paste insert mode
end
```

**Comment by sleeptightAnsiC** [comment]
If someone is still looking for copy/paste bindings introduced by most terminal emulators - Ctrl+Shift+C to Copy, Ctrl+Shitf+V to paste - this can be achieved with:
```lua
if vim.g.neovide then
	vim.api.nvim_set_keymap('v', '<sc-c>', '"+y', {noremap = true})
	vim.api.nvim_set_keymap('n', '<sc-v>', '"+P', {noremap = true})
	vim.api.nvim_set_keymap('v', '<sc-v>', '"+P', {noremap = true})
	vim.api.nvim_set_keymap('c', '<sc-v>', '<C-R>+', {noremap = true})
	vim.api.nvim_set_keymap('i', '<sc-v>', '<ESC>"+Pi', {noremap = true})
	vim.api.nvim_set_keymap('t', '<sc-v>', '<C-\\><C-n>"+Pi', {noremap = true})
end
```
Apologies for necroing this thread. It shows up on the very top of search results.

**Comment by RobertoMaurizzi** [comment]
... and in case anybody found this Issue while trying to understand how to paste a command in the command line: middle-mouse-button does the trick for me (in Debian/Wayland)

**Comment by alr86** [comment]
> If someone is still looking for copy/paste bindings introduced by most terminal emulators - Ctrl+Shift+C to Copy, Ctrl+Shitf+V to paste - this can be achieved with:
> 
> ```lua
> if vim.g.neovide then
> 	vim.api.nvim_set_keymap('v', '<sc-c>', '"+y', {noremap = true})
> 	vim.api.nvim_set_keymap('n', '<sc-v>', 'l"+P', {noremap = true})
> 	vim.api.nvim_set_keymap('v', '<sc-v>', '"+P', {noremap = true})
> 	vim.api.nvim_set_keymap('c', '<sc-v>', '<C-o>l<C-o>"+<C-o>P<C-o>l', {noremap = true})
> 	vim.api.nvim_set_keymap('i', '<sc-v>', '<ESC>l"+Pli', {noremap = true})
> 	vim.api.nvim_set_keymap('t', '<sc-v>', '<C-\\><C-n>"+Pi', {noremap = true})
> end
> ```
> 
> Apologies for necroing this thread. It shows up on the very top of search results.

In command line doesn't work correctly for me, It's type: ^O^O"+^OP^Ol

**Comment by g-h-97** [comment]
> If someone is still looking for copy/paste bindings introduced by most terminal emulators - Ctrl+Shift+C to Copy, Ctrl+Shitf+V to paste - this can be achieved with:
> 
> ```lua
> if vim.g.neovide then
> 	vim.api.nvim_set_keymap('v', '<sc-c>', '"+y', {noremap = true})
> 	vim.api.nvim_set_keymap('n', '<sc-v>', 'l"+P', {noremap = true})
> 	vim.api.nvim_set_keymap('v', '<sc-v>', '"+P', {noremap = true})
> 	vim.api.nvim_set_keymap('c', '<sc-v>', '<C-o>l<C-o>"+<C-o>P<C-o>l', {noremap = true})
> 	vim.api.nvim_set_keymap('i', '<sc-v>', '<ESC>l"+Pli', {noremap = true})
> 	vim.api.nvim_set_keymap('t', '<sc-v>', '<C-\\><C-n>"+Pi', {noremap = true})
> end
> ```
> 
> Apologies for necroing this thread. It shows up on the very top of search results.

I had to modify this as per below. I hope it helps :)

```lua
  vim.api.nvim_set_keymap("v", "<sc-c>", '"+y', { noremap = true }) -- Select line(s) in visual mode and copy (CTRL+Shift+V)
  vim.api.nvim_set_keymap("i", "<sc-v>", '<ESC>"+p', { noremap = true }) -- Paste in insert mode (CTRL+Shift+C)
  vim.api.nvim_set_keymap("n", "<sc-v>", '"+p', { noremap = true }) -- Paste in normal mode (CTRL+Shift+C)
```

**Comment by barsikus007** [comment]
I modified approaches above to make it suit my case (also, I use ^C and ^V without shift)
```lua
vim.keymap.set('n', '<C-c>', '"+y', { noremap = true })
vim.keymap.set('v', '<C-c>', '"+y', { noremap = true })
if vim.g.neovide then
    vim.api.nvim_set_keymap('n', '<C-v>', '"+p', { noremap = true })
    vim.api.nvim_set_keymap('v', '<C-v>', '"+P', { noremap = true })
    vim.api.nvim_set_keymap('c', '<C-v>', '<C-R>+', { noremap = true })
    vim.api.nvim_set_keymap('i', '<C-v>', '<C-R>+', { noremap = true })
    vim.api.nvim_set_keymap('t', '<C-v>', '<C-\\><C-n>"+Pi', { noremap = true })
end
```

**Comment by CI124** [comment]
> 我修改了上面的方法，使其适合我的情况（此外，我使用^C和^V而不移位）
> 
> vim.keymap.set('n', '<C-c>', '"+y', { noremap = true })
> vim.keymap.set('v', '<C-c>', '"+y', { noremap = true })
> if vim.g.neovide then
>     vim.api.nvim_set_keymap('n', '<C-v>', '"+p', { noremap = true })
>     vim.api.nvim_set_keymap('v', '<C-v>', '"+P', { noremap = true })
>     vim.api.nvim_set_keymap('c', '<C-v>', '<C-R>+', { noremap = true })
>     vim.api.nvim_set_keymap('i', '<C-v>', '<C-R>+', { noremap = true })
>     vim.api.nvim_set_keymap('t', '<C-v>', '<C-\\><C-n>"+Pi', { noremap = true })
> end

Thank you for the configuration you provided; it has been extremely useful.
