### ISSUE TITLE
Misalignment of border-lines of popups

### ISSUE THREAD

**Issue by madhurachanna** [neovide/neovide#1283]
**Describe the bug**
There is small misalignment with respect to border-line and border-curve/radius of popups

**Screenshots**
![image](https://user-images.githubusercontent.com/45120942/164610180-da64436d-9daf-4254-83ae-a07cc537efeb.png)

**Desktop**
 - OS: macOS 12.3.1
 - Neovide Version 0.8.0

**Comment by dineshKumar777** [comment]
please provide reproducible steps with more info, like font information
Also is it happening with other fonts and other nvim terminal, gui apps like nvim-qt.

**Comment by madhurachanna** [comment]
Its problem with `UbuntuMono Nerd Font Mono`.
