### ISSUE TITLE
can't open neovide 0.8 after install via scoop on windows11

### ISSUE THREAD

**Issue by HughGrant** [neovide/neovide#1284]
Some small windows flashed real quick and then quits.
can't read the text in the window because the flash is to quick.

**Comment by MultisampledNight** [comment]
Could you try running Neovide in the terminal through `neovide --log` and post the `neovide_rCURRENT.log` file created in the current directory here?

Please don't enter any sensitive information into Neovide in the meantime, it will be recorded in the log otherwise.

**Comment by HughGrant** [comment]
@MultisampledNight I got it, looks like I don't have neovim itself in the path, close this issue now.
