### ISSUE TITLE
Neovide doesn't integrate with WinSCP

### ISSUE THREAD

**Issue by kacystocks** [neovide/neovide#1285]
__Describe the bug:__

When attempting to open a file with Neovide from WinSCP's _external editor_ feature, __neovide.exe__ fails on Windows 10.

__To Reproduce:__

1. Install Neovim version 0.7.0, llvm, and cmake with chocolatey
2. Clone Neovide's main branch and use cargo to build a release binary
3. Move the binary to a path where it can be called, I chose to put it in the same location as where nvim.exe and nvim-qt.exe are located
4. Open WinSCP up on a remote dir, change external editor as follows:

![image](https://user-images.githubusercontent.com/36412717/164791026-7f66c901-8954-4370-9cb8-4de86b3c100b.png)

__Or__ use Nvim headless mode, in a terminal opened with admin preveleges, which just opens up a new instance of Neovide.exe with a new, empty buffer
```sh
nvim --headless --listen localhost:6666
``` 
and
```sh
C:\tools\neovim\nvim-win64\bin\neovide.exe --remote-tcp=localhost:6666 !.!
```
 as the external editor setting in WinSCP as shown:
![image](https://user-images.githubusercontent.com/36412717/164791269-eea4b624-db87-4af6-8770-724c4d5b61d2.png)

__Expected behavior:__

Upon double clicking a remote file, WinSCP should create a local temporary directory, download the file into the newly created directory, call __neovide.exe__, pass in the file downloaded locally, then Neovide should open the file in either a new window, or a new buffer/tab in either Neovim locally, or 'remote Neovim', respectively; this is how __neovim-qt.exe__ functions

__Desktop:__

* OS: Windows 10 (Microsoft Windows [Version 10.0.1944 Build 19044])
* Neovide Version: 0.9.0
* Neovim Version: 0.7.0

__`neovide --log` output:__

[neovide_rCURRENT.log](https://github.com/neovide/neovide/files/8544039/neovide_rCURRENT.log)

__Additional context:__

While `Nvim-qt.exe !.!` and `Code.exe !.!` work just fine, `neovide.exe !.!` does not work as one would expect in WinSCP (__neovide.exe__ and __neovim.exe__ are in the same directory); Please note that Neovide works as intended when I open a file otherwise from the terminal

**Comment by MultisampledNight** [comment]
What replaces `!.!` when in action, or more to say, what does `!.!` really mean?

**Comment by MultisampledNight** [comment]
Also, could you try to have WinSCP execute Neovide with the `--log` flag, too? I imagine the debug log to be useful there.

**Comment by kacystocks** [comment]
I've tried adding the --log flag, but I can't find an updated log file, and neither does windows:

![image](https://user-images.githubusercontent.com/36412717/164815159-f73dc21c-585f-4899-b8b1-3c1f561c1f18.png)

The `!.!` means __any__ filetype.

**Comment by MultisampledNight** [comment]
Alright, thank you. I guess WinSCP needs to stay running. If I follow the "temporary directory" thing on the WinSCP documentation correctly, the log file may be located there?

**Comment by kacystocks** [comment]
I've looked for the file in the temporary directory without closing WinSCP. It simply doesn't exist.

**Comment by MultisampledNight** [comment]
I'm pretty much clueless then, unfortunately. Sorry.

**Comment by kacystocks** [comment]
It works with .9! Consider this fixed!

**Comment by Ktoks** [comment]
![Using_Neovide_With_WinSCP](https://user-images.githubusercontent.com/36412717/226485905-2b288fef-e19d-482b-8782-649c9cf5adaa.PNG)
