### ISSUE TITLE
Gentoo Linux and Neovide

### ISSUE THREAD

**Issue by sacreative10** [neovide/neovide#1287]
**Is your feature request related to a problem? Please describe.**
I use Gentoo Linux and I use neovide, however the ebuild in the "molese" overlay is not only outdated but also does not work (at least on my machine, using Wayland, however building from source works like a charm).

**Describe the solution you'd like**
If that ebuild in the "molese" overlay is still in use, I would like for it to be updated.

**Describe alternatives you've considered**
If not I would like to lead the creation of a new ebuild (preferably building from source), which can be added to the main gentoo tree later down the line, to ease installation for neovide for other users.

As always, thank you for creating and maintaining neovide.

**Comment by MultisampledNight** [comment]
I wasn't even aware of an existing ebuild for Gentoo. And I can't seem to find any (existing) overlay named or by `molese` or `m0lese` either, only 404s.

In the past and with other projects as I see, packaging for distros was a thing of the distros, not the project's task. So, communicate that with whoever also has a word on that thing within your distro's reach.

**Comment by fredizzimo** [comment]
Yes, closing this, packaging issues should be reported to and fixed by the distributions.
