### ISSUE TITLE
Choose which config to use

### ISSUE THREAD

**Issue by danielo515** [neovide/neovide#1288]
**Is your feature request related to a problem? Please describe.**
Hello, thanks for this vim client, looks nice.
As a vim user, I like to experiment with several configurations and vim distrubitions. For example, I use spacevim, lunar vim and my own vim version. I would love to be able to specify to neovide which vim binary to use, or at least which vim configuration to load.

**Describe the solution you'd like**
A config setting, a environment variable, something that allows me to configure how the neovim is loaded

**Describe alternatives you've considered**
Just not using neovide

**Comment by danielo515** [comment]
> ...what an alternative, we can't let that happen! /s

LOL, sorry for the drama.

> Did you take a look at the wiki?

Didn't noticed the wiki, I just read the Readme and thought that was all the docs.

I tried the following, which didn't worked for some reason (still loads my old nvim config):

```bash
  neovide --neovim-bin /Users/danielo/.local/bin/lvim
```

Where lvim contains the following:

```bash
[I] ➜  cat /Users/danielo/.local/bin/lvim
#!/bin/sh

export LUNARVIM_RUNTIME_DIR="${LUNARVIM_RUNTIME_DIR:-"/Users/danielo/.local/share/lunarvim"}"
export LUNARVIM_CONFIG_DIR="${LUNARVIM_CONFIG_DIR:-"/Users/danielo/.config/lvim"}"
export LUNARVIM_CACHE_DIR="${LUNARVIM_CACHE_DIR:-"/Users/danielo/.cache/nvim"}"

exec nvim -u "$LUNARVIM_RUNTIME_DIR/lvim/init.lua" "$@"
```

Maybe all I need is to source that file and then call neovide as you explained.

**Comment by danielo515** [comment]
Yes, that did the trick. The font is a bit big and all over the place, but the point that this issue was about is ressolved.
I think I'll just put the required stuff in a script and use that from now on.

Thank you very much!

**Comment by MultisampledNight** [comment]
`--neovim-bin` not working is unexpected either way, I'll investigate anyways.
