### ISSUE TITLE
feat[cmd]: add flag to open file in existing window

### ISSUE THREAD

**Issue by d12bb** [neovide/neovide#1293]
**Is your feature request related to a problem? Please describe.**
When opening a file from command line while having Neovide already open, it creates a second instance (see Additional context).

**Describe the solution you'd like**
I'd like to have a flag to open the file in the existing instance and a setting to set the default behavior.

**Describe alternatives you've considered**
This probably can already be achieved with Neovim remote commands, but I couldn't get it to work.

**Additional context**
Reproduce:
```sh
neovide test.go
neovide go.mod
```
Result:
<img width="173" alt="image" src="https://user-images.githubusercontent.com/16717303/165721097-d8cd11c5-d6ff-481e-9aa4-f80a9a2644f1.png">

**Comment by LoipesMas** [comment]
This can be achieved with [nvr](https://github.com/mhinz/neovim-remote).
```
NVIM_LISTEN_ADDRESS=/tmp/nvimsocket neovide foo.rs
nvr bar.rs
```

**Comment by fredizzimo** [comment]
I'm closing this and leaving this one open, since it has more information
* https://github.com/neovide/neovide/issues/1586
