### ISSUE TITLE
neovide --wsl:    nvim not found

### ISSUE THREAD

**Issue by sisrfeng** [neovide/neovide#1296]
How to use my huge config files in wsl with neovide?

nvim0.7.0              on wsl2 "/home/linuxbrew/.linuxbrew/bin/nvim"
neovide0.8.0    in   "F:\nvim07\bin\neovide.exe"
from pwsh in windows terminal, I type "neovide --wsl", an ugly ubuntu window appear and disappear in about 1s.

/mnt/c/Users/IIIway/neovide_rCURRENT.log 

![image](https://user-images.githubusercontent.com/53520949/166108925-41667f9a-96f7-4724-914e-1aa5f800c046.png)

from pwsh in windows terminal, I type "nvim", nvim can start up:
![image](https://user-images.githubusercontent.com/53520949/166109016-ef553225-d470-480d-85ab-b63bb1b19897.png)

**Comment by MultisampledNight** [comment]
Hm, where is your NeoVim binary stored? Is the parent folder/NeoVim itself on the PATH environment variable (`echo $PATH`)? Does it work if you specify the NeoVim binary per command-line argument?

**Comment by sisrfeng** [comment]
Thank you for your quick reply

In wsl, print -l $path:
![image](https://user-images.githubusercontent.com/53520949/166109694-91335758-c509-49e1-b374-bc850b115714.png)


specify the NeoVim binary per command-line argument:
![image](https://user-images.githubusercontent.com/53520949/166109763-6060fbcb-282f-447e-8020-d6ba0b92bb8d.png)

Fails

**Comment by MultisampledNight** [comment]
Wait a moment, you're trying to use a Windows executable inside of WSL. I don't know whether that's possible, but why then are you using `--wsl` at all?

**Comment by MultisampledNight** [comment]
As explanation, `--wsl` literally searchs for NeoVim inside of WSL rather than Windows. That's the only difference it makes.

**Comment by sisrfeng** [comment]
![image](https://user-images.githubusercontent.com/53520949/166110015-72f911d0-0705-4bf3-9ce1-b17e927bda82.png)

![image](https://user-images.githubusercontent.com/53520949/166110001-5171137c-7e09-4c52-8bb6-a41d1536897b.png)

The same with:
![image](https://user-images.githubusercontent.com/53520949/166110093-f2531b83-60b2-4971-bb73-e97f809202b4.png)

**Comment by sisrfeng** [comment]
I use zsh as my default shell. ( Not relevant to this problem? )

**Comment by MultisampledNight** [comment]
Indeed, not relevant. But is `/home/linuxbrew/.linuxbrew/bin/nvim` on `$PATH`?

**Comment by sisrfeng** [comment]
![image](https://user-images.githubusercontent.com/53520949/166110386-2e1ae015-7582-490e-87c7-c33565efb2b0.png)

**Comment by sisrfeng** [comment]
Do you know why F:\NeoVim\bin  is  in win10's %PATH% ? 
That path does not exist. I only have F:\nvim07

![image](https://user-images.githubusercontent.com/53520949/166110453-11e695f8-259c-4f5d-8427-3710f2637ac4.png)

**Comment by sisrfeng** [comment]
WSL's path:
![image](https://user-images.githubusercontent.com/53520949/166110546-5b21be7a-0731-4ccd-a3a9-20ed1f228883.png)

I don't know how it comes into PATH in WSL

**Comment by MultisampledNight** [comment]
No, I don't know how WSL works, and not how it correlates with Windows' PATH entries either.

I assume `which nvim` does yield the path to `nvim`. But that doesn't make any sense to me: If the WSL `which` command is flawed, then at  least the `which` crate should find `nvim`.

Could you run the long command `wsl $SHELL -lc 'which nvim'` from a Windows (not WSL) shell and tell us the exit code and output?

**Comment by sisrfeng** [comment]
`wsl $SHELL -lc 'which nvim'` can't work.
I use:
![image](https://user-images.githubusercontent.com/53520949/166127616-e608ffc9-d92b-446b-8ff2-dbdb71a5e472.png)
![image](https://user-images.githubusercontent.com/53520949/166127626-26d67c01-b3e5-482d-ae0e-5ac3731f6b0b.png)

after `apt install neovim` , `neovide --wsl` works.  
![image](https://user-images.githubusercontent.com/53520949/166127683-d0f7d60c-18f5-4aa1-bc68-1733962d92f8.png)

But, I can do nothing in this window:
![image](https://user-images.githubusercontent.com/53520949/166127712-ebc157b5-e832-450b-a7e7-8aa3662e5748.png)


Nvim installed by apt is too old:
![image](https://user-images.githubusercontent.com/53520949/166127727-ab7cfc1d-bd7e-4eec-b66c-db70ecd5dfba.png)

I managed to use nvim by moving  `export PATH=/home/linux....................` from zshrc to zshenv.
Like this:
![image](https://user-images.githubusercontent.com/53520949/166128262-93a99e63-5df7-477d-ae70-7b694548641d.png)


(BTW, my default shell is `/home/linuxbrew/.linuxbrew/bin/zsh` )

In  /etc/shells
![image](https://user-images.githubusercontent.com/53520949/166127823-463c06e3-1083-485d-90e3-bd30c8afbc62.png)

In /etc/passwd , there is
`MY_USER_naMe:x:NumbeR:NumbeR:,,,:/home/MY_USER_naMe:/home/linuxbrew/.linuxbrew/bin/zsh`


![image](https://user-images.githubusercontent.com/53520949/166128184-45146264-04e3-41d1-9eb3-1a4918ef85da.png)

But I still can do nothing in this window:

![image](https://user-images.githubusercontent.com/53520949/166128310-6c6e3961-7d89-4224-898b-c364aad36104.png)

**Comment by MultisampledNight** [comment]
(woah, you really went all the way down the rabbit hole)

Okay, your last try with `~/.linuxbrew/bin/nvim` as NeoVim seems really promising. Could you post the log created by `neovide --log` in that case again? Thanks anyways for your time!

**Comment by sisrfeng** [comment]
using 
`/usr/bin/nvim`
![image](https://user-images.githubusercontent.com/53520949/166173749-6c3ee37b-a1bc-492f-9cfa-ea0d7c577d24.png)

using
 `linuxbrew/bin/nvim`

![image](https://user-images.githubusercontent.com/53520949/166174873-1f57aaa8-1f70-486e-ae70-b2556c6bddd8.png)

![image](https://user-images.githubusercontent.com/53520949/166174889-d10b27cf-0963-4fd1-8ebc-01b5720a4294.png)

![image](https://user-images.githubusercontent.com/53520949/166174898-92d37764-78f0-4a44-b4ad-1ec099a8ea96.png)

This does not help:   `mv ~/.config/nvim ~/.config/bk_nvim`
![image](https://user-images.githubusercontent.com/53520949/166175046-92ed9859-0274-44ae-9e0a-c45c1e97ca80.png)

**Comment by sisrfeng** [comment]
![image](https://user-images.githubusercontent.com/53520949/166176452-554cfe9d-5d43-4e5a-a295-82a1e8fa84e7.png)


A window of goneovim shows up and disappeared in 1s:
![image](https://user-images.githubusercontent.com/53520949/166176526-55c21dc6-226d-40c7-849f-ad8675176916.png)

**Comment by MultisampledNight** [comment]
Hm, well, I'm drawing a blank then. Someone else using WSL may want to look into this.

**Comment by jamespotz** [comment]
Create `.zshenv` file and add all your homebrew path inside. That should fix your issue

**Comment by sisrfeng** [comment]
Thx. But even nvim can be found by neovide, still:

https://github.com/neovide/neovide/issues/1296#issuecomment-1114422506

**Comment by sisrfeng** [comment]
I use --remote-tcp instead of --wsl, finding if the port number is 111 or  32780,  neovide can start but can't response to my input.

port numbers like 4444 6666 work well
![image](https://user-images.githubusercontent.com/53520949/167248344-cd603095-88c5-4e74-8b1d-3f98a88a72f3.png)

**Comment by sisrfeng** [comment]
But using` --remote-tcp`, I have to type additional `\nvim--headless --listen ""localhost:6666" `,  which is annoying.

**Comment by feature-not-a-bug** [comment]
I use Neovide with WSL2 and Debian. I installed from the nvim releases deb file, which should be possible in Ubuntu, but I've also used the appimage successfully. I'm using a convention where '>' indicates a Windows command and '$' is a bash command

`>wsl --status
Default Distribution: Debian
Default Version: 2

Windows Subsystem for Linux was last updated on 3/25/2022
WSL automatic updates are on.

Kernel version: 5.10.102.1`

`$ nvim --version
NVIM v0.8.0-dev+141-g55187de11
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/gcc-11 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -DNVIM_TS_HAS_SET_ALLOCATOR -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wdouble-promotion -Wmissing-noreturn -Wmissing-format-attribute -Wmissing-prototypes -Wimplicit-fallthrough -Wsuggest-attribute=pure -Wsuggest-attribute=const -Wsuggest-attribute=malloc -Wsuggest-attribute=cold -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/runner/work/neovim/neovim/build/config -I/home/runner/work/neovim/neovim/src -I/home/runner/work/neovim/neovim/.deps/usr/include -I/usr/include -I/home/runner/work/neovim/neovim/build/src/nvim/auto -I/home/runner/work/neovim/neovim/build/include
Compiled by runner@fv-az242-535

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/share/nvim"

Run :checkhealth for more info`

First thing to check is:

`$ which -a -- nvim
/usr/bin/nvim`

Ideally you only have a single executable on the path, but if you have multiple be sure that the preferable version is listed first. Next make sure that nvim can run in the terminal without a problem:

`$ nvim`

![Screenshot 2022-05-09 164742](https://user-images.githubusercontent.com/19642535/167496219-c587ab6c-baea-41dd-9349-c48a44519e85.png)

`> wsl -e nvim`

![Screenshot 2022-05-09 164808](https://user-images.githubusercontent.com/19642535/167496244-732b3424-fc86-4c92-acb6-bd276f8f7d13.png)

`>neovide --version

>Neovide 0.9.0`

`>neovide --wsl`

Then `:read env` `:pwd` produces

![Screenshot 2022-05-09 165557](https://user-images.githubusercontent.com/19642535/167497277-7c951962-fa8a-402b-a84b-294190e6ccad.png)

**Comment by jacksonludwig** [comment]
Hopefully this isn't pointless to add, however I also believe I have the same issue of neovide misdetecting my neovim version.

Among the logs is this line:
```
DEBUG [neovide::bridge::command] Starting neovim with: Command { std: "wsl" "$SHELL" "-lc" "/usr/bin/nvim --embed", kill_on_drop: false }
```

Running `wsl bash -lc "/usr/bin/nvim --embed"` manually runs successfully. I also have only one distro and one neovim version installed (nightly/0.8).

As OP, using `remote-tcp` instead of `wsl` does work.

**Comment by sisrfeng** [comment]
Yes, using remote-tcp instead of wsl does work,  but while editing,  it feels slower than nvim without neovide.
Will `neovide --wsl` runs faster then `remote-tcp` ?

**Comment by feature-not-a-bug** [comment]
Not a formal benchmark by any means, but I tried inserting, deleting, and mode switching in a new buffer as well as editing some rust code to produce error messages from rust-analyzer and jumping to code definitions in the standard library (same source file & edits). The only difference seems to be a slightly slower startup time for a remote-tcp connection and not having to set up a headless session before connecting with `neovide --wsl`, but otherwise no apparent change when working.

**Comment by birtles** [comment]
This is probably not helpful to those using zsh, but on bash I found I had the following at the top of my `.bashrc`:

```bash
# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac
```

which was causing none of my paths to be reflected when launching neovide with `--wsl`.

**Comment by LukeDRussell** [comment]
I'm seeing the same symptoms as @sisrfeng, but with FedoraRemix and `fish` shell. Just here to add another datapoint.

```
> wsl --list  
Windows Subsystem for Linux Distributions:  
fedoraremix (Default)

> neovide.exe --version
neovide 0.10.3

> wsl -e nvim --version
NVIM v0.8.1
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/gcc -O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -Wp,-U_FORTIFY_SOURCE -Wp,-D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -DNVIM_TS_HAS_SET_ALLOCATOR -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wdouble-promotion -Wmissing-noreturn -Wmissing-format-attribute -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/builddir/build/BUILD/neovim-0.8.1/redhat-linux-build/cmake.config -I/builddir/build/BUILD/neovim-0.8.1/src -I/usr/include -I/usr/include/luajit-2.1 -I/builddir/build/BUILD/neovim-0.8.1/redhat-linux-build/src/nvim/auto -I/builddir/build/BUILD/neovim-0.8.1/redhat-linux-build/include
Compiled by mockbuild@koji

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info

> neovide --wsl --log
```
![image](https://user-images.githubusercontent.com/6735465/208222903-0b377591-d4d4-4da1-a448-86263a6a397f.png)
_Can't close this window without killing the process._

```
> cat .\neovide_rCURRENT.log
TRACE [neovide] Neovide version: 0.10.3
DEBUG [neovide::bridge::command] Running which command: "wsl" "$SHELL" "-lc" "which nvim"
TRACE [neovide::window] repositioned window: true
DEBUG [neovide::renderer::fonts::caching_shaper] Original font_size: 23.33px
TRACE [neovide::renderer::fonts::font_loader] Loading font FontKey { bold: false, italic: false, family_name: None, hinting: Full, edging: AntiAlias }
DEBUG [neovide::renderer::fonts::caching_shaper] Original font_width: 14.36px
DEBUG [neovide::renderer::fonts::caching_shaper] Font width: 14.36px (avg: 14.36px)
DEBUG [neovide::renderer::fonts::caching_shaper] Fudge factor: 0.97
DEBUG [neovide::renderer::fonts::caching_shaper] Fudged font size: 22.75px
DEBUG [neovide::renderer::fonts::caching_shaper] Fudged font width: 14.00px
TRACE [neovide::renderer::fonts::font_loader] Loading font FontKey { bold: false, italic: false, family_name: None, hinting: Full, edging: AntiAlias }
TRACE [neovide::renderer::fonts::font_loader] Loading font FontKey { bold: false, italic: false, family_name: None, hinting: Full, edging: AntiAlias }
INFO [neovide::window] window created (scale_factor: 1.2500, font_dimensions: Dimensions { width: 14, height: 28 })
TRACE [neovide::redraw_scheduler] Next frame queued
TRACE [neovide::redraw_scheduler] Next frame queued
TRACE [neovide::redraw_scheduler] Next frame queued
TRACE [neovide::renderer::fonts::caching_shaper] Shaping text:
TRACE [neovide::redraw_scheduler] Next frame queued
TRACE [neovide::redraw_scheduler] Next frame queued
TRACE [neovide::redraw_scheduler] Next frame queued
TRACE [neovide::redraw_scheduler] Next frame queued
TRACE [neovide::redraw_scheduler] Next frame queued
TRACE [neovide::redraw_scheduler] Next frame queued
TRACE [neovide::redraw_scheduler] Next frame queued
TRACE [neovide::redraw_scheduler] Next frame queued
TRACE [neovide::redraw_scheduler] Next frame queued
TRACE [neovide::channel_utils] neovide::bridge::ui_commands::UiCommand Parallel(FocusLost)
DEBUG [neovide::bridge::command] Starting neovim with: Command { std: "wsl" "$SHELL" "-lc" "/usr/bin/nvim --embed -p", kill_on_drop: false }
TRACE [neovide::redraw_scheduler] Next frame queued
TRACE [neovide::redraw_scheduler] Next frame queued
TRACE [neovide::redraw_scheduler] Next frame queued
TRACE [neovide::redraw_scheduler] Next frame queued
```
Remote TCP seems to work ok.
```
$ nvim --headless --listen "localhost:6666"
```
```
> neovide --remote-tcp=localhost:6666
```
![image](https://user-images.githubusercontent.com/6735465/208223739-90a54a42-3cc3-485f-b011-e4c50133ff16.png)

**Comment by dr4gut** [comment]
Same issue here. Both when launching from WSL install and Windows install connecting to WSL.

**Comment by SinMayFly** [comment]
> This is probably not helpful to those using zsh, but on bash I found I had the following at the top of my `.bashrc`:
> 
> ```shell
> # If not running interactively, don't do anything
> case $- in
>     *i*) ;;
>       *) return;;
> esac
> ```
> 
> which was causing none of my paths to be reflected when launching neovide with `--wsl`.

it work for me 0.0

**Comment by fredizzimo** [comment]
I'm pretty sure this fixes it https://github.com/neovide/neovide/issues/1296

**Comment by csh0101** [comment]
> This is probably not helpful to those using zsh, but on bash I found I had the following at the top of my `.bashrc`:这对于那些使用 zsh 的人来说可能没有帮助，但在 bash 上我发现我的 `.bashrc` 顶部有以下内容：
> 
> ```shell
> # If not running interactively, don't do anything
> case $- in
>     *i*) ;;
>       *) return;;
> esac
> ```
> 
> which was causing none of my paths to be reflected when launching neovide with `--wsl`.这导致在使用 `--wsl` 启动 neovide 时没有反映我的路径。

this is work for me!

**Comment by xerinox** [comment]
For me, the issue was fixed by adding the nvim path in `~/.profile`
It was in `~/.bashrc`, but seeing as neovide uses wsl as a login shell to get the neovim path, it didnt load my `.bashrc`

**Comment by kimusan** [comment]
I hit a similar problem. Turns out that the default wsl distribution wasnt actually the one I thought it was. Simply do wsl -s "correct distribution name" fixed the problem for me and now I can get it to start without problems - even with lunuarvim (neovim extention) as i can point it to the lvim "binary" with --neovim-bin $HOME/.local/bin/lvim

**Comment by alimulap** [comment]
i don't know if it will help other people, but i had the same issue because my default shell wasn't bash

changed to bash and it works fine

**Comment by fredizzimo** [comment]
It works in other shells as well, as long as the path is configured correctly so that it applies to non-interactive login shells.
