### ISSUE TITLE
Blur background when using Transparency

### ISSUE THREAD

**Issue by asmodeus812** [neovide/neovide#1300]
Hi, Looking for a way to provide a blur factor for the background when transparency is enabled. More specifically, to be able to provide a number between 0 and 1 that will specify by how much the background is blurred. As of now i believe that the background is not blurred and it is simply see through. 
On a similar note another thing i have been curious about is if it is possible to show the actual desktop background, even when you have maximized applications behind neovide. As of now you have to minimize the application each time you alt-tab between neovide and another application

**Comment by MultisampledNight** [comment]
Sounds a lot like #1265.

**Comment by LoipesMas** [comment]
I think @asmodeus812 refers to transparency of neovide window (i.e. showing what's behind neovide window: other applications, desktop background). This is different from transparency between floating (and non-floating) windows of neovim.
The latter is done entirely by neovide's rendering, while the former is handled by the display server.
AFAIK it's not possible to blur the background from neovide, but this can be achieved through OS-specific means (e.g. X11 compositor, if you are on Linux using X11).
As for showing actual desktop background, it would be even more OS-specific and may be impossible. Alternative would be patching neovide to display an image as background, but it's a bit more work and I don't expect something like this to be added to main neovide.

**Comment by MultisampledNight** [comment]
...oh wow. Yeah, I see.

The only exception to that is _Windows_, where through weird magic it's possible to get "acrylic" blur on background components like only some apps do. But I really don't want to implement that, and can't even test it.

**Comment by asmodeus812** [comment]
Yeah, that is what i meant, seems like it is more or less OS specific rather than neovide. Could be closed if you think there is nothing more to explore here. The way i was thinking about it was capturing the background in a frame buffer, blurring that and displaying it as background. Instead of making the app itself transparent. This way the buffer might be used to show whatever. But maybe this poses technical difficulties and might not be possible.

**Comment by MultisampledNight** [comment]
> Yeah, that is what i meant, seems like it is more or less OS specific rather than neovide. Could be closed if you think there is nothing more to explore here. The way i was thinking about it was capturing the background in a frame buffer, blurring that and displaying it as background. Instead of making the app itself transparent. This way the buffer might be used to show whatever. But maybe this poses technical difficulties and might not be possible.

Yeah, specifically some platforms (surely not only Wayland) make this even impossible. I'll close this then.

**Comment by Hubro** [comment]
Wayland windows can choose to be transparent, but they can't control what's displayed *behind* themselves. The Wayland server chooses that. Some Wayland servers, for eaxmple Wayfire, allow you to blur the background of transparent windows in a configurable way.

**Comment by thorlucas** [comment]
iTerm2 does this on macOS. 

[This feature request on the Yabai repo](https://github.com/koekeishiya/yabai/issues/1113) discusses the implementation thereof.
