### ISSUE TITLE
Scale/zoom, configurable at runtime

### ISSUE THREAD

**Issue by Hubro** [neovide/neovide#1301]
**Is your feature request related to a problem? Please describe.**

Setting the font size in Neovide is very clunky. It requires the `guifont` setting to be changed, which requires a very specific format including the font family name, the font size and any font weights and/or styles.

There are a couple of use cases in which I really miss the ability to just *increase the scaling* a little bit:

- **Screen sharing**

  I often screen share code as part of presentations at work. Very often I need to zoom in a bit for everybody to be able to see the code. For Vim in a terminal, I can just press <kbd>Ctrl</kbd><kbd>+</kbd>, but in Neovide I'm stuck at a specific font size. A perfect solution would be to have a variable like `g:neovide_scale` that defaults to `1`. I could bind <kbd>Ctrl</kbd><kbd>+</kbd> and <kbd>Ctrl</kbd><kbd>-</kbd> to increase and decrease this number by something like `0.05`.

- **Zen mode**

  Zen mode plugins like https://github.com/folke/zen-mode.nvim have hooks that run when enabling/disabling Zen mode. How cool wouldn't it be to be able to add `vim.g.neovide_scale = 1.5` to this hook, making everything larger while in Zen mode?

**Describe the solution you'd like**

Add a config value like `g:neovide_scale`. Changes to that value changes the scaling of the Neovide GUI at runtime.

Depending on how this is implemented, since Neovide is hardware accelerated, it might even be possible to animate the changing scale, which would be an extra nice touch.

**Describe alternatives you've considered**

Changing the font size. This is clunky. It would require parsing the current GUI font, modifying the font size value and formatting the result back into a font specification. Not very user friendly.

**Comment by 0x0013** [comment]
As someone who also struggled a bit with this initially, I also think it would be a good enhancement to have a more user-friendly option.

For anyone else struggling with this, I eventually solved it by defining a few global variables, and lua functions to change size, and map keybindings to them to increase, decrease or reset size to default.

Below is code snippet (neovim 0.7.0)
```
vim.g.gui_font_default_size = 12
vim.g.gui_font_size = vim.g.gui_font_default_size
vim.g.gui_font_face = "Fira Code Retina"

RefreshGuiFont = function()
  vim.opt.guifont = string.format("%s:h%s",vim.g.gui_font_face, vim.g.gui_font_size)
end

ResizeGuiFont = function(delta)
  vim.g.gui_font_size = vim.g.gui_font_size + delta
  RefreshGuiFont()
end

ResetGuiFont = function ()
  vim.g.gui_font_size = vim.g.gui_font_default_size
RefreshGuiFont()
end

-- Call function on startup to set default value
ResetGuiFont()

-- Keymaps
keymap({'n', 'i'}, "<C-+>", function() ResizeGuiFont(1)  end, opts)
keymap({'n', 'i'}, "<C-->", function() ResizeGuiFont(-1) end, opts)
keymap({'n', 'i'}, "<C-BS>", function() ResetGuiFont() end, opts)
```

I'm sure this could be made more elegant, but it works for me.

**Comment by MultisampledNight** [comment]
Weird question, but would you like to have this integrated with the OS scale factor? Or should the option override the OS scale factor completely? Both are useful in different scenarios.

**Comment by Hubro** [comment]
@MultisampledNight No idea. My guess is that winit handles everything to do with the OS scale factor though, and it might be complicated or impossible to hook into that, especially at runtime.

**Comment by MultisampledNight** [comment]
Yeah, but in the end it's just a number for which Neovide gets an event every time it changes. What we do with it is then our decision, which we can surely overwrite.

**Comment by Matts966** [comment]
viml version

```viml
  let g:gui_font_size = 12
  silent! execute('set guifont=Menlo:h'.g:gui_font_size)
  function! s:ResizeFont(delta)
    let g:gui_font_size = g:gui_font_size + a:delta
    execute('set guifont=Menlo:h'.g:gui_font_size)
    echo 'ok'
  endfunction
  noremap <expr><D-=> s:ResizeFont(1)
  noremap <expr><D--> s:ResizeFont(-1)
```

**Comment by Matts966** [comment]
Transparency

```viml
  let g:neovide_transparency=0.7
  function! ChangeTransparency(delta)
    let g:neovide_transparency = g:neovide_transparency + a:delta
  endfunction
  noremap <expr><D-]> ChangeTransparency(0.1)
  noremap <expr><D-[> ChangeTransparency(-0.1)
```

**Comment by Srijan1214** [comment]
> As someone who also struggled a bit with this initially, I also think it would be a good enhancement to have a more user-friendly option.
> 
> For anyone else struggling with this, I eventually solved it by defining a few global variables, and lua functions to change size, and map keybindings to them to increase, decrease or reset size to default.
> 
> Below is code snippet (neovim 0.7.0)
> 
> ```
> vim.g.gui_font_default_size = 12
> vim.g.gui_font_size = vim.g.gui_font_default_size
> vim.g.gui_font_face = "Fira Code Retina"
> 
> RefreshGuiFont = function()
>   vim.opt.guifont = string.format("%s:h%s",vim.g.gui_font_face, vim.g.gui_font_size)
> end
> 
> ResizeGuiFont = function(delta)
>   vim.g.gui_font_size = vim.g.gui_font_size + delta
>   RefreshGuiFont()
> end
> 
> ResetGuiFont = function ()
>   vim.g.gui_font_size = vim.g.gui_font_default_size
>   RefreshGuiFont()
> end
> 
> -- Call function on startup to set default value
> ResetGuiFont()
> 
> -- Keymaps
> 
> local opts = { noremap = true, silent = true }
> 
> vim.keymap.set({'n', 'i'}, "<C-+>", function() ResizeGuiFont(1)  end, opts)
> vim.keymap.set({'n', 'i'}, "<C-->", function() ResizeGuiFont(-1) end, opts)
> vim.keymap.set({'n', 'i'}, "<C-BS>", function() ResetGuiFont() end, opts)
> ```
> 
> I'm sure this could be made more elegant, but it works for me.

How, are you able to map <C-+>  and <C--> in neovide. As far as I know, vim does not allow this keycode. I was also not able to map this in neovide after many hours of trying.

**Comment by 0x0013** [comment]
> How, are you able to map `<C-+>` and `<C-->` in neovide. As far as I know, vim does not allow this keycode. I was also not able to map this in neovide after many hours of trying.

I don't recall having any problems with these bindings. I use keybinds such as `<C-x>` or `<A-x>` for other needs as well, both in neovide, as well as plain neovim (in terminal).

**Comment by Srijan1214** [comment]
> > How, are you able to map `<C-+>` and `<C-->` in neovide. As far as I know, vim does not allow this keycode. I was also not able to map this in neovide after many hours of trying.
> 
> I don't recall having any problems with these bindings. I use keybinds such as `<C-x>` or `<A-x>` for other needs as well, both in neovide, as well as plain neovim (in terminal).

Maybe a peculiarity with Windows. From my research online, the availablily of the Ctrl keycodes vary on the platform and other stuff.

**Comment by MultisampledNight** [comment]
Variable in #1589 a few days ago, personally I don't really want Neovide to set hidden keybindings.

**Comment by Hubro** [comment]
Can confirm this works great with these keybindings:

```lua
if vim.g.neovide == true then
  vim.api.nvim_set_keymap("n", "<C-+>", ":lua vim.g.neovide_scale_factor = vim.g.neovide_scale_factor + 0.1<CR>", { silent = true })
  vim.api.nvim_set_keymap("n", "<C-->", ":lua vim.g.neovide_scale_factor = vim.g.neovide_scale_factor - 0.1<CR>", { silent = true })
  vim.api.nvim_set_keymap("n", "<C-0>", ":lua vim.g.neovide_scale_factor = 1<CR>", { silent = true })
end
```

Great work, @BHatGuy!

**Comment by alexventuraio** [comment]
> Can confirm this works great with these keybindings:
> 
> ```lua
> if vim.g.neovide == true then
>   vim.api.nvim_set_keymap("n", "<C-+>", ":lua vim.g.neovide_scale_factor = vim.g.neovide_scale_factor + 0.1<CR>", { silent = true })
>   vim.api.nvim_set_keymap("n", "<C-->", ":lua vim.g.neovide_scale_factor = vim.g.neovide_scale_factor - 0.1<CR>", { silent = true })
>   vim.api.nvim_set_keymap("n", "<C-0>", ":lua vim.g.neovide_scale_factor = 1<CR>", { silent = true })
> end
> ```
> 
> Great work, @BHatGuy!

As far as I can see, you can either add these mappings only or do what is described [in the docs](https://neovide.dev/faq.html#how-can-i-dynamically-change-the-scale-at-runtime), right?
Is there any performance benefit or are they equivalent?

**Comment by MultisampledNight** [comment]
About performance I have no idea, doubt it'd matter at this scale of setting a variable anyways.

About them being equivalent, the snippet in the FAQ modifies the scale to be at `125%` or `1/125%` every time it's triggered, this one just plainly adds or subtracts `0.1`.

**Comment by Hubro** [comment]
> > Can confirm this works great with these keybindings:
> > 
> > ```lua
> > if vim.g.neovide == true then
> >   vim.api.nvim_set_keymap("n", "<C-+>", ":lua vim.g.neovide_scale_factor = vim.g.neovide_scale_factor + 0.1<CR>", { silent = true })
> >   vim.api.nvim_set_keymap("n", "<C-->", ":lua vim.g.neovide_scale_factor = vim.g.neovide_scale_factor - 0.1<CR>", { silent = true })
> >   vim.api.nvim_set_keymap("n", "<C-0>", ":lua vim.g.neovide_scale_factor = 1<CR>", { silent = true })
> > end
> > ```
> > 
> > Great work, @BHatGuy!
> 
> As far as I can see, you can either add these mappings only or do what is described [in the docs](https://neovide.dev/faq.html#how-can-i-dynamically-change-the-scale-at-runtime), right?
> Is there any performance benefit or are they equivalent?

Didn't even notice the FAQ 😄 I don't think there's any meaningful difference other than user preference.

**Comment by omaru-ok** [comment]
> Can confirm this works great with these keybindings:

that provided code is not workign for me ? please help 
not even provided at [FAQ](https://neovide.dev/faq.html#how-can-i-dynamically-change-the-scale-at-runtime) 
some info 
`neovide 0.10.4`
![Uploading image.png…]()

**Comment by omaru-ok** [comment]
sorry i found out 

Ctrl+key  , < this dont work in window
so i opt for ALt key instead as 
<A-=>

**Comment by Quicksilver151** [comment]
> Can confirm this works great with these keybindings:
> 
> ```lua
> if vim.g.neovide == true then
>   vim.api.nvim_set_keymap("n", "<C-+>", ":lua vim.g.neovide_scale_factor = vim.g.neovide_scale_factor + 0.1<CR>", { silent = true })
>   vim.a
>  pi.nvim_set_keymap("n", "<C-->", ":lua vim.g.neovide_scale_factor = vim.g.neovide_scale_factor - 0.1<CR>", { silent = true })
>   vim.api.nvim_set_keymap("n", "<C-0>", ":lua vim.g.neovide_scale_factor = 1<CR>", { silent = true })
> end
> ```
> Great work, @BHatGuy!


was working a bit weird for me so i added limits
cause when size got set to 0 it crashed
```lua
if vim.g.neovide == true then
  vim.api.nvim_set_keymap("n", "<C-=>", ":lua vim.g.neovide_scale_factor = math.min(vim.g.neovide_scale_factor + 0.1,  1.0)<CR>", { silent = true })
  vim.api.nvim_set_keymap("n", "<C-->", ":lua vim.g.neovide_scale_factor = math.max(vim.g.neovide_scale_factor - 0.1,  0.1)<CR>", { silent = true })
  vim.api.nvim_set_keymap("n", "<C-+>", ":lua vim.g.neovide_transparency = math.min(vim.g.neovide_transparency + 0.05, 1.0)<CR>", { silent = true })
  vim.api.nvim_set_keymap("n", "<C-_>", ":lua vim.g.neovide_transparency = math.max(vim.g.neovide_transparency - 0.05, 0.0)<CR>", { silent = true })
  vim.api.nvim_set_keymap("n", "<C-0>", ":lua vim.g.neovide_scale_factor = 0.5<CR>", { silent = true })
  vim.api.nvim_set_keymap("n", "<C-)>", ":lua vim.g.neovide_transparency = 0.9<CR>", { silent = true })
end
```
