### ISSUE TITLE
Misaligned and overlapping icon characters

### ISSUE THREAD

**Issue by 0x0013** [neovide/neovide#1302]
**Describe the bug**
Icons in buffer are enlarged and misaligned to the right side of the character bounds in neovide, while in terminal nvim they are fine.

**To Reproduce**
1. Open buffer
2. Insert icon character such as ⚠ between standard characters

**Expected behavior**
Icons are centered in their allocated character space, and keep in bounds. See screenshot with nvim on terminal.

**Screenshots**
Neovide on the left, same file in nvim in terminal (kitty) on right.
![image](https://user-images.githubusercontent.com/101050452/167068481-41706fdf-ea06-4599-b41a-8d56f69e66fd.png)

Here is a close-up. I have left the cursor in the middle of the second line. Since the cursor is one character width, it's very visible how the warning symbol is both enlarged and, more importantly, misaligned to the right side. It is even more visible on the third line, between wider characters such as 'A'.
![image](https://user-images.githubusercontent.com/101050452/167070082-c62bc11a-6ab4-45bf-a4d9-bbbf66c483a2.png)

**Desktop:**
 - OS: Linux (Wayland/Sway)
 - Neovide Version 0.8
 - Neovim Version 0.7.0

**Additional context**
Note that this is not an issue with emoji icons, which take up precisely 2 full character spaces, thus not going out of their reserved grid.

**Comment by fredizzimo** [comment]
This is most likely fixed, and looks like a broken nerdfont, that doesn't properly reserve 2 spaces for the glyphs that are used.
