### ISSUE TITLE
Neovide closes immediately after opening for the second time

### ISSUE THREAD

**Issue by Leonidas-from-XIV** [neovide/neovide#1308]
**Describe the bug**
On the second launch, neovide immediately closes itself with returncode 0. It doesn't crash so I am not sure this is the same error as #1307.

**To Reproduce**
1. Launch neovide
2. Close neovide
3. Launch neovide again
4. it closes itself automatically

**Expected behavior**
Neovide staying open

**Desktop (please complete the following information):**
 - OS: [e.g. macOS 11.4] Fedora 36
 - Neovide Version [e.g. 0.6.0] 0.8.0
 - Neovim Version [e.g. 0.5.0] 0.7.0

**Additional context**
The problem was that if I launch neovide it reads some settings (I don't know where from, maybe an older config?) and sets them in `.local/share/nvim/neovide-settings.json`, but unfortunately what it saves is invalid:

```
{"window":{"Windowed":{"position":{"x":0,"y":0},"size":{"width":105,"height":36}}}}
```
When launching `neovide --nofork` it shows this error message:

```
wl_surface@16: error 2: Buffer size (735x576) must be an integer multiple of the buffer_scale (2)
```

Which hints at the error. Fixing the `width` to an even number makes neovide launch and stay open. This can be reproduced easily by setting the `width` to an odd number which makes neovide fail to start.

**Comment by fredizzimo** [comment]
This should be fixed in the lates 0.12.1 release
