### ISSUE TITLE
Can't map <S-D-x>

### ISSUE THREAD

**Issue by skanev** [neovide/neovide#1309]
**Describe the bug**

Try as I might, I cannot map `<S-D-a>` (or any Cmd+Shift mapping) on macOS.

**To Reproduce**

1. Get a mac and do this on the mac
2. Set `let g:neovide_input_use_logo = 1` for good measure
3. Run `map <S-D-a> ihello` to do a Cmd+Shift mapping
4. Hit Cmd+Shift+a and watch your mapping not getting executed. It actually sends `<D-a>`

**Expected behavior**

The mapping to be execute (because Vim got `<S-D-a>`)

**Screenshots**

**Desktop (please complete the following information):**
 - macOS 12.3.1
 - Neovide Version 0.8.0, but it happens on 
 - Neovim Version 0.7.0

**Additional context**

I tried to get it fixed an open a PR, but I couldn't figure if I'm not breaking anything, and thought to open an issue and ask here instead. If somebody would like to give me guidance, I'm very happy to open a PR.

Anyway, I've managed to get it to work by changing [this line](https://github.com/lucas-miranda/neovide/blob/726539f/src/window/window_wrapper/keyboard_manager.rs#L132) from

```rust
        let shift = or_empty(self.shift && (use_shift), "S-");
```

to

```rust
        let shift = or_empty(self.shift && (use_shift || self.logo), "S-");
```

This is probably not how this should be fixed, but I struggle to figure out if I should pass `use_shift` as `true` in the caller or that will break something. Any pointers about either how I should fix this, or how should I test I'm not breaking anything, are highly appreciated!

**Comment by alexventuraio** [comment]
I'd love to see this feature moving forward, I'm coming from MacVim app and I'm very use to multiple mappings it has with SHIFT key and I'm just wondering when it gets supported by Neovide!

**Comment by alexventuraio** [comment]
I think this is also related See https://github.com/neovide/neovide/issues/992#issuecomment-1019569183.

**Comment by MultisampledNight** [comment]
what the doge, seems like a lot of duplicates with `<S-*` are out there, I'll take care of closing them while linking to #1483

`<S-*` support has been added in #1483, and since #1455 `g:neovide_use_logo` is `true` by default on macOS. The first PR is not in a release yet, so could you try building from source and see whether it works there?

**Comment by alexventuraio** [comment]
Sorry for buttering you one more time with the same topic, but yeah, I'm very happy to build from source and give it a try!
Where can I find the instructions to build it from source?

**Comment by MultisampledNight** [comment]
No worries! See https://neovide.dev/installation.html#mac-source, step 7 and following are only needed if you want an `.app` bundle. Feel free to ask if you hit any build issues, which are probably best handled on a more synchronous chat platform (like Discord or Matrix).

**Comment by alexventuraio** [comment]
@MultisampledNight just to let you know, I followed the instructions to build it from source in `MacOS Monterrey v12.4 Apple M1 Pro Silicon chip`, and every step went well, no warnings or bugs and my key mappings with <kbd>SHIFT</kbd> key are working just fine! ✅

**Comment by MultisampledNight** [comment]
Thank you! I'll keep the issue for searchability open though, at least until the next release.
