### ISSUE TITLE
Neovide constantly using cpu at idle

### ISSUE THREAD

**Issue by 0x0013** [neovide/neovide#1310]
**Describe the bug**
I'm seeing constant CPU usage of ~3% when neovide is running. This happens both with my normal config, as well as with `neovide -- --clean`, and persists with multigrid both enabled and disabled. Both when neovide is in focus or not in focus, or on a different (not visible) window manager workspace.

**To Reproduce**
1. Open neovide.
2. Observe cpu usage while neovide is idle.

**Expected behavior**
Neovide keeps idle while not actively used.

**Desktop (please complete the following information):**
 - OS: Arch Linux with Sway (also observed on different computer with i3)
 - Neovide Version 0.8.0 (AUR neovide) and 0.9.0 (AUR neovide-git)
 - Neovim Version 0.7.0

**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**

Log keeps growing with the following lines endlessly repeating:
```
TRACE [neovide::window] Settings geometry PhysicalSize { width: 69, height: 45 }
TRACE [neovide::window] Inner size: PhysicalSize { width: 3212, height: 1020 }
TRACE [neovide::window] Inner size scaled: PhysicalSize { width: 1606, height: 510 }
TRACE [neovide::window] Settings geometry PhysicalSize { width: 69, height: 45 }
TRACE [neovide::window] Inner size: PhysicalSize { width: 3212, height: 1020 }
TRACE [neovide::window] Inner size scaled: PhysicalSize { width: 1606, height: 510 }
TRACE [neovide::window] Settings geometry PhysicalSize { width: 69, height: 45 }
TRACE [neovide::window] Inner size: PhysicalSize { width: 3212, height: 1020 }
TRACE [neovide::window] Inner size scaled: PhysicalSize { width: 1606, height: 510 }
```
Full log attached. 
[neovide_rCURRENT.log](https://github.com/neovide/neovide/files/8692349/neovide_rCURRENT.log)

**Additional context**

Similar issue #440 but that seems to be a different issue, as that was reported only happening with multigrid enabled, while my issue persists with both options.

This does not impact performance for me, but the constant usage can impact battery life. While the idle usage is not high, I think it is too high for idle usage, and is probably not expected behavior, seeing as the usage is higher than a web browser at idle.

CPU usage increases when I am actively using Neovide (which is expected). I can also see GPU usage spike while I am using Neovide, so GPU is working.

While I primarily use Neovide on Sway, I have observed similar behavior on different hardware with i3, although I did not check the logs, so cannot say for sure it was the same issue.

**Comment by balroggg** [comment]
Same issue for me, around ~3% CPU. Maybe missing early `return` in `draw_frame` function.

**Comment by DerFetzer** [comment]
I profiled an idle neovide in the background with perf for one minute:

![neovide_idle_perf](https://user-images.githubusercontent.com/11207998/182665729-37bc29d1-f439-4cf2-9a31-46953ae35cab.png)

As you can see 58% of cpu time is spent in `winit` for event handling and only about 20% in actual `neovide` code.

One solution that I can see is to detect when neovide loses focus and then to lower the target frame rate maybe even to 0. This solves the load for me.

@MultisampledNight Do you think this would be a valid approach? If yes I'll prepare a pull request.

**Comment by MultisampledNight** [comment]
I'm not really active on Neovide for a week or two, but yeah, that's a valid solution. Note that this won't fix anything on Wayland though, as there we have no idea whether we're focused atm or not.

Anyways, the current renderer is suboptimal. Kethku, the original author of Neovide, did some effort to improve it in #1201, it might be worth thinking about the whole concept of rendering and an idealized frame timeline in general. But for now, your approach should bring a benefit on many platforms.

**Comment by Kethku** [comment]
I don't think this is an issue on main
