### ISSUE TITLE
Invalid runtimepath on Windows

### ISSUE THREAD

**Issue by qumusabel** [neovide/neovide#1315]
**Describe the bug**
Neovim seems to have wrong `runtimepath` when running with `--neovim-bin`. `syntax on` doesn't work: 
![image](https://user-images.githubusercontent.com/18624304/168724161-f127167f-be4c-451b-9275-3f26e38cee33.png)

**To Reproduce**
Launch neovide with `--neovim-bin`.

**Expected behavior**
Everything works.

**Screenshots**
`runtimepath` in nvim and nvim-qt:

![image](https://user-images.githubusercontent.com/18624304/168725255-87b71e5a-2e0c-437c-a039-cc04aa2118ab.png)

in neovide:

![image](https://user-images.githubusercontent.com/18624304/168725302-81e35bfc-9525-4063-9c2c-27dc323cba64.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Neovide Version 0.8
 - Neovim Version 0.7.0

**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**
It's too long to paste here, and anyways it only contained rendering logs.

</details>

**Comment by fredizzimo** [comment]
This should be fixed in the latest release, if not please reopen the issue.
