### ISSUE TITLE
Hide title bar in macOS

### ISSUE THREAD

**Issue by xbladesub** [neovide/neovide#1317]
Is there any way to hide title bar in macOS? I don't want to run it in fullscreen because cannot move using desktop shortcuts.

It looks terrible in new MacBooks not in fullscreen mode, too much space taken by title + stupid new MacBooks top bar:
<img width="1512" alt="Screen Shot 2022-05-21 at 4 27 32 AM" src="https://user-images.githubusercontent.com/45129790/169606070-b343702c-a8d5-4fef-a15c-5ca5cacc9840.png">

**Comment by MultisampledNight** [comment]
See the wiki: https://github.com/neovide/neovide/wiki/Configuration#frameless.

**Comment by Gurmukh-Singh-4253** [comment]
I have the same issue at this point of time, and it seems like this like this link has been deprecated. Please update the link

**Comment by MultisampledNight** [comment]
Done. Thanks for the hint!
