### ISSUE TITLE
Problems rendering text with Unicode

### ISSUE THREAD

**Issue by nowave7** [neovide/neovide#1318]
**Describe the bug**
I'm experiencing some problems displaying text that has Unicode characters in it, and it appears to be a problem only with Neovide. Neither nvim nor gvim nor vim seem to be affected by it.

**To Reproduce**
The way to reproduce it is to open a file with Unicode characters in it (like the one in attachment sr.txt), and then scroll. What happens is that lines get torn when scrolling.

**Expected behavior**
The file should be displayed correctly, ie. all the lines should be displayed without tearing.

**Desktop (please complete the following information):**
Linux Mint 20.3 Cinnamon
Cinnamon version: 5.2.7
Neovide 0.8.0
NVIM v0.6.0-dev+332-gabf13258c
Build type: RelWithDebInfo
I've got a couple of plugins installed, but not sure if these are relevant, since all other vi flavors also use them.

I've included the screenshots of neovide as well as of vim, gvim, and nvim, as well as the file with unicode characters (it's actually an qml filen, but I had to rename it because github doesn't support that filetype. The content is really not important, other that it contains Unicode).
When I remove the said characters from the file (for example the likes of these: èeéêë€), the file is being displayed normally.

**Screenshots**
vim
![vim](https://user-images.githubusercontent.com/1130101/169647246-4a128f8d-654b-4738-ac66-255ffde72f6a.png)
nvim
![nvim](https://user-images.githubusercontent.com/1130101/169647247-f4ac1793-af68-43eb-a626-e4331479b5a8.png)
gvim
![gvim](https://user-images.githubusercontent.com/1130101/169647250-b454e0db-b025-4e67-a5be-478f060f1f11.png)
neovide
![neovide](https://user-images.githubusercontent.com/1130101/169647249-6ac39b2b-7822-40a9-bb45-e7e3b14dc553.png)

Test file
[sr.txt](https://github.com/neovide/neovide/files/8747398/sr.txt)

**Comment by falcucci** [comment]
this is fixed in the latest versions, if in any case it persist somehow please let us know
