### ISSUE TITLE
Telescope recent files (macOS)

### ISSUE THREAD

**Issue by xbladesub** [neovide/neovide#1321]
Telescope doesn't show recent files. Everything works as expected if I use terminal. Any ideas how to fix this? I already gave all possible permission to Neovide - didn't help

**Comment by xbladesub** [comment]
it seems to work now, I had to give neovide different permissions manually

**Comment by guangxu-li** [comment]
Facing the same issue.

**Comment by guangxu-li** [comment]
solved by upgrading neovide from 0.8 to 0.9

> Facing the same issue.

**Comment by Kethku** [comment]
I think this is fixed in current main. Please reopen if problems persist
