### ISSUE TITLE
Pass commands to running neovide (macOS)

### ISSUE THREAD

**Issue by xbladesub** [neovide/neovide#1324]
May be it's stupid question, but is it possible to pass commands using shell script to running neovide on macOS? My goal is to create automator app which will open new buffer in running neovide when I click on any text file

**Comment by MultisampledNight** [comment]
Not directly with Neovide. But you can explicitly pass the `--neovide-tcp` option to set where Neovide should try to connect to, and use the same channel then to communicate with NeoVim behind the scenes.

**Comment by xbladesub** [comment]
> Not directly with Neovide. But you can explicitly pass the `--neovide-tcp` option to set where Neovide should try to connect to, and use the same channel then to communicate with NeoVim behind the scenes.

drag and drop feature works in macOS (it open new buffer) so may be any other solution to open files by click in macOS, not tcp communication?

**Comment by MultisampledNight** [comment]
That works completely different. By dropping a file into Neovide, your window manager (well, not directly, but kind of) says "hey, I have a file for you" which we [can conveniently access through `winit`](https://docs.rs/winit/0.26.1/winit/event/enum.WindowEvent.html#variant.DroppedFile). There's no inter-process communication involved.

**Comment by xbladesub** [comment]
> That works completely different. By dropping a file into Neovide, your window manager (well, not directly, but kind of) says "hey, I have a file for you" which we [can conveniently access through `winit`](https://docs.rs/winit/0.26.1/winit/event/enum.WindowEvent.html#variant.DroppedFile). There's no inter-process communication (from the NeoVim side) involved.

Is there any way to create middle app which will trigger winit and pass file to neovide's new buffer?

**Comment by MultisampledNight** [comment]
I don't know how macOS' windowing system works and how hackable it is, sorry. It may be worth researching on Quartz though.

**Comment by dartacao** [comment]
If you're looking for a way to open files/send commands/send keypresses to an already running neovim/neovide instance, check out [neovim-remote](https://github.com/mhinz/neovim-remote). I have a couple of shell aliases so that nvr fits my workflow specifically. I am on windows but as far as I know it works on Mac as well.
Here's how I set it up with powershell and neovide: (note that $env:NVIM_LISTEN_ADDRESS must be set for this to run
```
function nvd { neovide --multigrid -- --listen "$env:NVIM_LISTEN_ADDRESS" }
function nvr { nvr.exe -s --nostart -l $args; if ($LastExitCode -ne 0) { nvd; if ($args) { nvr.exe -s --nostart -l $args } } }
```

**Comment by Kethku** [comment]
Closing as there are alternatives and the core ask is covered elsewhere
