### ISSUE TITLE
Using neovide (Open with...) as my default replacement to TextEdit.app on Mac

### ISSUE THREAD

**Issue by AjayShanker-geek** [neovide/neovide#1326]
**Describe the bug**
Opening my codes using neovide will only open my neovim dashboard. 

**To Reproduce**
1. Right Click
2. Open with neovide 

**Expected behavior**
Open the selected file on neovide

**Desktop (please complete the following information):**
 - OS: macOS 12.4
 - Neovide Version: Version 0.8.0 (20220404.162807)
 - Neovim Version: NVIM v0.7.0

**Comment by MultisampledNight** [comment]
See #1259.

**Comment by xbladesub** [comment]
Musthave feature)

**Comment by amit-ug** [comment]
> See #1259.

This is a great workaround! 👍 

Adding this as built-in supported feature is "a must" for neovide to be useful out-of-the-box on macs (and probably every other platform as well).

**Comment by MultisampledNight** [comment]
Linux at least doesn't require much intervention from the application side, it just works already because the `.desktop` file of Neovide already specifies on how to forward files to Neovide.

**Comment by MultisampledNight** [comment]
Closing as duplicate in favor of #1259.
