### ISSUE TITLE
Crash when nvim-cmp completion is very long

### ISSUE THREAD

**Issue by muhmud** [neovide/neovide#1328]
**Describe the bug**
When an [hrsh7th/nvim-cmp](https://github.com/hrsh7th/nvim-cmp) completion is very long, say 2000 characters, Neovide will crash. I've tried this in a terminal and it's fine.

**To Reproduce**
1. Open a file with a very long word completion available
2. Go to a place in a the file and type the first few letters of the word
3. Neovide will crash

**Expected behavior**
Neovide should behave the same as the terminal, and not crash.

**Desktop (please complete the following information):**
 - OS: Manjaro Linux
 - Neovide Version: 0.9.0
 - Neovim Version: 0.7.0

**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**
[log](https://drive.google.com/file/d/1CsElTcAXMBOdwciYuFen3KeRlvV2DGas/view?usp=sharing)

**Additional context**
I am using Neovide with Lunar Vim.

**Comment by MultisampledNight** [comment]
Hm, do you have any snippet or example configuration which can reproduce that? I can imagine it's somewhere in the NeoVim communication stuff, but having something reproduceable would be nice.

**Comment by dineshKumar777** [comment]
@muhmud I am not able to reproduce this. enabled cmp-buffer, and its completing 5000 chars without crash
it would be helpful if you share reproducible config or video recording!

![image](https://user-images.githubusercontent.com/21097695/173715555-125e204d-13c8-4bc3-b9a6-70e29e31345a.png)

**Comment by muhmud** [comment]
Sorry guys, I've been a little busy recently, will get something to you soon.

As requested, I'll try to get you a minimal config you can use to reproduce it

**Comment by Kethku** [comment]
Closing for lack of response
