### ISSUE TITLE
Neovide doesn't remember window size/position (macOS)

### ISSUE THREAD

**Issue by xbladesub** [neovide/neovide#1337]
It seems like neovide doesn't want to remember not size neither position of the window.
What's strange - that it worked before and no anymore. 

this is my config:
```lua
vim.g.neovide_cursor_animation_length = 0.03
vim.g.neovide_cursor_trail_size = 0.75
vim.g.neovide_cursor_vfx_mode = "ripple"
vim.g.neovide_remember_window_size = true
vim.g.neovide_remember_window_position = true
vim.g.neovide_cursor_antialiasing = true
```

Also it works when I manually changing neovide-settings.json (I deleted this file and it doesn't create anymore automatically, not even after reinstall). Tried building from source and downloading ready bundle.

Please show me how neovide-settings.json should look like to maximize the window (not fullscreen) so I'll create neovide-settings.json file manually and set window to maximum

**Comment by ernie** [comment]
I believe this is related to #1279 which is tracking something I observed in #1247 as well.

**Comment by ernie** [comment]
If so, you might notice that it will save if you quit by clicking the close button and not clicking quit or using command-q.

**Comment by d12bb** [comment]
For me, it remembers window size, unless I maximized it. If it was maximized last time, it will open its default small size. Not depending on how I closed it (tried `:q`, `Cmd-q` and clicking the red button).

**Comment by xbladesub** [comment]
> If so, you might notice that it will save if you quit by clicking the close button and not clicking quit or using command-q.

hard to guess when you also have '--frame none' )

**Comment by s-cerevisiae** [comment]
> For me, it remembers window size, unless I maximized it. If it was maximized last time, it will open its default small size. Not depending on how I closed it (tried `:q`, `Cmd-q` and clicking the red button).

@d12bb It's a bit late now, but this might be fixed with #1525.

**Comment by d12bb** [comment]
Just tested fresh HEAD, using `cargo run`, Neovide specific parts of config below, complete [here](https://github.com/d12bb/dotfiles/tree/main/nvim). It works flawlessly now when using `:q`, with `Cmd+q` however it doesn't remember at all.


```fnl
(set! guifont "FiraCode Nerd Font Mono")
(when (and (boolean? vim.g.neovide) (= vim.g.neovide true))
  (g! neovide_remember_window_size true)
  (if (= vim.fn.getcwd "/")
      (vim.api.nvim_set_current_dir "~")))
```

**Comment by xbladesub** [comment]
Yep, figured out that many plugins have issues if I quit Neovide with cmd+q
