### ISSUE TITLE
Strange visual artifacts on Neovide start

### ISSUE THREAD

**Issue by xbladesub** [neovide/neovide#1339]
I got this
<img width="1322" alt="Screen Shot 2022-06-01 at 1 25 43 PM" src="https://user-images.githubusercontent.com/45129790/171333957-49e4cd5a-3a52-46e3-af67-ce4aa94a5d68.png">

I start neovide with --frame none --multigrid

**Comment by Kethku** [comment]
Closing as this probably isn't an issue anymore. Please reopen if this continues.
