### ISSUE TITLE
Click to focus on MacOS should not move the cursor

### ISSUE THREAD

**Issue by mgax** [neovide/neovide#1343]
**Is your feature request related to a problem? Please describe.**
On MacOS, if Neovide is in the background, and I click on its window, that brings Neovide to foreground _and also moves the cursor to where I clicked_.

**Describe the solution you'd like**
On MacOS, it's common for apps to receive focus via mouse click, _without_ the click being interpreted as an interaction with the UI elements of the app. I'd like Neovide to honor that convention and not move the cursor. It's easy enough to click again and move the cursor.

**Describe alternatives you've considered**
Some people might prefer the current behaviour; it could be configurable.

**Comment by dineshKumar777** [comment]
@mgax this behavior is from vim upto my knowledge. I tested this in terminal and nvim-qt too.
https://vim.fandom.com/wiki/How_to_not_move_cursor_when_selecting_window_with_mouse

As per wiki, you can disable this using vimscript.

Pls close this if its resolved

**Comment by mgax** [comment]
> As per wiki, you can disable this using vimscript.

Thanks for that link, it does work in neovide too! FWIW here's the lua version:

```lua
local no_cursor_move_on_focus = vim.api.nvim_create_augroup('NO_CURSOR_MOVE_ON_FOCUS', {clear = true})
vim.api.nvim_create_autocmd('FocusLost', {
  pattern = '*',
  group = no_cursor_move_on_focus,
  command = 'let g:oldmouse=&mouse | set mouse='
})
vim.api.nvim_create_autocmd('FocusGained', {
  pattern = '*',
  group = no_cursor_move_on_focus,
  command = "if exists('g:oldmouse') | let &mouse=g:oldmouse | unlet g:oldmouse | endif"
})
```

---
However, it feels like a hack, to undo a behaviour that's non-standard. IIUC "click-through" on MacOS is [off by default](https://apple.stackexchange.com/a/50753) and has to be explicitly enabled by apps, by implementing [acceptsFirstMouse](https://developer.apple.com/documentation/appkit/nsview/1483410-acceptsfirstmouse). Neovide depends on glutin which depends on winit which does indeed implement the method, returning `YES`: https://github.com/rust-windowing/winit/blob/6474891f1e04d66704e3ed84ee585cd8b02ba19f/src/platform_impl/macos/view.rs#L312-L315.

FWIW, MacVim doesn't enable click-through. I've recently switched from MacVim so that's how I noticed the issue.

**Comment by tobywan** [comment]
I came here to report the same problem. I'm trying out a few Neovim gui apps, and Neovide is my fave so far, however I'm finding I have to click on the window title bar (mac) to give focus if I want to avoid cursor the cursor following the mouse.

VimR for example doesn't have this issue. I click once to activate then a second time to move cursor.

**Comment by mgax** [comment]
FWIW, the workaround stopped working, probably after a recent update. Here's what I'm currently running:
* Mac OS 12.5.1
* Neovim 0.7.2
* Neovide 0.10.1

**Comment by mgax** [comment]
Fixed with https://github.com/neovide/winit/pull/8 and https://github.com/neovide/neovide/commit/b674fc4e9b97b657e5ab425d890675a36af7ae8b; thanks @MultisampledNight!
I've built Neovide from the latest `main` and it works like a charm.
