### ISSUE TITLE
Use Neovide as a diff tool

### ISSUE THREAD

**Issue by kishikaisei** [neovide/neovide#1346]
**Is your feature request related to a problem? Please describe.**
I want to open Neovide in diff mode so I can use it as a diff tool (instead of running nvim -d file1 file2, run neovide with the same parameters)

**Describe the solution you'd like**
An argument such as: neovide -d file2 file2

**Describe alternatives you've considered**
Just using nvim -d in a terminal window.

**Additional context**
---

**Comment by MultisampledNight** [comment]
Unnecessary. Neovide can passthrough arguments to NeoVim using ` -- `. Everything after those two dashes (space included) is directly interpreted by NeoVim, as documented in `neovide --help`.

**Comment by nyc-tinker** [comment]
Does this work anymore?  When I run `neovide -- -d file1 file2` I see now the two files that are tabs in neovide; they are not diff'ed.

**Comment by liarchgh** [comment]
> Agreed, didn't know about this feature: `neovide -- -d file1 file2` works

@kishikaisei 

It doesn't work. It just open two files in two tabs.

Can you show your config?

**Comment by mlmoses** [comment]
I think this should probably be reopened, or maybe there just needs to be a new ticket. `neovide -- -d file1 file2` doesn't work for me either. However, if you use `neovide -- -d -O file1 file2` or `neovide --notabs -- -d file1 file2`, then you get diff mode with vertical splits as expected. 

According to the [documentation for `--notabs`](https://neovide.dev/command-line-reference.html#no-tabs):

> By default, Neovide opens files given directly to Neovide (not NeoVim through `--`!) in multiple tabs to avoid confusing new users.

This seems to imply that I should be able to run `neovide -- file1 file2` and get the default NeoVim behavior of opening the first file in  a new window with all other files only loaded into buffers. However, `neovide file1 file2` and `neovide -- file1 file2` both behave the same way: all files listed on the command line are opened in separate tabs. This is probably why `neovde -- -d file1 file2` doesn't work as expected.

As an aside, it might also be useful to allow users to disable the default behavior of using tabs with an environment variable, e.g. `NEOVIDE_NOTABS=true`

**Comment by unclenull** [comment]
@MultisampledNight Can we reopen this issue? It still breaks.

**Comment by fredizzimo** [comment]
There's nothing that needs to be done, it still works like the message above. Additionally, you can now set `tabs=false` in the config file https://neovide.dev/config-file.html, to make the behaviour persistent.

After that `neovide -- -d file1 file2`  works as expected.

Defaulting to opening in tabs unlike terminal neovim was IMO a rushed decision without too much discussion https://github.com/neovide/neovide/pull/1275. And I would prefer if it worked the same way. That's however, a breaking change and we currently don't have any open issues for changing the defaults of that. 

So, if you want to see it changed, please open an issue.

**Comment by FocusedWolf** [comment]
chatGPT figured it out, $ neovide -- -O ./A.txt ./B.txt -c 'diffthis | wincmd w | diffthis'

```
Explanation:
-O → opens files in vertical splits.
diffthis → enables diff in current window.
wincmd w → moves to next window.
diffthis → enables diff in the second window.
Neovide doesn’t automatically run :diffthis in splits when launched with -d, unlike terminal Neovim.
```

**Comment by fredizzimo** [comment]
@FocusedWolf, it does, but the default option of opening files in different tabs messes it up. That's something I would personally want to change.

So, this works
`neovide --no-tabs -- -d file1.txt file2.txt`
