### ISSUE TITLE
`set clipboard=unnamed` makes lline yank (`yy`) and then paste (`p`) behave wrong

### ISSUE THREAD

**Issue by saitonakamura** [neovide/neovide#1347]
**Describe the bug**
`set clipboard=unnamed` makes lline yank (`yy`) and then paste (`p`) behave wrong. It looks like paste is executed in the wrong order, it should be newline first, then line insert, but it's a line insert with a newline in the end instead.

**To Reproduce**
1. Use `set clipboard=unnamed` in your neovim config
2. Open neovide with nvim with such config
3. Write down two lines of text, e.g.
```
one
two
```
3. Use line yank (`yy`) on the first line
4. Go to the middle of the second line (e.g. cursor on `w` letter)
5. Paste yanked line via `p`
6. `one` will be paste in between the word rather than on the same line
Actual
```
one
twone
o
```

**Expected behavior**
```
one
two
one
```

**Desktop (please complete the following information):**
 - OS: Windows 11 + WSL2
 - Neovide Version: latest main
 - Neovim Version: 0.8.0

**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**
Log is 1mb, so I'm not sure if posting here is a good idea

**Additional context**
I'm not sure if it's windows/wsl issue, I'll try on macos later. If you can give guidance on how and where it should be fix I can try doing a PR but I'm really only starting on rust

**Comment by JulesNP** [comment]
The same issue also occurs with `set clipboard=unnamedplus`.

**Comment by saitonakamura** [comment]
Tried it w/ neovide without wsl and works correctly. Then it probably have something to do with wsl

**Comment by saitonakamura** [comment]
#1003 is when it started
