### ISSUE TITLE
Error when starting neovide

### ISSUE THREAD

**Issue by ayush-india** [neovide/neovide#1350]
**Describe the bug**
When i run the neovide command (installed by snap) its just gives me an error

**To Reproduce**
just type neovide and press enter

**Expected behavior**
Should open neovide 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: lubuntu 20.04
 - Neovide Version 0.8.0
 - Neovim Version 0.8 dev

**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: GlobError { path: ".", error: Os { code: 13, kind: PermissionDenie
d, message: "Permission denied" } }', /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/ops/function.rs:150:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by ayush-india** [comment]
what kind of additional info do you need

**Comment by MultisampledNight** [comment]
The output of `RUST_BACKTRACE=full neovide` and whether it works if you install Neovide through `cargo install --git https://github.com/neovide/neovide`.

**Comment by ayush-india** [comment]
IT will take some time coz i have only limited data and there is somthing comming up 
Updating carated.io and it takes all of my data . So is there a way to stop it or u have to wait

**Comment by MultisampledNight** [comment]
You probably have to wait, unfortunately.

**Comment by Kethku** [comment]
CLosing for lack of response
