### ISSUE TITLE
Crash on keymap using cmdline with `set cmdheight=0`

### ISSUE THREAD

**Issue by barklan** [neovide/neovide#1351]
**Describe the bug**
Neovide crashes on keymap assigned to `:noh<cr>` (or any other keymap that uses cmdline) with `set cmdheight=0` (option got [merged](https://github.com/neovim/neovim/pull/16251) in Neovim that hides inactive cmdline)

**To Reproduce**
1. `neovide --log -- -u NONE`
2. Set keymap: `:lua vim.keymap.set("n", ";", ":noh<cr>")`
3. `:set cmdheight=0`
4. Press `;`. Neovide crashes consistently (also for any other keymap that uses cmdline)

**Expected behavior**
Command works successfully without crashing Neovide or changing cmdline state (like in Neovim without GUI).

**Screenshots**
none

**Desktop (please complete the following information):**
 - OS: Arch Linux with KDE Plasma (kwin) in Wayland session.
 - Neovide: latest master (0.9, rev `d113a0e`)
 - Neovim: latest master (0.8.0, rev `7f8f8d6`)

**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**

Last lines:

```
TRACE [neovide::channel_utils] neovide::bridge::ui_commands::UiCommand Serial(Keyboard(";"))
TRACE [neovide::bridge::ui_commands] Keyboard Input Sent: ;
TRACE [neovide::bridge::handler] Neovim notification: "redraw"
ERROR [neovide::error_handling] Could not parse event from neovim: invalid u64 format -1
ERROR [neovide::bridge] Error joining IO loop: 'task 9 panicked'
INFO [neovide::running_tracker] Quit neovim processed failed
DEBUG [neovide::settings::window_geometry] Saved Window Settings: {"window":{"Windowed":{"position":{"x":0,"y":0},"size":{"width":72,"height":27}}}}
```

Full log:

[neovide_rCURRENT.log](https://github.com/neovide/neovide/files/8894277/neovide_rCURRENT.log)

**Additional context**
none

**Comment by Shougo** [comment]
Please test https://github.com/neovim/neovim/pull/18961

**Comment by barklan** [comment]
> Please test [neovim/neovim#18961](https://github.com/neovim/neovim/pull/18961)

This fixes the issue. And thank you for your work - this feature is amazing!
