### ISSUE TITLE
What's the font neovide using when connect to remote tcp server?

### ISSUE THREAD

**Issue by fecet** [neovide/neovide#1352]
![image](https://user-images.githubusercontent.com/41792945/173834797-d399df19-5bb2-4b7c-bba7-550202cf2282.png)
The font seem to miss when connect to remote tcp server

**Comment by MultisampledNight** [comment]
It's the default font, Fira Code. You can configure it with the `guifont` option, see `:h guifont`.

**Comment by jamespeapen** [comment]
I have this issue as well - on Ubuntu. The font is set with `set guifont` and works for a local window, but doesn't when `--remote-tcp` is set. The font goes to the fallback whether the remote server is the localhost or is another machine.

**Comment by fredizzimo** [comment]
This should be fixed, and the initial settings read. But if not, please re-open the issue.
