### ISSUE TITLE
the window pops up and disappears suddenly on ubuntu

### ISSUE THREAD

**Issue by zero2076** [neovide/neovide#1362]
#### **mail: zero2076@outlook.com**

**Comment by MultisampledNight** [comment]
You could do a screenrecording while you perform those steps, and then take one frame where that happens and something is visible. Or you run Neovide through `neovide --nofork` and observe the output in the terminal. Or you take a look at `coredumpctl`, where at the bottom Neovide might be listed.

**Comment by zero2076** [comment]
ok,I'll try tomorrow

**Comment by zero2076** [comment]
![Screenshot from 2022-08-29 13-20-08](https://user-images.githubusercontent.com/104552112/187129003-37a07dae-4840-4163-83f3-fa98746ea803.png)
### the only picture I've got......
### It was the grey window.

**Comment by zero2076** [comment]
I mean the grey window pops up and then it was gone without displaying anything.The bug can be activated about one of  four times......I'm not quite sure.The bug seems to be the problem of appimage......For the solution I built it from source.

**Comment by MultisampledNight** [comment]
Hi again! Could you retry with the AppImage from `main`, as in from https://github.com/neovide/neovide/actions/runs/5476134854, and run it on the command line with `--nofork` as argument?

**Comment by zero2076** [comment]
The AppImage now launches well now. Tested on fedora 38 and ubuntu 22.04, it now seems to provide the transparent window shown in the snapshot every time, and then works properly. Thanks for your work.
________________________________
