### ISSUE TITLE
Way too Zoomed in by default on Windows 11

### ISSUE THREAD

**Issue by sergiza** [neovide/neovide#1367]
After I updated from 0.4 to 0.8 the scale just became enormous. Also I don't really know if this can be changed at all.
![toobig](https://user-images.githubusercontent.com/25955239/175541983-d664bccd-8083-4714-9dbc-f6da20b8c4bd.png)

**Comment by LoipesMas** [comment]
You can change the fontsize (as well as the font) with the `guifont` setting, e.g. `set guifont=FontName:h13`

**Comment by MultisampledNight** [comment]
You can easily change it by setting the `guifont` option, as documented in `:h guifont`, the default font is Fira Code. Who knows what could've changed since 0.4 to keep that exact default, so I won't look into this.
