### ISSUE TITLE
Neovide does not start, shows error: flexi_logger has to work with UTC rather than with local time, caused by IndeterminateOffset

### ISSUE THREAD

**Issue by robcmills** [neovide/neovide#1369]
**Describe the bug**

I compiled on Apple M1 Pro, and when I start neovide I immediately get an error in the console:
```
~/neovide/target/release [main]> ./neovide
[flexi_logger][ERRCODE::Time] flexi_logger has to work with UTC rather than with local time, caused by IndeterminateOffset
    See https://docs.rs/flexi_logger/latest/flexi_logger/error_info/index.html#time
```

**To Reproduce**

- Install the latest version of Rust. Using homebrew: `brew install rustup-init`
- Configure rust by running `rustup-init`
- Install CMake. Using homebrew: `brew install cmake`
- `git clone https://github.com/neovide/neovide`
- `cd neovide`
- `cargo build --release`
- `cd target/release`
- `./neovide`

**Expected behavior**

Neovide starts without error

**Desktop (please complete the following information):**

 - OS: macOS Monterey v12.0.1 Apple M1 Pro
 - Neovide 0.9.0
 - NVIM v0.7.0

**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**

```
~/neovide/target/release [main]> ./neovide --log
[flexi_logger][ERRCODE::Time] flexi_logger has to work with UTC rather than with local time, caused by IndeterminateOffset
    See https://docs.rs/flexi_logger/latest/flexi_logger/error_info/index.html#time
```
_(same error as trying to start)_

**Additional context**

Terminal: iTerm2 Build 3.4.15

**Comment by michalspano** [comment]
The same issue here. 

OS: `macOS Monterey 12.4 (21F79)`

`neovide --log`:
```
TRACE [neovide] Neovide version: 0.9.0
```

**Comment by krissen** [comment]
Same on macOS Ventura 13.6.

```
TRACE [neovide] Neovide version: 0.11.2
```

**Comment by fredizzimo** [comment]
It should still start with even when that error message is shown. I have it in Linux myself since I set `timedatectl set-local-rtc 1` to make Windows and Linux use the same clock.

Instead, I think you are running into this more generic issue https://github.com/neovide/neovide/issues/1859.

**Comment by fredizzimo** [comment]
Closing this, as the startup issue should be fixed. And the logger issue is just a warning with the logger, but works perfectly otherwise.
