### ISSUE TITLE
Snap won't start on Ubuntu 20.04 with AMD GPU

### ISSUE THREAD

**Issue by jes** [neovide/neovide#1372]
**Describe the bug**
I installed the snap on Ubuntu 20.04 with `sudo snap install neovide`. I tried to start neovide, but instead I got a load of graphics-related error messages, seemingly stemming from neovide trying to load amdgpu_dri.so from inside the snap directory instead of the main filesystem:

```libGL error: MESA-LOADER: failed to open amdgpu: /snap/neovide/132/usr/lib/x86_64-linux-gnu/dri/amdgpu_dri.so: cannot open shared object file: No such file or directory (search paths /snap/neovide/132/usr/lib/x86_64-linux-gnu/dri)```

I'm now building from source, but reporting the bug anyway in case it helps.

**To Reproduce**
1. `sudo snap install neovide`
2. `neovide`

**Expected behavior**
I expected neovide to start and run.

**Screenshots**
![Screenshot from 2022-06-27 08-58-20](https://user-images.githubusercontent.com/297425/175889764-606a6d79-5164-45b5-81f5-1c7348e8169b.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Neovide Version 0.8.0
 - Neovim Version 0.4.3

**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**
Since this is a snap it doesn't seem to have permission to write a .log file to my working directory. I managed to get one under /tmp, but one of the files is very long, so I've attached it instead of pasting:
[neovide_rCURRENT.log](https://github.com/neovide/neovide/files/8989879/neovide_rCURRENT.log). The other one is just:

```
$ cat /tmp/snap.neovide/tmp/neovide_r2022-06-27_09-07-35.log 
TRACE [neovide] Neovide version: 0.8.0
```

**Additional context**

**Comment by Alex-vZyl** [comment]
Could be related to #1081?

**Comment by fredizzimo** [comment]
The snap package is very outdated, and can most likely not be fixed without upstream help, or by some snap expert https://forum.snapcraft.io/t/need-help-with-the-snap-for-neovide/35978, until then I think we should remove the snap package completely.

Closing this for now.
