### ISSUE TITLE
Tests failing on Windows

### ISSUE THREAD

**Issue by MultisampledNight** [neovide/neovide#1375]
The CI tests on Windows are failing. It's likely not to be a code change, since previous commits [which tested just fine before](https://github.com/neovide/neovide/actions/runs/2491442429/attempts/1) are [suddently failing](https://github.com/neovide/neovide/actions/runs/2491442429/attempts/2). The CI logs [are pretty silent](https://github.com/neovide/neovide/runs/7063205182?check_suite_focus=true#step:8:395), probably because [every output on stdout is being eaten by that unpublished `results.json`](https://github.com/neovide/neovide/blob/main/.github/workflows/build.yml#L43).

Since I don't have a Windows machine and skia-safe doesn't like being cross-compiled, could anyone look into that? I believe it's "just" a toolchain mistake, but it could be anywhere, from cargo2junit over nightly Rust to a mistake on our side.

**Comment by MultisampledNight** [comment]
@scottwillmoore, you mentioned you'd be happy to help with the build issues. Could you run `cargo test` in this repo on your machine and see what it yields?

**Comment by dineshKumar777** [comment]
@MultisampledNight  i am not able to reproduce this issue in my local. all tests are passing in my windows machine.

**Comment by dineshKumar777** [comment]
I tried with both stable and nightly
rustup default nightly-x86_64-pc-windows-msvc
rustup default stable-x86_64-pc-windows-msvc

![image](https://user-images.githubusercontent.com/21097695/176462370-efe03916-779d-4708-bb5a-54ccc0a37c1f.png)

**Comment by scottwillmoore** [comment]
I can confirm that I was able to successfully run `cargo test -- -Z unstable-options --format json > results.json` on both stable and nightly on my machine for the latest commit and `7a3bf52` (the failed build).

**I also just noticed that @dineshKumar777 found the issue in #1377. Does this mean this issue can be closed?

**Comment by MultisampledNight** [comment]
Ah yeah, sorry. Forgot about still being open. Thanks anyways!
