### ISSUE TITLE
Stylistic Sets

### ISSUE THREAD

**Issue by DakshG07** [neovide/neovide#1378]
**Is your feature request related to a problem? Please describe.**
Stylistic sets are variants of fonts. Cascadia Code has a cursive italic variant I'd like to enable, but cannot due to lack of support.

**Describe the solution you'd like**
Add support for stylistic sets.

**Describe alternatives you've considered**
I've tried Opentype Font Freezer but it failed to work.

**Comment by fredizzimo** [comment]
There's a PR open for this https://github.com/neovide/neovide/pull/1920
