### ISSUE TITLE
Please remove debug flag from release profile

### ISSUE THREAD

**Issue by alerque** [neovide/neovide#1381]
Why is `debug = true` enabled for the **release** build profile in your Cargo.toml? That seems like something you could set in the debug profile (I assume it defaults anyway) or your own custom profile, but should not be enabled by default in the default release profile.

**Comment by MultisampledNight** [comment]
Yeah, I agree. I guess it was meant for easier debugging in case of a coredump or the like, but so far we never received any coredumps nor had issues with it where other methods haven't worked better. Any objections if I remove it?

**Comment by MultisampledNight** [comment]
Done in 48dfe95b6e3b2552afbf805921aeeb26cf124d05, thank you!
