### ISSUE TITLE
Neovide instantly crashes

### ISSUE THREAD

**Issue by Tomkoid** [neovide/neovide#1383]
*as 1

**Comment by Tomkoid** [comment]
Bad text

**Comment by Tomkoid** [comment]
Bad text

**Comment by MultisampledNight** [comment]
...for some reason your issue looks completely empty for me, but fine on the Discord hook, so I'll just ask the actual question: Could you provide us with some environment information? Which scale factor is the actually yielded one? What's your `xrandr` setup, or whatever the equivalent on your system is?

It's still an issue to fix.

**Comment by Tomkoid** [comment]
> ...for some reason your issue looks completely empty for me, but fine on the Discord hook, so I'll just ask the actual question: Could you provide us with some environment information? Which scale factor is the actually yielded one? What's your `xrandr` setup, or whatever the equivalent on your system is?
> 
> It's still an issue to fix.

I am sorry, but I created new issue because I tried to edit something in the issue and GitHub deleted everything.
