### ISSUE TITLE
Is it possible to have a keymap that can increase or decrease transparency?

### ISSUE THREAD

**Issue by bokonist** [neovide/neovide#1389]
### Discussed in https://github.com/neovide/neovide/discussions/1382

<div type='discussions-op-text'>

<sup>Originally posted by **bokonist** July  3, 2022</sup>
I'd like to increase/decrease transparency of the neovide window without relaunching the window. Is this possible?
	`vim.g.neovide_transparency = 0.95`
I'm trying to set this property with a keymap but it's not happening.</div>

**Comment by MultisampledNight** [comment]
For me on Sway/Wayland

```vim
let g:neovide_transparency=0.2
```

works just fine, even at runtime. But that can only work if your colorscheme even supports transparency, e.g. sets the `guibg` of `Normal` to `NONE` (see `:h highlight-guibg`). You can also do that manually with `hi! Normal guibg=NONE`.

**Comment by bokonist** [comment]
@MultisampledNight  I'm using gruv-box-material, and when i run `hi! Normal guibg=NONE` the background goes opaque black. Does this mean gruvbox is the problem here?

**Comment by MultisampledNight** [comment]
...actually it's `-1`, not `NONE`, my fault.

Yeah, I doubt gruvbox is setting `-1` as `guibg`. Really not many themes do. Though a way to set _both_ "hey, transparency is allowed here" _and_ the color for the background to blend in would be nice, I think something like that could be implemented in Neovide with an extra configuration variable.

**Comment by MultisampledNight** [comment]
The interesting code for that is here, in case anyone wants to hack around on it:

https://github.com/neovide/neovide/blob/48dfe95b6e3b2552afbf805921aeeb26cf124d05/src/renderer/mod.rs#L135-L141

Seems like first the default background is drawn (in any case), then all windows are drawn, including the root window. I guess the root window draws the colorscheme background then.

**Comment by falcucci** [comment]
I made an example so you can use it basically as two commands

```bash
:IncreateTransparency
```

and

```bash
:DecreaseTransparency
```

Just use this and update it accordingly

```vim
" returns a dictionary containing the transparency,
" background color, and terminal color for either
" a dark or light color scheme, depending on the value of `color`.
function! GetTransparentColors(color, level)
    return {
        \ 'dark': {
        \   'transparency': a:level,
        \   'background_color': '#0f1117',
        \   'term_color': 'black'
        \ },
        \ 'light': {
        \   'transparency': a:level,
        \   'background_color': '#FFFFFF',
        \   'term_color': 'NONE'
        \ },
    \ }[a:color]
endfunction

function! MakeItTransparent(level)
    if g:neovide_transparency == a:level
        let g:neovide_transparency = 1.0
        " let g:neovide_background_color = '#000'
        hi Floaterm guibg='#000000'
        set winblend=0
        return
    endif

    let g:transparency_level = GetTransparentColors(&background, a:level)['transparency']
    let g:background_color = GetTransparentColors(&background, a:level)['background_color']
    let g:term_color = GetTransparentColors(&background, a:level)['term_color']
    let g:neovide_transparency = g:transparency_level
    hi Floaterm guibg='#000000'
    set winblend=100
endfunction

function! UpdateTransparency(delta)
    let g:neovide_transparency_point = g:neovide_transparency + a:delta
    let g:level = g:neovide_transparency_point
    echo g:level
    call MakeItTransparent(g:level)
endfunction

command IncreateTransparency :call UpdateTransparency(0.02 * 2.5)
command DecreaseTransparency :call UpdateTransparency(-0.02 * 2.5)
```
