### ISSUE TITLE
Please add to the wiki how to do conditional branching for neovide in init.vim.

### ISSUE THREAD

**Issue by miyukic** [neovide/neovide#1390]
**Is your feature request related to a problem? Please describe.**
Most people use the existing init.vim, and some want to write settings for neovide.
However, I don't think the wiki describes how to do conditional branching for neovide.

**Describe the solution you'd like**
Please add to the wiki how to do conditional branching for neovide in init.vim.

**Additional context**
I managed to find an existing issue and found a way to do it.
 #835
```vim
if (exists("g:neovide"))
" Here is an optional configuration for neovide
endif
```

**Comment by MultisampledNight** [comment]
Where exactly would you like to have it? Under `Configuration` it's pretty unfitting, since in there are only neovide specific things documented. If a new wiki page is warranted, how would you call it?

**Comment by miyukic** [comment]
Isn't the variable g:neovide specific to neovide?

**Comment by MultisampledNight** [comment]
It is, I'm not asking about the mechanism itself, it's completely fine. Just how you would like to have it documented.

**Comment by MultisampledNight** [comment]
Oh wow, now I get it. Yeah, you're right, that makes sense.

**Comment by miyukic** [comment]
I think it is one way to write Configure, and I thought it would be better to make a section in Congfigure like "How to write neovide-specific settings in existing init.vim".
I'm not saying this strongly, as I'm sure there are repository-specific policies.
Also, I'm not confident about naming the items, as I'm not very good at English.

**Comment by MultisampledNight** [comment]
Done in [the configuration page right at the top](https://github.com/neovide/neovide/wiki/Configuration/_compare/450ec08589c5dd648ba4dcc2cb23416c8b7a04f7), thank you!

**Comment by miyukic** [comment]
## How to write neovide-specific settings in the existing init.vim
You can describe settings that you want to activate only when you use NEOVIDE.
```vim
if (exists("g:neovide"))
" Here is an optional configuration for neovide
endif
```

For example, something like this?

**Comment by miyukic** [comment]
Thank you for listening to my request!
Thanks for the great app!!
