### ISSUE TITLE
Neovide does not pick up path from ~./bashrc

### ISSUE THREAD

**Issue by kskarthik** [neovide/neovide#1395]
**Describe the bug**
Neovide does not load `$PATH` from ~/.bashrc where i have i have custom paths

**Expected behavior**
Neovide Should load $PATH from `~/.bashrc`  as well

**Screenshots**

`:echo $PATH` result in both the scenarios 

- neovim (terminal)
![image](https://user-images.githubusercontent.com/11899221/178146356-abc1e526-73c5-44ee-b6da-a56a713cb9b1.png)

- Neovide
![image](https://user-images.githubusercontent.com/11899221/178146373-b93f54fd-3364-4b41-896e-d34e824631d0.png)

**Desktop (please complete the following information):**
- OS: Debian Linux
- Neovide 0.9.0

**Comment by MultisampledNight** [comment]
Use your profile file instead. This is done on purpose to avoid issues with people who put text banners in their `.zshrc`/`.bashrc`, like it already happened in #1229 and #1175, for example.

**Comment by kskarthik** [comment]
Thanks for the tip!

**Comment by kskarthik** [comment]
@MultisampledNight  launching with `neovide --nofork` fixes the issue, I am not sure if this is the right way

**Comment by MultisampledNight** [comment]
`--nofork` circumventing the issue is more of a sideeffect of Neovide "remaining" in your shell than "splitting out".

No, zsh for example has a file called `~/.zprofile` which is sourced only for login shells (assumed you log in over a TTY and continue from there), though `~/.zshenv` is more applicable here since it's always sourced. `.bashrc`/`.zshrc` is not the only file that's read upon startup.

**Comment by kskarthik** [comment]
Hi @MultisampledNight 

So, I narrowed down the problem to sway Window manager. When i open neovide via a sway keyboard shortcut, It does not apply my $PATH
```
# start neovim gui
bindsym $mod+n exec neovide --multigrid
```

**Comment by MultisampledNight** [comment]
Is it possible that you start sway in turn through a display manager and not from the TTY?

**Comment by kskarthik** [comment]
I have to install a display manager first, to test that out :smile:

**Comment by kskarthik** [comment]
@MultisampledNight  finally, i found the solution!

`~/.profile` must load the custom $PATH first, Then launch sway on login:

```
# if running bash
if [ -n "$BASH_VERSION" ]; then
    # include .bashrc if it exists
    if [ -f "$HOME/.bashrc" ]; then
			. "$HOME/.bashrc"
    fi
fi

# set PATH so it includes user's private bin if it exists
if [ -d "$HOME/bin" ] ; then
    PATH="$HOME/bin:$PATH"
fi

# set PATH so it includes user's private bin if it exists
if [ -d "$HOME/.local/bin" ] ; then
    PATH="$HOME/.local/bin:$PATH"
fi

# launch sway
[ "$(tty)" = "/dev/tty1" ] && exec sway
```
