### ISSUE TITLE
set guifont causes monospacing(ish)/font rendering issues

### ISSUE THREAD

**Issue by coders4tomorrow-gr** [neovide/neovide#1396]
**Describe the bug**
Running ```set guifont=<font>``` causes the font to appear monospaced and not render properly.  The default font also no longer loads until Neovide is restarted, even after running ```source $MYVIMRC```

**To Reproduce**
1. Install neovide on a Mac running Apple Silicon (using homebrew)
2. Run Neovide (I generally use ```--frame buttonless``` and ```--multigrid``` flags but this issue still occurs without)
3. Either run ```set guifont=<font>``` or include in init.vim

**Expected behavior**
The font renders properly (not monospaced)

**Screenshots**
Normal behavior (no ```set guifont```)
![neovideBugNormal](https://user-images.githubusercontent.com/108999986/178200293-fea6a9ee-0948-4b1d-a002-6fc0f488101f.png)
Bugged behavior (```set guifont=<font>```)
![neovideBug](https://user-images.githubusercontent.com/108999986/178200296-c887c884-8352-4a35-a374-733bd90be00c.png)

**Desktop (please complete the following information):**
 - OS: macOS 12.4 (Apple Silicon)
 - Neovide Version: 0.9.0
 - Neovim Version: 0.7.2

**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**
<details open>
<summary>neovide log</summary>
Github won't let me paste or upload unless I zip the file ><

[neovide_rCURRENT.log.zip](https://github.com/neovide/neovide/files/9081480/neovide_rCURRENT.log.zip)
</details>

**Additional context**
There was a custom unicode character that wouldn't render properly (which is why I started messing around with fonts in the first place) that is included in the init.vim, but the same issue occurs when this is removed.  
<details>
<summary>my current init.vim</summary>

syntax on
set number
set clipboard=unnamed
set autoindent
set expandtab
set tabstop=4
set softtabstop=0
set shiftwidth=4
set mouse=a
set cursorline
set guifont=Osaka
set statusline+=%{FugitiveStatusline()}
set statusline+==᪲

call plug#begin()
Plug 'preservim/nerdtree'
Plug 'tpope/vim-sensible'
" Plug 'wfxr/minimap.vim'
Plug 'tpope/vim-fugitive'
Plug 'haystackandroid/strawberry'
Plug 'sainnhe/edge'
call plug#end()

autocmd VimEnter * NERDTree
autocmd VimEnter * wincmd p

let g:minimap_width = 10
" let g:minimap_auto_start = 1
" let g:minimap_auto_start_win_enter = 1
" let g:minimap_git_colors = 1
" let g:neovide_transparency=0.9
" let g:neovide_floating_blur_amount_x = 2.0
" let g:neovide_floating_blur_amount_y = 2.0
let g:neovide_remember_window_size = v:true
let g:neovide_input_macos_alt_is_meta=v:false

" Use ctrl-[hjkl] to select the active split!
nmap <silent> <c-k> :wincmd k<CR>
nmap <silent> <c-j> :wincmd j<CR>
nmap <silent> <c-h> :wincmd h<CR>
nmap <silent> <c-l> :wincmd l<CR>
nnoremap <silent> <Leader><Leader> :source $MYVIMRC<cr>

" colorschemes
" edge things
if has('termguicolors')
    set termguicolors
endif
let g:edge_style='neon'
let g:edge_better_performace=1

" time based selection
if (strftime("%H") < 9) || (strftime("%H") > 20)
    " dark mode night
    set background=dark
    colo edge
    " colo strawberry-dark
else
    " light mode day
    set background=light
    colo edge
    " colo strawberry-light
endif
</details>

**Comment by MultisampledNight** [comment]
Allowing non-monospaced fonts has a few fun issues to solve. Since Neovim expects to have a grid, should we lie to it and provide the maximum grid size possible? Some characters have no size at all, how should we handle those? Or should we set the grid size to what's "sensible" and just cut off characters which are longer than that (through them not being on the grid)? The status line wants characters to be on the right (like how much you are through the file), how do we want to detect that? How should we handle right-to-left scripts?

Alacritty doesn't really handle this either, and I'm not particularly interested in implementing that. I imagine it to be possible with a clear strategy though, and a lot of edge-case thoughts.

**Comment by coders4tomorrow-gr** [comment]
Ok I tried using a strictly monospaced font (Menlo, which appears to be the default font neovide used without ```set guifont```), and for some reason, although characters looking mostly the same (some fonts appear more bold which I'm pretty sure is another issue already in progress), the line height does decrease which I don't believe should happen.  The size of the characters are correct (:h14), but the spacing between lines decreases.  I might follow the temporary fix in issue #481 for now, but I don't think this should be changing from running ```set guifont```.

**Comment by MultisampledNight** [comment]
Fonts are pretty much controlling what they say about their contents, Neovide can't do much there except adding/subtracting _on top_ of those font specifics. Same reason Ubuntu Mono with height 8 looks so much smaller than Hack with height 8.

**Comment by dineshKumar777** [comment]
> Ok I tried using a strictly monospaced font (Menlo, which appears to be the default font neovide used without ```set guifont```), and for some reason, although characters looking mostly the same (some fonts appear more bold which I'm pretty sure is another issue already in progress), the line height does decrease which I don't believe should happen.  The size of the characters are correct (:h14), but the spacing between lines decreases.  I might follow the temporary fix in issue #481 for now, but I don't think this should be changing from running ```set guifont```. 

Just a small clarification. Neovide default is firacode not Menlo.

**Comment by huyz** [comment]
How are we supposed to set the font? For example, I just want to change to a smaller size.
But even if I try:
```vim
set guifont=MesloLGS-NF-Regular:h12
```
everything looks messed up:
![screenshot 2022-11-09T103053Z](https://user-images.githubusercontent.com/128394/200806997-5cd77a02-0a78-4e50-a5a6-e033ee063ef8.png)

**Comment by huyz** [comment]
Thanks.

I also realized that the syntax for `guifont` is different for neovide when it comes to spacing:
```vim
  if exists('g:neovide')
    " Default neovide font:
    "set guifont=Fira\ Mono\ for\ Powerline:h12
    set guifont=MesloLGS\ NF:h12
  else
    " To display devicons
    set guifont=MesloLGS-NF-Regular:h12
    " To make it spaced like in iTerm
    set linespace=1
  endif
```

**Comment by fredizzimo** [comment]
Closing as this was a configuration issue, and we have better error reporting now.
