### ISSUE TITLE
`--wsl` uses terminal nvim and colorscheme rather than GUI nvim

### ISSUE THREAD

**Issue by satvikpendem** [neovide/neovide#1397]
**Describe the bug**
When I use neovide through PowerShell, it correctly uses the GUI based colorscheme, but with the `--wsl` flag, it uses the terminal-based colorscheme. My theme doesn't have a terminal-based colorscheme so it reverts to the default colors.

**To Reproduce**
1. Run neovide in PowerShell and see that it works correctly with a GUI colorscheme.
2. Run neovide with `--wsl` and see that colors revert to terminal colorscheme.

**Expected behavior**
The same colorscheme that's on the GUI version should show up through `--wsl` as well.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Neovide Version: Master branch
 - Neovim Version: 0.7.2

**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**

`.log` file is too long to post here.

**Comment by MultisampledNight** [comment]
As a quick workaround, you can set the `termguicolors` option. Not a true solution though, I'm unable to look any more into it without Windows/WSL.

**Comment by satvikpendem** [comment]
Thanks, I've been setting `termguicolors` and it works fine for now.

**Comment by fredizzimo** [comment]
This is the problem with the colorscheme used. It should define all colors correctly.
