### ISSUE TITLE
Terminal uses fallback colours

### ISSUE THREAD

**Issue by 0atman** [neovide/neovide#1398]
## Describe the bug
The terminal seems to be using ugly, bad contrast fallback colours, maybe 16 or so safe colours? 
Native neovim does not do this, and uses the theme colours correctly.

## To Reproduce
Try using the terminal in neovim, then in neovide.

## Expected behavior
Nice colours in both

## Screenshots
Neovide
![Screenshot from 2022-07-13 10-53-04](https://user-images.githubusercontent.com/114097/178708700-cd01cdfd-5cc1-4f08-ab76-1f9893d610ac.png)

Neovim in gnome-terminal
![Screenshot from 2022-07-13 11-09-20](https://user-images.githubusercontent.com/114097/178709211-23ed2d4d-b761-408c-99f2-43a975d1a7e1.png)

## Desktop (please complete the following information):

Ubuntu 22.04
```
❯ nvim --version
NVIM v0.7.0
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by runner@fv-az316-460
```
Neovide version
```
❯ neovide --version

Neovide 0.9.0
```

## Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:
[neovide_rCURRENT.log](https://github.com/neovide/neovide/files/9101151/neovide_rCURRENT.log)
[neovide_r2022-07-13_11-12-11.log](https://github.com/neovide/neovide/files/9101154/neovide_r2022-07-13_11-12-11.log)

**Comment by 0atman** [comment]
even with this problem neovide has revolutionised my life!

**Comment by 0atman** [comment]
Oh fun! do you know where I should start looking to fix this? 
I'm using https://astronvim.github.io if that makes any difference

**Comment by MultisampledNight** [comment]
Seemingly you need to configure `g:terminal_color_0` through `g:terminal_color_15` inclusively, looking at `:h terminal-config`. A bit difficult to find.

AstroNvim seems to define their colorscheme in a more complicated way than one script: https://github.com/AstroNvim/AstroNvim/tree/main/lua/default_theme. So it might be worth to open an issue on their side about that. Would you mind if I close this issue?

**Comment by 0atman** [comment]
Thank you so much for the pointer, I'll open the issue on their side as you say, see if this is an oversight they can fix. Many thanks!
