### ISSUE TITLE
How do i launch it maximized? (not fullscreen, i want to see window frame, taskbar, etc)

### ISSUE THREAD

**Issue by smolovk** [neovide/neovide#1402]
I'm always frustrated when i launch neovide and i need to maximize it by hand, would be great to launch it already maximized

I tried using fullscreen option, but it doesn`t  work for me, cause i want to see taskbar and window frame with controls.
Also, remember size just does not maximize a window.
i solved it with kde settings for now, but would be cool if i could make neovide do this

**Comment by barklan** [comment]
```
neovide --maximized
```

works for me on KDE on X11 (or with `WINIT_UNIX_BACKEND=x11` on wayland)

**Comment by smolovk** [comment]
> ```
> neovide --maximized
> ```
> 
> works for me on KDE on X11 (or with `WINIT_UNIX_BACKEND=x11` on wayland). It's not documented in the wiki, but present in help output (`neovide --help`)

oh, thanks, it does work, didnt see this in the docs
