### ISSUE TITLE
Install script

### ISSUE THREAD

**Issue by ten3roberts** [neovide/neovide#1403]
**Is your feature request related to a problem? Please describe.**
Installing neovide along with properly installing the desktop files and icons can be challenging to newcomers.

**Describe the solution you'd like**
An install.sh which does 
- `cargo build --release`
- `install ./target/release/neovide ~/.local/bin`
- `install assets/neovide.svg ~/.local/share/icons`
- `install -m644 assets/neovide.desktop ~/.local/share/applications/neovide.desktop` 

It could also be made to use an ENV var to change the location from `~/.local/bin` to `/usr/local` and alike

**Comment by MultisampledNight** [comment]
First of all, thank you for bringing this up!

Then, to be honest, I think this causes an "unclean" installation. Your package manager doesn't know of the installation then, and those newcomers can easily transform this into a half-working installation where the actual `.desktop` files are deleted but the binary still persists. I don't think we need to reinvent the task of a package manager, this script would be just the start of it.

**Comment by ten3roberts** [comment]
I see your point.

**Comment by ten3roberts** [comment]
I see your point in reinventing the wheel, and providing an RPM, DEB, or flatpak is not pain free.

Perhaps cleaning up the install instructions is a better alternative, as the instruction to copy the binary is posed as a suggestion and not as a part of the code block.

![image](https://user-images.githubusercontent.com/25723553/180741874-ada8f13e-69a3-4137-97a2-5f7693b17695.png)

Better yet

We could use `cargo install --path .` which will build in release (which is easily forgotten) and copy the binary into the path, while also allowing the binary to be removed.

Then the desktop file instructions could be mentioned.

Something like:


1. Install necessary dependencies (adjust for your preferred package manager)

    ```sh
    sudo apt install -y curl \
        gnupg ca-certificates git \
        gcc-multilib g++-multilib cmake libssl-dev pkg-config \
        libfreetype6-dev libasound2-dev libexpat1-dev libxcb-composite0-dev \
        libbz2-dev libsndio-dev freeglut3-dev libxmu-dev libxi-dev libfontconfig1-dev
    ```

2. Install Rust

    ```sh
    curl --proto '=https' --tlsv1.2 -sSf "https://sh.rustup.rs" | sh
    ```

3. Clone the repository

    ```sh
    git clone "https://github.com/neovide/neovide"
    ```

4. Build and install

    ```sh
    cargo install --path .
    ```

5. (optional) install the desktop file for Neovide to show up in the app
   launcher


    ```sh
    install -m644 assets/neovide.desktop ~/.local/share/applications/neovide.desktop
    install assets/neovide.svg ~/.local/share/icons
    ```

**Comment by MultisampledNight** [comment]
That sounds like a good idea. It won't be added to the current README though, we're in the process of composing a new wiki combining README + GH wiki, which will then also contain this.

**Comment by MultisampledNight** [comment]
The install script by itself is not planned for now, unless better reasons arise. The `cargo install` method has been added to https://neovide.dev. Thank you!

**Comment by willwillsiii** [comment]
I've written a short per user install script for my own use to deal with the desktop shortcut, fonts, and icons. I figured some users might find it useful, even if it isn't planned for the main repository.

```sh
#!/bin/sh

# This script installs Neovide desktop entry and icons for a user.
# To use, run from the root of the Neovide git repository.

# Install the desktop entry
xdg-desktop-menu install --novendor ./assets/neovide.desktop
xdg-desktop-menu forceupdate

# Install icons
for f in $(find ./assets -type f -name "neovide*.png" ! -name "*dmg*"); do
    dim=$(echo $f | sed 's/.*\([0-9]\+\)x\1.*/\1/g')
    icon_dir="$HOME/.local/share/icons/hicolor/${dim}x${dim}/apps"
    if [ -d $icon_dir ]; then
        xdg-icon-resource install --novendor --size $dim $f neovide
    fi
done
cp ./assets/neovide.svg \
    "$HOME/.local/share/icons/hicolor/scalable/apps/neovide.svg"
xdg-icon-resource forceupdate

# Install fonts
font_dir="$HOME/.local/share/fonts/neovide"
if [ ! -d $font_dir ]; then
    mkdir -p $font_dir
fi
find ./assets/fonts \( -name "*.ttf" -or -name "*.otf" \) -execdir \
    cp "{}" $font_dir \;
fc-cache -f
```
