### ISSUE TITLE
Arm64 - Cargo build [FAILED]

### ISSUE THREAD

**Issue by Joarell** [neovide/neovide#1404]
Hi there!
First of all I would like to thank you guys for this amazing project. You are great!

**Describe the bug**
So, I have been trying to build neovide in my Arm Arch OS. However, I`ve got the error for the ` glutin `, dependency.

**To Reproduce**
1. cargo build --release

**Expected behavior**
Build the binary.

**Screenshots**
![2022-07-18_18-59](https://user-images.githubusercontent.com/42722369/179584659-069e628d-32b2-465d-a809-a5704b0b9324.png)

**Desktop (please complete the following information):**
![enviroment](https://user-images.githubusercontent.com/42722369/179588179-18d046ca-9f1f-4013-90c4-178b30718561.png)

Have a great day and be fine!

**Comment by Joarell** [comment]
Hi!
Dear @MultisampledNight,
I hope you are doing great.
Yesterday I had my last try to install Neovide in Arm architecture. Rsrsrsrsrsr...

I've edited the ` Cargo.toml `, get rid of all git hub links to the dependencies versions number. When I did it ` cargo ` could compile almost everything. But the, the problem is the ` skia ` dependency has no Arm binary to available to compile. That part is the last one when ` cargo ` is finishing the compile process.
So, due to that I will close this issue tomorrow if want to write your last message until there. So, it's not a fault of yours this library lack for Arm binary.
I'm sad but... Maybe in a near future it comes alive.
Cheers!
Be fine my friend!

**Comment by MultisampledNight** [comment]
Hi there, @Joarell!

I doubt the version pinned dependencies would've worked anyways, we use really much "custom" stuff in the GitHub dependencies which Neovide relies on. So the build would have failed anyways, just... later. The skia issue seems not impossible to fix, but would probably require much extra-effort anyways (in terms of building from source).

Either way, sorry to hear that. Not sure if this will be revisited in near future, but nothing's everlasting.

**Comment by Joarell** [comment]
You are correct!
I have faith too! Rsrsrsrsrsrsr...

It was a pleasure talking to you dear @MultisampledNight.
Finally I would like to share the way I use Nevide with [Lunarvim](https://www.lunarvim.org/#opinionated). Everything I need is in this fantastic IDE. I just make a TCP connection and everything works beautifully well with those two environments.

The installation requires some dependencies that are downloaded on the installation. Basically ` Node, Pip and Rust `.
That's my last message sharing this "tip", to you.
Have good day/night and be fine, my friend!
Thank you for all your assistance!
