### ISSUE TITLE
How to disable visual effect of cursor?

### ISSUE THREAD

**Issue by Rid1-fz-06** [neovide/neovide#1405]
It may sound wired, but I actually don't like those animations of cursor. How can I make cursor behave like actual neovim?

**Comment by MultisampledNight** [comment]
Pretty good question, I'll touch on the wiki to make this clearer.

You can disable the "lag-behind" part of the cursor by setting `g:neovide_cursor_animation_length` to `0`. Similarly the extra particles VFX can be disabled by either removing your `g:neovide_cursor_vfx_mode` setting in your `init.vim`/`init.lua`, or setting it to an empty string (`""`).

**Comment by MultisampledNight** [comment]
Just update the wiki.

**Comment by philippludwig** [comment]
"Unknown option: `g:neovide_cursor_animation_length`"

Also, where is this wiki located?

**Comment by philippludwig** [comment]
Thank you, that worked as expected. The Configuration page is also very helpful.
