### ISSUE TITLE
unable to start neovide

### ISSUE THREAD

**Issue by Felix-Kyun** [neovide/neovide#1409]
Unable to start neovide after installing.

when i try to open it, it just creates window for a second and then disappears.

 - OS: Arch Linux
 - Neovide Version 0.9.0
 - Neovim Version 0.7.2

[full log](https://github.com/neovide/neovide/files/9153939/neovide_rCURRENT.log)
uploaded the file as it was too long

**Comment by SergioRibera** [comment]
could you try upgrading? please

**Comment by refaelsh** [comment]
I have the same issue.

**Comment by Kethku** [comment]
Please try again with current main and --log and reopen if issues persist. We have different error reporting now that may give more information

**Comment by refaelsh** [comment]
For me, it works now. I have done anything special. I am guessing some update solved this issue.
