### ISSUE TITLE
Unable to start neovide after installation

### ISSUE THREAD

**Issue by refaelsh** [neovide/neovide#1410]
Unable to start neovide after installing.

When i try to open it, it just creates window for a second and then disappears.

    OS: NixOS
    Neovide Version 0.8.0
    Neovim Version 0.7.0

The log file contains only one line:
```
TRACE [neovide] Neovide version: 0.8.0
```

**Comment by MultisampledNight** [comment]
What graphics driver do you run on which GPU?

**Comment by refaelsh** [comment]
> What graphics driver do you run on which GPU?

Good question. I should have mentioned that it is NixOS running in a Virtual Machine.

**Comment by refaelsh** [comment]
For me, it works now. I have not done anything special. I am guessing some update solved this issue.
