### ISSUE TITLE
Proper support for unix domain socket based remote connections

### ISSUE THREAD

**Issue by koraa** [neovide/neovide#1412]
Neovide currently supports connecting to remote vim session via TCP; this is fantastic and enables remote connections to networked hosts. For many use cases though this is not the appropriate thing to use as it does not support encryption and introduces security problems; it is possible to limit neovim to listening on the localhost network, but then pretty much any process on the computer can connect to the neovim server.

Neovim supports another way to listen for incoming connections; by using a command like the following I can start a listen server that uses a unix domain socket instead of a tcp socket:

```bash
$ nvim --headless --listen "$XDG_RUNTIME_DIR"/neovide &
$ ls "$XDG_RUNTIME_DIR"/neovide
/run/user/1000/neovide=
file "$XDG_RUNTIME_DIR"/neovide
/run/user/1000/neovide: socket
```

This pattern is used by many applications (see below) because it provides better performance as the protocol overhead from using the tcp protocol can be avoided  and normal file-based permissions apply to unix sockets.

When using neovide on another host, the `ssh [HOST] -R remote_socket:local_socket` or a socat-based equivalent can be used to establish the connection to the remote socket with cryptographic protection.

When using neovide in virtual machines (as in my use case), virtio modules to forward the unix socket with low overhead are available.

For all these reasons I suggest that neovide be augmented with the ability to connect to unix sockets.

```
/run/user/1000/neovide
/run/user/1000/nvim.1059308.0
/run/user/1000/nvim.1003895.0
/run/user/1000/Alacritty-wayland-1-1003740.sock
/run/user/1000/Alacritty-wayland-1-900356.sock
/run/user/1000/Alacritty-wayland-1-621565.sock
/run/user/1000/Alacritty-wayland-1-557451.sock
/run/user/1000/wl-gammactl.socket
/run/user/1000/Alacritty-wayland-1-255605.sock
/run/user/1000/sway-ipc.1000.255584.sock
/run/user/1000/wayland-1
/run/user/1000/nvim.14266.0
/run/user/1000/at-spi/bus_0
/run/user/1000/sway-ipc.1000.2521.sock
/run/user/1000/ssh-agent.socket
/run/user/1000/pipewire-0
/run/user/1000/pulse/native
/run/user/1000/p11-kit/pkcs11
/run/user/1000/keyring/pkcs11
/run/user/1000/keyring/control
/run/user/1000/gcr/ssh
/run/user/1000/gnupg/S.gpg-agent
/run/user/1000/gnupg/S.gpg-agent.ssh
/run/user/1000/gnupg/S.gpg-agent.extra
/run/user/1000/gnupg/S.gpg-agent.browser
/run/user/1000/gnupg/S.dirmngr
/run/user/1000/bus
/run/user/1000/systemd/private
/run/user/1000/systemd/notify
/run/user/1000/systemd/inaccessible/sock
```

**Comment by khjorth** [comment]
This would be very useful, and I think it's actually quite simple to add. I'll start working on a PR.
