### ISSUE TITLE
glepnir/dashboard-nvim not centred automatically when neovide is maximised

### ISSUE THREAD

**Issue by sgoudham** [neovide/neovide#1414]
Hi again, I found another issue related to dashboard-nvim! Hopefully not as mind-bending as the previous one with the highlights :D

**Describe the bug**
When using the [glepnir/dashboard-nvim](https://github.com/glepnir/dashboard-nvim) plugin, the dashboard is not centred in the middle of the screen when starting up with Neovide maximised. Whereas, in the terminal or when neovide is windowed, it seems to be centred correctly. This leads me to believe that it's an issue on Neovide's side. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Use provided `init.lua` config
2. Start up Neovide maximised
3. Observe the dashboard being offset from the centre

Here is the minimum reproducible config:
```lua
local fn = vim.fn

-- Automatically install Packer
local install_path = fn.stdpath "data" .. "/site/pack/packer/start/packer.nvim"
if fn.empty(fn.glob(install_path)) > 0 then
    PACKER_BOOTSTRAP = fn.system {
        "git",
        "clone",
        "--depth",
        "1",
        "https://github.com/wbthomason/packer.nvim",
        install_path,
    }
    print "Installing Packer. Close and reopen Neovim..."
    vim.cmd([[packadd packer.nvim]])
end

-- Use a protected call so we don't error out on first use
local status_ok, packer = pcall(require, "packer")
if not status_ok then
    return
end

packer.startup(function(use)
    -- Packer can manage itself
    use 'wbthomason/packer.nvim'

    use { "glepnir/dashboard-nvim" }

    -- Automatically set up your configuration after cloning packer.nvim
    -- Put this at the end after all plugins
    if PACKER_BOOTSTRAP then
        require("packer").sync()
    end
end)

require("dashboard")
```

**Expected behaviour**
The dashboard should be centred as shown below in the screenshots.

**Screenshots**
The expected behaviour is `Windows Terminal`.  Also please ignore the loaded plugins, packer is weird 😅 and they shouldn't have an effect on the issue at hand.

`Windows Terminal (Powershell)`
![image](https://user-images.githubusercontent.com/58985301/180325537-0a19dee1-7f6a-4324-8857-e6905ae430b4.png)

`Neovide Maximised`
![image](https://user-images.githubusercontent.com/58985301/180325527-67a62621-e289-4f63-8914-6f2fea5aae47.png)

`Neovide Windowed`
![image](https://user-images.githubusercontent.com/58985301/180326393-6da9e023-02e0-469b-8403-d67976c1ecf0.png)

**Desktop (please complete the following information):**
 - **OS:** Windows 11
 - **Neovide Version:** 0.9.0
 - **Neovim Version:** 0.7.2

**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**
[neovide_rCURRENT.log](https://github.com/neovide/neovide/files/9163139/neovide_rCURRENT.log)

**Comment by Kethku** [comment]
I think this may be fixed in current main. Please reopen if issues persist
