### ISSUE TITLE
Particles are clipped to Neovim grid and not whole window

### ISSUE THREAD

**Issue by MultisampledNight** [neovide/neovide#1419]
**Describe the bug**
Particles, which are more of a visual nice thing than bound to Neovim, are only visible in the Neovim area and not in the part below the commandline which is used for padding.

**To Reproduce**
1. `:let g:neovide_cursor_vfx_mode="pixiedust"`
2. `:let g:neovide_cursor_vfx_particle_lifetime=20`
3. `:let g:neovide_cursor_vfx_particle_density=400` (not necessary, only to make it more visible)

**Expected behavior**
To have particles appear in the whole window.

**Screenshots**
![unknown](https://user-images.githubusercontent.com/80128916/180659504-bc0be444-c976-4689-9e84-d65d1a169237.png)

**Desktop (please complete the following information):**
 - OS: Irrelevant, though Arch Linux
 - Neovide Version: 130e15439a3a36d3e74756ccae666b3656a10f9e
 - Neovim Version: v0.7.2

**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**
Irrelevant

**Additional context**
Probably particles are drawn in the grid renderer and could need an extra layer, which could be expanded later on for GUI extensions.

Just leaving this here in order to maybe tackle it later, or not. idk

**Comment by Kethku** [comment]
I believe this is fixed with the new render rewrite
