### ISSUE TITLE
Attach to an already running remote nvim --headless

### ISSUE THREAD

**Issue by egolep** [neovide/neovide#1423]
I don't know if I'm missing something in the README, Wiki or an obvious thing in general, but I'm trying to attach to an aready running remote nvim instance with a local neovide installation but I can't find a way to do so.
If I follow the instructions on the README, I'm able to spawn a new instance via the `ssh` command and then attach to that, but I find no way to attach to an already running instance on my remote server.
Am I missing something obvious? Or there is no (trivial) way to do so?

**Comment by Ion-manden** [comment]
@egolep 
I assume you are running this
`ssh -L 6666:localhost:6666 ip.of.other.machine nvim --headless --listen localhost:6666`

First part is the part the docs talk about where you port forward to your remote machine with ssh, so you just need to run the `ssh -L 6666:localhost:6666 ip.of.other.machine` part. this will do the port forwarding.

Hope this helps.

**Comment by egolep** [comment]
So if I simply run  `ssh -L 6666:localhost:6666 ip.of.other.machine` and then launch `neovide` it should work, connecting to the already running `nvim` instance? If this is the case, unluckily it doesn't, and I also tried to use the `--log` parameter but there is nothing in the log file.
Could it be a problem related to the fact that I cannot directly connect to the remote machine but I have to use a proxy ssh connection from another server?

**Comment by Ion-manden** [comment]
@egolep 
Just to make sure i understand.

You ssh into the server that will be running neovim and start a process with `nvim --headless --listen localhost:6666` in a tmux instance or some other way to make it run in the background.

You then create the port forward from your local machine with `ssh -L 6666:localhost:6666 ip.of.other.machine` ip.of.other.machine being the ip of the maching running neovim headless.

And then in another terminal run `/path/to/neovide --remote-tcp=localhost:6666` likely just `neovide --remote-tcp=localhost:6666`, but neovide then not being able to talk with the remote headless instance of neovim?

If this matches your approach and is still not working ill give it a go in a couple hours to see if i can replicate your issue.

**Comment by egolep** [comment]
I'll write the entire situation in order to be more clear:
- I have a workstation in my office which is my main development machine with dedicated hardware for computing intensive tasks
- On this machine, I run `nvim --headless --listen localhost:6666` and then start a `neovide` instance connected to this instance of `neovim` with `neovide --remote-tcp=localhost:6666`. Then, I start my development which leads to long running procedure with continuous output (i.e. a machine learning algorithm printing the state of the training)
- Then I go home but I need to check the progress of the same task and I would like to be able to connect to the same instance of `neovim` on the workstation from my laptop. Then, on the laptop, I run `ssh -L 6666:localhost:6666 ip.of.the.workstation` and then `neovide --remote-tcp=localhost:6666` but I only get a black window with no interaction


is it possible to connect to the remote instance on the workstation using only `neovide`? Or I need to use something like `gnu-screen` or `tmux`?


(sorry for the delay in this reply, it has been a very tough work day)

**Comment by feature-not-a-bug** [comment]
The ssh tunnel should be transparent for both nvim and neovide. Can you verify that the nvim session is still running on the remote computer?

That is, if you close the neovide window the remote nvim session will still be alive and able to accept new connections, but if you exit with `:q` that command will be sent to nvim and it will close the headless instance and not accept further connections until it's restarted.

**Comment by egolep** [comment]
Yeah, the process is running. I also tried to kill it, re-launch it and connect only with a `neovide` instance on my laptop, without connecting on the workstation before. I'm still stuck with the same problem: I get a black window or a fully transparent one (it's worth saying that I also killed my compositor in order to avoid problem with it).
As I said in a previous post, before explaining the full situation: could this be some strange behavior due to the fact that I have to use a front-end server as a proxy in order to connect to my "personal" workstation? (This situation is unavoidable because it's a security measure explicitly written in my institute IT policy).


PS: thank you all for all the effort and time you already dedicated to me!

**Comment by feature-not-a-bug** [comment]
Sorry, I missed the part about the proxy server. Just to confirm, do you see something like this with no ability to scroll or change modes?
![neovide-connecting](https://user-images.githubusercontent.com/19642535/181235234-f917089f-d21f-4754-a2c1-3222c3e16b10.png)

The solution here will depend on the exact setup that your work network has implemented, but the first thing I'd try is invoking ssh with the ProxyJump option.

See `Port Forwarding Through One or More Intermediate Hosts` at https://en.m.wikibooks.org/wiki/OpenSSH/Cookbook/Proxies_and_Jump_Hosts

**Comment by egolep** [comment]
I wasn't aware of the "new" `ProxyJump` and the advantages against `ProxyCommand` for ssh. Switching to `ProxyJump` solved the problem. 
Thanks to all for the help and for your time! It turned out that the problem was my silliness
