### ISSUE TITLE
Neovide Available on crates.io so that installing from source is as easy as running `cargo install neovide`

### ISSUE THREAD

**Issue by troglodytto** [neovide/neovide#1427]
**Is your feature request related to a problem? Please describe.**
When installing Neovide on any Linux Distribution, other than Arch or Ubuntu (Even on Ubuntu if someone prefers not to use snap), Then they have to build from source, which involves cloning the repo, building and then moving the binary to somewhere in path

**Describe the solution you'd like**
The source can be made available to crates.io, which will allow the user to run

```
cargo install neovide
```

to do the above steps all in one go

**Comment by ipetrovbg** [comment]
Updating crates.io index
```
error: could not find `neovide` in registry `crates-io` with version `*`
```
I've just tried to install it and I got this error. I'm not sure if it matters but I'm on MacOS with M1 chip.

**Comment by shaunsingh** [comment]
As you've noticed neovide isn't on crates.io (yet), as we use a fork of glutin thats hosted on git. Any crates uploaded to crates.io can only have other crates in their repository, so we can only upload a neovide crate if we move to upstream winit 

(closing in favor of https://github.com/neovide/neovide/issues/839)
