### ISSUE TITLE
Neovide freezes when a lua error occurs and I try to close it first.

### ISSUE THREAD

**Issue by B4mbus** [neovide/neovide#1429]
**Describe the bug**
If config is incorrect and there's any lua error when neovide starts it displays the error, but if I try to close it with the X button on the title bar and then click enter in the editor, it instantly freezes and when I try to click on it or close it fades to white and the title bar says `Not responding` (I'm on windows).

**To Reproduce**
Create any malformed configuration file and open up neovim, try to close it with the X button and click enter to get rid of the error information, it will freeze.

**Expected behavior**
Neovide not freezing or crashing with malformed configuration, rather than displaying the issue.

**Screenshots**
![ooga2](https://user-images.githubusercontent.com/75364377/181754353-932529c9-839d-4dc8-a11e-bfe5efcffc1d.gif)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro N
 - Neovide Version 0.9.0
 - Neovim Version 0.7.2

**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**
https://gist.github.com/B4mbus/dda9f380fb158b30cf1b339e21c93f1b

**Additional context**
-

**Comment by MultisampledNight** [comment]
Thank you for reporting! I can't seem to reproduce the issue on Linux though, maybe this is something Windows-specific.

**Comment by Salakksson** [comment]
i got this issue on wayland arch when getting an unknown function error for vundle, installed using yay from extra/neovide

**Comment by charstale** [comment]
this issue occurs again after i update to 0.12.but 0.11 works fine
`TRACE [neovide] Neovide version: 0.12.0
DEBUG [neovide::settings::window_size] Loaded window settings: Windowed { position: PhysicalPosition { x: 94, y: 29 }, pixel_size: Some(PhysicalSize { width: 1005, height: 826 }), grid_size: Some(Dimensions { width: 125, height: 51 }) }
DEBUG [neovide::bridge::command] Starting neovim with: Command { std: "D:\\Neovim\\bin\\nvim.exe" "--embed" "-p", kill_on_drop: false }
INFO [neovide::bridge::setup] Neovide registered to nvim with channel id 1
TRACE [neovide::settings] Initial value load failed for cursor_animate_command_line: Error processing request: 1 - 'Key not found: neovide_cursor_animate_command_line')
TRACE [neovide::bridge::handler] Neovim notification: "setting_changed"
TRACE [neovide::settings] Initial value load failed for floating_blur: Error processing request: 1 - 'Key not found: neovide_floating_blur')
TRACE [neovide::bridge::handler] Neovim notification: "setting_changed"
TRACE [neovide::settings] Initial value load failed for hide_mouse_when_typing: Error processing request: 1 - 'Key not found: neovide_hide_mouse_when_typing')
TRACE [neovide::bridge::handler] Neovim notification: "setting_changed"
TRACE [neovide::settings] Initial value load failed for remember_window_size: Error processing request: 1 - 'Key not found: neovide_remember_window_size')
TRACE [neovide::bridge::handler] Neovim notification: "setting_changed"
TRACE [neovide::settings] Initial value load failed for floating_blur_amount_x: Error processing request: 1 - 'Key not found: neovide_floating_blur_amount_x')
TRACE [neovide::bridge::handler] Neovim notification: "setting_changed"
TRACE [neovide::settings] Initial value load failed for light_angle_degrees: Error processing request: 1 - 'Key not found: neovide_light_angle_degrees')
TRACE [neovide::bridge::handler] Neovim notification: "setting_changed"
TRACE [neovide::settings] Initial value load failed for cursor_animation_length: Error processing request: 1 - 'Key not found: neovide_cursor_animation_length')
TRACE [neovide::bridge::handler] Neovim notification: "setting_changed"
TRACE [neovide::settings] Initial value load failed for refresh_rate: Error processing request: 1 - 'Key not found: neovide_refresh_rate')
TRACE [neovide::bridge::handler] Neovim notification: "setting_changed"
TRACE [neovide::settings] Initial value load failed for idle: Error processing request: 1 - 'Key not found: neovide_idle')
TRACE [neovide::bridge::handler] Neovim notification: "setting_changed"
TRACE [neovide::settings] Initial value load failed for cursor_vfx_particle_density: Error processing request: 1 - 'Key not found: neovide_cursor_vfx_particle_density')
TRACE [neovide::bridge::handler] Neovim notification: "setting_changed"
TRACE [neovide::settings] Initial value load failed for cursor_vfx_particle_phase: Error processing request: 1 - 'Key not found: neovide_cursor_vfx_particle_phase')
TRACE [neovide::bridge::handler] Neovim notification: "setting_changed"
TRACE [neovide::settings] Initial value load failed for cursor_antialiasing: Error processing request: 1 - 'Key not found: neovide_cursor_antialiasing')
TRACE [neovide::bridge::handler] Neovim notification: "setting_changed"
TRACE [neovide::settings] Initial value load failed for input_macos_alt_is_meta: Error processing request: 1 - 'Key not found: neovide_input_macos_alt_is_meta')
TRACE [neovide::bridge::handler] Neovim notification: "setting_changed"
TRACE [neovide::settings] Initial value load failed for unlink_border_highlights: Error processing request: 1 - 'Key not found: neovide_unlink_border_highlights')
TRACE [neovide::bridge::handler] Neovim notification: "setting_changed"
TRACE [neovide::settings] Initial value load failed for position_animation_length: Error processing request: 1 - 'Key not found: neovide_position_animation_length')
TRACE [neovide::bridge::handler] Neovim notification: "setting_changed"
TRACE [neovide::settings] Initial value load failed for confirm_quit: Error processing request: 1 - 'Key not found: neovide_confirm_quit')
TRACE [neovide::bridge::handler] Neovim notification: "setting_changed"
TRACE [neovide::settings] Initial value load failed for floating_blur_amount_y: Error processing request: 1 - 'Key not found: neovide_floating_blur_amount_y')
TRACE [neovide::bridge::handler] Neovim notification: "setting_changed"
TRACE [neovide::settings] Initial value load failed for remember_window_position: Error processing request: 1 - 'Key not found: neovide_remember_window_position')
TRACE [neovide::bridge::handler] Neovim notification: "setting_changed"
TRACE [neovide::settings] Initial value load failed for padding_top: Error processing request: 1 - 'Key not found: neovide_padding_top')`



OS: Windows 10 Pro 
Neovim Versio:0.9.5

**Comment by MultisampledNight** [comment]
@charstale Hi! Could you try [building from main](https://neovide.dev/installation.html#windows-source)?

**Comment by fredizzimo** [comment]
I'm pretty sure that the new regression was fixed by
* https://github.com/neovide/neovide/pull/2241
