### ISSUE TITLE
Neovide doesn't show AstroNvim icons correctly

### ISSUE THREAD

**Issue by St0wy** [neovide/neovide#1430]
**Describe the bug**

When I start Neovide with AtroNvim, the icons in the menu don't show up properly.

**To Reproduce**

1. Install AstroNvim
2. Install Neovide
3. Start Neovide

**Expected behavior**

Have the icons show up properly, just like when I start Neovim in the new Windows Terminal.

**Screenshots**

In the Windows Terminal : 

![image](https://user-images.githubusercontent.com/35960548/181788905-6604cdf0-d7cf-4b7f-be82-0de35aa61109.png)

In Neovide : 

![image](https://user-images.githubusercontent.com/35960548/181788948-e9073470-5ed0-4bc3-a373-0fad28dd693b.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Neovide Version : 0.9.0
 - Neovim Version : 0.7.2

**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**
Was too long, so here is a part of it : 

TRACE [neovide::channel_utils] alloc::vec::Vec<neovide::renderer::DrawCommand> [UpdateCursor(Cursor { grid_position: (0, 29), parent_window_id: 1, shape: Block, cell_percentage: Some(0.0), blinkwait: Some(0), blinkon: Some(0), blinkoff: Some(0), style: None, enabled: false, double_width: false, grid_cell: (":", Some(Style { colors: Colors { foreground: None, background: None, special: None }, reverse: false, italic: false, bold: false, strikethrough: false, underline: false, undercurl: false, blend: 0 })) })]
TRACE [neovide::redraw_scheduler] Next frame queued
TRACE [neovide::redraw_scheduler] Next frame queued
TRACE [neovide::window] Settings geometry PhysicalSize { width: 100, height: 50 }
TRACE [neovide::window] Inner size: PhysicalSize { width: 1920, height: 986 }
TRACE [neovide::window] Inner size scaled: PhysicalSize { width: 1920, height: 986 }
TRACE [neovide::redraw_scheduler] Next frame queued
TRACE [neovide::window] Settings geometry PhysicalSize { width: 100, height: 50 }
TRACE [neovide::window] Inner size: PhysicalSize { width: 1920, height: 986 }
TRACE [neovide::window] Inner size scaled: PhysicalSize { width: 1920, height: 986 }
TRACE [neovide::settings] Initial value load failed for cursor_antialiasing: Error processing request: 1 - 'Key not found: neovide_cursor_antialiasing')
TRACE [neovide::bridge::handler] Neovim notification: "neovide.quit"
INFO [neovide::running_tracker] Quit with code 0: Quit from neovim
TRACE [neovide::settings] Initial value load failed for floating_blur_amount_x: Error sending request 'nvim_get_var'
TRACE [neovide::settings] Initial value load failed for cursor_animate_in_insert_mode: Error sending request 'nvim_get_var'
TRACE [neovide::settings] Initial value load failed for cursor_animate_command_line: Error sending request 'nvim_get_var'
TRACE [neovide::settings] Initial value load failed for cursor_vfx_particle_speed: Error sending request 'nvim_get_var'
TRACE [neovide::settings] Initial value load failed for no_idle: Error sending request 'nvim_get_var'
TRACE [neovide::settings] Initial value load failed for input_use_logo: Error sending request 'nvim_get_var'
TRACE [neovide::settings] Initial value load failed for cursor_animation_length: Error sending request 'nvim_get_var'
TRACE [neovide::settings] Initial value load failed for cursor_vfx_particle_density: Error sending request 'nvim_get_var'
TRACE [neovide::settings] Initial value load failed for profiler: Error sending request 'nvim_get_var'
TRACE [neovide::settings] Initial value load failed for cursor_unfocused_outline_width: Error sending request 'nvim_get_var'
TRACE [neovide::settings] Initial value load failed for cursor_vfx_mode: Error sending request 'nvim_get_var'
ERROR [neovide::error_handling] Could not setup setting notifier for touch_drag_timeout: Error sending request 'nvim_command'
DEBUG [neovide::settings::window_geometry] Saved Window Settings: {"window":"Maximized"}

**Comment by dineshKumar777** [comment]
are you using the same font as in first screenshot. looks different. use the same font and try again. 
or you can use fallback font with glyph support. 
Refer #1202

**Comment by St0wy** [comment]
Ah yes, I though I had setup my terminal to use Cascadia code but it was Hack NF instead. With this glyphs look good ! There are still small black lines between the characters of the big logo, but that's not really an issue. Thanks a lot !

![image](https://user-images.githubusercontent.com/35960548/181804256-6991b1ac-d389-4697-a577-186277847822.png)

**Comment by dineshKumar777** [comment]
"There are still small black lines between the characters of the big logo"
              These are known issues. There are few font related issues which might cause this.

**Comment by Fapuu** [comment]
@St0wy I have the same issue, but I cannot resolve it even with the answers in this issue :c

Just to be clear I'm a noob in neovim and I really want to give it a try to make it my main IDE.

My current workspace is a laptop with Windows 11 installed and I'm using WSL as my developing system. I followed the instalation guide and installed everyting that is needed. To use neovim I'm also using Neovide with the commend `neovide --wsl`. So the setup looks like this.

WSL:

    Neovim
    Astrovim (with the necessary dependencies)

Windows 11:

    Neovide

Right now everything works fine but I can't see the icons which is very annoying. Can you help?

![image](https://user-images.githubusercontent.com/39151576/183739898-9578ddbe-7462-4248-9431-9f4bfe7ee9a1.png)

**Comment by St0wy** [comment]
@Fapuu I don't know where it's located on WSL, but you need to change the font that's used in your neovide config. I did it in my `init.lua`.

```lua
-- init.lua
vim.opt.guifont = { "Hack NF", "h12" }

local impatient_ok, impatient = pcall(require, "imaptient")
-- Other nvim stuff below...
```

Hack NF is the font I choose, but you may use any nerd font. Make sure it's installed on your system too.

**Comment by Fapuu** [comment]
@St0wy Thank you a lot it work! :3
