### ISSUE TITLE
Set startup directory for lunarvim

### ISSUE THREAD

**Issue by xbladesub** [neovide/neovide#1433]
I'm using lunarvim and executable to run neovide:

```sh
#!/bin/sh
# ~/.local/bin/lvim-gui
export LUNARVIM_RUNTIME_DIR="${LUNARVIM_RUNTIME_DIR:-"$HOME/.local/share/lunarvim"}"
export LUNARVIM_CONFIG_DIR="${LUNARVIM_CONFIG_DIR:-"$HOME/.config/lvim"}"
export LUNARVIM_CACHE_DIR="${LUNARVIM_CACHE_DIR:-"$HOME/.cache/lvim"}"

exec /Applications/Neovide.app/Contents/MacOS/neovide --frame=none --multigrid -- -u "$LUNARVIM_RUNTIME_DIR/lvim/init.lua" "$@"
```

Is there any way to set startup directory (home directory, not just "/")? If I add "~/" lunarvim starts with expanded nvimtree and not with dashboard.

Not sure that something in plugins settings.

**Comment by xbladesub** [comment]
Just had to add "cd $HOME" before "exec"

**Comment by amojury** [comment]
I use LunarVim on remote.Does the script work with --remote-tcp?
