### ISSUE TITLE
neovide fails on crostini with Wayland

### ISSUE THREAD

**Issue by ellbur** [neovide/neovide#1436]
I am using crostini on an intel chromebook.

I downloaded the release from https://github.com/neovide/neovide/releases/download/0.9.0/neovide.tar.gz, extracted, and ran with `--nofork`. This results in:

    thread 'main' panicked at 'Could not get window position: NotSupportedError', src/window/mod.rs:361:14

Crostini has, unfortunately, incomplete Wayland support. Applications that expert all Wayland features to be implemented won't run for this reason.

neovide will run on crostini if made to use X rather than Wayland with:

    WAYLAND_DISPLAY='' neovide

**Comment by MultisampledNight** [comment]
Thank you for reporting! Hm, looking around in the code here:

https://github.com/neovide/neovide/blob/80b9f2edd7863bd58923542faf79d23bc462b96f/src/window/mod.rs#L352-L373

I'm wondering how incomplete crostini's Wayland support is if it allows things it actually doesn't need to. The check fails already at `if let Some(...` on sway. But that's easily "fixable".

**Comment by MultisampledNight** [comment]
@ellbur Could you please try the fix in #1437? I believe that should cut it, or at least show another point of failure.

**Comment by ellbur** [comment]
Yes, no issues so far!

**Comment by MultisampledNight** [comment]
Alright then, thank you!
