### ISSUE TITLE
No input when swapping between inactive/active window

### ISSUE THREAD

**Issue by alphastrata** [neovide/neovide#1438]
**Describe the bug**
Using Pop shell (and PopOS' amazing window manager)
When using hotkeys to change between focused windows, Neovide is unresponsive.
When I use the mouse to select the active window, everything works as expected, or indeed ANY mouse activity OVER the neovide window will make things behave as expected.

**To Reproduce**
Assuming you have pop_os! installed, activate the window manager (it's installed by default) with `super+y` 
Move between some active and inactive windows, if one of them is Neovide attempting to do *anything* with the keyboard will not work.
By default the window toggles are `super + arrowkeys` so if you jet around left to write trying to type into say, a terminal then, jump across to Neovide you'll see the issue immediately.

Unsure if this behavior exists on other window managers, or if there's a setting somewhere (couldn't find anything in existing docs/issues).

Seems to be driven by whatever is looking to 'capture' the mouse-cursor's position on screen.

**Expected behavior**
Moving between say, Firefox and Neovide shouldn't require me reaching for the mouse to click within the Neovide window.

**Screenshots**
Made a quick video https://youtu.be/pIN_KI-tfy0

**Desktop (please complete the following information):**
Pop!_OS 21.10 x86_64
Neovide 0.9.0

**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**
```
TRACE [neovide] Neovide version: 0.9.0
```

**Comment by alphastrata** [comment]
After messing with some settings this can be fixed with the following...

![image](https://user-images.githubusercontent.com/25101888/182025425-8b43caef-e3a7-4690-9f5a-c36a146099af.png)

**Comment by melkster** [comment]
I have the same issue on Manjaro GNOME. Your workaround works for me but perhaps the issue shouldn't closed yet since this is likely a bug that needs to be resolved on Neovide's side?

**Comment by MultisampledNight** [comment]
You're right there. Though there's not much we can actually do, it's yet another issue which might be very well fixed by upstream winit.

**Comment by fredizzimo** [comment]
We have now merged the latest winit with https://github.com/neovide/neovide/pull/1789. Can you test again with the latest master?

**Comment by fredizzimo** [comment]
Since there now new reports after the 0.11.0 release, I will clsoe this
