### ISSUE TITLE
Runnig neovide using wsl results in a frozen black window.

### ISSUE THREAD

**Issue by ehllie** [neovide/neovide#1442]
**Describe the bug**
Invoking `neovide --wsl` command results in a black window that accepts no inputs appearing. That window can only be closed with the help of task manager as it ignores normal window close.

**To Reproduce**
1. Run `neovide --wsl`

I'll try to provide minimal wsl configuration to troubleshoot this if a simple solution doesn't get found, as it is somewhat of a tedious task.

**Expected behavior**
Invoking `neovide --wsl` brings up the neovide window running my neovim configuration from inside wsl.

**Screen recording**

[Screen recording](https://user-images.githubusercontent.com/20847625/182329500-2d0c92f1-8157-48c2-b612-8f6c9125cc25.mp4)

**Desktop (please complete the following information):**
 - OS: Windows 11 Pro 21H2
 - Neovide Version 0.9.0
 - Neovim Version v0.7.2

[Log file](https://github.com/neovide/neovide/files/9240377/neovide_rCURRENT.log)

**Additional context**
I have installed neovide from source using cargo, however the same behaviour occurs when running the binary from scoop or the release page.
WSL setup:
```
Windows Subsystem for Linux Distributions:
fedoraremix (Default)
docker-desktop-data
docker-desktop
Ubuntu
```
[My neovim config](https://github.com/ehllie/my-dotfiles/tree/main/.config/nvim)
It works fine when I run it on arch(most recent build from the community repository at the time of writing) linux directly on my home pc.

**Comment by LukeDRussell** [comment]
I can reproduce, see https://github.com/neovide/neovide/issues/1296#issuecomment-1356017632

**Comment by fredizzimo** [comment]
I'm pretty sure this is fixed
