### ISSUE TITLE
Change type of cursor when resizing windows

### ISSUE THREAD

**Issue by fuzzypixelz** [neovide/neovide#1443]
**Is your feature request related to a problem? Please describe.**
When resizing windows with the mouse, it's generally awkward to figure out where exactly the cursor should be put, as there are no visual cues. This is why many UIs try to respond to your mouse movements, usually by highlighting the target, or in this case, switching the cursor type.

**Describe the solution you'd like**
Have neovide switch the cursor type to "resize column" or "resize line" when my mouse is in the right location on a window border.

**Describe alternatives you've considered**
None. Perhaps using themes that make the window borders into blocks. But that's not much better, as themes tend to vary in precision.

**Additional context**
Does this contradict Neovide's philosophy? I don't think do. This is a GUI afterall, and it has the opportunity to leverage precisely these kinds of things, which a terminal emulator can't, by having direct access to the toolkit. I don't think this compromises Neovim's behaviour, as it's entirely a visual cue. Neovim and/or Neovide can answer the question: "Is my cursor in the right position for a resize?", but the user isn't given this piece of information, I would argue this shouldn't be the case.

I'm entirely unfamiliar with Neovide's internals. In my mind this could either be a one-liner or an impossibility. But I'm very much interested in going at this myself; all I ask is some pointers (get it?)

**Comment by fredizzimo** [comment]
This is actually planned, but we need some features from Neovim first.

But I'm leaving this closed, as we have a more general issue that covers it:
* https://github.com/neovide/neovide/issues/2090
