### ISSUE TITLE
Support `<C-->` in terminal

### ISSUE THREAD

**Issue by Matts966** [neovide/neovide#1451]
**Is your feature request related to a problem? Please describe.**

Current neovide sends `5;5u` instead of `<C-->`, which is handled as shell undo in zsh, bash.

**Describe the solution you'd like**

`<C-->` in terminal is supported.

**Describe alternatives you've considered**

**Additional context**
<img width="159" alt="スクリーンショット 2022-08-05 1 16 02" src="https://user-images.githubusercontent.com/28551465/182897817-f129c8a8-feaf-42c6-9a0c-425a632c045d.png">

**Comment by fredizzimo** [comment]
This should be fixed by #1899, it would be great if you can test that.
