### ISSUE TITLE
Multi-file WinSCP Integration 

### ISSUE THREAD

**Issue by Ktoks** [neovide/neovide#1452]
**Is your feature request related to a problem? Please describe.**
As I open files in Neovide from WinSCP, they all open new instances instead of new buffers.

**Describe the solution you'd like**
When files are opened from WinSCP, open each new file in a new buffer.

**Describe alternatives you've considered**
I've considered and attempted installing Neovim remotely, but there remote server environment is incredibly locked down. They don't even allow WGET to run, so Neovim would not be able to pull down configuration files, parser updates, and extension updates with packer, or other package managers.

**Additional context**
This feature is available in GVim.

**Comment by kacystocks** [comment]
After talking with the Neovim, I was able to get it to work, but the steps I took are rather involved, is there somewhere you would like me to document said steps for others?
[Here is the issue with Neovim.](https://github.com/neovim/neovim/issues/19641) I'm willing to document on both locations, or you can put a link to Neovim's if they allow me to put the steps there.

**Comment by Kethku** [comment]
Given that this is relatively niche, I think leaving the documentation here in this issue is good enough.
