### ISSUE TITLE
Cursor offset with vim window open when using mouse

### ISSUE THREAD

**Issue by jivvy** [neovide/neovide#1464]
**Describe the bug**
When you have a vim window open, and you use the mouse to change cursor position, the cursor will be offset.

**To Reproduce**
1. VSplit the window
2. Use mouse to highlight text

**Expected behavior**
Cursor placed where the mouse is.
It works fine if there is only one vim window

**Screenshots**
[Video demonstrating](https://streamable.com/00apiv)

**Desktop**
 - OS: Arch Linux 5.18.16-arch1-1
 - Neovide Version 0.9.0
 - Neovim Version 0.7.2

[neovide_rCURRENT.log](https://github.com/neovide/neovide/files/9275066/neovide_rCURRENT.log)

**Comment by MultisampledNight** [comment]
Closing in favor of #1368, thank you though!
