### ISSUE TITLE
extremely LARGE

### ISSUE THREAD

**Issue by umop3plsdn** [neovide/neovide#1471]
**Describe the bug**
The app text IS LARGE it's like nvim is zoomed  in

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. macOS 11.4]
 - Neovide Version [e.g. 0.6.0]
 - Neovim Version [e.g. 0.5.0]

**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**

**Additional context**

**Comment by MultisampledNight** [comment]
Thanks for reporting! You can set the font size which also controls how "large" neovim appears through the `guifont` option and specifically there the `hXX` option, see https://neovide.dev/faq.html#how-can-i-set-the-fontscale-the-ui-size. You could try out

```vim
set guifont=Fira\ Code:h9
```

...which sets the font to `Fira Code` with `9` points of height.

**Comment by dineshKumar777** [comment]
@umop3plsdn you are using very old version of neovide. latest is 0.9.0. 
https://github.com/neovide/neovide/releases/tag/0.9.0

**Comment by umop3plsdn** [comment]
➜ neovide --version
Neovide 0.9.0

**Comment by umop3plsdn** [comment]
the font changed dinesh but it didn't get smaller unfortunately. Here's a pic to put it in perspective https://i.imgur.com/D5kAxScl.png

**Comment by dineshKumar777** [comment]
Please provide following details. 
Guifont setting which you added in config file 
Unable to view your screenshot on imgur. You can upload your img in github itself. Just drag and drop when editing comment.

**Comment by umop3plsdn** [comment]
i'm not sure why the couple of fonts I chose before changed the style but not the size even using h2 or h22. But I just tried using set guifont=* and picked another one from there and it worked fine so i'm good to go. Thank you for your help

**Comment by umop3plsdn** [comment]
i had tried several from fc-list on my system but I didn't see them listed in the list from within neovide the guifont=*. From that list it was fine
