### ISSUE TITLE
Can't build from source in GNU/Linux Debian 12

### ISSUE THREAD

**Issue by AguirreIF** [neovide/neovide#1476]
Hi, I tried to install neovide from source following the instructions from https://neovide.dev/installation.html and in the step 3:

```
$ cargo install --git https://github.com/neovide/neovide
     Updating git repository `https://github.com/neovide/neovide`
```

gives me the error:

```error: no packages found with binaries or examples```

I installed `cargo` (v `0.57.0-7+b1`) and `rust` (v `1.59.0+dfsg1-2`) from the Debian repository, not like in the step 2:

```curl --proto '=https' --tlsv1.2 -sSf "https://sh.rustup.rs" | sh```

could that be the problem?

Thanks,

**Comment by MultisampledNight** [comment]
Thanks for reporting! Though I don't know what patches Debian might have applied to cargo. Is it possible that you've typed the command maybe with one space too much?

**Comment by AguirreIF** [comment]
Hi, thanks for the quick reply. I tried several types and checked the spaces, it's ok.

**Comment by DerFetzer** [comment]
For me the problem went away when I upgraded `rust` from `1.58.1` to `1.63.0`.

**Comment by AguirreIF** [comment]
> For me the problem went away when I upgraded `rust` from `1.58.1` to `1.63.0`.

Thanks, i'll try that.

**Comment by Charles-Schleich** [comment]
After running `cargo install --git https://github.com/neovide/neovide`  
On `rustc 1.59.0 (9d1b2106e 2022-02-23)`  
I was struggling with a package error:  
```sh
error: failed to compile `neovide v0.10.1 (https://github.com/neovide/neovide#ec020c9d)`, intermediate artifacts can be found at `/tmp/cargo-installj9tz5U`

Caused by:
  failed to select a version for the requirement `phf = "^0.11.0"`
  candidate versions found which didn't match: 0.10.1, 0.10.0, 0.9.0, ...
  location searched: crates.io index
  required by package `csscolorparser v0.6.2`
      ... which satisfies dependency `csscolorparser = "^0.6.2"` of package `neovide v0.10.1 (/home/charles/.cargo/git/checkouts/neovide-fa1a54c7e22a1a5b/ec020c9)`
```

I can confirm upgrading to `rustc 1.63.0 (4b91a6ea7 2022-08-08)` results in a successfully building neovide executable.
