### ISSUE TITLE
Keep text display state separate from neovim (undercurl being clipped off)

### ISSUE THREAD

**Issue by MultisampledNight** [neovide/neovide#1478]
Currently, Neovide is rendering changed/new lines with text whenever it's told so by neovim, and only these lines are redrawn. That chain starts here:

https://github.com/neovide/neovide/blob/697480b9520fefff45ba3a2528560cb3b3b5fc66/src/bridge/events.rs#L860

But this causes some issues with Neovide's current rendering strategy of text with background clipping on previous contents (here with `g:neovide_underline_automatic_scaling = v:true` and `:hi! Keyword gui=undercurl`, a part of my `.zshrc`, scrolled down a bit):

![An image demonstrating partly vertically clipped undercurl](https://user-images.githubusercontent.com/80128916/184509330-e87580f6-326a-4b1b-b4b9-2ff5abe84077.png)

While there are some ways to approach that (such as re-requesting text in the line below from neovim when rendering a line with undercurl), I think the most reasonable way would be to keep internal text state for every rendered window, which neovim line update operations are simply directed into instead of redrawn directly. Then, upon render-time, we could figure out what truly changed in comparison to last frame's buffer, diff and apply redraws as needed.

This would allow coordinating redraws in a way while keeping effects such as undercurl intact. For example, if any text cell happens to be redrawn, it could check if the text cell above had undercurl and redraw it if that's the case. It would also make copying of specially-setup floating buffers or the command line possible to implement.

While this is just a wild spark, I'm not terribly sure how good this idea really is. It would duplicate work, since neovim already kind of keeps buffer state, and it would introduce a large surface for bugs, such as cases where neovim's line changes aren't fully/at all applied to the buffer and Neovide shows something else than really is on display.

**Comment by calops** [comment]
I do think it would be a good idea to separate the rendering phase from the drawing phase. In short, serialize the buffer state in a form that helps us render it efficiently and accurately, but separately.

A rendered buffer could be in the form of line fragments ready to render, but with the ability to split them into different elements to be rendered at different times. For example, different layers : line fragments for backgrounds, foregrounds, and then decorations (underlines and the sort). This enables us to render things in the correct order, to avoid backgrounds clipping over characters (this happens with some fonts) and undercurls/lines/whatever. This can even be done in a separate thread that's just waiting for the rendered buffers to have modifications.

And this would create future possibilites as well. For example, built-in pixel-perfect glyphs for drawing boxes and the sort (like alacritty does), which is a feature I've been wanting for a while (some fonts are a mess with these symbols).

**Comment by 9mm** [comment]
This is a side question... but is there a way to make the undercurl thicker? here is neovim

<img width="417" alt="image" src="https://github.com/neovide/neovide/assets/1386207/8e67e3af-982c-4fc4-a875-6ccbd3ff8a63">

macvim was about twice as thick and easier to see

**Comment by 9mm** [comment]
Oh.. I do see how `neovide_underline_automatic_scaling` definitely makes it bigger and thicker, at the expense of clipping.

Is there a way to explicitly define the factor at which its scaling? Maybe I can scale it up only 10% or something

**Comment by fredizzimo** [comment]
Once we get this in, we should be able to draw the undercurl using a separate pass without clipping. So the order would be the following:

1. Background
2. Underline, undercurl, underdouble,  underdotted, underdashed
3. Text
4. Strikethrough

**Comment by 9mm** [comment]
Thanks @fredizzimo I really appreciate all the work you're doing on Neovide

Moving to neovim has been really quite painless, and i dont feel like im missing anything, or the things im missing i can count on one hand and are in the roadmap/or issues already

I wish I could be more help fixing them, I had a serious look but it's a bit over my head. I've wanted to learn rust though, or at least mess around with it, so I'll give it another go

**Comment by 9mm** [comment]
Would it be crazy to make `neovide_underline_automatic_scaling` an actual value (like a target font size) instead of a boolean, so it could be tweaked?

**Comment by fredizzimo** [comment]
@9mm. No that sounds like a good feature request, you can go ahead and create an issue for it, so that it can be tracked separately.

And thanks, once you feel ready, you can look at issues with the ”good first issue” label. Most of them explain  exactly what needs to be done. And then once you have got a hang of it you can move to more complex stuff.
