### ISSUE TITLE
Startup performance on Mac

### ISSUE THREAD

**Issue by Matts966** [neovide/neovide#1480]
**Is your feature request related to a problem? Please describe.**

In issue #200 and PR #238, startup performance on Mac seems to be improved.
However, in my mac environment with the recent build, it takes about 3 seconds as reported in #200.

The binary size improved in #238 is about 10MB, but the current binary size is about 20MB, though #238 can't start with error `thread 'main' panicked at 'Failed to create window: SdlError("Failed to load Vulkan Portability library")`.

**Describe the solution you'd like**

- Locate where the performance issues are (Font loading is the point in #200)
- Fix it

**Comment by xzbdmw** [comment]
I turn off font smooth using https://www.fontsmoothingadjuster.com/, and startup time is about 200ms compared to 1s. Maybe you can try.

**Comment by falcucci** [comment]
startup time here it's 70ms avg.

i'll close it but we can reopen in case it still needs specific investigation.
