### ISSUE TITLE
Scrolling regression

### ISSUE THREAD

**Issue by LoipesMas** [neovide/neovide#1491]
**Describe the bug**
Scrolling is *glitchy* after #1485 (ironic)

**To Reproduce**
1. Launch neovide
1.1 `:let g:neovide_scroll_animation_length=0.0` (not sure if required)
2. Open a file
3. Scroll
4. See that lines sometimes show up empty for a split second

This also happens when jumping longer distances (e.g. `GG` from the bottom of the file)

**Expected behavior**
Working as before

**Screenshots**

Before:

https://user-images.githubusercontent.com/46327403/185205073-9ad6886f-79c9-427d-8a6a-bf1e559f68d1.mp4

Now:

https://user-images.githubusercontent.com/46327403/185205177-4f20d7ea-c238-4b02-b6c4-69274959204f.mp4

And I tried #1489 but it doesn't fix this sadly

**Comment by outfoxxed** [comment]
Interesting. #1485 should affect the entire window's offset, not just part of it. I'll take a look.

**Comment by outfoxxed** [comment]
Confirmed that pr is the cause, attempting to fix it.

**Comment by outfoxxed** [comment]
Found a way to fix it, should have something working soon.

**Comment by outfoxxed** [comment]
@LoipesMas try this

**Comment by LoipesMas** [comment]
@outfoxxed yep, that fixed that

**Comment by outfoxxed** [comment]
Good to hear

**Comment by outfoxxed** [comment]
@LoipesMas should this be closed? (the pr was merged)

**Comment by LoipesMas** [comment]
Yes, thanks!
