### ISSUE TITLE
Highlight and open URLs with mouse

### ISSUE THREAD

**Issue by mahor1221** [neovide/neovide#1492]
**Describe the solution you'd like**
It would be nice if Neovide had a similar feature found in terminals like Alacritty. The description from https://github.com/alacritty/alacritty/issues/113: 
> Other popular linux terminals often have a feature when you mouse over a URL it highlights and you can right click to open them in a browser. I believe this is often referred to as "dingus click". I find it a very handy feature.

**Comment by MultisampledNight** [comment]
Thanks for reporting! Probably requires #1478 to be implemented first.

**Comment by kskarthik** [comment]
Yes, I have been waiting for this feature as well

**Comment by Drllap** [comment]
I would like to upvote this

**Comment by ribtoks** [comment]
+1, it would great help with documentation and/or diagnostics links, that are provided by LSP

**Comment by fredizzimo** [comment]
This is now a native Neovim feature, so I don't see any need for a special neovide feature.
* https://github.com/neovim/neovim/pull/23401

And you can easily map that to the right click menu https://neovim.io/doc/user/gui.html#popup-menu

**Comment by hyt589** [comment]
> This is now a native Neovim feature, so I don't see any need for a special neovide feature.
> 
> * [vim.ui.open: "gx" without netrw neovim/neovim#23401](https://github.com/neovim/neovim/pull/23401)
> 
> And you can easily map that to the right click menu https://neovim.io/doc/user/gui.html#popup-menu

this does not seem to work when connecting to a remote instance of neovim?

**Comment by fredizzimo** [comment]
That's true, I think we should start by creating a `neovide.ui.open` API, that can override  [`vim.ui.open`](https://neovim.io/doc/user/lua.html#vim.ui.open()) or just used for the `gx` mapping.

I think this should be a user choice, so there needs to be a `vim.ui.open = neovide.ui.open` somewhere in the config.

I don't like overriding, but currently Neovim does not provide a customization directly, only through the `opts` to the command directly. We can add a feature request for that later.

**Comment by fredizzimo** [comment]
I forgot to mention, the UI protocol now also defines `url`  https://neovim.io/doc/user/api-ui-events.html#ui-event-hl_attr_define

So, we could provide an optional native integration, perhaps with ctrl-click.

**Comment by FrankTaylorLieder** [comment]
FYI I created this a few days ago to deal with this problem... https://github.com/FrankTaylorLieder/rurl (use at your own risk!)
