### ISSUE TITLE
Unicode rendering not working with JetBrains Mono

### ISSUE THREAD

**Issue by snoopdouglas** [neovide/neovide#1495]
**Describe the bug**

The latest 'stable' JetBrains Mono Nerd Font (available as of v2.1.0) doesn't seem to render unicode correctly; the characters just don't appear. The font seems to work fine in other apps, and upgrading to the font available with the 2.2.0 RC fixes this. Fira Sans works fine. Weirdly, in either case, icon glyphs do still render.

I'm unsure whether this is a Neovide-specific thing, but thought it'd be worth opening an issue just in case there's something to be remedied here.

This *might* be related to #1318.

**To Reproduce**

Paste a non-ASCII character - (like █ as shown below) into a document; it doesn't render.

**Expected behavior**

The character renders.

**Screenshots**

With JetBrains Mono Nerd Font v2.1.0:

![old](https://user-images.githubusercontent.com/4892574/185757638-73b0bfcb-06f2-48bf-b265-bf3403509b53.png)

...and with the v2.2.0 RC:

![new](https://user-images.githubusercontent.com/4892574/185757636-9c31180d-9ffb-4de7-a7a9-8e12156557bf.png)

(note that I've confirmed this doesn't just apply to the astronvim start screen. ;)

**Desktop (please complete the following information):**
 - OS: Fedora, GNOME 42
 - Neovide Version: 0.10.1
 - Neovim Version: 0.7.2

**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**

```
TRACE [neovide] Neovide version: 0.10.1
```

**Additional context**

n/a

**Comment by fredizzimo** [comment]
I think this was a Jetbrains issue, but it should be fixed now with the latest versions.
