### ISSUE TITLE
Unable to change the font size in my windows neovide.

### ISSUE THREAD

**Issue by 17Swagat** [neovide/neovide#1500]
**Describe the bug**
I'm unable to change the size of the fonts and logos in my neovide gui.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Neovide Version 0.9.0
 - Neovim Version 0.7.2

**Comment by MultisampledNight** [comment]
Thanks for reporting! What setting did you exactly try out? Are you sure the font name matches what's found in `:set guifont=*`? Did you take a look at https://neovide.dev/faq.html#how-can-i-set-the-fontscale-the-ui-size?

**Comment by 17Swagat** [comment]
Looked into the FAQ section and tried a bunch of methods,.. but everything is still a mess. And its not working. 
Neovide is stuck to a particular font and fontsize and I can't change it.

**Comment by MultisampledNight** [comment]
Alright. Could you run `:set guifont=*` in Neovide and hit Enter on some fonts? What do you observe?

**Comment by 17Swagat** [comment]
Everythings fine now after some tinkering .... Well Thanks for the help :)

**Comment by avalonv** [comment]
> Everythings fine now after some tinkering .... Well Thanks for the help :)

what tinkering?? what did you do?

https://xkcd.com/979/
