### ISSUE TITLE
Neovide doesn't get the right input from keyboard

### ISSUE THREAD

**Issue by netfri25** [neovide/neovide#1501]
**Describe the bug**
Switching between workspaces causes neovide to enter the wrong characters, which means I can't use it properly.
On neovim it doesn't happen.

**To Reproduce**
Open neovide, switch to a different workspace and go back.

**Expected behavior**
Be able to use neovim as usual.

**Screenshots**
[screen recording](https://user-images.githubusercontent.com/40868480/186001816-54216ee0-7e93-4d6d-a720-73c39c5385f5.mp4)

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04.1
 - Neovide Version: 0.9.0
 - Neovim Version: 0.7.2

**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**
[neovide_rCURRENT.log](https://github.com/neovide/neovide/files/9397039/neovide_rCURRENT.log)

**Additional context**
Only happens in neovide.
I've tried using other GUIs for neovim and it works fine in them (gnvim and nvui).

**Comment by MultisampledNight** [comment]
Thanks for reporting! Is it possible that you've switched keyboard layouts in-between? Also, are you running GNOME in a X11 or Wayland sessions (does `echo $WAYLAND_DISPLAY` in a terminal yield anything except a newline)?

**Comment by netfri25** [comment]
> Thanks for reporting! Is it possible that you've switched keyboard layouts in-between? Also, are you running GNOME in a X11 or Wayland session (does `echo $WAYLAND_DISPLAY` in a terminal yield anything except a newline)?

I didn't switch the layout, and running `echo $WAYLAND_DISPLAY` just prints a newline.
(I use `C-M-ArrowUp` and `C-M-ArrowDown` for switching between workspaces)

**Comment by netfri25** [comment]
I made a small program in c to test which keys are being pressed, and it seems like it presses the ESC key (ascii code 27).
I still can't figure out why it does that.

https://user-images.githubusercontent.com/40868480/186084347-a6fb19ea-15ff-408e-906d-f4438af778b3.mp4

**Comment by gaganchandan** [comment]
I am having this same issue on Gnome with Neovide version 0.10.1 and Neovim version 0.7.2. @netfri25 did you find a fix?

**Comment by netfri25** [comment]
@gaganchandan nope, but I recently switched my computer and it works fine now, so idk.
I hope it won't come back, probably some weird bug with ubuntu or smth.

**Comment by Phreno** [comment]
I have a similar issue. I'm using a BÉPO layout, and neovide seems to ignore it. Does'nt append in neovim.
Randomly, it works well, considering the good layout.

- Linux LIN0181233 5.15.0-56-generic #62~20.04.1-Ubuntu SMP Tue Nov 22 21:24:20 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
- neovide 0.10.3

**Comment by fredizzimo** [comment]
I think this is fixed by the new winit update in master with https://github.com/neovide/neovide/pull/1789, could you try again with Neovide master?

**Comment by fredizzimo** [comment]
This should be fixed by #1899, it would be great if you can test that.
