### ISSUE TITLE
Black screen with cursor when opening neovide

### ISSUE THREAD

**Issue by J-E-Mc** [neovide/neovide#1510]
**Describe the bug**
When I run `neovide` a new window opens with a black background and a white cursor (cursor becomes hollow when window looses focus), it cannot be closed normally, it only closes when I send it a SIGTERM / SIGKILL

**To Reproduce**
run `neovide`

**Expected behavior**
neovide should start up and display a similar interface to when I just run `nvim` in a terminal

**Screenshots**
![image](https://user-images.githubusercontent.com/44543806/187034862-8931437f-041c-44e4-8648-0b55b17dcc46.png)

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Neovide Version 0.10.1 (From normal repos)
 - Neovim Version v0.8.0-dev-967-g523600ea6 (from aur package `neovim-nightly-bin`
 I have also tried with v0.7.2 from the `neovim` package with the same result

**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**
[neovide_rCURRENT.log](https://github.com/neovide/neovide/files/9438151/neovide_rCURRENT.log)

**Additional context**
Probably related to `Error decoding response to request 'nvim_get_var'`?

**Comment by pspiagicw** [comment]
This happens when either neovim is still loading the configuration. Or there is a error in neovim configuration.Can you confirm that neovim is loading error-free in the terminal.

**Comment by J-E-Mc** [comment]
Yes, neovim loads perfectly fine from the terminal, it takes under half a second to start up and I waited a minute at least with neovide open and it still did nothing

**Comment by AverageComet250** [comment]
Any update on this? I seem to be having the same issue...

**Comment by dineshKumar777** [comment]
I encountered this bug long back randomly. for me just clicking insert button makes neovide responsive.
try running with neovide with clean flag - 'neovide -- --clean'.

**Comment by Mateiadrielrafael** [comment]
@dineshKumar777 I also have this issue when loading with `--clean`

**Comment by Mateiadrielrafael** [comment]
I also clicked insert and nothing happened

**Comment by dineshKumar777** [comment]
Then we need to investigate. Can you share your neovide logs

**Comment by Mateiadrielrafael** [comment]
Here's my logs:
[neovide-wrapped_rCURRENT.log](https://github.com/neovide/neovide/files/11015793/neovide-wrapped_rCURRENT.log)

Maybe this is useful? 
![image](https://user-images.githubusercontent.com/39400800/226289246-d2863dbf-5616-4e7c-870f-ed5fd5e3d51f.png)

@dineshKumar777

**Comment by Mateiadrielrafael** [comment]
@dineshKumar777 This only happens in neovim-nightly

**Comment by AverageComet250** [comment]
Happens for me on stable too. Can't attach a log right now, but I think it has something to do with screen resolution, since neovim is loading my config (I can see the background colour change) and I managed to get a view of part of a line number and the status bar when in full screen on a larger monitor

**Comment by willdavidow** [comment]
On Mac OS (Monterey) I'm seeing the same thing with Neovide installed using Homebrew and the latest nightly of Neovim (also installed using Homebrew)... 

It's worth noting, though: I just compiled Neovide from source and it works just fine.

If it's at all helpful: I've attached some log files from my last (unsuccessful) run of the Homebrew-installed Neovide before I uninstalled it and compiled from source locally.

[neovide_rCURRENT.log](https://github.com/neovide/neovide/files/11179358/neovide_rCURRENT.log)

**Comment by wizard-28** [comment]
Same issue here on neovim 0.9.0

**Comment by lenohard** [comment]
It works initially for me, but after a while, it works as described in this issue.

**Comment by NassimRayZ** [comment]
Just happened to me now, nvim is working but neovide is not.

**Comment by SpacewaIker** [comment]
Same here, on neovim 0.9.0 with AstroNvim config. Everything works for `nvim` or `nvim-qt`, but neovide doesn't load anything. I'm on Windows 11. I tried both the scoop version of neovide and the one from [GitHub Actions](https://github.com/neovide/neovide/actions/runs/4642339163)

**Comment by AverageComet250** [comment]
If anyone has a 4k display could they try seeing if their neovide install works with scalling set to 100%? I remember being able to get it display incorrectly (can't remember how) but my display wasn't big enough...

**Comment by AlleNeri** [comment]
For who had the problem since the 0.9.0 `nvim` version: this is the [link](https://discord.com/channels/896132176091955261/896263894086066216) to the discord channel where I found a temporary solution yesterday.

**Comment by Kethku** [comment]
This is fixed with current release.

**Comment by rxn7** [comment]
> This is fixed with current release.

no it's not lol

**Comment by shivamchandra75** [comment]
> This is fixed with current release.

It is not fixed in 0.10.3 for macOS
