### ISSUE TITLE
Keyboard confused after press win+left

### ISSUE THREAD

**Issue by yingmanwumen** [neovide/neovide#1512]
**Describe the bug**
After pressing `win+left`, the keyboard input confused:
I pressed `win+left` and then `:q<del>`
![image](https://user-images.githubusercontent.com/58961385/187076952-ceaca60f-8f98-44ba-b21f-73f140d9a4f6.png)

And after I press `win` or `win+anykey` again, this confusion disappeared.

**To Reproduce**
1. Press `win+left`
2. Key `h`、`q`……can not work,keyboard input confused
3. See error

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Debian testing bookworm
 - Neovide Version [e.g. 0.10.1]
 - Neovim Version [e.g. 0.7.2]

**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**

**Additional context**

**Comment by fredizzimo** [comment]
This should be fixed by #1899, it would be great if you can test that.
