### ISSUE TITLE
Cannot using Chinese input method in neovide

### ISSUE THREAD

**Issue by yingmanwumen** [neovide/neovide#1513]
**Describe the bug**
I cannot switch the input method via `left shift` neither use Chines input method of fcitx5.

**To Reproduce**
1. Press `left shift` or `ctrl+leftshift` or something to switch the input method
2. Doesn't work
3. Switch the input method by clicking, and then return to `neovide`
4. Cannot use my Chinese input method `pinyin`.

**Expected behavior**
Be able to use Chinese input method and switch it via keyboard shortcut `leftshift`.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Debian testing bookworm
 - Neovide Version: 0.10.1
 - Neovim Version : 0.7.2

**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**

**Additional context**

**Comment by hhofner** [comment]
I believe this is an ongoing issue, see here: https://github.com/neovide/neovide/issues/445

**Comment by yingmanwumen** [comment]
> I believe this is an ongoing issue, see here: #445

Thanks, I didn't find it. Too many issues.
