### ISSUE TITLE
Neovide closes immediately after starting in Ubuntu Linux

### ISSUE THREAD

**Issue by snoitallicso** [neovide/neovide#1514]
**Bug**
I installed neovide from Ubuntu/Debian [Linux Source](https://neovide.dev/installation.html#linux-source) and on opening, it appears for a second and then closes without any warnings or errors. But if I run something like `neovide script.py --log` it works.

**To Reproduce**

1. Install neovide from Ubuntu/Debian [Linux Source]
2. Launch neovide

**Expected behavior**
Neovide opens without any issue

**Desktop:**
 - OS: Ubuntu Linux 20.04
 - Neovide Version 0.10.1
 - Neovim Version 0.4.3

**Contents of the `.log` file:**
_Log file not created._

**Additionals:**

- window manager: i3
- display server: X

**Comment by FinallyFinancialFreedom** [comment]
ubuntu22.04, xfce4, i3wm, use latest binary release, the same problem, flash and quit

**Comment by davethecipo** [comment]
I have the same problem on Fedora 36, X11, neovide 0.9.0, NVIM 0.7.2. Running with `--log --nofork` generates a coredump (but I don't know how to use it...can somebody give some help?).

Shell output:
```
[xcb] Unknown sequence number while processing queue
[xcb] Most likely this is a multi-threaded client and XInitThreads has not been called
[xcb] Aborting, sorry about that.
neovide: xcb_io.c:269: poll_for_event: Assertion `!xcb_xlib_threads_sequence_lost' failed.
fish: Job 1, 'neovide --nofork' terminated by signal SIGABRT (Abort)
```

Log file:
```
TRACE [neovide] Neovide version: 0.9.0
DEBUG [neovide::bridge::command] Starting neovim with: Command { std: "/usr/bin/nvim" "--embed" "cover_letter_davide_olianas.tex", kill_on_drop: false }
INFO [neovide::bridge::setup] Neovide registered to nvim with channel id 1
INFO [neovide::bridge] Neovim process attached
DEBUG [neovide::settings::window_geometry] Loaded window settings: Windowed { position: PhysicalPosition { x: 0, y: 32 }, size: Dimensions { width: 96, height: 44 } }
```

**Comment by MultisampledNight** [comment]
@davethecipo The shell output makes me think you're facing https://github.com/neovide/neovide/issues/1068, not this issue. At least that's what I assume as long as the OP doesn't answer/a comparable setup faces the same output.
