### ISSUE TITLE
mouse selection with `set mouse=a` breaks when vim is split up

### ISSUE THREAD

**Issue by worldwalker2000** [neovide/neovide#1515]
**Describe the bug**
When you have your vim window split, selecting text with the mouse in sections that are not directly on the very top cause the selection to teleport to the end of the file.

**To Reproduce**
0. :set mouse=a
1. Open a file in neovide that has a substantial amount of text.
2. Split the window horizontally (<C-w><C-s>)
3. Select text using the mouse within the lower section.

**Expected behavior**
I expect it to select the text that the mouse pointer passes over just like how it functions in the window that is on the top.

**Screenshots**
![output](https://user-images.githubusercontent.com/26694636/187093716-3afe76ee-f415-4e94-b9b5-8fa00e2aa508.gif)

**Desktop (please complete the following information):**
 - OS: macOS 12.4
 - Neovide Version: 0.9.0
 - Neovim Version: 0.7.0

**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**
TRACE [neovide] Neovide version: 0.9.0
It produced two log files, one was too long to put here and the other just said the version. If you need the log then ill get it again and attach it.

**Additional context**
This does not happen when I run neovim in my terminal so I know that this is a problem with neovide.

**Comment by MultisampledNight** [comment]
Thanks for reporting! Do you have multigrid enabled, by chance?

**Comment by worldwalker2000** [comment]
I have never heard of that. I tried seeing if it was enabled by doing ```:echo ext_multigrid``` and checking for some other variables, but that just gave me undefined variable. I see that multigrid is for floating windows and I do get some floating notification popups from Neogit so maybe I do have it enabled?

I just can't tell. If you tell me how to I will happily check.

**Comment by MultisampledNight** [comment]
Okay, by default multigrid is disabled at the moment, Neovide conditionally implements it as a NeoVim UI extension. If it happens to be enabled, floating windows should be blurred and scrolling should be smooth.

You can enable it through `--multigrid` as command line option or through setting an environment variable named `NEOVIDE_MULTIGRID` to something non-empty (reference https://neovide.dev/command-line-reference.html#multigrid).

**Comment by worldwalker2000** [comment]
Enabling multigrid does fix the bug. Thank you.
