### ISSUE TITLE
Crash when opening in remote desktop of Windows.

### ISSUE THREAD

**Issue by zhangzhishan** [neovide/neovide#1517]
**Describe the bug**
When open the neovide in remote desktop of windows, it will crash immediately.
**To Reproduce**
1. Open in remote desktop

**Desktop (please complete the following information):**
 - OS: Windows 10 19044.1889
 - Neovide Version [0.10.1]
 - Neovim Version [0.6.1]

**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**
TRACE [neovide] Neovide version: 0.10.1
DEBUG [neovide::bridge::command] Starting neovim with: Command { std: "C:\\Users\\zhizha\\scoop\\shims\\nvim.EXE" "--embed", kill_on_drop: false }

**Additional context**
when runing with `neovide --nofork`, I can get this crash location below, thus I guess it is realted to the remote desktop.
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: NoAvailablePixelFormat', src\window\mod.rs:352:10

**Comment by fredizzimo** [comment]
Neovide needs gpu access with opengl 3.3 or later or hardware d3d with this, so you could try if that works better.
* https://github.com/neovide/neovide/pull/2215

If that's not available, I don't think there's anything we can do, Neovide would just be too slow.
