### ISSUE TITLE
neovide internal elements messed up

### ISSUE THREAD

**Issue by Varad-Sharma** [neovide/neovide#1518]
It started happening quite often that when i run neovide it is opened in an complete weird way the application size is good but the contents inside are misplaced. When i start it using terminal or rofi it opens like it:
![2022-08-29-18:28:20-screenshot](https://user-images.githubusercontent.com/87317408/187206677-c0797749-4fd1-41db-93bc-b221a83214ee.png)

OS: endeavourOS(i3)
Neovide ver: 0.10.1
Neovim ver: 0.7.2

**Comment by katawful** [comment]
I'm also experiencing this on 0.10.1 on Arch. Its using the default size when launching for some reason

**Comment by Varad-Sharma** [comment]
I guess we'll have to use another editor till it's fixed

**Comment by katawful** [comment]
If you force a resize (like quickly enabling and disabling fullscreen via i3), it will properly resize. It only seems to break on the initial size startup calculation

**Comment by katawful** [comment]
https://github.com/neovide/neovide/commit/324a02bd323a7af1bfbf6f2ce21213299f305769

This is likely the offending commit

**Comment by Varad-Sharma** [comment]
> If you force a resize (like quickly enabling and disabling fullscreen via i3), it will properly resize. It only seems to break on the initial size startup calculation

Thanks it really worked by entering and exiting fullscreen

**Comment by MultisampledNight** [comment]
The original issue still persists though.

**Comment by laniusone** [comment]
I face the same issue. Additionally, after resizing the window (which makes it resize the grid correctly) it sometimes ignores keyboard input until restarted.

**Comment by Varad-Sharma** [comment]
> I face the same issue. Additionally, after resizing the window (which makes it resize the grid correctly) it sometimes ignores keyboard input until restarted.

It gets temporarily solved if you alt-tab it once

**Comment by aj3423** [comment]
I found that the buffer size is saved somehow, and if the last closed window is in different size, this bug happens.
For instance:
1. open window A, resize to 400*300, close A
2. open window B, maximize to full screen, close B
3. open A again, the window is maximized, but the buffer is only 400*300

I thought it maybe vim sessions that saved the buffer size, so I removed the session plugin and seems the bug no more happens.

Anyone also has session plugin installed? Try disable it.

**Comment by stefanwatt** [comment]
Just built the latest commit and the issue persists.
I also never had `vim.opt.sessionoptions:append('resize,....') ` set.
I don't see how scheduling a redraw after a resize event would fix this. It was always drawn correctly after a resize as indicated by this comment:

> If you force a resize (like quickly enabling and disabling fullscreen via i3), it will properly resize. It only seems to break on the initial size startup calculation

**Comment by gctypo** [comment]
I'm also encountering this in 0.10.3 on Arch, with i3wm. It starts with its size that differs from the window's actual size.

It seems like Neovide retrieves its internal size from somewhere, sets it, and while maybe that works for floating WMs, for tiling WMs the actual window size is often different, since it's set by where the tiled window is on the workspace.

The workaround I have is to force float and return the window (`$mod+space` x2).

**Comment by laniusone** [comment]
I open a lot of Neovim windows (actually kitty -e nvim), and if I had to float/defloat every one of them, and put them back where they were supposed to be (usually a tabbed layout), I would go bonkers. This problem is the single reason Neovide is a no-go for me.

**Comment by MultisampledNight** [comment]
:thonk:

**Comment by MultisampledNight** [comment]
Personally I'm partly able to reproduce this, but very randomly, running on Sway.

**Comment by MultisampledNight** [comment]
I think this is a perfect moment to ~~ab~~use rr, I'll see if I can get any recordings with that bug happening.

**Comment by MultisampledNight** [comment]
Okay, got a trace. At `window/mod.rs:401` the `initial_size` does really represent the true window size, but it seems like it's somehow not propagated to the grid renderer/ignored at creation.

**Comment by jiblets22** [comment]
I don't know if this will help anyone or what is causing it.... but when i start neovide with hotkeys using a modifier... and continue to hold the modifier it causes this behavior?
in i3 this fixed it for me? 
exec  --no-startup-id neovide && xdotool keyup $mod 

neovide is a great program and this was driving me crazy for awhile

**Comment by aj3423** [comment]
> I don't know if this will help anyone or what is causing it.... but when i start neovide with hotkeys using a modifier... and continue to hold the modifier it causes this behavior? in i3 this fixed it for me? exec --no-startup-id neovide && xdotool keyup $mod
> 
> neovide is a great program and this was driving me crazy for awhile

@jiblets22 I opened another issue for the sticky modifier problem, in my case it's the Alt key:  https://github.com/neovide/neovide/issues/1631

**Comment by fredizzimo** [comment]
Is this still an issue in Neovide 0.12.1?
