### ISSUE TITLE
Slow relative numbers rendering performance.

### ISSUE THREAD

**Issue by MainEditor** [neovide/neovide#1519]
Well it's just slow when relative numbers are enabled. I'm talking about scrolling to that side of code that not displayed currently on the screen. Low FPS while scroll up or down when relative numbers are enabled.

**Comment by heimer16** [comment]
Also experiencing this issue.  I have a fast repeat rate on my keyboard and holding j/k to scroll up/down is laggy/stuttery with relativenumber on.  With relativenumber, it's fast and smooth.

**Comment by fredizzimo** [comment]
This should be fixed in Neovide 0.12.0 and later.
