### ISSUE TITLE
`g:neovide_cursor_trail_length` option not working with MacOS

### ISSUE THREAD

**Issue by dev-monokai** [neovide/neovide#1522]
I like Neovide's soft cursor animation. But the way the cursor is stretched is too fancy.
I used the `g:neovide_cursor_trail_length` option, but it doesn't seem to work.

[video capture](https://streamable.com/e/d5471g?autoplay=1)

**Comment by TomLebeda** [comment]
I have the same issue on Linux (Manjaro XFCE). I set the trail length to various numbers and also to 0, but I can't see any difference.

**Comment by MultisampledNight** [comment]
Thanks for reporting! The option is wrongly documented:

https://github.com/neovide/neovide/blob/9ccd709c6e26d20223f7b158677bbe3e68ab8690/src/renderer/cursor_renderer/mod.rs#L33

I'll change the website in a few moments.

**Comment by MultisampledNight** [comment]
Fixed in ffb3749f15c64b0f53f9fb4eead43962994286df, thank you!

**Comment by dev-monokai** [comment]
@MultisampledNight Thank you so much 💕

**Comment by TomLebeda** [comment]
Great, it works like a charm. Thanks for the quick fix.
