### ISSUE TITLE
Uses incorrect path when saving to nvim-data

### ISSUE THREAD

**Issue by junglie85** [neovide/neovide#1535]
**Describe the bug**
Appears to append path to `nvim-data` to the current directory from which the executable has been launched. Example is with Telescope but I've had this error a few times (I think also with Treesitter). In the screenshot below it shows the error from `D:\\` but I've also had it from `C:\Users\junglie85\.cargo\bin` which is where my icon on the taskbar is pinned from.

**To Reproduce**
1. Open neovide from PowerShell
2. `:lua require'telescope.builtin'.oldfiles{}<CR>" "recent"`
3. `<ESC>,<ESC>`

**Expected behavior**
I expected the telescope history file to be created.

**Screenshots**
![Untitled](https://user-images.githubusercontent.com/17502031/189913125-0a45aa74-75aa-4a73-a1eb-b1a1202c7a78.png)

**Desktop (please complete the following information):**
 - OS: Windows 11 Home 21H2
 - Neovide Version 0.10.1
 - Neovim Version 0.7.2

**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**
[neovide_rCURRENT.log](https://github.com/neovide/neovide/files/9557609/neovide_rCURRENT.log)

**Comment by fredizzimo** [comment]
I'm pretty sure, that this is fixed in the latest Neovide 0.12.1 release, but if not feel free to re-open.
