### ISSUE TITLE
Some Digraphs Recently Broken

### ISSUE THREAD

**Issue by jamesb6626** [neovide/neovide#1542]
**Describe the bug**
Since 346dc05, digraphs starting with the characters `<` and `|` are broken.
Instead of allowing digraph entry, it inserts the text `<S-lt>` or `<S-Bar>` respectively.
Note: `>`, and digraphs with these as the second character are unaffected.

**To Reproduce**
1. `$ neovide -- -u NONE`
2. `i<C-K><lt>` or `i<C-K><Bar>` behaves as described above.

**Expected behavior**
Some affected digraphs are `||`, `<<`, `<=`. For anyone testing this.

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04.5
 - Neovide Version 346dc05, d453921 (main)
 - Neovim Version 0.7.2

**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**

[neovide_rCURRENT.log](https://github.com/neovide/neovide/files/9586434/neovide_rCURRENT.log)
[neovide_r2022-09-16_19-23-15.log](https://github.com/neovide/neovide/files/9586438/neovide_r2022-09-16_19-23-15.log)

**Additional context**
Neovide built from source: `$ cargo install --path .`
Bug is not present in dc35636.

**Comment by s-cerevisiae** [comment]
This is probably the same problem as #1539. I'm looking for a fix.

**Comment by s-cerevisiae** [comment]
It's a bit late now, but the fix is merged. Would you like to test it?

**Comment by jamesb6626** [comment]
Sorry for the delay, seems like its fixed. Also fixed an issue I was having with hop.nvim, similar to #1539.
Thanks. I'll close the issue.
