### ISSUE TITLE
Multigrid: wrong order of floating windows in Telescope plugin

### ISSUE THREAD

**Issue by jamesb6626** [neovide/neovide#1543]
**Describe the bug**
Multigrid breaks the order of floating (I think) windows in the Telescope plugin.

**To Reproduce**
1. Install the telescope plugin (requires plenary plugin)
2. Open telescope and help window: `:Telescope<CR><Esc>?`

**Expected behavior**
Help window is supposed to appear on top, not below.
Compare result with and without multigrid.

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04.5
 - Neovide Version edc4cc9 (0.9.0), d453921 (main, after 0.10.1)
 - Neovim Version 0.7.2

**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**

[neovide_r2022-09-16_20-31-25.log](https://github.com/neovide/neovide/files/9586748/neovide_r2022-09-16_20-31-25.log)
[neovide_rCURRENT.log](https://github.com/neovide/neovide/files/9586749/neovide_rCURRENT.log)

**Additional context**
Neovide built from source: `$ cargo install --path .`
Not a big issue with this plugin, but I'm guessing this might break other plugins later on.

**Comment by Kethku** [comment]
This is fixed
