### ISSUE TITLE
incsearch crashes neovide when multigrid is set

### ISSUE THREAD

**Issue by khalidchawtany** [neovide/neovide#1546]
**Describe the bug**
When performing a search using "/" neovide crashes is incsearch is set with multigrid.

**To Reproduce**

1. start neovide  ./neovide --multigrid
2. set incsearch
3. search for a word /
4. Neovide crashes

**Expected behavior**
Not to crash

**Screenshots**
Not applicable

**Desktop (please complete the following information):**
 - OS: macOS 12.6 (21G115)
 - Neovide Version: Version 0.10.0 (20220815.121330)
 - Neovim Version: NVIM v0.8.0-dev-1110-g6966b476

**Please run `neovide --log  --multigrid` and paste the contents of the `.log` file created in the current directory here:**
[neovide_rCURRENT.log](https://github.com/neovide/neovide/files/9591623/neovide_rCURRENT.log)

<details>
<summary>Crash log</summary>
TRACE [neovide] Neovide version: 0.10.1
DEBUG [neovide::bridge::command] Running which command: "/bin/zsh" "-lc" "which nvim"
DEBUG [neovide::bridge::command] Starting neovim with: Command { std: "/bin/zsh" "-lc" "/usr/local/bin/nvim --embed", kill_on_drop: false }
DEBUG [neovide::settings::window_geometry] Loaded window settings: Windowed { position: PhysicalPosition { x: 960, y: 0 }, size: Dimensions { width: 71, height: 38 } }
INFO [neovide::bridge::setup] Neovide registered to nvim with channel id 1
INFO [neovide::bridge] Neovim process attached
TRACE [neovide::bridge::handler] Neovim notification: "redraw"
TRACE [neovide::channel_utils] neovide::editor::EditorCommand NeovimRedrawEvent(OptionSet { gui_option: ArabicShape(true) })
TRACE [neovide::channel_utils] neovide::editor::EditorCommand NeovimRedrawEvent(OptionSet { gui_option: AmbiWidth("single") })
.
.
.
.
.
.
.
.
.
.
.
.
.
.
TRACE [neovide::channel_utils] neovide::editor::EditorCommand NeovimRedrawEvent(GridLine { grid: 3, row: 0, column_start: 0, cells: [GridLineCell { text: " ", highlight_id: Some(189), repeat: Some(58) }] })
TRACE [neovide::channel_utils] neovide::editor::EditorCommand NeovimRedrawEvent(WindowViewport { grid: 2, top_line: 0.0, bottom_line: 25.0, current_line: 14.0, current_column: 56.0, line_count: Some(24.0) })
ERROR [neovide::error_handling] Could not parse event from neovim: invalid u64 format -1
ERROR [neovide::bridge] Error joining IO loop: 'task 17 panicked'
INFO [neovide::running_tracker] Quit neovim processed failed
DEBUG [neovide::settings::window_geometry] Saved Window Settings: {"window":{"Windowed":{"position":{"x":960,"y":0},"size":{"width":58,"height":31}}}}

</details>

**Comment by MultisampledNight** [comment]
Thanks for reporting! Likely linked to #1541.

**Comment by Suyashtnt** [comment]
It seems that any command which brings up the command line bar thing crashes neovide

**Comment by ad-chaos** [comment]
Do you have a minimal config that reproduces it?

**Comment by khalidchawtany** [comment]
@ad-chaos I can reproduce the error only if cmdheight =0

```
open -a /Applications/Neovide.app/Contents/MacOS/neovide --args  --multigrid --log -- --clean
:set cmdheight=0
:set incsearch
:e somefile.txt
/search_text
```
Pressing / shows the command bar. However, the moment I type a character neovide crashes.
I get some random crashes other times, but they are rare and I don't know why they happen.
>It seems that any command which brings up the command line bar thing crashes neovide

@Suyashtnt That is not the case for me.

**Comment by ad-chaos** [comment]
What's your neovim version? I am unable to reporduce it on the latest `HEAD`

**Comment by khalidchawtany** [comment]
I am always on HEAD. Every morning I compile neovim from source.

Any of incsearch and inccomand cause neovide to crash if multigrid is set and cmdheight=0.

**Comment by ad-chaos** [comment]
I just updated neovim and I am indeed able to reproduce this error. Will try to bisect neovim tommorrow and see where this originated from.

**Comment by ad-chaos** [comment]
Hmm, looks like this commit caused the problem https://github.com/neovim/neovim/pull/20188, I don't know what exactly causes the problem in that commit yet though :(

**Comment by khalidchawtany** [comment]
Thanks, @ad-chaos fixed by https://github.com/neovim/neovim/pull/20351

**Comment by ad-chaos** [comment]
ay! I was just about to come here, beat me to it 😅
