### ISSUE TITLE
`<C-CR>` support

### ISSUE THREAD

**Issue by musjj** [neovide/neovide#1548]
**Is your feature request related to a problem? Please describe.**
`<C-CR>` doesn't work with neovide.

**Describe the solution you'd like**
`<C-CR>` requires special [terminal codes](https://stackoverflow.com/a/42461580/19942988) to work with Neovim. A lot of terminal emulators supports this, but neovide doesn't.

**Comment by s-cerevisiae** [comment]
Another edge case? Is there any resources that tells how *each and every keys and their combinations with modifiers* should be sent?

**Comment by musjj** [comment]
This seems to be a working general solution for this problem:
http://www.leonerd.org.uk/hacks/fixterms/

There's also the keyboard protocol from Kitty (which apparently fixes some issues with the classic CSI encoding solution):
https://sw.kovidgoyal.net/kitty/keyboard-protocol/

Wezterm has an implementation for both of those schemes, and they seem to work pretty well for me:
https://github.com/wez/wezterm/blob/main/docs/config/key-encoding.md

**Comment by fredizzimo** [comment]
This should be fixed by #1899, it would be great if you can test that.
