### ISSUE TITLE
Sudo neovide.exe --wsl opens a non-root Neovim instance

### ISSUE THREAD

**Issue by richardhttps** [neovide/neovide#1552]
**Describe the bug**
Running neovide.exe from WSL as root runs a regular instance of Neovim.

**To Reproduce**
1. From WSL2 shell, run sudo neovide.exe --wsl /etc/bash.bashrc
2. File is opened as [RO]

**Expected behavior**
Running sudo neovide.exe --wsl should open a root instance of nvim.

**Desktop (please complete the following information):**
 - OS: [W11 22H22]
 - Neovide Version [0.10.1]
 - Neovim Version [0.7.2]

**Comment by NotTheDr01ds** [comment]
More info on my answer to your [Super User question](https://superuser.com/q/1743898/1210833).

Most existing WSL releases always run Windows executables as the default WSL user, even if started with `root`.  The same thing even [happens for VSCode](https://stackoverflow.com/q/58980356/11810933).

My proposal would be to add a new argument to Neovide:

```
--wslargs
```

... which would allow extra arguments to be passed to the `wsl` command.  Then, for editing files as root, you'd add:

```
--wslargs="-u root"
```

This would have the WSL session which is started by Neovide by running as the root user.

It would also be possible, using this type of mechanism, to specify the WSL distribution where Neovim (and your project files) are located.  Without this, Neovide can only be used on the default WSL distribution.  But one of the great things about WSL is being able to run multiple distributions (or even multiple instances of the same distribution).

Looking at the Neovide source, besides adding the flag itself, there are, I believe, only a few places where the argument string would need to be added:

* `build_nvim_cmd_with_args`
* `create_platform_shell_command`

**Comment by fredizzimo** [comment]
You should never run neovim as root, that's a huge security risk

https://superuser.com/questions/785187/sudoedit-why-use-it-over-sudo-vi

Instead you should set `nvim.exe` as your `$EDITOR`, and use `sudoedit`.
