### ISSUE TITLE
Set window title

### ISSUE THREAD

**Issue by bigH** [neovide/neovide#1553]
**Is your feature request related to a problem? Please describe.**
I'd like to be able to customize Neovide's title bar to include the `pwd`.

**Describe the solution you'd like**
Ideally, I'd expect that `vimrc` or equivalent can simply set:
```viml
let g:neovide_window_title = $PWD
```

Furthermore, it would also be nice to change the title while Neovide is running. This could be useful to indicate that `:terminal`s are waiting to complete some command or any number of things.

**Describe alternatives you've considered**
The only alternative I know is to use a terminal emulator instead.

**Additional context**
N/A

**Comment by MultisampledNight** [comment]
Thanks for reporting!

This is already possible, see the `title` and `titlestring` options. They both are respected by Neovide and can also be changed at runtime.

Though for the terminal, I'm not sure how this would go. Maybe the shell can set the current working directory and NeoVim just propagates it upwards, but this is either way something that's outside of Neovide's play area.

**Comment by fredizzimo** [comment]
@gsouf, they are Neovim options https://neovim.io/doc/user/options.html#'titlestring'
