### ISSUE TITLE
Terminal mode scrolling is broken with multigrid

### ISSUE THREAD

**Issue by outfoxxed** [neovide/neovide#1559]
**Describe the bug**
Scrolling breaks visually in terminal mode when multigrid is enabled.
This is caused by because #1489's position override is not released until it recieves a `WindowDrawCommand::DrawLine` following a `WindowDrawCommand::Viewport`, which does not happen in terminal mode.

I'm not particularly familiar with the codebase, and don't know what causes the `WindowDrawCommand`s (seems to lead back into an event bus or something), so I'm not sure how to fix it myself. From what I can tell, fixing it would involve either adding another condition to creating a position override, or causing another draw event to happen.

**To Reproduce**
1. enable multigrid & launch
2. open a terminal
3. type a command with output that will cause the terminal to scroll

**Expected behavior**
Terminal mode behaves the same way normal mode does.

**Screenshots**
Notice how in normal mode the log doesn't stop scrolling with an override active.
In terminal mode it does, causing the terminal to be offset.

https://user-images.githubusercontent.com/83010835/192428387-5ebcb251-13e2-4874-800c-b9c0add87ffc.mp4

**Desktop (please complete the following information):**
 - OS: Arch linux (updated somewhat recently)
 - Neovide Version: master
 - Neovim Version: v0.7.2

**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**
Scrolling in normal mode: 
[neovide_rCURRENT.log](https://github.com/neovide/neovide/files/9651450/neovide_rCURRENT.log)
Scrolling in terminal mode:
[neovide_rCURRENT.log](https://github.com/neovide/neovide/files/9651452/neovide_rCURRENT.log)

**Additional context**
See Screenshots

**Comment by xbladesub** [comment]
Seems like many things are broken with multigrid enabled, after last neovim update even more things. Considering to switch to helix and alacritty. I opened similar issue about multigrid - https://github.com/neovide/neovide/issues/1584

**Comment by MultisampledNight** [comment]
Hm. I'll revert #1489 for now, since scrolls partly not showing sounds worse to me than a few scrolling stutters.
