### ISSUE TITLE
Neovide closes almost immediatly after opening

### ISSUE THREAD

**Issue by Furanshisuko17** [neovide/neovide#1564]
**Describe the bug**
Neovim closes instantly after opening.

**To Reproduce**
1. Install latest neovide
2. Open neovide.

**Expected behavior**
Neovide should open normally

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 11 Insider Preview 10.0.22622.440
 - Neovide Version: 0.10.1 
 - Neovim Version: 0.7.2

**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**

neovide_rCURRENT.log
```
TRACE [neovide] Neovide version: 0.10.1
DEBUG [neovide::bridge::command] Starting neovim with: Command { std: "C:\\Program Files\\Neovim\\/bin\\nvim.EXE" "--embed", kill_on_drop: false }
```

**Additional context**
After checking the neovide command line reference, I added the `--nofork` argument and then this showed in the terminal:

```
❯ .\neovide.exe --log --nofork
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: NotSupported("required extension \"WGL_ARB_create_context_profile\" not found")', src\window\mod.rs:352:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by correabuscar** [comment]
It works for me, maybe see if you have these:
```
$ glxinfo|grep -i create_context_profile
    GLX_ARB_create_context_no_error, GLX_ARB_create_context_profile, 
    GLX_ARB_create_context_no_error, GLX_ARB_create_context_profile, 
    GLX_ARB_create_context_no_error, GLX_ARB_create_context_profile, 
```

or see if `glxgears` works for you?

on Gentoo `glxinfo` and `glxgears` are from package `x11-apps/mesa-progs-8.5.0`

**Comment by Furanshisuko17** [comment]
I see, my cpu is an old i5 2320, it has the integrated Intel HD 2000 graphics, as far as I know Intel hasn't released any new driver for this gpu

**Comment by fredizzimo** [comment]
The GPU is good enough for Opengl 3.3, since the open source drivers in Mac and Linux seems to support it, but Intel never bothered to implement it.

But I checked it a bit more supporing opengl 3.1 might be as simple as Changing this 
https://github.com/neovide/neovide/blob/0b6e20c1994c761814eb6a8ad33dea90ade97573/src/window/mod.rs#L346-L353

to 
I'm not 100% sure that the profile should be removed, but I think so since that seems to be 3.2 functionality.
```diff 
 let windowed_context = ContextBuilder::new() 
     .with_pixel_format(24, 8) 
     .with_stencil_buffer(8) 
-    .with_gl_profile(GlProfile::Core)
+    .with_gl(GlRequest::Specific(Api::OpenGl, (3, 1)).) 
     .with_vsync(false) 
     .with_srgb(cmd_line_settings.srgb) 
     .build_windowed(winit_window_builder, &event_loop) 
     .unwrap(); 
```

But, even if it works, I'm not sure if it should be the default, since it could have some performance implications on newer hardware

**Comment by Furanshisuko17** [comment]
Hello, I downloaded the repo and tried changing that line of code but many more errors appeared, I ran `cargo run -- --log` three times and two different errors appeared:
```
 Finished dev [unoptimized + debuginfo] target(s) in 3m 52s
     Running `target\debug\neovide.exe --log`
error: process didn't exit successfully: `target\debug\neovide.exe --log` (exit code: 0xc0000005, STATUS_ACCESS_VIOLATION)
Fran in neovide-0.10.1                                                                            
❯ cargo run -- --log
   Compiling neovide v0.10.1 
    Finished dev [unoptimized + debuginfo] target(s) in 7.74s
     Running `target\debug\neovide.exe --log`
error: process didn't exit successfully: `target\debug\neovide.exe --log` (exit code: 0xc000041d)
Fran in neovide-0.10.1                                                                                                     
❯ cargo run -- --log
   Compiling neovide v0.10.1 
    Finished dev [unoptimized + debuginfo] target(s) in 7.33s
     Running `target\debug\neovide.exe --log`
error: process didn't exit successfully: `target\debug\neovide.exe --log` (exit code: 0xc0000005, STATUS_ACCESS_VIOLATION)
```
I'm not sure why it crashed with two different errors, but as you can see the first run was the first one(building all external crates) also this is the .log file [neovide_rCURRENT.log](https://github.com/neovide/neovide/files/9687923/neovide_rCURRENT.log)
At the end of the file there are many errors that I think that probably appeared because OpenGl 3.1 doesn't support many features required by neovide

**Comment by fredizzimo** [comment]
This might be fixed if we switch to a wgpu renderer, but for now there's nothing we can do, so closing this.

**Comment by BL-BlueLighting** [comment]
after 3 years, i am still using amd radeon hd 7600, but wgpu renderer makes it crashed and no time to save logs. if your graphics card supports opengl 4.5, but not supports vulkan and more new renderer, try use 'neovide --opengl'.
