### ISSUE TITLE
Super (Win key) + Number unexpected behavious

### ISSUE THREAD

**Issue by Karthik-Dulam** [neovide/neovide#1568]
**Describe the bug**
On my terminal neovim, Super + any number key does nothing. 
But when pressed on neovide, no key press works until I press Esc.

**To Reproduce**
1. Press Super + 6
2. Press i to insert (does not go into insert mode)
3. Press Esc
4. Press i to insert (goes into insert mode)

**Expected behavior**
Nothing should happen, and key presses should be recognized.

**Desktop (please complete the following information):**
 - OS: Archlinux
 - Neovide Version [e.g. 0.10.1.r16.gf7ad535-1]
 - Neovim Version [e.g. 0.7.2-3]

**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**
Log is very long, but window key + number was not registered in log.

**Comment by fredizzimo** [comment]
This should be fixed by #1899, it would be great if you can test that.
