### ISSUE TITLE
neovide --neovim-bin lvim

### ISSUE THREAD

**Issue by kdamaski** [neovide/neovide#1570]
i use the flag --neovim-bin to launch neovide with the lvim executable that i have (which has different configuration dir (\~/.config/lvim) and different runtime dir (\~/.local/share/lunarvim/) but the gui and my settings in lua managed to work when hitting the command under the \~/.config but not under every other directory (for example doesn't run under home dir). I cannot assume anything as neovide is not configurable by itself so i would appreciate some help if there is a quick(?) fix for that.

[Screencast from 29-09-2022 09:56:52 ΜΜ.webm](https://user-images.githubusercontent.com/64901487/193118993-a063a770-1afc-44fa-bec0-2e429e10e65d.webm)

**Comment by indika-dev** [comment]
I run neovide with lvim in the following way:
- lunarvim.lua in ~/.local/bin
> vim.fn.setenv("LUNARVIM_CONFIG_DIR", "/home/user/.config/lvim")
> vim.fn.setenv("LUNARVIM_RUNTIME_DIR", "/home/user/.local/share/lunarvim")
> vim.fn.setenv("LUNARVIM_CACHE_DIR", "/home/user/.cache/lvim")
>
> dofile("/home/user/.local/share/lunarvim/lvim/init.lua")

- commandline then for neovide `neovide --multigrid -- -u /home/stefan/.local/bin/lunarvim.lua`
  all things written after '--' are parameters for neovim

**Comment by kdamaski** [comment]
> I run neovide with lvim in the following way:
> 
>     * lunarvim.lua in ~/.local/bin
> 
> 
> > vim.fn.setenv("LUNARVIM_CONFIG_DIR", "/home/user/.config/lvim")
> > vim.fn.setenv("LUNARVIM_RUNTIME_DIR", "/home/user/.local/share/lunarvim")
> > vim.fn.setenv("LUNARVIM_CACHE_DIR", "/home/user/.cache/lvim")
> > dofile("/home/user/.local/share/lunarvim/lvim/init.lua")
> 
>     * commandline then for neovide `neovide --multigrid -- -u /home/user/.local/bin/lunarvim.lua`
>       all things written after '--' are parameters for neovim

Thanks for replying. Unfortunately this doesn't work for me. What version of lvim are you running though?

**Comment by indika-dev** [comment]
My version of lvim 1.1.4 (47e4e5b) and neovim 0.7.2
What error message do you get?

**Comment by kdamaski** [comment]
The problem is i get not error. The neovide now provides the flag --neovim-bin and the lvim i am running is a seperate executable from nvim ( no longer runs like an alias of nvim $args -- -u <config_file> ). I am not sure if that's the case though and will be very time consuming to figure that out so i made a script that firstly goes into ~/.config and then runs neovide with the given filename as arg (if there is one) in the previous directory like so:

#!/bin/bash

cur_dir=${PWD}
cd /home/user/.config; 

if [ -z $1 ] # no args given
then
	neovide --multigrid --neovim-bin lvim 
elif [ ${1:0:1} = "/" ] # first arg is an absolute path
then
	neovide --multigrid --neovim-bin lvim "$1"
else
	# neovide --multigrid --neovim-bin lvim "$cur_dir/$1"
	echo "oxi den einai $first_arg"
fi


Which works fine

**Comment by indika-dev** [comment]
if it's working for you, that will be great news! 
Nevertheless, I would check for lvim again, perhaps with a "file lvim", because lvim is not an executable like nvim but a shell script. I checked https://github.com/LunarVim/LunarVim/blob/master/utils/bin/lvim.template (this is the lvim installed by the installer) and it's still a shell script.

**Comment by kdamaski** [comment]
Oh, that's true. I should have noticed 😅.

**Comment by fredizzimo** [comment]
I think this fixes it https://github.com/neovide/neovide/pull/1946, at least it seems to work when I tested it, at least on Linux. Could someone else verify? 

Just start `neovide --neovim-bin lvim`

**Comment by kdamaski** [comment]
> if it's working for you, that will be great news! Nevertheless, I would check for lvim again, perhaps with a "file lvim", because lvim is not an executable like nvim but a shell script. I checked https://github.com/LunarVim/LunarVim/blob/master/utils/bin/lvim.template (this is the lvim installed by the installer) and it's still a shell script.

Lvim depends on its own runtime configuration to run and this aknowledgement that it's a script solved my issue back then. So when I checked lvim script I just had to change nvim with neovide and there you have the correct way to run lvim through neovide.
