### ISSUE TITLE
neovide reorders $PATH, which breaks LSP

### ISSUE THREAD

**Issue by nikhiljha** [neovide/neovide#1571]
**Describe the bug**

**To Reproduce**
1. Install neovide via Homebrew non-cask (`brew install neovide`). 
2. Enter a poetry environment (for example) (`poetry shell`)
3. `echo $PATH` and notice that `$HOME/Library/Caches/pypoetry/virtualenvs/example-py3.10/bin` is first
4. Launch neovide (`neovide` or `neovide --nofork`)
5. `:!echo $PATH` and notice that `$HOME/Library/Caches/pypoetry/virtualenvs/example-py3.10/bin` is not first
6. 😢 LSP is broken because it's using the wrong Python

**Expected behavior**
The `$PATH` does not get reordered when neovide starts.

**Desktop (please complete the following information):**
 - OS: [e.g. macOS 11.4] macOS 12.5.1
 - Neovide Version [e.g. 0.6.0] 0.10.1
 - Neovim Version [e.g. 0.5.0] 0.7.2

**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:** Unsure if applicable, but this doesn't look like what I want...

```
TRACE [neovide] Neovide version: 0.10.1
DEBUG [neovide::bridge::command] Running which command: "/bin/zsh" "-lc" "which nvim"
DEBUG [neovide::bridge::command] Starting neovim with: Command { std: "/bin/zsh" "-lc" "/opt/homebrew/bin/nvim --embed", kill_on_drop: false }
```

**Comment by fredizzimo** [comment]
I'm fairly sure that it does not re-order the path. But Neovide launches nvim in a non-interactive shell, so it will not run `zprofile` for example. This is the environment most gui applications run with, but terminal applications, like nvim are usually launched through an interactive shell, so from an usability standpoint it's not great.

For more discussions, see this https://github.com/neovide/neovide/issues/950, especially the last comment, and also my comments and diagram in the original MR https://github.com/neovide/neovide/pull/1118, that used an interactive login shell.

**Comment by aikow** [comment]
If you're using `fish` this is a problem with the subshell [here](https://github.com/fish-shell/fish-shell/issues/5456) and [here](https://github.com/LnL7/nix-darwin/issues/122).

**Comment by fredizzimo** [comment]
Closing this, due to no response from the author and the issue is very likely something other than Neovide.
