### ISSUE TITLE
Hide mouse cursor when neovide window is active

### ISSUE THREAD

**Issue by xbladesub** [neovide/neovide#1572]
Is it possible to hide mouse cursor while neovide window is focused?

**Comment by tombruijn** [comment]
It's not possible to hide the mouse as soon as the Neovide window gets focus.
It is possible to immediately hide it when typing is detected with the [neovide_hide_mouse_when_typing](https://neovide.dev/configuration.html#hiding-the-mouse-when-typing) config. The mouse will show again when it's moved.
