### ISSUE TITLE
Specify neovim config in source code

### ISSUE THREAD

**Issue by xbladesub** [neovide/neovide#1574]
I'm using lunarvim with neovide. Everything was fine so far. But recently I got a problems.

To run Neovide with lunarvim config I used the next shellscript:
```sh
#!/bin/bash
export LUNARVIM_RUNTIME_DIR="${LUNARVIM_RUNTIME_DIR:-"$HOME/.local/share/lunarvim"}"
export LUNARVIM_CONFIG_DIR="${LUNARVIM_CONFIG_DIR:-"$HOME/.config/lvim"}"
export LUNARVIM_CACHE_DIR="${LUNARVIM_CACHE_DIR:-"$HOME/.cache/lvim"}"

cd $HOME
exec /Users/nshv/Repos/neovide/target/release/neovide --frame=none --multigrid -- -u "$LUNARVIM_RUNTIME_DIR/lvim/init.lua" "$@"
```

I wrapped this shell script to an app instance through macOS Automator. However now it doesn't work correctly anymore. 

My question is - where in the source code should I specify path to neovim config (basically change it to lunarvim config) if possible? Would be really nice and I don't have to messing around with tons of shell/apple scripts

**Comment by xbladesub** [comment]
Fixed by changing the path to executable to bundled binary. However would be nice to have an option to do it in more easily way

**Comment by BlueFalconHD** [comment]
@xbladesub might you be able to share the change you made? I am having the same issue with LunarVim.

**Comment by xbladesub** [comment]
> @xbladesub might you be able to share the change you made? I am having the same issue with LunarVim.

Sorry for delayed reply. Next steps helped:
1. Build Neovide from source 
2. Make sure you also bundled it with ```cargo bundle``` (can see in Neovide's docs)
3. Provide correct path to executable which is inside hte macOS bundle. Here is my shell script which I use with ```skhd``` (key-binding tool). So I call this shell script wiht cmd+shift+1 and if Neovide process no running - it start the process, if it's running - it will just go to the app:

```sh
#!/bin/bash
SERVICE="Neovide"
if pgrep -f "$SERVICE" >/dev/null
then
	open /Users/nshv/Repos/neovide/target/release/bundle/osx/Neovide.app
else
	export LUNARVIM_RUNTIME_DIR="${LUNARVIM_RUNTIME_DIR:-"$HOME/.local/share/lunarvim"}"
	export LUNARVIM_CONFIG_DIR="${LUNARVIM_CONFIG_DIR:-"$HOME/.config/lvim"}"
	export LUNARVIM_CACHE_DIR="${LUNARVIM_CACHE_DIR:-"$HOME/.cache/lvim"}"

	cd $HOME

	exec /Users/nshv/Repos/neovide/target/release/bundle/osx/Neovide.app/Contents/MacOS/neovide --frame=none -- -u "$LUNARVIM_RUNTIME_DIR/lvim/init.lua" "$@"
	# exec /Users/nshv/Repos/neovide/target/release/bundle/osx/Neovide.app/Contents/MacOS/neovide --frame=none --multigrid -- -u "$LUNARVIM_RUNTIME_DIR/lvim/init.lua" "$@"
fi

```
