### ISSUE TITLE
Frame is being resized too late, causing rendering issues

### ISSUE THREAD

**Issue by musjj** [neovide/neovide#1576]
**Describe the bug**
Not sure what the correct vim terminology is, but I'm going to borrow the one from Emacs:
- Frame: The entire Neovide GUI window
- Window: The windows containing buffers that you can control from inside neovim

I have a function that loads a session near startup, but because of the timing that Neovide chooses to resize its frame cause issues when the session contains multiple windows.
Because the frame resizing happens way later, the window balance ended up being incorrect.
This is an illustration of what I *suspect* is happening:
```
┌────┬────┐      ┌─────┬──────────────┐
│    │    │ ───► │     │              │
│    │    │      │     │              │
└────┴────┘      │     │              │
                 │     │              │
                 │     │              │
                 │     │              │
                 │     │              │
                 └─────┴──────────────┘
```
If I *heavily* delay the session loading by doing something like:
```lua
vim.defer_fn(function() vim.cmd.source("/tmp/session/foo.vim") end, 5000)
```
This problem no longer occurs, which confirms my suspicion of what is causing this issue.
I have tried delaying the loading function via other ways (such as using the `VimEnter` autocmd), but none of it works.

Right now my hacky solution is to run Neovide with a `--geometry` argument that is the near-equivalent to a maximized window resolution in my monitor. I guess that `--geometry` runs very early, which is why the problem above doesn't occur.

**To Reproduce**
1. Run neovim and create multiple windows.
2. Save it to a session: `:mksession /tmp/session.vim`.
3. Run nvim with that session: `nvim -c "source /tmp/session.vim"`

**Expected behavior**
The balance of the window sizes should not get distorted, even if they're created during nvim startup.

**Desktop (please complete the following information):**
 - OS: Microsoft Windows [Version 10.0.19043.2006]
 - Neovide Version: 0.9.0
 - Neovim Version: v0.8.0-dev-1120-ga0e6e767a

**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**
[neovide_rCURRENT.log](https://github.com/neovide/neovide/files/9690945/neovide_rCURRENT.log)

**Comment by aj3423** [comment]
Do you have *sessionoptions* `resize` enabled? I have same problem until I removed that option:
https://github.com/neovide/neovide/issues/1518#issuecomment-1266794633

**Comment by musjj** [comment]
Thanks, that solution works well for me and is a bit cleaner than hardcoding `--geometry`

**Comment by musjj** [comment]
I don't have `resize` set in my `sessionoptions`. My `sessionoptions`:
`blank,buffers,folds,help,tabpages,winsize,terminal`
Have you tried saving a session with multiple splits and loading the session right at startup? (something like `nvim -c "source /tmp/session.vim"`). For additional context, I run neovide with `--maximized`.

**Comment by aj3423** [comment]
Yes, my buffer layout is saved/restored at exit/startup, I'm not doing it manually by `source` command, I'm using the [rmagatti/auto-session](https://github.com/rmagatti/auto-session) plugin, but it should be the same. 

In my case, the window manager remembers the window size of last closed Neovide, and tries to resize any new Neovide to that size. If I do:
1. launch Neovide A, resize it to a small size like 400*300, close it
2. launch Neovide B, maximize it, close it
3. launch A again, the window is maximized because last closed B is maximized, but then the saved sessionoptions resizes the buffer to 400*300, which causes the problem.

I'm on Linux, maybe it behaves different on Windows. Try to disable these switches, the `winsize` looks suspicious to me, and the `--maximized`.

Since the *sessionoptions* is saved last time you close the window, it won't take effect at the next launch if you modified it, make sure launch->close->launch again to see if it works.

**Comment by musjj** [comment]
Right, I'm can't get Windows to remember my window size for some reason, so I use `--maximized` since I usually work fullscreen.
Googling around, it seems that Windows should remember the window size if I hold shift while pressing the close button, but it didn't work for Neovide.
Tried removing `winsize`, but it didn't do anything.
I tried removing the `--maximized`, then doing something like `neovide -- -c "source /tmp/session.vim"`, and it results into the default non-maximized window size.
When I manually maximize that window, it ended up having the exact kind of distorted layout that I get when I use `--maximized`, which confirms that Neovide is resizing the window size too late.
Btw, do you have `neovide_remember_window_size` or `neovide_remember_window_position` set?

**Comment by aj3423** [comment]
Never heard of these two variables. Windows is always the tough part..

**Comment by Kethku** [comment]
I thiiiink this is fixed in current main. Please reopen if issues continue
