### ISSUE TITLE
terminal_color hex values are interpreted wrong

### ISSUE THREAD

**Issue by kdamaski** [neovide/neovide#1579]
i copied and pasted my gnome-terminal hex values (e.g. #ffffff 6 hex digits) into the g:terminal_color (1 to 15). The colors changed but they were different from my terminal's. The only colors that look similar are the ones with no character values (a-f) regardless of capital letters or not.

**Comment by MultisampledNight** [comment]
Thanks for reporting! Could you try to run Neovide with `--nosrgb` and see how the behavior changes?
