### ISSUE TITLE
CLI does not start at all

### ISSUE THREAD

**Issue by chrisgrieser** [neovide/neovide#1582]
**Describe the bug**
the neovide CLI does not start at all. Neither with arguments nor without arguments does anything happen.

**Expected behavior**
the cli should start

**Desktop (please complete the following information):**
- macOS 12.5.1
- neovim 0.8
- neovide 0.10.1

```
TRACE [neovide] Neovide version: 0.10.1
DEBUG [neovide::bridge::command] Running which command: "/bin/zsh" "-lc" "which nvim"
DEBUG [neovide::bridge::command] Starting neovim with: Command { std: "/bin/zsh" "-lc" "\x1b[H\x1b[2J ___________________________________________________________________ \n( bit, n:                                                           )\n(                                                                   )\n( A unit of measure applied to color. Twenty-four-bit color         )\n(                                                                   )\n( refers to expensive $3 color as opposed to the cheaper 25         )\n(                                                                   )\n( cent, or two-bit, color that use to be available a few years ago. )\n ------------------------------------------------------------------- \n        o   ^__^\n         o  (--)\\_______\n            (__)\\       )\\/\\\n                ||----w |\n                ||     ||\n\nneovide_r2022-10-03_19-26-48.log\nneovide_rCURRENT.log\n\n/opt/homebrew/bin//nvim --embed", kill_on_drop: false }
DEBUG [neovide::settings::window_geometry] Loaded window settings: Windowed { position: PhysicalPosition { x: 0, y: 0 }, size: Dimensions { width: 100, height: 50 } }
ERROR [neovide::bridge] Neovide requires nvim version 0.4 or higher. Download the latest version here https://github.com/neovim/neovim/wiki/Installing-Neovim
```

even though the log says that nvim must be installed, it already is installed, at version 0.8, and in the PATH:
<img width="1557" alt="Pasted image 2022-10-03 19 28 34" src="https://user-images.githubusercontent.com/73286100/193640886-7db06d89-fe08-41c9-8286-f16c82c1506b.png">

**Additional context**
M1 Mac, installed neovide via homebrew. Tried both, with and without the formula.

**Comment by MultisampledNight** [comment]
Thanks for reporting! Looking at your fancy shell, is it possible it emits something in its startup sequence? Like `neofetch` or similar?

**Comment by chrisgrieser** [comment]
I have `fortune` and `cowsay` in my `.zlogin`; commenting it all out indeed fixed the issue.
well, that was a very good guess! 😂  

Any way I can use the neovide CLI while keeping things in `.zlogin`?

**Comment by fredizzimo** [comment]
You probably don't want to run fortune and cosway from zlogin. Zlogin is run only for login shells, which are not necessarily interactive, which means that they don't have a terminal windows attached.

Instead you should put that in .zshrc, which is for interactive shells, see https://unix.stackexchange.com/questions/71253/what-should-shouldnt-go-in-zshenv-zshrc-zlogin-zprofile-zlogout. If you wish to run it only for interactive login shells, you can do an if check 
```bash
if [[ -o login ]]; then
echo "Do stuff"
fi
```
Or alternatively you can keep it in zlogin, and check for `-o interactive`

**Comment by chrisgrieser** [comment]
huh, thank you, I already knew that `zlogin` is for the login shell, but I naively assumed that "login shell" meant "interactive session" 🙈

Maybe the info that `.zlogin` should not produce more output should go to the docs in the FAQ or the troubleshooting section? Otherwise, I guess this issue can be closed.
