### ISSUE TITLE
alpha-nvim plugin UI broken on neovide startup

### ISSUE THREAD

**Issue by xbladesub** [neovide/neovide#1587]
It happens only when multigrid is disabled. Tried different alpha settings - same. 
I use lunrvim, not sure if the problem is related to lunarvim code.

This line goes away when another buffer or floating window opens (nvim-tree or telescope). It's not a big deal but quite annoying when I open neovide

<img width="1495" alt="Screen Shot 2022-10-05 at 9 44 26 AM" src="https://user-images.githubusercontent.com/45129790/193970556-33ad06a5-165b-443f-9836-c86fe3ad624b.png">

**Comment by AbbasSrour** [comment]
Are you sure its neovide related? I have both lunarvim and nvim configs with both multigrid and without, and this is not happening. I suggest using stable release (if you are not using it) on lunar since the rolling release was quite buggy that past week or so.

**Comment by MultisampledNight** [comment]
Thanks for reporting! This is the same issue as #1387, I think.
