### ISSUE TITLE
version `GLIBC_2.27' not found with latest release

### ISSUE THREAD

**Issue by vignesh0025** [neovide/neovide#1592]
**Describe the bug**
Latest release is in-compatible with older version of linux

**To Reproduce**
Start the application in ubuntu 14.04.

**Expected behavior**
Application runs

**Screenshots**
./neovide: /lib64/libm.so.6: version `GLIBC_2.27' not found (required by ./neovide)
./neovide: /lib64/libm.so.6: version `GLIBC_2.29' not found (required by ./neovide)
./neovide: /lib64/libc.so.6: version `GLIBC_2.28' not found (required by ./neovide)
./neovide: /lib64/libc.so.6: version `GLIBC_2.25' not found (required by ./neovide)
./neovide: /lib64/libc.so.6: version `GLIBC_2.29' not found (required by ./neovide)

**Desktop (please complete the following information):**
 - Ubuntu 14.04 (LTS)

**Comment by Suyashtnt** [comment]
Old versions of ubuntu do not have a recent enough version of libc to support neovide, its time to upgrade to the latest LTS by now.

**Comment by MultisampledNight** [comment]
Thanks for reporting! I'm not really sure if we can handle supporting a distro which has been EOL for 3 years now, probably glibc being out of date is just the start of it.

You may be able to build from source though.

**Comment by vignesh0025** [comment]
Thank you for the reply...



> Old versions of ubuntu do not have a recent enough version of libc to support neovide, its time to upgrade to the latest LTS by now.

Its not my personal system and so its impossible to upgrade the OS. In my personal laptop, I have no issues in using Neovide.

  



> Thanks for reporting! I'm not really sure if we can handle supporting a distro which has been EOL for 3 years now, probably glibc being out of date is just the start of a long chain of dependency errors.
> 
> You may be able to build from source though.

I did try to build it from source in older version of ubuntu.. but it fails with some "undefined references" which I suspect should come from more latest version of GLIBC. :-(

**Comment by chipbuster** [comment]
I've spent a little time trying to build neovide under musl, but it seems that no matter what I try, the building of the skia bindings fails, no matter whether I try to cross-compile directly, use cross-rs, or use the custom docker container provided by the rust-skia project.

I saw a discussion on #437 that implies that neovide is expected to build under musl. Is that still the case? If so, I might be able to spend a few hours this weekend to get a working musl build.

**Comment by vignesh0025** [comment]
@chipbuster Hi, I spent almost one full day trying to build neovide with Ubuntu 15.04 as well as with Musl and all other possible old distros and it ended up always as a failure. So, the answer is "No, latest version of Neovide has no compatibility with older versions of glibc". Don't spent time on it.
