### ISSUE TITLE
`nvim` process remains, even after quitting Neovide.

### ISSUE THREAD

**Issue by chrisgrieser** [neovide/neovide#1596]
**Describe the bug**
When quitting Neovide, it seems that sometimes the corresponding `nvim` process isn't terminated. After a while, this leads to a bunch of nvim processes runningm, even though I have no running instance of neovide. And those nvim processes still take up RAM (which is how I noticed this.)
<img width="917" alt="Pasted image 2022-10-12 15 06 54" src="https://user-images.githubusercontent.com/73286100/195353578-9a38c932-bfbf-450f-a429-4f2359fb95b8.png">

**To Reproduce**
Not sure how to reproduce this, I only notice `nvim` processes piling up after a while, but when opening and quitting Neovide, the number of processes don't always increase.

**Expected behavior**
When quitting neovide, nvim processes should be terminated as well.

**Desktop (please complete the following information):**
```
macOS 12.5.1 (M1)
neovim 0.8.0 (homebrew)
Neovide 0.10.1 (homebrew)
```

**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**
[neovide_rCURRENT 15.15.27.log](https://github.com/neovide/neovide/files/9765180/neovide_rCURRENT.15.15.27.log)

**Additional context**
I am mostly starting neovide via the cli, not the .app if that is relevant?

**Comment by MultisampledNight** [comment]
Thanks for reporting! I guess you accidentally duplicated the issue? See #1595.

**Comment by chrisgrieser** [comment]
ah yes, indeed.

After I send the first one, I got a weird error and rewrote the whole thing, apparently not noticing that it worked 😓 

Closing this in favor of the earlier one
