### ISSUE TITLE
Font size gets too big after switching from Monitor to Laptop screen

### ISSUE THREAD

**Issue by runitmisra** [neovide/neovide#1597]
**Describe the bug**
I usually hook up my laptop to an external monitor, but sometimes I like to work on the laptop screen itself. The font scaling/size (not sure what to call it exactly I'm very new to this) on the monitor is okay, but when I switch to the Laptop screen, the font is very large. I have found some answers here to set some keybindings to change the scaling, but shouldn't it work out of the box? I have used goneovim and nvim-qt and they work just fine, I just LOVE neovide though except for this behavior. Fantastic work otherwise guys!

**To Reproduce**
1. Open neovide in a monitor screen with a bigger size (but same resolution as the laptop screen)
2. Disconnect the monitor
3. Open neovide on laptop screen
4. See HUGE font

**Expected behavior**
The font scaling should adapt to the screen size automatically.

**Screenshots**
![image](https://user-images.githubusercontent.com/32189847/195827342-a0697530-224a-4896-a6f7-2e02d3efbb0e.png)
opened calendar popup for reference

**Desktop (please complete the following information):**
 - OS: KDE Neon 5.26
 - Neovide Version: 0.10.1
 - Neovim Version: NVIM v0.9.0-dev-9207ad5

**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**

**Additional context**

**Comment by runitmisra** [comment]
Update:
`g:neovide_scale_factor=1.0` works good on my Monitor,
`g:neovide_scale_factor=0.5` works good on my laptop

But I have to change between them every time I connect/disconnect from my monitor. I can make a small script in my init.lua that checks if I am connected to my monitor or not using xrandr, but not only is that a hacky way, I also have to source my init file manually.

**Comment by MultisampledNight** [comment]
Thanks for reporting!

It looks like your laptop is a HiDPI display and xrandr marks it as a scale=2 display. Can you confirm that? If that's the case, you should be able to use arandr/xrandr to configure your laptop to have a scale of 1.

Neovide just respects whatever the OS (through winit) tells it about the scale. As a last resort, you can override the scale factor through the `WINIT_X11_SCALE_FACTOR` environment variable, though you should really consider making the system xrandr has the same one as you'd seriously like.

**Comment by runitmisra** [comment]
Thanks @MultisampledNight the env variable worked. Not sure about the xrandr stuff though, I'll have to look more into it. For now it's a fix.

**Comment by Kethku** [comment]
Closing as I believe Multi's recommendation is correct.
