### ISSUE TITLE
Neovide not working with poetry environment

### ISSUE THREAD

**Issue by topsideduck** [neovide/neovide#1599]
**Describe the bug**
Neovide does not use the updated $PATH (lsp throws 'module could not be resolved' error) after activating poetry virtual environment (using lunarvim). Imports are resolved on normal neovim instance.

**To Reproduce**
Steps to reproduce the behaviour:
1. Create new poetry environment with `poetry init`
2. Activate virtual environment with `poetry shell`
3. Install a module/package (eg: requests) using poetry add (eg: `poetry add requests`)
4. Start neovide using the command line `neovide`
5. Create a new python file and enter `import requests`
6. Pyright throws `Import "requests" could not be resolved.`

**Expected behavior**
Imports should work normally and be recognised.

**Screenshots**
![Neovim Instance](https://user-images.githubusercontent.com/63719951/195999180-b9a9fe2e-1f1e-40bd-b581-785e35dcbd02.png)
![Neovide Instance](https://user-images.githubusercontent.com/63719951/195999207-250f9683-a094-4c1f-91aa-d2f730ff4249.png)

**Desktop (please complete the following information):**
 - OS: macOS 12.5
 - Neovide 0.10.1
 - Neovim Version v0.8.0

**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**
[neovide_rCURRENT.log](https://github.com/neovide/neovide/files/9792687/neovide_rCURRENT.log)
[neovide_r2022-10-15_22-40-54.log](https://github.com/neovide/neovide/files/9792686/neovide_r2022-10-15_22-40-54.log)

**Comment by pspiagicw** [comment]
Pyright is being started from global environment. Not the poetry virtual environment. Uninstall your system pyright and then install through poetry. 

This should resolve your issue. I had the same problems with conda environments.

**Comment by ad-chaos** [comment]
System Packages should not be affected by being in a virtual environment.
Also I am unable to reproduce the issue using your steps.
Try running `which pyright` in both neovide (using `:term`) and in the terminal and see if you get the same result.

**Comment by topsideduck** [comment]
I have installed pyright using mason.nvim.
`which pyright` returns `/Users/user/.local/share/nvim/mason/bin/pyright` in both neovide and terminal.
My neovide startup script is using lunarvim's startup but `nvim` replaced with `neovide`.

Neovide lunarvim startup script:
`#!/bin/sh

export LUNARVIM_RUNTIME_DIR="${LUNARVIM_RUNTIME_DIR:-"/Users/hari/.local/share/lunarvim"}"
export LUNARVIM_CONFIG_DIR="${LUNARVIM_CONFIG_DIR:-"/Users/hari/.config/lvim"}"
export LUNARVIM_CACHE_DIR="${LUNARVIM_CACHE_DIR:-"/Users/hari/.cache/lvim"}"

exec neovide --multigrid --maximized -- -u "$LUNARVIM_RUNTIME_DIR/lvim/init.lua" "$@"`

**Comment by topsideduck** [comment]
I have installed pyright using mason.nvim.
which pyright returns /Users/user/.local/share/nvim/mason/bin/pyright in both neovide and terminal.
My neovide startup script is using lunarvim's startup but nvim replaced with neovide.

Neovide lunarvim startup script:
`
#!/bin/sh

export LUNARVIM_RUNTIME_DIR="${LUNARVIM_RUNTIME_DIR:-"/Users/hari/.local/share/lunarvim"}"
export LUNARVIM_CONFIG_DIR="${LUNARVIM_CONFIG_DIR:-"/Users/hari/.config/lvim"}"
export LUNARVIM_CACHE_DIR="${LUNARVIM_CACHE_DIR:-"/Users/hari/.cache/lvim"}"

exec neovide --multigrid --maximized -- -u "$LUNARVIM_RUNTIME_DIR/lvim/init.lua" "$@" `

**Comment by topsideduck** [comment]
I have installed pyright using mason.nvim.
which pyright returns /Users/hari/.local/share/nvim/mason/bin/pyright in both neovide and terminal.
My neovide startup script is using lunarvim's startup but nvim replaced with neovide.

Neovide lunarvim startup script:
`#!/bin/sh

export LUNARVIM_RUNTIME_DIR="${LUNARVIM_RUNTIME_DIR:-"/Users/hari/.local/share/lunarvim"}"
export LUNARVIM_CONFIG_DIR="${LUNARVIM_CONFIG_DIR:-"/Users/hari/.config/lvim"}"
export LUNARVIM_CACHE_DIR="${LUNARVIM_CACHE_DIR:-"/Users/hari/.cache/lvim"}"

exec neovide --multigrid --maximized -- -u "$LUNARVIM_RUNTIME_DIR/lvim/init.lua" "$@"`

**Comment by topsideduck** [comment]
i just found that that `echo $PATH` on neovide `:term` results in this
`/Users/hari/.local/share/nvim/mason/bin:/Users/hari/.local/bin:/Users/hari/.local/share/nvim/mason/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet:~/.dotnet/tools:/Users/hari/.virtualenvs/turing-bot-updated-ty17Q-qm-py3.10/bin:/Users/hari/.local/share/nvim/mason/bin:/Users/hari/.local/bin:/usr/local/sbin:/Users/hari/Developer/Evergreen/.venv/bin:/Users/hari/.pyenv/shims:/Users/hari/.car go/bin:/usr/local/bin`

The virtualenv python3 at `/Users/hari/.virtualenvs/turing-bot-updated-ty17Q-qm-py3.10/bin` is being overwritten by the system python3 at `/usr/local/bin/python3`. This happens only on neovide, and not on the terminal nvim. Is there any way to fix this?

**Comment by ad-chaos** [comment]
Why is your virtual-environment in PATH?
That seems wrong, did you put it there?

**Comment by topsideduck** [comment]
No, i used `poetry shell` to activate the virtual environment.

**Comment by pspiagicw** [comment]
> I have installed pyright using mason.nvim.
> which pyright returns /Users/hari/.local/share/nvim/mason/bin/pyright in both neovide and terminal.



This shows Pyright is installed in a global environment, albeit through Mason. Can you try removing your Mason install of Pyright and install pyright through poetry ?

**Comment by ad-chaos** [comment]
Oh ok, so the output is from `poetry shell`

You can try setting the `venvPath` and `venv` attributes under `tool.pyright` in your `pyproject.toml`
Doing that worked for me, you could try something along the lines of the following script.

```zsh
% poetry_env=$(env | \grep "VIRTUAL_ENV" | sed "s/VIRTUAL_ENV=//")
% lines=( '\n' '[tool.pyright]' "venvPath=`dirname $poetry_env`" "venv=`basename $poetry_env`")
% for line in "$lines[@]"; do echo $line >> pyproject.toml; done
```

**Comment by topsideduck** [comment]
> > I have installed pyright using mason.nvim.
> > which pyright returns /Users/hari/.local/share/nvim/mason/bin/pyright in both neovide and terminal.
> 
> This shows Pyright is installed in a global environment, albeit through Mason. Can you try removing your Mason install of Pyright and install pyright through poetry ?

> Oh ok, so the output is from `poetry shell`
> 
> You can try setting the `venvPath` and `venv` attributes under `tool.pyright` in your `pyproject.toml` You can read more about them [here](https://github.com/microsoft/pyright/blob/main/docs/configuration.md#main-pyright-config-options). Doing that worked for me, you could try something along the lines of the following script from your poetry shell.
> 
> ```shell
> % poetry_env=$(env | \grep "VIRTUAL_ENV" | sed "s/VIRTUAL_ENV=//")
> % lines=( '\n' '[tool.pyright]' "venvPath=`dirname $poetry_env`" "venv=`basename $poetry_env`")
> % for line in "$lines[@]"; do echo $line >> pyproject.toml; done
> ```

I followed both your suggestions, and the issue is fixed! Thank you both for your help!
Is there a permanent fix, or do i have to install pyright in every virtual environment and add the `[tool.poetry]` to every `pyproject.toml` in every project i create?

**Comment by ad-chaos** [comment]
I don't think installing pyright through poetry is needed if you are going to set those keys in your, `pyproject.toml`.

Ss for having to set them in every project, you can try running `poetry config virtualenvs.in-project true` which will create the `venv` in your project root and pyright will pick that up.

**Comment by topsideduck** [comment]
Okay, that works for me. Thank you so much for your help!

**Comment by BSiddharth** [comment]
@topsideduck @ad-chaos 
I am using neovim and installed pyright using mason. I created an env using poetry but cannot make pyright use the venv. 
```toml
[tool.pyright]
venvPath = "C:/Users/usernname/AppData/Local/pypoetry/Cache/virtualenvs"
venv = "api-ascah5cj-py3.11"
```
This is my `pyproject.toml` file. What am I doing wrong?

**Comment by bryan-lott** [comment]
FWIW, this fixed the issue for me, at least with pyright.

`pyrightconfig.json` in the root of the project. My virtual environments are auto-activated with `mise` and are set to create a `.venv` virtual environment folder.

```json
{
  "venvPath": ".",
  "venv": ".venv"
}
```
