### ISSUE TITLE
Neovide crashing in multigrid mode when getting long autocompletion menu

### ISSUE THREAD

**Issue by DarkStar1997** [neovide/neovide#1600]
**Describe the bug**
I noticed that sometimes when faced with a long autocompletion menu, neovide crashes.

**To Reproduce**
1. Open a file and generate a long autocompletion menu towards the end of the window. In my case it was with a cpp file and a long list of completions generated by nvim-cmp.

**Expected behavior**
Not crash and work normally.

**Screenshots**
The following is a screenshot without multigrid flag just at the point of crashing.
![image](https://user-images.githubusercontent.com/28505425/196002379-3f068189-9696-4c52-82a4-8a1c0907ea11.png)

**Desktop (please complete the following information):**
 - OS: [Arch Linux]
 - Neovide Version [0.10.1]
 - Neovim Version [0.8.0]

**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**
[neovide_rCURRENT.log](https://github.com/neovide/neovide/files/9792839/neovide_rCURRENT.log)

**Additional context**

**Comment by MultisampledNight** [comment]
Thanks for reporting!

By chance, could you run Neovide with `--nofork` added to multigrid and see what the console output is? Does it segfault? Does it panic? If it segfaults, it'd be really cool to have a backtrace (made by `coredumpctl debug` after a crash, then `bt`).

**Comment by DarkStar1997** [comment]
It's indeed a panic. `coredumpctl debug` couldn't display any information. I did get this with the RUST_BACKTRACE flag:
```
❯ RUST_BACKTRACE=full neovide --nofork --multigrid .
thread 'main' panicked at 'Could not create surface', src/renderer/rendered_window.rs:75:6
stack backtrace:
   0:     0x55a1244bafe1 - <unknown>
   1:     0x55a1243bc48c - <unknown>
   2:     0x55a124490124 - <unknown>
   3:     0x55a1244bc156 - <unknown>
   4:     0x55a1244bd1e7 - <unknown>
   5:     0x55a1244bccc2 - <unknown>
   6:     0x55a1244bcc36 - <unknown>
   7:     0x55a1244bcbf2 - <unknown>
   8:     0x55a124275d22 - <unknown>
   9:     0x55a1243c0cd0 - <unknown>
  10:     0x55a1243c0c7b - <unknown>
  11:     0x55a124275e96 - <unknown>
  12:     0x55a12432293c - <unknown>
  13:     0x55a124368233 - <unknown>
  14:     0x55a1242a6bd7 - <unknown>
  15:     0x55a124304497 - <unknown>
  16:     0x55a124320de8 - <unknown>
  17:     0x55a124304139 - <unknown>
  18:     0x55a1242ad9fc - <unknown>
  19:     0x55a1242ac736 - <unknown>
  20:     0x55a12428c36c - <unknown>
  21:     0x55a1242e14a3 - <unknown>
  22:     0x55a12428b566 - <unknown>
  23:     0x7f9f75c85290 - <unknown>
  24:     0x7f9f75c8534a - __libc_start_main
  25:     0x55a1242861c5 - <unknown>
  26:                0x0 - <unknown>
```

Is this information helpful? I'll be happy to do everything needful to fix this issue. I installed neovide from the Arch repositories.
Do you want me to build neovide from source, build it in debug mode and then grab a backtrace?

**Comment by fredizzimo** [comment]
I'm not sure if this deserves its own issue, since we have a more generic one for multigrid and Neovim 0.8.0 https://github.com/neovide/neovide/issues/1584 but leaving it open until it's fixed. The multigrid support seems to be almost completely broken with 0.8

**Comment by ryo33** [comment]
I have the same error with neovide@0.11.2

**Comment by fredizzimo** [comment]
The crash is probably becuase it's trying allocate a too large texture. That is fixed in https://github.com/neovide/neovide/pull/1977

**Comment by Kethku** [comment]
Closing as fixed
