### ISSUE TITLE
Set webpage in the about section

### ISSUE THREAD

**Issue by anachronic** [neovide/neovide#1601]
**Is your feature request related to a problem? Please describe.**
No problem whatsoever, it just makes it easier to get to documentation

**Describe the solution you'd like**
Add the webpage in the about section in the repo page like so:

![image](https://user-images.githubusercontent.com/3452930/196048482-9bf695a9-c4aa-487e-969d-b3c90b4e37fe.png)

**Additional context**
Not much to say, but I think it can be useful if looking for a quick link to the main page

**Comment by MultisampledNight** [comment]
Indeed. Thank you!
