### ISSUE TITLE
Functional bug: cannot paste from system clipboard to command mode without external mouse

### ISSUE THREAD

**Issue by bmulholland** [neovide/neovide#1602]
**Describe the bug**

I don't know if this is a bug in the Neovide codebase per se, but it is a user problem that I have only while using Neovide: I need to paste to command mode. When using nvim in a terminal, the terminal's clipboard integration means I don't have this problem; I just Cmd-V.  AFAICT, the Vim solution is to use Ctrl-R ". This doesn't work; it only pastes the last thing I copied in Vim. It doesn't seem to read from the system clipboard at all. Ctrl-R " does the same thing in nvim in a terminal, so that's not Neovide specific. But I still need some working solution here.

What does work is clicking the middle mouse button, but 1. that means reaching for my mouse, something I use Vim to avoid, and 2. is only possible when I'm using an external mouse; the mac trackpads don't have a middle click (not even an alt-click alternative).

Specifically, I have a common workflow where I have a file in a PR that I'm reviewing, and I want to look at the full file. So I copy the full path from Github, and then I want to do `:e <paste filename>`.

I know a full clipboard integration is [off the table](https://github.com/neovide/neovide/issues/113#issuecomment-1030660477). I do have `set clipboard+=unnamedplus` set.

**To Reproduce**
1. Open Neovide
2. Copy text from e.g. a browser with Cmd-C
3. Open command mode with `:`
4. Try to paste with Cmd-V, Ctrl-R ", or anything else. None of them work.
5. Paste with middle click, if you have one. Note that works.
6. Try yanking from text in vim, then opening command mode. Try Ctrl-R ", note that pastes the yanked text. Middle-click, too.

**Desktop (please complete the following information):**
 - OS: macOS 12.6
 - Neovide Version 0.10.1
 - Neovim Version v0.8.0

Happy to share a Neovide log if it would help, just let me know what to do.

**Comment by xiaochuanyu** [comment]
I'm on same OSX/nvim/neovide versions.
For step 3/4, `<c-r>*` seem to work for me.

https://user-images.githubusercontent.com/1718745/197398075-182ddc03-4f89-48c4-a812-c5b1a8cece10.mov

**Comment by bmulholland** [comment]
Ctrl-R * does work. Fantastic!

How did you figure that out?

**Comment by xiaochuanyu** [comment]
I got it from `:h clipboard-tool` (excerpt):
>  *clipboard-tool*
> The presence of a working clipboard tool implicitly enables the '+' and '*'
> registers. Nvim looks for these clipboard tools, in order of priority:
> 
>   - |g:clipboard|
>   - pbcopy, pbpaste (macOS)
>  ...

My understanding is:
* When you `<c-r>` with `+` or `*` then neovim uses `pbpaste` to read from OSX clipboard. When you yank into `+`/`*` it would use `pbcopy` to write into OSX clipboard.
* If you have `set clipboard+=unnamedplus` then yanking and pasting will use `+`/`*` by default. Otherwise you'd have to for example do `"+yy` to copy a line into clipboard via `+` instead of just `yy`.

Also, if you look at `:h provider-paste`, it implies mouse middle click on OSX actually bypasses `pbpaste`. Neovim gets a dump of text that it will try to insert after cursor.

**Comment by falcucci** [comment]
I am closing this in favor of `<C-r>` solution.

speaking about my own way of making it work is using

```lua
vim.keymap.set("c", "<D-v>", "<C-r>+")                                          -- paste (command)
```

@bmulholland reach out if it persists somehow
