### ISSUE TITLE
How to specify font weight?

### ISSUE THREAD

**Issue by xbladesub** [neovide/neovide#1607]
I'm trying to specify font weight, but it doesn't work some reason. Am I doing something wrong?
It works if I specify font family, but in this case it uses 'regular' font and not 'ExtraLight' which I want:
```lua
vim.o.guifont = "JetBrainsMono_Nerd_Font:h12"
```

I can delete all weights except 'ExtraLight' but it's not the best solution I guess.

Also I tried to specify exact font name, which doesn't work - font not being recognized:
```lua
vim.o.guifont = "JetBrains_Mono_ExtraLight_Nerd_Font_Complete:h12"
```
Any ideas how to use exact font weight?

**Comment by ayush-seth** [comment]
I  have this exact issue

**Comment by fredizzimo** [comment]
Font weight support was added by
* https://github.com/neovide/neovide/pull/2246
