### ISSUE TITLE
How to change cursor color for normal mode?

### ISSUE THREAD

**Issue by xbladesub** [neovide/neovide#1611]
I have tried many options but none of them work some reason for Neovide. (Works if I use Alacritty or other terminals with my config)

**Comment by MultisampledNight** [comment]
Thanks for asking!

This seems to be currently implicitly controlled through the `Normal` highlight, which also controls the color non-syntax-colored text uses.

**Comment by xbladesub** [comment]
> Thanks for asking!
> 
> This seems to be currently implicitly controlled through the `Normal` highlight, which also controls the color non-syntax-colored text uses.

so is it possible to change?

**Comment by MultisampledNight** [comment]
Yeah, through the `Normal` highlight, for example:

```vim
highlight! Normal guifg=#00FFFF
```

which would color the text and the cursor cyan.

**Comment by xbladesub** [comment]
> Yeah, through the `Normal` highlight, for example:
> 
> ```viml
> highlight! Normal guifg=#00FFFF
> ```
> 
> which would color the text and the cursor cyan.

thanks, it works
