### ISSUE TITLE
pass stdin to nvim

### ISSUE THREAD

**Issue by Madoshakalaka** [neovide/neovide#1619]
**Is your feature request related to a problem? Please describe.**
nvim can write stdin to a buffer so both the following works:
`echo loremipsum | nvim`
and
`nvim /tmp/loremipsum.txt`

neovide, however, only supports the latter. The first works but neovide simply ignores stdin.

**Additional context**
was trying to use neovide as a replacement for the `less` reader, but had to do this workaround in my shell resource file:

```sh
# /etc/zsh/zshrc
less () {
	# neovide has skill issue: it doesn't read from stdin
	if [ $# -eq 0 ]
	then
		tmp=$(mktemp)
		cat - > ${tmp}
		neovide --nofork ${tmp} -- -R
		rm -f ${tmp}

	else
		neovide ${1} -- -R
	fi
}
```

**Comment by MultisampledNight** [comment]
@williamspatrick For what it's worth, in script usage like you seem to do in a Python script, creating a temporary file and opening it might just do the job as well. Not ideal, but okay-ish, I've got this function in my shell resource file to open the output of `cargo expand` in Neovide:

```sh
ce() {
	output=$(mktemp)
	cargo expand --color never $@ >$output
	neovide -R "+set ft=rust" $output
}
```

**Comment by MultisampledNight** [comment]
Closing in favor of https://github.com/neovide/neovide/issues/1865.
