### ISSUE TITLE
Ctrl keyup is ignored at startup

### ISSUE THREAD

**Issue by Madoshakalaka** [neovide/neovide#1621]
**Describe the bug**
when opened from terminal with the ctrl key held. Neovide will keep thinking the ctrl key is held

**To Reproduce**

On a terminal, do the following
1. type `neovide`
2. hold <kbd>ctrl</kbd>, press and release <kbd>j</kbd>. (this works as as the carriage return key in many programs, at least on zsh). Neovide opens and becomes focused.
3. release <kbd>ctrl</kbd>.
4. Neovide still thinks the <kbd>ctrl</kbd> key is held. For example, hit <kbd>o</kbd> and neovim will try to jump back to the last buffer.

**Expected behavior**
Properly receive the keyup event.

**Desktop (please complete the following information):**
 - OS: I use Arch btw. Kernel 6.0.6-arch1-1
 - Shell: zsh 5.9 
 - Desktop: gnome
 - Neovide Version 0.10.1
 - Neovim Version 0.8.0

**Comment by Madoshakalaka** [comment]
same happens with the super key. I'm using gnome, where `super` + `arrow up` maximizes the window. Say I'm using neovide and I press `super` + `arrow up` to maximize the window. Neovide will keep thinking that the `super` key is held down. A way to fix is to press and release super key again. It can be very confusing to the user as suddenly every key doesn't work.

**Comment by thiru** [comment]
I have the same issue on Arch.  The latest Neovide doesn't help - but actually adds more regressions mentioned in other issues.

**Comment by thiru** [comment]
I guess this is essentially the same issue:
https://github.com/neovide/neovide/issues/1631

**Comment by TpouHuK** [comment]
> I have the same issue on Arch. The latest Neovide doesn't help - but actually adds more regressions mentioned in other issues.

Same issue, neovide does not register KeyUp event if KeyUp event happens too fast or window goes out of focus during keydown. **Switching from X11 to Wayland fixed the issue for me.**
Fedora 37; neovide 0.10.3

**Comment by fredizzimo** [comment]
https://github.com/neovide/neovide/pull/1789 is now merged to master, and #1631 was already confirming with that. So closing this one as well. But if not, please report, and I will re-open.
