### ISSUE TITLE
Window title bar should also append active buffer name

### ISSUE THREAD

**Issue by kskarthik** [neovide/neovide#1625]
**Is your feature request related to a problem? Please describe.**

When opening multiple windows of neovide for different buffers, The name "Neovide" only appears in all the windows, There will be a bit confusing to know which window has which buffer opened.

![image](https://user-images.githubusercontent.com/11899221/199927783-ba532612-a77e-4607-92fb-10354105a735.png)

in the above image, you can see Firefox window prepended the current tab name in the window title, But neovide has static name.

**Describe the solution you'd like**
The proposal is to append the current active buffer name to the window title, to easily distinguish the difference between neovide windows

**Comment by MultisampledNight** [comment]
Thanks for reporting!

This is configurable in NeoVim itself, see the `title` and `titlestring` options. Neovide respects both.

**Comment by kskarthik** [comment]
Sigh! Did not know it before, Thank you @MultisampledNight

**Comment by MultisampledNight** [comment]
That's what questions are for, right? You're welcome!
