### ISSUE TITLE
[Windows] Version 0.10.2 cannot open a file with full path

### ISSUE THREAD

**Issue by VladimirMarkelov** [neovide/neovide#1627]
**Describe the bug**
I just updated neovide to 0.10.2 and cannot open a file by relative or full path. I have a menu item in my file manager that calls Neovide with full path to a file and now it stopped working. It looks like the new version add extra escaping.

**To Reproduce**
1. In a file manager: Create a directory `src`
2. In a file manager: create a file `err.rs` and add some random text to it
3. Go to the directory that is the parent of `src`
4. Try opening the file `src\err.rs`: `"c:\neovim\bin\neovide.exe" --geometry=140x45 "src\err.rs" --neovim-bin="c:\neovim\bin\nvim.exe"`
5. The Neovide opes with an error:

```
E303: Unable to open swap file for ""src\\err.rs"", recovery impossible
""src\\err.rs"" [New DIRECTORY]
```

Removing quotes(that is not good in some cases) does not fix the issue: `"c:\neovim\bin\neovide.exe" --geometry=140x45 src\err.rs --neovim-bin="c:\neovim\bin\nvim.exe"`

6. Only if I enter the directory `src` and edit a file providing just its name, new version works: `"c:\neovim\bin\neovide.exe" --geometry=140x45 err.rs --neovim-bin="c:\neovim\bin\nvim.exe"`

**Expected behavior**
Previous version of Neovide opens the same file without any issues

**Screenshots**
No screenshot, I pasted the text of the error above

**Desktop (please complete the following information):**
 - Windows 10
 - Neovide: 0.10.2
 - Neovim: NVIM v0.8.0-1210-gd367ed9b2

**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**
I've attached log as pasting 400k of text is overkill
[neovide_new_rCURRENT.log](https://github.com/neovide/neovide/files/9946527/neovide_new_rCURRENT.log)

**Additional context**
From logs it seems that the new version does extra escaping. I ran previous version with the same arguments and compared logs.

New version:

```
TRACE [neovide] Neovide version: 0.10.2
DEBUG [neovide::bridge::command] Starting neovim with: Command { std: "d:\\utils\\neovim\\bin\\nvim.exe" "--embed" "-p" "\"src\\\\err.rs\"", kill_on_drop: false }
```

Previous version:

```
TRACE [neovide] Neovide version: 0.10.1
DEBUG [neovide::bridge::command] Starting neovim with: Command { std: "d:\\utils\\neovim\\bin\\nvim.exe" "--embed" "src\\err.rs", kill_on_drop: false }
```

**Comment by MultisampledNight** [comment]
Thanks for reporting!

This is the same issue as #1608 I believe, which already has a PR ready and set, but can't really go on with without having someone confirm that this doesn't allow shell injections.

**Comment by VladimirMarkelov** [comment]
I see. I looked for `E303`, found nothing, hence I opened the issue as it was new to me. Thanks for clarification!

**Comment by MultisampledNight** [comment]
No worries!
