### ISSUE TITLE
Cargo.lock needs update 0.10.2

### ISSUE THREAD

**Issue by ck3d** [neovide/neovide#1628]
With package manager Nix the package neovide is built in mode --frozen. This leads to errors, when Cargo.toml and Cargo.lock do not fit:
```
the lock file Cargo.lock needs to be updated but --frozen was passed to prevent this
...
```

When version is bumped in Cargo.toml then Cargo.lock needs to be updated. The version of neovide is recorded in the lock file:
https://github.com/neovide/neovide/blob/0.10.2/Cargo.lock#L1342

I had to apply following patch:
https://github.com/NixOS/nixpkgs/pull/199915/files#diff-90fb02ea9ea5dc47f898f3d23c599148b71120cf8b9fc79bf8a5c507863c18d3

**Comment by alerque** [comment]
Same issue packaging for Arch Linux.

**Comment by alerque** [comment]
This also happened with 0.10.0 (see #1482). Is there a release checklist or script you run when tagging releases that we can get a `cargo update` added to, or a CI check run with `--frozen` that would tip you off when you forget to update it along with Cargo.toml?

**Comment by MultisampledNight** [comment]
Hm, this is weird. I've set up a checklist at https://neovide.dev/maintainer-cookbook.html#actually-releasing which also includes running `cargo update`, which I did in fe66dde839fce44800f8c5617e274a1fe78190c2.

But I just realized what I did wrong. I didn't run `cargo build` _after_ bumping the version everywhere. Phew, another time another patch release, I'm sorry.

**Comment by MultisampledNight** [comment]
A CI check is a very good idea, I'll do that.

**Comment by MultisampledNight** [comment]
0.10.3 is out. I'll try to improve the maintainer cookbook later on, quite busy right now

**Comment by ck3d** [comment]
Thanks for the quick response!

**Comment by MultisampledNight** [comment]
f93a5f35a699e7ffa1aa1d141e73ca18e530f6a3 added an explicit mention of the need of `Cargo.lock` added to the bump version commit, and should we somehow manage to miss that, 2c0916e8e26106ca7ed9261d2640ad8dd4e68a31 added a CI check which will cry on release with a non-frozen build. Hopefully that'll be enough to avoid this annoying situation in the future, sorry again.
