### ISSUE TITLE
Part of buffer is cleared instantly instead of remaining until out of view

### ISSUE THREAD

**Issue by Hubro** [neovide/neovide#1630]
**Describe the bug**

When scrolling up or down, the portion of the buffer that is scrolled out of view is instantly cleared, i.e. blanked. This has been happening to me for a long, long time (over a year?) but I haven't realized what the issue is because of my short animation time, I just noticed a very annoying flash any time I scrolled. Increasing the animation time makes it clear what the problem is (see the video below.)

For a nice scroll effect, this part of the buffer should remain visible until it leaves the viewport.

Looking at the [smooth scrolling demo in the GIF on the features page](https://neovide.dev/features.html), this doesn't appear to happen. Does this only occur to me?

**To Reproduce**
1. Enable multigrid
2. Scroll up or down using Ctrl+f or Ctrl+b

**Expected behavior**

A nice scroll animation.

**Screenshots**

https://user-images.githubusercontent.com/597206/200279267-4b78b925-53a9-4d14-a330-957ed6f82c18.mp4

**Desktop (please complete the following information):**
 - OS: Linux (Linux 6.0.7-arch1-1)
 - Neovide Version 0.10.1
 - Neovim Version 0.8.0

**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**

[neovide_rCURRENT.log.gz](https://github.com/neovide/neovide/files/9950234/neovide_rCURRENT.log.gz)
[neovide_r2022-11-07_10-53-45.log.gz](https://github.com/neovide/neovide/files/9950235/neovide_r2022-11-07_10-53-45.log.gz)

(These are some huge files, I don't think you want me to paste the contents... :smile:)

**Additional context**

\-

**Comment by fredizzimo** [comment]
This will be greatly improved when I finish this https://github.com/fredizzimo/neovide/commits/fsundvik/improve-performance. At least cttrl-f and ctrl-b should work perfectly. But there will still be problems when scrolling completely outside of the previous view. For that we probably need to snap to the last line and animate only the scrolling of the final line.

Furher improvements probably need new support from Neovim itself.

**Comment by Awpteamoose** [comment]
Not sure if related, but seems to be related:
If open fzf's `:Files` (or anything that pops up a quickfix) - a portion of the buffer would just get blanked out. Unless I'm at the very top of the buffer, the blanked out lines will be redrawn, otherwise I have to either switch buffer and go back or scroll or smth like that:

https://user-images.githubusercontent.com/3111840/206703193-c935a3c1-b907-40c2-a48a-3d21720ba86e.mp4

**Comment by fdev31** [comment]
https://user-images.githubusercontent.com/238622/214561394-cd6a7c73-0608-44e9-951f-09ce20af90df.mp4

Similar issue when scrolling up with the mouse wheel... (requires multigrid)
