### ISSUE TITLE
KeyUp event not handled if the KeyDown is triggered before startup

### ISSUE THREAD

**Issue by aj3423** [neovide/neovide#1631]
**Describe the bug**
I use a global hotkey "Alt+Enter" to launch Neovide, if I release the 'Alt' key after Neovide launches, then the `Alt` is always down even after being released, all key strokes will become combination of 'Alt + key'. I need to press and release 'Alt' again to fix it.

**To Reproduce**
1. Type `neovide` in terminal
2. Hold down "Alt" key and press "Enter" to launch Neovide
3. After Neovide is launched, release "Alt" key
4. Press any key would become "Alt + key"

**Expected behavior**
The key up event should be handled even if the keydown event is triggered before it launches.

**Screenshots**
None

**Desktop (please complete the following information):**
 - OS: Kali Linux 2022.3
 - Neovide Version 0.10.3
 - Neovim Version  v0.8.0-1210-gd367ed9b2

**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**
[neovide_rCURRENT.log](https://github.com/neovide/neovide/files/9953664/neovide_rCURRENT.log)

**Additional context**
None

**Comment by fredizzimo** [comment]
Can you test if this is fixed by https://github.com/neovide/neovide/pull/1789? That branch uses the master of Winit with a lot of fixes. 

If it still happens with that, we need to report it to the Winit team.

**Comment by aj3423** [comment]
@fredizzimo I just tried the branch [new-keyboard-v3](https://github.com/neovide/neovide/pull/1789/commits/bf29c85e09aef79d9a7c27c2a0baec4997487fa9), seems it's fixed.
Thanks.
