### ISSUE TITLE
Window size is increasing with every start of neovide

### ISSUE THREAD

**Issue by bytex0a** [neovide/neovide#1636]
**Describe the bug**
When I start neovide.exe, close the window an restart it again, the window size increases with every new start.
I do not change the window size manually. You can see the problem in the log beneath:
At the top of the top the is size: Dimensions "{ width: 190, height: 44 } }" and at the bottom "size":{"width":232,"height":48}}}}".
After another start it is width: 232, height: 48 at the top and "width":283,"height":52 at the bottom.

**To Reproduce**
Set let g:neovide_remember_window_size = v:true in init.vim (If it is set to false window size will be set to 100 x 50 when quitting neovide)
Start and close the program (no matter if you close by closing the window, using :quit or shortcut ZZ) several times.

**Expected behavior**
The size of the window should stay the same at every start.

**Desktop (please complete the following information):**
 - OS: Windows 10
 
[neovide_rCURRENT.log](https://github.com/neovide/neovide/files/9997854/neovide_rCURRENT.log)
- Neovide Version 0.10.3
 - Neovim Version 0.9.0

**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**
File too big, see attachment

**Comment by sid-6581** [comment]
For me it's hit or miss. Sometimes it ends up smaller than it should, sometimes it's way bigger. I'm using PowerToys FancyZones to try to put it in a zone, but Neovide just doesn't want to play ball with it. It's never the correct size on startup.

**Comment by cmcpasserby** [comment]
experience the same thing, think its only happening on windows but can test on mac later if needed

**Comment by USER-5** [comment]
Yes I'm having this issue on macOS. I have `vim.g.remember_window_size = true` in my config, but have tried without as well. 

Testing via launching with `neovide dotfiles` from iterm2, and quitting with `:wqa` (not Cmd+q):
- lines=31, columns=111
- lines=27, columns=124
- lines=24, columns=139
- lines=21, columns=156
- lines=18, columns=175

Strangely, mine gets increasingly short and wide...

**Comment by chomosuke** [comment]
I've been having the same issue since forever now. As I suspected this is because font changes after the window has already been opened. Because neovide save its size by characters, it'll open the window with the size calculated from the default font which is presumably bigger than the font you use.

You can verify this by adding 
```lua
    local i = 0
    while i < 500000000 do
      i = i + 1
    end
``` 
Before you change font in your `init.lua`. After that neovide will consistently get bigger every launch. If you set your `guifont` to be something bigger than the default font then neovide will consistently get smaller.

**Comment by chomosuke** [comment]
The solution to this problem will be to save the window size via pixel instead of character, though I'm not sure how feasible that would be.

**Comment by danielb2** [comment]
Is there a workaround to this? my window is huge now every time I start it.

**Comment by chomosuke** [comment]
@danielb2 use this PR https://github.com/neovide/neovide/pull/1706

**Comment by danielb2** [comment]
woh. i made something happen 😁
