### ISSUE TITLE
Neovide 10.0.3 is really slow

### ISSUE THREAD

**Issue by xbladesub** [neovide/neovide#1639]
I upgraded from 10.0.1 to 10.0.3 and it became really slow. Any ideas why and how could I fix that?
I used 10.0.1 with lunarvim and everything was fine.

MacOS Monterey 12.6 (M1 pro)

**Comment by xbladesub** [comment]
https://github.com/neovide/neovide/issues/1634#issuecomment-1315417301

**Comment by MultisampledNight** [comment]
(closing this to keep discussion at one place, thanks for reporting though!)
