### ISSUE TITLE
error: '1' isn't a valid value for '--multigrid' [possible values: true, false]

### ISSUE THREAD

**Issue by Ouilly** [neovide/neovide#1645]
**Describe the bug**
When opening Neovide (same for neovide-git-package) from Kitty (or any other terminal emulator)  it produces the following error message: "error: '1' isn't a valid value for '--multigrid' [possible values: true, false]". 

**To Reproduce**
1. Open terminal 
2. Type 'neovide' and hit enter
3. See error

**Expected behavior**
Opening an instance of Neovide from the terminal.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Manjaro Linux, version 22.0.0
 - Neovide Version 0.10.3
 - Neovim Version 0.9.0-dev-356+g6e8ed5aba

**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**

**Additional context**
If, instead, one types: "neovide --multigrid" into the terminal emulator it opens up without problem. I am not super well versed in what this means and it may just be an issue with my version of Neovim or something else.

**Comment by melkster** [comment]
@Ouilly This was recently changed, so now you need to change the line

```
export NEOVIDE_MULTIGRID=1
```

to

```
export NEOVIDE_MULTIGRID="true"
```

In your `~/.zshrc` or `~/.profile`, or wherever you have it set :)

**Comment by Ouilly** [comment]
Beautiful, thanks a tonne! :)
