### ISSUE TITLE
Neovide won't start on Fedora Silverblue

### ISSUE THREAD

**Issue by AsterisMono** [neovide/neovide#1647]
**Describe the bug**
Neovide fails to start on [Fedora Silverblue](https://docs.fedoraproject.org/en-US/fedora-silverblue/), an immutable variant of Fedora Workstation.

**To Reproduce**
1. Enter a freshly created _Toolbox_ (More about toolbox below), install Neovim, and install development dependencies following [the guide](https://neovide.dev/installation.html).
2. Install neovide by `cargo install --git https://github.com/neovide/neovide`.
3. Run `neovide`.
4. Nothing happens.

**Expected behavior**
Neovide should start, or at least it should give meaningful log or error messages.

**Screenshots**
![Image](https://user-images.githubusercontent.com/54884471/202974778-a1568440-c08c-4ae4-bdf5-64a689ea87d8.png)

**Desktop (please complete the following information):**
 - OS: Fedora 36/37 Silverblue
 - Neovide Version 0.10.3
 - Neovim Version 0.8.0
 - DE: Gnome 42/43, running Wayland session. (Tried Xorg session, won't help.)

**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**

`cat neovide_rCURRENT.log`
```
TRACE [neovide] Neovide version: 0.10.3
DEBUG [neovide::bridge::command] Starting neovim with: Command { std: "/usr/bin/nvim" "--embed" "-p", kill_on_drop: false }
```

`cat neovide_r2022-11-21_13-42-09.log`
```
TRACE [neovide] Neovide version: 0.10.3
```

**Additional context**
Some context here FYI:
- On Fedora Silverblue, the root filesystem is read-only, thus conventional package manager (`dnf` of Fedora) will not work and is disabled.
- To install command line tools like Neovim and Neovide, [Toolbox](https://docs.fedoraproject.org/en-US/fedora-silverblue/toolbox/) is used to create a **containerized environment**, in which `dnf` is present and can be used to install packages.
- I have not tested if Neovide will run on original Fedora Workstation, but judging by the fact that the installation guide contains steps to build Neovide on Fedora I'll consider it good.
- Prebuilt binary grabbed from [Github Actions](https://github.com/neovide/neovide/actions/runs/3510001109) won't work either.

Neovide specific settings in [Neovim config](https://github.com/AsterisMono/nvim-config):
```lua
-- Neovide specific settings
vim.cmd [[
  if exists("g:neovide")
    let g:neovide_scale_factor = 0.8
    set guifont=Hack Nerd Font:h14
  endif
]]
```

**Comment by MultisampledNight** [comment]
Thanks for reporting and the insanely fine-grained detail, this is very useful! Could you run with `--nofork` as flag to Neovide and take a look at the output? It's probably a panic, we're lacking better error reporting mechanisms at the moment. (wouldn't be hard to do actually, hm)

**Comment by AsterisMono** [comment]
`neovide --nofork` under Wayland session:
```
thread 'main' panicked at '
  Failed to initialize any backend! 
  Wayland status: NoWaylandLib
  X11 status: LibraryOpenError(
    OpenError { 
      kind: Library, 
      detail: "opening library failed (libXcursor.so.1: cannot open shared object file: No such file or directory);
        opening library failed (libXcursor.so: cannot open shared object file: No such file or directory)" 
    }
  )
', /var/home/cmiki/.cargo/git/checkouts/winit-58efae9df3f5264a/27967af/src/platform_impl/linux/mod.rs:626:9
```
`neovide --nofork` under X11 session:
```
thread 'main' panicked at '
  Failed to initialize any backend!
  Wayland status: NoCompositorListening
  X11 status: LibraryOpenError(
    OpenError {
      kind: Library,
      detail: "opening library failed (libXcursor.so.1: cannot open shared object file: No such file or directory);
        opening library failed (libXcursor.so: cannot open shared object file: No such file or directory)" 
    }
  )
', /var/home/cmiki/.cargo/git/checkouts/winit-58efae9df3f5264a/27967af/src/platform_impl/linux/mod.rs:626:9
```
## Some thoughts
It seems that in the containerized environment created by toolbox, window protocol libraries are not correctly installed (or not installed at all).
Will try installing the essentials and come back later., it doesn't look like a Neovide bug at this point.

**Comment by camilo-celis** [comment]
rather than closing this, it would be interesting to see if the maintainers and others can spend time coming up with a solution (?) I had a working version of Ubuntu 22, but after a recent upgrade, it stopped working failing in the exact same manner as described here.

**Comment by AsterisMono** [comment]
@camilo-celis 

How things on Fedora Silverblue work is vastly different from common distributions like Ubuntu.

It introduces a unique container mechanism that *can* cause problems, and in this particular case,  **is** the thing that breaks the deal. Neovide failing on Silverblue is more like a *mechanism*, not an *issue* of Neovide itself. In other words, it **can't be solved** on Silverblue.

What happening to your Neovide on Ubuntu is more likely a _real issue_, and I think it deserves its own issue thread. :D

**Comment by MultisampledNight** [comment]
(sorry to hijack your mailbox for the last time, AsterisMono)

@camilo-celis Likely you just need to install `libxcursor-dev`.

**Comment by camilo-celis** [comment]
@AsterisMono cool - thanks; I was not really familiar with Silverblue :+1:
