### ISSUE TITLE
Add the ability for the user to reconnect if the network connection with the --remote-tcp connection drops

### ISSUE THREAD

**Issue by rphodges** [neovide/neovide#1648]
If the network connection with the server specified by --remote-tcp times out or drops, neovide goes into a hung state until it finally quits.  I have to wait for it to exit or quit it myself and then manually restart it to restore the connection.

**Describe the solution you'd like**
As soon as neovide loses connection with the server I'd like for it to prompt me with a button to "retry" the connection at which point I can press the button when I'm sure the network is back up.

**Comment by fredizzimo** [comment]
Neovide 0.13.0 should detect the connection drop properly, and also allow you to reconnect.
