### ISSUE TITLE
Mac os: keyboard input is a bit clunky

### ISSUE THREAD

**Issue by jaanauati** [neovide/neovide#1649]
**Describe the bug**
Input feels a bit clunky In my two macbooks with spanish keyboard.
When entering the "{" char using the combination option+{, I actually have to press the "{" key **twice** for Neovide to enter the '{' symbol. Otherwise, Neovide won't enter the mentioned symbol.

**To Reproduce**
1. Use a macbook w spanish keyboard.
2. Open neovide
3. Open a buffer.
4. Press option+{.
5. Notice the bug: the symbol "{" is not entered.
6. Try entering option+{+{. This time works.

**Expected behavior**
"{" should be entered whenever I enter option+{.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Monterrey 12.3.1 (21E258).
 - Neovide Version: 12.3.1 (21E258)
 - Neovim Version: NVIM v0.8.0-dev+366-gc6d747e6a

**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**

**Additional context**

**Comment by fredizzimo** [comment]
The new winit keyboard api has been merged to master https://github.com/neovide/neovide/pull/1789. Hopefully that fixes the issue, could you test again with Neovim master?

**Comment by fredizzimo** [comment]
I'm pretty sure this is fixed in Neovide 0.11.0
