### ISSUE TITLE
Support pipe/stdin buffer.

### ISSUE THREAD

**Issue by williamspatrick** [neovide/neovide#1654]
**Is your feature request related to a problem? Please describe.**
A fairly regular pattern is to take the output of a shell command and pipe it to [n]vim: `echo example | vim -`.  This works with vim, nvim, and gvim, but not neovide.  Instead you end up with a broken pipe: `BrokenPipeError: [Errno 32] Broken pipe` (example from a python script).

**Describe the solution you'd like**
`neovide -` or `neovide -- -` does the expected.

**Describe alternatives you've considered**
I also tried `neovide /proc/self/fd/0`, which just causes a hang.

**Additional context**
N/A.

**Comment by williamspatrick** [comment]
This also appears related to neovide/neovide#1619

**Comment by MultisampledNight** [comment]
Thanks for reporting! Seems like this and #1619 are the same issues, I'd like to keep communication at one place if possible, so I'll close this if you don't mind.
