### ISSUE TITLE
What is the default font?

### ISSUE THREAD

**Issue by wh1le** [neovide/neovide#1657]
**Is your feature request related to a problem? Please describe.**
I'm trying to find what font Neovide uses by default.

**Describe the solution you'd like**
Somebody help to answer, or point to the place in the configuration

**Describe alternatives you've considered**
Tried googling or reading manuals

**Comment by MultisampledNight** [comment]
Thanks for the question!

The default font is Fira Code Nerd Font, as found on the configuration page: https://neovide.dev/configuration.html#font. Though the point is there, it's probably worth highlighting that one explicitly.

**Comment by wh1le** [comment]
Thank you!

**Comment by scutwengxinqian** [comment]
> Thanks for the question!
> 
> The default font is Fira Code Nerd Font, as found on the configuration page: https://neovide.dev/configuration.html#font. Though the point is there, it's probably worth highlighting that one explicitly.

The link doesn't show the default font anymore. How can I find out the default font?

**Comment by MultisampledNight** [comment]
It got moved into the config file docs some time ago: https://neovide.dev/config-file.html

> ```toml
> [font]
> normal = [] # Will use the bundled Fira Code Nerd Font by default
> size = 14.0
> ```

Hence: Fira Code Nerd Font at size 14pt.
Would be worth replacing the listing in the original link at some point I believe.
