### ISSUE TITLE
Terminal scroll doesn't work when connected to remote server via SSH

### ISSUE THREAD

**Issue by xbladesub** [neovide/neovide#1658]
If I connect to my server via SSH (ssh root@[server_ip] ...) - I can't scroll inside terminal. For example after ```apt list --installed``` I can't scroll up to see all packages. Is there any way to fix or I have to setup it somehow?

(I open neovide's terminal with command ```:term://zsh```)

**Comment by fredizzimo** [comment]
I'm pretty sure this works with the latest version, you just need to enter the normal mode to scroll.
