### ISSUE TITLE
Scroll actions on popup window close the popup window.

### ISSUE THREAD

**Issue by iHnR** [neovide/neovide#1668]
**Describe the bug**
When I try to scroll through floating window (see screenshot) the documentation closes and the file underneath is scrolled.

When I launch from a terminal, I can simply scroll the window using the scrollwheel/touchpad.

I imagine there could be some config setting that might fix this but I'm not clever enough to find it.

**To Reproduce**
1. Install something that provides autocompletion or any other sort of popup (I use lunarvim)
2. Partially type some builtin keyword.
3. See automoplete or documentation window popup.
4. The window now disappears and the file underneath just starts scrolling.

**Expected behavior**
The popup window scrolls.

**Screenshots**
[When trying to scroll through the popup on the right, the popup disappears](https://imgur.com/a/kECXQw0)

**Desktop (please complete the following information):**
 - OS: [Pop_OS_22.04]
 - Neovide Version [0.10.3]
 - Neovim Version [0.8.1 (lunarvim)]

**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**
```
TRACE [neovide] Neovide version: 0.10.3
```

**Additional context**
As I mentioned earlier, I use Lunarvim. I'm not too familiar with how the whole plugin system of neovim works quite yet. I made it work with neovide by copying [this script](https://github.com/LunarVim/LunarVim/issues/1553#issuecomment-920247252).

I have other minor issues with using the mouse in neovide as well that don't seem to be an issue in the terminal. I'll list them as they might be related:

- Notably I always have to click the window after starting neovide and occasionally after performing some window action. Before I do this, no keyboard action is recognized.
- Primary selection and pasting did not work out of the box but were (partially) fixed by setting the clipboard provider.

**Comment by maksut** [comment]
I think I have the same problem.  In my setup; scrolling on `vim.lsp.buf.hover` floating window scrolls the background buffer instead.  And floating window is closed when the scrolling eventually moves the cursor in the buffer.

I don't have lunarvim.

**Comment by sa-mendez** [comment]
I am also having this issue as well (also using Lunarvim, but I think this issue is independent of Lunarvim usage).

**Comment by alex35mil** [comment]
I think the same issue here. I use [zen-mode](https://github.com/folke/zen-mode.nvim) a lot. When it is activated, scrolling doesn't work, and when I click anywhere, the floating buffer closes.

**Comment by Kethku** [comment]
I think this may have been due to improper handling of mouse events with floating windows. This is handled better with multigrid and a recent fix that went in for non multigrid. Please reopen if the problem persists
