### ISSUE TITLE
Multigrid: z-index is wrong for Telescope modal

### ISSUE THREAD

**Issue by ndan** [neovide/neovide#1676]
With multigrid enabled. When I open a `Telescope file_browser` then press `<esc>?` to open help. The help window opens behind the Telescope. 

* I can reproduce it on my custom config and lunarvim.
* It doesn't matter which Telescope command you use, file_browser or any other command
* No bug in a terminal

Multigrid disabled
<img width="1792" alt="Screenshot 2022-12-13 at 11 38 49" src="https://user-images.githubusercontent.com/760394/207222071-0c9109c9-823d-4536-ae7e-b69febc2a529.png">

Multigrid enabled
<img width="1792" alt="Screenshot 2022-12-13 at 11 51 52" src="https://user-images.githubusercontent.com/760394/207222205-f24602e6-303c-4179-88c2-a116e4ac9bd0.png">

**Desktop:**
 - OS: macOS 13.0.1
 - Neovide Version: 0.10.3
 - Neovim Version: 0.8.1

**Comment by Kethku** [comment]
I believe this is fixed. Please reopen if problems persist

**Comment by Kethku** [comment]
Can you send a link to your config or a minimal repro?

**Comment by sid-6581** [comment]
> Can you send a link to your config or a minimal repro?

Here is my config: https://github.com/sid-6581/NeovimConfig

**Comment by FloatStream** [comment]
I also have this problem, and I tried a minimal repro:
```lua
{
    'nvim-telescope/telescope.nvim',
    branch = '0.1.x',
    dependencies = { 'nvim-lua/plenary.nvim' },
    opts = {}
}
```
I use Lazy.nvim to manage my plugins. The above only calls `require(telescope).setup()` to initialize it. The test results are as follows:
Multigrid ON
![multigrid](https://github.com/neovide/neovide/assets/69284622/b36c1148-44c2-4b62-ad90-c8b7b9511505)
Multigrid OFF
![no-multigrid](https://github.com/neovide/neovide/assets/69284622/6dc89ed3-5e7f-464b-bd25-68cd79babeb4)

**Comment by FloatStream** [comment]
> To be honest, I'm not sure if this is a Neovide bug, both windows specify a zindex of 50, and the neovim documentation does not say anything about the ordering of windows with the same index.
> 
> ~So, I think a bug report should be opened in the LazyVim repository.~ The bug is actually in Telescope

Ok, I'll try to find the answer on Telescope's project or open an issue. Thank you

**Comment by sid-6581** [comment]
> To be honest, I'm not sure if this is a Neovide bug, both windows specify a zindex of 50, and the neovim documentation does not say anything about the ordering of windows with the same index.
> 
> ~So, I think a bug report should be opened in the LazyVim repository.~ The bug is actually in Telescope

I looked into this, hoping that a secondary sort by window ID would solve the problem, but not only are they creating the floats all with the same z-index, they're creating the floats in the wrong (IMHO) order. The border float is created after the content float that goes inside the border float. This definitely is something that needs to be fixed in telescope.

**Comment by sid-6581** [comment]
Found someone else with the exact same issue lol:

https://neovim.discourse.group/t/multigrid-ui-z-indexing-grids/1177

I've looked into a lot of telescope bugs this year, it's quite a mess.

**Comment by fredizzimo** [comment]
Did anyone report this to telescope yet?

**Comment by fredizzimo** [comment]
There's a telescope issue here:
* https://github.com/nvim-telescope/telescope.nvim/issues/2976

**Comment by emmanueltouzery** [comment]
The telescope fix was merged, I think this issue can now be closed.

**Comment by fredizzimo** [comment]
Great, I will close this then.
