### ISSUE TITLE
Neovide.app launch on MacOS (Apple Silicon) via Spotlight/Alfred is broken

### ISSUE THREAD

**Issue by owittek** [neovide/neovide#1679]
neovide 0.10.3
NVIM v0.8.1

I've already tried adding the NVIM_BIN env to .zprofile (as an alternative to https://github.com/neovide/neovide/issues/1373#issuecomment-1179268069 ) and tried the fix described in Troubleshooting. Symlinking is a workaround but it breaks telescope and might affect other plugins.

____________________________________

> I found a section in [Homebrew documentation](https://docs.brew.sh/FAQ#my-mac-apps-dont-find-homebrew-utilities) talking about this issue. Hope it helps.

This seems to work for opening the GUI in finder but it is still not possible to open it from spotlight/alfred. Symlinking nvim to /usr/local/bin ( ln -s /opt/homebrew/bin/nvim /usr/local/bin/nvim ) fixes that but neovide will always launch in the /usr/local/bin folder which seems to break the telescope plugin.

_Originally posted by @owittek in https://github.com/neovide/neovide/issues/1242#issuecomment-1355747526_

**Comment by aromeronavia** [comment]
Same here

**Comment by chrisgrieser** [comment]
As far as I can tell, opening via Alfred works now. (neovide 0.13)

**Comment by ttollet** [comment]
A temporary workaround:

1. Open Automator
2. Click "New Document"
3. Select "Application" then click "Choose"
4. Search and add "Run Shell Script"
5. Paste the following: `open -a /opt/homebrew/bin/neovide --args $1`
   - Assumes neovide is installed via homebrew
   - Opens neovide as an application
   - Accepts other files as arguments to ensure "Open With" will work
7. In the top right of the input box, set _Pass Input_ to "as arguments"
8. Click _File > Save_

Now:
- Neovide can be opened from Spotlight search.
- Neovide supports the "Open With" menu option.

Only caveat is this approach shows Neovide without the nice Neovide icon until opened.

**Comment by falcucci** [comment]
At least to me, no problem at all.

https://github.com/neovide/neovide/assets/33763843/a4d74c47-0a15-4227-a1bc-e076d5c0125b
