### ISSUE TITLE
Resizing causes non-regular animation.

### ISSUE THREAD

**Issue by Rid1-fz-06** [neovide/neovide#1680]
**Describe the bug**
Whilst resizing neovide windows, the animation is not smooth. The titlebar precedes the window.

**To Reproduce**
1. Open a neovide instance.
2. Try to resize using mouse from sides or corner.

**Expected behavior**
The transition should be smooth.

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.0.1
 - Neovide Version: O.10.3
 - Neovim Version: v0.8.1

**Comment by fredizzimo** [comment]
Would it be possible to provide a tracy log following these instrucitons https://neovide.dev/troubleshooting.html#performance-profiling?

**Comment by Rid1-fz-06** [comment]
@fredizzimo this issue no longer exists in my system. Should I close this issue?

**Comment by fredizzimo** [comment]
Ok thanks, I'm closing this.

There has been many optimizations since the report, so something has probably fixed it.
