### ISSUE TITLE
Cleartype font rendering on Windows

### ISSUE THREAD

**Issue by harg** [neovide/neovide#1689]
**Is your feature request related to a problem? Please describe.**
On windows OS, font rendering is not using Cleartype technology

**Describe the solution you'd like**
Have an option to select cleartype font rendering on windows  OS (like the in the new Windows Terminal)

![image](https://user-images.githubusercontent.com/34398/209110713-fca7990f-edfc-4de0-8ba9-ee09f374cdfc.png)

**Comment by yashamon** [comment]
Pretty sure it uses cleartype. The output is indistinguishable from nvy, at least on win11, which explicitly uses clear type.

**Comment by harg** [comment]
@yashamon you can clearly see the difference on my previous screenshot. top: nvy, bottom: neovide. OS is Windows 10.

**Comment by yashamon** [comment]
You might be right nvy looks a bit more antialiased. though I prefer the
sharper look of neovide. Of course that's very monitor dependant.

**Comment by harg** [comment]
Thank you for your answer.
I will toy with antialias options. This ticket can be closed.

**Comment by shaunsingh** [comment]
I would try enabling/disabling subpixel antialiasing and seeing if it has an effect
