### ISSUE TITLE
Flash of white when opening the application on Windows

### ISSUE THREAD

**Issue by fgimian** [neovide/neovide#1691]
**Describe the bug**
There's a brief burst of white before the editor appears when starting the application.

Here's a video demostration with a few sleeps thrown in to exxagerate the problem:

```rust
diff --git a/src/window/mod.rs b/src/window/mod.rs
index 82aa281..6fe47ef 100644
--- a/src/window/mod.rs
+++ b/src/window/mod.rs
@@ -511,7 +511,11 @@ pub fn create_window() {

         if frame_start - previous_frame_start > frame_duration {
             let dt = previous_frame_start.elapsed().as_secs_f32();
+            std::thread::sleep(Duration::from_millis(500));
+
             window_wrapper.draw_frame(dt);
+            std::thread::sleep(Duration::from_millis(500));
+
             if let FocusedState::UnfocusedNotDrawn = focused {
                 focused = FocusedState::Unfocused;
             }
```

![Neovide White Burst](https://user-images.githubusercontent.com/1811813/209253280-47096b2f-c6eb-4c2d-ba47-6a1d137e029c.gif)

**To Reproduce**
1. Simply open the application on a Windows system (I'm using Windows 11 Pro)
2. Observe a brief burst of white while it is opening

**Expected behavior**
This burst of white should not happen.

**Screenshots**
See the video above 😄 

**Desktop (please complete the following information):**
 - OS: Windows 11 Pro
 - Neovide Version: main branch (67a48653b71bf8a7c36953ddd75dc06894628d9a)
 - Neovim Version: 0.8.1

**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**

```
TRACE [neovide] Neovide version: 0.10.3
```

**Additional context**
In my own app using egui and winit, I had to ensure that the window was only made visible after the first frame was drawn.  I've attempted this with the Neovide source but still saw a burst of white so there may be something I'm missing with how the window is drawn here.

**Comment by yellowHatpro** [comment]
I am also facing the same issue.

**Comment by Kethku** [comment]
I believe this has been fixed. Please reopen if the problem continues
