### ISSUE TITLE
[ Feature Request ] add align to top

### ISSUE THREAD

**Issue by NEX-S** [neovide/neovide#1698]
before
![image](https://user-images.githubusercontent.com/97107165/209484224-c88155bb-f6f7-4b8e-bbac-13d17895b636.png)

after
![image](https://user-images.githubusercontent.com/97107165/209484232-ade8a43e-d6b2-4a8b-b39e-12c1c11a7419.png)

**Comment by MultisampledNight** [comment]
Thanks for the request! This is already possible on main with the padding options as introduced by https://github.com/neovide/neovide/pull/1632.
