### ISSUE TITLE
Neovide doesn't remenber correct window position when taskbar location on top of screen on Windows 10

### ISSUE THREAD

**Issue by luozhiya** [neovide/neovide#1699]
**Describe the bug**
Neovide doesn't remenber correct window position when taskbar location on top of screen on Windows 10

**To Reproduce**
1. Set Taskbar location on the top of screen
2. Set neovide_remember_window_size to true

**Expected behavior**
Neovide remenber window position when taskbar location on top of screen on Windows 10.

**Screenshots**
If applicable, add screenshots to help explain your `problem.`

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Neovide Version [0.10.1]
 - Neovim Version [v0.9.0-dev-533+ga6747545b]

**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**
https://gist.github.com/luozhiya/a1e14b2b8575a45cf5cbc6d3ecff4fce

**Additional context**

**Comment by falcucci** [comment]
@luozhiya is this still an issue for you?

**Comment by luozhiya** [comment]
@falcucci 

Cannot reproduce the issue in the latest version '0.13.3'.
