### ISSUE TITLE
E488 error Trailing characters when trying to :enew filename

### ISSUE THREAD

**Issue by nerdo** [neovide/neovide#1702]
**Describe the bug**
For some reason I keep getting the error `E488: Trailing characters: %whatever_i_typed_as_the_filename` when trying to create a new file with that filename.

**To Reproduce**
On macOS...
1. Launch neovide (doesn't matter if it is launched from the terminal with `-- --clean`, or double clicking the application)
2. Type `:enew %filename.txt`

**Expected behavior**
A new buffer with the specified filename should be created.

**Desktop (please complete the following information):**
 - OS: macOS 13.1
 - Neovide Version 0.10.3
 - Neovim Version 0.8.1

Neovide logs:
[neovide_r2022-12-27_16-31-21.log](https://github.com/neovide/neovide/files/10310809/neovide_r2022-12-27_16-31-21.log)
[neovide_rCURRENT.log](https://github.com/neovide/neovide/files/10310810/neovide_rCURRENT.log)

**Comment by dineshKumar777** [comment]
is this command working in neovim terminal ??? for me, i am getting the same error in terminal too.

**Comment by nerdo** [comment]
Ugh, disregard, I definitely had a brain fart yesterday. It's `:e` not `:enew`, and that  is working.
