### ISSUE TITLE
Neovide crashes when opening in fullscreen on osx

### ISSUE THREAD

**Issue by EtshD1** [neovide/neovide#1704]
I was re-setting my nvim config from scratch and I added neovide config as a Lua file. The Lua file was configured as such:
```lua
vim.g.neovide_cursor_vfx_mode = "railgun"
vim.g.neovide_fullscreen = true
```
This caused neovide to crash when starting up.

See below for reproduction.

https://user-images.githubusercontent.com/33322463/209930072-ce6d5640-8404-40c5-bc6d-ba740f673b65.mp4

**Comment by fredizzimo** [comment]
I'm closing this, since there has been no additional reports, and because no log and `neovide_backtraces.log` is provided, which would allow us to debug further.
