### ISSUE TITLE
WSL2: gui shows no window borders hence unable to resize window

### ISSUE THREAD

**Issue by kting28** [neovide/neovide#1708]
**Describe the bug**

**To Reproduce**
1. Launch neovide on WSL2. I have to start from an existing xterm (not windows terminal)
2. neovide window pops up, can minimize or maximize but no window border to resize

**Expected behavior**
with `--frame full` the border should be visible
**Screenshots**
![image](https://user-images.githubusercontent.com/24449116/210097824-3c912225-af59-4053-a61f-8f13bf3110e0.png)

**Desktop (please complete the following information):**
 - OS: windows 10 with WSL2
 - Neovide Version 0.10.3
 - Neovim Version 0.8.1

**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**
[neovide_rCURRENT.log](https://github.com/neovide/neovide/files/10325721/neovide_rCURRENT.log)

**Comment by cewestermann** [comment]
I've got the same issue. Would love to use Neovide, but gotta stick to cmder-terminal nvim until this is looked at.

**Comment by MultisampledNight** [comment]
Likely related to #728, or maybe even the same issue. I don't know anything about the WSL(2) stack. But this seems like winit's default window decorations to me.

**Comment by fredizzimo** [comment]
Is there any reason why you are launching Neovide through WSLg, rather than the native Windows version with `--wsl`? The Windows version is much better and gets proper GPU acceleration.

**Comment by Kethku** [comment]
Closing for lack of response. We recommend running in windows natively with --wsl
