### ISSUE TITLE
Some plugins do not render correctly when running without a file/dir specified

### ISSUE THREAD

**Issue by mrivnak** [neovide/neovide#1711]
**Describe the bug**
When launching from the shortcut or cli with no arguments using the `e` command to select a directory or file to edit does not render some plugins (namely barbar and galaxyline) correctly. The plugins are still loaded correctly as their respective commands are still available and no errors are produced.

**To Reproduce**
1. Run neovide without any arguments
2. execute `e ~/some_dir_or_file`
3. open one or multiple buffers

**Expected behavior**
barbar and galaxy line are rendered correctly

**Screenshots**
galaxyline and barbar not loaded
![image](https://user-images.githubusercontent.com/7389355/210140862-c1a47cd4-c8d0-4d81-a846-3b9c17469dd3.png)

plugins all loaded correctly when specifying a startup directory
![image](https://user-images.githubusercontent.com/7389355/210141033-f9ab9dde-2863-403b-814f-f152eeb8e671.png)

plugins loaded correctly when running nvim without any arguments and following the same steps as above
![image](https://user-images.githubusercontent.com/7389355/210141017-38523148-e284-424d-acb4-ad3c730782a7.png)

**Desktop (please complete the following information):**
 - OS: Windows 11 22H2
 - Neovide Version: 0.10.3
 - Neovim Version: 0.8.2

**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**
https://gist.github.com/mrivnak/41a52d803fd1ed79c1239c333aab3d10

**Additional context**

**Comment by Kethku** [comment]
This sounds heavily like a config issue. I cannot reproduce this on my machine. Can you give some more details, for example what exactly you ran to give it a starting directory and file? Can you try splitting your config in half to isolate which plugins have this issue?

**Comment by fredizzimo** [comment]
Closing due to it most likely being a. configuration issue and lack of response from the author.
