### ISSUE TITLE
Super (Cmd) keys (eg. `<D-j>`) are not captured

### ISSUE THREAD

**Issue by starptr** [neovide/neovide#1715]
**Describe the bug**
Neovide doesn't capture super key combos, eg. `<D-j>`.

**To Reproduce**
1. Enter insert mode
2. Press `<D-j>`. This is possible on a mac by pressing Command + j.
3. Observe that the string `<D-j>` is literally inserted into the buffer.

**Expected behavior**
The `<D-j>` keycode should be sent to neovim.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: 13.1
 - Neovide Version 0.10.3
 - Neovim Version 0.8.2

**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**

**Additional context**
Workaround is [possible (this example also remaps it to meta, but you can change it to send super)](https://github.com/starptr/nvim-config/blob/081ac4a1a35bb1c0d4c53d99e482c7f86ffe1331/lua/remap-cmd-to-meta.lua#L1-L31) but has limitations (typing `<D-j>` manually will trigger the keycode).

**Comment by fredizzimo** [comment]
This should be fixed by #1899, it would be great if you can test that.
