### ISSUE TITLE
Problems with terminal colours

### ISSUE THREAD

**Issue by yyy33** [neovide/neovide#1718]
**Describe the bug**
I'm about to switch to neovide recently and I'm having problems with the terminal colours, I don't know anything about this, how can I get the terminal colours to display properly, the first picture is nvim running in alacritty and it looks normal, the second picture is nvim running in neovide and it looks very "dark"

**To Reproduce**

**Expected behavior**

**Screenshots**
![1](https://user-images.githubusercontent.com/51548147/210492685-7b711032-75ab-428c-b82f-d22a105abb8f.png)
![2](https://user-images.githubusercontent.com/51548147/210492701-e2ebe0ac-2ffd-4d28-87a1-a4532233f4ca.png)

**Desktop (please complete the following information):**
 - OS: [arch linux]
 - Neovide Version [neovide 0.10.3]
 - Neovim Version [NVIM v0.8.0]

**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**
[neovide_rCURRENT.log](https://github.com/neovide/neovide/files/10341778/neovide_rCURRENT.log)

**Additional context**

**Comment by MultisampledNight** [comment]
Hi! Likely your colorscheme doesn't set `g:terminal_color_0` through `g:terminal_color_15`. See https://neovide.dev/faq.html#the-terminal-displays-fallback-colorsterminal-does-not-show-my-colors for details.

**Comment by MultisampledNight** [comment]
Since there hasn't been any response for about a month, I'll close this. Feel free to reopen if you tried the above and still notice this is a bug!
