### ISSUE TITLE
Neovide crashes with latest sway/wlroots versions

### ISSUE THREAD

**Issue by itaranto** [neovide/neovide#1724]
**Describe the bug**
Neovide crashes with latest sway/wlroots versions upon start.

**To Reproduce**
1. Open a terminal
2. Run `neovide`
4. Neovide crashes with `SIGABORT`

See the attached file which is the output of `coredumpctl info`:

[neovide-dump-info.txt](https://github.com/neovide/neovide/files/10353271/neovide-dump-info.txt)

**Expected behavior**
Neovide starts successfully.

**Desktop**
 - OS: Arch Linux
 - Neovide Version: 0.10.3
 - Neovim Version: 0.8.2

**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**

[neovide_r2023-01-05_11-55-24.log](https://github.com/neovide/neovide/files/10353278/neovide_r2023-01-05_11-55-24.log)
[neovide_rCURRENT.log](https://github.com/neovide/neovide/files/10353281/neovide_rCURRENT.log)

**Additional context**

It apparently started happening after updating `sway` and  `wlroots`.

sway version: 1.8
wlroots version: 0.16.1

**Comment by MultisampledNight** [comment]
Hi! As per the discussion in #1356, I'll close this as duplicate.
