### ISSUE TITLE
neovide dpi too high?

### ISSUE THREAD

**Issue by GRR3ED** [neovide/neovide#1728]
**Describe the bug**
I just installed neovide but the dpi is too high IDK if it counts as bug

**To Reproduce**
Just installed and launched neovide

**Expected behavior**
a normal dpi

**Screenshots**
Screenshots : 

**What I See** :
![Jan-07_13:54:58](https://user-images.githubusercontent.com/58597122/211141025-89202199-3378-4afb-a1b5-0c121c836186.png)

**Expected Output**:
![Jan-07_13:54:55](https://user-images.githubusercontent.com/58597122/211141035-e8d34ced-43f7-4389-acbb-ddfb53d6677a.png)

**Desktop (please complete the following information):**
OS : Arch-5.15.86-1-lts
Neovide version : 0.10.3
Neovim version : 0.8.2

**Comment by MultisampledNight** [comment]
Taken to Discord. Put short, the font size controls _everything_, including the perceived scale, since Neovim under the hood still operates on a grid of characters. See https://neovide.dev/configuration.html#font.
