### ISSUE TITLE
still don't work in ubuntu 22.04

### ISSUE THREAD

**Issue by 88srzh** [neovide/neovide#1732]
**Describe the bug**
install neovide from snap in ubuntu 22.04

**To Reproduce**
try to run neovide, see error:
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: CreationErrors([NoAvailablePixelFormat, OsError("GL context creation failed")])', src/window/window_wrapper/mod.rs:287:10

**Desktop (please complete the following information):**
 - OS: ubuntu 22.04
 - Neovide Version 0.8.0

**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: GlobError { path: ".", error: Os { code: 13, kind: PermissionDenied, message: "Permission denied" } }', /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/ops/function.rs:150:5

**Comment by fredizzimo** [comment]
The window size stored in the settings files is probably wrong, try launching with `neovide --size=100x100` to fix it.

**Comment by 88srzh** [comment]
`⋊> ~/D/G/surf-flutter-study-jam-4 on study-jam-4 ◦ neovide README.md
                                    
⋊> ~/D/G/surf-flutter-study-jam-4 on study-jam-4 ◦ libGL error: No matching fbConfigs or visuals found                                                                                                 
libGL error: failed to load driver: swrast
libEGL warning: DRI3: Screen seems not DRI3 capable
libEGL warning: DRI2: failed to authenticate
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: CreationErrors([NoAvailablePixelFormat, OsError("GL context creation failed")])', src/window/window_wrapper/mod.rs:287:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

⋊> ~/D/G/surf-flutter-study-jam-4 on study-jam-4 ◦ neovide --size=100x100 README.md                                                                                                                    
error: Found argument '--size' which wasn't expected, or isn't valid in this context

USAGE:
    neovide [FLAGS] [OPTIONS] [files]... [-- <neovim_args>...]

For more information try --help`

**Comment by fredizzimo** [comment]
The size argument is available in the latest release 0.11.0, try updating to that.
