### ISSUE TITLE
Logo key cannot be remapped in `<C-r>` combinations

### ISSUE THREAD

**Issue by terence-dickson-faire** [neovide/neovide#1739]
**Describe the bug**
Enabling `g:neovide_input_use_logo` and executing `{i,c}map <D-{...}> <C-{...}>` does not allow to use `<D-r><D-{...}>` to perform non-register paste operations. For example, `<C-r><C-w>` can typically be used to paste the word under the cursor into the command-line, and while these remap commands do allow `<D-r><C-w>` to work, they don't enable `<D-r><D-w>` (i.e., the second keystroke is still required to use the Ctrl key.)

**To Reproduce**
1. Enable `g:neovide_input_use_logo`.
2. Place the cursor over a word.
4. Execute `:cmap <D-r> <C-r>`, `:cmap <D-w> <C-w>` (typing the chevrons literally.)
5. Type `:<D-r><D-w>` (actually using the command key.)

**Expected behavior**
The `<D-w>` keystroke should cause the word under the cursor to be pasted. Instead, nothing happens. (`<C-r><C-w>` and `<D-r><C-w>` both cause the word under the cursor to be pasted, as expected.)
Adding every combination of `map` commands (`xmap`, `omap`, `lmap`...) does not help; none of them appear to be sufficient to cause `<D-w>` to work as `<C-w>` in this particular key sequence.

**Desktop (please complete the following information):**
 - macOS 13.1
 - Neovide Version 0.10.3
 - Neovim Version 0.8.2

**Additional context**
I use multiple operating systems on a daily basis, and so when working on Mac, I map the Ctrl key on my typical keyboard to be Command, as this results in more reliable muscle memory when inputting normal keystrokes in most programs. However, this isn't ideal in vim, when you actually want to use the Ctrl key most of the time, even on Mac OS. iTerm2 allows you to map Command back to Ctrl, which solves that problem, but Neovide doesn't have similar capabilities currently; Vim's own `map` commands are insufficient to cover all cases.

Allowing the command key to be used as the Ctrl key in all circumstances would be really useful for workflows like this. I know it sounds odd, but I can't imagine I'm all that unusual in wanting a Ctrl key that "just works like Ctrl" in my daily workflow when I'm on a Mac. `<C-r><C-w>` is a huge part of my workflow as it's really convenient for doing things like "fuzzy-search for the identifier under the cursor".

I think an ideal solution here would be just to add an option to neovide's configuration to have the Command key function as the Ctrl key under all circumstances, rather than worrying about each individual key and mode mapping, as I'm not sure if `cmap` actually is _meant_ to apply to the keystroke after a `<C-r>` input.

**Workaround**
`cmap <C-r><D-w> <C-r><C-w>`, and all corresponding key combinations. This is not an ideal solution as it will buffer the `<C-r>` keystroke until it can tell what the next key is supposed to be, so that it can tell if it's meant to execute the mapping or write `<C-r>` literally. It's not a big problem for `<C-r>` since it waits for the next keystroke anyway, but it will interrupt any tab completions or previews you have for registers.

**Comment by terence-dickson-faire** [comment]
[This is the full set of mappings](https://gist.github.com/terence-dickson-faire/2478598d06e4c19d7cd4ee96d48ba882#file-ginit-vim) that I've come up with as a workaround to "remap" the Command key to Ctrl, if it's useful to anybody else. Many of them are probably unnecessary (in particular `map` should obviate `omap`) but I was seeing what map commands were necessary.

**Comment by fredizzimo** [comment]
This should be fixed by #1899, it would be great if you can test that.
