### ISSUE TITLE
Windows Alt+Space shortcut not working

### ISSUE THREAD

**Issue by QuadrupleA** [neovide/neovide#1740]
**Describe the bug**
With neovide in Windows, the alt-space keyboard combination (popping up a menu in the top left of the window allowing you to move, minimize, etc. without using the mouse) doesn't pop up anything. Vs. a typical windows application (e.g. nvim-qt). 

**To Reproduce**
1. Launch neovide
2. Type Alt-Space

**Expected behavior**
The window menu - Restore, Move, Size, etc. 

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Neovide Version 0.10.3.0
 - Neovim Version 0.8.2

**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**
(356 KB, not sure if security sensitive - will include it if needed)

**Comment by QuadrupleA** [comment]
AutoHotKey workaround if anyone needs it:

`#If WinActive("ahk_exe neovide.exe")
!space::
    Click, 23, 14
Return
#If
`

**Comment by gilbh** [comment]
Brilliant ... you've just made my day!

**Comment by fredizzimo** [comment]
This should be fixed by #1899, it would be great if you can test that.
