### ISSUE TITLE
Didn't render some ligatures when using cursorcolumn

### ISSUE THREAD

**Issue by elytraflyer** [neovide/neovide#1741]
**Describe the bug**
When i'm using FiraCode Nerd Font,the ligatures cursorcolumn highlighted wasn't rendered.
When i'm using neovim in kitty terminal,it didn't happen.

**To Reproduce**
1. ```set cursorcolumn```
2. ```set guifont=Fira\ Code\ Nerd\ Font:h10```

**Expected behavior**
Render ligatures when using cursorcolumn

**Screenshots**
```:set nocursorcolumn```
![图片](https://user-images.githubusercontent.com/59987531/213418375-f2c7d967-f578-4b13-8b22-096685121799.png)

```:set cursorcolumn```
![图片](https://user-images.githubusercontent.com/59987531/213418903-561a126b-c36c-4ba6-9b07-f3b4eaed4af2.png)

**Desktop (please complete the following information):**
 - OS: Manjaro Linux
 - Neovide Version [e.g. 0.6.0]
 - Neovim Version [e.g. 0.5.0]

**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**
[neovide_rCURRENT.log](https://github.com/neovide/neovide/files/10455858/neovide_rCURRENT.log)

**Comment by Kethku** [comment]
This won't be fixed. We render ligatures based on the font style. If they match, we assume the text is a single run and shape it together. If it doesn't match (for instance when the background changes) we cannot assume that the text is part of the same text run and so cannot render the ligature.
