### ISSUE TITLE
lsp tsserver failed

### ISSUE THREAD

**Issue by Alan110** [neovide/neovide#1742]
**Describe the bug**
lsp tsserver can't start . it shows error msg : 

`spawn: npm failed with code - and signal . - npm is not executable`

but in neovim  terminal ,  it's ok 

i guess is that npm path used wrong in tsserver ?  i install node and npm by nvm .  here is the path 

`/Users/alan/.nvm/versions/node/v16.18.0/bin/npm`

**Screenshots**
in neovide
![image](https://user-images.githubusercontent.com/7564425/213626542-91bed19b-bd07-42f0-8036-43ded716da7c.png)

in terminal
![image](https://user-images.githubusercontent.com/7564425/213626826-58515af9-d7e5-4fcb-9d18-3a9dc70ccd5f.png)

**Expected behavior**
lsp tsserver start correct .

**Desktop (please complete the following information):**
 - OS: [macOS 12.4]
 - Neovide Version [0.10.3]
 - Neovim Version [0.8.2]

**Comment by webmarkyn** [comment]
This should help
`sudo ln -s "$(which node)" /usr/bin/node`
`sudo ln -s "$(which npm)" /usr/bin/npm`

**Comment by fredizzimo** [comment]
This is answered by the FAQ https://neovide.dev/faq.html#neovide-is-not-picking-up-some-shell-configured-information
