### ISSUE TITLE
Map option on Mac to Alt?

### ISSUE THREAD

**Issue by Ciel-MC** [neovide/neovide#1744]
**Is your feature request related to a problem? Please describe.**
I share a nvim config folder between my linux desktop and macbook, and I would like to use option for <M-something> keys on Mac

**Describe the solution you'd like**
An option to use option as alt instead of inputting the other characters

**Describe alternatives you've considered**
Mapped Option to Alt in Kitty

**Additional context**
N/A

**Comment by shaunsingh** [comment]
Try https://neovide.dev/configuration.html#macos-alt-is-meta

**Comment by NikosEfthias** [comment]
I can confirm that this works with no issues on my mac

**Comment by NikosEfthias** [comment]
@Ciel-MC may be you can give some feedback or close this issue to reduce the noise in the issue tracker

**Comment by shaunsingh** [comment]
Closing as this should be covered by the option above, feel free to reopen if the issue persists

**Comment by Ciel-MC** [comment]
(Wait isn't <M-X> "modifier" instead of meta?

**Comment by OliverChao** [comment]
> Try https://neovide.dev/configuration.html#macos-alt-is-meta

It works fine except `<A-n>` (or `<M-n>`). 
I don't know why. See https://github.com/neovide/neovide/issues/1866#issue-1711231757
