### ISSUE TITLE
Couldn't find any pixel format that matches the criteria (Win10 VM)

### ISSUE THREAD

**Issue by MostHated** [neovide/neovide#1747]
**Describe the bug**
  
Hey there, I am having the following message when trying to start Neovide. I am assuming that this is because I am trying to run it in a Windows 10 VM (Running via KVM/QUEMU). 

```sh
thread 'main' panicked at 'Couldn't find any pixel format that matches the criteria.', src\window\mod.rs:368:17
```

With other apps I have been able to overcome this in various ways, typically by setting a few env variables, such as the ones seen below. I also tried to set Neovide flags that seemed like they might help, but unfortunately, no luck:

```bat

@REM The following worked for Houdini, so I figured it was worth a try:

@set LIBGL_ALWAYS_SOFTWARE=1
@set MESA_GLSL_CACHE_DISABLE=1
@set MESA_GL_VERSION_OVERRIDE=3.3COMPAT
@set MESA_GLSL_VERSION_OVERRIDE=330
@set MESA_EXTENSION_OVERRIDE=-GL_ARB_buffer_storage
@cd "C:\Users\mosthated\Downloads\neovide-windows\"
@neovide.exe --nofork --nosrgb

```

**Desktop (please complete the following information):**
 - OS: Win 10 VM
 - Neovide Version: 0.10.3
 - Neovim Version: NVIM v0.9.0-dev-598+g3a519d86b

**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**
```sh
TRACE [neovide] Neovide version: 0.10.3
DEBUG [neovide::bridge::command] Starting neovim with: Command { std: "C:\\Program Files\\Neovim\\bin\\nvim.exe" "--embed" "-p", kill_on_drop: false }
```
This is probably less of a bug and more of a question, if anyone happens to know of a workaround or resolution to this? I suppose I should look into if I can pass in my igpu to the VM somehow.

**Comment by shaunsingh** [comment]
Neovide isn't going to perform very well running on software rendering regardless, I'd recommend looking into passing through your gpu. This is a bit of a stretch, but if you want the neovide/linux experience on windows, we have pretty good wsl support

**Comment by MostHated** [comment]
The Windows machine is my work VM. I would imagine that if the native Windows executable won't work, trying to run it in WSL would not make a difference if lack of graphics is the issue, unless running it in WSL has different requirements? I can give it a try, just to see.

**Comment by zbigniewzolnierowicz** [comment]
Got the same issue, but on Fedora 38.

**Comment by fredizzimo** [comment]
I'm closing this, you will need gpu passthrough or something else that allows for hardware opengl 3.3
