### ISSUE TITLE
Single-application support on macOS

### ISSUE THREAD

**Issue by trombonehero** [neovide/neovide#1748]
Thanks for this lovely neovim GUI! I am a long-time Vim user, but tools like Neovide are helping me make the jump to neovim.

One issue I've run into on macOS is that every new Neovide window creates a new running application: not just a new process visible with `ps`, but a new application with a Dock icon, isolated from the other applications. This breaks the normal macOS experience, e.g., I can't use Cmd+Tab to switch between Neovide windows.

This is one thing that Neovide could take from MacVim. When I start MacVim, it runs two processes:

```
/Applications/MacPorts/MacVim.app/Contents/MacOS/MacVim -MMNoWindow yes
/Applications/MacPorts/MacVim.app/Contents/MacOS/Vim -f -g
```

When I press Cmd+N to create a new window, it creates a new `Vim -f -g` instance with a new window, but the application itself, with its Dock icon, etc., is linked to the `MacVim -MMNoWindow yes` process.

I would love it if Neovide did the same thing: if pressing Cmd+N created a new Neovide window within the same macOS application, allowing me to Cmd+Tab around between my various neovim windows.

**Comment by MultisampledNight** [comment]
Hi, thanks for reporting! This is tracked in #1586 already, so I'll close this issue in favor of the other one, to keep discussion at one place.
