### ISSUE TITLE
Send Latin letters (from scancodes) to Nvim

### ISSUE THREAD

**Issue by SnosMe** [neovide/neovide#1749]
**Is your feature request related to a problem? Please describe.**
vim/nvim as a TUI has a limitation that it can only operate on unicode codepoints.
Therefore, key mappings stop working if you switch the language.

**Describe the solution you'd like**
neovide itself is a GUI app, and as an embedder it has access to raw input events.
We can send raw scancodes where appropriate, they map to physical keys.

```js
if (mode == 'insert' || mode == 'replace') {
  if (e.ctrl || e.alt || e.meta) {
    nvim_input(e.scancode)
  } else nvim_input(e.codepoint) // <-- keep current behaviour only here
} else {
  nvim_input(e.scancode)
}
```

Of course, we are not sending scancodes, but rather english letters to what they would map on QWERTY keyboard (#445 will help with non-qwerty ones).

**Describe alternatives you've considered**
There is a not so good `langmap` option, that
1) requires you to write mapping for every non-English layout you use
2) doesn't work in insert mode

**Comment by MultisampledNight** [comment]
Thanks for the suggestion! This would break a lot of existing mappings though, which assume that the key after the modifier corresponds the the virtual keycode. Also this would be non-conformant to how Neovim works in the terminal and break one's workflow in case one's Neovide installation breaks/one is dependent on a TTY for sometime/whatever other scenario might hinder somebody from using Neovide.

Alternatively, we could maybe think of introducing new syntax for "I mean the keycode here" (which would be the default I think) and "I mean the scancode here". This would be needed to be introduced in Neovim itself though, so I'd recommend you to open an issue there if you'd like to take this further.

**Comment by fredizzimo** [comment]
I'm closing this. We can re-open if neovim adds support for this.
