### ISSUE TITLE
Unable to paste on MacOS

### ISSUE THREAD

**Issue by Xuanluo-Qiu** [neovide/neovide#1752]
I downloaded neovide with `brew` and it can't be pasted, when using the shortcut key, it just written `<D-v>` , when I exit neovide using normal terminal paste without problem

**Comment by Abdullah-coder2013** [comment]
I also had this problem, you can paste stuff by right clicking and selecting “Paste”

**Comment by akio-ito** [comment]
Issue referenced at:
https://github.com/neovide/neovide/issues/1263#issuecomment-1094628137

In my case, it is working with:
https://github.com/akioito/dotfiles/blob/master/vim/.config/nvim/lua/configs.lua#L5-L28

**Comment by shaunsingh** [comment]
As mentioned in the issue above, we don't add or remove any keybindings to neovim, we merely forward the keys. We also disable use of the "logo" key (on macOS, thats `cmd`) by default. Its likely that your terminal emulator enables copy/pasting with cmd-c/v, as neovim doesn't bind those keys by default

I believe the following mapping should work

```lua
-- Allow clipboard copy paste in neovim
vim.g.neovide_input_use_logo = 1
vim.api.nvim_set_keymap('', '<D-v>', '+p<CR>', { noremap = true, silent = true})
vim.api.nvim_set_keymap('!', '<D-v>', '<C-R>+', { noremap = true, silent = true})
vim.api.nvim_set_keymap('t', '<D-v>', '<C-R>+', { noremap = true, silent = true})
vim.api.nvim_set_keymap('v', '<D-v>', '<C-R>+', { noremap = true, silent = true})
```

I'll add this to the documentation

**Comment by shaunsingh** [comment]
This has been added do the documentation https://neovide.dev/faq.html#how-can-i-use-cmd-ccmd-v-to-copy-and-paste

**Comment by falcucci** [comment]
for non .lua users:

```shell
let g:neovide_input_use_logo = 1

map <D-v> "+p<CR>
map! <D-v> <C-R>+
tmap <D-v> <C-R>+
vmap <D-c> "+y<CR>
``` 

the only problem I am having after mapping this keybindings is during the float windows, eg. floaterm.

I am unable to paste anything there.

I guess that my command map are wrong tho.

trying to figure out.

**Comment by falcucci** [comment]
@shaunsingh could you gently add this for non `.lua` users in the docs too?

being aware of this issue I am pointing above which I am trying to figure out.

**Comment by ystyle** [comment]
Does this setting only take effect on mac? It does not work under linux

**Comment by yam-liu** [comment]
On macOS, this works without exiting insert mode.
```
vim.keymap.set("i", "<D-v>", "<C-r>*") -- Paste insert mode
```
