### ISSUE TITLE
VFX effects (cursor) don't work

### ISSUE THREAD

**Issue by thistlillo** [neovide/neovide#1754]
More than a bug report, this is a question. I installed Neovide  0.10.3 both on Windows and Mac OS Ventura 13.1 as a GUI for NeoVim. It does not seem to work correctly on either platform.

On Mac:
- none of the configuration options at https://neovide.dev/configuration.html work on the Mac when I issue commands in Neovide. Some of them do work in Windows 11.
- I created a configuration file in `~/.config/nvim/init.vim` ( the `nvim` folder did not exist and I had to create it -> BTW: in the instruction page add some info on where init.vim should be created). Now some configuration option work, e.g. transparency, but others seem to have no effects, e.g. vfx sonicboom.

I installed neovide instead of other GUIs for the nice effects on the cursor, that I really enjoy. However, I have a question: are Windows and Mac really supported?

**Comment by shaunsingh** [comment]
Both windows and macOS are completely supported (in fact, this was original developed on windows) and I develop/use this software on macOS. I'm not quite sure why the vfx effects don't work, could you share a copy of your `init.vim`

**Comment by Kethku** [comment]
Closing for no response
