### ISSUE TITLE
add hiden title bar user option

### ISSUE THREAD

**Issue by liaohui5** [neovide/neovide#1756]
**Is your feature request related to a problem? Please describe.**
Black neovim colorscheme, white title bar looks very strange

**Describe the solution you'd like**

add a `buttonless` user option like alacritty

<img width="1664" alt="image" src="https://user-images.githubusercontent.com/29266093/216667596-0aa6fe4f-e098-46ed-999e-ab845b58cbf4.png">

**Comment by shaunsingh** [comment]
You can run neovide with the `--frame` argument e.g. `neovide --frame none` command to remove the titlebar on macOS. We also have options to make the frame transparent, or buttonless if thats more your style

**Comment by m-faith** [comment]
> ...on macOS.

How about Linux?

**Comment by tobealive** [comment]
@m-faith 
> How about Linux?

Title bars and frames are managed by your window manager. Usually it is quite easy to disable them. Unless the application has built-in custom title bars. Neovide does not have such.

![Screenshot_20230204_045202](https://user-images.githubusercontent.com/34311583/216746565-c91ec541-4e35-44a9-86bb-a95e77a7674e.png)

**Comment by m-faith** [comment]
@tobealive thanks!!!

**Comment by tobealive** [comment]
Hey @arpanetus. I'm not in the Windows game and I don't plan to join. Sorry 🙏

**Comment by arpanetus** [comment]
@tobealive oh sorry, for some reason I thought you're one of the main contributors haha

**Comment by arpanetus** [comment]
@Kethku Could something be done here? Maybe I can somehow tinker it?

https://github.com/neovide/neovide/issues/1756#issuecomment-1517911741

**Comment by meicale** [comment]
How to use the "buttonless" option in windows 11. I am using a tiling windows manager(TWM), too. If I use --frame none, neovide use the fullscreen and cannot be managed by the TWM. Any options or suggestions? LOTS Thx!

**Comment by arpanetus** [comment]
> How to use the "buttonless" option in windows 11. I am using a tiling windows manager(TWM), too. If I use --frame none, neovide use the fullscreen and cannot be managed by the TWM. Any options or suggestions? LOTS Thx!

@meicale I managed to not to use neovide at all. 

Default Windows Terminal ships a focus mode option (ctrl+shift+p => toggle focus mode) which lets you basically hide the title bar. You might also want to tinker the scroll bar option in settings, which would allow you to hide it for aesthetic purposes.

![image](https://github.com/neovide/neovide/assets/14979358/efcae633-64ca-45ae-8d04-8556e78f7d9b)
![image](https://github.com/neovide/neovide/assets/14979358/fd72464d-f3bf-4ceb-84a5-c1190f0acc05)
