### ISSUE TITLE
Neovide window partially opens off the screen

### ISSUE THREAD

**Issue by damanis** [neovide/neovide#1767]
**Is your feature request related to a problem? Please describe.**

Some window managers on Linux XWindow (e.g., `WindowMaker`, but not only) has a feature to open application window with an offset: first time left top corner of window is 0:0 (for example), next time 10:100, then 20:200, etc. After application window touch screen bottom, window manager resets left top corner to 0:0, etc.
If I don't mistake, `neovide` opens window on start in two steps:
(1) create window with some default dimensions
(2) calculate window dimensions according lines, columns and font sizes, then resize window created on step (1).

Window manager calculates the window's left top corner on step (1), so after several launches `neovide` window opened low enough that its bottom is off screen after step (2).

**Describe the solution you'd like**

Calculate proper window dimension before create window to omit resize on step (2).

**Comment by damanis** [comment]
Yes, seems fixed.

**Comment by fredizzimo** [comment]
@damanis, are you using Wayland? The protocol does not allow setting of the window position, see this for one of the proposals https://gitlab.freedesktop.org/wayland/wayland-protocols/-/merge_requests/247

I'm not sure why your workaround works though, or maybe I'm understanding the problem wrong. The window creation is one phase, but it tries to reposition the window if it's outside the screen https://github.com/neovide/neovide/blob/c2c2179060f89766939b036f72b8404f7aeb7536/src/window/mod.rs#L85-L189

**Comment by damanis** [comment]
I'm not use Wayland.
`neovide` saves position in settings file:
```
{"window":{"Windowed":{"position":{"x":179,"y":115},"pixel_size":null,"grid_size":null}}}
```
As I understand the code
```
if let Some(previous_position) = previous_position { 
    winit_window_builder = winit_window_builder.with_position(previous_position); 
}
```
uses saved position (`x` and `y`) for created window.
In my options, `position` should not be saved.

**Comment by damanis** [comment]
I added the `neovide_remember_window_position` to init.lua - no effect.
![image](https://github.com/neovide/neovide/assets/65733488/0b59202b-f914-4db8-aeaf-8928860f1f6b)

P.S. Two autocmd at end requires for nvim 0.10.
I reported same issue for [goneovim](https://github.com/akiyosi/goneovim/issues/434).
Run neovide, use `yank` for any text then try close neovide - it stuck until you select something in terminal (is `ps ax` you should see `xsel ...`).

**Comment by fredizzimo** [comment]
Ah I see now; I think this always writes 0x0 when the saving is turned off.
https://github.com/neovide/neovide/blob/c2c2179060f89766939b036f72b8404f7aeb7536/src/settings/window_size.rs#L82-L88

But I think we need to re-design the whole system. The automatic saving and loading is just strange. Additionally, there's no way to just use the default once the settings are saved.

I'm re-opening this.

For the yank problem, I think you are seeing this issue https://github.com/neovide/neovide/issues/2003, if that's the case I will re-open it. In the end I think it's a Neovim issue, similar to this https://github.com/neovim/neovim/issues/24470
