### ISSUE TITLE
how do i source my wsl2 ubuntu ${home}/.bashrc when i neovide --wsl

### ISSUE THREAD

**Issue by HUAHUAI23** [neovide/neovide#1775]
when i neovide --wsl, it's not seem to source my ${home}/.bashrc 

https://user-images.githubusercontent.com/43649186/220323334-b58d7dd6-bcde-4d8e-91ff-6bcc9e75155b.mp4

**Comment by webmarkyn** [comment]
Please take a look at FAQ: https://neovide.dev/faq.html#neovide-is-not-picking-up-some-shell-configured-information

**Comment by HUAHUAI23** [comment]
> Please take a look at FAQ: https://neovide.dev/faq.html#neovide-is-not-picking-up-some-shell-configured-information

yeah,it's  ok,haha thank you very much

**Comment by HUAHUAI23** [comment]
what should i do, i want close this issue
