### ISSUE TITLE
Crash on startup under sway 1.8 / wlroots 0.16.1

### ISSUE THREAD

**Issue by williamspatrick** [neovide/neovide#1776]
**Describe the bug**
Both 0.10.3 release and github main branch seem to crash after a Wayland update to 1.21.
```
[wayland-client error] Attempted to dispatch unknown opcode 0 for wl_shm, aborting.
```

The closest historical bug I could find was one from [Alacritty](https://github.com/alacritty/alacritty/issues/4206) which required an update to glutin.  I attempted to update the glutin dependency, but there are API changes and at least one backported change in the neovide organization.  Considering glutin hasn't been updated in over 2 years, this seems to be a likely culprit.

I built with `--debug` and ran under GDB but this doesn't seem to give any additional details.  Attached is the results of running `WAYLAND_DEBUG=1 neovide --log`:

[wayland_debug.log](https://github.com/neovide/neovide/files/10796518/wayland_debug.log)

**To Reproduce**
1. Run under wayland 1.21 on Gentoo.
2. Window never starts.

**Expected behavior**
Window to launch without error.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Gentoo Linux
 - Neovide Version [main / 0.10.3]

**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**
[neovide_rCURRENT.log](https://github.com/neovide/neovide/files/10796526/neovide_rCURRENT.log)

**Additional context**
N/A

**Comment by williamspatrick** [comment]
Clearly I don't understand Wayland.  Both nested `weston` and `mutter` launch this correctly.  I'm actually using `sway` which uses wlroots.  It seems that wlroots / sway is the only environment where I can cause this crash.

sway 1.8
wlroots 0.16.2

**Comment by MultisampledNight** [comment]
Hi! Sorry to hear you're having such issues, this is the same issue as #1356 I think. In effect the winit we're using is indeed out of date, but this is due to our winit actually being forked to get early access to a new API. And now that bites us back.
