### ISSUE TITLE
Starting over "x2go" X sessions fails with "X server has XInput extension 1.3 but does not support XInput2" message.

### ISSUE THREAD

**Issue by brendanrankin** [neovide/neovide#1779]
**Describe the bug**
x2go sessions fails to start neovide with the message in the subject line.

**To Reproduce**
1. Start "x2go" session to remote machine.
2. Attempt to run neovide from an opened terminal shell.

**Expected behavior**
I expect an nvim window to pop open, like it does when I "ssh -XY" into the same remote machine.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Xubuntu 22.04LTS on remote, Fedora 37 on client
 - Neovide Version 0.10.3
 - Neovim 0.8.3
[neovide_backtraces.log](https://github.com/neovide/neovide/files/10811212/neovide_backtraces.log)

**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**

**Additional context**
At first, I thought it was some sort of fundamental issue with OpenGL as I couldn't get glxinfo or glxgears, etc. to function properly and some other x2go reports that ultimately involved Qt and/or OpenGL in some fashion led me to try...setting LIBGL_ALWAYS_INDIRECT=1 in my environment seems to solve that for those apps....but not for neovide.

I know it's a strange issue and it's happening in something that's expecting "xinput2" to be supported...I gather it's not with x2go and that's my issue.

Help appreciated!

**Comment by fredizzimo** [comment]
I'm closing this, you should report a bug to the https://wiki.x2go.org/doku.php/wiki:bugs. But unless you also can get hardware opengl 3 support, Neovide will be very laggy, even if you get xinput2 working.
