### ISSUE TITLE
Text display bug using opacity

### ISSUE THREAD

**Issue by Valwex** [neovide/neovide#1782]
**Describe the bug**
Text display bug using opacity.

**To Reproduce**
1. Add an opacity in the config file
2. Resize the window

**Expected behavior**
Do not have the old text displayed in the background.

**Screenshots**
<img width="853" alt="Capture_decran_2023-02-28_a_21 20 26" src="https://user-images.githubusercontent.com/62778739/221977870-6ffebde3-a3dd-4de9-a2c6-888d775aca26.png">

**Desktop (please complete the following information):**
 - OS: [macOS 13.3]
 - Neovide Version [0.10.3]
 - Neovim Version [0.8.3]

**Comment by xbladesub** [comment]
same
