### ISSUE TITLE
Neovide fails to start on Arch Linux with minimal logs

### ISSUE THREAD

**Issue by jivvy** [neovide/neovide#1784]
**Describe the bug**
Running `neovide` will silently fail.
Running `neovide --log` will produce the following log files:

**neovide_rCURRENT.log**
```
TRACE [neovide] Neovide version: 0.10.3
DEBUG [neovide::bridge::command] Starting neovim with: Command { std: "/usr/bin/nvim" "--embed" "-p", kill_on_drop: false }
```

**neovide_r2023-02-28_22-29-48.log**
```
TRACE [neovide] Neovide version: 0.10.3
```

**To Reproduce**
1. Installed from neovide-git AUR
2. Run `neovide`

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - neovide 0.10.3
 - NVIM v0.8.3
 - swaywm 1:1.8.1-1

**Comment by MultisampledNight** [comment]
Hi, thanks for reporting! Given your setup with swaywm, I believe this is the same issue as #1356, so I'll close this one to keep discussion at one place.
