### ISSUE TITLE
Windows crashes on start, "Could not create surface"

### ISSUE THREAD

**Issue by A-Lamia** [neovide/neovide#1788]
**Describe the bug**
Does not load and instantly crashes on execution.

**To Reproduce**
1. build master on windows.

**Expected behavior**
1. Neovide starts with no issues.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Neovide Version Master
 - Neovim Version 0.9.0

**Please run `neovide --log` and paste the contents of the `.log` file created in the 
[neovide_backtraces.log](https://github.com/neovide/neovide/files/10891352/neovide_backtraces.log)
[neovide_rCURRENT.log](https://github.com/neovide/neovide/files/10891803/neovide_rCURRENT.log)

**Additional context**
Happens on master found it trying to use https://github.com/neovide/neovide/pull/1786, current version that is working for me is the bellow setup.
1. https://github.com/neovide/neovide/pull/1706 <-- what i was using before
2. https://github.com/neovide/neovide/pull/1786 <-- currently using with window-size-fix (merged after window fix)

was trying to test out the anchor fix things seemed normal but i could not get floating window blur to work tried `pumblend` and `winblend` with no luck.

**Comment by fredizzimo** [comment]
I think it would be helpful to also have the regular `neovide_rCurrent.log` That should tell more about what kind of surfaces it was trying to create.

**Comment by A-Lamia** [comment]
@fredizzimo sure thing.
[neovide_rCURRENT.log](https://github.com/neovide/neovide/files/10891800/neovide_rCURRENT.log)

**Comment by fredizzimo** [comment]
I just took a quick look for now, it's trying to create a grid that is 934x1000 characters, with a font size of 11x22 pixels that's a texture of 10274x22000, which is 215M pixels or 7 times bigger than an 8k picture. So no wonder why it's unable to create a texture that big.

It's the main grid that is that big, and the culprit seems to be a saved setting. 
> DEBUG [neovide::settings::window_geometry] Loaded window settings: Windowed { position: PhysicalPosition { x: 961, y: 16 }, size: Dimensions { width: 934, height: 1016 } }

So, I think you need to delete the settings file in `AppData/local/nvim-data` (it looks like you are on Windows)

**Comment by fredizzimo** [comment]
I think it has stored your windows size in pixels, but trying to use it as characters. That MR should probably use a different name for the setting.

**Comment by A-Lamia** [comment]
@fredizzimo aaah so i need to clear the cache.

**Comment by A-Lamia** [comment]
If that's the issue then this can be closed, it's an other PR im using that converts window size to pixel and stops the screen from expanding on each start.
