### ISSUE TITLE
Line height issue

### ISSUE THREAD

**Issue by xbladesub** [neovide/neovide#1793]
Is it possible to display some unicode character without additional vertical spacing? As I know we have line height support now, but it doesn't fix the issue.

Example what I have:
<img width="401" alt="Screenshot 2023-03-09 at 12 17 58 AM" src="https://user-images.githubusercontent.com/45129790/223771219-e529fc8d-9d45-41f9-a97a-7a5515936b22.png">

Example what do I expect (no strange gaps, neovide ASCII art is displayed correctly. Wezterm):
<img width="446" alt="Screenshot 2023-03-09 at 12 18 12 AM" src="https://user-images.githubusercontent.com/45129790/223771426-79b691cd-3068-49ae-808b-4f6473af79c9.png">

**Comment by fredizzimo** [comment]
This has been discussed multiple times, for example

* You reported this earlier https://github.com/neovide/neovide/issues/1774
* https://github.com/neovide/neovide/issues/1197 - I think the conclusion from that one is that our current shaper does not render some characters correctly, as defined in the font. I think we should switch to https://github.com/harfbuzz/harfbuzz, which is used almost everywhere else. Right now we are using https://github.com/dfrg/swash
* And as mentioned in this one I think that we should have a fallback font for certain characters, that always fills the whole height and width  https://github.com/neovide/neovide/issues/481

**Comment by xbladesub** [comment]
Any updates?)
