### ISSUE TITLE
vim-airline makes cursor animation to insert mode work incorrect

### ISSUE THREAD

**Issue by WhiteBlackGoose** [neovide/neovide#1794]
**Describe the bug**
![neovide-cursor-bug](https://user-images.githubusercontent.com/31178401/224467682-16bb70ad-98e4-41fe-8a3e-dfe8a4391a9e.gif)

**To Reproduce**
Minimal config:
```lua
local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "https://github.com/folke/lazy.nvim.git",
    "--branch=stable", -- latest stable release
    lazypath,
  })
end
vim.opt.rtp:prepend(lazypath)


local commonPlugins = {
    'https://github.com/vim-airline/vim-airline',
    'vim-airline/vim-airline-themes',
}
require("lazy").setup(commonPlugins, {})
```

Go to insert mode

**Expected behavior**
Obvious

**Screenshots**
Attached in description

**Desktop (please complete the following information):**
 - OS: NixOS unstable
 - Neovide Version: 0.10.3
 - Neovim Version: v0.9.0-dev

**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**
```
TRACE [neovide] Neovide version: 0.10.3
```

**Comment by WhiteBlackGoose** [comment]
[`set noshowmode`](https://github.com/neovide/neovide/issues/158) fixes it

**Comment by fredizzimo** [comment]
I think this fixed it for multigrid
* https://github.com/neovide/neovide/pull/753

And since 0.12.0 multigrid is the default, while `--no-multigrid` is deprecated and will probably eventually be removed.

So, closing this as fixed
