### ISSUE TITLE
No externalfile drag possible on self compiled binary but works on released binary (windows)

### ISSUE THREAD

**Issue by mroxh** [neovide/neovide#1796]
**Describe the bug**
I have followed the [windows source installation](https://neovide.dev/installation.html#windows-source) and I am able to compile the windows neovide binary and run it.

With either the "debug" or "release" version, 
- start neovide binary
- I try to drop a file from the explorer and place this in neovide, the mouse arrow changes to a stop sign.
- release the mouse button, nothing happens.

However, if use the windows neovide binary from scoop or from the [release page](https://github.com/neovide/neovide/releases/tag/0.10.3)
- start neovide binary
- I try to drop a file from the explorer and place this in neovide, the mouse arrow changes to an arrow with dotted rectangular and + sign
- release the mouse button and the file name/path is dropped in neovide/neovim

**To Reproduce**
1 -  follow the [windows source installation](https://neovide.dev/installation.html#windows-source)
2 - cargo build --release
3 - Start the binary from the target\release\neovide.exe
4 - I try to drop a file from the explorer and place this in neovide, the mouse arrow changes to a stop sign icon.
5 - release the mouse button, nothing happens.

**Expected behavior**
The self compiled version should behave the same as the released version.
Is there something missing in the build instructions to have drag and drop enabled? I guess I am doing something wrong to build it properly? I can't find any documentation hence this bug. Please refer to other documentation that I would have missed. I have read the maintainer cookbook, but I see no specific instructions related to this problem. This is my first time compiling neovide.

**Screenshots**
Difficult because the stop sign icon is lost the moment I release my mouse button, to make a screenshot

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Neovide Version 0.10.3
 - Neovim Version 0.8.1

**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**
I tried to for both cases with --log file, but I see nothing specific. If needed I can still attach.

**Additional context**
When running neovide in wsl mode (neovide.exe --wsl), dragging a file will pass the windows os path (e.g d:\\textfile.log) to neovim running in wsl which is incorrect (dtextfile.log). I would like to convert this to WSL1 path (/mnt/d/textfile.log), by adjusting the code, but I would need to be able to drag and drop from the self build version to reproduce the situation.
My development environment is in WSL1, but I sometimes get log or other text files in windows.
Currently I open this in a direct windows neovide, but I would like to open these files in a  windows neovide in wsl mode.

**Comment by Kethku** [comment]
I looked into this and can reproduce it, but I wasn't able to figure out why it was happening. Seems like something is weird with file drops in winit. Not sure.

**Comment by 9mm** [comment]
Im also encountering this on mac which is a bit painful when downloading files from internet and just want to drag into icon, i have to do this nearly daily with CSV's etc so i actually left vim in the dock just for that purpose even tho i dont use vim anymore

@fredizzimo can you think of any way i could assist with this one?

**Comment by 9mm** [comment]
Ah I am on OSX im not sure, was that also attempting to fix?

**Comment by fredizzimo** [comment]
I'm pretty sure this was fixed on Windows with
* #2056
