### ISSUE TITLE
neovide freezes on startup

### ISSUE THREAD

**Issue by simonlearnscoding** [neovide/neovide#1804]
when I startup neovide, it freezes. 
I deactivated my init.lua so its probably not due to this
this happened after I updated my amd graphics driver

I am running pop os (ubuntu)
Neovide version 0.10.3
nvim version 0.9.0-dev

this is what I got from running neovide --nofork

ERROR [neovide::renderer::fonts::caching_shaper] Font can't be updated to: MonoLisa,Symbols Nerd Font
ERROR [neovide::renderer::fonts::caching_shaper] Font can't be updated to: Source Code Pro:h12
Neovide panicked with the message 'index out of bounds: the len is 1 but the index is 1'. (File: src/bridge/events.rs; Line: 321, Column: 17)
This is a bug and we would love for it to be reported to https://github.com/neovide/neovide/

this is whats in the backtraces log:

2023-03-15 00:21:01 - Neovide panicked with the message 'Resize failed: SendError(WriterError(Os { code: 32, kind: BrokenPipe, message: "Broken pipe" }), "nvim_ui_try_resize")'. (File: src/bridge/ui_commands.rs; Line: 139, Column: 18)

**Comment by A-Lamia** [comment]
having a similar issue
```
'index out of bounds: the len is 1 but the index is 1'. (File: src\bridge\events.rs; Line: 321, Column: 17)
```

**Comment by MultisampledNight** [comment]
Same issue as #1798, I believe. Thanks for reporting though!

**Comment by letavocado** [comment]
It still freezes

➜  neovide --nofork                                                                                                                                                                             
thread 'tokio-runtime-worker' panicked at 'index out of bounds: the len is 1 but the index is 1', src/bridge/events.rs:321:17
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

NVIM v0.9.0-dev-1305+g83bfd94d1
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3

**Comment by MultisampledNight** [comment]
@letavocado Just making sure, are you using one of the releases or did you build from source? The change did not land in a release yet.

**Comment by letavocado** [comment]
@MultisampledNight  build from source
Thank you!

**Comment by letavocado** [comment]
@MultisampledNight 
Neovide release version
Neovim-nightly build from source
