### ISSUE TITLE
Neovide fullscreeen window randomly disappears when switching from other fullscreen apps on macOS

### ISSUE THREAD

**Issue by lutalli** [neovide/neovide#1806]
**Describe the bug**
It's a quite weird bug: On macOS, when Neovide is in fullscreen, and when I switch from Neovide to other fullscreen apps and switch back (like using `Command + Tab` shortcut or three-finger sliding on touchpad), there's a chance that the Neovide window disappears.

Not happening when Neovide or the window been switched from is not in fullscreen.

**To Reproduce**
1. Enable Neovide fullscreen mode
2. Focus Neovide window
3. Press `Command + Tab` to switch to another fullscreen app
4. Press `Command + Tab` to switch back to Neovide (normally, the fullscreened Neovide window will be shown after this step)
5. Repeat step 3 and 4 until Neovide window disappears
6. Repeat another time to see Neovide window comes back

**Expected behavior**
Neovide window should consistently remain during the process of switching.

**Recording**
The following clip shows how it is happening. The "NERV" thing is my wallpaper, when it's visible it means that the fullscreened Neovide window disappeared.

https://user-images.githubusercontent.com/47910890/225592037-78b0adab-80e0-42f9-8e7d-ca47a8fc6b7a.mov

**Desktop:**
 - OS: macOS Monterey 12.4
 - Neovide: 0.10.0
 - NeoVim: 0.8.2

**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**
Visit [Ubuntu Pastebin](https://paste.ubuntu.com/p/mHbRdQv2yg/) to see the full log file (considering pasting the long log here would mess up).

The log file does not necessarily match the recording above perfectly, but it also includes the case.

**Comment by lutalli** [comment]
Not a direct solution to this bug, but the workaround I use for now is to make Neovide **maximalized framelessly**, instead of fullscreen. It has the same visual effect as fullscreen, gets rid of the random disappearance of the window, and even solves the problem that the MacOS menu bar is not accessible in fullscreen mode.

NOTE: Looks like there's currently no configuration option for launching Neovide in frameless mode, but the frameless mode can be enabled using the command argument `neovide --frame none`.

**Comment by fredizzimo** [comment]
I have a potential fix for this here:
* https://github.com/neovide/neovide/pull/2562

It would be good if someone could test it.
