### ISSUE TITLE
LSPs failing to load when running neovide --wsl

### ISSUE THREAD

**Issue by lukeemhigh** [neovide/neovide#1807]
**Describe the bug**
Many LSPs fail to load when running `nvim` through `neovide --wsl`, but they have no problems when executing `nvim` natively on wsl2.
In the picture below the LSP failing is `bashls`, but the same thing happended with `dockerls` and `yamlls`.

**To Reproduce**
1) Launch `neovide --wsl`
2) Open a file to load an LSP

**Expected behavior**
LSPs running the same way through `neovide --wsl` or native `nvim` on wsl2,

**Screenshots**
![image](https://user-images.githubusercontent.com/113122350/226058270-b9f46ddc-9bd3-4463-a4ef-7d6fead47e61.png)

**Desktop (please complete the following information):**
 - OS: Windows 11 Pro 22H2
 - Neovide Version 0.10.3
 - Neovim Version 0.9.0-dev

[neovide_rCURRENT.log](https://github.com/neovide/neovide/files/11006056/neovide_rCURRENT.log)

**Additional context**
Using default AstroNvim config files.
All LSPs installed through `mason.nvim`

**Comment by lukeemhigh** [comment]
Turns out it was an environment problem. I just set my PATH in `.zprofile` and the issue disappeared.

**Comment by dunix241** [comment]
> Turns out it was an environment problem. I just set my PATH in `.zprofile` and the issue disappeared.

Hi! Can you specify how you set your PATH?
