### ISSUE TITLE
--nofork option does not work in Windows

### ISSUE THREAD

**Issue by adamlopresto** [neovide/neovide#1814]
**Describe the bug**
--nofork option in Windows seems to be ignored

**To Reproduce**
1. Open a terminal (Windows Terminal, PowerShell, etc)
2. Run 'neovide --nofork'
3. Neovide starts in a separate window in the background, but another prompt is displayed immediately.

**Expected behavior**
Neovide starts in a separate window, but the command line knows that it's still running. Another prompt isn't displayed until the process is finished, and Neovide is exited.

**Desktop (please complete the following information):**
 - OS: Windows 10, Windows 11
 - Neovide Version: neovide 0.10.3
 - Neovim Version: NVIM v0.8.3

**Additional context**
Although it doesn't really matter from the command-line, that's a convenient test case. The real issue is that it prevents Neovide from being used as an external editor, because as far as the invoking program is concerned, Neovide exits instantly. There's no way to start it, watch its progress, and then read a temp file back after it quits.

**Comment by fredizzimo** [comment]
Since 0.12.0, neovide always forks on Windows, it's not optimal but a hybrid console/windows application can not be properly supported with just one executable.
