### ISSUE TITLE
Smooth Scrolling

### ISSUE THREAD

**Issue by huge-pancake** [neovide/neovide#1817]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Add smooth scrolling animation like [nvui](https://github.com/rohit-px2/nvui.git)

**Describe alternatives you've considered**

**Additional context**

**Comment by EpsilonKu** [comment]
It already has smooth scrolling. U need to run under `--multigrid` command

**Comment by huge-pancake** [comment]
sorry, i didn't notice that
