### ISSUE TITLE
Does not work with neovim nightly NVIM v0.9.0-dev-1278+g063e93864

### ISSUE THREAD

**Issue by yashamon** [neovide/neovide#1818]
The client just hangs, no response. Works fine with neovim 8.3. This is on windows 11, beta channel.

**Comment by collin-luma** [comment]
I'm seeing the same result on MacOS Monterey.  Neovide itself opens (blank window, no text), and I have access to the Neovide menu bar, but that's it:
<img width="723" alt="CleanShot 2023-03-29 at 00 16 24@2x" src="https://user-images.githubusercontent.com/104395748/228425361-c63975ad-ff9f-4412-b67b-3928c14199a4.png">

**Comment by letavocado** [comment]
Same issue

NVIM v0.9.0-dev-1305+g83bfd94d1
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3

**Comment by letavocado** [comment]
UPD https://github.com/neovide/neovide/issues/1804#issuecomment-1492498379

**Comment by collin-luma** [comment]
Building from the latest source (after the fix merged 2 weeks ago by @JakeHandsome ) fixed this problem from me.  [Here](https://neovide.dev/installation.html#mac-source) are instructions on how to build from source.  Thanks all!

**Comment by letavocado** [comment]
Neovim v0.9.0 released as [stable](https://github.com/neovim/neovim/releases/tag/stable). Issue is now also relevant for the stable version. Looking forward to your release! Thank you!

Cheers.

P.s. I love neovide! 😍

**Comment by LAST7** [comment]
Same issue occurs on stable version of Neovim v0.9.0. Hoping for a fix on that, appreciate for your work.

**Comment by letavocado** [comment]
@LAST7 it's already [fixed](https://github.com/neovide/neovide/pull/1800). Fix will be in the next [release](https://github.com/neovide/neovide/releases). For now, you can [build from source](https://neovide.dev/installation.html#linux-source) or downgrade neovim to a previous version. if you use pacman archlinux, you can downgrade via this command `sudo pacman -U /var/cache/pacman/pkg/neovim-{version}.pkg.tar.zst` In my case, previous version of neovim was '0.8.3-1-x86_64'.

**Comment by alexventuraio** [comment]
Same freezing error here, not sure if it is related to Neovide itself but these are the logs I get:

MacOS Ventura 13.2.1 (22D68)
Apple M1 Pro

```shell
➜  ~ nvim --version
NVIM v0.9.0
Build type: Release
LuaJIT 2.1.0-beta3

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/opt/homebrew/Cellar/neovim/0.9.0/share/nvim"

Run :checkhealth for more info
```

<img width="1139" alt="Screenshot 2023-04-08 at 15 47 26" src="https://user-images.githubusercontent.com/13169164/230743862-89d1a5db-c250-4c76-ac31-761e2fa3d458.png">

**Comment by Kethku** [comment]
This should be fixed in the new release. Please download it and try. If it is still broken please reopen this issue.

**Comment by alexventuraio** [comment]
> is still broken please reopen this issue.

All working fine for me, thanks!

**Comment by xarthurx** [comment]
Will this automatically be included in the `scoop` pkg manager or I need to submit a PR for that?
