### ISSUE TITLE
Neovide hangs when nvim exits unexpectedly

### ISSUE THREAD

**Issue by BatmanAoD** [neovide/neovide#1823]
#### Describe the bug
On Windows, when the `nvim` service exits, instead of closing the window, NeoVide hangs and becomes unresponsive.

#### To Reproduce
The easiest way is to have swap-files enabled and open the same file in two different windows, which causes the classic "Swap file...already exists" error, then pressing `a` for "(A)bort".

I'm not sure if this happens on all platforms, so I've used Windows path separators.

1. Open a file: `neovide ~\tmp\foo`
2. Open a second Neovide window with the same file: `neovide ~\tmp\foo`
3. Press `a` to abort the `nvim` process

#### Expected behavior
The Neovide window connected to the nvim session should close.

#### Screenshots
Immediately after nvim exits:
![image](https://user-images.githubusercontent.com/2313807/229376654-c7488123-2418-4b49-bcb9-54599f1488c0.png)

After Windows notices the process isn't responding:
![image](https://user-images.githubusercontent.com/2313807/229376668-be55d0ff-9413-4c89-8b5f-8d22858d9c00.png)

#### Desktop (please complete the following information):
 - OS: Windows 11 (stable)
 - Neovide Version: 0.10.3 (installed with Chocolatey)
 - Neovim Version: v0.8.0-1210-gd367ed9b2

#### Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:
I've attached this as a file.

[neovide_rCURRENT.log](https://github.com/neovide/neovide/files/11133231/neovide_rCURRENT.log)
199-f44e6731-b76d-44cd-a0fe-b3e916fe2a7b.png)

**Comment by fredizzimo** [comment]
This is fixed in Neovide 0.13.0 by:
* https://github.com/neovide/neovide/pull/2463

But, do note that there's a more generic hang at the exit on a few Windows systems.
