### ISSUE TITLE
Cannot install from source

### ISSUE THREAD

**Issue by toastmod** [neovide/neovide#1824]
**Describe the bug**
I'm trying to install from source through cargo, but `winapi` is missing `wincon`.

**To Reproduce**
1. Install from source using `cargo install --git https://github.com/neovide/neovide.git`
2. Observe error

**Expected behavior**
Source compiles successfully

**Screenshots**
not a screenshot but here's the output
```
error[E0432]: unresolved import `winapi::um::wincon`
  --> src\windows_utils.rs:13:9
   |
13 |         wincon::{AttachConsole, FreeConsole, ATTACH_PARENT_PROCESS},
   |         ^^^^^^ could not find `wincon` in `um`

For more information about this error, try `rustc --explain E0432`.
error: could not compile `neovide` due to previous error
error: failed to compile `neovide v0.10.3 (https://github.com/neovide/neovide.git#2766fe7f)`, intermediate artifacts can be found at `C:\Users\anumr\AppData\Local\Temp\cargo-installPOOwd1`
```

**Desktop (please complete the following information):**
 - OS: Windows 10 19045
 - Neovide Version 0.10.3
 - Neovim Version 0.8.1

**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**
N/A

**Additional context**
Already had Neovide installed, trying to update.

**Comment by Rafael-Conde** [comment]
I have the same error, I'm still looking for a solution, I'll update if I find something

**Comment by FreebeJan** [comment]
I ran into the same issue, does anybody have a solution yet?

**Comment by FreebeJan** [comment]
Found a solution that is pretty simple: https://github.com/neovide/neovide/pull/1831

**Comment by Kethku** [comment]
This should be fixed on main.
