### ISSUE TITLE
Window with height 0 causes panic at 'Could not create surface'

### ISSUE THREAD

**Issue by crides** [neovide/neovide#1830]
**Describe the bug**
`neovide` panics with `thread 'main' panicked at 'Could not create surface', src/renderer/rendered_window.rs:75:6` when trying to resize a window to min/0 height

**To Reproduce**
1. `neovide <file>` (any file is fine, apparently even non-existent ones)
2. `:sp <file2>`
3. `:tabe <file3>`
4. `:mks test.vim`
5. `:qa`
6. load the session (`neovide -- -S test.vim`)
7. go to the first tab, and the top window
8. `^W_` (make the current window the largest vertically)
9. panic

**Expected behavior**
The bottom window gets resized to 1-/0-high

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Arch
 - Neovide Version: `0.10.3`
 - Neovim Version: `0.8.3`

**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**
[neovide_rCURRENT.log](https://github.com/neovide/neovide/files/11182426/neovide_rCURRENT.log)

**Additional context**
The issue still happens with `-u NONE`

**Comment by fdev31** [comment]
Looks like #1669

**Comment by crides** [comment]
Yes it seems to have the exact same cause (`--multigrid` + `wmh`/`wmw`). Though the curious thing is I didn't explicitly set `wmh` (I didn't know about it until just now), but the session file sets it. Closing as the underlying issue is duplicated.
