### ISSUE TITLE
Panics immediately on any mouse movement

### ISSUE THREAD

**Issue by WhiskeyTuesday** [neovide/neovide#1833]
**Describe the bug**
I just built from source as per the docs and it panics on any mouse movement within the window

**To Reproduce**
1. launch
2. move mouse

**Expected behavior**
nothing

**Desktop (please complete the following information):**
 - OS: Pop_OS 22.04
 - Neovide Version 0.10.4
 - Neovim Version 0.6.1

**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**
file only contains one line, asserting that neovide is version 0.10.4

**Additional context**
running `neovide --nofork -- -u x` (to eliminate the possibility that it's my config) results in:

```
Neovide panicked with the message 'Mouse Input Failed: NeovimError(Some(1), "invalid button or action")'. (File: src/bridge/ui_commands.rs; Line: 69, Column: 18)
This is a bug and we would love for it to be reported to https://github.com/neovide/neovide/issues

Backtrace saved to neovide_backtraces.log!
Neovide panicked with the message 'Could not send serial ui command: SendError(MouseButton { button: "move", action: "", grid_id: 1, position: (101, 44), modifier_string: "" })'. (File: src/bridge/ui_commands.rs; Line: 253, Column: 22)
This is a bug and we would love for it to be reported to https://github.com/neovide/neovide/issues

Backtrace saved to neovide_backtraces.log!
Neovide panicked with the message 'called `Result::unwrap()` on an `Err` value: SendError(Serial(MouseButton { button: "move", action: "", grid_id: 1, position: (102, 44), modifier_string: "" }))'. (File: src/event_aggregator.rs; Line: 55, Column: 28)
This is a bug and we would love for it to be reported to https://github.com/neovide/neovide/issues

Backtrace saved to neovide_backtraces.log!
```

backtrace log:
```
2023-04-11 03:44:37 - Neovide panicked with the message 'Mouse Input Failed: NeovimError(Some(1), "invalid button or action")'. (File: src/bridge/ui_commands.rs; Line: 69, Column: 18)
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: <unknown>
  14: <unknown>
  15: <unknown>

2023-04-11 03:44:37 - Neovide panicked with the message 'Could not send serial ui command: SendError(MouseButton { button: "move", action: "", grid_id: 1, position: (167, 23), modifier_string: "" })'. (File: src/bridge/ui_commands.rs; Line: 253, Column: 22)
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: <unknown>
  14: <unknown>
  15: <unknown>

2023-04-11 03:44:37 - Neovide panicked with the message 'called `Result::unwrap()` on an `Err` value: SendError(Serial(MouseButton { button: "move", action: "", grid_id: 1, position: (166, 23), modifier_string: "" }))'. (File: src/event_aggregator.rs; Line: 55, Column: 28)
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: <unknown>
  14: <unknown>
  15: <unknown>
  16: <unknown>
  17: <unknown>
  18: <unknown>
  19: <unknown>
  20: <unknown>
  21: <unknown>
  22: __libc_start_main
  23: <unknown>
```

**Comment by edi9999** [comment]
Same thing for me !

It must be something new in version 0.10.4 since I installed this just yesterday.

**Comment by edi9999** [comment]
Could be linked to this change : 

https://github.com/neovide/neovide/commit/5b4ae91f28e1a06dd99303f3684371a69525c1ed

**Comment by edi9999** [comment]
This is my nvim version : 

```
$ nvim --version
NVIM v0.6.1
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by team+vim@tracker.debian.org

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

**Comment by Kethku** [comment]
That's certainly the issue. I won't be at my computer for a bit but I can try to get a hot fix going shortly. In the meantime, try updating nvim to 0.9

**Comment by edi9999** [comment]
I've tried with 0.7.2 of neovim which is the version provided in

```
sudo add-apt-repository ppa:neovim-ppa/stable
```

It didn't work either.


Now I'm going to try :

```
sudo add-apt-repository ppa:neovim-ppa/unstable
```

But I don't really like that cause I've had many issues in the past because of unstable neovim that was updated every day and had quite a few bugs.

**Comment by edi9999** [comment]
It indeed works with the neovim 0.9.0 version, however, I will rather fix my neovide version to 0.10.3 and neovim to 0.7.2

**Comment by arnoldmashava** [comment]
> neovide --nofork

I am encountering the same glitch and registering the same errors on openSUSE Tumbleweed with the latest `Release 0.10.4` of both the `neovide.tar.gz` Linux binary and the resulting `~/.cargo/bin/neovide` binary that is built from the source: `cargo install --git https://github.com/neovide/neovide`

**1. Linux Environment**:

```bash
~/.cargo/bin/lsb_release --all
LSB Version:    n/a
Distributor ID: openSUSE
Description:    openSUSE Tumbleweed
Release:        20230130
Codename:       n/a
```

**2. Rustlang Environment**:

```bash
~/.cargo/bin/cargo --version
cargo 1.70.0-nightly (7d3033d2e 2023-03-08)
```

**3. Neovim Ecosystem**:

```bash
~/.cargo/bin/nvim --version
NVIM v0.7.0
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by runner@fv-az316-460

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/share/nvim"

Run :checkhealth for more info
```

The `neovide_backtraces.log` echoes that of @WhiskeyTuesday and is therefore not necessary to replicate.

I have fallen back on the prior `Release 0.10.3`, which holds steady to the input from the mouse, but I am of the feeling that I could be missing out on the latest features and improvements.

Any hack to forge a continuous and decent dance with `Release 0.10.4` of neovide?

**Comment by WhiskeyTuesday** [comment]
Switching from 0.6.1 (installed with apt) to 0.9.0 (installed with bob) did indeed solve the problem for me

**Comment by bedaro** [comment]
I'm having the same problem. I'd like to point out that the [neovide website](https://neovide.dev/installation.html) says it's supposed to be compatible with nvim 0.6 or later, so upgrading nvim should not be necessary and I too don't want a bleeding-edge neovim.

**Comment by falcucci** [comment]
@bedaro as everyone else who had this problem, the workaround is upgrade your neovim to 0.9 at the moment.

@Kethku maybe we should write down a note that we highly recommend nvim 0.9?

**Comment by fredizzimo** [comment]
This was an oversight when we merged this https://github.com/neovide/neovide/pull/1766. It now requires Neovim 0.8. I believe that respecting the `mousemoveevent` option (which is default off, and unsupported on older versions) should fix this and also the terminal mode cursor issue mentioned above.

**Comment by Kethku** [comment]
Fixed
