### ISSUE TITLE
Frame Stutter on Scrolling

### ISSUE THREAD

**Issue by AI221** [neovide/neovide#1836]
**Describe the bug**
The frame stutters on scrolling in X11 or Wayland with XWayland

Wayland itself does not work.

**To Reproduce**
1. Use Ubuntu 22.10
2. Download Neovide 10.4
3. Try any combination of, with --multigrid enabled: --novsync --noidle, changing the refresh rate. Stutters with the wrong frame injected on scroll.

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.10
 - Neovide Version 10.4
 - Neovim Version 0.90

**Comment by fredizzimo** [comment]
This should fix it https://github.com/neovide/neovide/pull/1870

**Comment by MultisampledNight** [comment]
(fwiw Wayland should work already since 0.11, but I imagine the stutter won't be gone completely until #1977)
