### ISSUE TITLE
Mac: Function Keys from F13 to F19 don't work

### ISSUE THREAD

**Issue by apettel** [neovide/neovide#1840]
**Describe the bug**
Keys F13-F19 don't work on MacOS 13.3.1.

**To Reproduce**
1. Enter Command-Mode
2. Press e.g. F12 -> \<F12> gets displayed
3. Press F13 -> nothing happens

Mappings to the keys from F13 to F19 also don't work.

**Expected behavior**
Keys F13-F19 can be mapped by user.

**Desktop (please complete the following information):**
 - OS: MacOS 13.3.1
 - Neovide Version 0.10.4
 - Neovim Version 0.9.0
 
**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**
TRACE [neovide] Neovide version: 0.10.4

**Comment by fredizzimo** [comment]
Could you try the latest master. It's possible that the new winit keyboard update https://github.com/neovide/neovide/pull/1789 has fixed it. But if not, it is hopefully possible to fix now.

**Comment by quadruple-output** [comment]
I observe the same issue outside of neovide. I have a programmable keyboard, and I programmed the keys F1 to F20. I use BetterTouchTool to create key mappings, but whenever I press any of F13 to F19, BTT simply won't recognize them. I have the impression that this is a general MacOS issue, but I may be wrong, ofc.

**Comment by fredizzimo** [comment]
This should be fixed by #1899, it would be great if you can test that.

**Comment by apettel** [comment]
Works great. Also all combinations with shift, control, option and command work as well.
