### ISSUE TITLE
<M> or <A> can't be accepted in neovide.

### ISSUE THREAD

**Issue by chaozwn** [neovide/neovide#1843]
**Describe the bug**
i use <M> in neovide,but it can't receive command Option in macos system。

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. macOS 11.4]
 - Neovide Version [e.g. 0.6.0]
 - Neovim Version [e.g. 0.5.0]

**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**

**Additional context**

**Comment by OliverChao** [comment]
Do you set `neovide_input_macos_alt_is_meta `? see https://neovide.dev/configuration.html#macos-alt-is-meta

**Comment by fredizzimo** [comment]
This should be fixed by #1899, it would be great if you can test that.
