### ISSUE TITLE
new scroll delta broke smooth scrolling for me

### ISSUE THREAD

**Issue by emmanueltouzery** [neovide/neovide#1844]
**Describe the bug**
With 0.10.4 I don't have smooth scrolling. I enable multigrid, I get animations when I rotate windows for instance, but I do not have smooth scrolling.

**To Reproduce**
1. Enable multigrid --multigrid
2. Try smooth scrolling, like using `<C-e>` on a text file
3. Notice that the scroll is strictly line by line with the latest neovide git
4. Revert commit c19b142380325baf83461d806d23f8cfdc5e08bd from https://github.com/neovide/neovide/pull/1827 -- `git revert c19b142380325baf83461d806d23f8cfdc5e08bd`, and fix a conflict
5. recompile, try smooth scrolling again, now it works

**Expected behavior**
Smooth scrolling should work when multigrid is enabled.
Note that I had the smooth scrolling issue BOTH on wayland and X11.

**Screenshots**
-

**Desktop (please complete the following information):**
 - OS: Fedora 37, sway display
 - Neovide Version: 0.10.4 and daf5307953d87afabd2cea17bdf7cf1ca2f33dd3
 - Neovim Version 0.8.0

**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**
this is the log of the master code, without the commit reverted, smooth scroll is not working:
https://www.dropbox.com/s/wynvkpdpdeusj4i/smooth_scroll_bad.log?dl=0

**Additional context**
this is the log of the master code, with the commit reverted, smooth scroll is working:
https://www.dropbox.com/s/mkfhcq059uf8eed/smooth_scroll_ok.log?dl=0

**Comment by emmanueltouzery** [comment]
I also believe the person in this reddit thread possibly has the same issue than me:
https://www.reddit.com/r/neovim/comments/12ge8m9/any_neovide_multigrid_troubleshooting_tips/

**Comment by Manuzor** [comment]
For what it's worth, smooth scrolling still works for my setup:

- OS: Windows 11 (22H2)
- Neovide Version: 0.10.4 and daf5307953d87afabd2cea17bdf7cf1ca2f33dd3 (same as OP)
- Neovim Version: 0.9.0

**Comment by crispinb** [comment]
@emmanueltouzery and I are both on Linux (Fedora / wayland / mutter in my case).

**Comment by fredizzimo** [comment]
You will need Nvim 0.9.x for this, and the breakage seems to be delierate since it's documented on the PR https://github.com/neovide/neovide/pull/1827

**Comment by emmanueltouzery** [comment]
Ok this sounds great if it'll work out of the box with neivim 0.9. unfortunately I won't be able to test this this week. Maybe @crispinb can check whether that works for him and confirm whether he was in fact using 0.8. I can confirm I was in fact using 0.8 myself.
Maybe a comment could be added to the documentation to explain that 0.9 or newer is needed for smooth scrolling, to be honest it wasn't clear to me, not even reading the PR in question.

**Comment by crispinb** [comment]
I hadn't tried neovide again since I got the neovim 0.9 update, but have done so just now. I can happily confirm that smooth scrolling does now work for me as expected.

**Comment by emmanueltouzery** [comment]
confirming using 0.9.0 makes smooth scrolling work: closing the issue.
