### ISSUE TITLE
The flags `--maximized` and `--frame none` don't work together on Gnome

### ISSUE THREAD

**Issue by Revanee** [neovide/neovide#1845]
**Description**
The flags `--maximized` and `--frame none` don't work together on Gnome. Using them results in the
window not being maximized.

**To Reproduce**
1. Launch with `neovide --maximized --frame none`
2. See that the window is not maximized

**Expected behavior**
The window should be maximized as well as frameless.

**Desktop:**
 - OS: Manjaro Linux x86_64 with kernel 5.15.106-1-MANJARO
 - Neovide Version 0.10.4
 - Neovim Version v0.9.0

**Logs:**

```
TRACE [neovide] Neovide version: 0.10.4
DEBUG [neovide::bridge::command] Starting neovim with: Command { std: "/usr/bin/nvim" "--embed" "-p", kill_on_drop: false }
INFO [neovide::bridge::setup] Neovide registered to nvim with channel id 1
DEBUG [neovide::settings::window_size] Loaded window settings: Windowed { position: PhysicalPosition { x: 0, y: 0 }, pixel_size: Some(PhysicalSize { width: 800, height: 600 }) }
INFO [neovide::bridge] Neovim process attached
```

**Comment by fredizzimo** [comment]
Can you check with Neovide 0.11.0? Winit has been updated, which fixes a lot of things, so it's quite likely that this has been fixed as well.

**Comment by Revanee** [comment]
I checked with version `0.11.1` and it works! Also, when passing only `--frame none`, it launches maximized by default, so it's no longer even necessary to use `--maximized` as well.
