### ISSUE TITLE
Mouse cursor hightlighting doesn't work properly with split panes

### ISSUE THREAD

**Issue by BestClaws** [neovide/neovide#1846]
**Describe the bug**
moving the cursor around with mouse, highlighting doesn't work properly when using splits, nvim-tree etc., as the cursor movement is relative to top left corner of window and not buffer/pane

**To Reproduce**

just create vertical / horizontal splits and try moving the cursor in anything but top left buffer, see attached video

**Expected behavior**
highlighting in other split buffers should work properly, i.e., highlight what is selected.

**Screenshots**

https://user-images.githubusercontent.com/40067018/233655132-6718b010-b4a1-4d8f-a5ee-6ed25963faff.mp4

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Neovide Version : 0.10.4
 - Neovim Version: 0.9.0
 - 
[vi_rCURRENT.log](https://github.com/neovide/neovide/files/11296402/vi_rCURRENT.log)

**Comment by Kethku** [comment]
This is fixed and likely never happened with multigrid

**Comment by j-xella** [comment]
A duplicate of #1368 ?

**Comment by BestClaws** [comment]
Apparently. Yea. Tried looking through issues dint find any with my wording.

 thanks for update though I can get  back to thid editor happily now
