### ISSUE TITLE
Neovim ui not load on Windows

### ISSUE THREAD

**Issue by Jack253-png** [neovide/neovide#1854]
**Describe the bug**
When I open neovide, neovim not opened its ui but process is running

**To Reproduce**
Null

**Expected behavior**
The neovim ui open

**Screenshots**
![图片](https://user-images.githubusercontent.com/83895170/235353146-f1df97b1-9b0b-41f6-b763-f598e2a559af.png)
![图片](https://user-images.githubusercontent.com/83895170/235353158-356c3711-50c8-4980-9391-283812fa9b53.png)

**Desktop (please complete the following information):**
 - OS: Windows 11 22H2 build 22621.1555
 - Neovide Version 0.10.3
 - Neovim Version 0.9.0

**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**
TRACE [neovide] Neovide version: 0.10.3
(no more logs)

**Additional context**

**Comment by Jack253-png** [comment]
and it doesn't run on the WSL, it just runs on native windows platform.

**Comment by tamton-aquib** [comment]
Neovim 0.8.3 and all below versions works for me but 0.9 doesn't. (I am on a mac m1 pro)
Can you check that from your side too @Jack253-png ?

**Comment by Jack253-png** [comment]
yes, i tried neovim 0.8.3 and it is ok

**Comment by ykerit** [comment]
Your version should be 0.10.3, did the last installation not clean up @Jack253-png

**Comment by Jack253-png** [comment]
i use windows and config by my self，i can extract older versions and cover newer versions to change versions，or by editing env variables



| |
***@***.***
|
|
***@***.***
|




---- Replied Message ----
| From | ***@***.***> |
| Date | 05/02/2023 20:27 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [neovide/neovide] Neovim ui not load on Windows (Issue #1854) |

Your version should be 0.10.3, did the last installation not clean up @Jack253-png

**Comment by golanguage** [comment]
Yes. with nvim 0.9, neovide 0.10.1~0.10.3 can not work. Neovide 0.10.4 is nice.

**Comment by fredizzimo** [comment]
I think we can close this. Yes, Neovide Nvim 0.9.x requires at least version 0.10.4 of Neovide.

The issue was fixed by this PR https://github.com/neovide/neovide/pull/1800
