### ISSUE TITLE
No keyboard control when opened via sxhkd until swapping windows or clicking

### ISSUE THREAD

**Issue by MithicSpirit** [neovide/neovide#1856]
**Describe the bug**
This is very similar to #960, but that was closed due to difficulty with reproduction. I believe this should help. Particularly, it seems like only some ways of opening neovide cause issues (for me it's `sxhkd`, although others seem to also be having issue) 

**To Reproduce**
1. Use a tiling window manager under X11 (I am on qtile and haven't tested anything else, but #960 says it is necessary)
2. Install `sxhkd`, configure it to spawn neovide on some keybind, and start `sxhkd`
3. Press the keybind to spawn neovide
4. Try using the keyboard within neovide (nothing happens)
5. Do any of: swapping focus to a different window and back, resizing the neovide window, clicking on the neovide window, moving the mouse while hovering the neovide window (there are probably other things that work but these are the only ones I found)
6. Try using the keyboard within neovide again (should behave as normal)

**Expected behavior**
Keyboard should behave as normal on step 4.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Neovide Version: 0.10.4
 - Neovim Version: 0.9.0

**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**
[neovide_rCURRENT.log](https://github.com/neovide/neovide/files/11362675/neovide_rCURRENT.log) (didn't paste contents because file is 643 KiB).

**Comment by fredizzimo** [comment]
Can you test with the latest master https://github.com/neovide/neovide/pull/1789, updated Winit, and I think that might have fixed the issue?

**Comment by MithicSpirit** [comment]
I switched to wayland a few days ago so I can't really test this anymore. I'll be able to do so in a month or so when I have access to my old rig that's still running X. (Although I have been having issues with neovide running *at all* under wayland so I'll give this a shot anyways.)

@drasill and @kuviman reacted with :+1: to the original post so maybe they can test?
