### ISSUE TITLE
Neovide crashes when opening files with swapfiles

### ISSUE THREAD

**Issue by mathiasmellemstuen** [neovide/neovide#1861]
**Describe the bug**
If I open a file that has a swapfile, Neovide will immediately crash. 

**To Reproduce**
1. Create a new file with Neovide and save it to disk. '
2. Open another session of Neovide WITHOUT closing the first session, i.e. the first session is still open.
3. Open the saved file with the new Neovide session.

**Expected behavior**
N/A

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Neovide Version 0.10.4
 - Neovim Version 0.9.0

**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**
Logfiles are attached, including backtrace. 

[neovide_rCURRENT.log](https://github.com/neovide/neovide/files/11415409/neovide_rCURRENT.log)
[neovide_backtraces.log](https://github.com/neovide/neovide/files/11415410/neovide_backtraces.log)

**Comment by mkcode** [comment]
This happens for me on macOS as well:

Setup:

 * neovide: 0.10.4
 * neovim: 0.9.0
 * macOS: 12.6.3

[neovide_rCURRENT.log](https://github.com/neovide/neovide/files/11446733/neovide_rCURRENT.log)
[neovide_backtraces.log](https://github.com/neovide/neovide/files/11446735/neovide_backtraces.log)

**Comment by fredizzimo** [comment]
Do you use `nvim.noice` https://github.com/neovide/neovide/issues/1751?

**Comment by openersoft** [comment]
yes.

**Comment by openersoft** [comment]
> Do you use `nvim.noice` #1751?

yes

**Comment by fredizzimo** [comment]
@openersoft, then I think it should be fixed by updating it to the latest version. Could you confirm?

**Comment by fredizzimo** [comment]
I'm assuming this is fixed now, with the latest `nvim.noice` version. So closing this issue.
