### ISSUE TITLE
`--remote` support like original `gvim`

### ISSUE THREAD

**Issue by wzhliang** [neovide/neovide#1863]
Original gvim has an option `--remote` to send a file into an already opened GUI. It'd be nice to have this in neovide

See documentation here: https://vimdoc.sourceforge.net/htmldoc/remote.html

**Comment by wzhliang** [comment]
`brew install neovide` solved it

**Comment by fredizzimo** [comment]
This is a duplicate of https://github.com/neovide/neovide/issues/1293. `nvr` is a good workaround for now.
