### ISSUE TITLE
Add option to map only the `left option` key to meta on macOS

### ISSUE THREAD

**Issue by esamattis** [neovide/neovide#1877]
**Is your feature request related to a problem? Please describe.**

At the moment I'm unable to use Neovide because I cannot get the meta key working with being able type certain special characters. I use a finnish keyboard layout where for example `Option-8` is used to type `[`, `Option-shift-8` for `{` etc. 

To get the `<M-a>` style keybindings working I need to set `neovide_input_macos_alt_is_meta` to true but this makes me unable to type the above special characters because the Option keys now send the meta key to Neovide causing it to just exit from the insert mode.

**Describe the solution you'd like**

With iTerm2 and terminal Neovim I was able to solve this sending the meta key only from the Left Option key so I could use Right Option to type the special characters.

I'd like to be able to this in Neovide too.

**Describe alternatives you've considered**

I'm open to other workarounds / solutions too.

Ideally I'd like to be able tell Neovide/Neovim to bind actions directly to the "left option key" and not to the "meta key".

Or maybe allow configuring the macOs `fn` key as the meta key? I could just swap it with the left option using Karabiner Elements.

**Additional context**

iTerm2 options screen

<img width="335" alt="image" src="https://github.com/neovide/neovide/assets/225712/84acc407-ca14-4e84-beaa-cdfd47d43bf3">

---------------

Thank you for creating such a awesome tool! I'd really like be able make work for me :)

**Comment by esamattis** [comment]
Figured out a workaround: Neovide / Neovim supports binding keys to `<D-S-[key]>` which means `command-shift-[key]` so I just configured Karabiner Elements to emit `command-shift` from the Left Option key when Neovide is the "frontmost application" and used this helper to bind the keys

```lua
function meta_key(key)
    if vim.g.neovide then
        return "<S-D-" .. key .. ">"
    else
        return "<M-" .. key .. ">"
    end
end
```

so the Left Option key works the same in terminal Neovim and Neovide.

**Comment by fredizzimo** [comment]
We need to implement winit `OptionAsAlt`  https://github.com/rust-windowing/winit/pull/2887, instead of our custom `neovide_input_macos_alt_is_meta`, just call `window.set_option_as_alt`

With that we should also be able to remove all the customization for MacOS in https://github.com/neovide/neovide/blob/main/src/window/keyboard_manager.rs

**Comment by JamesWidman** [comment]
i just tested #2046 with a Finnish input source (where option + 8 yields `[` in other mac apps), and it seems to fix this issue. (However, my physical keyboard has a u.s. english layout.)
