### ISSUE TITLE
Support multiple NeoVim configs installed in different folders via "Neovim Config Switcher".

### ISSUE THREAD

**Issue by hopezh** [neovide/neovide#1879]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
We can use "[Neovim Config Switcher](https://www.youtube.com/watch?v=LkHjJlSgKZY)" to switch between multiple neovim configs installed in their respective folders. 

It will be great if Neovide can work hand-in-hand with this "switcher" so that it can be used for different configs, rather than just for the default one installed in the `~/.config/nvim` folder. 

**Describe alternatives you've considered**
Nil.

**Additional context**
Nil.

**Comment by fredizzimo** [comment]
I feel that this could be easier implemented outside Neovide, just like Neovim Config Switcher in itself, perhaps even implemented into that. But I think we need to support additional arguments 
as requested here https://github.com/neovide/neovide/issues/1810

**Comment by last-partizan** [comment]
I think, this is completely unrelated to neovide, and additional arguments is already supported.

```
Usage: neovide [OPTIONS] [FILES_TO_OPEN]... [-- [NEOVIM_ARGS]...]

Arguments:
  [FILES_TO_OPEN]...  Files to open (plainly appended to NeoVim args)
  [NEOVIM_ARGS]...    Arguments to pass down to NeoVim without interpreting them
```
