### ISSUE TITLE
lualine statusline does not show

### ISSUE THREAD

**Issue by reDpz** [neovide/neovide#1883]
**Describe the bug**

**To Reproduce**
1. open any file

**Expected behavior**
lualine should be visible

**Screenshots**
left is windows terminal, right is neovide
![image](https://github.com/neovide/neovide/assets/71374038/a7c5b0c5-0d89-4763-b824-b6505271a22a)

**Desktop (please complete the following information):**
 - OS: windows 10
 - Neovide Version 0.10.4
 - Neovim Version  0.9.0

**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**
I sent it as a discord attachment because my browser literally crashed when I tried to pastebin it, and I couldnt paste it here as it exceeded the 65536 character limit
https://cdn.discordapp.com/attachments/1055860948423938189/1113909092138897539/neovide_rCURRENT.log

**Comment by fredizzimo** [comment]
The terminal version also looks wrong, there's an empty line between the main window and the buffer, which should not be there. So, there might be a problem with the configuration.

Also, the examples are not comparable, one has a split, while the other doesn't.

**Comment by fredizzimo** [comment]
Could you report the bug to upstream neovim, if it still occurs? As mentioned the screenshot from the terminal is also wrong, so that should be reported there. And that most likely fixes Neovide as well.

**Comment by reDpz** [comment]
I'm sorry for being inactive but I was using neovim from scoop.sh, installed via winget and problem was solved. I'm not sure of the cause.
