### ISSUE TITLE
Multi-window support

### ISSUE THREAD

**Issue by xbladesub** [neovide/neovide#1890]
I'd like to know if there any plans to add multi-window support for macOS? Sometimes I want to send my DB manager (dadbod UI) and rest client to 2nd monitor instead of switching between tabs. 

If no - does it make any sense to run multiple Neovide instances or it's bad practice?

**Comment by Kethku** [comment]
Without more support upstream this is no. I frequently create multiple neovide instances without issue, so I don't see it as bad practice.

**Comment by Kethku** [comment]
Note we would love to do this, but upstream neovim doesn't really have a good story for creating multiple top level windows as far as I know. We intentionally do not control nvim window positions so as to more closely match the experience in terminal. So to support this we would need support for multiple top level grids which I don't believe is getting worked on.

**Comment by p0deje** [comment]
@Kethku It would be nice to be able to switch between Neovide instances just like a regular macOS application with multiple windows (Safari, iTerm). Right now it seems like macOS thinks that each Neovide instance is a completely separate application with its separate stack of windows. I am not sure if this is related to Neovim or it's the way Neovide.app is being packaged.

**Comment by Kethku** [comment]
This issue is tracked here: https://github.com/neovide/neovide/issues/1332

I think it has to do with the way the app is run currently. Neovide as its built today assumes heavily that there is one nvim process per app instance. It seems like Macos assumes that apps wont do that. To fix this would be a pretty big change that would likely require some help from somebody who actually has a mac machine. None of the current main contributors have a mac so thats probably not going to happen for a while

**Comment by fredizzimo** [comment]
Neovim actually do support multiple windows that would be completely compatible with Neovide

https://neovim.io/doc/user/api.html#nvim_open_win()
>  external: GUI should display the window as an external
   top-level window. Currently accepts no other positioning
   configuration together with this.

There's also a built-in keymapping for it https://neovim.io/doc/user/windows.html#CTRL-W_ge

We then receive the following UI event
> ["win_external_pos", grid, win]  
  Display or reconfigure external window `win`. The window should be
  displayed as a separate top-level window in the desktop environment,
  or something similar.

I think it's actually a bug to not implement it, it's part of the standard protocol without any extensions. And if you do
1. `:split`
2. `<CTRL-W>e`
3. `i` and type something, Neovim now thinks that the invisible external window is focused, the cursor is not visible for example

Of course these external windows are not full fledged Neovim instances, I'm not sure but I don't think they:
1. Have a cmd line
2. Can be split futher
3. You can open floating windows anchored to them (but this one I'm not sure about at all)

But I think you can:
1. Have a winbar
2. Switch buffers
3. Resize them completely independently from the main window

So at least for people with multiple monitors, it could be useful. And as mentioned we are actually required to implement it according to the specs, so re-opening this.

That said, it's not a small task to implement it, but I don't see any huge obstacles either.

**Comment by fredizzimo** [comment]
I added my comment to #https://github.com/neovide/neovide/issues/1332 and closing this again.
