### ISSUE TITLE
chinases can`t input with new keyboard api

### ISSUE THREAD

**Issue by obmutescences** [neovide/neovide#1897]
**Describe the bug**
chinases can`t input with new keyboard api in newest commmit

**Desktop (please complete the following information):**
 - OS: macos 13.4
 - Neovide Version main newest commit
 - Neovim Version 0.10.0
**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**

**Additional context**

**Comment by fredizzimo** [comment]
With #1899, this should work as before, but there's still no preedit, and the popup sometimes overlaps the text.
