### ISSUE TITLE
Language server isn't detected in PATH on Neovide (Windows 11 + WSL2)

### ISSUE THREAD

**Issue by Ruturajn** [neovide/neovide#1903]
**Describe the bug**
Hi, I'm facing an issue where Neovide doesn't pick up the path to the `clangd` language server and says that the server can't be spawned, whereas, in neovim, it is recognized and successfully attached to the buffer. I'm running Neovide on Windows with WSL2. 

**To Reproduce**
1. Install WSL2 + Ubuntu 20.04 on Windows 11
2. Install neovim v0.8.0 in WSL
3. Install the following plugins for the language servers, with `vim_plug`:
     ``` 
     Plug 'neovim/nvim-lspconfig'
     Plug 'hrsh7th/cmp-nvim-lsp'
     ```
5. Install neovide v0.10.4 on Windows
6. Run neovide with the `--wsl` flag.

**Expected behavior**
The `clangd` language server is up and running.

**Screenshots**
![image](https://github.com/neovide/neovide/assets/56625259/c467bd31-52aa-4254-942e-899a14d1da82)

**Desktop (please complete the following information):**
 - OS: Windows 11 + WSL2
 - Neovide Version: v0.10.4
 - Neovim Version:  v0.8.0-1210

**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**

**Additional context**

**Comment by fredizzimo** [comment]
This is most likely due to this https://neovide.dev/faq.html#neovide-is-not-picking-up-some-shell-configured-information

**Comment by Ruturajn** [comment]
Ohh ok. I'll try doing this. Thanks.

**Comment by Ruturajn** [comment]
That worked. Thanks a lot.

**Comment by GreatestOfAllTimee** [comment]
hey, neovide work fine in wsl using `neovide --wsl` command but how can I connect to wsl using ssh? I tried to use `neovide --server name@localhost` seems like not working. Using `--wsl` are fine but slow on my machines.
