### ISSUE TITLE
Neovide appimage fails to launch

### ISSUE THREAD

**Issue by thirstyice** [neovide/neovide#1909]
**Describe the bug**
Neovide appimage fails to launch

**To Reproduce**
1. Download appimage from https://github.com/neovide/neovide/releases/tag/0.10.4
2. Unzip appimage
3. `chmod +x` appimage
4. `./appimage'
5. Nothing happens

**Expected behavior**
Neovide to open

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu 23.04
 - Neovide Version 0.10.4
 - Neovim Version 0.9.1

**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**
```
TRACE [neovide] Neovide version: 0.10.4
DEBUG [neovide::bridge::command] Starting neovim with: Command { std: "/snap/bin/nvim" "--embed" "-p", kill_on_drop: false }
ERROR [neovide::bridge] Neovide requires nvim version 0.4 or higher. Download the latest version here https://github.com/neovim/neovim/wiki/Installing-Neovim
```

**Additional context**

**Comment by alexmario74** [comment]
Same issue on ubuntu 22.04.

I also build from source code, and have the same result.

Even with --log nothing is printed out.

**Comment by MultisampledNight** [comment]
Hi! I tried a blank Fedora installation, and the appimage seems to work just fine. Is it possible your shell is printing something during startup, such as an initial neofetch or just `echo`? If so, could you try without that? See also https://neovide.dev/troubleshooting.html.

**Comment by thirstyice** [comment]
Tried it on a fresh liveimage of ubuntu, neovide launched.
I guess now I've got to figure out what I've screwed up on my installation.
Any recommendations for how to figure out where I should be looking are more than welcome.

**Comment by thirstyice** [comment]
Update: looks like my nvim is throwing an error during launch, which neovide is probably trying to read as the version. I still need to figure out why nvim is throwing an error, but that's not a neovide problem.

Thanks for pointing me in the right direction!
