### ISSUE TITLE
Crash after using HopChar2 with nvim extension hop

### ISSUE THREAD

**Issue by SergoGansta777** [neovide/neovide#1910]
**Describe the bug**
The application closes without any warning immediately after using the hop extension for nvim. More precisely, using the HopChar2 function. This happens when using the shortcut or when calling the that command from the command line. That being said, everything is fine when used in vim from the terminal. 

**To Reproduce**
1. Install hop extension: https://github.com/phaazon/hop.nvim
2. Use HopChar2 with :HopChar2 or :HopChar2AC
3. Type first char of two
4. Look at closing

**Expected behavior**
Everything will work fine, as in a regular terminal

**Desktop (please complete the following information):**
 - OS: [macOS 13.4]
 - Neovide Version [0.10.4]
 - Neovim Version [0.9.1]

**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**
It's to big

**Comment by fredizzimo** [comment]
I think we need more information. Many users are probably running hop and you are the first to report this, so there must be something special. 

Could you check if you have `neovide_backtraces.log` file and attach that? For the actual log file, you can try to reproduce the issue as quickly as possible to avoid generating a too big log file. And attach the file to the message, maybe zipping it first instead of copy pasting.

And don't open any sensitive files with passwords and such, since the log files contain the buffer contents.

**Comment by SergoGansta777** [comment]
[neovide_rCURRENT.log](https://github.com/neovide/neovide/files/11829998/neovide_rCURRENT.log)
[neovide_r2023-06-22_10-10-06.log](https://github.com/neovide/neovide/files/11830000/neovide_r2023-06-22_10-10-06.log)
[neovide_backtraces.log](https://github.com/neovide/neovide/files/11829999/neovide_backtraces.log)

**Comment by fredizzimo** [comment]
Would it be possible for you to test with the main branch of Neovide? Neovim sends some event that we don't deal with properly, and the released version does not print enough information in the logs to determine what it is. So, I while ago I added better logging, but that's only in main still.

You can either build from source, or download the binaries from the CI https://github.com/neovide/neovide/actions/runs/5272313380

**Comment by SergoGansta777** [comment]
I have downloaded the binaries from your link

[neovide_rCURRENT.log](https://github.com/neovide/neovide/files/11830597/neovide_rCURRENT.log)
[neovide_backtraces.log](https://github.com/neovide/neovide/files/11830594/neovide_backtraces.log)
[neovide_r2023-06-22_10-56-38.restart-0000.log](https://github.com/neovide/neovide/files/11830596/neovide_r2023-06-22_10-56-38.restart-0000.log)

**Comment by fredizzimo** [comment]
It looks like it receives a `message_show` event with a missing `replace_last` argument. 

Do you have `noice.nvim` installed, that has caused problems before #1847, #1751 #1737? 

In that case you need to disable the messages view
```lua
require('noice.nvim').setup({
  messages = {
    view = false,
  },
})
```

I have not investigated the problems myself, but we need to find out why, either noice sends invalid messages or why it causes Neovide to send invalid messages.

**Comment by SergoGansta777** [comment]
Yes, this fixed my issue.  Thanks a lot!
