### ISSUE TITLE
Must Restart Neovide to See Newly-Installed Fonts

### ISSUE THREAD

**Issue by ewhac** [neovide/neovide#1911]
**Describe the bug**
`se gfn=*` does not list fonts that were installed after Neovide was launched.

I learned about the [IntelOne](/intel/intel-one-mono) font today.  So I installed it, then tried to load it into an already-running Neovide session.  Neovide couldn't find it, either via `se gfn=*` or by naming the font explicitly.

Quitting and restarting Neovide allowed it to be found and used.

**Desktop (please complete the following information):**
 - OS: Debian Sid
 - Neovide Version 0.10.4+ (built from Git top-of-tree as of 2023.06.22)
 - Neovim Version 0.9.1

**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**
( No such file was generated. )

**Comment by Kethku** [comment]
Skia-Safe doesn't expose the necessary apis to do this properly. So this is unlikely to get fixed
