### ISSUE TITLE
`Lspsaga term_toggle`'s inputting is lagging

### ISSUE THREAD

**Issue by FledgeXu** [neovide/neovide#1913]
**Describe the bug**
When I use the `:Lspsaga term_toggle`, neovide's inputting is lagging. But When I use the `:terminal`, everything is fine. And It seems that this bug only happens when I opened a buffer.

**To Reproduce**
1. run `:Lspsaga term_toggle`

**Expected behavior**
`:Lspsaga term_toggle`'s inputting should be as smooth as `:terminal`

**Screenshots**

https://github.com/neovide/neovide/assets/16664654/b52e825f-aa46-4e0d-8bc2-466b84c7893a

**Desktop (please complete the following information):**
 - OS: macOS 13.4.1 (22F82)
 - Neovide Version 0.10.4
 - Neovim Version 0.9.1
 - Boot arguments: `/opt/homebrew/bin/neovide --multigrid --frame transparent`

**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**
https://pastebin.com/HvsTmEW3

**Comment by Kethku** [comment]
I'm not running on macos, but I think this may be fixed on current main with the new update loop. Closing for now, but please reopen if the problem persists.
