### ISSUE TITLE
Wallpaper changes on fullscreen with transparency ( wl-roots Hyprland )

### ISSUE THREAD

**Issue by CarloCattano** [neovide/neovide#1918]
**Describe the bug**
neovide --multigrid ~/.config/hypr/hyprland.conf

**To Reproduce**
1. run neovide with or without multigrid 
2. make the window fullscreen
3. Background changes (swww)

**Expected behavior**
Background image stays the same

**Screenshots**
![image](https://github.com/neovide/neovide/assets/17380530/7de68894-d39e-421c-b908-af29e6689225)

![image](https://github.com/neovide/neovide/assets/17380530/03114e7c-4b0b-4ffe-8711-cdcaec3e1dd5)

**Desktop (please complete the following information):**
 - OS: Linux arch 6.3.9-arch1-1  x86_64 GNU/Linux
 -  hyprland-git r3026.738ec900-1
 - neovide 0.10.4
 - NVIM v0.9.1

**Comment by CarloCattano** [comment]
It does not happen on xwayland with ```env -u WAYLAND_DISPLAY```

**Comment by vaxerski** [comment]
that looks to me like neovide reports the `wl_surface` object as opaque even though it isn't and the optimizations kick in

**Comment by MultisampledNight** [comment]
Hi! Could you test from git main, by chance? Between the last release (0.10.4) and current git main, the windowing library Neovide uses has been updated with a pretty large step.

**Comment by CarloCattano** [comment]
Tried 7h ago manually compiled from git main.
The issue persists

**Comment by fredizzimo** [comment]
Could you also test https://github.com/neovide/neovide/pull/1870? There are a lot of changes to the transparency rendering.

**Comment by CarloCattano** [comment]
@fredizzimo  still happening at this commit 
```
commit c75e3632118a38ab0ebb948c1335ba23ceb8e91e (HEAD, origin/fsundvik/improve-render-loop)
Author: Fred Sundvik <fsundvik@gmail.com>
Date:   Wed Jun 21 15:48:30 2023 +0300

    Improve the scroll animation length documentation
```

**Comment by Suyashtnt** [comment]
> Could you also test #1870? There are a lot of changes to the transparency rendering.

using this branch. Background image does change, however there is no background blur for some reason. I am using `--multigrid`
![image](https://github.com/neovide/neovide/assets/45307955/cceeb0ff-00e0-4694-965c-33fab3cee6aa)

![image](https://github.com/neovide/neovide/assets/45307955/c320ecee-e218-45f6-b650-0e7e321dd4fc)

**Comment by fredizzimo** [comment]
Yes, the background blur is only applied behind floating windows, not between the desktop and the main application. I'm not sure if that's doable with Skia, and what performance implications it has, the Skia blur rendering that we are using is rather expensive already.

**Comment by Suyashtnt** [comment]
> Yes, the background blur is only applied behind floating windows, not between the desktop and the main application. I'm not sure if that's doable with Skia, and what performance implications it has, the Skia blur rendering that we are using is rather expensive already.

I mean in the fact that my compositor (hyprland) doesn't apply it's blur to the window. The terminal background blur is handled through hyprland, so I would expect neovide to also have hyprland's transparent background blur working

**Comment by CarloCattano** [comment]
Please let's focus on this issue. That is a different one

**Comment by CarloCattano** [comment]
The problem is gone after an update from neovide-git AUR 0.10.4
