### ISSUE TITLE
Transparency doesn't work on full screen mode (WSL)

### ISSUE THREAD

**Issue by AbdoOmarEg** [neovide/neovide#1919]
**Bug Description:**
The bug occurs when the application is in full-screen mode, causing the transparency feature to malfunction. In non-full-screen mode, the transparency works correctly.

**Steps to Reproduce:**
1. Launch neovide.exe with the command `neovide.exe --wsl --frame none`
2. Use the following Lua script:
```lua
if vim.g.neovide then
  vim.o.guifont = "CaskaydiaCove Nerd Font Mono:h12"
  vim.g.neovide_hide_mouse_when_typing = true
  -- vim.g.neovide_fullscreen = true
  vim.g.neovide_transparency = 0.7
end
```
or
3. Launch neovide.exe with the command `neovide.exe --wsl`
4. Use the following Lua script:
```lua
if vim.g.neovide then
  vim.o.guifont = "CaskaydiaCove Nerd Font Mono:h12"
  vim.g.neovide_hide_mouse_when_typing = true
  vim.g.neovide_fullscreen = true
  vim.g.neovide_transparency = 0.7
end
```
5. Observe the error.

**Expected Behavior:**
When the application is in full-screen mode or non-full-screen mode, the transparency feature should work consistently.

**Screenshots:**
If applicable, attach screenshots to help illustrate the problem.

**Desktop Information:**
- OS: Windows 11
- Neovide Version: 0.10.4
- Neovim Version: 0.9.0

**Additional Context:**
When taking screenshots it appeared transparent because the application is unfocused, but in reality, it has a black background.

log
https://drive.google.com/file/d/1lfAeaQoYNzV-SD6r1kYpXLKoBAPLRSO5/view

**Comment by AbdoOmarEg** [comment]
I don't know if it's a windows bug or a neovide bug
it's more likely a windows problem but I searched a lot and don't know how to fix it_

**Comment by fredizzimo** [comment]
Can you test if this PR works https://github.com/neovide/neovide/pull/1870? There are a lot of changes to the transparency rendering.

**Comment by AbdoOmarEg** [comment]
@fredizzimo, I'm new to GitHub, and I'm having trouble finding the branch `origin/fsundvik/improve-render-loop` to test the PR. Could you please provide some guidance or clarify how I can access the changes from the PR? Thank you!

**Comment by falcucci** [comment]
@AbdoOmarEg sorry if I sound rude but please, serach first about github stuff and focus in the issue itself here.

that said I believe that [this](https://cli.github.com/manual/gh_pr_checkout) can be the easiest way for you.

<img width="438" alt="CleanShot 2023-07-06 at 14 55 36@2x" src="https://github.com/neovide/neovide/assets/33763843/ad65665e-eba6-44d2-98c0-d858da790310">

**Comment by AbdoOmarEg** [comment]
@falcucci. Thank you for the help on how to do the pr,  I will make sure to look up the documentation more to understand gh and only focus on the issue here
