### ISSUE TITLE
Starting dir option

### ISSUE THREAD

**Issue by TakenMC** [neovide/neovide#1921]
**Is your feature request related to a problem? Please describe.**
Nope

**Describe the solution you'd like**
Adding a option in the config.toml that would make neovide use a custom starting dir etc. the home dir

**Describe alternatives you've considered**
Right now I just run cd on launch.

**Additional context**
Not really

**Comment by MultisampledNight** [comment]
Hi! The `cd` command is directly built into Neovim, which allows you to use `cd whereever/you/want/to/go` in your `init.vim`, see `:h cd`!

If you want to do so on the command line, you can pass cmdline options to Neovim directly through `--` which is listed when passing the `--help` flag, in this case as in `neovide -- -c 'cd whereever/you/want/to/go'`. Maybe we should add this forwarding in the commandline documentation on https://neovide.dev/command-line-reference.html.

**Comment by Kethku** [comment]
Closing as this is not for us to implement
