### ISSUE TITLE
file called "not" gets created on each run

### ISSUE THREAD

**Issue by justchokingaround** [neovide/neovide#1922]
**Describe the bug**
Every time I run neovide, a file called `not` gets created in the current working directory.

**To Reproduce**
1. Run neovide
2. Exit it
3. Run `ls`

**Expected behavior**
There should not be a file named `not` getting created.

**Screenshots**
![image](https://github.com/neovide/neovide/assets/44473782/b0f0b0b1-80fe-4a45-90b5-df490fb471ef)
![image](https://github.com/neovide/neovide/assets/44473782/c3fbf1dd-8260-4254-83b0-458cf25f7e29)

**Desktop (please complete the following information):**
 - OS: arch linux 6.4.1-arch
 - Neovide Version 0.10.4
 - Neovim Version v0.9.1

**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**
https://transfer.sh/ORHigFJlfu/neovide_rCURRENT.log

**Comment by MultisampledNight** [comment]
Hi, thanks for reporting!

That's _very_ interesting. Is `neovide` anything aliased to/taken precedence of in your shell? Could you run `neovide --nofork` with `strace` and look for `fopen`s?

**Comment by justchokingaround** [comment]
i don't understand the `with strace and look for fopens` part, sorry

**Comment by TobyBridle** [comment]
I also have this issue.

It seems like it's created on exit. Below is my `strace ./neovide --nofork` log
https://transfer.sh/0KNJSYYzF1/log

OS: EndeavourOS 6.4.3-arch1-1
Neovide Version: 0.10.4
Neovim Version: v0.9.1

**Comment by fredizzimo** [comment]
Hm, I can't find `not` in the logfile, maybe it's some other process, like some language server that creates it.

What happens if you change the permissions of the file, so that it's not writeable? Maybe that will cause something to crash, and easier to debug, for example some entries in `journalctl`

**Comment by justchokingaround** [comment]
after further debugging, it turns out this was a problem with a plugin i had in my config. removing the following from my config fixed the issue, sorry for the trouble:
```lua
  {
    "typicode/bg.nvim",
    lazy = false,
    cond = function()
      return os.getenv("NVIM_COLORSYNC") == nil
    end,
  },
```
