### ISSUE TITLE
crash if file has a .swp file

### ISSUE THREAD

**Issue by openersoft** [neovide/neovide#1924]
OS: Windows
Version: 0.10.4

Describe the bug:
     it crashes if a .swp file exist; and then nvim.exe will create a process and run in background.

     i open file with right mouse : "D:\Neovim\bin\neovide.exe" "%1"

**Comment by thirstyice** [comment]
Duplicate of #1861?

**Comment by fredizzimo** [comment]
Closing as duplicate, but with the question: do you use `nvim.noice` https://github.com/neovide/neovide/issues/1751?

Please answer in #1861
