### ISSUE TITLE
Dragging behaves strangely with split.

### ISSUE THREAD

**Issue by damhiya** [neovide/neovide#1927]
**Describe the bug**
When I open multiple splits in neovide and focused on non-primary pane (e.g. right split if the layout is vertical split), I can't use mouse dragging properly in visual mode. The dragging behaves as if the coordinate of the mouse pointer is relative to first pane though I focused on the second pane.

**To Reproduce**
1. Open a vertical split in neovide (Use `:vsplit` command)
2. Focus on the right split.
3. Open any file and try dragging using mouse.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: NixOS 23.11 (Linux kernel 6.3.11, x86_64)
 - Neovide Version : 0.10.4
 - Neovim Version : 0.9.1

**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**
```
TRACE [neovide] Neovide version: 0.10.4
```

**Additional context**

**Comment by MultisampledNight** [comment]
Hi! Are you using [multigrid](https://neovide.dev/command-line-reference.html#multigrid)? If not, could you try with it?

**Comment by damhiya** [comment]
> Hi! Are you using [multigrid](https://neovide.dev/command-line-reference.html#multigrid)? If not, could you try with it?

I tried it and the problem disappears with multigrid option.

**Comment by MultisampledNight** [comment]
Then I believe this is the same issue as https://github.com/neovide/neovide/issues/1368, thanks for confirming though!
