### ISSUE TITLE
Neovide snap libwayland-egl.so could not be loaded

### ISSUE THREAD

**Issue by thirstyice** [neovide/neovide#1932]
**Describe the bug**
Launching neovide doesn't work.
Terminal output:
```
thread 'main' panicked at 'Library libwayland-egl.so could not be loaded.', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/wayland-sys-0.28.6/src/egl.rs:48:37
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**To Reproduce**
1. Install neovim snap
1. Install neovide snap
2. `neovide`
3. See error

**Expected behavior**
Neovide to launch

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu 23.04
 - Neovide Version 0.8.0
 - Neovim Version 0.9.1

**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**
No log file created.
Terminal output (note that it is different than the terminal output above):
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: GlobError { path: ".", error: Os { code: 13, kind: PermissionDenied, message: "Permission denied" } }', /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/ops/function.rs:150:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Additional context**
I suspect that a dependency is missing, but I don't know which one. The `libwayland-egl1` package is already installed

**Comment by fredizzimo** [comment]
There are some big problems with the Snap packages, see here https://forum.snapcraft.io/t/need-help-with-the-snap-for-neovide/35978

The package is also very outdated (over a year old) ,and does not support Wayland yet.

Due to these issues we will probably remove the snap packages completely, until everything is resolved.

**Comment by fredizzimo** [comment]
Closing this, we wont look into snap issues until we get help

**Comment by danbrotherston** [comment]
This is almost 1 year later, and I am getting the same error when installing the Snap.

I would suggest that if the snap is not supported, it be removed from the installation instructions page here: https://neovide.dev/installation.html

**Comment by thirstyice** [comment]
See my PR #2674
