### ISSUE TITLE
Character after tilde swallowed on Mac (if second key requires shift or alt)

### ISSUE THREAD

**Issue by adrianhelvikspond** [neovide/neovide#1933]
**Describe the bug**
When I type ~/foo for instance, the output is ~foo.

**To Reproduce**
1. neovide -- -u NONE
2. Type ~ and then any character you need to hold shift to input
3. The character is ignored

**Expected behavior**
- When you type any special character involving shift after pressing ~, both characters should be emitted.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: MacOS 13.1
 - Neovide Version 0.10.4
 - Neovim Version 0.9.1

**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**

Log file after calling `neovide --log -- -u NONE` and typing `a~/<esc>:q!<cr>`

[neovide_rCURRENT.log](https://github.com/neovide/neovide/files/12042884/neovide_rCURRENT.log)

**Additional context**
I'm using a Norwegian keyboard. But as all other keys that require holding shift are also affected, I'm guessing it is related to that.

**Comment by adrianhelvikspond** [comment]
Checking the logs, I can see that the second character is not picked up by `TRACE [neovide::bridge::ui_commands]` as shown here, where I typed `i~/~/~/~/<ESC>:q!<CR>`.

```
TRACE [neovide::bridge::ui_commands] Keyboard Input Sent: i
TRACE [neovide::bridge::ui_commands] Keyboard Input Sent: ~
TRACE [neovide::bridge::ui_commands] Keyboard Input Sent: ~
TRACE [neovide::bridge::ui_commands] Keyboard Input Sent: ~
TRACE [neovide::bridge::ui_commands] Keyboard Input Sent: ~
TRACE [neovide::bridge::ui_commands] Keyboard Input Sent: <Esc>
TRACE [neovide::bridge::ui_commands] Keyboard Input Sent: :
TRACE [neovide::bridge::ui_commands] Keyboard Input Sent: q
TRACE [neovide::bridge::ui_commands] Keyboard Input Sent: !
TRACE [neovide::bridge::ui_commands] Keyboard Input Sent: <CR>
```

**Comment by adrianhelvikspond** [comment]
This looks related: https://github.com/rust-windowing/winit/issues/2898

**Comment by adrianhelvikspond** [comment]
Another clue is that the `~` isn't output when I don't follow it with anything. Sure enough, this is the only log item for `[neovide::bridge::ui_commands]` when I type `i~` and close the window.

```
TRACE [neovide::bridge::ui_commands] Keyboard Input Sent: i
```

Which makes sense, as it's an accent character.

This is the case for `~n`:

```
TRACE [neovide::bridge::ui_commands] Keyboard Input Sent: ñ
```

However `~w` is sent as one event, so I guess that's what we'll want in the bug case as well:

```
TRACE [neovide::bridge::ui_commands] Keyboard Input Sent: ~w
```

**Comment by adrianhelvikspond** [comment]
On a separate note, <S-Space> in a terminal outputs `;2u`

Repro: `:new term://bash<CR><S-Space>`

**Comment by fredizzimo** [comment]
The latest release is unfortunately quite broken on MacOS, but I think most of the things should be fixed on main. So it would be nice if you could build from source and try with that.

**Comment by fredizzimo** [comment]
Release 0.11.0 is out. I think that fixes the issue, can you test?

**Comment by adrianhelvikspond** [comment]
Looks good for my use case! 👍  Characters such as ñ produce n~ though, but that's not a problem for me.
