### ISSUE TITLE
self updating neovide binary 

### ISSUE THREAD

**Issue by kskarthik** [neovide/neovide#1935]
**Is your feature request related to a problem? Please describe.**

Users should be able to upgrade neovide binary downloaded via github releases. This is similar to what deno does with `deno upgrade` command.

**Describe the solution you'd like**
The neovide binary should self upgrade when there is a latest version available from github releases. I did a bit of search & this library achieves this https://crates.io/crates/self_update

**Some more thoughts**

* Only binaries downloaded from github releases should have this option enabled
* A build flag can be added to disable this feature for package maintainers
*  the cli flag can be `--upgrade` or  `-u`

**Comment by fredizzimo** [comment]
I don't think it should be integrated into the application itself.

Updating will soon be supported by the AppImage packages, using https://github.com/TheAssassin/AppImageLauncher for example. 

The snap packages also supports autoupdating, but there are some quite big problems with them at the moment, so we will probably remove them completely.

I don't know how the dmg images for macOS works, but there's probably some update support there as well.

Scoop for Windows already supports autoupdating. And Winget for Windows supports it as well, once all the issues are solved https://github.com/neovide/neovide/issues/1374

**Comment by fredizzimo** [comment]
I think we can consider this resolved through the various package managers now.
