### ISSUE TITLE
neovide --neovim-bin lvim renders font different from nvim binary

### ISSUE THREAD

**Issue by rpanachi** [neovide/neovide#1945]
This is a screenshot of `neovide --neovim-bin lvim config.lug`:

<img width="1728" alt="image" src="https://github.com/neovide/neovide/assets/51511/d81a8a85-4e5d-48d7-99dd-93e4dc6b4d4d">

And this is a screenshot of `neovide config.lua`:

<img width="1728" alt="image" src="https://github.com/neovide/neovide/assets/51511/4c94b3d3-3e2f-4f15-8195-311eedfd043d">

No matters the font I change on `config.lua`, the font don't change on neovide's GUI. On `config.lua` I had this for example:
```lua
if vim.g.neovide then
  vim.o.guifont = "Source Code Pro:h14"
end
```

My installation is pretty fresh, with default settings. I have the Nerd Fonts installed. Could you help me identify what's wrong?

**Desktop (please complete the following information):**
 - OS: macOS 13.4.1
 - Neovide Version: 0.10.4
 - Neovim Version: v0.9.1
 - LunarVim Version: 1.3

**Comment by fredizzimo** [comment]
Probably related to #1570. It does not seem to pick up the lvim configuration properly. Checkout the workaround in that issue if it helps.

**Comment by rpanachi** [comment]
Tried to launch neovide using the command below, but nothing changed:
```
neovide --multigrid -- -u /Users/user/.local/share/lunarvim/lvim/init.lua
```

The log file generated running `neovide --log` has almost 4MB. Could I grep for something specific to check if the configs are loaded correctly?

**Comment by fredizzimo** [comment]
Would it be possible to test this PR https://github.com/neovide/neovide/pull/1946. And starting with just `neovide --neovim-bin lvim`? I did not spot any problems when doing that myself.
