### ISSUE TITLE
Scrolling code (without enable mouse on in neovim 

### ISSUE THREAD

**Issue by 3Xpl0it3r** [neovide/neovide#1948]
Is possible neovide scrolling code like some terminal (eg. wezterm)behaviour , no need set  mouse option on in neovim config?

**Comment by fredizzimo** [comment]
What do you mean?, There are several ways of scrolling without the keyboard `<C-e>` / `<C-y>` or `<C-f>` / `<C-u>` for example. See https://neovim.io/doc/user/scroll.html

**Comment by 3Xpl0it3r** [comment]
thx ,got it
