### ISSUE TITLE
The input of Chinese characters always appears in italics.

### ISSUE THREAD

**Issue by 1538379200** [neovide/neovide#1950]
When I input Chinese characters in neovide, they always appear in italics, which makes the entire layout look less aesthetically pleasing.

- neovide: 0.10.4

- windows terminal
![image](https://github.com/neovide/neovide/assets/42434762/ea6cba2f-6654-4cdf-a747-a8ce87f219d5)

- neovide
![image](https://github.com/neovide/neovide/assets/42434762/2d495106-fbe0-46bc-b231-eab545144647)

**Comment by 1538379200** [comment]
They use the same font.

**Comment by fredizzimo** [comment]
I'm pretty sure this is your color scheme that makes strings italic. The configuration of that usually has an option to turn it off.

The reason why the Windows terminal does not render the text in italics, is because I believe it does not do fake italics, if the font does not support it.

**Comment by 1538379200** [comment]
Indeed, I reinstalled the plugin and it is now working fine
