### ISSUE TITLE
Incorrect cmd-c/cmd-v in docs

### ISSUE THREAD

**Issue by 9mm** [neovide/neovide#1953]
**Describe the bug**

The docs help somewhat to reproduce common mac hotkeys:

- copy, paste, save

But some are missing:

- cut. This one I took care of I think, and might be worth adding:

```
vim.keymap.set('v', '<D-x>', '"+d')         -- cut
```

And some appear to be wrong

- paste insert mode

This one is a super pain, ive been trying for awhile to improve it but I'm not having any luck.

I know it's probably not a huge priority as its not technically a 'bug' but I feel like its quite important as the entire reason for using a GUI is integration with the OS and not having to do everything through terminal.

The main problems are below:

**To Reproduce**

```
def hello
  puts "hi"
  <cursor>
end
```

The issue also occurs if the cursor has no space before it. The paste appears after 1 space in both cases, and not where the cursor was

**issue 2**

Multi line pastes from insert mode leave empty lines, as well as not putting the cursor at the end of the multi-line paste

**Desktop (please complete the following information):**
OS: macOS 13.4.1
Neovide Version 0.10.4
Neovim Version:

**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**

**Additional context**

[neovide_rCURRENT.log](https://github.com/neovide/neovide/files/12209681/neovide_rCURRENT.log)

**Comment by 9mm** [comment]
AHHHHH the "command mode" paste actually works so much better than whatever is in the docs.

I also added command+A for select all.

Here's my revised ones if anyone is interested

```
vim.keymap.set('n', '<D-w>', ':bd<CR>')   -- close window       
vim.keymap.set('n', '<D-a>', '<ESC>ggVG') -- select all         
vim.keymap.set('n', '<D-s>', ':w<CR>')    -- save               
vim.keymap.set('v', '<D-x>', '"+d')       -- cut                
vim.keymap.set('v', '<D-c>', '"+y')       -- copy               
vim.keymap.set('i', '<D-v>', '<C-r>+')    -- paste insert mode  
vim.keymap.set('n', '<D-v>', '"+P')       -- paste normal mode  
vim.keymap.set('v', '<D-v>', '"+P')       -- paste visual mode  
vim.keymap.set('c', '<D-v>', '<C-r>+')    -- paste command mode 
```

**Comment by 9mm** [comment]
I'm curious how I can get <D-q> to work however... that one still just immediately quits vim 

  vim.keymap.set('n', '<D-q>', ':q<CR>')    -- quit

**Comment by fredizzimo** [comment]
Yes, paste should this looks like 
```
vim.keymap.set('i', '<D-v>', '<C-r>+')    -- paste insert mode  
```

But you also need to `set paste` to enable the paste mode, in order to disable the formatting. And then `set nopaste` after you are done pasting. Note that for some reason Neovim 0.10 is going to deprecate `set paste`, see https://github.com/neovim/neovim/pull/22647. I noticed that when I was going to link to the documentation, but here's the Vim documentation, which still applies to nvim https://vimhelp.org/options.txt.html#%27paste%27

**Comment by 9mm** [comment]
@fredizzimo you are awesome, and extremely helpful. Thanks so much. Neovide really is great, I really appreciate all the work.

Do you happen to know btw how I can also remap command+Q instead of hard aborting neovim? it seems to be the only hotkey that i cant overwrite with something more graceful like `:q` (so it warns about unsaved changes)

**Comment by 9mm** [comment]
PS thats really awful about removing `paste`  mode...  hopefully they dont do that

**Comment by fredizzimo** [comment]
I don't think you will ever be able to remap `command+Q`, that seems to be something that is handled by the system on mac, But we should be able to fix https://github.com/neovide/neovide/issues/1279. But I can't do that myself, since I don't own a mac, and the last time I used one was almost 30 years ago.

**Comment by 9mm** [comment]
Ah ok, sweet. I'll just be careful until then.

**Comment by 9mm** [comment]
Ok I actually have one more question if you dont mind... i actually created an issue on SO about this but no one answered.

The problem is ... how do I actually set `nopaste`?

If I have my cursor like this:

```
if vim.g.neovide then

  local alpha = function()
    <CURSOR>
    return string.format('%x', math.floor(255 * (vim.g.transparency or 0.8)))
  end
```

Notice where the `<CURSOR>` is. Theres no way for me to enter Normal mode without losing the position.

For whatever reason,  it jumps to the beginning of the line of the line has spaces but it's blank.

This makes it really difficult to actually just enter insert mode RIGHT where normal mode is

Then I suppose I'd do something like this, if I could figure that part out:

```
:set paste<CR>i<C-r>+<ESC>:set nopaste<CR>
```

**Comment by fredizzimo** [comment]
There's actually another way, 
```
vim.keymap.set('i', '<D-v>', '<C-r><C-o>+')    -- paste insert mode  
```
https://neovim.io/doc/user/insert.html#i_CTRL-R_CTRL-O

I had completely forgot that this one existed, since I almost never paste in insert mode, at least not long text.

And to use `paste` you could run a normal mode command from insert mode with `<C-o>`, like this, but it's quite verbose and probably a bad idea if it's getting deprecated.

```
vim.keymap.set('i', '<D-v>', '<C-o>:set paste<CR><C-r>+<C-o>:set nopaste<CR>') 
```

And thinking about it, you could also run paste from normal mode like this
```
vim.keymap.set('i', '<D-v>', '<C-o>"+p') 
```

**Comment by 9mm** [comment]
Interesting, that appears to work.

Sadly, theres still cases where neither RO/RP indent properly,

simply taking something like this

```
{
  'filetype',
  colored = false,
  icon_only = false,
  icon = { align = 'right' },
}
```

and pasting it into a lua config file will not indent it properly

I've thought of maybe trying to just go back to the harder way of using marks and trying to `=` format it that way, but for now ive given up for the time being. this is excrutiatingly frustrating spending like 6 or 7 hours just trying to get things to paste.

Thanks for all your help

**Comment by 9mm** [comment]
I agree, totally.

In my switch to neovim, where I'm combing over every config with a fine-tooth comb and restructuring my brain (after all the whole point of switching to neovim is increase in quality of life), I decided to fix all the extreme annoyances that ive tolerated, nearly completely subconsciously, when using macvim for over a decade.

One of those is simply just pasting and it "just works", always. It's so engrained in my routine to re-format every single thing I paste, that I was like wait a second.......... why am I even doing this? VSCode garbage just pastes perfectly every time, why cannot I not have this.

I guess the answer is, I still cant, 😂💀

**Comment by 9mm** [comment]
if anyone wants further information that comes across this, this is my current solution, read this thread https://neovim.discourse.group/t/how-to-indent-what-is-pasted/4233
