### ISSUE TITLE
skia-bindings version fails to build on Asahi Linux (SIGBUS in build script)

### ISSUE THREAD

**Issue by mrhh69** [neovide/neovide#1954]
**Describe the bug**
skia-bindings v0.52.0 fails to build because the bindgen version (v0.60.1) gets a SIGBUS signal while running the build script.

**To Reproduce**
(might just be a problem with my machine)
1. Clone skia-bindings v0.52.0
2. Try to build

**Expected behavior**
Neovide uses a newer version of skia-bindings that builds successfully

**Desktop (please complete the following information):**
 - OS: Asahi Linux Gentoo (m1 air)
 - Neovide Version 0.10.4
 - Neovim Version 0.9.1

**Additional context**
skia-bindings version v0.57.0 builds correctly (and bindgen versions v0.62.0-0.63.0)

Not sure whether or not to file an upstream skia-bindings bug report (because this is an outdated version, and the problem is already fixed in master), so I'll just open one here.

**Comment by fredizzimo** [comment]
Skia will be updated as part of https://github.com/neovide/neovide/pull/1870, and it also enables binary compatible features, so that pre-built binaries are used instead of downloading from the source.

**Comment by mrhh69** [comment]
I tried the PR and it builds now, but only starts when using `LIBGL_ALWAYS_SOFTWARE=1`, here's the error trying to use normal GPU rendering:
```
Neovide panicked with the message 'Failed to create OpenGL context: Error { raw_code: Some(12297), raw_os_message: None, kind: BadMatch }'. (File: src/renderer/opengl.rs; Line: 117, Column: 10)
```
I'm not sure if this is an issue with the PR or the main repository, but it might also be because GL/EGL support on Asahi Linux is still pretty minimal. 
Is there a minimum required OpenGL/ES version to run from the PR?

**Comment by fredizzimo** [comment]
I don't know the exact requirements of Skia, but it's probably lower than what we currently request. 

Here https://github.com/neovide/neovide/blob/f85ae873517a8e198ed013457b7df7b8f229aa0f/src/renderer/opengl.rs#L113-L115 we request the core profile without arguments, which automatically requires OpenGL 3.3, which was released "March 11, 2010",  so I have been assuming it's compatible enough.

According to https://asahilinux.org/2023/06/opengl-3-1-on-asahi-linux/, it supports OpenGL 3.1 and OpenGles 3.0

So you could try either this

```diff
let context_attributes = ContextAttributesBuilder::new()
+   .with_context_api(ContextApi::Gles(Some(Version::new(3, 0)))
    .with_profile(GlProfile::Core)
    .build(Some(raw_window_handle));
```
or this
```diff
let context_attributes = ContextAttributesBuilder::new()
+   .with_context_api(ContextApi::OpenGl(Some(Version::new(3, 1)))
    .with_profile(GlProfile::Core)
    .build(Some(raw_window_handle));
```

**Comment by mrhh69** [comment]
Working after latest release, but I was getting linking errors when compiling neovide (related to skia), and it turned out I had to link the c++ std library 
```diff
diff --git a/build.rs b/build.rs
index 97f5693..4005f6a 100644
--- a/build.rs
+++ b/build.rs
@@ -1,4 +1,8 @@
 fn main() {
+    // Set the necessary linker flags to link the C++ Standard Library (libc++)
+    println!("cargo:rustc-link-lib=dylib=c++");
+    println!("cargo:rustc-link-lib=dylib=c++abi");
+
     #[cfg(windows)]
     {
         let mut res = winres::WindowsResource::new();

``` 
After that, and using glutin gles 3.0, everything works!

**Comment by ZerdoX-x** [comment]
@mrhh69 sorry for raising this up, but I am also trying to get neovide working on Asahi Linux.

For me it compiles with no problems, but performance is terrible. Do you encounter any issues? Which distro and which WM are you using?

I've raised #2008 where you can see an example with screenshot
