### ISSUE TITLE
globe icon in lspsaga

### ISSUE THREAD

**Issue by masha-sh** [neovide/neovide#1957]
**Describe the bug**
When using the "glepnir/lspsaga.nvim" plugin in Neovide, there are some globe icons which appear around the function

**To Reproduce**
1. Open a rust file
2. Wait for the LSP to start
3. Go inside of a function

**Expected behavior**
When using neovim in terminal, this doesn't happen, which is the expected behavior

**Screenshots**
Neovide:
![image](https://github.com/neovide/neovide/assets/141178891/94fe630f-f06f-497a-b709-f18a98cba169)
Neovim in terminal (expected behavior):
![image](https://github.com/neovide/neovide/assets/141178891/56cd0a82-a6aa-447c-ae72-9017f3ecdaa5)

**Desktop (please complete the following information):**
- OS: arch linux 6.4.7-arch
- Neovide Version 0.10.4
- Neovim Version v0.9.1

**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**
https://filetransfer.io/data-package/QhWhX5e8#link

**Comment by fredizzimo** [comment]
You probably don't have an emoji font installed. The character is supposed to be 💡, the "Electric Light Bulb Emoji", see https://wiki.archlinux.org/title/Fonts#Emoji_and_symbols

**Comment by masha-sh** [comment]
installing a package to have that emoji displayed, did work:
![image](https://github.com/neovide/neovide/assets/141178891/b9ac544c-7c0e-4276-bb8c-a605d17a7a2d)

however, i don't want it to be displayed at all, and i'm not quite sure why it appeared in the first place. maybe it's an issue with lspsaga, i'm not sure. the thing is that it only happens when i use neovide

**Comment by fredizzimo** [comment]
That's part of the lspsaga configuration https://github.com/nvimdev/lspsaga.nvim/blob/main/lua/lspsaga/init.lua and shows that there's some code action you can perform.

I suspect that the font issue was also the reason you did not see it in the terminal in the first place.

Closing, since this is not a Neovide issue.

**Comment by masha-sh** [comment]
yes, that's right, i fixed it by setting `code_action = ""`. thank you so much for helping me, even though it was outside of the project scope!
