### ISSUE TITLE
set size based on rows & columns

### ISSUE THREAD

**Issue by theotheroracle** [neovide/neovide#1958]
**Is your feature request related to a problem? Please describe.**
i want neovide to be a precise number of rows and columns, so it matches my terminals, and also the character limit i have set in neovim

**Describe the solution you'd like**
an option to define the rows and columns on start

**Describe alternatives you've considered**
figure out the size of each collum and row somehow and multiply by the amount i want ?
or just guess and check :/

**Additional context**
preferably a vim option and not an env variable if possible

**Comment by fredizzimo** [comment]
Hm.. It seems to be undocumented, but the main version supports both `--size` and `--geometry`. Geometry is coulms/rows, while size is pixels. The `neovide --help` shows both options. 

Note that the current release Neovide 0.10.4 only supports geometry, but the parameter is named size.

**Comment by theotheroracle** [comment]
ah ok thanks !

**Comment by fredizzimo** [comment]
Could you confirm that it works as you expect? I will still leave the issue open though until it's documented properly.

**Comment by theotheroracle** [comment]
hmm, it seems a little buggy, i can't seem to get it to the right width

**Comment by theotheroracle** [comment]
this is set to 84
![image](https://github.com/neovide/neovide/assets/20211219/b910e706-a8f3-410d-8da0-c51cdd4bb066)
this is set to 85
![image](https://github.com/neovide/neovide/assets/20211219/753ba39a-46e5-4250-8a99-aecee9e4586d)
it skipped a column ? 
but also, when it first opens it opens to the expected size, and then "jumps" to a smaller size
it's not %100 of the time though, sometimes it opens to the right size, but it's like every other time or so

**Comment by fredizzimo** [comment]
I will remove the documentation tag, since it's not just documentation issue. 

Part of the reason we switched to saving by pixel size was because it was more reliable. Probably because of issues like these. 

I don't see any reason why it couldn't be properly fixed though, we just need to get the calculations right, and there's probably also some kind of timing issue that needs to be fixed.
