### ISSUE TITLE
Create a desktop shortcut

### ISSUE THREAD

**Issue by Free-Aaron-Li** [neovide/neovide#1961]
**Describe the bug**

like title,
i want create a desktop shortcut,below is my code:

```desktop
[Desktop Entry]
Name=neovide
Exec=/home/myname/Software/neovide/neovide
Terminal=false
Type=Application
Icon=/home/myname/Software/neovide/neovide.png
```

If the Terminal option is set to true, a box is displayed. Just like the video I gave below. and if Terminal option is set to false,nothing happen.

https://github.com/neovide/neovide/assets/95997167/b6255f49-cc5d-4561-8a10-9ea9757f7607

**To Reproduce**

Video above

**Expected behavior**

I want to implement that when I open that desktop shortcut, neovide automatically jumps to the neovim main page I set up, just like using the command line in the shell

**Screenshots**

in command line in the shell:
![image](https://github.com/neovide/neovide/assets/95997167/22d90f7b-7f3a-4955-a22a-1d9271648aa7)

but,in desktop shotcut is nothing.

**Desktop (please complete the following information):**
 - OS: [Linux 6.1.32-amd64-desktop-hwe,OS:Deepin(like Debian)V23]
 - Neovide Version [0.10.4]
 - Neovim Version [0.9.1]

**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**
[neovide_r2023-08-04_23-01-04.log](https://github.com/neovide/neovide/files/12262040/neovide_r2023-08-04_23-01-04.log)
[neovide_rCURRENT.log](https://github.com/neovide/neovide/files/12262038/neovide_rCURRENT.log)

**Additional context**

**Comment by fredizzimo** [comment]
We don't have full documentation for it yet, but the preferred way of installing on Linux and creating desktop shortcuts is to use the AppImage, on the releases page, and use https://github.com/TheAssassin/AppImageLauncher to create the shortcuts and optionally handle updates.

I'm not sure if this solves your issue, but could you try that?

**Comment by Free-Aaron-Li** [comment]
very Sorry, even the appimage format executable file has the same effect as above. Maybe I should choose to wait for Neovide to grow

**Comment by SyedAhkam** [comment]
for me something like this works perfectly:

```desktop
[Desktop Entry]
Type=Application
TryExec=neovide
Exec=neovide
Name=neovide
```

although I haven't got the icon figured out myself.

**Comment by Free-Aaron-Li** [comment]
> 

sorry,in my operating system not work.
On my system, neovide must be enabled through a terminal

**Comment by GlekoMa** [comment]
@Free-Aaron-Li You need to use the `--neovim-bin` argument to make it work:

```
Exec=your_path/neovide --neovim-bin your_path/nvim
```

In Neovide version 0.10.4, clicking on its binary will result in no response (as shown in your video). However, in version 0.12.2 (the latest release), it will display a `nvim not found error` in its GUI, which is the crucial point.

Despite adding nvim to the $PATH (include set $NEOVIM_BIN), Neovide seems unable to find the nvim binary. As everything runs smoothly in Ubuntu 22.04, I consider this issue to be caused by the uniqueness of the deepin V23 Beta3 OS.

**Comment by Free-Aaron-Li** [comment]
@GlekoMa 
The good news is, with your advice, I've been able to run it successfully.
Sorry to give the results now, but I have been busy with other work recently and have not paid attention to the development of neovide.
This issue was resolved after the Deepin operating system I use was updated to the latest version.

**Comment by GlekoMa** [comment]
@Free-Aaron-Li Fine! 

Besides, I noticed that deepin OS doesn't honor the user's shell configuration, so adding nvim to it (e.g. /home/user/.bashrc) doesn't take effect. To make $PATH work, moving nvim to /usr/local/bin is a good choice.

I'm not a regular Deepin user, so I might be mistaken. Good luck!

**Comment by noppelmax** [comment]
In case anybody else is looking for this; I have put a gist here: https://gist.github.com/noppelmax/1e8d7eeac39ec4fb6bff4d0bc7091b64
