### ISSUE TITLE
maximized option set vim.o.lines and vim.o.columns is defered

### ISSUE THREAD

**Issue by Mr-LLLLL** [neovide/neovide#1965]
**Describe the bug**
when i set maximized = true in config.toml. and open neovide, plugin load vim.o.lines is not maximized, 
then opened neovide, print(vim.o.lines) in cmdline, vim.o.lines value is maxmized.
**To Reproduce**
1. set maximized = true in config.toml
2. open neovide, and print(vim.o.lines) in init.lua is not equal  max 
3. entered neovide, and call print(vim.o.lines) in cmdline, will print max value 

**Expected behavior**
when i open neovide, set vim.o.lines and vim.o.columns to max first when set maximized = true in config.toml

**Screenshots**

**Desktop (please complete the following information):**
 - OS: ubuntu 22.4
 - Neovide Version v0.10.0-dev
 - Neovim Version 0.11.0

**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**

**Additional context**
normal in neovide 0.10.4

**Comment by alex35mil** [comment]
@fredizzimo I don't think it is fixed or there's a regression that broke it again. I'm still getting non-maximized value of `vim.o.columns` on startup.
