### ISSUE TITLE
Bug: since 0.11, keybindings with two modifiers stopped working

### ISSUE THREAD

**Issue by chrisgrieser** [neovide/neovide#1968]
**Describe the bug**
Bug: since 0.11, keybindings with two modifiers stopped working. I haven't tried all combinations, but as far as I can tell this concerns keybindings with a letter and two modifiers.

**To Reproduce**
```lua
-- enable `cmd` key on macOS
vim.g.neovide_input_use_logo = true 

-- this worked before 0.11
vim.keymap.set("n", "<D-S-t>", ":echo 'foo'<CR>")

-- also tried this, does not work too
vim.keymap.set("n", "<D-T>", ":echo 'foo'<CR>")
```

**Expected behavior**
the keymap should work like before 0.11

**Desktop (please complete the following information):**
```
neovim 0.9.1 (homebrew)
neovide 0.11.0 (homebrew)
macOS 13.4.1 (M1)
```

**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**
[neovide_r2023-08-09_06-30-18.log](https://github.com/neovide/neovide/files/12298282/neovide_r2023-08-09_06-30-18.log)
[neovide_rCURRENT.log](https://github.com/neovide/neovide/files/12298289/neovide_rCURRENT.log)

**Comment by fredizzimo** [comment]
This is a known issue and tracked here https://github.com/neovide/neovide/issues/1237

**Comment by chrisgrieser** [comment]
hmmm, haven't searched the existing issues so far back, because this issue only occurred for me after updating to 0.11 🤔

**Comment by fredizzimo** [comment]
Sorry for that, it's mentioned in the release notes https://github.com/neovide/neovide/releases/tag/0.11.0. We tried to solve the issue before the release, but at the moment we have very few available developers in the Neovide organization that can develop for Mac (including me), so it took too much time, and we went ahead and did the release anyway.

The issue itself is a Winit (a library we use) issue, and should be reported there, I have the logs for `CMD+shift`, but it was also reported in the issue that `CTRL+shift` is not working either, so I still need a log for that, before I can report it.

**Comment by chrisgrieser** [comment]
oh, I see, I totally overlooked the "Breaking Change" section. (though "Breaking Changes" should really be at the top and not below "Bug Fixes" ;) )

Thanks for the hard work and no hurry! `<D-S-t>` is an inconvenience, but no dealbreaker.

**Comment by fredizzimo** [comment]
> oh, I see, I totally overlooked the "Breaking Change" section. (though "Breaking Changes" should really be at the top and not below "Bug Fixes" 😉 )

I updated the release notes to make it more clear.
