### ISSUE TITLE
Broken linux release link on the website

### ISSUE THREAD

**Issue by anisse** [neovide/neovide#1970]
**Describe the bug**

When visiting https://neovide.dev/, and clicking "Download for Linux", it points to https://github.com/neovide/neovide/releases/latest/download/neovide.tar.gz

**To Reproduce**
1. Go to neovide.dev
2. Click on Download for Linux
3. See 404 error

**Expected behavior**
A download starts

**Screenshots**

**Desktop (please complete the following information):**
 - Firefox

**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**
I wasn't able to download it

**Additional context**

The new release link is https://github.com/neovide/neovide/releases/download/0.11.0/neovide-linux-x86_64.tar.gz instead

**Comment by MultisampledNight** [comment]
Would tackle this now since someone else got tripped up, too.

**Comment by MultisampledNight** [comment]
Fixed in 4630103.
