### ISSUE TITLE
`neovide_remember_window_size` doesn't work properly when setting any `vim.g.neovide_padding*` size on macOS

### ISSUE THREAD

**Issue by rosingrind** [neovide/neovide#1972]
**Describe the bug**

I have the following configuration with window paddings set:

```lua
if vim.g.neovide then
    vim.g.neovide_remember_window_size = true
    vim.g.neovide_padding_top = 16
    vim.g.neovide_padding_bottom = 16
    vim.g.neovide_padding_right = 16
    vim.g.neovide_padding_left = 16
end
```

When any padding is set, some specific actions (changing config and restarting) may trigger resetting remembered window size. For example, after setting `vim.o.foldenable = true`, starting a new window works as described:

- if only default height was changed, it remembers height
- if width was changed, it completely resets/shrinks size

Setting `vim.o.foldenable = false` back will cause window size to be remembered. I can't point other specific settings to have any weight on this bug.

**To Reproduce**

1. Set `vim.g.neovide_remember_window_size = true`
2. Set `vim.g.neovide_padding*` to any number
3. Try to reopen window with `vim.o.foldenable = false/true` (possible reproduction variant)

**Expected behavior**

Window size should be remembered independently of window padding or any other settings.

**Desktop (please complete the following information):**
OS: macOS Ventura 13.5 (22G74)
NVIM: v0.9.1 Release
LuaJIT: 2.1.0-beta3
Neovide: 0.11.0 stable (brew cask)

**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**

Attaching log as file as it's to big to paste :/ [neovide_rCURRENT.log](https://github.com/neovide/neovide/files/12326208/neovide_rCURRENT.log)

**Additional context**

- while trying to pin-point the issue, I've noticed that it reproduces stable only with `foldenable = true`; changing other folding-related settings may shot the same bug (I'm using `lazy.nvim`, probably this is the cause)
- the issue is probably related to #620, or any startup buffer operations performed by nvim's folding mechanisms

**Comment by fredizzimo** [comment]
This is a bit strange since the windows sizes should be saved as pixels in Neovide 0.11.0. 

Can you check how `neovide-settings.json` is updated, and what it looks like. I think it's in `~/library/nvim` on macOS.

**Comment by rosingrind** [comment]
1. `foldenable = false` and quit remembers this (valid):

```json
{"window":{"Windowed":{"position":{"x":454,"y":82},"pixel_size":{"width":2092,"height":1454}}}}
```

2. `foldenable = true` and `open-close again` remembers this (invalid):

```json
{"window":{"Windowed":{"position":{"x":454,"y":50},"pixel_size":{"width":1600,"height":1200}}}}
```

3. Strange, but now you can change vertical window size and it will be saved (changing horizontal resets `pixel_size`):

```json
{"window":{"Windowed":{"position":{"x":454,"y":50},"pixel_size":{"width":1600,"height":1426}}}}
```

> I think it's in ~/library/nvim on macOS.

Actually it's on `~.local/share/nvim/`, may be useful for reproducing

**Comment by rosingrind** [comment]
After permanently setting `foldenable = true` and hours of tweaking another settings non-related to folding (and resizing the window), I've noticed that sometimes it may occasionally remember window size. Reset always happen again, but after some random events such as changing window size or crashing when starting up with incorrect lua config - I can't really point out the reason

**Comment by fredizzimo** [comment]
Thanks for the information, this will be really useful for tracking this down. But I don't see anything obvious in the code that would explain this, we always call `save_window_size` unconditionally at exit, and only at exit. And that seems to save what winit gives us with `window.inner_size()`

> Actually it's on ~.local/share/nvim/, may be useful for reproducing

Thanks, I don't use a Mac and just did a web search trying to find out how it maps the xdg base directory specification, which we are using, on macOS. Does `nvim` itself save the plugins and stuff there too. It's supposed to be the same folder, but I'm not sure why we are not using a dedicated `neovide` folder instead.

**Comment by rosingrind** [comment]
I think it's 100% reproducible on me, I'll leave 2 videos here just in case:

https://github.com/neovide/neovide/assets/108860307/d30d983a-c63f-4364-bac1-26679425151f

https://github.com/neovide/neovide/assets/108860307/9ce147be-5c23-4c06-a064-5788d5ba0f8a

> And that seems to save what winit gives us with window.inner_size()

Probably a `winit` bug? `alacritty`'s repo seems to pretty much have one's issues

**Comment by rosingrind** [comment]
Running `neovide -- --clean` from terminal while playing with additional `-c 'set [no]foldenable'` seems to always allow remembering window size successfully. Either my config is invalid somewhere, or some plugins are causing a havoc, but this part shouldn't really affect neovide's windowing.

I'll try to upload my config and envs later, when I'll ensure their validity, if it will still be related to this issue.

**Comment by rosingrind** [comment]
Setting any of [paddings](https://neovide.dev/configuration.html#padding) causes the window to randomly reset saved size:

```lua
vim.g.neovide_padding_top = 16
vim.g.neovide_padding_bottom = 16
vim.g.neovide_padding_right = 16
vim.g.neovide_padding_left = 16
```

I don't really know how changing `foldenable` stimulates this, but this may be another iceberg. For now, I think the cause is localized and probably reproduced anywhere.

**Comment by fredizzimo** [comment]
I tried to reproduce this on Windows but I'm unable to. It would be good to know if it's reproducible for someone else on macOS, since I'm unable to test that myself.

Given that Neovide don't deal with `foldenable` in any special way, I'm inclined to believe that is a timing related bug, and that the request to resize is not going through. `foldenable` probably changes the timings just enough for that to happen at least on the given system.

Furthermore, if I understand what's being said here correctly, it looks like the size is actually saved in the settings file, but it's not being honoured upon restart. Which further makes me think of timing related issues.

**Comment by 9mm** [comment]
I have OSX and this also occurs to me when I have padding set. I also have it running locally now if you ever need me to try experimenting with changing different things.

**Comment by 9mm** [comment]
@fredizzimo is there anything i can do to assist here? This is really the only -huge- annoyance left. Neovide is so freaking awesome in every other way though (thank you!) that I just tolerate it

Now that i have everything building locally, I'd be happy to experiment with settings or whatever youd need if you just tell me what to do or change

BTW here was my other issue about it https://github.com/neovide/neovide/issues/1580

**Comment by 9mm** [comment]
This also properly preserves window position in my case:

```
~/.cargo/bin/neovide -- -c 'set [no]foldenable'
```

**Comment by fredizzimo** [comment]
I think we should be able to fix this by creating the window with the correct size at the start instead of resizing it later. This should now be possible, since we store the window size as pixels, so we don't need to wait for the font before the window can be sized.
