### ISSUE TITLE
Command to draw focus to the neovide window

### ISSUE THREAD

**Issue by IndianBoy42** [neovide/neovide#1974]
**Is your feature request related to a problem? Please describe.**
I would like to be able to open files in an existing neovide window (already possible due to neovim rpc), and shift the window focus to that neovide window. For example I may be performing a git commit in another terminal which would ideally open the commit msg in the existing editor. or simply using the terminal to navigate directories and projects and opening files in a global neovide instance. Again all of this is mostly possible using the neovim rpc to open files. the missing link is to send the focus to that neovide window. 

**Describe the solution you'd like**
A neovim command `:NeovideFocus` that when invoked would tell neovide to tell the os/wm/wtv that the neovide window should be focused. Obviously this command would be pointless when run manually but could be invoked remotely using the rpc function `nvim_command`.

**Describe alternatives you've considered**
I'm not sure if three is, I think some level of support from the gui is necessary to implement this. For now I have to manually switch to the neovide window after opening files.

**Additional context**

[Kitty](https://sw.kovidgoyal.net/kitty/remote-control/#kitty-focus-window) and [Wezterm](https://wezfurlong.org/wezterm/config/lua/window/focus.html?h=focus) both have their own control protocols that allow this kind of pulling focus that allow the workflow described above to work.

**Comment by fredizzimo** [comment]
This should be possible to implement in a similar way as this https://github.com/neovide/neovide/pull/1971. But we are still in progress of reviewing to see if that's the solution we will go with.

**Comment by IndianBoy42** [comment]
Ah yes that is similar. Actually the variable based workflow could work too, and it would double as a variable for checking whether the neovide window is focused or not.

Something I just thought of related to window control is whether neovide has plans to support multiple windows into the same neovim instance ever? It would potentially be useful for multi monitor support or and just beingore flexible with using monitor space. I bring it up because then all of these windowing controls (focus, minimize, fullscreen etc) need to take arguments or be dictionaries

**Comment by fredizzimo** [comment]
> Something I just thought of related to window control is whether neovide has plans to support multiple windows into the same neovim instance ever?

We want to support that, but it's currently unclear how to do it. We need this or something similar to make it work https://github.com/neovim/neovim/pull/7541.

**Comment by Kethku** [comment]
Completed by #2058
