### ISSUE TITLE
neovide_underline_automatic_scaling set to target value instead of boolean

### ISSUE THREAD

**Issue by 9mm** [neovide/neovide#1976]
**Is your feature request related to a problem? Please describe.**
I think `neovide_underline_automatic_scaling` is a very nice feature for improving the visibility of undercurls and such.

Currently there are clipping issues that will be solved soon, but aside from that,  it would still be nice to be able to scale the size by a target factor rather than matching the current font size.

**Describe the solution you'd like**

Assuming it's based on the current font size as the intended plan, the option could work independently of that, like this:

`vim.g.neovide_underline_automatic_scaling = 14`

Or, just some arbitrary scale factor would also work

`vim.g.neovide_underline_automatic_scaling = 2.25`

**Describe alternatives you've considered**

I am quite happy with them currently, but I notice the default is way too hard to read:

<img width="408" alt="image" src="https://github.com/neovide/neovide/assets/1386207/5ea69d75-e4af-4efb-9b27-ae0f8a638b2a">

and the automatic scaled version is too thick, but still, quite nice I might add

<img width="465" alt="image" src="https://github.com/neovide/neovide/assets/1386207/0d7af2d7-e779-48c1-9b42-35c5ba6e368c">

**Additional context**

I don't consider this very important, but if it's not too much effort to change a boolean to a number value, then I think it might be a good addition

**Comment by Kethku** [comment]
Implemented in #2116

**Comment by 9mm** [comment]
Awesome, thank you!! @Kethku
