### ISSUE TITLE
Mouse drag (x,y) is wrong when tabs are visible

### ISSUE THREAD

**Issue by 9mm** [neovide/neovide#1986]
**Describe the bug**

On the rare occurances I want to drag and drop with the mouse, either because im drinking coffee in the other hand or what have you, the cursor is using the bottom of the arrow to drag instead of the point.

I cant take a screenshot of it because OSX hides the cursor, but in this screenshot look at the highlight. The tip of my mouse is actually on the dot if the `i` in the commented line above, NOT the current line where it's highlighted.

<img width="172" alt="image" src="https://github.com/neovide/neovide/assets/1386207/f3935878-d5a9-4f24-99aa-09cb75e85da6">

I went through and deleted every plugin and it went away when i disabled barbar. Then I tried without using any plugins at all and just making a new tab, and the problem occured, so I'm confident its neovide and not a plugin.

**To Reproduce**

1. open a new buffer
2. `:tabnew`
3. make several lines of text and drag, and you will see the mouse misbehaves when tabs are visible.

**Expected behavior**

The highlight should follow the exact tip of the cursor both in the case of tabs being visible and not visible

**Desktop (please complete the following information):**
 - OS: MacOS 13.5 (22G74)
 - Neovide Version neovide 0.11.1
 - Neovim Version:

NVIM v0.9.1
Build type: Release
LuaJIT 2.1.0-beta3

**Comment by 9mm** [comment]
Interestingly I JUST made this comment: https://github.com/neovide/neovide/pull/1977#issuecomment-1685310132

about something else, and now that `--multigrid` is on this problem went away

Multigrid seems to be the ultimate setting

**Comment by fredizzimo** [comment]
Is this the same issue as https://github.com/neovide/neovide/issues/1368?

**Comment by 9mm** [comment]
The initial issue, yes that looks like the same (sorry.. all these issues Im making I really am searching for it, I guess I have missed it)

Later replies in the thread though almost dont look like the same issue. Their text highlighting is VERY off, like multiple lines away.

Mine is was always exactly about 30px under wherever the tip of the point of the arrow cursor was though (like the person who opened the issue)

**Comment by 9mm** [comment]
Then again, my problem goes away when tabs are visible. In theirs, they dont have tabs, but they ARE using a window frame, and i'm using `--frameless`

So maybe their frame + no tabs is the same as my frameless + tabs?

<img width="288" alt="image" src="https://github.com/neovide/neovide/assets/1386207/4a5f9804-33b7-4d68-a14a-0926633f6be0">

**Comment by fredizzimo** [comment]
Can you add that last piece of information to https://github.com/neovide/neovide/issues/1368 and then close this issue? It's easier for us to track everything in one issue.
