### ISSUE TITLE
Cannot focus back on float window after focus on other program

### ISSUE THREAD

**Issue by xarthurx** [neovide/neovide#1988]
**Describe the bug**
On Windows, after opening a floating window (e.g. `Lazy`), if I mouse-click other program and click back, the cursor is always on the buffer behind the floating window -- I cannot focus on the floating window and close it.

In the end, I need to close the whole neovide itself.

This doesn't happen on `nvim-qt` -- I believe this is a neovide bug.

**To Reproduce**
1. Open a floating window (e.g. `Lazy`)
2. Click on some other program to make `neovide` loose focus
3. Click back on `neovide` to focus on the window
4. Cannot close the floating window

**Expected behavior**
I can focus on the floating window and close it.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Neovide Version: 0.11
 - Neovim Version 0.9.1

**Comment by fredizzimo** [comment]
This is a more general version of https://github.com/neovide/neovide/issues/1943.

The focus works properly if you use `neovide --multigrid`, so I suggest that as a workaround. The problem seems to be that we pass the wrong grid id, at least with my quick testing.


The documentation for `nvim_input_mouse` says that the grid should be zero when not using multigrid.
> {grid} Grid number if the client uses [ui-multigrid](https://neovim.io/doc/user/ui.html#ui-multigrid), else 0.

I did a quick hack and modified these two lines to hardcode `0` and that seems to fix the problem
https://github.com/neovide/neovide/blob/main/src/window/mouse_manager.rs#L192
https://github.com/neovide/neovide/blob/main/src/window/mouse_manager.rs#L229

Adding the "good first issue" tag, this should be easy to fix and test for someone that wants to contribute to Neovide.

**Comment by 9mm** [comment]
@fredizzimo So Ive been fighting with this issue a bit and I believe it still is broken with multigrid.

I did what you suggested with making sure its a neovide problem, and I think it is. It seems to work fine in neovim terminal, which doesnt support the mouse "focus" events, but clicking outside the window and clicking back in DOES work.

For starters im using floaterm:

```lua
return {
  'voldikss/vim-floaterm',
  keys = {
    {
      '<Leader>x',
      function() vim.cmd('FloatermNew --title=ZSH --floaterm_autoclose=2 --width=0.7 --height=0.4') end,
      desc = 'ZSH shell',
    },
    {
      '<Leader>z',
      function() vim.cmd('FloatermNew --title=LazyGit --width=0.95 --height=0.95 lazygit') end,
      desc = 'LazyGit',
    },
  },
}
```

So first, I press `<Leader>z` to bring up LazyGit.

As SOON as I move the mouse outside the window the bottom status bar changes from `--TERMINAL` to just blank.

At that exact moment, LazyGit stops responding to the `q` command. Which is strange, becuase I dont have to click. Simply moving the mouse outside the window stops it from working.

Im not sure if this is desired behavior or not, id like to disable that, but thats not actually the "bug"

When I move the mouse back INTO the window, it still wont respond to "q"

I need to press `<C-w><C-w><C-w><C-w>` 4 times and it will refocus the window, so `--TERMINAL` shows back up, and now i can press `q`

The bug I believe can be simply reproduced by just clicking outside the window, and clicking back in, and the window will not re-focus. On neovim in terminal, it refocuses immediately. On Neovide, the cursor appears in the window, but its actually "behind" the window.

I have tried both 'improve render loop' branch, and 'stable' release branch.

Here is part of my bash script which shows which ENV vars im loading before calling neovide.

```
export NEOVIDE_MULTIGRID=true
export NEOVIDE_FRAME=buttonless
export NEOVIDE_VSYNC=0
```

**Comment by xarthurx** [comment]
I'm recently using `nvim-qt` and found that they have resolved this issue quite nicely.
Probably look into their code base?

**Comment by fredizzimo** [comment]
@xarthurx
The fix should be trivial https://github.com/neovide/neovide/issues/1988#issuecomment-1685913726, but I don't have time to fix each tiny issue myself, so I added a "good first issue" for someone else to pick up. Multigrid will be the default soon, and that's where we concentrate all our development on.

@9mm, 
You are actually hitting a different issue, this one https://github.com/neovide/neovide/issues/1838. And after you click the terminal with the mouse it should work as long as you go back to terminal mode with `a`, `A`, `i`, `I` for example.

**Comment by 9mm** [comment]
oooooo...... Interesting.

Knowing I can use `a` or `i` is extremely helpful, also that I could just disable hover altogether... which I will do as I cant think of other things I'd want to use mousehover for

With that said... what actually makes the `mousemoveevent` ignore the floating window? Wouldnt it make sense if it floated back onto the window when the mouse is back over it? or is that not how it works. No need to really answer just curious if you feel like it.

Thanks again @fredizzimo i am forever gratful for all this awesome work.
