### ISSUE TITLE
Weasel's first Chinese input lags

### ISSUE THREAD

**Issue by MOldtime** [neovide/neovide#1989]
**Describe the bug**
When using [weasel](https://github.com/rime/weasel) to input Chinese, the first input will be stuck, and then it will be smooth. When Neovide is opened again, this situation will appear again.

**To Reproduce**
1. Installation `weasel`
2. Open `neovide`
3. Input Chinese

**Expected behavior**
The first time the input does not freeze

**Screenshots**
You can observe my keyboard input in the lower left corner. After I opened it twice, I paused for a while after typing Chinese and waited for the words to appear completely.

https://github.com/neovide/neovide/assets/38435967/3214a5e3-6e08-4ece-b319-d4759bba87a2

**Desktop (please complete the following information):**
 - OS: [WIndows11 23H2]
 - Neovide Version [0.11.1]
 - Neovim Version [0.9.1]

**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**
[neovide_rCURRENT.log](https://github.com/neovide/neovide/files/12394926/neovide_rCURRENT.log)
[neovide_r2023-08-21_18-05-51.log](https://github.com/neovide/neovide/files/12394927/neovide_r2023-08-21_18-05-51.log)

**Additional context**

**Comment by fredizzimo** [comment]
Does it work without delays in other applications? And are there any similar issues either closed or open in the repository https://github.com/rime/weasel/issues? I did not find anything myself using Google translate, but it's probably easier for someone that knows the language to find an existing issue.

**Comment by MOldtime** [comment]
> Does it work without delays in other applications? And are there any similar issues either closed or open in the repository https://github.com/rime/weasel/issues? I did not find anything myself using Google translate, but it's probably easier for someone that knows the language to find an existing issue.

I looked at the issues of `weasel` and found no such problems
Since this problem only occurs in `neovide`, I first thought of asking here
But your words reminded me, I decided to ask questions there too
