### ISSUE TITLE
mac m1 open error/unable to open

### ISSUE THREAD

**Issue by saikete** [neovide/neovide#1990]
**Describe the bug**
macOS m1 install the latest version of neovidide can not start / start error

**To Reproduce**
1. Build from source following the documentation/Download the dmg installation package
2.Open after security issues are resolved
3. The source code build crashed instantly/dmg cannot be opened after installation（img）
5. See error

<img width="925" alt="Snipaste_2023-08-22_14-21-31" src="https://github.com/neovide/neovide/assets/45237450/0167d33a-177b-4543-a97a-edc8185cc450">

**Expected behavior**

**Screenshots**
Building from source code or installing from dmg can be used normally

**Desktop (please complete the following information):**
 - OS: [e.g. macOS 14.0 Beta]
 - Neovide Version [e.g. 0.11.1]
 - Neovim Version [e.g. 0.9.1]

**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**
TRACE [neovide] Neovide version: 0.11.1
DEBUG [neovide::bridge::command] Starting neovim with: Command { std: "/bin/zsh" "-c" "/opt/homebrew/bin/nvim --embed -p", kill_on_drop: false }

**Additional context**
none

**Comment by brake** [comment]
Same for:
macOS 13.5.2
Neovim 0.9.1, 0.9.2

**Comment by fredizzimo** [comment]
I'm fairly certain this is one of the issues reported in https://github.com/neovide/neovide/issues/1373. Since you already build from source, it's probably the path that is set wrong. The thread mentions a couple of different ways to solve that.

**Comment by fredizzimo** [comment]
I'm closing this as a duplicate of
* #1373
