### ISSUE TITLE
NvChad dashboard does not show in NeoVide but works in Terminal

### ISSUE THREAD

**Issue by anantnrg** [neovide/neovide#1999]
**Describe the bug**
I'm using NvChad with the dotfiles [here](https://github.com/anantnrg/nvchad-conf/tree/main/lua/custom/chadrc.lua). If I start Neovim from WezTerm using `nvim`, then the usual NvChad dashboard shows. But if I start Neovide with `neovide`, then it shows the default Neovim help screen/dashboard. I've been trying to fix this because some times its annoying but mostly its harmless. If I run `Nvdash` after opening Neovide then it works okay.

**To Reproduce**
1. Install NvChad
2. Enable dashboard (`Nvdash`)
4. Restart/Open Neovide
5. Dashboard not shown

**Expected behavior**
The dashboard should be shown as it is in the terminal.

**Screenshots**
In WezTerm:
![11_04_42_08_30_2023](https://github.com/neovide/neovide/assets/47025756/0495cd14-8543-40b4-a668-d578f5c014a5)

In Neovide:
![11_04_45_08_30_2023](https://github.com/neovide/neovide/assets/47025756/6b20d973-889e-4454-a13e-9b07075810d5)

**Desktop (please complete the following information):**
 - OS: Artix Linux Zen kernel x86_64 Runit 
 - Neovide Version: Latest Git compiled from source (0.11.1)
 - Neovim Version: Latest Git compiled from source (0.9.0)

**Comment by MultisampledNight** [comment]
Hi, thanks for reporting! Could you possibly try https://github.com/neovide/neovide/pull/1985?

Also, sidenote for future issues/bug reports: Often times "latest" can be ambiguous, since it's possible that the repository has moved while you were creating the PR. Generally it's more clear to directly use the commit hash as displayed by `git log --max-count=1` instead.

**Comment by anantnrg** [comment]
Hey, I just tested this out and it works! Next time I report a bug, I'll make sure to include the commit hash. Thanks for the advice. I'll close this issue now :)

One more thing, I was just going through Neovide's codebase and I wanted to know how Neovide (or rather the renderers) handle Wayland compositors. Currently I'm using BSPWM and everything works as expected. I'm currently developing my own Wayland compositor using Smithay and when I open Neovide in that (using the Winit backend but mostly all the backends are similar) it glitches out, meaning the text isn't rendered correctly and all colors are black. Other apps like Kitty and WezTerm work fine but it may also be a problem on my part. Could you please tell me how you guys handle Wayland compositors and if there is any libraries or special code you guys use? Thanks.

**Comment by MultisampledNight** [comment]
On main, we just use winit (on a yanked version though, we'll need to update this sometime), which is also what alacritty uses. Do compare the versions of winit though, the `0.29` beta includes an update of wayland-client to 0.30 which was a complete rewrite.

In https://github.com/neovide/neovide/pull/1977 platform-dependent vsyncing is introduced, ontop of winit.

By the way, I'd encourage you to join the Discord linked in the repo readme, most likely you can get faster responses regarding questions about the code there.
