### ISSUE TITLE
Neovide doesn't respect `shortmess`

### ISSUE THREAD

**Issue by itaranto** [neovide/neovide#2005]
**Describe the bug**

The latest version of Neovide (0.11.1) doesn't seem to be respecting the `shortmess` option.

In my case, I disable the intro screen by doing:

```lua
vim.opt.shortmess:append('I')
```

**To Reproduce**

1. Open Neovide
2. See the welcome screen

**Expected behavior**

An empty buffer should be displayed.

**Screenshots**

Bad welcome screen (Neovide)
![image](https://github.com/neovide/neovide/assets/11463919/8f05fa10-b763-470a-b6a6-6e949aeae4c1)

Good welcome screen (Neovim from the terminal)
![image](https://github.com/neovide/neovide/assets/11463919/8a7b7124-7be3-4eab-8eb8-4e633be89963)

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Neovide Version: 0.11.1
 - Neovim Version:  v0.9.1

**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**

[neovide_r2023-08-30_23-49-29.log](https://github.com/neovide/neovide/files/12481719/neovide_r2023-08-30_23-49-29.log)
[neovide_rCURRENT.log](https://github.com/neovide/neovide/files/12481713/neovide_rCURRENT.log)

**Additional context**

Reproduced in Sway (Wayland) and i3 (Xorg).

**Comment by fredizzimo** [comment]
This should be fixed on main with https://github.com/neovide/neovide/pull/1985
