### ISSUE TITLE
Transparency doesn't work with pure white (#FFF) or black (#000)

### ISSUE THREAD

**Issue by D00mch** [neovide/neovide#2006]
When `neovide_background_color` has 'F' or '0', alpha modifier doesn't apply for some reason (example: `#ffffffea`).
`#f2f2f2ea` will be a little bit more transparent , because it has only 3 'F', and `#e5e5e5ea` will shine in transparency as it doesn't have 'F' at all.

`ea` in the examples above is just a 0.92 transparency postfix (see the example below):

```lua
local function alpha()
  return string.format("%x", math.floor(((255 * vim.g.transparency) or 0.8)))
end

local function make_transparent(dark)
  vim.g.neovide_transparency = 0
  vim.g.transparency = 0.92
  if dark then
    vim.g.neovide_background_color = ("#0f1117" .. alpha())
  else
    vim.g.neovide_background_color = ("#ffffff" .. alpha())
  end
end
```

It used to work before, I don't know why it stopped working. The only thing I did — I migrated from packer to lazy, but the code related to transparency is the same.

```
Neovide 0.11.1

NVIM v0.9.1
Build type: Release
LuaJIT 2.1.0-beta3

OSX Ventura 13.2
```

**Comment by falcucci** [comment]
@D00mch thank you for the report, but the `neovide_background_color` option has been [deprecated](https://github.com/neovide/neovide/pull/2168).
