### ISSUE TITLE
Panics on Asahi M1, OpenGL 3.1

### ISSUE THREAD

**Issue by ZerdoX-x** [neovide/neovide#2008]
**Describe the bug**
25-30 FPS (Fullscreen, 2560x1600@60)

**To Reproduce**
I guess can only be reproduced on M1/M2 machine with any asahi distro installed.

**Expected behavior**
Acceptable performance, no input delay.

**Screenshots**
![image](https://github.com/neovide/neovide/assets/49815452/f8c8cb01-5d9b-4650-8cf8-d3654e8ea6f6)
Screenshot for half sized window, so FPS is a bit higher

**Desktop**
Hardware: MacBook Air (M1, 2020)
OS: Gentoo (6.4.0-asahi-6-arm64)

WM: Hyprland 0.28.0
Video drivers: mesa-23.2.0_pre20230812 (it's been really good since asahilinux.org team implemented OpenGL 3.1 - you can even [run games](https://asahilinux.org/2023/06/opengl-3-1-on-asahi-linux/) on it). I have no issues with WM animations/effects, WebGL (figma, etc), and all other software works fine, didn't try any games yet tho.

Nvim: Built from source (9999 from gentoo overlay)
v0.10.0-dev-1012+g597355dea-dirty
Build type: Release
LuaJIT 2.1.0-beta3

**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**
https://0x0.st/Hp4t.log

**Additional context**
As in https://github.com/neovide/neovide/pull/1977#issuecomment-1703736102 and https://github.com/neovide/neovide/pull/1977#issuecomment-1703773083

Currently the only workaround is to compile this instead: https://github.com/ZerdoX-x/neovide (or patch neovide yourself)

**Comment by ZerdoX-x** [comment]
@fredizzimo I tried recompiling from [my fork](https://github.com/ZerdoX-x/neovide/tree/improve-render-loop). The same result in both branches. By looking at the neovide process and it's CPU usage I can probably tell that it's still using software rendering. Any ideas?

<details>
<summary>Screenshot</summary>

![image](https://github.com/neovide/neovide/assets/49815452/c2fe08ae-4353-4f85-9f9a-ac715b708b29)

</details>

**Comment by fredizzimo** [comment]
It looks like it only has OpenGL ES 3.0, but OpenGL 3.1 and your branch seems to use OpenGL ES currently (contextapi::Gles). Try changing either the version or mode.

**Comment by ZerdoX-x** [comment]
> Try changing either the version or mode.

Oops. Yeah, my bad. I made attempts [here](https://github.com/ZerdoX-x/neovide/commits/zerdox) on `zerdox` branch.

After recompiling with `cargo install --git https://github.com/ZerdoX-x/neovide --branch zerdox` nothing really changed. Maybe Gles 3.0 works even worse.

Any ideas how can we debug this and find out what is going on?

**Comment by fredizzimo** [comment]
You could try adding `prefer_hardware_accelerated(Some(true))` here https://github.com/neovide/neovide/blob/598f7779a404b729de33d748780e5be0de0197d5/src/renderer/opengl.rs#L69C32-L69C32

If that does not help, I think you somehow need to iterate the configs here https://github.com/neovide/neovide/blob/main/src/renderer/opengl.rs#L60, and select the correct one. But I'm not sure what to base the selection on.

**Comment by ZerdoX-x** [comment]
@fredizzimo thank you for your support and advices. First one didn't work and second either (it had only 2 configs, default and one which worse)

I found that my `eglinfo | grep "driver name"` should mostly output `apple` and `asahi`:
```
EGL driver name: apple
EGL driver name: asahi
EGL driver name: asahi
EGL driver name: asahi
EGL driver name: swrast
```
My previous output was like this:
```
EGL driver name: kms_swrast
EGL driver name: swrast
EGL driver name: asahi
EGL driver name: asahi
EGL driver name: kms_swrast
EGL driver name: swrast
```
Now I also don't receive any warnings about missing dri's in my system from other software.

So that was fault on my side, I had to properly configure kernel. After I properly configured my setup and upgraded to new mesa: https://rosenzweig.io/blog/first-conformant-m1-gpu-driver.html (which included new gles 3.1)
I successfully launched neovide with over 1400 FPS

The only thing I changed is opengl(es) version as you advised in https://github.com/neovide/neovide/pull/1977#issuecomment-1703773083 and https://github.com/neovide/neovide/issues/1954#issuecomment-1662036901

I tried several versions and here are my results:
OpenGL 3.1 - black screen, could not see any graphical or console output
OpenGL 3.0, OpenGL ES 3.1, OpenGL ES 3.0 - works great

I will leave gles 3.1 in my fork.

Also after properly configuring my system neovide stopped falling back to software rendering and started panicking:
```
Neovide panicked with the message 'Failed to create OpenGL context: Error { raw_code: Some(12297), raw_os_message: None, kind: BadMatch }'. (File: src/renderer/opengl.rs; Line: 117, Column: 10)
```

**Comment by ZerdoX-x** [comment]
Now I just would like to know how we can solve this for the rest

I guess it's either downgrading or maintaining my fork and mentioning it on https://github.com/neovide/neovide/blob/main/website/docs/installation.md and https://github.com/AsahiLinux/docs/wiki/Broken-Software

**Comment by fredizzimo** [comment]
I think downgrading might be fine. But I'm not sure if we should go with OpenGL or OpenGL ES. Another option is to add a command line parameter to specify the version. 

I need to do some investigations, if there are some performance hits or limitations on other platforms if we do so.

**Comment by ZerdoX-x** [comment]
> I think downgrading might be fine.

Is it possible to detect somehow? Like.. other software works fine. Alacritty renders on GPU for example.

> But I'm not sure if we should go with OpenGL or OpenGL ES

OpenGL ES is for mobiles so I guess it should be OpenGL. Or gl vs gles also might be dynamic, if device is mobile for example

> Another option is to add a command line parameter to specify the version.

I think that's one of the simplest and safest solutions for now. I would just put it in `.desktop` file and forget about it

**Comment by ZerdoX-x** [comment]
rust_windowing/glutin maintainer wrote this:
