### ISSUE TITLE
Out of memory crash in WinitWindowWrapper::draw_frame()

### ISSUE THREAD

**Issue by glibg10b** [neovide/neovide#2011]
**Describe the bug**
Neovide crashes occasionally.

These crashes occur when Neovide has been running for a while and always happen right after keyboard input. This particular one occurred immediately after typing `:w` and hitting Enter.

**Desktop (please complete the following information):**
 - OS: Gentoo Linux 2.23 (Linux 6.1.41)
 - Neovide Version 0.11.0 (*profiling* profile)
 - Neovim Version v0.9.1

**`neovide --log` (not after a crash):**
[neovide_rCURRENT.log](https://github.com/neovide/neovide/files/12506169/neovide_rCURRENT.log)

**Additional context**
Core dump:  [core.tar.gz](https://github.com/neovide/neovide/files/12506174/core.tar.gz)
Full backtrace:  [backtrace.txt](https://github.com/neovide/neovide/files/12506202/backtrace.txt)

**Comment by fredizzimo** [comment]
All the mainline versions of Neovide use quite much GPU memory, so that's most likely the reason. This will be fixed by https://github.com/neovide/neovide/pull/1977

**Comment by glibg10b** [comment]
@fredizzimo That could be it, considering I have integrated graphics with 8GB of RAM. I'll open a new issue with a fresh backtrace if the issue persists after the merge
