### ISSUE TITLE
Neovide freezes when trying to overwrite a file

### ISSUE THREAD

**Issue by SergoGansta777** [neovide/neovide#2013]
**Describe the bug**
If you edit a file in neovide and try to save a file that was saved outside of neovide, then the application freezes, nothing can be done, the document is not saved if forced to close

**To Reproduce**
1. Open any file with neovide
2. Open that file in another editor
3. Edit that file in another editor and save the changes
4. Return into neovide and save file 
5. Now you can't do anything

**Expected behavior**
You can see a warning like in terminal neovim. Screenshot below.

**Screenshots**
<img width="720" alt="CleanShot 2023-09-06 at 19 40 26@2x" src="https://github.com/neovide/neovide/assets/98104790/6b2412fd-f4f3-4c6e-81a6-767cdfb19cdf">

 - OS: Ventura 13.5.1
 - Neovide Version: 0.11.1
 - Neovim Version: 0.9.1

**Comment by SergoGansta777** [comment]
[neovide_r2023-09-06_19-43-16.log](https://github.com/neovide/neovide/files/12540460/neovide_r2023-09-06_19-43-16.log)

**Comment by SergoGansta777** [comment]
[neovide_r2023-09-06_19-50-57.restart-0000.log](https://github.com/neovide/neovide/files/12540492/neovide_r2023-09-06_19-50-57.restart-0000.log)

**Comment by MultisampledNight** [comment]
Hi, thanks for reporting!

Unfortunately I'm unable to reproduce this, the message appears and is interactable. I assume you forgot a step between 1. and 2. where an edit needs to be done in order for the message to be emitted, but even with I still see that message.

However, it looks like your message is wrapped by a plugin, as the message is usually emitted on the command line. Could you try with `--clean` and also another time with `--multigrid`? What plugin is that in specific?

**Comment by fredizzimo** [comment]
If it's `noice.nvim`, make sure that you are using the latest version to be Neovide compatible. That said, there could still be other incompatibilities.

**Comment by SergoGansta777** [comment]
Actions between steps 1 and 2 are optional. With my configuration, everything breaks regardless, even with those actions.

I had previously enabled the `--multigrid` option, but I tried running with and without it. Following your advice, I ran Neovim with the `--clean` option, and I did see the error message on the command line. So, it seems that the issue is not with Neovide. I apologize for the confusion.

After examining my configuration more closely, I realized that the problem was caused by the **noice** plugin from https://github.com/folke/noice.nvim. It either went missing or some of its selected options were causing the issue. Everything works as expected when I remove this plugin.

**Comment by SergoGansta777** [comment]
> If it's `noice.nvim`, make sure that you are using the latest version to be Neovide compatible. That said, there could still be other incompatibilities.

Oh, I am sorry. When I was doing my little research, I missed your message, but you are absolutely right! Thanks for the help

**Comment by fredizzimo** [comment]
If the latest version of noice still causes trouble, it's worth reporting the issue in their bug tracker. It can most likely quite easily be fixed like the other noice issues that were previously fixed.
