### ISSUE TITLE
neovide resizes to 0 by 0 pixels [Windows 11]

### ISSUE THREAD

**Issue by BartHageman** [neovide/neovide#2015]
**Describe the bug**
Neovide appears to occasionally snap to a size of 0 by 0 pixels, after which it remembers this size and opens every new instance at 0 by 0 pixels, rendering the program unusable.

**To Reproduce**
I am unsure what exactly triggers the bug, but it appears to happen when resizing neovide windows.

**Expected behavior**
I expect neovide to maintain a minimum size in order to remain useable, or to fall back on its defaults in cases like this, without having to resort to changing my config file.

**Screenshots**
![image](https://github.com/neovide/neovide/assets/17185514/74dd17c0-8dbc-46f6-8b37-cfbb5d915d6c)

**Desktop:**
- Edition	Windows 11 Pro
- Version	22H2
- OS build 22621.2134
- Neovide Version 0.11.1
- Neovim Version 0.9.0

[neovide_rCURRENT.log](https://github.com/neovide/neovide/files/12551500/neovide_rCURRENT.log)

**Comment by fredizzimo** [comment]
Yes, we need other validations too, like that it's not bigger than the current desktop, and that the window is visible, and not fully or partially outside the desktop.

**Comment by fredizzimo** [comment]
This happens when you close neovide and it's minimized, see https://github.com/neovide/neovide/issues/2141#issuecomment-1822741173
