### ISSUE TITLE
No numpad keybinds

### ISSUE THREAD

**Issue by plague-spreader** [neovide/neovide#2030]
**Describe the bug**

**ALL** the numpad keys do not honor their binding, e.g. when pressing `<kPlus>` neovim will handle the keypress of +.
Moreover, the most annoying thing to me, `<kUp>` gets remapped to `<Left>`.

**To Reproduce**
1. Open Neovide
2. Type `:map <kPlus> :echo "\<kPlus\> pressed"<CR>`
3. Type `:map + :echo "+ pressed"<CR>`
4. Press <kPlus>

**Expected behavior**

The message "`<kPlus>` pressed" is shown.

**Actual behavior**

The message "+ pressed" is shown.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Artix Linux
 - Neovide Version 0.11.2
 - Neovim Version 0.9.2

**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**
[neovide_rCURRENT.log](https://github.com/neovide/neovide/files/12642353/neovide_rCURRENT.log)

But I think the relevant portion is this:

`
TRACE [neovide::window::keyboard_manager] KeyEvent {
    physical_key: NumpadAdd,
    logical_key: Character(
        "+",
    ),
    text: Some(
        "+",
    ),
    location: Numpad,
    state: Pressed,
    repeat: false,
    platform_specific: KeyEventExtra {
        key_without_modifiers: Character(
            "+",
        ),
        text_with_all_modifiers: Some(
            "+",
        ),
    },
}
`

**Additional context**

**Comment by plague-spreader** [comment]
Decided to take matter into my own hands and done a pull request. This is my first time doing this so don't be too harsh on me if I've done something wrong :D Shall I close this issue tho?

**Comment by MultisampledNight** [comment]
Since fredizzimo helpfully linked the pull request, the issue will be closed automatically once the PR is merged! So no need to close it yet.
