### ISSUE TITLE
Not forking correctly when launched from WSL

### ISSUE THREAD

**Issue by claudio4** [neovide/neovide#2036]
**Describe the bug**
When neovide (installed on Windows not WSL) is launched with `neovide --wsl` from inside the WSL2, the terminal will await until neovide exits before showing the prompt again. A.K.A it behaves as if `--nofork` was used.
**To Reproduce**
1. Install neovide in Windows.
2. Go to the WSL2 terminal.
3. Execute `/path/to/neovide --wsl`.
**Expected behavior**
The terminal will return immendiatly after launching neovide.

**Screenshots**
![image](https://github.com/neovide/neovide/assets/9874071/e7da1b4e-d094-43d3-b667-7a217c481d75)

**Desktop (please complete the following information):**
 - OS: Windows 11 (22621.2283)
 - Neovide Version 0.10.4
 - Neovim Version v0.9.2
 - WSL Distro: OpenSUSE Tumbleweed
 
*Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**
TRACE [neovide] Neovide version: 0.10.4

**Comment by fredizzimo** [comment]
I don't think that there's anything we can do about that in the code, it seems to be the standard behaviour of WSL, even running `notepad.exe` will block until it's finished.

I suggest that you create shell function/alias that launches neovide in the background:
```bash
function neovide()
{
    neovide.exe --wsl "$@" &
}
```

**Comment by claudio4** [comment]
It does seems like the normal behaviour for Windows programs executed from WSL. Nonetheless, there must be a way to escaoe from this behavour, as VS Code has no problem doing it. I might try to do some digging to search how VS Code does it and report back.

**Comment by fredizzimo** [comment]
`code` is just a shell script which for neovide would do `neovide.exe &2>/dev/null </dev/nul` The effect is pretty much the same as `&` at the end of the command.

**Comment by claudio4** [comment]
Yes, as you said code is a shell script, altough it seems it does some magic with the blackbox that is the WSL Remote extension. I've been playing around with it, and I have come with this little script that completly detaches neovide from the current terminal with the help of Powershell.

```bash
#!/bin/sh
neovideDir="$(dirname "$(realpath "$0")")"

if [ -z "$WSL_DISTRO_NAME" ] && ! uname -r | grep -q 'microsoft'; then
  # Not running inside the WSL, execute neovide as normal
  exec "$neovideDir/neovide.exe" "$@"
fi

neovideDir="$(wslpath -w "$neovideDir")"
exec powershell.exe "Start-Process -FilePath \"$neovideDir\\neovide.exe\"  -ArgumentList \"--wsl $@\""
```

**Comment by fredizzimo** [comment]
I'm not sure why you need to launch an extra powershell process when both of these also work and detaches the console
* `$neovideDir/neovide.exe --wsl "$@" &`
* `$neovideDir/neovide.exe &2>/dev/null </dev/null`

**Comment by claudio4** [comment]
Using the `&` does not detach the command from the terminal session but rather it makes it run on background. It is still visible when the `jobs` command is used, and a `HUP` will be sent to it when the terminal closes, although it seems like it doesn't affect neovide.

**Comment by fredizzimo** [comment]
I think we can consider this fixed, since unless we distribute some kind of wrapper script there's nothing more we can do.

And we already have a few different workarounds here.
