### ISSUE TITLE
A --working-dir command line argument

### ISSUE THREAD

**Issue by iSplasher** [neovide/neovide#2037]
**Is your feature request related to a problem? Please describe.**
It would be really nice to add a --working-dir argument, along with a corresponding option in the config file.
For users who launch the application through other means than the shell, it can be inconvenient when the default cwd is set at the location of the Neovide executable.

**Describe the solution you'd like**
I propose adding the --working-dir or --default-working-dir argument, which should be set just *before* allocating control to nvim. This way, it won't interfere with any potential actions nvim might perform once it's up and running.
With this feature, users can set a default directory, like ~/my-dev, in the config file, and Neovide will start with that directory when launched by clicking on its icon.

**Describe alternatives you've considered**
I've looked at nvim's `autochdir` option, but it only works when you open Neovide with a file. Sometimes, you simply want to start with an empty buffer.
Another alternative is to create a Lua script and have it run upon nvim's launch. However, this approach could prove complicated since it might potentially override any plugins or settings that Neovim users have configured to affect the working directory.

**Comment by MultisampledNight** [comment]
Hi, thanks for the suggestion!

Since command line arguments to Neovim can be passed through `--` as shown in `neovide --help` (which probably would be a good idea to add to the website), does

```shell
neovide -- --cmd 'cd ~/whereever/you/want/to/go'
```

suffice? `--cmd`s to neovim are processed before the init file, as listed in [`:help startup`](https://neovim.io/doc/user/starting.html#--cmd), maybe that could fit your usecase.

**Comment by Kethku** [comment]
Yeah this is a neovim issue not neovide as it can be solved using built in features
