### ISSUE TITLE
data_path is hard coded

### ISSUE THREAD

**Issue by xavier-gl71** [neovide/neovide#2038]
data_path is (partially) hard coded.
Neovide does not use XDG_… variables on Windows. NVim does.
https://github.com/neovide/neovide/blob/33df9e578c52e285ed40f037908c4fa7330af582/src/settings/window_size.rs#L34

According to Nvim doc [stdpath()](https://neovim.io/doc/user/builtin.html#stdpath()) should be called.

**Comment by fredizzimo** [comment]
Neovide now usees it's own data path with, it's not exactly what the issue is asking for, but IMO the correct thing to do
* https://github.com/neovide/neovide/pull/2135
