### ISSUE TITLE
Distribute neovide through pip

### ISSUE THREAD

**Issue by SteveLauC** [neovide/neovide#2042]
Skip the issue template as this is not a feature request to the program.

-----

Maintaining Linux packages is painful, and not everyone is a fan of Appimage, so I am wondering if you guys want to distribute `neovide` through [`pip`](https://pypi.org/), this whole thing can be super easy and automated in CI thanks to the help of [PyO3: maturin](https://github.com/PyO3/maturin).

[Topgrade](https://github.com/topgrade-rs/topgrade/issues/462) (A CLI tool to update packages, also a Rust project) has done this, and it works well.

If you guys are willing to do this, I am happy to contribute! :)

**Comment by Kethku** [comment]
This feels like a bad idea to me just because this project has nothing to do with python and any platform we publish to inevitably requires us to support it. So I'm going to close this for now.
