### ISSUE TITLE
"neovide_cursor_vfx_mode" memory leak

### ISSUE THREAD

**Issue by MOldtime** [neovide/neovide#2045]
**Describe the bug**
After setting neovide_cursor_vfx_mode = "railgun", the memory continues to increase every time you move

**To Reproduce**
1. Set neovide_cursor_vfx_mode = "railgun"
2. Open a file with content
3. Move the cursor up and down

**Expected behavior**

**Screenshots**

https://github.com/neovide/neovide/assets/38435967/8933755d-5c95-42c1-ad29-dd9d1275f85d

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 11 25951.1000]
 - Neovide Version [e.g. 0.11.2]
 - Neovim Version [e.g. 0.9.2]

**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**
[neovide_r2023-09-21_15-09-51.log](https://github.com/neovide/neovide/files/12681442/neovide_r2023-09-21_15-09-51.log)
[neovide_rCURRENT.log](https://github.com/neovide/neovide/files/12681443/neovide_rCURRENT.log)

**Additional context**
```Lua
local neovideconfig = vim.g
neovideconfig.neovide_cursor_vfx_mode = "railgun"
neovideconfig.neovide_cursor_vfx_opacity = 100.0
neovideconfig.neovide_cursor_vfx_particle_lifetime = 1.0
neovideconfig.neovide_cursor_vfx_particle_density = 50.0
```

**Comment by fredizzimo** [comment]
Thanks for reporting, that's pretty bad

But unfortunately, I can't repeat it on Windows here with the same config. Neither the CPU or GPU memory is increasing according to Windows task manager.

Can you create a minimal configuration, using this template https://github.com/neovim/neovim/wiki/Minimal-reproduction-template.

Also, which graphics card do you have?
Maybe you need to update the drivers.

If there's a bug it might be in the Skia graphics library that we use, which only triggers when your graphics card doesn't support some feature and it uses an alternative implementation.

**Comment by MOldtime** [comment]
@fredizzimo Thanks Reply
I'm not using link generation
I cleared the configuration, leaving only `init.lua`
Even so, the problem remains
I did not use a discrete graphics card, but the core graphics that comes with the intel i7 11700 CPU.

In this test, I found that the cursor needs to move up and down at the end of the line to trigger this problem.

`init.lua`
```lua
local neovideconfig = vim.g
neovideconfig.neovide_cursor_vfx_mode = "railgun"
neovideconfig.neovide_cursor_vfx_opacity = 100.0
neovideconfig.neovide_cursor_vfx_particle_lifetime = 1.0
neovideconfig.neovide_cursor_vfx_particle_density = 50.0
```

https://github.com/neovide/neovide/assets/38435967/6715bf47-b9ec-4df8-b36a-2217646ef79e

**When I annotated the content the problem disappeared**
`init.lua`
```lua
--local neovideconfig = vim.g
--neovideconfig.neovide_cursor_vfx_mode = "railgun"
--neovideconfig.neovide_cursor_vfx_opacity = 100.0
--neovideconfig.neovide_cursor_vfx_particle_lifetime = 1.0
--neovideconfig.neovide_cursor_vfx_particle_density = 50.0
```

https://github.com/neovide/neovide/assets/38435967/2ce454c3-da32-4d2e-a51a-3da0c4af5a55

**Comment by fredizzimo** [comment]
I have bad memory, we tracked it down further here https://github.com/neovide/neovide/issues/843. So, closing this as a duplicate.
