### ISSUE TITLE
Scrolling lags compares to nvim in terminal

### ISSUE THREAD

**Issue by ogios** [neovide/neovide#2047]
**Describe the bug**
Scrolling lags in neovide compares to neovim in terminal

**To Reproduce**
Here's my neovim config: [config](https://github.com/ogios/nvim-config-nvchad)  
sorry i don't know what could possiblly cause this so i can only provide my whole config.

**Screenshots**
i don't know if you can feel it with this video, it feels kinda obvious in 90fps
https://github.com/neovide/neovide/assets/96933655/ed333748-63c2-47c7-adf8-9ecd64183d88

**Desktop (please complete the following information):**
 - OS: Windows10
 - Neovide Version 0.11.2
 - Neovim Version 0.9.2

**Additional context**
GPU: gtx1650ti, usage it about 25% when moving cursor and scrolling  
scrolling using mouse didn't actually lags that much but still a bit.

config for neovide:
```lua
vim.o.guifont = "JetBrainsMonoNL Nerd Font Mono:h14"
vim.g.neovide_underline_automatic_scaling = true


vim.g.neovide_floating_blur_amount_x = 2.0
vim.g.neovide_floating_blur_amount_y = 2.0


vim.g.neovide_scroll_animation_length = 0
vim.g.neovide_cursor_animation_length = 0
vim.g.neovide_cursor_trail_size = 0
vim.g.neovide_hide_mouse_when_typing = false

vim.g.neovide_fullscreen = true
-- vim.g.neovide_profiler = true
vim.g.neovide_cursor_vfx_mode = "sonicboom"
vim.g.neovide_refresh_rate = 90
```

https://github.com/neovide/neovide/assets/96933655/ed333748-63c2-47c7-adf8-9ecd64183d88

**Comment by fredizzimo** [comment]
There are numerous duplicates of this for example
* https://github.com/neovide/neovide/issues/1312

And this will be fixed by:
* https://github.com/neovide/neovide/pull/1977

So, I'm closing this as a duplicate
