### ISSUE TITLE
Neovide doesn't start up on WSL

### ISSUE THREAD

**Issue by Christiano300** [neovide/neovide#2048]
**Describe the bug**
When I use the neovide command, it returns immediately, but no window opens. Viewing the log files reveals that it immediately crashes on startup.

**Desktop (please complete the following information):**
 - OS: Windows 11 21H2
 - WSL: Ubuntu 20.04.6 LTS (Focal Fossa)
 - Neovide Version 0.11.2
 - Neovim Version 0.9.2

**Log:**
```
2023-09-24 15:52:08 - Neovide panicked with the message 'called `Result::unwrap()` on an `Err` value: XKBNotFound'. (File: /home/christian/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.29.0-beta.0/src/platform_impl/linux/wayland/seat/keyboard/mod.rs; Line: 278, Column: 40)
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: <unknown>
  14: <unknown>
  15: <unknown>
  16: <unknown>
  17: __libc_start_main
  18: <unknown>
```

**Comment by fredizzimo** [comment]
We don't really support running native `wsl` at the moment, and even if we did, the performance would be quite bad. 

I suggest that you run the windows version of Neovide instead with `neovide --wsl` 
https://neovide.dev/command-line-reference.html#wsl

**Comment by Kethku** [comment]
Closing as addressed.
