### ISSUE TITLE
Colors in neovide do not match terminal colors

### ISSUE THREAD

**Issue by asmodeus812** [neovide/neovide#2050]
**Describe the bug**
There is a huge discrepancy between the colors shown in neovide and the colors shown when neovim is opened in a terminal emulator instead. 

**To Reproduce**
1. open neovide 
2. :term 
3. bat fname --theme="whichever" 

1. open nvim (inside alacritty, iterm, etc)
2. :term
3. bat fname --theme="whichever"

**Expected behavior**
Neovide should display the same colors as in the terminal.

**Screenshots**
Neovide preview
![image](https://github.com/neovide/neovide/assets/15955811/d54778f7-86c2-4b70-b7f2-814082987f16)

Nvim preview
![image](https://github.com/neovide/neovide/assets/15955811/eb360df0-6341-4df0-999c-8c77f4fd8b93)

**Desktop (please complete the following information):**
 - Ubuntu 22
 - Neovide Version: latest release
 - Neovim Version: 0.9.1

In general the colors in neovide are much darker than what is observed in the terminal, some do not even match, for example the property in terminal is colored blue, neovide shows it as green, other colors seem closer but not exactly matching. Note i have tried Disabling transparency for my theme and neovide as well, does not change or fix the colors.

**Comment by Kethku** [comment]
Yeah I believe this is expected behavior

**Comment by Crispy13** [comment]
In my case, Terminal text colors were different with those of normal buffers.

```
-- init.lua
vim.opt.termguicolors = true
```
This solved it.

**Comment by youyoumu** [comment]
here is the example with theme from https://github.com/catppuccin/ghostty/blob/main/themes/catppuccin-mocha.conf
```lua
if vim.g.neovide then
  vim.g.terminal_color_0 = "#45475a"
  vim.g.terminal_color_1 = "#f38ba8"
  vim.g.terminal_color_2 = "#a6e3a1"
  vim.g.terminal_color_3 = "#f9e2af"
  vim.g.terminal_color_4 = "#89b4fa"
  vim.g.terminal_color_5 = "#f5c2e7"
  vim.g.terminal_color_6 = "#94e2d5"
  vim.g.terminal_color_7 = "#bac2de"
  vim.g.terminal_color_8 = "#585b70"
  vim.g.terminal_color_9 = "#f38ba8"
  vim.g.terminal_color_10 = "#a6e3a1"
  vim.g.terminal_color_11 = "#f9e2af"
  vim.g.terminal_color_12 = "#89b4fa"
  vim.g.terminal_color_13 = "#f5c2e7"
  vim.g.terminal_color_14 = "#94e2d5"
  vim.g.terminal_color_15 = "#a6adc8"
end
```

**Comment by YosefBayoude** [comment]
I found that catppuccin already had these terminal colors, but they are disabled by default, you need to enable them : 
```lua
{
  "catppuccin/nvim",
  opts = {
    term_colors = true,
  },
}
```
