### ISSUE TITLE
fzf-lua plugin layout different in terminal neovim vs neovide despite using the same config

### ISSUE THREAD

**Issue by sainttttt** [neovide/neovide#2052]
I'm having an issue with the fzf-lua plugin. For some reason the appearance is different in neovide compared to terminal nvim, even though the config used is exactly the same.

**To Reproduce**
1. Open terminal neovim 
2. Open fzf-lua
3. Open neovide with same config
4. Open fzf-lua

**Expected behavior**
1. It's expected for the layout to look the same for both neovide and terminal neovim

**Screenshots**
https://streamable.com/pnji3w - This is a video of the issue happpening

**Desktop (please complete the following information):**
mac0S 13.2
 - Neovide Version 0.11.1 
 - Neovim Version 0.9.1

[neovide_rCURRENT.log](https://github.com/neovide/neovide/files/12717076/neovide_rCURRENT.log)

**Comment by fredizzimo** [comment]
Just a stupid question, have you tried to make the Neovide window wider? It looks like it's too narrow to display the wide layout.

**Comment by sainttttt** [comment]
Wow you're right actually! Thanks a lot haha
