### ISSUE TITLE
Cursive/italics off by one

### ISSUE THREAD

**Issue by Jomik** [neovide/neovide#2064]
**Describe the bug**
I am using a theme that renders keywords with cursive. For some reason, some characters shift once to the right.

**To Reproduce**
1. Install [rebelot/kanagawa](https://github.com/rebelot/kanagawa.nvim)
2. Install [Victor Mono](https://rubjo.github.io/victor-mono/)
3. Write a keyword `local` for lua triggers it. `set` and `help` in the vim command also shows up odd.
4. Hovering over the blank spot reveals the missing character.

**Expected behavior**
No shift of characters. It works perfectly fine in the terminal.

**Screenshots**
<img width="157" alt="image" src="https://github.com/neovide/neovide/assets/699655/6ca378b1-7e7f-4aa6-be6f-ba04d1f24399">
<img width="157" alt="image" src="https://github.com/neovide/neovide/assets/699655/71ed66b4-691e-4f9f-b35d-73e4104733af">
<img width="293" alt="image" src="https://github.com/neovide/neovide/assets/699655/185376b9-9541-4e00-82d7-eaaa71b964c4">
<img width="293" alt="image" src="https://github.com/neovide/neovide/assets/699655/a2ea5b18-f16a-4640-95fd-0087186487bf">

**Desktop (please complete the following information):**
 - OS: macOS 13.6
 - Neovide Version: 0.11.2
 - Neovim Version: NVIM v0.10.0-dev-1275+gb2a8a9314-Homebrew

**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**
https://gist.github.com/Jomik/45eb4147bcf2edc25c531b11d1418d58

**Additional context**
Reproduction:
```lua
for name, url in pairs({
	kanagawa = "https://github.com/rebelot/kanagawa.nvim",
}) do
	local install_path = vim.fn.fnamemodify("nvim_issue/" .. name, ":p")
	if vim.fn.isdirectory(install_path) == 0 then
		vim.fn.system({ "git", "clone", "--depth=1", url, install_path })
	end
	vim.opt.runtimepath:append(install_path)
end

vim.cmd("colorscheme kanagawa")
vim.opt.guifont = "VictorMono_Nerd_Font_Mono:h14"
```
example.lua
```lua
-- Some of the things in comments are broken
-- I am unsure why this is different from what I see 
-- in my actualy config.
-- But this is quite a clear repro.
```
![image](https://github.com/neovide/neovide/assets/699655/7c037dfa-dfde-4af2-bd57-5e0cd0a8fa28)

**Comment by fredizzimo** [comment]
I have not seen that myself. But in order to rule out some things could you try Neovim 0.9.2, instead of nightly? 

Additionally, I can't seem to find the commit that matches your Neovim version, so I'm not sure how new or old it actually is.

**Comment by Jomik** [comment]
Tried on 0.9.2, same result.

I am unsure why the `+g` gets added.. :)
It is this commit: https://github.com/neovim/neovim/commit/b2a8a93
Also happens on latest: https://github.com/neovim/neovim/commit/5db076c7c

**Comment by fredizzimo** [comment]
It looks like it might draw the screen twice with different offsets, without properly clearing it between. In the help text you can see that the `e` and `l` characters are actually overlapping.

The way we are drawing things has changed completely in https://github.com/neovide/neovide/pull/1977, and we will soon merge that to master, so it would be great if you could test that before we start to investigate more. There's a big chance that it's fixed there.

**Comment by Jomik** [comment]
Will that be compatible with nightly by the time it is merged? I can wait for that to be merged, no problem. Or would you prefer that I try a build and test it early next week?

**Comment by fredizzimo** [comment]
@Jomik. It should work with both nightly and 0.9.2, but not with older versions than that.

It would be great if you could try it, so that we know if this is something that needs to be fixed or not. Otherwise, we will have to try to find a way to repeat it ourselves.

**Comment by Jomik** [comment]
I tried building the branch and testing there, same issue sadly.
![image](https://github.com/neovide/neovide/assets/699655/7deef592-eb18-43f9-b154-b5fa2e47cbb7)

Adding a screen recording so you can better see what happens, as I think the images may not explain it well enough 😄 
Let me know if you need anything else!
https://github.com/neovide/neovide/assets/699655/ca59cb47-a706-408e-9352-7506328dd6eb

**Comment by fredizzimo** [comment]
@Jomik, would it be possible for you to create a https://github.com/neovim/neovim/wiki/Minimal-reproduction-template? It might be some plugin that interacts badly with Neovide.

But first you could try with just an empty template that sets the guifont and `neovide -- --clean -u my_issue.lua` I guess you at least need the colorcscheme, but maybe something else is also needed.

**Comment by Jomik** [comment]
I have updated the original post with the repro. It obviously depends on a font with italics and also on the colorscheme using it..
I tried to avoid doing the exact same issue as I see, as that requires LSP setup, etc. The above is probably a clear enough reproduction 😄

**Comment by fredizzimo** [comment]
@Jomik 

It looks like it's a font bug. Other font's with italics works, and so do `VictorMono_Nerd_Font` and `VictorMono_Nerd_Font_Propo`, but not `VictorMono_Nerd_Font_Mono`. The standard `VictorMono` also works.

Since the Mono variant is Nerd Fonts specific, I suggest that you create an issue in the Nerd Fonts repository. 

That assumes that you actually want to use the Mono variant. IMO the regular non-mono version looks better, since it allows double width characters, which makes the icons become properly sized instead of shrinking some of them to fit the character width and becoming very small as a result.

**Comment by fredizzimo** [comment]
I tested the font in Windows notepad, and that one renders it wrong the same way too.

**Comment by Jomik** [comment]
That fixes it fully! Awesome :)
I found it very odd that it works in `iTerm` though, it supports ligatures, and does use the Mono variant.
I will close this - thanks!
