### ISSUE TITLE
Crash when external display is disconnected in Wayland

### ISSUE THREAD

**Issue by bleonard252** [neovide/neovide#2066]
**Describe the bug**

When an external display is disconnected, such as when the monitor goes to sleep while the computer is asleep or locked, Wayland does something Neovide doesn't anticipate. Neovide seems to attempt to write the error, fails, panics, and hangs, no longer displaying but, if there is unsaved text in `nvim`, it leaves the running `nvim` process behind.

**To reproduce**

1. Connect an external display in "join" mode.
2. Launch Neovide (with `--nofork`).
3. Disconnect the external display.
4. Re-connect, and observe.

**Expected behavior**

It moves to the other screen, and moves back when the external display is reconnected, like other apps do.

**System**

* Neovide: tested on both latest release and a debug build of `improve-render-loop`.
* VanillaOS 22.10 (Ubuntu-based)
* GNOME on Wayland

**Extra information**

* Neovide is running in a Distrobox container. I don't think that's relevant since neither VS Code nor Android Studio in the same container have this issue.
* [neovide_backtraces.log](https://github.com/neovide/neovide/files/12821644/neovide_backtraces.log)
* [Console output](https://github.com/neovide/neovide/files/12821650/output.log) from `RUST_BACKTRACE=1 ./target/debug/neovide --nofork`
* Running with latest release as `RUST_BACKTRACE=1 neovide --nofork` returns the less helpful error:
```
wl_display@1: error 1: invalid method 0 (since 2 < 3), object wl_output@6
Io error: Invalid argument (os error 22)
```

**Comment by fredizzimo** [comment]
I reported this https://github.com/rust-windowing/winit/issues/3102. But I'm not completely sure if it's a winit or Neovide bug at the moment.

The fact that nvim can be left behind is definitely an issue on our side, that we need to somehow deal with. But I'm not sure how, since there's not much we can do if the UI crashes. Perhaps we should use sockets instead of stdio as a channel, so that we can re-attach.

**Comment by bleonard252** [comment]
If everything in nvim is saved, nvim closes cleanly when this happens. It's only if something in nvim like a "save your changes?" prompt stops it from quitting that Neovide abandons the process.

**Comment by kchibisov** [comment]
>I reported this https://github.com/rust-windowing/winit/issues/3102. But I'm not completely sure if it's a winit or Neovide bug at the moment.

This is fixed in winit releases, so should be closed.

**Comment by fredizzimo** [comment]
@bleonard252, can you check with the latest master of Neovide. It’s not on Winit 0.29.3 yet, but I think the fix should be in 0.29.2 already.

**Comment by bleonard252** [comment]
Yep, this is fixed on latest master! Thanks for the help.

**Comment by gmankab** [comment]
i am also trying to het neovide to work in distrobox

host system is fedora silverblue

in arch distrobox, i tryed to install via `pacman -Syu neovide`, binary from releases page, and appimage on releases page, always geting this error:
```txt
Neovide panicked with the message 'called `Result::unwrap()` on an `Err` value: XKBNotFound'. (File: /build/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.29.4/src/platform_impl/linux/wayland/seat/keyboard/mod.rs; Line: 292, Column: 40)
This is a bug and we would love for it to be reported to https://github.com/neovide/neovide/issues
Backtrace saved to neovide_backtraces.log!
```

in fedora distrobox i tried to install from copr repos `agraven/neovide` and `chrisbouchard/neovide-nightly`, and binary from releases page, always getting very long unreadable error

appimage works in fedora distrobox and outside distrobox

**Comment by fredizzimo** [comment]
@gmankab, can you open a new issue for that, so that it can get tracked properly?

**Comment by gmankab** [comment]
done, #2293
