### ISSUE TITLE
Docs zoom function returns error

### ISSUE THREAD

**Issue by Slushee-a** [neovide/neovide#2069]
## Bug explanation:
I've always used the [scale shortcut function from the docs](https://neovide.dev/faq.html?highlight=scale#how-can-i-dynamically-change-the-scale-at-runtime) (the lua one) and it's always worked.

It suddenly stopped working and displays this message when I press either the zoom in or out shortcuts:
```
Error detected while processing function NeovideNotifyscale_factorChanged:
line 1:
E121: Undefined variable: g:neovide_channel_id
```

#### I have:
 - Done a full system upgrade (native package manager, flatpak, rustup, cargo, pip3, packer.nvim)
 - Removed all old cached packages and orphans
 - Recompiled neovide
 - Reinstalled neovim
 - Rebooted
 
And I still get the same error.

## To reproduce
1. Add the lua runtime scaling shortcut from [the docs](https://neovide.dev/faq.html?highlight=scale#how-can-i-dynamically-change-the-scale-at-runtime) to the lua nvim shortcuts config file
2. Open neovide. Error occurs with and without `--multigrid`
3. Use the defined shortcuts (`Ctrl` + `-`) and (`Ctrl` + `=`)

## Expected behavior
The function from the docs working as expected, zooming in when (`Ctrl` + `=`) and out when (`Ctrl` + `-`) is pressed instead of showing an error.

## Screenshots
> ![image](https://github.com/neovide/neovide/assets/55996847/dd6d8d71-a27f-4bce-b7a4-de16c8281463)
> What pops up after one of the zoom shortcuts is pressed.

## Desktop
 - **OS:** Void Linux (x86_64, glibc) Kernel 6.5.6_1
 - **Neovide Version:** 0.11.2
 - **Neovim Version:** 0.9.2

## Log
Full log can be seen here: https://gitlab.com/-/snippets/3607601

**Comment by fredizzimo** [comment]
Hm. are you using the release version or build from master? 

Because this was changed yesterday here https://github.com/neovide/neovide/pull/2067. I don't have that much time to investigate deeper right now, but maybe @mopp has some ideas?

**Comment by Slushee-a** [comment]
I used `cargo install --git https://github.com/neovide/neovide --force` for the reinstall, which I assume uses the main branch.

**Comment by mopp** [comment]
oops, I reproduced the same error by inputting 

```vim
:let g:neovide_channel_id = 1.1
```

on command line :sob:

**Comment by fredizzimo** [comment]
The strange thing here is that the log has the following output
`INFO [neovide::bridge::setup] Neovide registered to nvim with channel id 1`

So, it seems like the channel is registered as it should. But still the autocommand does not find it.

**Comment by mopp** [comment]
ah, the command works with remote neovim.

**Comment by fredizzimo** [comment]
Ah, yes you are right, the channel seems to be registered inside the `setup_neovide_remote_clipboard` function instead of `setup_neovide_specific_state` where it should be.

**Comment by mopp** [comment]
Looks good! :+1: 
The variable `g:neovide_channel_id` should be initialized inside this branch.
https://github.com/neovide/neovide/blob/d61127f1d449425a716caf5f74a0a2eff660f4c9/src/bridge/setup.rs#L100-L105

**Comment by fredizzimo** [comment]
@mopp, can you make a PR, I have some other things in progress myself.

**Comment by mopp** [comment]
Okay, I will create it soon :ok_hand:

**Comment by mopp** [comment]
I did it :tada: 
https://github.com/neovide/neovide/pull/2070

**Comment by fredizzimo** [comment]
@Slushee-a. If you try again with the latest it should be fixed.

**Comment by Slushee-a** [comment]
It is indeed fixed! Thank you.
