### ISSUE TITLE
Cannot fallback to the provided font for CJK characters

### ISSUE THREAD

**Issue by inmaldrerah** [neovide/neovide#2071]
**Describe the bug**
CJK characters cannot display if the primary font does not support them. Works if only the CJK font is set.

**To Reproduce**
1. Start Neovide
2. Set vim.o.guifont to e.g. `"Fira Code,Noto Sans Mono CJK SC:h14"`
3. Input some CJK characters, e.g. "测试字体"

**Expected behavior**
The fallback font should be used and the CJK characters should be displayed correctly.

**Screenshots**
![CJK characters](https://gcdnb.pbrd.co/images/PftorCyEhKHF.png?o=1)
![CJK characters with config](https://gcdnb.pbrd.co/images/xTkQi155rJGu.png?o=1)

**Desktop (please complete the following information):**
 - OS: NixOS
 - Neovide Version 0.11.2
 - Neovim Version v0.10.0-dev-6823fdb

**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**
https://gist.github.com/inmaldrerah/3005c94ca241fb0f523267ee299426aa

**Comment by fredizzimo** [comment]
We need better error reporting for this... 
But in the logs you can see `Font can't be updated to: Fira Code,Noto Sans Mono CJK SC:h14`

I think the problem is that it should be `FiraCode,Noto Sans Mono CJK JP:h14`, note, no space between `Fira` and `Code`. At least that works for me. Additionally I see `CJK SC` in the logs, but you mention `CJK JP`. 

You can list all the supported fonts with `:set guifont=*`. Make sure you spell the names exactly like that.

**Comment by inmaldrerah** [comment]
Sorry, I am actually using `Noto Sans Mono CJK SC`, I just mistyped it as I used to use `JP`.

But I am quite sure I should use `Fira Code` instead of `FiraCode`, as both `:set guifont=*` and `fc-list` shows it as `Fira Code`.

![Fira Code instead of FiraCode](https://gcdnb.pbrd.co/images/2huYUZnApsfx.png?o=1)

**Comment by fredizzimo** [comment]
Do you have Noto Sans Mono CJK SC in the list as well?

**Comment by inmaldrerah** [comment]
Yes, and if I remove the `Fira Code,` part, neovide does show all text in Noto Sans Mono CJK SC.

**Comment by fredizzimo** [comment]
Can you test with just `Fira Code` you can try changing the font sizes to ensure that it's loading. The error in the log
`DEBUG [neovide::renderer::fonts::caching_shaper] Updating font: Fira Code,Noto Sans Mono CJK SC:h14` is actually printed when the primary font can't be loaded and there's no verification at all for the fallback font.

**Comment by inmaldrerah** [comment]
Ah... So there must be some problem with Fira Code then. `Updating Font:` and `Font can't be updated to:` are always printed even with just `Fira Code:h14`.

> The error in the log `DEBUG [neovide::renderer::fonts::caching_shaper] Updating font: Fira Code,Noto Sans Mono CJK SC:h14` is actually printed when the primary font can't be loaded and there's no verification at all for the fallback font.

For `Noto Sans Mono CJK SC:h14` it is printing this is printed but the `Font can't be updated to:` is not. Instead it says `Font updated to:`, which seems expected.

**Comment by fredizzimo** [comment]
I recommend that you install the nerd fonts version of fira code. A lot of Neovim plugins need nerd fonts anyway.

**Comment by inmaldrerah** [comment]
Oh, the font Fira Code Symbol seems to be working (I'm still testing, but at least it never triggers `Font can't be updated to:`). I found that the Fira Code font is in a .ttf while Noto Sans Mono CJK SC and Fira Code Symbol are in two .otf's. So maybe it is font type related?

BTW, I have the nerd font symbol only font. Maybe I should put it in the first place (or the last?).

**Comment by fredizzimo** [comment]
Both TTF and OTF should work, but it could still be corrupted or in the wrong format somehow, or your font cache needs to be re-built with `fs-cache` (I don't know how that works on NixOS).

And if you use the symbols only Nerd Font, it should be last in the fallback list.

**Comment by inmaldrerah** [comment]
Alright... I will continue to try to figure out what is happening, but it seems unrelated to the fallback mechanism then.
