### ISSUE TITLE
Neovide doesn't launch (Linux Debian)

### ISSUE THREAD

**Issue by azolus** [neovide/neovide#2075]
**Describe the bug**

Running neovide doesn't do anything on my machine, i.e.
```bash
$ neovide
```
exits without any error message and does nothing.

**To Reproduce**

I've installed neovide from source with cargo, made sure my guifont is set and tried launching `.cargo/bin/neovide` with an empty `.bashrc` and a minimal `init.lua` after deleting `.local/share/lsp` and `.local/share/nvim`:
```lua
-- .config/nvim/init.lua --
vim.opt.guifont = { "Hack Nerd Font", ":h12" }
```
and nothing happened

**Expected behavior**

Neovide launches and I make happy noise.

**Screenshots**

None

**Desktop (please complete the following information):**

My system:
- os: Debian Linux 12
- kernel: 5.10.0-23-amd64
- shell: bash
- neovide v0.11.2
- neovim v0.9.4 release

**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**

```
-- neovide_backtraces.log --
2023-10-11 15:08:52 - Neovide panicked with the message 'called `Option::unwrap()` on a `None` value'. (File: src/renderer/opengl.rs; Line: 60, Column: 28)
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: __libc_start_call_main
             at ./csu/../sysdeps/nptl/libc_start_call_main.h:58:16
  14: __libc_start_main_impl
             at ./csu/../csu/libc-start.c:360:3
  15: <unknown>


-- neovide_r2023-10-11_17-08-51.log --
TRACE [neovide] Neovide version: 0.11.2
DEBUG [neovide::bridge::command] Starting neovim with: Command { std: "/usr/local/bin/nvim" "--embed" "-p", kill_on_drop: false }
```

So it seems like theres an issue with `config_iterator`.

The last logfile named `neovide_rCURRENT.log` was 251 lines long so I didn't include it (but if needed I can paste it here or create a pastebin link).

**Additional context**

I've tried installing `librust-gl-dev` and rebuild sort of as a hail Mary to see if it would make a difference but it didn't. I've tried to see if there were any issues that could solve my problem like #574 or [this reddit post](https://www.reddit.com/r/neovim/comments/zayybd/neovide_not_launching/) and walked through the [troubleshooting section on the website](https://neovide.dev/troubleshooting.html) (couldn't figure out how to grab the latest binary from the github actions tab though but building from source should get me the latest binary anyway, right?). If I missed something important that I should try before you provide further assistance it'd be nice if you told me where to look. Cheers!

**Comment by fredizzimo** [comment]
It seems like it can't find any configurations with a stencil size of 8 that supports transparency, which is strange. 

But it's most likely because of missing, or misconfigured GPU drivers. 

What does `glxinfo -t` show?, and if you are on wayland `eglinfo -v`

**Comment by azolus** [comment]
I get
```bash
$ glxinfo -t
name of display: :0
Error: couldn't find RGB GLX visual or fbconfig
```

**Comment by azolus** [comment]
The kernel is old because somehow it wasn't registered as default after updating. That wasn't the problem though.

I did some searching and found out that a simple
```bash
$ sudo apt install nvidia-driver
```
fixed everything. Apparently I was still running on some `libnvidia-legacy-390xx-...` packages. So everything works now, just had to run the right update. Thanks :)
