### ISSUE TITLE
Setting the wrong guifont should report errors

### ISSUE THREAD

**Issue by fredizzimo** [neovide/neovide#2077]
We have many issues related to people mistyping the font names, or just otherwise use the guifont format the wrong way for example: 
* https://github.com/neovide/neovide/issues/2054
* https://github.com/neovide/neovide/issues/1944 (this one is because a Windows bug, but we should still report that we fail to load the font, instead of showing something else)
* https://github.com/neovide/neovide/issues/1872
* https://github.com/neovide/neovide/issues/1864
* https://github.com/neovide/neovide/issues/1396

And even more issues that are already closed, for example
* https://github.com/neovide/neovide/issues/2071
* https://github.com/neovide/neovide/issues/1973
* https://github.com/neovide/neovide/issues/1882
* https://github.com/neovide/neovide/issues/1500
* https://github.com/neovide/neovide/issues/1471
* https://github.com/neovide/neovide/issues/1274
* https://github.com/neovide/neovide/issues/846
* https://github.com/neovide/neovide/issues/260

So, we clearly need to report that loading the font failed to the user, and not just in the log. This should be done with `echomsg` or similar, so that it actually shows up in Neovim.

Finally, we should also check that all fallback fonts can be loaded properly and not just the main font, like we do currently.

**Comment by Tmpod** [comment]
Might take a jab at this soon!
