### ISSUE TITLE
Neovide starts maximized after tiling on Mac

### ISSUE THREAD

**Issue by carlmueller** [neovide/neovide#2079]
**Describe the bug**
I'm using an apple silicon Mac.  If I use left-right tiling with Neovide and another application (so it's in maximized mode), and then close Neovide, the next time I start Neovide it's maximized.  This even happens if I specify the geometry with "neovide --geometry=78x45".  In contrast, neovim-qt relaunches without maximization.

**To Reproduce**
1. Use an M1 Mac
2. use left-right tiling with Neovim and another application.
3. Quit Neovim
4. Restart Neovim (with our without --geometry=78x45)
5. Neovim starts maximized.
6. It should start non-maximized

**Expected behavior**
In this situation, Neovim should start non-maximized.

**Desktop (please complete the following information):**
 - OS: MacOS Sonoma 14.0
 - Neovide Version 0.11.2
 - Neovim Version 0.9.4

**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**

[neovide_rCURRENT.log](https://github.com/neovide/neovide/files/12895519/neovide_rCURRENT.log)

**Additional context**
[neovide_r2023-10-13_12-10-12.log](https://github.com/neovide/neovide/files/12895521/neovide_r2023-10-13_12-10-12.log)

**Comment by norflin321** [comment]
i have exactly the same issue

**Comment by fredizzimo** [comment]
In this branch https://github.com/neovide/neovide/pull/1977, the commandline  size will override the saved maximized status. 

You can also disable the saving of the windows size and maximized state with this https://neovide.dev/configuration.html#remember-previous-window-size. The last saved setting will still be used, so if you launch neovide once, make it the size you want and quit. And then after that disable the saving, it should stay like that all the time

**Comment by carlmueller** [comment]
Fredizzimo:  Thanks, it works.  But it's still true that Neovim-qt has the desired behavior without any configuration.

**Comment by fredizzimo** [comment]
Yes, I don't think we should save any size or position by default. That's better handled by the OS/desktop environment/window manager. 

It's still good as an option, but I don't think it should be the default.

**Comment by carlmueller** [comment]
Thanks, it works correctly now (with version 0.12.0)
