### ISSUE TITLE
Make thickness consistent for gui=underline

### ISSUE THREAD

**Issue by habamax** [neovide/neovide#208]
Hi, is it possible to create consistent thickness for underlines?

![neovide-underline-thickness](https://user-images.githubusercontent.com/234774/77247990-1fc98600-6c47-11ea-82be-4e80d131390c.gif)

**Comment by Kethku** [comment]
This likely has to do with the lack of antialiasing on lower dpi monitors. I will add an option to enable antialiasing for this part the rendering

**Comment by Kethku** [comment]
This is fixed I believe in main.
