### ISSUE TITLE
Double-click + Drag

### ISSUE THREAD

**Issue by 9mm** [neovide/neovide#2080]
**Is your feature request related to a problem? Please describe.**

On MacOS (and Im pretty sure windows as well), if you double click in the middle of text it will auto-highlight the word. This already words correctly, in Neovide.

But... if you don't let go the second time (ie... click + clickHOLD), if you drag the cursor around it should select by word.

I realize mouse is stupid in vim, but a lot of times I will use mouse when needing to copy lines of variable names out into wherever (env variables, etc).

**Describe the solution you'd like**

To follow the standard OS functionality where click+clickHold will highlight by word instead of highlighting by character

**Comment by fredizzimo** [comment]
Hm. It works for me as documented https://neovim.io/doc/user/term.html#mouse-using

Single click drag selects by character, double click drag selects by word, triple click selects by line, and quadruple clicking selects a rectangular region.

We don't do anything special about this, but Neovide should take care of it.

Maybe your https://neovim.io/doc/user/options.html#'mousetime' is set too fast? 

Note, this was broken in Neovim for a long time, but should have been fixed last year https://github.com/neovim/neovim/issues/4754

**Comment by 9mm** [comment]
Hmm, I dont have mouse time set (ill experiment with it) but i did see that the problem doesnt happen in Neovim, only in Neovide

45 seconds:

https://www.loom.com/share/88116f6c5df84943a62f712402ee7f99

**Comment by fredizzimo** [comment]
I can repeat it on this computer to some degree, it seems like it sometimes works, but most of the times it does not.

I wonder if we should send `left` and `drag`  instead of `move` and empty https://neovim.io/doc/user/api.html#nvim_input_mouse()

But I  don't understand why Neovim would need drag at all, since it should be able to track button down and up itself.

**Comment by fredizzimo** [comment]
It turns out that it works in debug mode, but not in release mode. But the fix seems to be easy, only send the move event when not dragging. Currently we actually send both events, and that seems to confuse Neovim it they arrive too close together.

I will create a PR

**Comment by 9mm** [comment]
Sweet!! Glad that was easy one

**Comment by fredizzimo** [comment]
It should be fixed here, https://github.com/neovide/neovide/pull/2082. But, note that the PR targets main and not the rendering branch.
