### ISSUE TITLE
Opening on MacOS sometimes results in only a non-interactive title bar showing up

### ISSUE THREAD

**Issue by Shock9616** [neovide/neovide#2084]
**Describe the bug**
I haven't yet discovered what specifically causes this issue, but it seems like it might be an issue specific to the Neovide cask from homebrew rather than the formula. Sometimes when I open Neovide it will just show a title bar which I cannot interact with in any way. If I opened it from the dock, the app icon continues bouncing (the opening animation) indefinitely until I force quit it. It does not show up as an open app, so unless I tried to open it from the dock, the only way to stop it is to either restart my computer, or kill the process in Activity Monitor.

**To Reproduce**
1. Install Neovide cask via homebrew
2. Repeatedly open Neovide until it happens...?

**Expected behavior**
Neovide should open properly every time.

**Screenshots**
<img width="1800" alt="Screenshot 2023-10-18 at 1 33 53 AM" src="https://github.com/neovide/neovide/assets/28808006/13db85a2-b113-458a-978a-89a9d43e9d45">

**Desktop (please complete the following information):**
 - OS: macOS 14.0 (23A344)
 - Neovide Version 0.11.2 (20230908.153339)
 - Neovim Version v0.9.4

**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**
Since this only seems to be an issue with the cask, I haven't been able to get a log like this. I will keep trying, but I'm not sure if I'll be able to get it (unless there's a way to get the log file for the cask that I'm unaware of)

**Additional context**

**Comment by fredizzimo** [comment]
I don't know if it's the same issue or not, but there's a similar issue here
* https://github.com/neovide/neovide/issues/1964

**Comment by Shock9616** [comment]
That does seem similar. I'll try and see if I can get a log with the different debug levels to compare.

**Comment by fredizzimo** [comment]
I think I'm going to close this because of no response, and it's most likely fixed.
