### ISSUE TITLE
Neovide crashes when moving the mouse over its window

### ISSUE THREAD

**Issue by stribika** [neovide/neovide#2086]
**Describe the bug**
Neovide creates an empty black window. Moving the mouse over the window instantly crashes the program with the message

```
Backtrace saved to neovide_backtraces.log!
Neovide panicked with the message 'Mouse Input Failed: NeovimError(Some(1), "invalid button or action")'. (File: src/bridge/ui_commands.rs; Line: 71, Column: 18)
This is a bug and we would love for it to be reported to https://github.com/neovide/neovide/issues
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

Backtrace saved to neovide_backtraces.log!
Neovide panicked with the message 'Could not send serial ui command: SendError { .. }'. (File: src/bridge/ui_commands.rs; Line: 274, Column: 22)
This is a bug and we would love for it to be reported to https://github.com/neovide/neovide/issues
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

Backtrace saved to neovide_backtraces.log!
Neovide panicked with the message 'called `Result::unwrap()` on an `Err` value: SendError { .. }'. (File: src/event_aggregator.rs; Line: 51, Column: 28)
This is a bug and we would love for it to be reported to https://github.com/neovide/neovide/issues
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Alt-tabbing to another window doesn't crash, but logs the following error:

```
Backtrace saved to neovide_backtraces.log!                                                                                                                                                               
Neovide panicked with the message 'Focus Lost Failed: NeovimError(Some(0), "Invalid method: nvim_ui_set_focus")'. (File: src/bridge/ui_commands.rs; Line: 147, Column: 48)                               
This is a bug and we would love for it to be reported to https://github.com/neovide/neovide/issues                                                                                                       
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace     
```

Switching back to Neovide without touching the mouse results in this error:

```
Backtrace saved to neovide_backtraces.log!                                                                                                                                                               
Neovide panicked with the message 'Focus Gained Failed: NeovimError(Some(0), "Invalid method: nvim_ui_set_focus")'. (File: src/bridge/ui_commands.rs; Line: 150, Column: 47)                             
This is a bug and we would love for it to be reported to https://github.com/neovide/neovide/issues                                                                                                       
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace    
```

If the mouse is not over the window when I start it, and I'm careful never to move it there, the editor becomes usable after pressing `i` or any other hotkey.

**To Reproduce**
1. Install with the command: `cargo install --debug --git https://github.com/neovide/neovide`
2. Start with the command: `~/.cargo/bin/neovide --log`
3. Move the mouse over the window.
4. Watch it crash.

**Expected behavior**
I expected it to be way more difficult to quit.

**Screenshots**
![neovide-before-crash](https://github.com/neovide/neovide/assets/625063/e2f91237-3b04-4aee-b0e3-4a23d219e71c)

**Desktop (please complete the following information):**
 - OS: Devuan Linux 5.0 "Daedalus"
 - Neovide Version 0.11.2 (85234dc)
 - Neovim Version 0.7.2 (from apt)

**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**

 - [neovide_backtraces.log](https://github.com/neovide/neovide/files/13045518/neovide_backtraces.log)
 - [neovide_rCURRENT.log](https://github.com/neovide/neovide/files/13045522/neovide_rCURRENT.log)

**Additional context**
It also happens with the commit tagged 0.11.2, installed using `cargo install --debug --git https://github.com/neovide/neovide --tag 0.11.2`

**Comment by MultisampledNight** [comment]
Hi, thanks for reporting! Could you try a newer Neovim version, ideally https://github.com/neovim/neovim/releases/tag/stable?

**Comment by stribika** [comment]
That fixes it. Works with nvim 0.9.4, thank you.
