### ISSUE TITLE
Crash on protocol error KDE Wayland

### ISSUE THREAD

**Issue by phddoom** [neovide/neovide#2091]
**Describe the bug**
After starting neovide and using normally the neovide GUI crashed but the process doesn't.
If run with no fork the following message is printed: `Protocol error 0 on object wl_registry@2:` until the process is killed.

**To Reproduce**
1. Run `neovide --nofork --multigrid ~/somefile`
2. Regular KDE desktop usage with changing virtual desktops or minimizing and restoring
3. Notice GUI window crash / disappears 

**Expected behavior**
Expect no crashes on KDE Wayland due to normal virtual desktop and window management use.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Neovide Version 0.11.2
 - Neovim Version v0.9.4

**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**
[neovide_r2023-10-26_13-03-33.log](https://github.com/neovide/neovide/files/13190370/neovide_r2023-10-26_13-03-33.log)
[neovide_rCURRENT.log](https://github.com/neovide/neovide/files/13190387/neovide_rCURRENT.log)

**Additional context**

**Comment by MultisampledNight** [comment]
Hi, thanks for reporting! I can't seem to reproduce this on KDE Plasma 5.27.9 on NixOS with Neovide 0.11.2 compiled locally, though.

Could you maybe share what KDE Plasma version you're on and how you installed Neovide (most likely through pacman)? You can find the Plasma version under `pacman -Qi plasma-desktop` or graphically under the `About this System` application.

**Comment by phddoom** [comment]
My plasma version: `5.27.9-1` from `pacman -Qi plasma-desktop`

**Comment by fredizzimo** [comment]
@phddoom, do you have a `neovide_backtrackes.log` file? Could you also try running with `WAYLAND_DEBUG=1 neovide --nofork` I think you should then get more wayland debug information in the debug console. Probably way too much, but hopefully the last few lines would be useful.

I'm also running KDE plasma wayland on Arch and I don't see the same problems. But I'm mostly using the improve-render-loop branch https://github.com/neovide/neovide/pull/1977.

**Comment by phddoom** [comment]
@fredizzimo Sorry for the delay in getting this information to you. It took a while for the bug to occur.
[wayland-Default.zip](https://github.com/neovide/neovide/files/13366942/wayland-Default.zip)

Let me know if there is any other steps I should take to help track down this bug.

Thanks

**Comment by fredizzimo** [comment]
Nice compression from 1 GB to 3 MB!

I believe the relevant parts are here:
> [ 112288.093] wl_registry@2.global(58, "wl_output", 4)
[ 112288.098] zxdg_toplevel_decoration_v1@30.configure(2)
[ 112288.103] zxdg_toplevel_decoration_v1@30.configure(2)
[ 112288.106] wp_fractional_scale_v1@32.preferred_scale(180)
[ 112288.131] xdg_toplevel@29.configure(2560, 1440, array[20])
[ 112288.136] xdg_surface@28.configure(12714)
[ 112288.140] wl_registry@2.global_remove(57)
[ 112288.145] wl_registry@2.global_remove(58)
[ 112288.149] zxdg_toplevel_decoration_v1@30.configure(2)
[ 112288.153] zxdg_toplevel_decoration_v1@30.configure(2)
[ 112288.157] wp_fractional_scale_v1@32.preferred_scale(120)
[ 112288.162] xdg_toplevel@29.configure(8192, 8148, array[20])
[ 112288.166] xdg_surface@28.configure(12740)
[ 112288.170] xdg_toplevel@29.configure(8192, 8192, array[20])
[ 112288.176] xdg_surface@28.configure(12752)
[ 112288.179] wl_registry@2.global(59, "kde_output_device_v2", 2)
[ 112288.184] wl_registry@2.global(60, "wl_output", 4)
[ 112288.233] zxdg_toplevel_decoration_v1@30.configure(2)
[ 112288.238] zxdg_toplevel_decoration_v1@30.configure(2)
[ 112288.243] wp_fractional_scale_v1@32.preferred_scale(180)
[ 112288.247] xdg_toplevel@29.configure(2560, 1440, array[20])
[ 112288.254] xdg_surface@28.configure(12758)
[ 112288.342]  -> zxdg_output_v1@7.destroy()
[ 112288.351]  -> wl_output@5.release()
[ 112288.384]  -> xdg_surface@28.ack_configure(12690)
[ 112288.397]  -> wl_surface@27.set_opaque_region(nil)
[ 112288.419]  -> xdg_surface@28.set_window_geometry(0, 0, 8192, 8148)
[ 112288.454]  -> wp_viewport@31.set_destination(8192, 8148)
[ 112288.475]  -> xdg_surface@28.ack_configure(12701)
[ 112288.496]  -> wl_surface@27.set_opaque_region(nil)
[ 112288.500]  -> xdg_surface@28.set_window_geometry(0, 0, 8192, 8148)
[ 112288.506]  -> wp_viewport@31.set_destination(8192, 8148)
[ 112288.514]  -> xdg_surface@28.ack_configure(12709)
[ 112288.518]  -> wl_surface@27.set_opaque_region(nil)
[ 112288.522]  -> xdg_surface@28.set_window_geometry(0, 0, 8192, 8192)
[ 112288.529]  -> wp_viewport@31.set_destination(8192, 8192)
[ 112288.545]  -> wl_registry@2.bind(58, "wl_output", 4, new id [unknown]@36)
[ 112288.554]  -> zxdg_output_manager_v1@6.get_xdg_output(new id zxdg_output_v1@41, wl_output@36)
[ 112288.596]  -> xdg_surface@28.ack_configure(12714)
[ 112288.601]  -> wl_surface@27.set_opaque_region(nil)
[ 112288.634]  -> xdg_surface@28.set_window_geometry(0, 0, 2560, 1440)
[ 112288.656]  -> wp_viewport@31.set_destination(2560, 1440)
[ 112288.720]  -> zxdg_output_v1@41.destroy()
[ 112288.725]  -> wl_output@36.release()
[ 112288.730]  -> xdg_surface@28.ack_configure(12740)
[ 112288.734]  -> wl_surface@27.set_opaque_region(nil)
[ 112288.764]  -> xdg_surface@28.set_window_geometry(0, 0, 8192, 8148)
[ 112288.769]  -> wp_viewport@31.set_destination(8192, 8148)
[ 112288.773]  -> xdg_surface@28.ack_configure(12752)
[ 112288.777]  -> wl_surface@27.set_opaque_region(nil)
[ 112288.807]  -> xdg_surface@28.set_window_geometry(0, 0, 8192, 8192)
[ 112288.812]  -> wp_viewport@31.set_destination(8192, 8192)
[ 112288.820]  -> wl_registry@2.bind(60, "wl_output", 4, new id [unknown]@42)
[ 112288.825]  -> zxdg_output_manager_v1@6.get_xdg_output(new id zxdg_output_v1@43, wl_output@42)
[ 112288.857]  -> xdg_surface@28.ack_configure(12758)
[ 112288.861]  -> wl_surface@27.set_opaque_region(nil)
[ 112288.866]  -> xdg_surface@28.set_window_geometry(0, 0, 2560, 1440)
[ 112288.870]  -> wp_viewport@31.set_destination(2560, 1440)
[ 112289.671] wl_display@1.delete_id(7)
[ 112289.683] wl_display@1.delete_id(5)
[ 112289.688] wl_display@1.error(wl_registry@2, 0, "invalid global wl_output (58)")

The output 58 is created at the start of this sequence, but then deleted, and later used. And there also seem to be some strange window resizing going on. It resizes it to 8192x8192 and then back to 2560x1440. 

I don't really have any idea what could have happened here without studying it deeper, maybe @kchibisov knows.

**Comment by kchibisov** [comment]
It looks to me like KDE bug tbh, it advertises 2 globals for wl_output, we bind both, it doesn't like it.

**Comment by kchibisov** [comment]
Hm, maybe not a kwin bug, since remove was done, but I can't say why it ended like that...

**Comment by kchibisov** [comment]
What winit version was used here, I don't think it could happen with 0.29+?

**Comment by fredizzimo** [comment]
@kchibisov 
> What winit version was used here, I don't think it could happen with 0.29+?

Our latest release 0.11.2 uses 0.29.0-beta.0.

@phddoom, our main branch uses winit 0.29.2. Maybe it’s worth checking if that fixes it?

**Comment by kchibisov** [comment]
Also, was it only with a single window being used? Like the log doesn't make any sense to me...

**Comment by fredizzimo** [comment]
We only support a single window at the moment, so there has to be only one. 

But maybe kwin somehow duplicates the window during the virtual desktop switch? Based on the original description, I think a virtual desktop switch triggered the bug.

**Comment by kchibisov** [comment]
As discussed on `#wayland` this is a kwin bug

```
        pq  kchibisov, could it be a case of
            https://gitlab.freedesktop.org/wayland/wayland/-/issues/10 ?
        pq  kchibisov, you can see multiple wl_seat and wl_output globals. Each global
            refers to a different underlying thing, but since an output is an output, all
            outputs use the wl_output interface each.
        pq  Globals are things, interfaces are APIs, and wl_proxies are instances of an
            interface referring to a thing.
 kchibisov  pq: could, but I'm not quite sure how I end up binding the display.
 kchibisov  Like from the log it looks like a client bug
            https://github.com/neovide/neovide/issues/2091#issuecomment-1813101342 ?
 kchibisov  but in the code we reliably remove outputs.
        pq  kchibisov, this is issue 10.
 kchibisov  so it's a kwin bug?
 kchibisov  I read that you need to send things in the near same time in 10.
        pq  Originally it is a protocol mis-design, making clients vulnerable to global
            removal races, and losing that race trigger the error here.
 kchibisov  but given that I got add/remove as a 2 consequative events won't it be fine?
        pq  It has been solved by adding API (links in the issue) to send the global removal
            event first, and then much later actually destroying the global, to give time
            for clients to handle the removal. This is something the compositor needs to
            implement.
 kchibisov  Hm, I think I get the issue is that it's removed on kwin side.
        pq  between global_remove event and actual removal, a client binding to the removed
            global would still work.
        pq  yes, this is something only kwin can fix
```

**Comment by fredizzimo** [comment]
@kchibisov, thanks for the information. I will close this then, but it would be good to get a link to the KDE issue tracer, when a bug report is created, so that we can link it from here and people can watch it. I assume that someone who knows enough will create it, as I don't think I have enough information to do that myself.

**Comment by MultisampledNight** [comment]
The chatlog mentions that there is one already: https://gitlab.freedesktop.org/wayland/wayland/-/issues/10

**Comment by kchibisov** [comment]
yes, it's not fixable at the protocol level, compositors should use provide some time for globals, since client can't win the race in such a cases.

**Comment by kchibisov** [comment]
Also, @phddoom could you crash alacritty master that way?

**Comment by kchibisov** [comment]
@fredizzimo can neovide by any chance block for like 5 seconds and not poll the winit event loop? Since it could cause a thing like that in such case.

**Comment by kchibisov** [comment]
Anyway, the only way you can trigger that in kwin(as I was told by kwin developer) is **You somehow block event loop for 5 seconds and got this event**. If you're using frame callbacks and disable vsync, you can't really trigger that behavior, since you never block. If you call `swapBuffers` on the main thread, you can easily trigger that **when the window is minimized**.

**Comment by fredizzimo** [comment]
And I was also wrong in my previous message, main never used a separate thread. All of that was inside the rendering update branch that we had. I was just working on it for so long that I mixed up things.

I checked the update loop that it's using 
https://github.com/neovide/neovide/blob/113955bb68bf6715c784ea0b7ee75011c55471c9/src/window/mod.rs#L146-L148
https://github.com/neovide/neovide/blob/0.11.2/src/window/update_loop.rs

And it also turns out that it enables `vsync`, 
https://github.com/neovide/neovide/blob/113955bb68bf6715c784ea0b7ee75011c55471c9/src/cmd_line.rs#L89-L90
https://github.com/neovide/neovide/blob/113955bb68bf6715c784ea0b7ee75011c55471c9/src/renderer/opengl.rs#L106-L109

So yes it can indeed block.

It should be fixed on main though, where we always use a zero swapinterval and frame callbacks.

**Comment by kchibisov** [comment]
Well, yeah, this could clearly break it.

**Comment by fredizzimo** [comment]
Yes, thanks for the investigation 👍. Now, we just need to wait for it to be tested on main before continuing or hopefully leaving it as fixed.
