### ISSUE TITLE
Transparency issues on macOS

### ISSUE THREAD

**Issue by fredizzimo** [neovide/neovide#2094]
The rendering of transparent windows have changed on macOS, and the old recommendations about using the [background color](https://neovide.dev/configuration.html#background-color-currently-macos-only) to control the dependency does no longer apply. The reason for that is that the background color transparency and the regular transparency  (blend/pumblend/neovide_transparency) conflicts with each other.

The workaround is a bit unclear to me since I don't own a mac to test it out. But I think that you should start by  disabling the background by not setting it in your settings. After that you can control the global transparency (affects all background colors) with `g:neovide_transparency`, and the native Neovim `pumblend` and `blend` options.

The background color was originally made to control the color of the title bar, see:
* https://github.com/neovide/neovide/issues/1298
* https://github.com/neovide/neovide/pull/1459

So we need an alternative to that. Some users have reported that setting [`--frame`](https://neovide.dev/command-line-reference.html#frame) to `none` works reasonably well for certain use cases. But I think we should remove `g:neovide_background_color` completely, and implement the title  bar color some other way. And even in the case where `--frame` is the final workaround, I don't see any use for the background color, since it just cause problems and makes macOS work differently than other platforms.

We need help from mac users to find the final solution for this. Preferably a complete pull request with the required code and documentation changes.

Some discussion about the transparency issues
* https://github.com/neovide/neovide/pull/1870#pullrequestreview-1508224104
* https://github.com/neovide/neovide/pull/1870#issuecomment-1649503004 (forward from that message)

**Comment by fredizzimo** [comment]
We still need help with this. Since this is the only critical issue for creating a new release right now, after a few minor issues has been fixed and the vsync improvements have been tested.

**Comment by crupest** [comment]
Now that the vsync feature is basically done. I'm happy to push this problem forward. But like before, it may take a rather long time for me to make this. However, if nobody has time to do this, my efforts should still make sense.

I don't use the transparency function very much. So I need to make the demand clearer.

We now have two ways to achieve transparency on macos. One is `neovide_background_color`, which is unique on macos. The other is `neovide_transparency`, which is generally usable on every platform. These two ways conflict each other like there are 2 layers. `neovide_background_color` is implemented with macos platform api. It can change the transparency of title bar, but it can only control the transparency of the whole window. `neovide_transparency` is the general way and implemented in neovide, but it can not control the title bar. And some features of neovim also allow users to set transparency, so `neovide_background_color` can't do this.

So, the best result is to remove `neovide_background_color` totally and make `neovide_transparency` able to change the title bar. Do I understand this correctly? And are there any other demands I don't notice?

**Comment by fredizzimo** [comment]
I'm not sure what the best way to do it would be, but ideally, I would like to see only the current `neovide_transparency` setting remaining and that the title bar gets the `Normal` highlight color background with the neovide_transparency applied.

**Comment by crupest** [comment]
Maybe we can remove the title bar, make a top padding and draw the window buttons (close, maximum, ...) by ourselves. https://developer.apple.com/documentation/appkit/nswindow/1419173-standardwindowbutton?language=objc this api seems to allow us draw the buttons with the appearance like macos itself. How do you think? I'll give a try later.

**Comment by crupest** [comment]
A lot of apps draw title bar themselves, like vscode. I'll take a look at how they do this. After deciding how to do this, everything becomes straightforward then.
