### ISSUE TITLE
Breaking changes and new issues on main

### ISSUE THREAD

**Issue by fredizzimo** [neovide/neovide#2095]
The main branch has been updated with big improvements to the rendering, but also have following breaking changes and new issues compared to the latest 0.11.2 release. 

* Neovim 0.9.2 is needed
* All configuration file options and command line arguments are renamed to fit kebab-case, e.g. `noidle` is now `no-idle`
* `--no-fork` has no effect on Windows, the process is always a Gui application without console output. 
* `--vsync` is now on by default and `g:neovide_refresh_rate` does not have any effect unless you set `--no-vsync`
* `--multigrid` is the default and highly recommended. If you want to disable the animations you can set `g:neovide_cursor_animation_length`, `g:neovide_scroll_animation_length` and/or `g:neovide_position_animation_length` to `0`.
* The length of the `g:neovide_scroll_animation` length is not exact anymore and might differ slightly from the previous setting, so you might have to adjust it slightly, for more information see https://neovide.dev/configuration.html#scroll-animation-length
* There's a new setting  [`g:neovide_far_scroll_lines` ](https://neovide.dev/configuration.html#far-scroll-lines), which controls how much scrolling there is when you make long jumps, for example to the beginning and end of the document. That animation is much shorter than the previous default, but setting it to `9999` emulates the old behaviour.

Note that the following issues are still open, if those bother you it's recommended to set  `g:neovide_scroll_animation_length` to `0`. Or maybe find an alternative to using the winbar. For floating windows, switching the plugin might be an option, only native borders are an issue, so plugins using `plenary` or `nui` work correctly. (fix pending in https://github.com/neovide/neovide/pull/2165)
* https://github.com/neovide/neovide/issues/1550 (A Neovim issue is open https://github.com/neovim/neovim/issues/23610)
* https://github.com/neovide/neovide/issues/1446

The following issue needs fixing on the Neovim side
`:set inccommand=split` doe snot work
* https://github.com/neovide/neovide/issues/1947 (A Neovim issue is open https://github.com/neovim/neovim/issues/24802)

On macOS there are these issues
* https://github.com/neovide/neovide/issues/2093
* https://github.com/neovide/neovide/issues/2094
* https://github.com/neovide/neovide/issues/2097

On Windows make sure you have recent Nvidia drivers 526.47 or newer for slightly reduced frame drops. It has the setting Vulkan/OpenGL present method/Prefer layered on DXGI Swapchain, either true or auto(default) is ok.

I hope I didn't forget something important, but if I  did, please let me know.

**Comment by 9mm** [comment]
I did notice a crash that happens 10% of the time on launch. I don't know when it started, I think it was when I was messing around with the different branches and I didn't notice it.

I captured a log file, let me know if its immediately apparent or if I should make a new issue!

[neovide_rCURRENT.log](https://github.com/neovide/neovide/files/13232923/neovide_rCURRENT.log)

**Comment by fredizzimo** [comment]
@9mm, yes create a new issue, along with a backtraces log if you have one. I see now that you reported it here https://github.com/neovide/neovide/pull/1977#issuecomment-1774162326, but I forgot since we didn’t get further along with the debugging.

**Comment by linrongbin16** [comment]
Hi, I installed neovide on latest commit 5743356d654dbeaf213c0da3e2988c4d89c218e1, and I found the first line when scroll down looks like having multiple lines:

https://github.com/neovide/neovide/assets/6496887/8aefd2c5-38ee-41ad-91c1-6d438d2ee8b3


OS: macOS M1 chip, Ventura 13.6
nvim: latest stable v0.9.4
Neovide: main branch, commit 5743356d654dbeaf213c0da3e2988c4d89c218e1
installation: 
```bash
git clone https://github.com/neovide/neovide ~/.neovide
cd ~/.neovide
cargo install cargo-bundle
cargo bundle --release
```

**Comment by fredizzimo** [comment]
@linrongbin16, yes that's one of the issues mentioned in the original post:
* https://github.com/neovide/neovide/issues/1550

Currently the only workaround is to either disable the smooth scrolling with `g:neovide_scroll_animation_length=0` or  find an alternative workflow to the winbar.

The issue is quite tricky to solve on the Neovide side, so we have this issue open in the Neovim repository:
* https://github.com/neovim/neovim/issues/23610

But I don't think it has a high priority for them, and I have since then got an idea of how to fix it on our side. So, I think I will start working on fixing it soon. BTW, floating windows with native neovim borders have the same issue, and a similar solution will be done for that case as well.

I'm not 100% sure that my idea of fixing it will work, but I think so. I will be using the highlight groups to detect certain elements (borders, winbar) that should stay in place, and then only scroll the inner areas.

**Comment by linrongbin16** [comment]
thanks for reply, I will use the workaround.

**Comment by 9mm** [comment]
> @9mm, yes create a new issue, along with a backtraces log if you have one. I see now that you reported it here [#1977 (comment)](https://github.com/neovide/neovide/pull/1977#issuecomment-1774162326), but I forgot since we didn’t get further along with the debugging.

Ughhhh you're right, I'm sorry. I do remember that now, and I tried (and failed) to add logging. I will try again

**Comment by 9mm** [comment]
So, hmm.... @fredizzimo I just pulled from main and synced and now the issue with the window not reading from settings and remembering the size is a problem again.  I remember we fixed it (I don't remember how) but on main its doing same thing where loading always restores the top right quadrant even though I do a proper `:q` which should save settings

**Comment by fredizzimo** [comment]
@9mm. They are saved for me, are you sure that you haven't disabled the settings by mistake?  https://neovide.dev/configuration.html#remember-previous-window-size

@Kethku has also merged a lot of new changes, so maybe you could try with some older commit and see if it helps. This one in particular changed how the settings are handled https://github.com/neovide/neovide/commit/03a8429a11ccc43a8122f51593584b7d10136140, so something before that would be good to test. Or even the merge of the render improvements branch https://github.com/neovide/neovide/commit/5743356d654dbeaf213c0da3e2988c4d89c218e1

**Comment by Kethku** [comment]
For what its worth I can't reproduce that issue and I did test observing the lines and columns option before I merged. Maybe something subtle was going on that I missed...

**Comment by 9mm** [comment]
Sure, I'll try right now

**Comment by 9mm** [comment]
The "observe mousemoveevent option" is the one where when i delete that commit, it all works correctly

**Comment by Kethku** [comment]
Ok ill do some more looking tomorrow.

**Comment by Kethku** [comment]
@9mm can you try https://github.com/neovide/neovide/pull/2120 and see if its fixed for you? I think I finally figured out what changed and have a fix

**Comment by 9mm** [comment]
Sure! Thank you let me try right now

**Comment by unplugred** [comment]
Hey!
Detailing a problem I've experienced with the new build:
I've got the following script to change the transparency when doing CTRL+SHIFT+Scroll
`
let g:neovide_transparency=0.9
highlight Normal ctermbg=none
highlight NonText ctermbg=none
function! ChangeTransparency(delta)
  let g:neovide_transparency = g:neovide_transparency + a:delta
endfunction
noremap <expr><C-S-ScrollWheelUp> ChangeTransparency(0.02)
noremap <expr><C-S-ScrollWheelDown> ChangeTransparency(-0.02)
`

While it did operate correctly in 0.11.2, it broke when compiling from main.
The transparency does not update, until scrolling up and down the currently opened file.
I am running Windows 11 with an NVIDIA graphics card.

**Comment by fredizzimo** [comment]
@unplugred, can you open a new issue, so it gets properly tracked. I know what the problem is, we don't properly signal Neovide to redraw when some of the options are changed.

As a workaround you should be able to call the neovim `:redraw` command from you function.

**Comment by fredizzimo** [comment]
@crupest has now implemented vsync frame callback on macOS, so the frame stuttering issues on that should now be fixed. 

If you have previously used special command-line parameters and custom `g:neovide_refresh_rate` settings, it's recommended that you remove them and let everything be left on the defaults. The refresh rate should then be the same as the one you have configured for your monitor.

It would be nice if as many people as possible could test it out, and report any issues in 
https://github.com/neovide/neovide/issues/2093.

**Comment by fredizzimo** [comment]
I think this has served its purpose now, so closing and unpinning.
