### ISSUE TITLE
Can skia-bindings be disabled during build?

### ISSUE THREAD

**Issue by yurivict** [neovide/neovide#2096]
**Is your feature request related to a problem? Please describe.**

It seems to be extremely difficult to build skia and its bindings due to skia's use of non-standard build tools and practices.

**Describe the solution you'd like**
Possibly disable skia during neovide build.

**Describe alternatives you've considered**
n/a

**Additional context**
It seems to be very hard to build skia-bindings on FreeBSD, see https://github.com/rust-skia/rust-skia/issues/753

**Comment by fredizzimo** [comment]
Unfortunately Skia is a very integral part of Neovide and can't be disabled. We do use a configuration that downloads the pre-built binaries though, https://github.com/rust-skia/skia-binaries.

But that does not help with the FreeBSD case and Google does not want to support it https://issues.skia.org/issues/40045542. The best hope is probably the patches in the FreeBSD chromium project https://github.com/freebsd/chromium as a starting point.

But note that even if skia builds, Neovide still probably wouldn't work out of the box on FreeBSD. But I would not expect that adding support would be a too big task for someone that wants to do it.

**Comment by yurivict** [comment]
Thank you for this information.
