### ISSUE TITLE
Can not start by spotlight or double click App icon , but can launch from cli: /Applications/neovide.app/Contents/MacOS/neovide

### ISSUE THREAD

**Issue by finviman** [neovide/neovide#2112]
**Describe the bug**
can not start by alfred or click App icon , nothing happened. But can start from cli: ./Applications/neovide.app/Contents/MacOS/neovide

**To Reproduce**
In MacOS, Finder, go to Application, double click Neovide, nothing happened

**Expected behavior**
Can be launched by alfred or spotlight.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS 13.5.2 
 - Neovide Version 0.11.2
 - Neovim Version 0.9.4

**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**
there are 2 log files, both of them are too large. only TRACE log, no ERROR log.
**Additional context**

**Comment by vasac** [comment]
I had the same problem. Culprit was my `.bash_profile` or `.bashrc` config which printed something to `stderr` which then causes `neovide` to abort startup at it expects empty `stderr`.

**Comment by falcucci** [comment]
> I had the same problem. Culprit was my `.bash_profile` or `.bashrc` config which printed something to `stderr` which then causes `neovide` to abort startup at it expects empty `stderr`.

This is a reasonable answer. I had it in the past as-well, same issue.
