### ISSUE TITLE
Drop shadow causes incorrect rendering of float border

### ISSUE THREAD

**Issue by sid-6581** [neovide/neovide#2113]
**Describe the bug**
When drop shadows are enabled (which they are by default currently), float borders aren't rendered correctly. Instead of the drop shadow being under/outside the float itself, there are dark outlines around the border inside the float.

**To Reproduce**
Open a float with a border

**Expected behavior**
Drop shadow should be external to the float.

**Screenshots**
With drop shadows enabled:

![image](https://github.com/neovide/neovide/assets/28602336/3672e2a6-062e-42df-8cba-cfcec2caba9a)

With drop shadows disabled:

![image](https://github.com/neovide/neovide/assets/28602336/30d307f3-62ee-4e84-b2d7-eacdc7e8ee9e)

**Desktop (please complete the following information):**
Windows 11
Neovim nightly
neovide commit #[3cc98d5](https://github.com/neovide/neovide/commit/3cc98d56ec7ae6e6dcff188d45a1b0b521d016bc)

**Comment by Kethku** [comment]
Ah yeah thats an issue with the fake borders that are used in many plugins. They create the border by creating stacks of floating windows. I'll address this by not drawing the shadow if theres already a floating window beneath it
