### ISSUE TITLE
Ghost text on macOS

### ISSUE THREAD

**Issue by Gutawer** [neovide/neovide#2122]
**Describe the bug**
The text that used to be in the window seems to get stuck in the background after changing the buffer in any way (i.e. scrolling) with transparency on:
<img width="1034" alt="image" src="https://github.com/neovide/neovide/assets/9727338/cf116e0c-be26-4bf3-afbe-607521713868">
The effect can be "reset" by going into the macOS desktop switcher, but this shows a different but similar-vibe visual bug:
<img width="1034" alt="image" src="https://github.com/neovide/neovide/assets/9727338/c38c63ee-4a01-46bc-9b2c-72847ad48c91">

**To Reproduce**
I used a very stripped down (one-line) Neovim config to make sure this wasn't more complicated:

```lua
vim.g.neovide_transparency = 0.5
```

Then I created a buffer with random text and scrolled it. I then went into the macOS desktop switcher (gesture is three fingers upwards on the mouse pad) while focused on the Neovide window and it shows a new stuck background.

**Expected behavior**
No stuck text.

**Screenshots**
Screenshots in description.

**Desktop (please complete the following information):**

- OS: macOS 12.7.1
- Neovide Version: latest git commit (installed via `cargo install --git`)
- Neovim Version: 0.9.4

**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**
[neovide_rCURRENT.log](https://github.com/neovide/neovide/files/13318120/neovide_rCURRENT.log)

**Additional context**
My macOS version is a bit old, could just be an incompatibility? If it doesn't happen on modern macOS then feel free to close and I'll work out upgrading.

**Comment by fredizzimo** [comment]
See this issue https://github.com/neovide/neovide/issues/2094
