### ISSUE TITLE
Is it possible to change the default shell on Windows? 

### ISSUE THREAD

**Issue by mister-choo** [neovide/neovide#2124]
As the title says. There are troubles with using neovim with default windows shell. Is it possible to set the shell as zsh I have in my msys installation?

**Comment by sid-6581** [comment]
I use msys2 and zsh with no problems, I'm not sure what that has to do with neovide though?

**Comment by Kethku** [comment]
Yeah closing as not neovide. There are other places to ask neovim questions

**Comment by mister-choo** [comment]
> Yeah closing as not neovide. There are other places to ask neovim questions

Sorry, I was unclear. I mean - is it possible to choose what shell neovide run in the background. I know, that when I start neovide from the terminal everything is fine. But I if start neovide from the background cmd.exe is in the background, which causes problems.

**Comment by mister-choo** [comment]
> I use msys2 and zsh with no problems, I'm not sure what that has to do with neovide though?

May I ask. Do you start neovide only from the terminal?

**Comment by Kethku** [comment]
Im not sure i understand. What problems happen when you start neovide? I start it from powershell most often but sometimes from the start menu

**Comment by fredizzimo** [comment]
You should be able to use the environment variables `SHELL` or `COMPSPEC` https://neovim.io/doc/user/starting.html#SHELL

You can also use the shell option https://neovim.io/doc/user/options.html#'shell'
Also check out https://neovim.io/doc/user/usr_10.html#10.9

**Comment by sid-6581** [comment]
> > I use msys2 and zsh with no problems, I'm not sure what that has to do with neovide though?
> 
> May I ask. Do you start neovide only from the terminal?

No, I start it a lot of ways. From msys2, from PowerShell, from the task bar, from AutoHotKey, and from  within IDEs and Directory Opus. I haven't had any issues starting it any of those ways. I think I've left `shell` the default in my neovim config, but I do have toggleterm configured to open msys2.

**Comment by mister-choo** [comment]
> > > I use msys2 and zsh with no problems, I'm not sure what that has to do with neovide though?
> > 
> > 
> > May I ask. Do you start neovide only from the terminal?
> 
> No, I start it a lot of ways. From msys2, from PowerShell, from the task bar, from AutoHotKey, and from within IDEs and Directory Opus. I haven't had any issues starting it any of those ways. I think I've left `shell` the default in my neovim config, but I do have toggleterm configured to open msys2.

Weird. I get all sorts of errors around .get_pwd() and such

**Comment by Kethku** [comment]
We can't help you without the specific errors. Can you paste all that you encounter here?

**Comment by fredizzimo** [comment]
Also, not just the error, also the context, what were you are actually trying to do? Do you use  the built in terminal, or run some command directly from Neovim, and in the latter case what command did you try to run?

**Comment by Kethku** [comment]
Closing as no further response given. I believe this is not a problem with neovide but without further details we can't help. Please open if your issue persists with further details

**Comment by pedrohgmacedo** [comment]
> > Yeah closing as not neovide. There are other places to ask neovim questions
> 
> Sorry, I was unclear. I mean - is it possible to choose what shell neovide run in the background. I know, that when I start neovide from the terminal everything is fine. But I if start neovide from the background cmd.exe is in the background, which causes problems.

I have a somewhat similar issue. In config.toml I leave `wsl = true`. 
When I try to open a file with neovide from the windows side, for instance, a file that is associated with neovide.exe, it fails to correctly open the file.
