### ISSUE TITLE
Ligatures/Font size not working depending on how I write the space in the font's name

### ISSUE THREAD

**Issue by borealsoul** [neovide/neovide#2128]
**Describe the bug**
Depending on how I write "Monaspace Argon" in `:set guifont`, I get either the ligatures working, or I can change it's size, but not both.

**To Reproduce**
1. If I write `:set guifont="Monaspace Argon"`, ligatures work.
2. `:set guifont="Monaspace Argon:h10"`, ligatures work, but the font size doesn't change.
3. `:set guifont="Monaspace_Argon:h10"` or `Monaspace\ Argon:h10` changes the font size, but ligatures stop working
4. No matter the combination, I can't get ligatures working by setting the font with `vim.opt.guifont`

**Expected behavior**
`vim.opt.guifont="Monaspace Argon:h10"` kept ligatures working, or
`:set guifont="Monaspace Argon:h10"` made the font change it's size

**Desktop (please complete the following information):**
 - Manjaro
 - Neovide 0.11.2
 - Neovim v0.9.4

**Additional context**
I also tried the following to get the ligatures to work:

```
if vim.g.neovide then
  -- vim.g.neovide_cursor_antialiasing = false
  vim.g.neovide_cursor_vfx_mode = "ripple"
  vim.g.neovide_font_features = {
    ["Monaspace Argon"] = {
      "+ss01",
      "+ss02",
      "+ss03",
      "+ss04",
      "+ss05",
      "+ss06",
      "+ss07",
      "+ss08",
    },
  }
end

vim.opt.guifont = "Monaspace Argon"
```

**Comment by fredizzimo** [comment]
Can you try with Neovide master, it has better error reporting for the fonts? I think in the case where ligatures work, it’s actually failing to load and use some fallback.

Unfortunately it looks like all ligatures are disabled by default according to the font readme, and we have not yet merged the support for font features, so you will have to wait a bit before you can use the ligatures.
* https://github.com/neovide/neovide/pull/1920

**Comment by borealsoul** [comment]
Yes, testing it in master actually made the ligatures stop altogether. Doing any kind of `:set guifont` with the font between quotes doesn't work, but using underlines and reverse slashes do.

I don't mind waiting for the font features support, I just wondered if I was missing some setting, thanks for the support!

**Comment by fredizzimo** [comment]
The font features support has been merged, so I think this can be closed
* https://github.com/neovide/neovide/pull/2213
