### ISSUE TITLE
Neovide transparency wont update until scrolling

### ISSUE THREAD

**Issue by unplugred** [neovide/neovide#2131]
Ticket describing the comment from https://github.com/neovide/neovide/issues/2095#issuecomment-1807059512

**Describe the bug**
I've got the following script to change the transparency when doing CTRL+SHIFT+Scroll
While it did operate correctly in 0.11.2, it broke when compiling from main.
The transparency does not update, until scrolling up and down the currently opened file.

**To Reproduce**
1. Write the following code in vimrc:
```
let g:neovide_transparency=0.9
highlight Normal ctermbg=none
highlight NonText ctermbg=none
function! ChangeTransparency(delta)
  let g:neovide_transparency = g:neovide_transparency + a:delta
endfunction
noremap <expr><C-S-ScrollWheelUp> ChangeTransparency(0.02)
noremap <expr><C-S-ScrollWheelDown> ChangeTransparency(-0.02)
```
2. Open a new instance of vim, CTRL+SHIFT+Scroll to change the transparency. The transparency won't change.
3. Scroll up and down the file. The transparency will update

UPDATE: adding `redraw!` after changing the transparency fixes it.

**Expected behavior**
Transparency should update when updating g:neovide_transparency

**Desktop:**
 - OS: Windows 11
 - Neovide Version: Commit b79b7cc0be18fd36b469713e55c558835178dad5
 - Neovim Version: v0.9.2

**Comment by fredizzimo** [comment]
This should be fixed by:
* https://github.com/neovide/neovide/pull/2167
