### ISSUE TITLE
Panic closing the file 

### ISSUE THREAD

**Issue by dev-ardi** [neovide/neovide#2132]
**Describe the bug**
Panic closing the file 

**To Reproduce**
1. Close neovide

**Expected behavior**
Closes normally but instead it panics

**Desktop (please complete the following information):**

`Linux arch 6.6.1-arch1-1 #1 SMP PREEMPT_DYNAMIC Wed, 08 Nov 2023 16:05:38 +0000 x86_64 GNU/Linux`
```
NVIM v0.9.4
Build type: Release
LuaJIT 2.1.1699392533
  ```
`neovide 0.11.2`

**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**
[neovide_backtraces.log](https://github.com/neovide/neovide/files/13366657/neovide_backtraces.log)
[neovide_rCURRENT.log](https://github.com/neovide/neovide/files/13366658/neovide_rCURRENT.log)

**Additional context**

**Comment by dev-ardi** [comment]
Solved with `sudo chown ardi /home/ardi/.local/share/nvim/neovide-settings.json`.

I think that at some point I ran neovide as sudo because it had root permissions

**Comment by fredizzimo** [comment]
Edit: I saw your message after writing this, but I think the below can still be an issue.

Are you running neovim from an AppImage or something else where Neovide would not have write permission to? Remote connections to Neovim could also cause the issue.

We save our data files to the data path of Neovim for some reason (I have no idea why).

**Comment by dev-ardi** [comment]
> We save our data files to the data path of Neovim for some reason

That's not where you should save it!

**Comment by agraven** [comment]
This issue should presumably be considered addressed by #2133 and #2135

**Comment by fredizzimo** [comment]
I agree closing this
