### ISSUE TITLE
Transparency not working in subwindows neovide

### ISSUE THREAD

**Issue by Sarthak950** [neovide/neovide#2134]
**Describe the bug**
Cant get the transparency to work on some windows in the neovide like command area or telescope window

**Expected behavior**
windows should be transparent as i open the neovim in alacritty or kitty terminal emiluator 2

**Screenshots**
![231116_10-23-58](https://github.com/neovide/neovide/assets/93645760/f39c17c2-dd03-4c18-9355-8b9f769e939f)
![231116_10-25-58](https://github.com/neovide/neovide/assets/93645760/3581dd65-f124-4840-b90c-dcaacae3dc90)

**Desktop**
 - Arch
 - Neovide 0.11.2
 - Neovim 0.9.4

** intersting behaviour **
running neovide --log open a new neovide instance that have the windows transparent but any other new instance still dont have the transparent windows 

https://github.com/neovide/neovide/assets/93645760/0977a96a-7d65-4cb6-afbf-5a7c33251f5b

**Neovide config**
`if vim.g.neovide then
    vim.opt.guifont = "JetBrainsMonoNL Nerd Font Propo:h11:b:#e-subpixelantialias"
    vim.opt.linespace = 1

    vim.g.neovide_padding_top = 10
    vim.g.neovide_padding_bottom = 10
    vim.g.neovide_padding_right = 10
    vim.g.neovide_padding_left = 10

    vim.g.neovide_scale_factor = 1.0

    -- Helper function for transparency formatting
    local alpha = function()
        return string.format("%x", math.floor(255 * vim.g.transparency or 0.8))
    end
    -- g:neovide_transparency should be 0 if you want to unify transparency of content and title bar.
    vim.g.neovide_transparency = 0.6
    vim.g.transparency = 0
    vim.g.neovide_background_color = "#0f1117" .. alpha()

    vim.g.neovide_floating_blur_amount_x = 2.0
    vim.g.neovide_floating_blur_amount_y = 2.0

    vim.g.neovide_hide_mouse_when_typing = true

    vim.g.neovide_scroll_animation_length = 0.1

    vim.g.neovide_theme = 'auto'
    vim.g.neovide_refresh_rate = 60
    vim.g.neovide_confirm_quit = true
    vim.g.neovide_cursor_animation_length = 0.1
    vim.g.neovide_cursor_trail_length = 10
    vim.g.neovide_cursor_antialiasing = true
    vim.g.neovide_cursor_vfx_particle_lifetime = 1.2
    vim.g.neovide_cursor_vfx_particle_speed = 20.0
    vim.g.neovide_cursor_vfx_particle_density = 10.0

    vim.g.neovide_cursor_animate_in_insert_mode = true
    vim.g.neovide_cursor_animate_in_normal_mode = true
    vim.g.neovide_cursor_animate_in_visual_mode = true
    vim.g.neovide_cursor_animate_in_replace_mode = true
    vim.g.neovide_cursor_animate_in_command_mode = true
    vim.g.neovide_cursor_animate_in_term_mode = true
    vim.g.neovide_cursor_vfx_mode = "sonicboom"

end

dofile(vim.g.base46_cache .. "defaults")
vim.opt.rtp:prepend(lazypath)
require "plugins"

`

**Comment by fredizzimo** [comment]
This should be fixed on main, can you try with that version of Neovide?

**Comment by Sarthak950** [comment]
so should i build it from source without deleting it or remove the old one first and then build it

**Comment by fredizzimo** [comment]
If you just want to test without installing, I recommend to run neovide like this instead of `neovide`:
`cargo run --release` 

But otherwise, it's best to uninstall the other version first, and then install main with `cargo install --path .`

**Comment by fredizzimo** [comment]
I notice that you are on Arch Linux, in that case you can also use `neovide-git` from AUR

**Comment by Sarthak950** [comment]
![Uploading 231116_21-07-17.png…]()

**Comment by fredizzimo** [comment]
@Sarthak950, have you edited the `neovide.desktop` file? You can remove the `--multigrid` parameter, since it's now on by default.

**Comment by Sarthak950** [comment]
no i havent any file i just call neovide in my hyprland conf with `noevide --multigrid` option but now ii have fixed that and i have another issue
i installed it through `yay -S neovide-git` and now these are the results
![231116_21-12-09](https://github.com/neovide/neovide/assets/93645760/65cc5198-c922-4259-a4cf-f5bec143ff1d)
![231116_21-12-16](https://github.com/neovide/neovide/assets/93645760/909593a9-74af-469f-bb47-04e42eb034b0)

**Comment by fredizzimo** [comment]
That looks like what it's supposed to look like. I know that it's not perfect, we just apply transparency to all neovide background colors. So, there are some elements using the foreground color, which are not transparent. 

To fix that we need more support from Neovim https://github.com/neovim/neovim/issues/24472

**Comment by Sarthak950** [comment]
cant i just remove the color from those windows

**Comment by fredizzimo** [comment]
Yes, you can control it with https://neovim.io/doc/user/syntax.html#highlight-blend, but you can still not change the transparency of the half triangle after `NORMAL` for example.

Ideally you should be able to control all of the transparency through the highlight groups, and the color scheme should have an option for adjusting the transparency, so that it can precisely control what is transparent and what is not. Then `g:neovide_transparency` would not be needed either.

**Comment by Sarthak950** [comment]
i just removed the git version and installed non git and it seem to fix the issue 
neovide version 0.11.2

**Comment by Sarthak950** [comment]
it looks like multigrid is the culprit here

**Comment by fredizzimo** [comment]
To be honest, I don't know which issue you are talking about anymore. In your new screenshot I can see your desktop background shining through the telescope window.

You can make the telescope window more transparent by the `telescope.defaults.winblend` option, see the telescope help for that.

**Comment by Sarthak950** [comment]
this is what i am talking about 


https://github.com/neovide/neovide/assets/93645760/db92f1b4-f0c3-4579-8124-5e0071c759ef

can i enable smooth scrolling without multigrid @fredizzimo

**Comment by fredizzimo** [comment]
Yes, but what's the issue with this one https://github.com/neovide/neovide/issues/2134#issuecomment-1814717198

![231116_21-12-09](https://github.com/neovide/neovide/assets/93645760/65cc5198-c922-4259-a4cf-f5bec143ff1d)

That one has a transparent background for the telescope window.

**Comment by Sarthak950** [comment]
its black and not pleasing
its just defeats the point of putting work on arch at all
i dont want to be rude in any sense i just want to understand is there a way to fix it

**Comment by fredizzimo** [comment]
Yes, by changing the winblend option of telescope, https://github.com/nvim-telescope/telescope.nvim/blob/18774ec7929c8a8003a91e9e1f69f6c32258bbfe/doc/telescope.txt#L214-L219

By setting that to 1, you get the same transparency as the main background.

**Comment by fredizzimo** [comment]
To add more context, I believe it would be a bug to not render the floating window darker if you use any other `neovide_transparency` than 0.

For example: Take a real-world example of two semi-transparent sheets of glass. If you add them on top of each other, the things under them will look darker. But if the top one is fully transparent, then the color underneath them will not change. 

So, to achieve the same thing in Neovide you need to make the top layer (telescope) either fully transparent or at least more transparent.

**Comment by williamhCode** [comment]
In some cases for example the toggleterm border, the blend doesn't work but for telescope it's really weird. Normally in my terminal the blend amount is the same across the telescope popup. But in Neovide, the text area is more opaque than the borders. In fact, it's not just that transparency is not working, but it's just less transparent.

Telescope:
<img width="1722" alt="image" src="https://github.com/neovide/neovide/assets/83525937/994b35cf-a471-4d84-9643-950c399f9ee5">

Toggleterm:
<img width="1722" alt="image" src="https://github.com/neovide/neovide/assets/83525937/1bf22510-13a5-423a-a8d8-4b9afdf925a1">

**Comment by fredizzimo** [comment]
@williamhCode 

That's a bug in telescope, see this https://github.com/neovide/neovide/issues/1676

**Comment by williamhCode** [comment]
@fredizzimo 
I see, that makes so much more sense given the inconsistency between toggleterm and telescope.

**Comment by fredizzimo** [comment]
Closing this, as I believe everything works as it should, except for bugs in plugins like telescope

**Comment by fredizzimo** [comment]
I created a proposal for dealing with global transparency
* #2471
