### ISSUE TITLE
neovide maximized does not work in wayland 

### ISSUE THREAD

**Issue by busaster** [neovide/neovide#2137]
Linux Ubuntu 22.04.3 LTS with wayland

Neoide version 0.10.0-dev

Launch command "neoide --maximized" from command line or via a .desktop file
The windows pops up but it is not maximized.

![image](https://github.com/neovide/neovide/assets/1733338/5bb6a315-ccca-40c1-a1b3-d64d39a2e2e1)

**Comment by fredizzimo** [comment]
On my system this happens maybe once in ten tries. Most of the time it's maximized correctly.

In any case it looks like a winit, wayland or gnome bug, but probably need a bit more investigation before reporting. I'm currently on gnome and haven't tested with any other DE/window manger yet.

I can't repeat it with the `maximized` winit example, so I don't think changing the `maximized` state is the trigger, it's probably the fact that we call `show` and `maximized` right after each other.

**Comment by mati865** [comment]
FYI Alacritty has the same issue, it supposedly has been fixed on the master but hasn't made it to the release yet: https://github.com/alacritty/alacritty/issues/6184

**Comment by fredizzimo** [comment]
Can you test if this is fixed on main? I think it might have been fixed by
* https://github.com/neovide/neovide/pull/2205

But I don't have a computer to test on for one week more.

**Comment by mati865** [comment]
I haven't observed it since that PR was merged to main branch.

**Comment by fredizzimo** [comment]
Nice, I'm going to close this then.
