### ISSUE TITLE
The first letter invisible when editing latex file.

### ISSUE THREAD

**Issue by chen-gz** [neovide/neovide#2144]
**Describe the bug**
The first letter invisible when editing latex file.
<img width="82" alt="image" src="https://github.com/neovide/neovide/assets/18215354/24c47984-8794-421c-a87d-b8ad6a4ceda7">

**To Reproduce**
1. install default lazyvim as configuration. (I will try to find out the minimum configuration later).
2. open an ".tex" file.

**Expected behavior**
<img width="58" alt="image" src="https://github.com/neovide/neovide/assets/18215354/bfb40714-6664-482b-90ba-d7888f79c1f8">
This screenshot is running neovim from terminal.

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 11 WSL]
 - Neovide Version [e.g. 0.10.4]
 - Neovim Version [e.g. 0.9.4]

**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**
[neovide_r2023-11-24_16-18-18.log](https://github.com/neovide/neovide/files/13462920/neovide_r2023-11-24_16-18-18.log)

**Comment by MultisampledNight** [comment]
Hi! Your Neovide seems to be pretty old, could you please try the latest release (currently 0.11.2)?

**Comment by chen-gz** [comment]
Thank you. I just try 0.11.2. Everything works great.
FYI, I was installing neovide using winget (https://winstall.app/apps/Neovim.Neovim). The version is [v0.10.4].

**Comment by MultisampledNight** [comment]
Ah, well. I don't know who maintains the winget package, and I can't do it myself since I'm not on Windows.

Closing as fixed in newer version.

**Comment by fredizzimo** [comment]
This was the main reson for the 0.11.2 release https://github.com/neovide/neovide/releases/tag/0.11.2 and fixed by https://github.com/neovide/neovide/pull/2012
