### ISSUE TITLE
Support for X1Mouse and X2Mouse

### ISSUE THREAD

**Issue by raggi** [neovide/neovide#2148]
**Is your feature request related to a problem? Please describe.**

I have two mouse side-buttons, which in old Vim keycodes are typically `<X1Mouse>` and `<X2Mouse>`. I would like to be able to use them in Neovide. I use them all the time in other code environments to navigate forward and backward, and would do the same in Neovide + Neovim with binding them to `<C-O>` and `<C-I>`.

**Describe the solution you'd like**

I would like the events to be sent to Neovim such that they map to X1Mouse and X2Mouse events.

**Describe alternatives you've considered**

I've checked if they're supported already, and don't seem to be. `C-V` followed by pressing them does nothing. As I can't capture an event myself, the only other thing I could do would be to remap the mouse buttons themselves to keybinds, but that would break them in, say, my browser instead.

**Additional context**

They appear to be available as events in winit: https://docs.rs/winit/latest/winit/event/enum.MouseButton.html

**Comment by fredizzimo** [comment]
Could you create an issue in the nvim repository? `nvim_input_mouse` unfortunately does not accept those buttons https://neovim.io/doc/user/api.html#nvim_input_mouse()

**Comment by agraven** [comment]
I filed an issue. I'll give implementing it upstream a shot too if I get the time.

**Comment by Sam-programs** [comment]
Is there anything wrong with using `nvim_input` to send the keycodes instead?
```lua
vim.keymap.set('n','<X1Mouse>','dd')
vim.api.nvim_input('<X1Mouse>')
```

**Comment by fredizzimo** [comment]
That could work as a quick workaround, but it would not support double, and triple clicking, dragging or cursor positions.

**Comment by agraven** [comment]
I filed an MR against upstream which implements api support: https://github.com/neovim/neovim/pull/26279
