### ISSUE TITLE
Error when starting neovide

### ISSUE THREAD

**Issue by sandermarechal** [neovide/neovide#2155]
**Describe the bug**
I downloaded the pre-built binary of neovide (https://github.com/neovide/neovide/releases/download/0.11.2/neovide-linux-x86_64.tar.gz). When attempting to start it, a window pops up with the following error (transcribed, so beware my typos):

```
Error detected while processing VimEnter Autocommands for "*":
Error executing lua callback: [string "<nvim>"]:96: attempt to call field 'nvim_exec2'

stack traceback:
    [string "<nvim>"]:96: in function 'get_intro_lines'
    [string "<nvim>"]:162: in function <[string "<nvim>"]:151>
Press ENTER or type command to continue
``` 

I am running Debian stable (bookworm) which has nvim v0.7.2. `nvim --version` says:

```
NVIM v0.7.2
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by team+vim@tracker.debian.org

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

**To Reproduce**
1. Download https://github.com/neovide/neovide/releases/download/0.11.2/neovide-linux-x86_64.tar.gz
2. Unpack
3. Run neovide

**Desktop (please complete the following information):**
 - OS: Debian stable (bookworm)
 - Neovide Version: 0.11.2
 - Neovim Version: 0.7.2

**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**

```
TRACE [neovide] Neovide version: 0.11.2
DEBUG [neovide::bridge::command] Starting neovim with: Command { std: "/usr/bin/nvim" "--embed" "-p", kill_on_drop: false }
```

**Comment by fredizzimo** [comment]
It's an oversight by us, we haven't specified the minimum requirements properly. I think that Neovide 0.11.2 requires minimum Neovim 0.8, but it might even be 0.9. The next release will require 0.9.2, and an error message will be shown if that's not the case.

So, your problem should be fixed by updating Neovim.
