### ISSUE TITLE
Performance regression on Wayland with 6c9b9219dbbd43e3eb6be9fe725d68e8e9ee2561

### ISSUE THREAD

**Issue by wroyca** [neovide/neovide#2162]
**Describe the bug**
Starting with https://github.com/neovide/neovide/commit/6c9b9219dbbd43e3eb6be9fe725d68e8e9ee2561, there's a performance regression on Wayland, with noticeable latency and lag input while typing and scrolling.

**To Reproduce**
1. Checkout 6c9b9219dbbd43e3eb6be9fe725d68e8e9ee2561 (or master)
2. Install with Cargo.
3. Start using Neovim as you normally would.
4. See noticeable performance issues.

**Expected behavior**
This is not an issue with the preceding commit (c2c2179060f89766939b036f72b8404f7aeb7536), in which performance maintains proper smoothness with no latency.

**Desktop (please complete the following information):**
 - OS: Fedora 39 (GNOME 45)
 - Neovide Version: 0787fd1828acb2b87ae2b73c9482adc1dcd0976f
 - Neovim Version: v0.10.0-dev+1741-gc45d1e32a

**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**
[neovide_rCURRENT.log](https://github.com/neovide/neovide/files/13537059/neovide_rCURRENT.log)

**Additional context**
I run the kernel with ```preempt=full``` which may (or may not) impact said performance.

**Comment by fredizzimo** [comment]
It should be no worse than other platforms, and it does not really bother me, so I haven't made a fix yet. But there's indeed a pointless latency, due to the event loop only waking up with a timer or when there are window events, and not when there are new updates from Neovim. We should probably deliver those as winit user events instead to properly wake up the loop.

A workaround is to set `neovide_refresh_rate_idle` to something smaller like 60 or 120.

**Comment by wroyca** [comment]
> But there's indeed a pointless latency, due to the event loop only waking up with a timer or when there are window events, and not when there are new updates from Neovim. 

Thank for the insight!

> A workaround is to set `neovide_refresh_rate_idle` to something smaller like 60 or 120.

Unfortunately, that doesn't help on my side. I suspect this is very hardware-specific and that I'm perhaps I'm just one isolated case

**Comment by fredizzimo** [comment]
Could you install tracy https://github.com/wolfpld/tracy and run `tracy-capture -o latency.tracy & cargo run --release --features profiling -- --no-fork`?  And attach `latency.tacy` here.

The file should show if the loop is waking up regularly at least every `neovide_refresh_rate_idle` interval. I'm not sure if everything is properly annotated to determine the real latency, but it should allow us to get started to diagnose the problem.

**Comment by fredizzimo** [comment]
I'm not sure if this helps or not:
* https://github.com/neovide/neovide/pull/2167

But at least I can't notice any latency with that anymore.

**Comment by wroyca** [comment]
> Could you install tracy https://github.com/wolfpld/tracy and run tracy-capture -o latency.tracy & cargo run --release --features profiling -- --no-fork? And attach latency.tacy here.

Sorry, but no clue how. Neither make, meson, nor cmake produce "tracy-capture". The closest I got was the `/capture/` directory with `capture-release`, but that doesn't yield any results, so it doesn't seem to be the right thing.

> I'm not sure if this helps or not:
> 
>     * [fix: Completely event driven update loop #2167](https://github.com/neovide/neovide/pull/2167)
> 
> 
> But at least I can't notice any latency with that anymore.

Looks good on my side as well. I don't see lag input any longer. Thank!

**Comment by fredizzimo** [comment]
This was fixed by #2167
