### ISSUE TITLE
"blinkon" doesn't blink

### ISSUE THREAD

**Issue by 9mm** [neovide/neovide#2164]
**Describe the bug**

If using a vim setting like this:

```
vim.opt.guicursor = "a:blinkon100"
```

The square cursor doesn't blink

**Expected behavior**

It should blink 👁️

**Desktop (please complete the following information):**
 - OS: 14.1.2 (23B92)
 - Neovide Version Latest `main` branch
 - Neovim Version NVIM v0.9.4

**Comment by fredizzimo** [comment]
I think it might need the full format `set guicursor=a:blinkwait700-blinkoff400-blinkon175` but that does not work either. The actual option works, since the shape can be changed.

**Comment by 9mm** [comment]
Yes sorry I should have added that.

I actually had `guicursor = ""` for the longest time, and only realized later hmm......... maybe I want to try blink.

**Comment by fredizzimo** [comment]
This should be fixed by
* https://github.com/neovide/neovide/pull/2167

**Comment by 9mm** [comment]
Ah, I just noticed you already said that about the full format. I must have missed that the first time.

**Comment by 9mm** [comment]
thanks!

**Comment by ddevaal** [comment]
Is this fixed in Neovide 0.12.0? I'm on 0.12.2 (macOS) and I can't get blinking to work. `vim.opt.guicursor = "a:blinkon100"` doesn't do anything for me. It would be so cool if we can get this animation too: https://github.com/neovide/neovide/pull/2167#issuecomment-1859037271 ❤️‍🔥❤️‍🔥❤️‍🔥
