### ISSUE TITLE
Shrink window will leave previous boundary on screen.

### ISSUE THREAD

**Issue by RomaLzhih** [neovide/neovide#2172]
**Describe the bug**
When neovide launches and click to be maximize, it will leave the initial window boundary remain on the screen.

**To Reproduce**
I am using the `wsl` to launch the neovide with command `neovide`. 
Below is my configuration in `init.lua`

```
if vim.g.neovide then
  -- Put anything you want to happen only in Neovide here
  vim.g.neovide_padding_top = 0
  vim.g.neovide_padding_bottom = 0
  vim.g.neovide_padding_right = 0
  vim.g.neovide_padding_left = 0
  -- vim.g.neovide_floating_shadow = false
  vim.g.neovide_transparency = 0.9
  vim.g.neovide_cursor_vfx_mode = "railgun"
  -- vim.g.neovide_fullscreen = true
end
```

**Expected behavior**
No boundary left. 

**Screenshots**
![Weixin Screenshot_20231208150251](https://github.com/neovide/neovide/assets/45626759/e91e95b1-638d-482b-9472-03ea8d245c73)
![Weixin Screenshot_20231208150303](https://github.com/neovide/neovide/assets/45626759/295b7a37-afa3-45d2-8464-888701d541ec)

**Desktop (please complete the following information):**
 - wsl
 - Neovide Version [e.g. 0.11.2]
 - Neovim Version [e.g. 0.9.4]

**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**

[neovide_rCURRENT.log](https://github.com/neovide/neovide/files/13621617/neovide_rCURRENT.log)

Very thanks!

**Comment by fredizzimo** [comment]
Unfortunately we don't have the resources to try to work around bugs in Microsoft's Weston based WSLg compositor. And even if we did, the performance would be subpar compared to the native windows versions.

So I recommend that you use `neovide --wsl`, on the windows side https://neovide.dev/command-line-reference.html#wsl or alternatively start a server instance `nvim --listen` followed by `neovide.exe --server` https://neovide.dev/command-line-reference.html#neovim-server, which is much faster and allows you to work completely inside WSL, you can wrap that inside a bash script.

You can also use https://github.com/mhinz/neovim-remote, to keep one instance open all the time, and just open new buffers inside that instance.

**Comment by RomaLzhih** [comment]
It works, thanks very much!
