### ISSUE TITLE
MacOS: using `--server` CLI option causes nvim binary not to be found

### ISSUE THREAD

**Issue by proofer** [neovide/neovide#2177]
**Describe the bug**
When starting in MacOS terminal, adding `--server /tmp/neovide.pipe` outputs:
> ERROR [neovide::error_handling] Could not locate or start neovim process: No such file or directory (os error 2)

and a small (relative to my previous remembered large size) and unresponsive window opens with title `Neovide`  and a block cursor at the upper left. Same behavior, except no error message output, if the option is written 
`--server=/tmp/neovide.pipe` (with an equal sign instead of space).

**To Reproduce**
1. In terminal, type : `/Applications/Neovide.app/Contents/MacOS/neovide --server /tmp/foobar.pipe`

**Expected behavior**
Neovide opens with normal (for me) large window containing embedded nvim initial display, plus effect of `--server`.

**Desktop (please complete the following information):**
 - OS: MacOS 14.1.2
 - Neovide Version 0.11.2
 - Neovim Version 0.9.4

**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**
[neovide_rCURRENT.log](https://github.com/neovide/neovide/files/13664754/neovide_rCURRENT.log)
(I chose not to paste ~1 MB here.)

**Additional context**
Apple silicon

**Comment by fredizzimo** [comment]
Did you start the `nvim` server first with `nvim --listen`?  Neovide does not start it automatically. 

The error should also be properly reported in our latest main version, but it has not made it into a release version yet.

**Comment by proofer** [comment]
(Amazed by your rapid response time -- thanks!) OK, that works. It does leave an unneeded terminal (iTerm2 in my case) window open, but that's minor.

BTW, the reason I want RPC is to facilitate having Neovide cooperate when the user double-clicks a document (source code, etc.) file in MacOS Finder. I'm developing a shell script-based application that would be the default for such files.

**Comment by fredizzimo** [comment]
This might already do at leaset close to what you want
https://github.com/mhinz/neovim-remote 

And you don't even need to start a server, if you just start `neovide` normally, then you can type `:echo v:servername` to get the address of the server.

Then you can use `nvr --servername /run/user/1000/nvim.351873.0 README.md` to open a file inside that instance, replace  `/run/user/1000/nvim.351873.0` with the address  `v:servername` gives.  You might want to add something to your Neovim `init.lua` that writes it to a more stable location that you can use.

**Comment by proofer** [comment]
I had looked at nvr, but don't understand why I'd need it -- which may well be due to my lack of experience with nvim RPC. I want to accommodate users who double-click on a file when there's no current instance of nvim. If my init.lua calls `vim.fn.serverstart(my-pipe-address)` then I think my shell application should be able to remote-send to it to `edit` the double-clicked file.

**Comment by fredizzimo** [comment]
Yes, you can use `vim.fn.serverstart` if you want to start another server, but as mentioned there's already one running that you can use. 

I missed that Neovim 0.7.0 added the remote support back last year, so I guess `nvr` is no longer needed, although it still seems to be more flexible.

**Comment by proofer** [comment]
What I've done is kind of hacky but it works. --Hacky because it depends on undocumented details of nvim's creation of each instance's default server socket.

```
#!/bin/sh

# Open the argument file in the most recent instance of nvim, which is
# intended(?!) to be that attached to a GUI editor such as Neovide or goneovim.
# The editor is specified in ~/dev/editorOpen/editorApp.txt
# This script is executed by an Automator applet. The Automator shell script code:
# for f in "$@"
# do
#	/bin/zsh [path to this .sh file] "$f"
# done

app_path=$(head -n 1 ~/dev/editorOpen/editorApp.txt) # e.g., /Applications/MyEditor.app
# Get the Executable file value, e.g., myeditor, from the app's Info.plist:
editor_cmd_name="$(defaults read "$app_path/Contents/Info.plist" CFBundleExecutable)"

if [[ -z $(pgrep $editor_cmd_name) ]]; then
    open -a $app_path/Contents/MacOS/$editor_cmd_name --arch=x86_64
fi

ls_endian='head' # newest instance of nvim
# ls_endian='tail' # oldest instance of nvim

sockets_dir=$(ls -t ${TMPDIR}nvim.$USER/ | $ls_endian -n 1)  # nvim directory containing socket file(s)
socket_file=$(ls -t ${TMPDIR}nvim.$USER/$sockets_dir/nvim.*.0 | head -n 1)
/usr/local/bin/nvim --server $socket_file --remote-send "<C-\><C-n>:e $1<CR>"

# ${TMPDIR}nvim.$USER/ contains 6-character directories of the base socket file(s).
# Socket files names: nvim.ddddd.0
# ls -t to sort in descending mod time, so to get newest in an ls:
# ls -t | head -n1
```
