### ISSUE TITLE
Crashes on startup

### ISSUE THREAD

**Issue by Jay-Waves** [neovide/neovide#2190]
**Describe the bug**

love neovide, but frequently **crashes on startup** recently. By the way, I can open nvim independently.

**To Reproduce**

Steps to reproduce the behavior: i don't know how you can reproduce.

**Expected behavior**

correctly startup.

**Screenshots**

Seem that neovide tries to open a terminal, it just blinks and exits

**Desktop (please complete the following information):**
 - OS: windows 10
 - Neovide Version 0.10.4
 - Neovim Version 0.9.4
 - Nvida RTX3070, Version 537.13, CUDA Version 12.2

**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**

the neovide_rCurrent.log:
```
TRACE [neovide] Neovide version: 0.11.2
DEBUG [neovide::bridge::command] Starting neovim with: Command { std: "E:\\editor\\nvim\\bin\\nvim.exe" "--embed" "-p", kill_on_drop: false }
DEBUG [neovide::settings::window_size] Loaded window settings: Windowed { position: PhysicalPosition { x: 297, y: 134 }, pixel_size: Some(PhysicalSize { width: 1071, height: 749 }) }
TRACE [neovide::window::window_wrapper] repositioned window: true
DEBUG [neovide::renderer::fonts::caching_shaper] Original font_size: 18.67px
TRACE [neovide::renderer::fonts::font_loader] Loading font FontKey { bold: false, italic: false, family_name: None, hinting: Full, edging: AntiAlias }
DEBUG [neovide::renderer::fonts::caching_shaper] Original font_width: 11.49px
DEBUG [neovide::renderer::fonts::caching_shaper] Font width: 11.49px (avg: 11.49px)
DEBUG [neovide::renderer::fonts::caching_shaper] Fudge factor: 0.96
DEBUG [neovide::renderer::fonts::caching_shaper] Fudged font size: 17.88px
DEBUG [neovide::renderer::fonts::caching_shaper] Fudged font width: 11.00px
TRACE [neovide::renderer::fonts::font_loader] Loading font FontKey { bold: false, italic: false, family_name: None, hinting: Full, edging: AntiAlias }
TRACE [neovide::renderer::fonts::font_loader] Loading font FontKey { bold: false, italic: false, family_name: None, hinting: Full, edging: AntiAlias }
INFO [neovide::bridge::setup] Neovide registered to nvim with channel id 1
INFO [neovide::bridge] Neovim process attached
```

round_log:
```
TRACE [neovide] Neovide version: 0.11.2
DEBUG [neovide::bridge::command] Starting neovim with: Command { std: "E:\\editor\\nvim\\bin\\nvim.exe" "--embed" "-p", kill_on_drop: false }
```

**Additional context**

```
2023-12-19 11:46:01 - Neovide panicked with the message 'Could not create interface'. (File: src\window\renderer.rs; Line: 60, Column: 10)
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: <unknown>
  14: BaseThreadInitThunk
  15: RtlUserThreadStart
```

**Comment by fredizzimo** [comment]
It looks like the the `eglGetCurrentDisplay` function is missing, which might be caused by outdated graphics card drivers or unsupported hardware. But it could also be something else.

Could you try updating the drivers to the latest version? Which graphics card do you have, and is Windows 10 the correct OS? You left `e.g.`, so I'm not sure if it's correct.

**Comment by Jay-Waves** [comment]
Thanks for your patience, more information has been updated

**Comment by fredizzimo** [comment]
Thanks, I think the Neovide version is still wrong in your information, the logs says 0.11.2

And I read the code wrong it's not `eglGetCurrentDisplay` that's failing, but some other function needed by skia. Your graphics card should definitely be supported, and the drivers are quite new, so it's probably not that either.

This can be very tricky to debug, but maybe it's possible with some well targeted log statements. But before that, would it be possible for you to compile Neovide yourself and try the latest main version? A lot of things has changed there, including updating the glutin and skia libraries, which are both involved here.

**Comment by Jay-Waves** [comment]
Everything is fine after compiling neovide myself. Thanks a lot. 🤗
