### ISSUE TITLE
Is it possible to specify neovim-bin while setting wsl = true?

### ISSUE THREAD

**Issue by nullptr-yxw** [neovide/neovide#2193]
I'd like to use a neovim version manager [`bob`](https://github.com/MordechaiHadad/bob), which will put the neovim in `"~/.local/share/bob/nvim-bin/nvim"`, but not `"/usr/bin/nvim"`. As a result, neovide cannot find the nvim
```
~> neovide
ERROR: nvim not found!
```
(the `wsl -e` cannot find the nvim as well)
```
~> wsl -e nvim
<3>WSL (1912) ERROR: CreateProcessEntryCommon:502: execvpe nvim failed 2
<3>WSL (1912) ERROR: CreateProcessEntryCommon:505: Create process not expected to return
```
I have set `neovim-bin = "/home/yxw/.local/share/bob/nvim-bin/nvim"`, but it doesn't work still.
So is it possible to allow users to specify neovim-bin while using wsl?

**Comment by fredizzimo** [comment]
Yes, both the config file and `neovide --wsl --nvim-bin /home/yxw/.local/share/bob/nvim-bin/nvim` should work. I use that feature all the time when testing.

Can you compile from source and test the latest main version of Neovide, that one should give you better diagnostics?

**Comment by nullptr-yxw** [comment]
> Yes, both the config file and `neovide --wsl --nvim-bin /home/yxw/.local/share/bob/nvim-bin/nvim` should work. I use that feature all the time when testing.
> 
> Can you compile from source and test the latest main version of Neovide, that one should give you better diagnostics?

Thanks for your answer. My current neovide version is `0.11.2`, and it looks like a bit difficult to get the latest version by compiling from the source. Is there any tutorials or instructions?
And It is a bit strange that `neovide --wsl --nvim-bin /home/yxw/.local/share/bob/nvim-bin/nvim` can work well as expected, while config file cannot.

**Comment by fredizzimo** [comment]
We have instructions for compiling from source here https://neovide.dev/installation.html. But you can also try the binaries produced by the CI, this is the latest version of main https://github.com/neovide/neovide/actions/runs/7243302784

**Comment by nullptr-yxw** [comment]
> We have instructions for compiling from source here https://neovide.dev/installation.html. But you can also try the binaries produced by the CI, this is the latest version of main https://github.com/neovide/neovide/actions/runs/7243302784

Ok, it can work well now with the latest version. Thank you very much

**Comment by fredizzimo** [comment]
Closing as fixed
