### ISSUE TITLE
[FR] - Vim reload

### ISSUE THREAD

**Issue by JGabrielGruber** [neovide/neovide#2196]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated to have to re-open neovide when I change my nvim config

**Describe the solution you'd like**
Would be really useful to have a shortcut to reload the nvim

**Describe alternatives you've considered**
Also reloading the Neovide is very acceptable too! An auto-reload config would be even better!!

**Additional context**
Any feature that allows me to continue working on my neovide without having to manually re-open it would be perfect!

Also, thank you very much for your work, I'm loving it!

**Comment by dineshKumar777** [comment]
:so %
This command will reload the config without restarting. 

https://superuser.com/a/132030

**Comment by JGabrielGruber** [comment]
> :so % This command will reload the config without restarting.
> 
> https://superuser.com/a/132030

I appreciate your help, but that's doesn't help when you're more elaborated nvim configs with plugins and Lua.
Really sorry, my fault, I set the bar very low; I will fix my description.

**Comment by JGabrielGruber** [comment]
Too complex to explain, various possibles solutions, better close it.
I thought it would be a cool feature since Neovide is controlling nvim.
