### ISSUE TITLE
Don't render the whole ligature under the cursor

### ISSUE THREAD

**Issue by REmerald** [neovide/neovide#2202]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I'm trying to change a character, but the next/previous one is obscured by the part of the ligature.

**Describe the solution you'd like**
[See kitty's `disable_ligatures cursor`.](https://sw.kovidgoyal.net/kitty/conf/#opt-kitty.disable_ligatures)

**Describe alternatives you've considered**
Don't use ligatures at all, I guess.

**Additional context**
Neovide
![image](https://github.com/neovide/neovide/assets/55359236/d14ce4d0-cc57-4ac3-a1ef-e7eaf1e70935)
Kitty `disable_ligatures cursor`
![image](https://github.com/neovide/neovide/assets/55359236/8fd27c1b-2935-4a7f-8210-60902c31656f)

**Comment by Kethku** [comment]
My expectation when writing this originally was that the way it works today is a reasonable compromise while preventing the cursor position from adjusting text rendering under it which feels weird. The cursor character inside of the block acts as a window which reveals what the actual character is. So Im inclined to say this is a wont fix as theres a different tradeoff being taken here

**Comment by Kethku** [comment]
Marking wont fix just to keep things clear but feel free to reopen if you wanna chat more
