### ISSUE TITLE
fedora 39  aarch64 failed to load driver: zink

### ISSUE THREAD

**Issue by stockxiay** [neovide/neovide#2219]
fedora 39 aarch64
MESA: error: ZINK: failed to choose pdev
glx: failed to create drisw screen
failed to load driver: zink

**Comment by stockxiay** [comment]
fedora 39 aarch64 
MESA: error: ZINK: failed to choose pdev
glx: failed to create drisw screen
failed to load driver: zink

**Comment by fredizzimo** [comment]
This is most likely caused by a broken mesa update https://www.reddit.com/r/Fedora/comments/18ko4iy/mesa_23_update_broken/
