### ISSUE TITLE
Unix sockets forwarded over SSH fails to connect

### ISSUE THREAD

**Issue by krlhBlupine** [neovide/neovide#2220]
**Describe the bug:**
Neovide gives a version error when connecting to a remote instance via SSH socket forwarding.

**To Reproduce**
    0. `nvim -v` : `NVIM v0.9.4` , `neovide -V` : `neovide 0.12.0`
    1. Set up a local nvim instance, `nvim --headless --listen /path/to/socket0`
    2. forward over ssh, `ssh -L /path/to/socket1:/path/to/socket0 localhost`
    3. run neovide, `neovide --server=/path/to/socket1`
    4. receive a version error specifying I need to have at least version 0.9.2 of nvim

**Expected behavior**
I expected to get a connection to the instance of nvim. I verified I have the latest versions of both packages, and I'm not quite sure what's going on. The behavior only occurs when forwarding over ssh, if I connect to the socket directly everything works as expected. The bug occurs when connecting both to localhost and to a remote server.

**Screenshots**
[No screenshots]

**Desktop (please complete the following information):**
 - OS: Archlinux, linux kernel 6.6.3
 - Neovide Version 0.12.0
 - Neovim Version 0.9.4
 - OpenSSH_9.6p1, OpenSSL 3.2.0 23 Nov 2023

**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**

When launching ssh'd instance:
> TRACE [neovide] Neovide version: 0.12.0
> DEBUG [neovide::settings::window_size] Loaded window settings: Maximized
> ERROR [neovide::error_handling] Neovide just crashed :(
> This is the error that caused the crash. In case you don't know what to do with this, please feel free to report this on https://github.com/neovide/neovide/issues!
> 
> Neovide requires nvim version 0.9.2 or higher. Download the latest version here https://github.com/neovim/neovim/wiki/Installing-Neovim

When launching normally:
[neovide_rCURRENT.log](https://github.com/neovide/neovide/files/13790732/neovide_rCURRENT.log)

**Additional context**
I've been working on a script to automate this sort of thing (really rough right now, but getting there.)

[remote-nvide.txt](https://github.com/neovide/neovide/files/13790739/remote-nvide.txt)

**Comment by fredizzimo** [comment]
I think you want to start neovide on the remote, and use `ssh -R` to forward it to your local machine, instead of forwarding the local socket to the remote.

**Comment by krlhBlupine** [comment]
Just tried that to make sure, which fails with a different error:

> TRACE [neovide] Neovide version: 0.12.0
> DEBUG [neovide::settings::window_size] Loaded window settings: Maximized
> ERROR [neovide::error_handling] Neovide just crashed :(
> This is the error that caused the crash. In case you don't know what to do with this, please feel free to report this on https://github.com/neovide/neovide/issues!
> 
> Could not locate or start neovim process
> 
> Caused by:
>     No such file or directory (os error 2)
> 

Additionally, the setup I'm using works perfectly when swapping port forwarding for socket forwarding.

**Comment by krlhBlupine** [comment]
Closing this, figured it out lmao

**Comment by krlhBlupine** [comment]
Additional context here for anyone curious: nvim wasn't launching properly by the time the script tried to connect with it. Adding a `sleep 2` line fixed the issue.
