### ISSUE TITLE
Mouse position functions don't work in latest release

### ISSUE THREAD

**Issue by PyDev19** [neovide/neovide#2222]
**Describe the bug**
I recently downloaded Neovide 0.12.0 on Windows 11 through the MSI installer. I am using AstroNvim, and they have a clickable fold column. The fold column utilizes the `vim.fn.screenstring function`, which retrieves the string under the mouse. I tested this function while moving the mouse around the screen, and it consistently returned blank strings instead of the character under the cursor. This issue does not exist in Neovide 0.11.2 on Windows 11. I don't believe it's a problem with Neovim, as I tested it in the terminal and it worked correctly. Additionally, I tested this on Windows 10 to confirm that it's not an issue exclusive to Windows 11.

**To Reproduce**
1. Download Neovide 0.12.0 on Windows 11 or 10
2. Use `vim.fn.screenstring(row, col)` with the mouse position as argument
3. Check to see if the output in blank or if it returns the character under the mouse

**Expected behavior**
It should return the character under the mouse when using the `screenstring` function

**Desktop (please complete the following information):**
 - OS: Windows 11 & 10
 - Neovide Version 0.12.0
 - Neovim Version 0.6.4

Here is the neovide log while I was clicking the foldcolumns:
[neovide_rCURRENT.log](https://github.com/neovide/neovide/files/13795608/neovide_rCURRENT.log)

**Additional context**
I didn't test any other mouse position functions but I do think that some updates changed the way mouse position functions are handled which causes some errors and returns nothing when called on.

**Comment by fredizzimo** [comment]
I’m not sure why it works in he terminal. We disabled sending of the mouse movement events when it’s disabled (https://neovim.io/doc/user/options.html#'mousemoveevent' ) here https://github.com/neovide/neovide/pull/2111

So enabling that should fix the issue. But I’m not sure what the correct behaviour should be, so if someoene can find a definite specification, it would be good. Otherwise, we need to clarify it with the neovim team. Note, we do send the cursor position with clicks.

**Comment by fredizzimo** [comment]
Note that if we always send the mouse position, we will cause a regression for this bug https://github.com/neovide/neovide/issues/1838. So perhaps, additionally a Neovim fix is needed to get the same behaviour as the terminal mode.

**Comment by tan-wei** [comment]
I can confirm that only with neovide (0.12.1) I will meet this issue.

**Comment by fredizzimo** [comment]
This is very likely the same issue as
* #2300 

The `mousemoveevent` option is not properly parsed from the init files. But it starts working if you manually execute `:set mousemoveevent` after Neovide has loaded.
