### ISSUE TITLE
Missing font causes window to be unresponsive

### ISSUE THREAD

**Issue by nobody-famous** [neovide/neovide#2225]
**Describe the bug**
When Neovide can't find the specified font, the window becomes unresponsive and has to be killed with Task Manager.

**To Reproduce**
1. In init.lua, set the font to vim.o.guifont = "foo:h11"
2. Start Neovide
3. Profit

**Expected behavior**
Something reasonable.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Neovide Version 0.12.0
 - Neovim Version 0.9.5

**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**

TRACE [neovide] Neovide version: 0.12.0
DEBUG [neovide::settings::window_size] Loaded window settings: Maximized
DEBUG [neovide::bridge::command] Starting neovim with: Command { std: "C:\\Program Files\\Neovim\\bin\\nvim.exe" "--embed" "-p", kill_on_drop: false }
INFO [neovide::bridge::setup] Neovide registered to nvim with channel id 1

-- TRIMMING DUE TO BEING TOLD IT WAS TOO LONG TO SUBMIT --

TRACE [neovide::channel_utils] neovim_handler CursorGoto { grid: 5, row: 2, column: 39 }
TRACE [neovide::channel_utils] neovim_handler MouseOff
TRACE [neovide::channel_utils] neovim_handler Flush
TRACE [neovide::editor] Cursor unexpectedly sent to message buffer 5 (39, 2)
TRACE [neovide::editor] Image flushed
TRACE [neovide::editor] send_batch
TRACE [neovide::channel_utils] UICommand Parallel(FocusGained)
TRACE [neovide::renderer::fonts::caching_shaper] Shaping text:  
TRACE [neovide::renderer::fonts::font_loader] Loading font FontKey { bold: false, italic: false, family_name: None, hinting: Full, edging: AntiAlias }
INFO [neovide::window::window_wrapper] Resizing grid based on window size. Grid Size: Dimensions { width: 174, height: 49 }, Window Size PhysicalSize { width: 1920, height: 1129 }
TRACE [neovide::channel_utils] UICommand Parallel(Resize { width: 174, height: 49 })
TRACE [neovide::renderer::fonts::caching_shaper] Shaping text: NVIM v0.9.5
TRACE [neovide::renderer::fonts::caching_shaper] Shaping text: Nvim is open source and freely distributable
TRACE [neovide::renderer::fonts::caching_shaper] Shaping text: https://neovim.io/#chat
TRACE [neovide::renderer::fonts::caching_shaper] Shaping text: type  :help nvim
TRACE [neovide::renderer::fonts::caching_shaper] Shaping text: <Enter>
TRACE [neovide::renderer::fonts::caching_shaper] Shaping text: if you are new!
TRACE [neovide::renderer::fonts::caching_shaper] Shaping text: type  :checkhealth
TRACE [neovide::renderer::fonts::caching_shaper] Shaping text: to optimize Nvim
TRACE [neovide::renderer::fonts::caching_shaper] Shaping text: type  :q
TRACE [neovide::renderer::fonts::caching_shaper] Shaping text: to exit
TRACE [neovide::renderer::fonts::caching_shaper] Shaping text: type  :help
TRACE [neovide::renderer::fonts::caching_shaper] Shaping text: for help
TRACE [neovide::renderer::fonts::caching_shaper] Shaping text: type  :help news
TRACE [neovide::renderer::fonts::caching_shaper] Shaping text: to see changes in v0.9
TRACE [neovide::renderer::fonts::caching_shaper] Shaping text: Help poor children in Uganda!
TRACE [neovide::renderer::fonts::caching_shaper] Shaping text: type  :help iccf
TRACE [neovide::renderer::fonts::caching_shaper] Shaping text: for information
TRACE [neovide::renderer::fonts::caching_shaper] Shaping text: 1
TRACE [neovide::renderer::fonts::caching_shaper] Shaping text: Error: Font can't be updated to: foo:h11
TRACE [neovide::renderer::fonts::caching_shaper] Shaping text: Following fonts couldn't be loaded: foo
TRACE [neovide::renderer::fonts::caching_shaper] Shaping text: Press ENTER or type command to continue
TRACE [neovide::renderer::fonts::font_loader] Loading font FontKey { bold: true, italic: false, family_name: None, hinting: Full, edging: AntiAlias }
TRACE [neovide::renderer::fonts::caching_shaper] Shaping text: [No Name]                                                                         0,0-1          All
TRACE [neovide::channel_utils] UICommand Parallel(Quit)
TRACE [neovide::window::keyboard_manager] Modifiers { state: ModifiersState(ALT), pressed_mods: ModifiersKeys(0x0) }
TRACE [neovide::window::keyboard_manager] KeyEvent {
    physical_key: Code(
        AltLeft,
    ),
    logical_key: Named(
        Alt,
    ),
    text: None,
    location: Left,
    state: Pressed,
    repeat: false,
    platform_specific: KeyEventExtra {
        text_with_all_modifers: None,
        key_without_modifiers: Named(
            Alt,
        ),
    },
}
TRACE [neovide::window::keyboard_manager] Modifiers { state: ModifiersState(0x0), pressed_mods: ModifiersKeys(0x0) }
TRACE [neovide::channel_utils] UICommand Parallel(FocusLost)
TRACE [neovide::channel_utils] UICommand Parallel(FocusGained)
TRACE [neovide::window::keyboard_manager] KeyEvent {
    physical_key: Code(
        Tab,
    ),
    logical_key: Named(
        Tab,
    ),
    text: None,
    location: Standard,
    state: Released,
    repeat: false,
    platform_specific: KeyEventExtra {
        text_with_all_modifers: None,
        key_without_modifiers: Named(
            Tab,
        ),
    },
}
TRACE [neovide::window::keyboard_manager] Modifiers { state: ModifiersState(ALT), pressed_mods: ModifiersKeys(0x0) }
TRACE [neovide::window::keyboard_manager] KeyEvent {
    physical_key: Code(
        AltLeft,
    ),
    logical_key: Named(
        Alt,
    ),
    text: None,
    location: Left,
    state: Pressed,
    repeat: false,
    platform_specific: KeyEventExtra {
        text_with_all_modifers: None,
        key_without_modifiers: Named(
            Alt,
        ),
    },
}
TRACE [neovide::window::keyboard_manager] Modifiers { state: ModifiersState(0x0), pressed_mods: ModifiersKeys(0x0) }
TRACE [neovide::channel_utils] UICommand Parallel(FocusLost)
TRACE [neovide::channel_utils] UICommand Parallel(Quit)
INFO [neovide::running_tracker] Quit neovim processed failed
ERROR [neovide::bridge::ui_commands] ShowError failed

Caused by:
    0: Error decoding response to request 'nvim_echo'
    1: Error while reading from Reader
    2: EOF
ERROR [neovide::bridge::ui_commands] FocusGained failed

Caused by:
    0: Error decoding response to request 'nvim_ui_set_focus'
    1: Error while reading from Reader
    2: EOF
ERROR [neovide::bridge::ui_commands] Resize failed

Caused by:
    0: Error decoding response to request 'nvim_ui_try_resize'
    1: Error while reading from Reader
    2: EOF
ERROR [neovide::bridge::ui_commands] FocusLost failed

Caused by:
    0: Error decoding response to request 'nvim_ui_set_focus'
    1: Error while reading from Reader
    2: EOF
ERROR [neovide::bridge::ui_commands] FocusGained failed

Caused by:
    0: Error decoding response to request 'nvim_ui_set_focus'
    1: Error while reading from Reader
    2: EOF
ERROR [neovide::bridge::ui_commands] FocusLost failed

Caused by:
    0: Error decoding response to request 'nvim_ui_set_focus'
    1: Error while reading from Reader
    2: EOF
DEBUG [neovide::settings::window_size] Saved Window Settings: {"window":"Maximized"}
DEBUG [neovide::settings::window_size] Saved Window Settings: {"window":"Maximized"}

**Comment by fredizzimo** [comment]
Can you send a bit more of the log? You should be able to attach the file to the message for a much longer log file. It appears as if we try to send multiple error messages, and that Neovim does not like it. But I need more lines from the end to determine for sure.

Maybe we can try to work around it by trying to send just one message, It’s not a complete fix for the issue, since multiple messages could happen due to other errors at the startup as well, but I think it’s the best we can do on the Neovide side.

The real fix, needs rather big changes to Neovim, it should run the full event loop, or at least something close to it, to accept at least messages, input, resize requests and focus changes

**Comment by nobody-famous** [comment]
[neovide_rCURRENT.log](https://github.com/neovide/neovide/files/13799355/neovide_rCURRENT.log)

I was able to recreate it on Linux, so it's not Windows only which makes sense given your explanation.

As far as expectations, I'd at least expect it to not block the UI thread and be able to close the window without having to resort to forcefully killing it. Falling back to the default font make sense. I know that's what Emacs does. I'd assume that's what VSCode does, but haven't tried it. I don't know the architecture of Neovide, so not sure how easy that would be to do.

**Comment by fredizzimo** [comment]
Actually, when I look more closely at the logs, in both of them it looks like the quit request at least have gone through, and that Neovim has exited, and also our main loop. So this needs more debugging, to see exactly where it hangs, and what we are waiting for.

**Comment by zperk13** [comment]
I just updated to 0.12.0 and am getting the same issue, What makes things weirder is that it should be finding this font, it was earlier in 0.11.whatever I had

**Comment by Awpteamoose** [comment]
I'm getting something similar but with any error in my config.

**Comment by genzj** [comment]
I'm getting the same issue 

```
DEBUG [neovide::renderer::fonts::caching_shaper] Updating font: JetBrainsMono_Nerd_Font,Monospace:h12
TRACE [neovide::renderer::fonts::font_loader] Loading font FontKey { bold: false, italic: false, family_name: Some("JetBrainsMono Nerd Font"), hinting: Full, edging: AntiAlia
s }
TRACE [neovide::renderer::fonts::font_loader] Loading font FontKey { bold: false, italic: false, family_name: Some("Monospace"), hinting: Full, edging: AntiAlias }
ERROR [neovide::renderer::fonts::caching_shaper] Font can't be updated to: JetBrainsMono_Nerd_Font,Monospace:h12
Following fonts couldn't be loaded: Monospace
TRACE [neovide::channel_utils] UICommand Parallel(ShowError { lines: ["Font can't be updated to: JetBrainsMono_Nerd_Font,Monospace:h12", "Following fonts couldn't be loaded: 
Monospace"] })
DEBUG [neovide::renderer::fonts::caching_shaper] Font updated to: JetBrainsMono_Nerd_Font,Monospace:h12
DEBUG [neovide::renderer::fonts::caching_shaper] Original font_size: 24.00px
TRACE [neovide::renderer::fonts::font_loader] Loading font FontKey { bold: false, italic: false, family_name: Some("JetBrainsMono Nerd Font"), hinting: Full, edging: AntiAlia
s }
...
TRACE [neovide::renderer::fonts::caching_shaper] Shaping text: N
TRACE [neovide::renderer::fonts::font_loader] Loading font FontKey { bold: false, italic: false, family_name: Some("JetBrainsMono Nerd Font"), hinting: Full, edging: AntiAlias }
INFO [neovide::window::window_wrapper] Resizing grid based on window size. Grid Size: Dimensions { width: 329, height: 77 }, Window Size PhysicalSize { width: 4608, height: 2492 }
TRACE [neovide::channel_utils] UICommand Parallel(Resize { width: 329, height: 77 })
TRACE [neovide::renderer::fonts::caching_shaper] Shaping text: Following fonts couldn't be loaded: Monospace
TRACE [neovide::renderer::fonts::font_loader] Loading font FontKey { bold: true, italic: true, family_name: Some("JetBrainsMono Nerd Font"), hinting: Full, edging: AntiAlias }
TRACE [neovide::renderer::fonts::caching_shaper] Shaping text: Press ENTER or type command to continue
```

"Monospace" is a fallback font used in Linux, but it is not available on my MacOS laptop. Its unavailability led to unresponsiveness of the window, although the first font was successfully loaded.

Screenshot:
<img width="800" alt="image" src="https://github.com/neovide/neovide/assets/1018413/92ff1e56-259c-4a5d-8e78-745c60476881">


Full log:
[neovide_rCURRENT.log](https://github.com/neovide/neovide/files/13814468/neovide_rCURRENT.log)

**Comment by fredizzimo** [comment]
This was fixed by
* #2241
