### ISSUE TITLE
Can't open neovide with wslg.exe

### ISSUE THREAD

**Issue by ZreXoc** [neovide/neovide#2227]
**Describe the bug**
I can't open neovide with wslg:
```Firefox
wslg.exe -d Arch --cd "~" -- neovide
```
I ran the command but nothing happened, while other applications installed in wsl (like Firefox) can open normally.

**To Reproduce**
1. install neovide in wsl with pacman
2. run the command

**Expected behavior**
The neovide should open as expected, allowing me to open neovide by windows shortcut.

**Desktop (please complete the following information):**
 - OS: Windows11
 - WSL: 2.0.9.0
 - WSLg: 1.0.59
 - OS of WSL: https://github.com/yuk7/ArchWSL/
 - Neovide Version: 0.12.0
 - Neovim Version: v0.9.4

**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**
no log file is created with `wslg.exe -d Arch --cd "~" -- neovide --log`. Simply nothing happens.

**Comment by fredizzimo** [comment]
We haven’t tried to get wslg to work, because we have native windows support, which will work much smoother and better anyway. 

So, you should use launch it with `neovide.exe —wsl` instead. https://neovide.dev/command-line-reference.html#wsl

**Comment by ZreXoc** [comment]
thx, it solves my problem
