### ISSUE TITLE
Freeze when doing vim.notify with cmdheight set to 0 in init.lua

### ISSUE THREAD

**Issue by yayoyuyu** [neovide/neovide#2231]
**Describe the bug**
Running `vim.notify` after setting `vim.opt.cmdheight=0` in init.lua freezes and does not accept any input

**To Reproduce**
1. Write the following settings in init.lua
```
vim.opt.cmdheight = 0
vim.notify('test')
```
2. Launch neovide

**Expected behavior**
If any key is pressed, the notification should be closed.

**Screenshots**
![shot](https://github.com/neovide/neovide/assets/112897090/06ed81d1-6563-4963-b5b1-766be0c71706)

**Desktop (please complete the following information):**
 - OS: Windows 11 
 - Neovide Version 0.12.0
 - Neovim Version 0.9.2
 
**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**
[neovide_rCURRENT.log](https://github.com/neovide/neovide/files/13807375/neovide_rCURRENT.log)

**Additional context**

**Comment by fredizzimo** [comment]
It looks like Neovim is crashing, and then furthermore running into the same exit issue as https://github.com/neovide/neovide/issues/2225

I think this crash is fixed in Neovim 0.9.4 though, there was some memory corruption when the grid was resized, so try updating to that.

**Comment by yayoyuyu** [comment]
I updated Neovim to the latest version (0.9.5) but I have the same problem.

**Comment by fredizzimo** [comment]
Ok, can you try in terminal nvim first? If that also crashes we just need to open an nvim issue. Otherwise I guess someone need to attach a debugger and see exactly what crashes.

I can't check myself, since I don't have access to a development environment until the middle of January.

**Comment by yayoyuyu** [comment]
I tried it on terminal and it works as expected there.
It worked as expected with neovim-qt as well, so perhaps it is an inherent problem with neovide.

**Comment by fredizzimo** [comment]
After taking a second look, I think I read the log wrong. But I don't see any enter key presses there, could you provide another log where you also try to press enter?

**Comment by yayoyuyu** [comment]
Sorry for the many inadequacies...
Here is the log of my attempted keystrokes.
[neovide_rCURRENT.log](https://github.com/neovide/neovide/files/13811069/neovide_rCURRENT.log)

**Comment by fredizzimo** [comment]
Thanks

I think this might indeed be the same hang as 
* #2225

And from the logs caused by
* https://github.com/neovide/neovide/pull/2161 

I don't think #2161 is the only trigger, but it makes it much more likely to occur, neovim does not seem to process `echo has('nvim-0.10')` when the error message is showing. That can probably be fixed by using an api call instead. And because that is blocked, all the following commands are blocked as well.

**Comment by fredizzimo** [comment]
Fixed by https://github.com/neovide/neovide/pull/2241

**Comment by Curve** [comment]
I'm having this exact issue again on Neovide 0.15.1 - Logs: 

[neovide_rCURRENT.log](https://github.com/user-attachments/files/22265376/neovide_rCURRENT.log)

Everything works as expected in the terminal.

**Comment by fredizzimo** [comment]
It looks like Neovim just stops sending replies.

This is a technically a different issue than the original, which has been closed, so can you open a new issue and include the version of Neovim you are using? Does it also happen with `neovide -- --clean` and setting just the `cmdheight`?

**Comment by Curve** [comment]
> It looks like Neovim just stops sending replies.
> 
> This is a technically a different issue than the original, which has been closed, so can you open a new issue and include the version of Neovim you are using? Does it also happen with `neovide -- --clean` and setting just the `cmdheight`?

Will open a new issue, and yes, it happens just with setting cmdheight
