### ISSUE TITLE
Can't keep maximised on Ubuntu 22.04

### ISSUE THREAD

**Issue by yangrq1018** [neovide/neovide#2232]
**Describe the bug**
Open neovide, click maximise button. The window is now maximised.
Switch to another app (like browser), then switch back, now neovide is not high enough to cover the entire screen.
See screen shot
![image](https://github.com/neovide/neovide/assets/25074163/464712ae-f673-412d-8a8c-7e6cb1c66c3d)
Notice the topright icon that the window still thinks it's maximised.

**To Reproduce**
nvim version v0.10.0-dev-2000+g6fa0f303d
neovide version 0.12.0, installed as appimage
Ubuntu 22.04.03, start neovide appimage from terminal
All other neovide functionality is fine, except for this maximised behavior. Other apps on ubuntu maximise as expected as well.

**Expected behavior**
The neovide window should remain maximised (copy entire screen) after switching.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04.3
 - Neovide Version 0.12.0
 - Neovim Version v0.10.0-dev-2000+g6fa0f303d

**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**
[neovide_rCURRENT.log](https://github.com/neovide/neovide/files/13808415/neovide_rCURRENT.log)

**Additional context**

**Comment by fredizzimo** [comment]
Are you using wayland or x11? 

I don't think this is a direct Neovide bug, but it could be a winit or mutter one. The window is resized to exactly 1000 pixels in height after the focus is lost, but there are no other resizes after that.

On the winit side there are a few fixes that might fix this bug, most probably this https://github.com/rust-windowing/winit/pull/3273. But nothing matches exactly. 

If you can build from source, you could try changing this line to 0.29.8
https://github.com/neovide/neovide/blob/af9869bd6d8d3434b187e29f85032ee74e40b536/Cargo.toml#L70

**Comment by yangrq1018** [comment]
I am using wayland, default for ubuntu 22.04. Thanks I will try to build from source.

**Comment by yangrq1018** [comment]
I tried updating to winit 0.29.8 and build from source. Problem remained.
But I can confirm that this is a wayland problem. Checked rust-windowing/winit#3263, set `WAYLAND_DISPLAY=`
then issue is gone.

**Comment by fredizzimo** [comment]
I think we will keep this open, until it's fixed, or at least until we know the issue.

Could you run `WAYLAND_DEBUG=1 neovide --nofork > wayland.txt 2>&1` and repeat the bug with as few steps as possible. The generated wayland.txt file will be huge, but it should compress very well, so I think you will be able to attach it here after it's compressed.

**Comment by yangrq1018** [comment]
[wayland.txt](https://github.com/neovide/neovide/files/13820119/wayland.txt)
Not very huge, actually.

**Comment by fredizzimo** [comment]
I think we will need to ask for help from the winit team, but before that would it be possible to check if this fixes it? I don't think it will, but it's worth a try.
* https://github.com/neovide/neovide/pull/2205

There are also binaries available here, if you don't know how to build a PR from source 
https://github.com/fredizzimo/neovide/actions/runs/7322966077

**Comment by yangrq1018** [comment]
I think it works! I checkout the PR branch and build a debug target. No resizing for now. I could use this version and look out for it for some days.

PS: look like this PR has also fixed a strange issue - cursor got hidden by neovide window. This sometimes happens on the initial start of neovide.

Nice job by the way!

**Comment by fredizzimo** [comment]
Great, let's hope that it indeed fixes the issue completely.

**Comment by mati865** [comment]
This is the issue I have reported in https://github.com/neovide/neovide/pull/2188#issuecomment-1863556885 and indeed #2205 fixed it for me as well.

**Comment by fredizzimo** [comment]
Fixed by #2205
