### ISSUE TITLE
Not All Available Font Styles Respected in 0.12.1 TOML Configuration

### ISSUE THREAD

**Issue by bnwa** [neovide/neovide#2242]
**Describe the bug**
`config.toml` font configuration only respects `Regular` and `Bold` styles out of the six styles of `FiraCode Nerd Font`

**To Reproduce**
1. Ensure no Lua configuration of `vim.g.guifont`
2. Configuration normal font family in `config.toml` for family `FiraCode Nerd Font` with any of the available styles (Light, Regular, Retina, Medium, Semibold, Bold)

**Expected behavior**
All six styles should be respected and Neovide should auto update font rendering in a live window to match

**Screenshots**
<img width="1919" alt="Screenshot 2024-01-06 at 1 28 47 PM" src="https://github.com/neovide/neovide/assets/74591246/04feab1d-3f5d-4d4b-93b8-ccd93ad9db9d">
<img width="1919" alt="Screenshot 2024-01-06 at 1 29 32 PM" src="https://github.com/neovide/neovide/assets/74591246/0c291c45-be40-4124-ab58-11d790abdee1">
<img width="1919" alt="Screenshot 2024-01-06 at 1 30 48 PM" src="https://github.com/neovide/neovide/assets/74591246/ad6827ce-7d23-4d3e-a920-1d8b4570b02c">
<img width="1919" alt="Screenshot 2024-01-06 at 1 31 06 PM" src="https://github.com/neovide/neovide/assets/74591246/7832757d-5144-4b08-b426-2e2a7f1de2af">
<img width="1919" alt="Screenshot 2024-01-06 at 1 31 25 PM" src="https://github.com/neovide/neovide/assets/74591246/2d1ba519-0c77-4bf9-b8f5-3ec2a44057b1">
<img width="1919" alt="Screenshot 2024-01-06 at 1 31 40 PM" src="https://github.com/neovide/neovide/assets/74591246/1f7b0543-e2c5-445e-be91-edcc2532c07f">

**Desktop**
 - OS: macOS 14.2.1
 - Neovide Version 0.12.1
 - Neovim Version NVIM v0.9.5,LuaJIT 2.1.1703358377

[neovide_rCURRENT.log](https://github.com/neovide/neovide/files/13851078/neovide_rCURRENT.log)

**Comment by fredizzimo** [comment]
This should take care of that, but note that retina is a separate font name, so you need to specify that as the name

* https://github.com/neovide/neovide/pull/2246

**Comment by bnwa** [comment]
> This should take care of that, but note that retina is a separate font name, so you need to specify that as the name
> 
> * [feat: support all font weights and slants #2246](https://github.com/neovide/neovide/pull/2246)

Thanks for getting back. Unsure how to resolve specifyin the Retina style outside of the `style` property as I get the following error:
<img width="1392" alt="image" src="https://github.com/neovide/neovide/assets/74591246/74a16df0-357f-4664-874f-602df9a16d03">

Am I missing something?

**Comment by fredizzimo** [comment]
Ah, I never used it myself, but I saw it as a separate font earlier, but it should be a weight, nerd fonts must have fixed it.

It's actually a custom weight https://github.com/tonsky/FiraCode/issues/872#issuecomment-544480764, slightly thicker than normal. You can use `W450` to use it https://github.com/tonsky/FiraCode/wiki/VS-Code-Instructions#font-weights

**Comment by bnwa** [comment]
> Ah, I never used it myself, but I saw it as a separate font earlier, but it should be a weight, nerd fonts must have fixed it.
> 
> It's actually a custom weight [tonsky/FiraCode#872 (comment)](https://github.com/tonsky/FiraCode/issues/872#issuecomment-544480764), slightly thicker than normal. You can use `W450` to use it https://github.com/tonsky/FiraCode/wiki/VS-Code-Instructions#font-weights

Ah, gotcha. Thanks!
