### ISSUE TITLE
The font width can't be configured

### ISSUE THREAD

**Issue by obmutescences** [neovide/neovide#2251]
**Describe the bug**
width setting in config not working

**Desktop (please complete the following information):**
 - OS: ubuntu23.10
 - Neovide Version main
 - Neovim Version last

[font]
normal = { "family" = "Monaspace Radon", "style" = "W400" }
size = 13
width = 5.0
hinting = "full"
edging = "antialias"

**Comment by fredizzimo** [comment]
It's a a bit strange that it's not working, but maybe you did not pull the latest, since the support was merged just a few hours ago.

**Comment by obmutescences** [comment]
> It's a a bit strange that it's not working, but maybe you did not pull the latest, since the support was merged just a few hours ago.

hi.
this is the git log
commit bbb26e84ac0d76a44ec71c53f7e104bc37054b9a (HEAD -> main, origin/main, origin/HEAD)
Author: Hawtian Wang <hawtian.wang@twistoy.cn>
Date:   Tue Jan 9 07:42:50 2024 +0800

    feat: support all font weights and slants (#2246)
    
    * support all font weights and slants
    
    * add support for variable font weights
    
    * try to add some docs
    
    * fix md lint


i change this func to + 1.1 , then build its working;
```rust
pub fn font_base_dimensions(&mut self) -> (u64, u64) {
        let (metrics, glyph_advance) = self.info();
        let bare_font_height = (metrics.ascent + metrics.descent + metrics.leading).ceil();
        let font_height = bare_font_height as i64 + self.linespace;
        let font_width = (glyph_advance + self.options.width + 0.5 + 1.1).floor() as u64;

        (
            font_width,
            font_height as u64, // assuming that linespace is checked on receive for
                                // validity
        )
    }
```

maybe self.options.width not read from config width?

**Comment by fredizzimo** [comment]
Ah, sorry, I did not read the issue correctly. The `W` setting stands for weight, or how bold it is, not the width. Changing the width is not currently supported, but it should be easy to add. It's always set to normal here https://github.com/neovide/neovide/blob/bbb26e84ac0d76a44ec71c53f7e104bc37054b9a/src/renderer/fonts/font_options.rs#L382

**Comment by obmutescences** [comment]
> Ah, sorry, I did not read the issue correctly. The `W` setting stands for weight, or how bold it is, not the width. Changing the width is not currently supported, but it should be easy to add. It's always set to normal here
> 
> https://github.com/neovide/neovide/blob/bbb26e84ac0d76a44ec71c53f7e104bc37054b9a/src/renderer/fonts/font_options.rs#L382
> 
> These will be the supported values https://rust-skia.github.io/doc/skia_safe/font_style/struct.Width.html

i see. thanks.

**Comment by fredizzimo** [comment]
I'm re-opening and changing the title, because we should add support for this

This is an old issue asking for the same, but since we are adding things to the config file I will close that one

* https://github.com/neovide/neovide/issues/1130

**Comment by MultisampledNight** [comment]
The weird thing is that we do support the width already, but only in `guifont`:

```vim
set guifont=IBM_Plex_Mono:h12:w30
```

![Very spaced character rendering](https://github.com/neovide/neovide/assets/80128916/20a69eb2-deb7-43d7-8eb7-89e281ee09d5)

**Comment by fredizzimo** [comment]
So maybe we also need to auppoer numerical width in addtion to the skia ones, for backward compatibility and full customization?

The skia font width is slightly different though, since it actually scales the font, and not just the width of the box.

**Comment by gmr458** [comment]
I was reading the code and by just changing this line I got `width` working, really simple and easy.
```
diff --git a/src/settings/font.rs b/src/settings/font.rs
index fef49f4..31593c0 100644
--- a/src/settings/font.rs
+++ b/src/settings/font.rs
@@ -119,7 +119,7 @@ impl From<FontSettings> for FontOptions {
                 })
                 .unwrap_or_default(),
             size: value.size,
-            width: 0.0,
+            width: value.width.unwrap_or_default(),
             allow_float_size: value.allow_float_size.unwrap_or_default(),
             hinting: value
                 .hinting
```

**Comment by subnut** [comment]
I don't get it.  

Why is `width` mentioned here in https://neovide.dev/config-file.html if it's not even configurable yet?

**Comment by Kethku** [comment]
Fixed via @gmr458's PR. I think this was just a simple mistake in the original implementation. Should work now
