### ISSUE TITLE
Neovide Nix install fails to create a window on Linux Mint

### ISSUE THREAD

**Issue by norandom** [neovide/neovide#2255]
**Describe the bug**
In a fresh Linux mint install, Neovide fails to create a window.
A log file with errors is being written.

**To Reproduce**
1. nix-env -e neovide
2. nix-env -e neovim
3. neovide

**Expected behavior**
Start of the neovide window / application.

**Screenshots**
```
2024-01-09 19:30:01 - Neovide panicked with the message 'Failed to create Window: Error { raw_code: None, raw_os_message: None, kind: BadConfig }'. (File: src/renderer/opengl.rs; Line: 92, Column: 10)
   0: neovide::main::{{closure}}
   1: std::panicking::rust_panic_with_hook
   2: std::panicking::begin_panic_handler::{{closure}}
   3: std::sys_common::backtrace::__rust_end_short_backtrace
   4: rust_begin_unwind
   5: core::panicking::panic_fmt
   6: core::result::unwrap_failed
   7: neovide::renderer::opengl::build_window
   8: neovide::window::error_window::show_error_window
   9: neovide::main
  10: std::sys_common::backtrace::__rust_begin_short_backtrace
  11: main
  12: __libc_start_call_main
  13: __libc_start_main_impl
  14: _start
```

**Desktop (please complete the following information):**
 - OS: Linux Mint 21.2 (Apt / Ubuntu based)
 - Neovide 0.11.2
 - Neovim 0.9.5

**Additional context**
Downloading the release binary and executing it works fine.
It's not a gfx driver issue, therefore.
Maybe something missing in the package spec I can install?

**Comment by fredizzimo** [comment]
@MultisampledNight, do hou have any idea what could cause the nix package to behave differently?

**Comment by MultisampledNight** [comment]
I'd guess mis-setup OpenGL, @norandom could you try running with [nixGL](https://github.com/nix-community/nixGL)?

(sidenote: nix-env can sometimes behave in very unexpected ways. maybe you want to take a look at home-manager or nix-shell.)

**Comment by norandom** [comment]
I have tried that, and it works.

```
marius@mleng:~$ which neovide
/home/marius/.nix-profile/bin/neovide
marius@mleng:~$ which nixGL
/home/marius/.nix-profile/bin/nixGL
marius@mleng:~$ nixGL neovide
```

Window comes up.

**Comment by fredizzimo** [comment]
Is this something that can be fixed in the nix package, or do we need some faq entry for this?

**Comment by MultisampledNight** [comment]
We'll need an FAQ entry. OpenGL is notoriously difficult with Nix, and a lot of other applications need it, too.

**Comment by MultisampledNight** [comment]
I'll write an FAQ entry today.

**Comment by fredizzimo** [comment]
The [installation instructions](https://neovide.dev/installation.html#nix) were updated by this https://github.com/neovide/neovide/commit/96c81fc30166f6f030e157cca53063834b57e3c6
