### ISSUE TITLE
"Natural scrolling" on a trackpad is inverted on the x axis

### ISSUE THREAD

**Issue by raggi** [neovide/neovide#2258]
**Describe the bug**

Noticed on macOS, but likely also applies to other platforms with trackpad configurations that utilize "natural scrolling". Scrolling to the left should "move content left", but instead it moves content right. This is inverted from the proper direction for "natural scrolling".

**To Reproduce**
1. Scroll right on a natural scrolling trackpad.
2. Observe content moves left.

**Expected behavior**
Scrolling left should move content left. Scrolling right should move content right.

**Desktop (please complete the following information):**
 - OS: macOS 14.2.1
 - Neovide Version 0.11.2
 - Neovim Version v0.9.4

**Comment by fredizzimo** [comment]
@MultisampledNight, it seems like you reversed the scroll direction here in this commit https://github.com/neovide/neovide/pull/1148/commits/6e8f0d1950eb7294607f2594825a230d89eeef2f of this PR
* https://github.com/neovide/neovide/pull/1148

Is this bug?
* A difference between platforms
* Difference between touchpad and touch screen
* A changed winit behavior
* A subjective difference

I also find it suprising that this is the first bug report, when the code has been the same for two years.

**Comment by MultisampledNight** [comment]
I can reproduce this

- on a touchscreen (where the horizontal direction is inverted from what one would expect),
- but not on a touchpad with natural scroll enabled on Sway (Wayland, where the horizontal scroll **does** move the content as well)

Maybe this is a difference between platforms indeed. I'll setup some debugging in a few weeks since I know someone with a mac machine, a bit busy atm.

**Comment by MultisampledNight** [comment]
So just that I get this right:

- @raggi on macOS 14.2.1: Scroll → right, content → left
- @diocletiann on macOS: Scroll → right, content → right
- Me on Wayland:
  - Touchpad: Scroll → right, content → right
  - Touchscreen: Scroll → right, content → left

@diocletiann For the sake of pedanticness: What macOS version are you on?

**Comment by diocletiann** [comment]
@MultisampledNight I'm on 14.2.1 and your understanding is correct, in my case. However horizontal movement is by cell, not sure it that is intended behavior as I usually have it disabled and if it's changing the input direction.

**Comment by raggi** [comment]
Some relevant history:
https://github.com/rust-windowing/winit/issues/1695
https://github.com/rust-windowing/winit/issues/2099
https://github.com/rust-windowing/winit/pull/2105
Of particular interest: https://github.com/rust-windowing/winit/pull/2105#issuecomment-1015695124
This example forms a meaningful test program: https://github.com/rust-windowing/winit/blob/master/examples/mouse_wheel.rs

**Comment by fredizzimo** [comment]
Also relevant, we used to invert the scroll direction, until winit also did it, and we had to revert our change

* https://github.com/neovide/neovide/issues/582

**Comment by cbaroni-otto** [comment]
WTF! Mac is imposing changes too often, too much....In 14.2.1 can't find the option natural scrolling (enable/disable)....
