### ISSUE TITLE
GUI scale changes when moved between two screens with identical resolution

### ISSUE THREAD

**Issue by kamoshi** [neovide/neovide#2263]
**Describe the bug**
I have a laptop screen and an external Iiyama screen plugged in via a HDMI port. Both have the same resolution - 1980 x 1080.

When I move Neovide to my laptop's screen, it looks like this:
![image](https://github.com/neovide/neovide/assets/18511281/9b64fa09-e4fb-4ce2-a42a-a83e868e37cd)

Meanwhile, when the window is located within the boundary of the external screen the scaling becomes like this:
![image](https://github.com/neovide/neovide/assets/18511281/0242f897-99f2-4974-9794-07856e284428)

I've included terminal window for scale.

**To Reproduce**
1. Use Neovide
2. Move the Neovide window between two screens

**Expected behavior**
The scaling should be the roughly same.

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Neovide Version 0.12.1
 - Neovim Version 0.9.5

**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**
[neovide_rCURRENT.log](https://github.com/neovide/neovide/files/13908688/neovide_rCURRENT.log)

**Additional context**
This started happening since Neovide 0.12

**Comment by fredizzimo** [comment]
I think this will be fixed by 
* https://github.com/neovide/neovide/pull/2218

But, I'm not sure if the PR works correctly yet.

**Comment by MultisampledNight** [comment]
@kamoshi Since you're on KDE Plasma, are you on X11 or Wayland? What are each monitor's DPI?

**Comment by kamoshi** [comment]
I'm on X11

```
$ xrandr | grep -w connected
eDP-1 connected primary 1920x1080+0+0 (normal left inverted right x axis y axis) 344mm x 193mm
HDMI-2 connected 1920x1080+1920+0 (normal left inverted right x axis y axis) 496mm x 292mm
```

**Comment by MultisampledNight** [comment]
That sounds like it could be within bounds of the DPI scaling then. Are they visually speaking (not in terms of pixels) appearing the same size when viewing both screens? Could you try launching Neovide with the environment variable `WINIT_X11_SCALE_FACTOR` set to `1.0`?

**Comment by kamoshi** [comment]
> Are they visually speaking (not in terms of pixels) appearing the same size when viewing both screens?

They look roughly the same

![IMG_20240115_211342](https://github.com/neovide/neovide/assets/18511281/2b9d6c46-945b-4819-9a0f-dfed950a6d2d)

> Could you try launching Neovide with the environment variable `WINIT_X11_SCALE_FACTOR` set to `1.0`?

With `WINIT_X11_SCALE_FACTOR` set to `1.0` this stops happening, and they resize along with the rest of the DE

![image](https://github.com/neovide/neovide/assets/18511281/46b723da-1d26-471f-8c93-381a7b823b0f)

**Comment by MultisampledNight** [comment]
Then tbh I believe that behavior is to be expected. The points `guifont` is configured in try to correspond to physical sizes, not digital ones.

**Comment by kamoshi** [comment]
Maybe, but Neovide is the only program on my PC that adjusts itself against the scaling of DE, so it looks strangely out of place. It just subjectively *feels* broken

**Comment by fredizzimo** [comment]
Winit, and as a result Neovide and also Alacritty for example, uses a quite controlversial way of setting the scale factor on X11. There's not much Neovide can do about that.

* https://github.com/rust-windowing/winit/issues/2231

On other platforms, and also Wayland it works as expected and also supports per display configuration.

We also have a FAQ entry about it https://neovide.dev/faq.html#font-size-is-weird-with-high-dpi-display-on-x11, although, it could be expanded a bit more there directly.

**Comment by fredizzimo** [comment]
Closing, this as that's just the way winit works on X11, and it's documented. So, you can either use the documented workaround or switch to Wayland.
