### ISSUE TITLE
macos full screen weird button bar location

### ISSUE THREAD

**Issue by xzbdmw** [neovide/neovide#2274]
**Describe the bug**
the window size will influence the button status bar and make it a bit higher

**To Reproduce**
see screenshot

**Expected behavior**
status bar stay on button

**Screenshots**

https://github.com/neovide/neovide/assets/97848247/0a1c6e22-06b0-4055-9594-026efa4c46d7

**Desktop (please complete the following information):**
 - macOS 14.1
 - Neovide Version 0.12.1
 - Neovim Version  v0.9.5

**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**

**Additional context**

**Comment by crupest** [comment]
Is it possibly because there is no enough space to contain the height of a full line, so there is an empty padding?

**Comment by xzbdmw** [comment]
yes, I see.
