### ISSUE TITLE
Transparent frame looks weird

### ISSUE THREAD

**Issue by polachok** [neovide/neovide#2285]
**Is your feature request related to a problem? Please describe.**
Currently, if I use `--frame transparent` it looks like this:

<img width="909" alt="Screenshot 2024-01-18 at 20 24 11" src="https://github.com/neovide/neovide/assets/94035/3b34cc45-f452-43a9-8ec6-d7a92c12507b">

Which is kinda weird and not really usable.

**Describe the solution you'd like**
I think it would make sense to add padding to the top by default, like this:
<img width="1077" alt="Screenshot 2024-01-18 at 20 25 41" src="https://github.com/neovide/neovide/assets/94035/acd524d4-7d4f-4817-abf1-aad837c77f00">
and also make it possible to enable window title like I did here by modifying `src/window/mod.rs:219`

**Describe alternatives you've considered**
I can set padding myself in config, but no way I know to add title back.

**Comment by fredizzimo** [comment]
Check out this PR, which does exactly that and a few other things.

* https://github.com/neovide/neovide/pull/2168
