### ISSUE TITLE
When there is a message with prompt “Press ENTER or type command to continue”, neovide cannot be closed normally .

### ISSUE THREAD

**Issue by nullptr-yxw** [neovide/neovide#2286]
When there is a message with prompt “Press ENTER or type command to continue”, the neovide cannot be closed normally (for example, by clicking the "x"). And after I click the "x", as soon as I press enter to continue, the neovide will be closed.

https://github.com/neovide/neovide/assets/96286337/6a30d2ea-5911-49ea-99a5-72b6a68017fa

As a result, when there is much error of neovim (for example, the large number of errors produced by treesitter-nvim), I can only close the neovim by task manager or `kill` command.

**Desktop:**
 - OS: `windows11`
 - Neovide Version: `0.12.1`(the latest release), and the `0.12.0` has the same problem as well.
 - Neovim Version: `NVIM v0.10.0-dev-2110+g2fce95ec4`, and other versions has the same problem as well.

**Comment by fredizzimo** [comment]
I'm going to close this as duplicates of 
* https://github.com/neovide/neovide/issues/2233
* https://github.com/neovide/neovide/issues/2271
* https://github.com/neovide/neovide/issues/2277
* https://github.com/neovide/neovide/issues/2261
* https://github.com/neovide/neovide/issues/2245

It's fixed on main if you build from source with 
* https://github.com/neovide/neovide/pull/2241
