### ISSUE TITLE
Devicons and Nerd Font disappearing or overlap??

### ISSUE THREAD

**Issue by LeFFaQ** [neovide/neovide#2289]
I use Neovide for the WSL. As usual I wrote the line `vim.o.guifont="Fira Code Nerd Font"` in wsl `~/.config/nvim/init.lua`. Font installed  globally for all windows users. I go to the folder of the test project and encounter a problem: when I open the file and go back to tree, the icons in `nvim-tree` disappear and appear only when I move the cursor over the lines.

[Video to get a better understanding of the problem](https://drive.google.com/file/d/1yPNwyi7X2-S7_eoYrok-kdUKc4WZaj9l/view?usp=sharing)

**To Reproduce**
1. Install Neovide from winget
2. Add shortcut to desktop with `--wsl` parameter 
3. Install Nvim on WSL machine ( `sudo pacman -S neovim`)
4. Install NvChad (`git clone https://github.com/NvChad/NvChad ~/.config/nvim --depth 1 && nvim`)
5. Set  `vim.o.guifont="Fira Code Nerd Font"` (also tried with `JetbrainsMono Nerd Font`)
5. Open file in a folder from `nvim-tree` (with devicons?)
6. Go focus to `nvim-tree` again
7. Nerd Icons gone

**Expected behavior**
No nerd font issues. This config works fine in pure linux machine. Also this works as expected when using same nerd font in Windows Terminal WSL session of Nvim

**Desktop (please complete the following information):**
 - OS: Windows 11 Pro 23H2 22631.3007
 - Neovide Version: 0.10.4 (Windows)
  - Neovim Version: v0.9.5 Build type: Release LuaJIT 2.1.1702233742 (WSL)

**Comment by LeFFaQ** [comment]
I realized that the problem is with the neovide version in the winget repository. I installed the latest release and everything works as it should

**Comment by fredizzimo** [comment]
Hm the winget package seems to be very outdated 

https://github.com/microsoft/winget-pkgs/tree/master/manifests/n/Neovide, on version 0.10.4
