### ISSUE TITLE
set guifont=* Errors on macOS on latest neovide release 0.12.1

### ISSUE THREAD

**Issue by craigmac** [neovide/neovide#2290]
**Describe the bug**
Trying to change font via `:set guifont=*` produces error, from the log:

```
ERROR [neovide::renderer::fonts::caching_shaper] Font can't be updated to: FontOptions {
    normal: [
        FontDescription {
            family: "*",
            style: None,
        },
    ],
    italic: None,
    bold: None,
    bold_italic: None,
    features: {},
    size: 14.0,
    width: 0.0,
    allow_float_size: false,
    hinting: Full,
    edging: AntiAlias,
}
Following fonts couldn't be loaded: FontKey { font_desc: Some(FontDescription { family: "*", style: Some("Bold Italic") }), hinting: Full, edging: AntiAlias },
FontKey { font_desc: Some(FontDescription { family: "*", style: Some("Bold") }), hinting: Full, edging: AntiAlias },
FontKey { font_desc: Some(FontDescription { family: "*", style: Some("Italic") }), hinting: Full, edging: AntiAlias },
FontKey { font_desc: Some(FontDescription { family: "*", style: None }), hinting: Full, edging: AntiAlias }
```

**To Reproduce**
1. `:set guifont=*` on 0.12.1 release for macOS

**Expected behavior**
font chooser modal to popup like <0.12.1

**Screenshots**
NA

**Desktop (please complete the following information):**
- macOS 12.7.2
- Neovide 0.12.1
 - Neovim NVIM v0.10.0-dev-2133+g5a8fe0769 Release build (from source this morning)

**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**

[neovide_rCURRENT.log](https://github.com/neovide/neovide/files/13990922/neovide_rCURRENT.log)

**Comment by craigmac** [comment]
Just tried `neovide -- --clean` and Error still occurs.

**Comment by fredizzimo** [comment]
It looks like it displays both the error and the list at the same time, and possibly closing the list when you press enter.

The fix should be easy, but I don't have access to a computer until next week. This should be an if else
https://github.com/neovide/neovide/blob/7d0c42b8bec78f99156037b1acf2454426145b01/src/editor/mod.rs#L505-L515

The `FontChanged` and `redraw_screen` should be in the else clause.

**Comment by al3xandru** [comment]
I have just noticed that `set guifont=Font:size,Font:size` is not working either. I'm fairly sure this worked in the previous version:

`set gfn=Iosevka_Fixed:h15,PragmataPro_Mono:h15,mononoki:h15`

**Comment by fredizzimo** [comment]
@al3xandru, it might have seemed to work, because the errors were silently ignored, but it did not in practice, only the last `h15` was used, just like documented in the specification https://neovide.dev/configuration.html#font

**Comment by fredizzimo** [comment]
Although, now when I read this https://neovide.dev/configuration.html#font, I think our specification is wrong, the neovim documentatinsays this:

> This is a list of fonts which will be used for the GUI version of Vim

> takes these options in the font name

So, I think the options should apply to just one of the fonts listed, perhaps with inferred values for the other options.

Adapting that format could allow us to support stuff that the new toml based font config with `guifont`, but we will have to decide what to do about backward compatibility.

**Comment by al3xandru** [comment]
I always had it with option for each font.  I went looking into MacVim documentation and I can't say I have found the part being clear that one way or the other is the correct one 🙃
