### ISSUE TITLE
UI: Winbar moves along when scrolling

### ISSUE THREAD

**Issue by nyyakko** [neovide/neovide#2291]
**Describe the bug**
winbar moving along when scrolling the buffer contents.

**To Reproduce**
This probably affects any setup which uses the winbar, but in my case i installed the [barbecue](https://github.com/utilyre/barbecue.nvim) plugin to get the so called ``breadcumbs`` to appear as a winbar component.

**Expected behavior**
expected the winbar to stay in place, not moving along when scrolling.

**Screenshots**

https://github.com/neovide/neovide/assets/36525792/0091f96b-b7c8-4bf4-b606-0e34ef71ea98

**Desktop (please complete the following information):**
 - OS: Windows 10 22H2 19045.3930
 - Neovide Version 0.12.1
 - Neovim Version 0.9.5

**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**
https://gist.github.com/nyyakko/22e39956c2419e433351a0f6b9ebffd2

**Additional context**

nvim configuration: https://github.com/nyyakko/dotfiles/tree/main/nvim

**Comment by nullptr-yxw** [comment]
I have similar problem as well. the option [vim.g.neovide_unlink_border_highlights](https://neovide.dev/configuration.html#fix-border-and-winbar-scrolling-glitches) can only work well with the native `winbar` which is a new feature in `nvim 0.10`. But barbecue plugin doesn't use this feature to display winbar.

For breadcrumbs, I perfer [lspsaga.nvim](https://nvimdev.github.io/lspsaga/breadcrumbs/), but it doesn't use the feature when lsp is loaded as well(but it will use the feature before lsp is loaded and has the correct performance). I have ask the author of lspsaga.nvim about this problem but he is busy with the development of neovim itself, and only have little time to fix the bugs with his plugins.

So I can only set `neovide_scroll_animation_length = 0` to disable the smooth scroll completely.

**Comment by fredizzimo** [comment]
Unfortunately, there's not much we can do without a Neovim fix:
* https://github.com/neovim/neovim/issues/23610

But you might be able to work around the problem by modifying the highlight groups used for the barbeque. As long as there's at least some elements with the [WinbBar](https://neovim.io/doc/user/syntax.html#hl-WinBar) highlight group, it should stay in place. I think you can add a custom section, with space as a text and `WinBar` as the highlight group, but I don't use barbecue myself and I have not tested if it works. https://github.com/utilyre/barbecue.nvim/blob/d38a2a023dfb1073dd0e8fee0c9be08855d3688f/doc/barbecue.txt#L315-L317

**Comment by wSedlacek** [comment]
This worked for me without the complexity of the autocmd
```
    require("barbecue").setup {
      -- https://github.com/neovide/neovide/pull/2165
      lead_custom_section = function()
        return { { " ", "WinBar" } }
      end,
    }
```
