### ISSUE TITLE
Incorrect space size when non-standard space the first character on the line

### ISSUE THREAD

**Issue by ZyX-II** [neovide/neovide#2292]
**Describe the bug**
If U+2009 THIN SPACE happens to be the first character on the line then once you type some non-whitespace character after that U+2009 will be displayed occupying three horizontal cells in place of one. Additionally cursor will be placed “correctly” in that it is placed as if U+2009 did occupy only one cell.

I have also managed to reproduce the issue by using U+00A0 NO-BREAK SPACE which occupies two cells in place of three which probably means that amount of cells occupied is equal to amount of bytes. I have not tried any other unicode whitespace characters though.

**To Reproduce**
1. Run `neovide --log -- -u NONE -i NONE -N` (note: `--no-multigrid` does not help).
2. ~~Type `t` until it fills the entire line.~~ Scratch that, I see this incorrect behaviour without line wrapping.
3. Type `<Char-0x2009>` (`<C-k>1T` should also work).
4. Type some more `t`s.

**Expected behavior**
Line starting with U+2009 or U+00A0 should look like a regular line which starts with a space, and that space should occupy a single cell.

**Screenshots**

![There actually is a single space and cursor is logically after the last `t`](https://github.com/neovide/neovide/assets/32704105/13f3b492-4e0e-41b6-81b0-f5681f4c9e3b)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro 21H2 19044.1526.
 - Neovide Version 0.12.1, from [scoop](https://github.com/ScoopInstaller/Extras/blob/ed7ff48db8232f7f0eaabae08ae4a61ff8a7ee20/bucket/neovide.json)
 - Neovim Version 0.9.5, from [chocolatey](https://community.chocolatey.org/packages/neovim/0.9.5)

**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**
[neovide_rCURRENT.log](https://github.com/neovide/neovide/files/13993027/neovide_rCURRENT.log)

**Additional context**
`nvim` and `nvim-qt` handle this situation just fine.

**Comment by ZyX-II** [comment]
Note that I have `showbreak=>>>>` and `number` where I first saw the issue and U+2009 was first character after the wrap. Incorrect behaviour was seen despite `showbreak` and `number` shifting U+2009 away from screen edge.

**Comment by ZyX-II** [comment]
A bit better log, when using the following command:

    cargo +stable-x86_64-pc-windows-msvc run -- --grid '1x1' --log -- -u NONE -i NONE -N --cmd 'set fillchars=eob:\  cmdheight=0 nolist noshowcmd laststatus=0' --cmd "call setline(1, nr2char(0x2009).'tt'.nr2char(0x2009).'uu')" --cmd 'autocmd FocusGained * redraw! | sleep 1 | cq'

: [neovide_rCURRENT.log](https://github.com/neovide/neovide/files/13993957/neovide_rCURRENT.log). This is with

```diff
diff --git a/src/renderer/fonts/caching_shaper.rs b/src/renderer/fonts/caching_shaper.rs
index 00f1b82..e2b8011 100644
--- a/src/renderer/fonts/caching_shaper.rs
+++ b/src/renderer/fonts/caching_shaper.rs
@@ -386,7 +386,7 @@ impl CachingShaper {

         let mut resulting_blobs = Vec::new();

-        trace!("Shaping text: {}", text);
+        trace!("Shaping text: {:?}", text);

         for (cluster_group, font_pair) in self.build_clusters(&text, style) {
             let features = self.get_font_features(
@@ -420,6 +420,8 @@ impl CachingShaper {
                 }
             });

+            trace!("GD: {:?}", glyph_data);
+
             if glyph_data.is_empty() {
                 continue;
             }
@@ -432,6 +434,8 @@ impl CachingShaper {
                 positions[i] = (*glyph_position).into();
             }

+            trace!("G, P: {:?}, {:?}", glyphs, positions);
+
             let blob = blob_builder.make();
             resulting_blobs.push(blob.expect("Could not create textblob"));
         }
diff --git a/src/renderer/grid_renderer.rs b/src/renderer/grid_renderer.rs
index d7abf24..f792a2a 100644
--- a/src/renderer/grid_renderer.rs
+++ b/src/renderer/grid_renderer.rs
@@ -178,6 +178,7 @@ impl GridRenderer {
         let (grid_x, grid_y) = grid_position;
         let clip_position = (grid_x.saturating_sub(1), grid_y);
         let region = self.compute_text_region(clip_position, cell_width + 2);
+        trace!("CTR: {text:?} -> {region:?}");

         if let Some(underline_style) = style.underline {
             let line_position = self.shaper.underline_position();
```
as I tried to debug the issue, though I failed to spot anything amiss so far.

**Comment by ZyX-II** [comment]
Looking at [neovide_rCURRENT.log](https://github.com/neovide/neovide/files/13994097/neovide_rCURRENT.log) made by running

    cargo +stable-x86_64-pc-windows-msvc run -- --grid '1x1' --log -- -u NONE -i NONE -N --cmd 'set fillchars=eob:\  cmdheight=0 nolist noshowcmd laststatus=0' --cmd "call setline(1, [nr2char(0x2009).'t', 'u'.nr2char(0x2009).'v', ' t'])" --cmd 'autocmd FocusGained * redraw! | sleep 1 | cq'

(diff at the end) I see that resulting blobs for all U+2009 characters have width 38.6, for regular space: 46.1, for `t`, `u` and `v` 14.8. Is there an anomaly? I am not sure, but this is weird. If I use

    cargo +stable-x86_64-pc-windows-msvc run -- --grid '1x1' --log -- -u NONE -i NONE -N --cmd 'set fillchars=eob:\  cmdheight=0 nolist noshowcmd laststatus=0' --cmd "call setline(1, [nr2char(0x2009).'t', 'u'.nr2char(0x2009).'v', ' t', nr2char(0xA0).'w'])" --cmd 'autocmd FocusGained * redraw! | sleep 1 | cq'

instead (note: added line `\u{00A0}w`) I get `w` with the same width as other letter characters in [log](https://github.com/neovide/neovide/files/13994157/neovide_rCURRENT.log) and no `Shaping text: "\u{a0}"` log entry, so problem is probably not here.

```diff
diff --git a/src/renderer/fonts/caching_shaper.rs b/src/renderer/fonts/caching_shaper.rs
index 00f1b82..123c204 100644
--- a/src/renderer/fonts/caching_shaper.rs
+++ b/src/renderer/fonts/caching_shaper.rs
@@ -386,7 +386,7 @@ impl CachingShaper {

         let mut resulting_blobs = Vec::new();

-        trace!("Shaping text: {}", text);
+        trace!("Shaping text: {:?}", text);

         for (cluster_group, font_pair) in self.build_clusters(&text, style) {
             let features = self.get_font_features(
@@ -420,6 +420,8 @@ impl CachingShaper {
                 }
             });

+            trace!("GD: {:?}", glyph_data);
+
             if glyph_data.is_empty() {
                 continue;
             }
@@ -432,10 +434,14 @@ impl CachingShaper {
                 positions[i] = (*glyph_position).into();
             }

+            trace!("G, P: {:?}, {:?}", glyphs, positions);
+
             let blob = blob_builder.make();
             resulting_blobs.push(blob.expect("Could not create textblob"));
         }

+        trace!("RB: {resulting_blobs:?}");
+
         self.adjust_font_cache_size();

         resulting_blobs
diff --git a/src/renderer/grid_renderer.rs b/src/renderer/grid_renderer.rs
index d7abf24..f792a2a 100644
--- a/src/renderer/grid_renderer.rs
+++ b/src/renderer/grid_renderer.rs
@@ -178,6 +178,7 @@ impl GridRenderer {
         let (grid_x, grid_y) = grid_position;
         let clip_position = (grid_x.saturating_sub(1), grid_y);
         let region = self.compute_text_region(clip_position, cell_width + 2);
+        trace!("CTR: {text:?} -> {region:?}");

         if let Some(underline_style) = style.underline {
             let line_position = self.shaper.underline_position();
```

**Comment by fredizzimo** [comment]
I don't have access to a computer until monday, but the problem is most likely this optimization, it should probably  count unicode characters instead of length

https://github.com/neovide/neovide/blob/7d0c42b8bec78f99156037b1acf2454426145b01/src/renderer/grid_renderer.rs#L215-L220

**Comment by fredizzimo** [comment]
> I see that resulting blobs for all U+2009 characters have width 38.6, for regular space: 46.1, for t, u and v 14.8. Is there an anomaly? I am not sure, but this is weird

That's probably because the correct font is not yet loaded

**Comment by ZyX-II** [comment]
> I don't have access to a computer until monday, but the problem is most likely this optimization, it should probably count unicode characters instead of length
> 
> https://github.com/neovide/neovide/blob/7d0c42b8bec78f99156037b1acf2454426145b01/src/renderer/grid_renderer.rs#L215-L220

It looks like you are right, I do not see a problem with

```diff
diff --git a/src/renderer/grid_renderer.rs b/src/renderer/grid_renderer.rs
index d7abf24..b3e65b6 100644
--- a/src/renderer/grid_renderer.rs
+++ b/src/renderer/grid_renderer.rs
@@ -178,6 +178,7 @@ impl GridRenderer {
         let (grid_x, grid_y) = grid_position;
         let clip_position = (grid_x.saturating_sub(1), grid_y);
         let region = self.compute_text_region(clip_position, cell_width + 2);
+        trace!("CTR: {text:?} -> {region:?}");

         if let Some(underline_style) = style.underline {
             let line_position = self.shaper.underline_position();
@@ -212,23 +213,23 @@ impl GridRenderer {
         }
         paint.set_anti_alias(false);

-        // There's a lot of overhead for empty blobs in Skia, for some reason they never hit the
-        // cache, so trim all the spaces
-        let trimmed = text.trim_start();
-        let leading_spaces = text.len() - trimmed.len();
-        let trimmed = trimmed.trim_end();
-        let x_adjustment = leading_spaces as u64 * self.font_dimensions.width;
+        //// There's a lot of overhead for empty blobs in Skia, for some reason they never hit the
+        //// cache, so trim all the spaces
+        //let trimmed = text.trim_start();
+        //let leading_spaces = text.len() - trimmed.len();
+        //let trimmed = trimmed.trim_end();
+        //let x_adjustment = leading_spaces as u64 * self.font_dimensions.width;

-        if !trimmed.is_empty() {
+        if /* !trimmed.is_empty() */ true {
             for blob in self
                 .shaper
-                .shape_cached(trimmed.to_string(), style.into())
+                .shape_cached(text.to_string(), style.into())
                 .iter()
             {
                 tracy_zone!("draw_text_blob");
                 canvas.draw_text_blob(
                     blob,
-                    ((x + x_adjustment) as f32, (y + y_adjustment) as f32),
+                    ((x + 0) as f32, (y + y_adjustment) as f32),
                     &paint,
                 );
                 drawn = true;
```

**Comment by ZyX-II** [comment]
The following patch also looks like it is working fine:

```diff
diff --git a/src/renderer/fonts/caching_shaper.rs b/src/renderer/fonts/caching_shaper.rs
index 00f1b82..d890827 100644
--- a/src/renderer/fonts/caching_shaper.rs
+++ b/src/renderer/fonts/caching_shaper.rs
@@ -386,7 +386,7 @@ impl CachingShaper {

         let mut resulting_blobs = Vec::new();

-        trace!("Shaping text: {}", text);
+        trace!("Shaping text: {:?}", text);

         for (cluster_group, font_pair) in self.build_clusters(&text, style) {
             let features = self.get_font_features(
diff --git a/src/renderer/grid_renderer.rs b/src/renderer/grid_renderer.rs
index d7abf24..2e6f9cc 100644
--- a/src/renderer/grid_renderer.rs
+++ b/src/renderer/grid_renderer.rs
@@ -215,7 +215,8 @@ impl GridRenderer {
         // There's a lot of overhead for empty blobs in Skia, for some reason they never hit the
         // cache, so trim all the spaces
         let trimmed = text.trim_start();
-        let leading_spaces = text.len() - trimmed.len();
+        let leading_space_bytes = text.len() - trimmed.len();
+        let leading_spaces = text[..leading_space_bytes].chars().count();
         let trimmed = trimmed.trim_end();
         let x_adjustment = leading_spaces as u64 * self.font_dimensions.width;
```

It is better then current situation, but I am wondering though whether it actually is correct: unicode has zero-width spaces and wide spaces like EM SPACE. From what I see at least U+3000 IDEOGRAPHIC SPACE is displayed in two cells even with this patch, U+200B ZERO WIDTH SPACE and U+FEFF ZERO WIDTH NO-BREAK SPACE are displayed as `<200b>` and `<feff>` respectively which is good, but I currently have no time to try anything else.

**Comment by fredizzimo** [comment]
I think `IDEOGRAPHIC_SPACE`, is correct. CJK glyps are displayed as as two cells, so the space should be the same width.

**Comment by ZyX-II** [comment]
Sorry, “which is good” comment was meant to apply to all three tests, but after rereading I see that my comment actually looks like I expected U+3000 to occupy one space.

**Comment by ZyX-II** [comment]
Bug is also reproducible with

    neovide --grid '1x1' --log -- -u NONE -i NONE -N --cmd 'set fillchars=eob:\  cmdheight=0 nolist noshowcmd laststatus=0' --cmd "call matchaddpos('MatchParen', [[1, 2, 1]], 10, 3)" --cmd "call setline(1, [printf('{}%sA', nr2char(0x2009))])" --cmd 'autocmd FocusGained * redraw! | sleep 1'

(i.e. by having unicode space right after highlighted parenthesis), so I guess it is triggered by having space be the first character in similarly highlighted region and has nothing to do with specifically line starts. Was going to report that until I found out I still had 0.12.1 and checked it does not show up on main or after an update to 0.12.2 and thus is probably the same one.
