### ISSUE TITLE
crashes in distrobox

### ISSUE THREAD

**Issue by gmankab** [neovide/neovide#2293]
host system is fedora silverblue

in arch distrobox i tried to install via `pacman -Syu neovide`, binary from releases page, and appimage on releases page, always geting this error:
```txt
Neovide panicked with the message 'called `Result::unwrap()` on an `Err` value: XKBNotFound'. (File: /build/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.29.4/src/platform_impl/linux/wayland/seat/keyboard/mod.rs; Line: 292, Column: 40)
This is a bug and we would love for it to be reported to https://github.com/neovide/neovide/issues
Backtrace saved to neovide_backtraces.log!
```

in fedora distrobox i tried to install from copr repos `agraven/neovide`, `chrisbouchard/neovide-nightly`, and binary from releases page, always getting very long unreadable error

appimage works in fedora distrobox and outside distrobox

**Comment by fredizzimo** [comment]
Can you try installing `libxkbcommon`inside distrobox, I think the aur package is missing a dependency?

**Comment by gmankab** [comment]
thank you, after installing `libxkbcommon` it worked in arch distrobx

i noticed that copr packages for fedora are too outdated, and there is no sense to work with them

also only copr packages shows long unreadable message, and i was wrong about error message with binary from releases page on fedora, here is the real one:

```text
[flexi_logger][ERRCODE::Time] flexi_logger has to work with UTC rather than with local time, caused by IndeterminateOffset
    See https://docs.rs/flexi_logger/latest/flexi_logger/error_info/index.html#time
Neovide panicked with the message 'Failed to create Window: Error { raw_code: None, raw_os_message: None, kind: NotFound }'. (File: src/renderer/opengl.rs; Line: 92, Column: 10)
This is a bug and we would love for it to be reported to https://github.com/neovide/neovide/issues
Backtrace saved to neovide_backtraces.log!
```

backtrace:

```text
2024-01-20 04:26:01 - Neovide panicked with the message 'Failed to create Window: Error { raw_code: None, raw_os_message: None, kind: NotFound }'. (File: src/renderer/opengl.rs; Line: 92, Column: 10)
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: __libc_start_call_main
  12: __libc_start_main_impl
  13: <unknown>
```

`freetype`, `libxkbcommon`, and build dependencies are installed

**Comment by MultisampledNight** [comment]
Do other OpenGL based applications like glxgears or the like work?

**Comment by gmankab** [comment]
glxgears works without any problems

i found dependenvies fix for neovide on fedora, now everything works, so can you please add this on installation page:

fedora dependences:
```shell
sudo dnf install -y libxkbcommon libxkbcommon-x11 fontconfig libwayland-egl libglvnd-egl
```
arch dependences:
```shell
sudo pacman -Syu --noconfim libxkbcommon neovide
```

feel free to close issue

**Comment by fredizzimo** [comment]
@alerque, do you think the `libxkbcommon` dependency should be added to the Arch Linux package? On X11, I think that `libxkbcommon-x11` is also needed.

Normally this is not a problem, since your are almost guaranteed yo have them installed with a desktop environment, but when using from something like distrobox that's not the case.

**Comment by MultisampledNight** [comment]
I have a Deja-Vu. We had this already sometime ago, and alerque ended up [adding `libxkbcommon-x11` as optional dep](https://archlinux.org/packages/extra/x86_64/neovide/):


> [libxkbcommon-x11](https://archlinux.org/packages/extra/x86_64/libxkbcommon-x11/) (optional) - run on X11 (not needed for wayland)

**Comment by fredizzimo** [comment]
`libxkbcommon` is required on both Wayland and X11 though, and `libxkbcommon-x11` is additionally needed on X11.

Alacritty has both as required dependencies:
https://gitlab.archlinux.org/archlinux/packaging/packages/alacritty/-/blob/main/PKGBUILD?ref_type=heads

**Comment by alerque** [comment]
Yes absolutely if it is *required* to run it should be a dependency.

**Comment by alerque** [comment]
The official repos now have a revised package `neovide-0.12.1-2` with this fixed. It has been published but will take a few minutes to start hitting mirrors.

**Comment by fredizzimo** [comment]
Thank you alerque, I will close this issue now.
