### ISSUE TITLE
U+00A0 (NBSP) breaks color text rendering in terminal buffers

### ISSUE THREAD

**Issue by XrXr** [neovide/neovide#2294]
**Describe the bug**

Neovide renders colored text on top of other text when there is a NBSP character in the line:

<img width="391" alt="overlap" src="https://github.com/neovide/neovide/assets/6457510/7f507f70-946b-4b6a-a120-a16ad8750877">

**To Reproduce**
1. Run `:term`
2. Run `printf '\u00a0123\u001b[31m456\n'` in the shell

**Expected behavior**

It should show `123456` without any overlap.

**Desktop (please complete the following information):**
 - OS: macOS 14.2.1
 - Neovide Version 0.12.1
 - Neovim Version 0.9.5

**Additional context**
This breaks fzf.lua. Changing font does not seem to help. For example, it stills breaks if I use `Monaco` as suggested by `:help guifont`.
It's also a problem with U+2002, what `fzf.lua` uses by default. With `call setcellwidths([[0x2002, 0x2002, 2]])` it ends up coloring `345` instead of `456`.

**Comment by fredizzimo** [comment]
Yes, it indeed looks like the same issue, and your usernames were similar enough that I thought both bugs were reported by you, and that you planned to close both of them with the same fix, so I didn't make a comment.

**Comment by XrXr** [comment]
Thanks! I tested #2298 locally and it does seem to fix the issue.
