### ISSUE TITLE
Neovide cannot work well with hover.nvim

### ISSUE THREAD

**Issue by nullptr-yxw** [neovide/neovide#2300]
[hover.nvim](https://github.com/lewis6991/hover.nvim) is a plugin to display lsp and other sources, just like vim.lsp.buf.hover. But it can support mouse hover as well. However, the mouse hover cannot work well with neovide.

Behaviour of it in windows terminal (can work as except):

https://github.com/neovide/neovide/assets/96286337/be9c5715-0c7f-4572-9c32-2b90796ab557

Behaviour of it in neovide (have no response to the mouse):

https://github.com/neovide/neovide/assets/96286337/e2df7a01-82db-449e-8f2b-e9a9f925384f

However, if I use the plugin via keyboard keymap, it can work well, so the plugin has been loaded and setup successfully:

https://github.com/neovide/neovide/assets/96286337/b4276584-dbcd-403a-ac99-3d0afbc0e001

I have a look at the source code of `hover.nvim`, the code of keymap setting is [Setup and Installation](https://github.com/lewis6991/hover.nvim/blob/a7b7aba3ebf92a85e4cb6ebf1c4ee67862c5980a/README.md#setup-and-installation), and the source code of mouse hover is [require('hover').hover_mouse](https://github.com/lewis6991/hover.nvim/blob/a7b7aba3ebf92a85e4cb6ebf1c4ee67862c5980a/lua/hover/actions.lua#L311-L331)
```lua
-- copied from lewis6991/hover.nvim
local timer --- @type uv.uv_timer_t
function M.hover_mouse()
  timer = timer or assert(vim.uv.new_timer())

  local buf = api.nvim_get_current_buf()

  M.close(buf)

  local config = get_config()

  timer:start(config.mouse_delay, 0, vim.schedule_wrap(function()
    local pos = vim.fn.getmousepos()
    M.hover {
      providers = config.mouse_providers,
      relative = 'mouse',
      pos = { pos.line, pos.column }
    }
  end))
end
```
I have taken a test, and find that both `<MouseMove>`, `vim.fn.getmousepos` and `vim.uv.timer` can work well with neovide, so I have no idea about why the bug appears.

**Desktop (please complete the following information):**
 - OS: win11
 - Neovide Version: `0.12.1`(the latest release)
 - Neovim Version: `NVIM v0.10.0-dev-2164+gdc466f9a6`

**Comment by fredizzimo** [comment]
We have a couple of other issues that are almost certainly caused by the same underlying bug.
* https://github.com/neovide/neovide/issues/2222
* https://github.com/neovide/neovide/issues/2226

I'm not sure what the underlying cause and the correct fix is yet, but I think I will have time to look at it later this week.

**Comment by nullptr-yxw** [comment]
Thanks for your reply very much. I have tried it again and found that in neovide `vim.fn.getmousepos` will return the position of cursor, but not the position of the mouse, which might cause these problems.

**Comment by fredizzimo** [comment]
It looks like the problem is that the `mousemoveevent` option is not properly recognized by Neovide if it's set in the init files.

But once it has started up, and you run `:set mousemoveevent` it starts to work properly.

Can you confirm that this is the case for you as well?

**Comment by nullptr-yxw** [comment]
@fredizzimo Yes, if I run `:set mousemoveevent`, the plugin can work well as expect
