### ISSUE TITLE
`shlex::join` is Deprecated

### ISSUE THREAD

**Issue by abhillman** [neovide/neovide#2313]
**Describe the bug**

```
warning: use of deprecated function `shlex::join`: replace with `try_join(words)?` to avoid nul byte danger
   --> src/bridge/command.rs:175:23
    |
175 |     let args = shlex::join(args.iter().map(String::as_str));
    |                       ^^^^
    |
    = note: `#[warn(deprecated)]` on by default
```

**To Reproduce**
1. `cargo install --path .`

**Expected behavior**
No deprecation warnings.

**Desktop (please complete the following information):**
 - OS: macOS 14.2.1
 - Neovide Version: [`cea91a909bb3a8114074089ced7bd253ed03ed8a`](https://github.com/neovide/neovide/commit/cea91a909bb3a8114074089ced7bd253ed03ed8a)

**Comment by abhillman** [comment]
Here is some additional information regarding `shlex::join`'s deprecation:

* [GitHub Advisory Database: Multiple issues involving quote API in shlex](https://github.com/advisories/GHSA-r7qv-8r2h-pg27)
* Commit from [`comex/rust-shlex`](https://github.com/comex/rust-shlex) that deprecates `shlex::join` https://github.com/comex/rust-shlex/commit/4a0724b0b62ef715467875b040a890ce75a8a829

**Comment by abhillman** [comment]
This appears to be the only instance of `shlex::join` in this repository:

```
% rg 'shlex::join' 
src/bridge/command.rs
175:    let args = shlex::join(args.iter().map(String::as_str));
```

**Comment by fredizzimo** [comment]
This was fixed by
* https://github.com/neovide/neovide/pull/2314
