### ISSUE TITLE
Neovide is not focused after opening from icon on OSX 14.3

### ISSUE THREAD

**Issue by D00mch** [neovide/neovide#2324]
**Describe the Bug** 

When I open Neovide either from the icon or from the terminal using

```bash
$ open /Applications/Neovide.app
```

the previously active application remains focused instead of Neovide.

However, if I open Neovide using

```bash
$ neovide
```

everything works as expected: Neovide is focused.

**Desktop:** 
- OS: OSX 14.3 (23D56)
- Neovide Version: 0.12.2

**Additional Context** 

This behavior is not observed on OSX version 13.6.2 (22G320).

[neovide_rCURRENT.log](https://github.com/neovide/neovide/files/14089289/neovide_rCURRENT.log)

**Comment by AThePeanut4** [comment]
Related #2147

I've experienced this issue as well, and disabling forking fixes it for me (run `launchctl setenv NEOVIDE_FORK 0` and try launching Neovide again)

**Comment by fredizzimo** [comment]
Forking is now disabled by default by and released in Neovide 0.13.0
* https://github.com/neovide/neovide/pull/2512
