### ISSUE TITLE
Jetbrains Mono Nerd Font missing fonts on Windows 

### ISSUE THREAD

**Issue by ohuu** [neovide/neovide#2332]
![image](https://github.com/neovide/neovide/assets/25370730/11dd68c0-a594-41fb-b5f5-878d72d6f37b)

Does JetBrains font not work in Neovide?

**Comment by fredizzimo** [comment]
It should work, but there's a bug in Windows 11 that causes some fonts to disappear after a reboot, more information here:
* https://github.com/microsoft/terminal/issues/3257#issuecomment-1691425659

The font name might also be slightly different, depending on which version you have installed, you can check the correct name with
`set guifont=*`

**Comment by ohuu** [comment]
yup, it was the font name it should have been "JetBrainsMono Nerd Font"
