### ISSUE TITLE
Neovide freezes after saving file

### ISSUE THREAD

**Issue by LavaCxx** [neovide/neovide#2339]
**Describe the bug**
Each time saving the file has a probability of causing the window to freeze. I guess this is related to `noice` or `null-ls`.

At this time, clicking the X in the upper left corner cannot close Neovide.

However, the cursor still responds when switching windows.
![image](https://github.com/neovide/neovide/assets/48022591/ecdda442-b5f7-42a0-9b3a-4ee613d013d5)
![image](https://github.com/neovide/neovide/assets/48022591/ddc464a6-1902-4eeb-bcdc-8a433995d410)

**To Reproduce**
1. Save file

**Expected behavior**
None

**Screenshots**
The last thing to appear before the page froze
![image](https://github.com/neovide/neovide/assets/48022591/9e5fb8ed-2366-4b66-b5a6-bbff5d5c42e1)

**Desktop (please complete the following information):**
 - OS: macOS Sonoma 14.2.1
 - Neovide Version : 0.12.2
 - Neovim Version : v0.10.0-dev-2267+g6709f7f8f

**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**

[Neovide log](https://glaze-phosphorus-a53.notion.site/Neovide-error-log-af3221db52ff47aeb2ddde9e036b5fd9?pvs=4)

**Additional context**

**Comment by fredizzimo** [comment]
This is caused by the same Neovim bug as
* https://github.com/neovide/neovide/issues/2217
* https://github.com/neovim/neovim/issues/26980

The highlight info messages becomes too large.

**Comment by fredizzimo** [comment]
I did not notice the highlight group involved, but after checking the log again, this is indeed caused by https://github.com/lukas-reineke/indent-blankline.nvim. 

So, to work around the issue, you can disable that plugin for now. Or perhaps use https://github.com/shellRaining/hlchunk.nvim, which might not cause the same problem. In any case I recommend that over `indent-blankline.nvim`, since the latter is very slow on large files.

**Comment by LavaCxx** [comment]
> I did not notice the highlight group involved, but after checking the log again, this is indeed caused by https://github.com/lukas-reineke/indent-blankline.nvim.
> 
> So, to work around the issue, you can disable that plugin for now. Or perhaps use https://github.com/shellRaining/hlchunk.nvim, which might not cause the same problem. In any case I recommend that over `indent-blankline.nvim`, since the latter is very slow on large files.

`hlchunk` looks great, and hasn't triggered this bug so far ;).

By the way, `indent-blankline` is a plugin used by LazyVim, and others may encounter this problem. Until they fix this bug, it is indeed necessary to let more people know about this potential issue.

**Comment by LavaCxx** [comment]
The same problem occurred again, I will observe for a period of time first.

**Comment by fredizzimo** [comment]
There's also another fix, the core issue has been fixed in Neovim with this:
https://github.com/neovim/neovim/pull/27348

So ,if you use Neovim nightly it should be fixed.
