### ISSUE TITLE
`no-tabs = true` in `~/.config/neovide/config.toml` does not work

### ISSUE THREAD

**Issue by halostatue** [neovide/neovide#2348]
**Describe the bug**

Neovide opens files in tabs. I dislike this and want to disable it permanently. Documentation suggests that I can put `no-tabs = true` in `~/.config/neovide/config.toml` and it will act as if I passed `--no-tabs` on the command line.

It does not.

**To Reproduce**

1. `neovide *.md` in a directory with multiple markdown files. Observe that the files are open in tabs.
2. Add `~/.config/neovide/config.toml` containing `no-tabs = true`.
3. `neovide *.md` again. Observe that the files still open in tabs.

**Expected behavior**

Files do not open in tabs and do not waste horizontal space on the vim "tab bar".

**Desktop (please complete the following information):**

- OS: macOS 14.3 23D56 arm64
- Neovide 0.12.2
- nvim 0.9.5

[neovide_rCURRENT.log](https://github.com/neovide/neovide/files/14205105/neovide_rCURRENT.log)

**Additional context**

Trying to use `~/Library/Application Support/neovide/config.toml` does not work, either.

**Comment by AThePeanut4** [comment]
The docs aren't amazingly clear in general, but I think `Settings currently available in the config file with default values:` indicates clearly enough that the following settings are the only ones available in the config file.

https://neovide.dev/config-file.html#available-settings

But yes it would be nice to have this setting available in the config file. I never really open files from the command line with Neovide, but if I did, the silently added `-p` argument would definitely annoy me.
