### ISSUE TITLE
Can't open NeoVide in folders with `.nvimrc`

### ISSUE THREAD

**Issue by Drllap** [neovide/neovide#2349]
**To Reproduce**
1. add `set exrc` to your init.vim
2. add a `.nvimrc` to to current working directory
3. start neovide in the directory with the `.nvimrc` 
4. Neovide starts and prompts you if you trust the `.nvimrc` file but doesn't take any input so you can't proceed.

**Expected behavior**
You be able to respond to the prompt

**Screenshots**
![the prompt](https://github.com/neovide/neovide/assets/3659986/26300100-7487-44dd-afd4-4209d66705d5)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Neovide Version 0.12.1
 - Neovim Version v0.9.5

**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**
Can't, neovide start and I get the prompt and nothing is written to the log

**Additional context**
I can't even close neovide with the X button in the top right

**Comment by Drllap** [comment]
I get something similar if I start and get error in my config:
![image](https://github.com/neovide/neovide/assets/3659986/46e7c5c2-bedc-4587-a20f-45a5ba73357c)
Pressing <CR> (or anything) doesn't work and I can't close it with the top right X

**Comment by fredizzimo** [comment]
Can you try to update to Neovide  0.12.2? The issue should be fixed in that.

**Comment by Drllap** [comment]
> Can you try to update to Neovide 0.12.2? The issue should be fixed in that.

Thx, will check when it becomes available on Chocolatey

**Comment by fredizzimo** [comment]
Sorry about that.

Scoop has the latest version, and you can also. build from source.

The Winget and Chocolatey packages are currently maintained externally, and therefore not up to date, but we are looking into changing that.

**Comment by Drllap** [comment]
Guess I'm just going to need to install it manually then 😢

**Comment by Drllap** [comment]
@fredizzimo Both issues seems fixed in v0.12.2

Thanks
