### ISSUE TITLE
Frozen after sleep and wake up

### ISSUE THREAD

**Issue by badosu** [neovide/neovide#2361]
**Describe the bug**
Sometimes when I let the computer sleep neovide is frozen after wakeup.

**To Reproduce**
Can't really provide a consistent way to reproduce.

**Expected behavior**
To not freeze.

**Desktop (please complete the following information):**
 - Arch (rolling release)
 - Neovide Version 0.12.1
 - Neovim Version NVIM v0.9.5 Build type: Release LuaJIT 2.1.1702233742

Note the last keystrokes recorded in the log are meta(/super)+shift+q (the keybindings I use to quit the window, wasn't able to quit it after frozen):

[neovide_rCURRENT.log](https://github.com/neovide/neovide/files/14302338/neovide_rCURRENT.log)
[neovide_r2024-02-15_16-39-06.log](https://github.com/neovide/neovide/files/14302339/neovide_r2024-02-15_16-39-06.log)

**Additional context**
Let me know if the bug report is not good enough and I can close it. But I just can't reproduce.

**Comment by fredizzimo** [comment]
I have noticed this myself, and I think I know the cause, but have not completely verified it. 

It seems like there's a bug here, which forces it to catch up the whole sleep duration.
* https://github.com/neovide/neovide/pull/2188/commits/2fe2ff5e3ba658539e3307bdbb7168ae5642f619

This means that it does recover if you leave it running for a while (a couple of minutes at most, if it has been sleeping over the night), at least it does for me, I have never seen a complete freeze.

**Comment by badosu** [comment]
Alright, next time I'll wait a bit after wakeup to see if neovide recovers and update here with what I get

**Comment by fredizzimo** [comment]
This was fixed in https://github.com/neovide/neovide/pull/2472

**Comment by badosu** [comment]
Thank you! For the record haven't seen it on a long while.
