### ISSUE TITLE
Duplicate texts popping up when scrolling

### ISSUE THREAD

**Issue by idelice** [neovide/neovide#2364]
**Describe the bug**
Duplicate texts pop up when I scroll with C-d

**To Reproduce**
1. Scroll with C-d

**Expected behavior**
I expect *not* to see duplicate text when scrolling

**Screenshots**

https://github.com/neovide/neovide/assets/59118341/d6282441-78a7-48df-887a-686d606915a0

**Desktop (please complete the following information):**
 - OS: macOS 14.1.2
 - Neovide Version 0.12.2
 - Neovim Version 0.9.4

**Comment by wSedlacek** [comment]
This is probably the same issue as this.
https://github.com/neovide/neovide/issues/2291

The jist of it is it uses the highlight group of `WinBar` to control what is static when scrolling.
So if you want to have lualine be static you need to add something to it have the highlight group of `WinBar`

**Comment by fredizzimo** [comment]
This is fixed in Neovide 0.13.0
