### ISSUE TITLE
Uncessary padding in command line

### ISSUE THREAD

**Issue by 9mm** [neovide/neovide#2367]
This is not exactly a bug I suppose, but a change in behavior that's unideal.

**Describe the bug**

In this commit: https://github.com/neovide/neovide/pull/2307

It introduced a change where the command line takes up a lot more space which is unecessary.

I say it's not a bug because the expected behavior is that as the window size increases vertically, the command line "jumps down" _just_ when theres enough room to fit it. This is still working as expected.

however this commit seems to introduce some extremely small margin somewhere, maybe even as small as 1px, where the command line fit before and no longer does. I know this is "screen specific", but if it indeed added a very small margin/pad somewhere, then its possible it applies to many screen sizes where the command line just barely fit perfectly on that persons screen/window size, and now no longer does.

I have confirmed the window size is identical as I always use the same window manager and its as large as mac will allow it to be

<img width="1728" alt="image" src="https://github.com/neovide/neovide/assets/1386207/3bd890bf-9914-46fc-94a7-c3b8ab2fe0eb">

**Comment by 9mm** [comment]
Hmmm actually @fredizzimo .... I think the problem is in this commit, not the one i mentioned... 

https://github.com/9mm/neovide/commit/15de208f26257a19f890714cfa7d92a47cad66ed

I noticed this after rebuilding from head and reverting only this commit. I dunno what made me think it was the other one, maybe i did get reset wrong

**Comment by fredizzimo** [comment]
This will be fixed by
* https://github.com/neovide/neovide/pull/2908
