### ISSUE TITLE
Unable to open Neovide in WSL, it seems to have crashed 

### ISSUE THREAD

**Issue by FriendsZonn** [neovide/neovide#2383]
**Describe the bug**
When I input neovide in the shell, an error occurs and I am unable to open neovide

**To Reproduce**
1.type in 'neovide' in shell
2. error occurs with error msg : 
'Neovide panicked with the message 'Failed to create winit event loop: Os(OsError { line: 776, file: "/home/f/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.29.10/src/platform_impl/linux/mod.rs", error: Misc("neither WAYLAND_DISPLAY nor DISPLAY is set.") })'. (File: src/window/mod.rs; Line: 121, Column: 10)
This is a bug and we would love for it to be reported to https://github.com/neovide/neovide/issues

Backtrace saved to neovide_backtraces.log!'

**Expected behavior**
normally use 
**Screenshots**
![image](https://github.com/neovide/neovide/assets/108604742/55d323f7-ccf9-4d82-845c-5f02f6dcb356)

**Desktop (please complete the following information):**
 - OS: WSL (Linux version 5.10.16.3-microsoft-standard-WSL2 (oe-user@oe-host) (x86_64-msft-linux-gcc (GCC) 9.3.0, GNU ld (GNU Binutils) 2.34.0.20200220) #1 SMP Fri Apr 2 22:23:49 UTC 2021)
 - Neovide Version unknown, build from the latest soruce code
 - Neovim Version v0.9.5

**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**
cannot run 'neovide --log',but a neovide_backtraces.log file was saved after the error, here is the file content : 
2024-02-26 12:41:35 - Neovide panicked with the message 'Failed to create winit event loop: Os(OsError { line: 776, file: "/home/f/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.29.10/src/platform_impl/linux/mod.rs", error: Misc("neither WAYLAND_DISPLAY nor DISPLAY is set.") })'. (File: src/window/mod.rs; Line: 121, Column: 10)
0:<unknown>
1:<unknown>
2:<unknown>
3:<unknown>
4:<unknown>
5:<unknown>
6:<unknown>
7:<unknown>
8:<unknown>
9:<unknown>
10:<unknown>
11:__libc__start__main
12:<unknown>

**Additional context**

**Comment by fredizzimo** [comment]
The recommended way to use Neovide with WSL is to use the windows executable with the `--wsl` flag https://neovide.dev/command-line-reference.html#wsl.

You might be able to get it to work directly in WSL by properly installing WSLg https://github.com/microsoft/wslg, but that's not a configuration we are actively supporting and testing, and if it works, the performance would be much worse anyway.

**Comment by wanghaiqiangk** [comment]
@fredizzimo Hello there. I also met with the same problem, without setting up WAYLAND_DISPLAY or DISPLAY. However, I'm on Ubuntu and not WSL.

Somehow, the DISPLAY is unset unintentionally. If I manually set a valid value or re-open the terminal, then the problem is gone.

I wonder, in my case, the error message is reasonable, right? The environment is messed up so neovide cannot open. Or can we just guess which display monitor to use?

**Comment by fredizzimo** [comment]
On Ubuntu `DISPLAY` or `WAYLAND_DISPLAY` should be set by your Desktop Environment/Window Manager/Compositor. If that's not set, then you have serious issues with your configuration.
