### ISSUE TITLE
opening from raycast (macos) will set sh as default shell

### ISSUE THREAD

**Issue by lucax88x** [neovide/neovide#2394]
**Describe the bug**
Opening neovide from raycast, will have $SHELL with sh instead of zsh (the default one of my user & of the macos)

**To Reproduce**
1. Open raycast
2. Search neovide
3. Open it
4. Open a terminal inside of neovide
5. printenv | grep $SHELL
6. output is /bin/sh

**Expected behavior**
I would expect to see /bin/zsh

**Screenshots**
<img width="1515" alt="Screenshot 2024-03-02 at 12 17 55" src="https://github.com/neovide/neovide/assets/6294464/d7322aee-fbea-477e-a33b-ca02c3cd7c53">

**Desktop (please complete the following information):**
 - OS: macos 14.3.1
 - Neovide Version 0.12.2
 - Neovim Version 0.10.0 nightly

**Additional context**
Opening neovide from spotlight or from another terminal, it will have the correct /bin/zsh, this happens only when opened from raycast.
Honestly I have no idea if it's a raycast or neovide bug, but the weird thing is that other applications opened from raycast have zsh (like wezterm, warp, kitty) so I'm out of ideas there.

**Comment by fredizzimo** [comment]
This looks like a Raycast bug. The main application is not open source, so I can't search for bug reports. But ther are some indications that environment variables like `$SHELL` are not forwarded.

* https://github.com/raycast/extensions/issues/6073
* https://github.com/raycast/extensions/issues/3368
And on the other hand it seems to leak others
* https://github.com/raycast/extensions/issues/10078

Unless, you can convince the Raycast team to always expose the `$SHELL` environment variable, then I guess the standard approach is to create a custom extension, like for alacritty, which lets you set the shell
* https://github.com/raycast/extensions/tree/main/extensions/alacritty

**Comment by lucax88x** [comment]
I'll definitely create a bug report and an extensions to circumnavigate that!

Thanks!

**Comment by gisketch** [comment]
I use the Automator App with a zsh script and it will come up on raycast as well
![CleanShot 2024-03-04 at 10 39 46](https://github.com/neovide/neovide/assets/78424395/1e7cdad6-cb2b-43f0-a781-04021981df3e)

**Comment by lucax88x** [comment]
thanks I was able to achieve the same using raycast scripts!

Kudos to both.

**Comment by wSedlacek** [comment]
Instead of creating a luanch script you can always just set `vim.o.shell` and it most terminal plugins should use that value.
```
if vim.g.neovide then
  vim.o.shell = "fish"
end
```
