### ISSUE TITLE
able to use , but some xkbcommon error msg

### ISSUE THREAD

**Issue by FriendsZonn** [neovide/neovide#2400]
**Describe the bug**
When opening neovide, some error message disapper. but it is able to use

**To Reproduce**
1. type in 'neovide' 
2. See error

**Expected behavior**
dont print error message 
**Screenshots**

**Desktop (please complete the following information):**
 - OS:archlinux
 - Neovide Version [e.g. 0.6.0]
 - Neovim Version [e.g. 0.5.0]

**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**

**Additional context**
here is the error message : xkbcommon: ERROR: /usr/share/X11/locale/iso8859-1/Compose:39:34: string literal is not a valid UTF-8 string
xkbcommon: ERROR: /usr/share/X11/locale/iso8859-1/Compose:40:29: string literal is not a valid UTF-8 string
xkbcommon: ERROR: /usr/share/X11/locale/iso8859-1/Compose:41:29: string literal is not a valid UTF-8 string
xkbcommon: ERROR: /usr/share/X11/locale/iso8859-1/Compose:42:29: string literal is not a valid UTF-8 string
xkbcommon: ERROR: /usr/share/X11/locale/iso8859-1/Compose:43:29: string literal is not a valid UTF-8 string
xkbcommon: ERROR: /usr/share/X11/locale/iso8859-1/Compose:44:27: string literal is not a valid UTF-8 string
xkbcommon: ERROR: /usr/share/X11/locale/iso8859-1/Compose:45:27: string literal is not a valid UTF-8 string
xkbcommon: ERROR: /usr/share/X11/locale/iso8859-1/Compose:46:27: string literal is not a valid UTF-8 string
xkbcommon: ERROR: /usr/share/X11/locale/iso8859-1/Compose:47:27: string literal is not a valid UTF-8 string
xkbcommon: ERROR: /usr/share/X11/locale/iso8859-1/Compose:48:29: string literal is not a valid UTF-8 string
xkbcommon: ERROR: /usr/share/X11/locale/iso8859-1/Compose:49:29: string literal is not a valid UTF-8 string
xkbcommon: ERROR: /usr/share/X11/locale/iso8859-1/Compose:49:29: too many errors
xkbcommon: ERROR: /usr/share/X11/locale/iso8859-1/Compose:49:29: failed to parse file

**Comment by falcucci** [comment]
@FriendsZonnthank you for the effort of sharing your problem with us but,

both neovide and neovim are many versions ahead of yours.

please use the most up to date version of possible so you can check by yourself if your problem is gone.

I am closing this but can reopen  in case it persists for you after the update.

**Comment by fredizzimo** [comment]
I think the version number in the description wasn't just updated, they probably used a newer version.

In any case, this seems like a problem with some outdated system packages, if you search for similar problems elsewhere.

**Comment by fredizzimo** [comment]
I think the problem should go away if you switch to an `utf-8` locale: 
* https://github.com/xkbcommon/libxkbcommon/issues/76
