### ISSUE TITLE
How to disable ligature of font..

### ISSUE THREAD

**Issue by Jaehaks** [neovide/neovide#2403]
I found that neovide has supported font features on Jan.15 as  #2213 
but I cannot find the method anywhere.

isn't ligature feature name  'liga'? 
I entered below codes in init.lua but it doesn't work, and config.toml also. 
I'm windows 10 user.

There are not configuration explanation in configuration page of neovide homepage.
They said about just font features like size, width, etc..

```lua
vim.g.neovide_font_features = {
		["FiraCode Nerd Font Mono"] = {
			'-liga',
			'+ss07',
			'calt=0',
			'cv49=16',
			'cv94=1',
			'VXLA=2',
			'VXLC=2',
			'cv34=12',
			'cv31=13',
		}
	}

opt.guifont = 'FiraCode Nerd Font Mono:h11'
```

doesn't FiraCode Nerd Font Mono support disabling ligature?

**Comment by TwIStOy** [comment]
Font features can not be update from neovim. It should be configed in [config file](https://neovide.dev/config-file.html#location). see https://neovide.dev/config-file.html#font

**Comment by fredizzimo** [comment]
For FiraCode the correct way to disable ligatures is the following in the config file.
```toml
[font.features]
"FiraCode Nerd Font" = ["-calt"]
```
