### ISSUE TITLE
winbar glitches while scrolling

### ISSUE THREAD

**Issue by mrded** [neovide/neovide#2406]
I'm using neovim's winbar and noticed that it glitches while scrolling.

**To Reproduce**
1. Enable winbar
2. Open a file
3. Scroll down
4. You will see winbar is glitching 

**Expected behavior**
winbar to stay in place and not moving.

https://github.com/neovide/neovide/assets/347098/f2d4b088-967f-4220-bcef-16f0cb8a8a88

**Desktop (please complete the following information):**
 - OS: macOS 14.2.1
 - Neovide Version: 0.12.2
 - Neovim Version: 0.9.5

To render neovim, I'm using [nvim-lualine/lualine.nvim](https://github.com/nvim-lualine/lualine.nvim) plugin.
```lua
require('lualine').setup {
  winbar = {
    lualine_a = {
      { 'filename', path = 1 }
    },
    lualine_b = {},
    lualine_y = { 'diff', 'diagnostics' },
  },

  inactive_winbar = {
    lualine_c = {
      { 'filename', path = 1 }
    },
    lualine_x = { 'diff', 'diagnostics' },
  }
}
```

**Comment by wSedlacek** [comment]
This is probably the same issue as this.
https://github.com/neovide/neovide/issues/2291

The jist of it is it uses the highlight group of `WinBar` to control what is static when scrolling.
So if you want to have lualine be static you need to add something to it have the highlight group of `WinBar`

**Comment by 5huanghuai** [comment]
> This is probably the same issue as this. #2291
> 
> The jist of it is it uses the highlight group of `WinBar` to control what is static when scrolling. So if you want to have lualine be static you need to add something to it have the highlight group of `WinBar`

I have used your suggestion, but it didn't work. My settings are as follows:
```shell
	-- winbar
	{
		"utilyre/barbecue.nvim",
		event = "VeryLazy",
		name = "barbecue",
		version = "*",
		dependencies = {
			"SmiteshP/nvim-navic",
			"nvim-tree/nvim-web-devicons", -- optional dependency
		},
		config = function()
			require("barbecue").setup({
				-- https://github.com/neovide/neovide/pull/2165
				lead_custom_section = function()
					return { { " ", "WinBar" } }
				end,
			})
		end,
	},

```

**Comment by wSedlacek** [comment]
Hm, is barbecue the line that is having the issue or is it some over bar?
My configuration targets specifically barbecue as that is the one I was having issues with.
Tabufline (the tabs in Nvchad) had WinBar configured by default so I didn't have to adjust it's configuration at all.
If you are using something like lualine you'd need to look at the options to see how you can insert a WinBar highligh somewhere.

Here is a short clip of my configuration.

https://github.com/neovide/neovide/assets/8206108/2d56da1d-381d-4c49-b2eb-5484fe6dff3f

**Comment by fredizzimo** [comment]
This will be fixed with this https://github.com/neovide/neovide/pull/2438, but we need to get some new features to nvim in first.

**Comment by 5huanghuai** [comment]
> Hm, is barbecue the line that is having the issue or is it some over bar? My configuration targets specifically barbecue as that is the one I was having issues with. Tabufline (the tabs in Nvchad) had WinBar configured by default so I didn't have to adjust it's configuration at all. If you are using something like lualine you'd need to look at the options to see how you can insert a WinBar highligh somewhere.
> 
> Here is my configuration if you want to compare. https://github.com/wSedlacek/nvim/blob/main/lua/plugins/barbecue.lua
> 
> Here is a short clip of my configuration.
> 
>  Screen.Recording.2024-03-24.at.12.53.48.mov

Yes, I'm using utilyre/barbecue.nvim to display the winbar. The configuration I showed before was based on your configuration, but it didn't work.

**Comment by 5huanghuai** [comment]
> This will be fixed with this #2438, but we need to get some new features to nvim in first.

Thank you very much.

**Comment by mrded** [comment]
Since https://github.com/neovide/neovide/pull/2438 was closed, can we please reopen this? 🙏

**Comment by fredizzimo** [comment]
It was fixed by https://github.com/neovide/neovide/pull/2455. If there still are problems in some special case, please open a new bug.
