### ISSUE TITLE
feat: launch neovide as `--cwd $HOME` if not given directory path on macOS

### ISSUE THREAD

**Issue by falcucci** [neovide/neovide#2407]
**Is your feature request related to a problem? Please describe.**
Usually users who doesnt know neovide or it's having a trial, launches their apps from the Dock or Finder,
making it to always being opened as root path / and not the user $HOME path.

**Describe the solution you'd like**
https://github.com/neovide/neovide/pull/2405 fixes that.

**Describe alternatives you've considered**
Usually macOS users who get into neovide as their daily editor finds a trick by adding this setup on their own neovim setup, but it can generates complains, once it shouldn't open as root path as default.

**Comment by polachok** [comment]
Can't we just do something like this 🤔 

```diff
--- a/src/bridge/command.rs
+++ b/src/bridge/command.rs
@@ -182,6 +182,15 @@ fn platform_which(bin: &str) -> Option<String> {

 #[cfg(target_os = "macos")]
 fn nvim_cmd_impl(bin: String, mut args: Vec<String>) -> TokioCommand {
+    use std::io::IsTerminal;
+
+    let home_dir = {
+        objc2::rc::autoreleasepool(|pool| unsafe {
+            let home_dir = icrate::Foundation::NSHomeDirectory();
+            home_dir.as_ref().as_str(pool).to_owned()
+        })
+    };
+
     let shell = env::var("SHELL").unwrap_or_else(|_| "/bin/sh".to_string());
     args.insert(0, bin);
     let args = match shlex::try_join(args.iter().map(String::as_str)) {
@@ -194,6 +203,9 @@ fn nvim_cmd_impl(bin: String, mut args: Vec<String>) -> TokioCommand {
     }
     cmd.arg("-c");
     cmd.arg(&args);
+    if !std::io::stdin().is_terminal() {
+        cmd.current_dir(home_dir);
+    }
     cmd
 }
 ```

**Comment by falcucci** [comment]
@polachok actually not, this will override in case the tty session is launched w a startup directory (e.g Neohub) and would break its behavior, so it must respect the path.

It also overrides the --cmd/-c command which must work properly as before in neovide such as `neovide -- -- -c "cd /project"`

your trial (which actually was my first implementation) just works in case neovide is launched from Finder and the Dock itself.

**Comment by polachok** [comment]
This works from Finder, Dock and Neohub and I don't see how it may affect -c "cd /project" in any way. But yeah, whatever.

```diff
--- a/src/bridge/command.rs
+++ b/src/bridge/command.rs
@@ -194,6 +194,16 @@ fn nvim_cmd_impl(bin: String, mut args: Vec<String>) -> TokioCommand {
     }
     cmd.arg("-c");
     cmd.arg(&args);
+    if unsafe { libc::getppid() } == 1 {
+        let home_dir = {
+            objc2::rc::autoreleasepool(|pool| unsafe {
+                let home_dir = icrate::Foundation::NSHomeDirectory();
+                home_dir.as_ref().as_str(pool).to_owned()
+            })
+        };
+
+        cmd.current_dir(home_dir);
+    }
     cmd
 }
```

**Comment by falcucci** [comment]
@polachok idk if it was an artifact issue but after doing `cargo clean` it really worked as expected. Before that it kept overriding my tests such as `neovide -- /proj2 -c "cd /proj1"`.

i'll update the PR with this specific change. thank you!

**Comment by falcucci** [comment]
@polachok I found the reason why it wasn't working properly at #2405

the refactor made a change to mount the exec args.

this wasn't respecting the nvim commands anymore.

but the problem was that you were executing this at main and I was replicating at the PR which was creating this misunderstanding.

**Comment by falcucci** [comment]
@polachok I actually thought that it would work but

this is still overriding the given path to $HOME for every tty including Neohub, it should respect the given path as startup.

**Comment by polachok** [comment]
Ah, I see what may be the problem, if NEOVIDE_FORK is 1 (default) first process dies quickly enough for the second one to get reparented to 1.
So we can just do it earlier, like this:

```diff
diff --git a/src/main.rs b/src/main.rs
index 830828f..9c0ecf1 100644
--- a/src/main.rs
+++ b/src/main.rs
@@ -237,14 +237,24 @@ fn maybe_disown() {
     }

     if let Ok(current_exe) = env::current_exe() {
-        assert!(process::Command::new(current_exe)
-            .stdin(process::Stdio::null())
+        let mut cmd = process::Command::new(current_exe);
+        cmd.stdin(process::Stdio::null())
             .stdout(process::Stdio::null())
             .stderr(process::Stdio::null())
             .arg("--no-fork")
-            .args(env::args().skip(1))
-            .spawn()
-            .is_ok());
+            .args(env::args().skip(1));
+        #[cfg(target_os = "macos")]
+        if unsafe { libc::getppid() } == 1 {
+            let home_dir = {
+                objc2::rc::autoreleasepool(|pool| unsafe {
+                    let home_dir = icrate::Foundation::NSHomeDirectory();
+                    home_dir.as_ref().as_str(pool).to_owned()
+                })
+            };
+            cmd.current_dir(home_dir);
+        }
+
+        assert!(cmd.spawn().is_ok());
         process::exit(0);
     } else {
         eprintln!("error in disowning process, cannot obtain the path for the current executable, continuing without disowning...");
```

**Comment by falcucci** [comment]
@polachok that's tricky cuz using neohub if I launch a project from another dir instead of the current, the actual current overrides the given dir.

e.g supposing you are at `$HOME` and launch as

```bash
neohub $HOME/proj
```

`$HOME` overrides `$HOME/proj` startup dir which shouldn't

**Comment by polachok** [comment]
Ok, I guess it only works for me 🤷🏼 

https://github.com/neovide/neovide/assets/94035/379516fb-2bb0-489e-a34a-ff6b35c58f33

**Comment by piotrpalek** [comment]
👋 I saw that #2587 says this is fixed, but when I open neovide via spotlight it's still opening neovide with the cwd being set to "/" instead of the home directory

**Comment by ThSGM** [comment]
> 👋 I saw that [#2587](https://github.com/neovide/neovide/pull/2587) says this is fixed, but when I open neovide via spotlight it's still opening neovide with the cwd being set to "/" instead of the home directory

I have exactly the same issue, opening Neovide on MacOS---it starts off in / directory.

Has a fix been proposed?

**Comment by fredizzimo** [comment]
@ThSGM. Are you able to test with main? I think this was fixed by https://github.com/neovide/neovide/pull/2928
