### ISSUE TITLE
Not working on Ubuntu 22.04.4

### ISSUE THREAD

**Issue by rahvee** [neovide/neovide#2411]
**Describe the bug**
neovide won't open. Here is the output from command line:
neovide 
thread 'main' panicked at 'Library libwayland-egl.so could not be loaded.', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/wayland-sys-0.28.6/src/egl.rs:48:37
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

Please note, it output the path "/root/.cargo/..." but I am not running as root. That may be the cause of the problem. I have no idea why it's trying to do anything with root's home directory.

**To Reproduce**
sudo snap install nvim --classic
sudo snap install neovide
neovide

**Expected behavior**
neovide should open, or appear as an application when you open the application search menu, or be launchable in some way.

**Screenshots**

**Desktop (please complete the following information):**
Ubuntu 22.04.4 LTS
neovide 0.8.0+git from Jack Frost (j4qfrost) installed
nvim v0.9.4 from neovim-snap (neovim-snap) installed

**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**

neovide --log
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: GlobError { path: ".", error: Os { code: 13, kind: PermissionDenied, message: "Permission denied" } }', /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/ops/function.rs:150:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Additional context**
Just a fresh install, trying neovide for the first time.

**Comment by fredizzimo** [comment]
I will close this as a snap issue. Snap is not really supported anymore.
