### ISSUE TITLE
Text is wider in neovide

### ISSUE THREAD

**Issue by pushqrdx** [neovide/neovide#2424]
**Describe the bug**
Here's a comparison between vscode, photoshop, neovide and windows 10 font preview:

**Screenshots**

![image](https://github.com/neovide/neovide/assets/25884937/a246481f-35e9-46ae-8fe5-24538d433f84)

**Additional context**

Compared to vscode and photoshop's font rendering, JetBrains Mono looks wider in neovide, but it also does in the windows 10 font previewer, So I can't decide which one is correct.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Neovide Version All
 - Neovim Version nightly

**Comment by fredizzimo** [comment]
This should be fixed by https://github.com/neovide/neovide/pull/2500
