### ISSUE TITLE
IME Support

### ISSUE THREAD

**Issue by ghost** [neovide/neovide#243]
Hi there~

Awesome NeoVide is, though some support of non-English inputs may face some degrees of disability. Dynamic represent [here](https://twitter.com/_kjhl/status/1248993062837039105). Besides, thanks Kethku for friendly reply on my previous tweets, such a warm action.

- **Catch Tapping Events** When user is typing in non-English context, Vide catchs the letter and send it to inside vim. In normal situations with modern IDE, problem above will be (probably I guess) solved with `if_not_us_keyboard_current -> act nothing`.
- **Position of Popup Vocab List** As shown in tweets, the popup input methods was fixed at TL, something like `(0, 0)`.
- **The Convert of Chinese** Seemingly strings of pronunciation always goes under a process of converting to square Chinese chars in my terminal-based vim, while Vide does not.

I've noticed that some similar bugs were tagged but I hope this helps, at least the former two (I guess) will be a common faults in **Input Methods Situation**.

**Comment by Kethku** [comment]
closing in favor of https://github.com/Kethku/neovide/issues/445

**Comment by ouuan** [comment]
Please reopen this. #445 is about keyboard layout. I don't think keyboard layout support and IME support have much in common. Their purpose are both to input non-English text, but I guess the codes to support them are totally different.

I'm using US keyboard layout and IME. I subscribed to #445 hoping to watch the progress on IME support, but I'm only receiving noficiations about keyboard layout that I don't care about.

**Comment by Kethku** [comment]
Done. I'm focusing on dead keys and such for now, but am going to look into this after. I do care about the use case, it's just hard to get right when I don't personally use it

**Comment by H-M-H** [comment]
This may be of interest: https://github.com/alacritty/alacritty/pull/691/files

**Comment by Kethku** [comment]
That is interesting. I don't know how it interacts with upstream plans for keyboard input handling though

**Comment by oliver6653** [comment]
same issues, May someone fix  that ?
![image](https://user-images.githubusercontent.com/12772041/136650306-427cd881-3aee-495b-9bfd-b14386d85692.png)

**Comment by oliver6653** [comment]
thanks, good job! 
however,  I meet another question. The Eingabefeld not follow courson,  may boss spare time to fix that????

![image](https://user-images.githubusercontent.com/12772041/146769097-30f55e25-ab18-4513-8496-a0f3e4cfcd77.png)

**Comment by oliver6653** [comment]
@vzex

**Comment by oliver6653** [comment]
> thanks, good job! however, I meet another question. The Eingabefeld not follow courson, may boss spare time to fix that????
> 
> ![image](https://user-images.githubusercontent.com/12772041/146769097-30f55e25-ab18-4513-8496-a0f3e4cfcd77.png)

@vzex

**Comment by oliver6653** [comment]
@vzex  @vzex
thanks, good job! however, I meet another question. The Eingabefeld not follow courson, may boss spare time to fix that????

![image](https://user-images.githubusercontent.com/12772041/146770150-0ba52273-6068-4c68-b664-b240d52d6deb.png)

**Comment by vzex** [comment]
> @vzex @vzex Thanks, good job on win10! However, I meet another question. The Eingabefeld not follow courson, may boss spare time to fix that????
> 
> ![image](https://user-images.githubusercontent.com/12772041/146770150-0ba52273-6068-4c68-b664-b240d52d6deb.png)

I think this should be a problem of winit

**Comment by Kethku** [comment]
@vzex can you try this branch https://github.com/neovide/neovide/tree/ime-position

**Comment by lowking** [comment]
> @vzex can you try this branch https://github.com/neovide/neovide/tree/ime-position

![image](https://user-images.githubusercontent.com/33308659/183296777-6977b1b0-6132-4bce-9fe6-8e1803549219.png)
Maybe can adjust the position, it blocking the text(ime-position branch).
