### ISSUE TITLE
Handle blur setting on wayland

### ISSUE THREAD

**Issue by agraven** [neovide/neovide#2433]
**Is your feature request related to a problem? Please describe.**
As noted in `winit`'s documentation for [`Window::set_blur`](https://docs.rs/winit/latest/winit/window/struct.Window.html#method.set_blur), the blur setting works for wayland desktops with support for the `org_kde_kwin_blur_manager` protocol, i.e. at the very least KDE.

The `g:neovide_window_blurred` setting is currently only applied to the window in MacOS, but can be applied in the above cases as well. I would suggest calling `set_blur` on the winit window based on the neovide setting unconditionally, since it will at worst be a no-op.  

**Describe the solution you'd like**
Apply the `set_blur` winit setting at least on wayland, and ideally everywhere 

**Describe alternatives you've considered**
I suppose things could be kept as is

**Additional context**
Here's an example of what it looks like on KDE with neovide patched to unconditionally enable blur and with transparency set to `0.9`

![Screenshot_20240323_163547](https://github.com/neovide/neovide/assets/23525639/3ccde8a5-2d97-490f-8809-66095a3e3a5e)

**Comment by fredizzimo** [comment]
We have a couple of issues open already:
* https://github.com/neovide/neovide/issues/2078
* https://github.com/neovide/neovide/issues/1936

And a start of an implementation here:
* https://github.com/neovide/neovide/pull/2104

So I think I will close this issue.
