### ISSUE TITLE
How to disable long range animations?

### ISSUE THREAD

**Issue by leiserfg** [neovide/neovide#2435]
I want to remove all animations but the smooth movement of the cursor to the next character while typing (the rest are too eye-catching for me) Is there any way to achieve that?

**Comment by agraven** [comment]
Try setting [`let g:neovide_scroll_animation_length = 0`](https://neovide.dev/configuration.html#scroll-animation-length) and [`let g:neovide_cursor_animate_command_line = v:false`](https://neovide.dev/configuration.html#animate-switch-to-command-line)

**Comment by leiserfg** [comment]
Thanks, I did that plus `g:neovide_cursor_trail_size = 0`
