### ISSUE TITLE
Command mode tab completion breaks

### ISSUE THREAD

**Issue by 9mm** [neovide/neovide#2436]
**Describe the bug**

I notice that sometimes when I go to tab-complete in command mode it does this, instead of tab completing it inserts `^I`.

Sadly, I have tried to reproduce the error and I have no idea what I am doing which causes it to break, it happens only semi frequently. The closest I can come up with is something inside a window (either lazy.nvim or mason.nvim updating?) but if i open neovide right now and update them, i dont get a problem. it only happens sometimes

<img width="391" alt="image" src="https://github.com/neovide/neovide/assets/1386207/5106803e-309c-44d7-a082-1aad9c80adcc">

**To Reproduce**

Sadly I dont know how to reproduce, but i will keep trying

**Expected behavior**

Tab completion always works
**Desktop (please complete the following information):**
 - OS: MacOS 14.4 (23E214)
 - Neovide Version: latest master (as of a few weeks ago, if you want the actual commit let me know)
 - Neovim Version:

NVIM v0.9.5
Build type: Release
LuaJIT 2.1.1710088188

**Comment by fredizzimo** [comment]
Is there a chance that you have accidentally activated macro recording, since that usually disables all auto-completion?

**Comment by 9mm** [comment]
Hmm, if I type `qa` and then `:lsp`TAB it actually does autocomplete still

**Comment by 9mm** [comment]
That was agonizing but i tracked it down how i can reproduce on my end...

if i open any file type and type `/somethign` to search, then hit `<CR>`, any subsequent call to `:something<TAB>` will cause `^I`.

I notice this also happens in neovim though, so its not a neovide problem. i have no idea, ill have ot track this down later maybe its some plugin.....

**Comment by 9mm** [comment]
the problem is nvim-cmp or more specifically nvim-cmd-line complation

https://github.com/hrsh7th/nvim-cmp/issues/874

this might not be the issue but i forgot i had that. disabling this works
