### ISSUE TITLE
Setting fontsize causing error

### ISSUE THREAD

**Issue by idelice** [neovide/neovide#2444]
**Describe the bug**
I tried setting the font size in my init.lua:

```lua
if vim.g.neovide then
  vim.g.neovide_transparency = 0.6
  vim.g.neovide_window_blurred = true
  vim.g.neovide_unlink_border_highlights = false
  vim.g.neovide_refresh_rate = 120
  vim.g.neovide_remember_window_size = true
  vim.g.neovide_show_border = false
  -- vim.g.neovide_floating_blur_amount_x = 2.0
  -- vim.g.neovide_floating_blur_amount_y = 2.0
  vim.g.neovide_floating_shadow = true
  vim.g.neovide_floating_z_height = 10
  vim.g.neovide_light_angle_degrees = 45
  vim.g.neovide_light_radius = 5
  vim.o.guifont = ":h11" -- text below applies for VimScript
end
```

and I get the following error when opening a new neovide instance:
<img width="775" alt="Screenshot 2024-03-25 at 22 25 43" src="https://github.com/neovide/neovide/assets/59118341/1a72d90f-38eb-42fb-b204-8e112ee3d2f7">

**Expected behavior**
I expect the font size to be changed to the one i set and receive no errors.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [macOS 14.3]
 - Neovide Version [0.12.2]
 - Neovim Version [0.9.5]

**Comment by fredizzimo** [comment]
You need to specify a font name before `:h11`, you can check available fonts with `set guifont=*`

**Comment by Delice0** [comment]
> You need to specify a font name before `:h11`, you can check available fonts with `set guifont=*`

I've already tried that and a couple of other suggested solutions from Reddit but none worked... can you please provide me an example of _only_ changing the font size?

**Comment by fredizzimo** [comment]
To change the font size you can you the `neovide_scale_factor` option. There are some examples in this discussion  https://github.com/neovide/neovide/discussions/2301#discussioncomment-8223203
