### ISSUE TITLE
[feature request] smooth coursor animations in terminal emulator

### ISSUE THREAD

**Issue by gmankab** [neovide/neovide#2445]
hello

there are no coursor animations in terminal emulator

can you please add them

**Comment by Kethku** [comment]
This is out of our control. Nvim renders the cursor as a background color rather than the actual cursor position, so we cannot fix this without upstream changes.

**Comment by xzbdmw** [comment]
In fact it already works, by deleting [this check](https://github.com/neovide/neovide/blob/74170f4884322ea8f236b66308feba1e2b3e1912/src/renderer/cursor_renderer/mod.rs#L284) and delete TermCursor highlight group, you will see neovide cursor in terminal.

**Comment by gmankab** [comment]
@xzbdmw, can you pleate make a pull request?

**Comment by xzbdmw** [comment]
It's just a workaround to see vertical bar in terminal, the real fix would behttps://github.com/neovim/neovim/pull/26835
