### ISSUE TITLE
Neovide fails to launch on Hyper-V VM

### ISSUE THREAD

**Issue by kbarnes3** [neovide/neovide#2453]
**Describe the bug**
Neovide fails to launch on Windows Hyper-V VMs

**To Reproduce**
1. Install the latest version of Windows 11 on Hyper-V
2. Install Neovim and Neovide using Winget or other methods
3. Try to launch Neovide

**Expected behavior**
Neovide opens

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Windows 11 23H2 (for both the Hyper-V host and VM)
 - Neovide Version 0.12.2
 - Neovim Version 0.9.5

```
2024-03-29 17:03:38 - Neovide panicked with the message 'Could not create interface'. (File: src\window\renderer.rs; Line: 58, Column: 10)
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: <unknown>
  14: BaseThreadInitThunk
  15: RtlUserThreadStart
```

**Additional context**
This problem goes away when I set up GPU-PV on the VM, but this is not common or always available. Launching Neovide with `--nosrgb`, `--srgb`, `--novsync`, or `--vsync` does not change the behavior.

**Comment by fredizzimo** [comment]
Neovide will need a working GPU with Opengl 3.3 support, otherwise things would be way too slow. So, I don't think it's something we can fix, unless the virtualization exposes such an interface.

But there is a chance that the D3D drivers works, better if you try my experimental D3D branch:
* https://github.com/neovide/neovide/pull/2215

**Comment by kbarnes3** [comment]
Thanks, I tried your experimental branch and that does work on Hyper-V VMs using the default video adapter.

**Comment by Kethku** [comment]
We just merged that branch to main. So I believe this is fixed!
