### ISSUE TITLE
#2455 regresses scrolling on certain floating windows with borders

### ISSUE THREAD

**Issue by griwes** [neovide/neovide#2464]
**Describe the bug**
Before #2455 (and after the previous heuristics-based change), floating windows like those created with nvim-cmp smooth scrolled just their contents, not their borders. Now this behavior has regressed, and neovide attempts to scroll the contents together with the floating window.

So far I have noticed this with:
* nvim-cmp;
* dropbar's navigation dropdowns;
* neozoom's zoomed in windows.

Noice's windows scroll fine, but that's probably because of the nui hack to emulate borders without actually using floating window borders (which is a whole separate discussion, but causes me grief when trying to do consistent winblend with neovide :upside_down_face:).

**To Reproduce**
1. Install nvim-cmp.
2. Configure its windows to have a border (rounded in my case, but presumably repro's with the other options too).
3. Trigger the completion window and scroll within it.

**Expected behavior**
The borders of those floating windows should not be scrolling. This is the behavior prior to #2455.

**Desktop (please complete the following information):**
 - OS: Debian sid
 - Neovide Version 0.12.2 (git head as of typing this)
 - Neovim Version v0.10.0-dev-2791+g99b3a068d

**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**
https://gist.github.com/griwes/3e542ad7dd304a9ef2de8647abdcf379

**Comment by griwes** [comment]
@Kethku [here](https://www.dropbox.com/scl/fi/2xgk57e9pxon4j4bu6pz5/2024-04-04-03-14-14.mkv?rlkey=cdpfijp7bkzgj68vuzfdor6bz&dl=0), hopefully that's legible enough to see what's going on? Watch what happens with the top and bottom borders when I scroll.

**Comment by fredizzimo** [comment]
I can repeat this here, simply by running
`:lua vim.api.nvim_open_win(0, true, {relative="win", row=10, col=10, width=100, height=40, border="single"})`

If you add a winbar to the same window with `setlocal winbar=test` it starts scrolling correctly again. And so does a floating window without borders and winbar.

Just a bottom or a top border is also buggy
`lua vim.api.nvim_open_win(0, true, {relative="win", row=10, col=10, width=100, height=40, border="=", "=", "=", "", "", "", "", ""}})` or
`lua vim.api.nvim_open_win(0, true, {relative="win", row=10, col=10, width=100, height=40, border={"", "", "", "", "=", "=", "=", ""}})`

The problem appears to be that Neovim sends the events in the wrong order, the margin information is sent before the window is even created:
> TRACE [neovide::channel_utils] neovim_handler WindowViewportMargins { grid: 16, top: 1, bottom: 1, left: 1, right: 1 }
TRACE [neovide::channel_utils] neovim_handler WindowViewportMargins { grid: 16, top: 1, bottom: 1, left: 1, right: 1 }
TRACE [neovide::editor] viewport event received before window initialized
TRACE [neovide::editor] viewport event received before window initialized

We create the window on the Resize event, which is received after that. but still within the same flush event, so I guess technically it's according to the UI protocol spec to do it this way, but it's not how one would expect it to work.
