### ISSUE TITLE
neovide_remember_window_size and neovide_transparency options stopped working after updating to the latest commit

### ISSUE THREAD

**Issue by OrangeLightning219** [neovide/neovide#2465]
**Describe the bug**
After not updating for a long time I decided to update neovide to the latest version. After the update the `neovide_remember_window_size` and `neovide_transparency` stopped working. When launching neovide the window opens very small and messes up all my splits and the background is fully opaque.

**To Reproduce**
1. Open neovide
2. Close the window
3. Open neovide again

**Expected behavior**
Neovide remebers previous window size and the background is transparent.

**Screenshots**
Here's a short video showing the problem:
https://github.com/neovide/neovide/assets/22556400/7961b616-7018-4089-9af3-b9995681c8c6

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Neovide Version built from source from [this commit](https://github.com/neovide/neovide/commit/bcd913496924c0cfd5a99216dfb2abef2d25dcc3)
 - Neovim Version v0.10.0-dev-2210+g38bb0e1da

**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**
I found these two lines in the log:
`TRACE [neovide::settings] Initial value load failed for transparency: Error processing request: 1 - 'Key not found: neovide_transparency')`
`TRACE [neovide::settings] Initial value load failed for remember_window_size: Error processing request: 1 - 'Key not found: neovide_remember_window_size')`
Here's the full file: [neovide_rCURRENT.log](https://github.com/neovide/neovide/files/14863791/neovide_rCURRENT.log)

**Additional context**
My neovim config: https://github.com/OrangeLightning219/dotfiles/tree/master/nvim

**Comment by fredizzimo** [comment]
The log file indeed shows that the settings are not updated. The initial value load one is normal, but it should be updated after that.

Does it work if you set it from inside Neovim with `:let g:neovide_transparency=0.5`?

**Comment by OrangeLightning219** [comment]
If I set the transparency from inside neovim the background just gets darker. With transparency set to 0 it's pure black.

**Comment by fredizzimo** [comment]
That's probably a different bug actually, with the new D3D rendering backend.

But, since changing the values directly has an effect, it seems to indicate that there's something wrong with our settings reading during the startup.

**Comment by raggi** [comment]
It doesn't appear to be working with `--opengl` either

**Comment by OrangeLightning219** [comment]
When running with `--opengl` the transparency works for me, but the window size is still broken.

**Comment by Kethku** [comment]
transparency works with d3d now

**Comment by fredizzimo** [comment]
I think both `remember_window_size` and `neovide_transparency` works properly in 0.13.1. At least I have not been able to find any issues when testing it.
