### ISSUE TITLE
In neovide appimage terminal[:term] mode rustc not working properly Shell:zsh

### ISSUE THREAD

**Issue by LightningPheonix77** [neovide/neovide#2477]
**Describe the bug**
❯ rustc --version

error: unknown proxy name: 'neovide'; valid proxy names are 'rustc', 'rustdoc', 'cargo', 'rust-lldb', 'rust-gdb', 'rust-gdbgui', 'rls', 'cargo-clippy', 'clippy-driver', 'cargo-miri', 'rust-analyz

er', 'rustfmt', 'cargo-fmt'.

In neovide appimage only 

**To Reproduce**
1. Open Neovide appimage
2. go to terminal mode by using :term command
3. Then type rustc --version or rustup --version

**Desktop :**
 - OS:  AntiX 23
 - Neovide Version 0.12.2
 - Neovim Version v0.10.0-dev-2637+g400ef8aaa

**Comment by fredizzimo** [comment]
The Appimages do something very strange with the process names

* https://github.com/neovide/neovide/issues/2388
* https://github.com/neovide/neovide/issues/2209

I don't know why, and I have not found any reasonable explanation for it.

**Comment by LightningPheonix77** [comment]
Can you see this link I think it may be can able to help you https://github.com/GitSquared/edex-ui/issues/1124

**Comment by fredizzimo** [comment]
Thanks, it gave me a hint, and this issue is even more relevant:
* https://github.com/AppImage/AppImageKit/issues/852

It looks like we just need to delete the `ARGV0` environment variable.

**Comment by LightningPheonix77** [comment]
Great !! Thanks for finding and fixing the bug / error , waiting for the bugfix update !!
