### ISSUE TITLE
Direct3D rendering for linux

### ISSUE THREAD

**Issue by MOldtime** [neovide/neovide#2480]
**Is your feature request related to a problem? Please describe.**
I encountered [this problem](https://github.com/neovide/neovide/issues/843), but I was under a linux system

**Describe the solution you'd like**
Direct3D rendering for linux

**Comment by agraven** [comment]
Direct3D is a windows-specific API.

**Comment by MOldtime** [comment]
> Direct3D is a windows-specific API.

Thanks for the answer
