### ISSUE TITLE
when i use copyq select copy item, the neovide cannot paste it in insert mode

### ISSUE THREAD

**Issue by newyorkthink** [neovide/neovide#2482]
![image](https://github.com/neovide/neovide/assets/87791643/521894f7-56a6-4882-9b6e-fb83c349097e)

**Comment by fredizzimo** [comment]
To paste in insert mode, you should use the Neovim native mapping https://neovim.io/doc/user/insert.html#i_CTRL-R.

The `S-Insert` mapping is probably something your terminal provides.
