### ISSUE TITLE
delete stale branches

### ISSUE THREAD

**Issue by goyalyashpal** [neovide/neovide#2498]
hi!

thanks for providing this software.
there are lots and lots of stale branches with 3-4 yrs old with only 1-4 commits, are those needed 😃 ?

https://github.com/neovide/neovide/branches/stale

-----
backstory:

i came here to see for how to configure some behaviours like:

* reduce smoothness of scrolling for long scrolls (the `<C-d>` or `<C-u>`s) or else, disable it entirely
    > Details in the main readme https://github.com/neovide/neovide/issues/62#issuecomment-754317730
* disable cursor animations for single line movements (the `jjjjkkkk`s) or else entirely

on finding the readme to be lean, i thought maybe there's a docs site with branch `github-pages` or the like.
that's when i noticed this.

and the docs site seems to be here:
https://neovide.dev/configuration.html

----
* https://neovide.dev/configuration.html?highlight=smooth#cursor-settings
* https://neovim.io/doc/user/lua-guide.html#_-vim.o

how can i change these in current instance? 
i tried with this: `:set <option name>` with following option names, but no go, always showed '`E518: Unknown option: <option name>`'

option names tried with in `:set <option name>`:

* `neovide_cursor_trail_size`
* `g:neovide_cursor_trail_size`
* `vim.g.neovide_cursor_trail_size?`

edit: the vimscript's options work: `:let <option name>`

* <tt>:let g:neovide_cursor_[animation_length]</tt>: `0.06`
* <tt>:let g:neovide_cursor_[trail_size]</tt>: `0.7`
* <tt>:let g:neovide_[scroll_animation_length]</tt>: `0.3`

[animation_length]: https://neovide.dev/configuration.html?highlight=smooth#animation-length "(seconds)"
[trail_size]: https://neovide.dev/configuration.html?highlight=smooth#animation-trail-size "(unit not specified)"
[scroll_animation_length]: https://neovide.dev/configuration.html?highlight=smooth#scroll-animation-length "(seconds)"

**Comment by fredizzimo** [comment]
The stale branches are deleted.

And yes, you need to use `let` not set. It's not possible for a plugin or GUI to create real custom options, so variables are used instead. But I agree the documentation could be clearer here.
