### ISSUE TITLE
Position animation length is undocumented

### ISSUE THREAD

**Issue by xzbdmw** [neovide/neovide#2501]
Is there a way to disable window movement animation when :split

**Comment by fredizzimo** [comment]
If you mean the animation of the window itself, then it's `neovide_position_animation_length`. 

But I guess you mean the scrolling inside the window, that's unfortunately not possible, Neovim sends us a message that the window has been scrolled, even if it hasn't, so it needs to be fixed on their side, I think.

**Comment by xzbdmw** [comment]
> If you mean the animation of the window itself, then it's neovide_position_animation_length

Yes, it is exactly what I mean.
But I don't find this option in documentation on website.

**Comment by fredizzimo** [comment]
Ah, yes, it does indeed seem to be undocumented.
