### ISSUE TITLE
Cursor is offset from click

### ISSUE THREAD

**Issue by 9mm** [neovide/neovide#2503]
> I can confirm that it's the padding that's causing the issue. The pixel_region function does not take that into account. If you have time, you can create a quick issue so that we don't forget it. I will fix it, maybe already tomorrow, but I think I will go to bed now.

From this commit: https://github.com/neovide/neovide/commit/776ad1db5251aacf19a68580e044e92071bfb37c

**Comment by fredizzimo** [comment]
This should be fixed by
* #2511
