### ISSUE TITLE
Open files in wsl from windows context menu

### ISSUE THREAD

**Issue by WillScarlettOhara** [neovide/neovide#2506]
**Is your feature request related to a problem? Please describe.**
I can't find a way to open in wsl a Windows file with context menu.

**Describe alternatives you've considered**
I tried this key `C:\Program Files\Neovide\neovide.exe --wsl "%1"` in `\HKEY_CLASSES_ROOT\*\shell\Neovide\command`
My wsl neovim opens at the right place but the file won't open.

**Additional context**
Example trying to open `LICENSE.electron.txt` from context menu.
![image](https://github.com/neovide/neovide/assets/39462014/a46af0f7-cd46-42d0-bf22-ae44f984d4e6)
![image](https://github.com/neovide/neovide/assets/39462014/0d3633a5-45a3-47c9-8d95-b1a2e5dff4cb)

**Comments**
For the time being, I don't use Neovide, although I'd like to, because my context menu thing works with wsltty and this registry key :
`C:\Users\leilu\AppData\Local\wsltty\bin\mintty.exe --WSL="Ubuntu" --configdir="C:\Users\leilu\AppData\Roaming\wsltty" -t "%1" -e bash --login -c "nvim \"$(wslpath '%1')\""`

Btw, the command line reference section might lacks some details about wsl. It took me a while to realize that I'd have to exec `wsl --set-default Ubuntu` for `neovide --wsl` to work ;)

**Comment by fredizzimo** [comment]
I believe this was just recently fixed by:
* https://github.com/neovide/neovide/pull/2256

So, I think it should work if you build the latest from source.

**Comment by WillScarlettOhara** [comment]
`C:\Program Files\Neovide\neovide.exe --wsl "%1"` is working with latest build from source. Thank you.
Now I have to find a way to make it work with files and paths with space(s). Anything in Program Files\ won't open.

**Comment by fredizzimo** [comment]
#2507 should deal with spaces and relative paths correctly.

**Comment by WillScarlettOhara** [comment]
Thank you
