### ISSUE TITLE
Neovide Freeze (after focus?)

### ISSUE THREAD

**Issue by 9mm** [neovide/neovide#2514]
I am on latest main branch: 5efb713

I notice that when editing, neovide will entirely freeze.

I have checked my home folder and there's no crash reports so I ran it like this and tried to get it to occur:

```
cargo run --release -- --log
```

It's kind of hard to tell what steps to reproduce, however it appears I can trigger it within maybe 30 seconds if I constantly switch out of the Neovide window (to my terminal or something) and immediately switch back to neovide and hold down the `l` move right key.

I have captured some logs from the time it happened:

[Archive.zip](https://github.com/neovide/neovide/files/15153302/Archive.zip)

```
macOS: 14.4.1 (23E224)

NVIM v0.9.5
Build type: Release
LuaJIT 2.1.1713773202
```

**Comment by fredizzimo** [comment]
Would it be possible to test with Neovim nightly? There are a few bugs in 0.9.5, that could cause freezes like that.

**Comment by 9mm** [comment]
ah ok, ill have to try that later as i dont have neovim set up to build from source atm, mainly because 0.10 was nearly unusable and broke like 100 different things, i just reverted back. I do know that this never occured though before until very recently in last few days. now it happens pretty consistently (and i dont think neovim updated)

**Comment by fredizzimo** [comment]
Did you update your neovim plugins? Since they can change the behaviour. Maybe it's worth trying to see if you can repeat it with '--clean`

**Comment by 9mm** [comment]
will check now

**Comment by 9mm** [comment]
hmm cant get it to reproduce after doing it for a few mins, i will keep trying

**Comment by 9mm** [comment]
well i guess ill just close this as i cant reproduce it, and i dont have time to go through every plugin right now lol. painful

**Comment by fredizzimo** [comment]
Based on the logs, it might be `nvim-treesitter-context`

**Comment by 9mm** [comment]
Mmm i think you are right, thanks. Sorry to pollute this with noise, I forgot about `--clean`, I will remember that for the future

**Comment by 9mm** [comment]
So i disabled that plugin, and the problem didnt occur.

then i was about to make an issue there, when i decided to disable every plugin EXCEPT theirs, and now it doesnt occur lol.

So maybe its a combination of plugins or something, ill probably wait a week or two and see if it goes away, as debugging that sounds like such a pain
