### ISSUE TITLE
NeoVide renders the characters "hk" as an accented uppercase A

### ISSUE THREAD

**Issue by luhkevin** [neovide/neovide#2515]
**Describe the bug**
An uppercase accented "A" is displayed whenever I type the characters `hk`

**To Reproduce**
Go to any file, type the characters `hk`

**Expected behavior**
`hk` should be displayed

**Screenshots**

<img width="244" alt="Screenshot 2024-04-29 at 3 58 41 PM" src="https://github.com/neovide/neovide/assets/342515/df459258-bd46-4cf2-91e7-da112a055e57">
<img width="210" alt="Screenshot 2024-04-29 at 3 59 01 PM" src="https://github.com/neovide/neovide/assets/342515/a106039f-374b-4892-982f-3c0afa4873d7">
<img width="285" alt="Screenshot 2024-04-29 at 3 59 09 PM" src="https://github.com/neovide/neovide/assets/342515/95a709cd-9f07-43ef-aa73-6674ff6c87bc">

**Desktop (please complete the following information):**
Mac OS 14.4.1 
NeoVide 0.12.2
NVIM v0.9.5

**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**

[neovide_r2024-04-29_20-05-40.log](https://github.com/neovide/neovide/files/15154416/neovide_r2024-04-29_20-05-40.log)
[neovide_rCURRENT.log](https://github.com/neovide/neovide/files/15154417/neovide_rCURRENT.log)

**Additional context**
This doesn't happen when I just run `nvim` or `vim` in the terminal. This is my only neovide related config (that I know of) in my nvim config:
```
if vim.g.neovide then

  vim.g.neovide_cursor_animation_length = 0
  vim.g.neovide_cursor_trail_size = 0

  local function open_nvim_tree()
    -- open the tree
    require('nvim-tree.api').tree.open()
  end
  vim.api.nvim_create_autocmd({ 'VimEnter' }, { callback = open_nvim_tree })
end

```

As far as I know, neovim still recognizes "hk" as "hk". Searching for "hk" in neovide will still match the characters as expected. 
Wasn't able to reproduce this behavior with any other characters.

**Comment by luhkevin** [comment]
Ah I managed to sort of find the issue, it seems like switching off this font I was using fixed it...
```
vim.o.guifont = 'Monaco Nerd Font Mono:h14' -- text below applies for VimScript
```

**Comment by fredizzimo** [comment]
Can you provide the log files again. I looks like the first one was cut just as the bug was about to happen, and I don't see the hk keypresses at all in the second one.

`neovide_rCurrent.log` should be enough, just start Neovide, repeat the bug, and exit without doing anything else.

**Comment by luhkevin** [comment]
No problem -- thanks for taking a look! 
Re-ran and generated log:
[neovide_rCURRENT.log](https://github.com/neovide/neovide/files/15155099/neovide_rCURRENT.log)

**Comment by fredizzimo** [comment]
I see nothing out of the ordinary in the log. But where did you download that font from? I can see that it has had a similar problem before with the `fl` character combination https://github.com/Karmenzind/monaco-nerd-fonts/issues/5#issuecomment-1280295129

Also does your terminal support ligatures? Since I think it's a ligature bug and will only show up in editors/terminals that support that.

**Comment by luhkevin** [comment]
I think I downloaded it from https://github.com/ryanoasis/nerd-fonts/releases/download/v3.2.1/SourceCodePro.zip...but I suppose I'll try reinstalling the font from some official source.

Could be that my terminal doesn't support ligatures. I remember a ligature being displayed in NeoVide but not my terminal. My terminal is a basic iTerm2 installation on MacOS for what it's worth.

**Comment by fredizzimo** [comment]
I don't think there's an official source, all of the patched versions are technically pirated and modified from the macOS official font. The only legal way is for you to patch it yourself using the nerd fonts patcher.

By looking at the various github repositories, I also saw this issue: https://github.com/thep0y/monaco-nerd-font/issues/5, which looks very similar, but for a different combination.

**Comment by fredizzimo** [comment]
I'm going to close this as not a Neovide bug.

**Comment by luhkevin** [comment]
Thanks! Yeah seems like it, I will just try switching fonts.
