### ISSUE TITLE
cmdline copy paste suport

### ISSUE THREAD

**Issue by hantianxiaoxue** [neovide/neovide#2519]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Kethku** [comment]
Please fill out the issue template. Its there for a reason

**Comment by robbinhan** [comment]
![image](https://github.com/user-attachments/assets/eaedd0b5-f87b-48f5-bf6b-6f05e7f0509f)
I have same promble, copy text to cmdline
