### ISSUE TITLE
Map `modifier+function key` to their alternative representation

### ISSUE THREAD

**Issue by igorlfs** [neovide/neovide#2520]
**Is your feature request related to a problem? Please describe.**
When using neovim in the terminal, I can create a mapping for `<F17>`. However, instead of pressing `<F17>` (which is a key I don't even have on my keyboard), I can use `<S-F5>` instead.

In fact, there are 60 functions key, that can be achieved with a combination of modifiers. See [this discussion](https://old.reddit.com/r/neovim/comments/1111ixq/there_are_60_f_keys/) for details. 

**Describe the solution you'd like**
It would be nice if Neovide followed this "convention" too -- at least for keys `<F13>` through `<F24>`, which are fairly more common.

**Describe alternatives you've considered**
Currently, I have to create mappings for both neovim in the terminal and Neovide. This works, but it's clumsy.

**Comment by fredizzimo** [comment]
Neovide already supports mapping physical functional keys up to `F35` if your keyboard supports it and, we don't want to remove that support.

And all of the Neovide F keys can be combined with `S-`, `M-`, And `C-`, mappings so we do in fact support no less than 280 different functional key combinations currently and 96 if you restrict yourself to just F1-F12.

**Comment by fredizzimo** [comment]
And you can of course create those mapping yourself.

For example: 
* `:map <S-F1> <F13>`,

**Comment by igorlfs** [comment]
> Neovide already supports mapping physical functional keys up to F35 if your keyboard supports it and, we don't want to remove that support.

I'm not sure that I follow. Wouldn't it be possible to have support for both physical keys (up to F35) and a mapping from `<S-FX>` to `<FX+12>`, for instance? Or are you saying this would be undesirable for users with physical keyboards that have such physical keys?

> And you can of course create those mapping yourself.
> 
> For example:
> 
>     * `:map <S-F1> <F13>`,

That sounds good to me. You can close this if you want to.
