### ISSUE TITLE
can't boot neovide

### ISSUE THREAD

**Issue by Laplace825** [neovide/neovide#2523]
**Describe the bug**
I just `wget` the github latest releast of neovide and run it, after which I get the wrong message in the terminal

**To Reproduce**
1. wget https://github.com/neovide/neovide/releases/download/0.12.2/neovide-linux-x86_64.tar.gz
2. tar xzvf neovide-linux-x86_64.tar.gz
3. ./neovide

**Expected behavior**
Expected the neovide will start correctly but the bug message automatically send to my terminal.

**Desktop**
 - OS: WSL2 with Ubuntu 24.04 LTS
 - Neovide Version 0.12.2 (github release)
 - Neovim Version 0.9.5
 - I use Zshell with oh-my-zsh
 - cargo 1.78.0

**run `neovide --log` and the contents of the `.log` file**
Neovide panicked with the message 'Failed to create winit event loop: Os(OsError { line: 776, file: "/home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.29.10/src/platform_impl/linux/mod.rs", error: Misc("neither WAYLAND_DISPLAY nor DISPLAY is set.") })'. (File: src/window/mod.rs; Line: 133, Column: 10)
This is a bug and we would love for it to be reported to https://github.com/neovide/neovide/issues

Backtrace saved to neovide_backtraces.log!

**Comment by fredizzimo** [comment]
If you are using WSL, you should use `--wsl` parameter and run the native windows version https://neovide.dev/command-line-reference.html#wsl. 

`WSLg` https://learn.microsoft.com/en-us/windows/wsl/tutorials/gui-apps, might work, but that's not a configuration we actively support.
