### ISSUE TITLE
Z-index layers are not being merged correctly.

### ISSUE THREAD

**Issue by A-Lamia** [neovide/neovide#2524]
**Describe the bug**
Z-index layers are not being merged correctly causing shadows to show to show for every window layer.

**To Reproduce**
1. open neovide.
2. make sure shadows are enabled.
3. open telescope or any multi-layer plugin.

**Expected behavior**
similar z-index layers get merged in to a single window.

**Screenshots**
>https://github.com/neovide/neovide/assets/6450181/79b7b8f6-f570-48f0-8ba3-8028be396117

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Neovide Version [Main]
 - Neovim Version [v0.10.0-dev-3080+gefb44e0ca]

**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**
[neovide_rCURRENT.log](https://github.com/neovide/neovide/files/15238198/neovide_rCURRENT.log)

**Additional context**

**Comment by xzbdmw** [comment]
with a light theme
<img width="721" alt="截屏2024-05-17 23 09 56" src="https://github.com/neovide/neovide/assets/97848247/a9816a04-0a5e-4510-a770-d34ac6c62aff">
