### ISSUE TITLE
Can't config title-hidden through config file

### ISSUE THREAD

**Issue by hf-xz** [neovide/neovide#2531]
**Describe the bug**
Can't config `title-hidden` through config file on macOS, while config `frame` work.

**To Reproduce**
1. write config below into`~/.config/neovide/config.toml`.

```tool
title-hidden = true
frame = 'buttonless'
```

2. open Neovide through `Neovide.app` or run command `neovide` in terminal.
3. Neovide show with title, which shouldn't be there. However, the frame was set to 'buttonless' successfully.

**Expected behavior**
Neovide should show without title, just like run command `neovide --title-hidden`.

**Screenshots**
<img width="1370" alt="image" src="https://github.com/neovide/neovide/assets/27397614/362b8e7d-6c74-4805-946b-ba331c75dc53">

**Desktop (please complete the following information):**
 - OS: macOS 14.2
 - Neovide Version: v0.12.2
 - Neovim Version: v0.9.5

**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**
The contents is too long, so I attach a file: [neovide_rCURRENT.log](https://github.com/neovide/neovide/files/15262425/neovide_rCURRENT.log)

**Additional context**
Run `neovide --title-hidden` and set environment variable both work for me, but I really want to use raycast to open neovide.

**Comment by emonadeo** [comment]
Ran into the same issue back in feb (#2342), and was fixed in #2344.

**Comment by fredizzimo** [comment]
Ok, closing this
