### ISSUE TITLE
Toggle fullscreen uses incorrect borderless function for MacOS

### ISSUE THREAD

**Issue by diocletiann** [neovide/neovide#2532]
**Describe the bug**
https://github.com/neovide/neovide/blob/af98449980c139edfc240ef9bb9649f784c5815a/src/window/window_wrapper.rs#L179 also creates a dedicated space on MacOS. For correct borderless in current space it should be:
```
window.set_simple_fullscreen(true);
```

**To Reproduce**
toggle fullscreen

**Expected behavior**
fullscreen borderless window in current space

**Desktop (please complete the following information):**
 - OS: macOS 14.3.1
 - Neovide Version: main
 - Neovim Version: master

**Comment by falcucci** [comment]
the fullscreen has the correct behavior in the macOS perspective.

what you seems to achieve is more related to maximized windows that can be replicated such as:
```bash
neovide --maximized --frame buttonless
```
