### ISSUE TITLE
The inconsistency in the behavior of Neovide when closing compared to the closing of nvim leads to the issue of nvim processes remaining active in the background.

### ISSUE THREAD

**Issue by kebokiller** [neovide/neovide#2540]
When I attempt to exit nvim using ":q", nvim prompts me to confirm whether I want to close the already opened terminal, as shown in the image below. However, Neovide simply closes, leaving my nvim running in the background. This results in file conflicts when I reopen Neovide next time. 
![WX20240512-222822@2x](https://github.com/neovide/neovide/assets/36108603/cda5aad9-4a34-4d35-8ffe-4fd7c267fdcb)
Is it a bug? i have no idea.

**Comment by fredizzimo** [comment]
We have had a fix in the progress for a long time, but due to some problems on a few systems it wasn't merged until we finally did it yesterday:
* https://github.com/neovide/neovide/pull/2463

So, if you build from main it should be fixed.

**Comment by kebokiller** [comment]
> * #2463
Thank you for your response so soon. I will give it a try and close this issue for now.
