### ISSUE TITLE
Every neovim window in its own os-level window

### ISSUE THREAD

**Issue by IndianBoy42** [neovide/neovide#2544]
**Is your feature request related to a problem? Please describe.**
I use a tiling window manager (pop os) to run Kitty to run neovim. This means I have 3 levels of tabs and windows. 
OS-level windows can be stacked into tabs, one of those os windows has Kitty running which has tabs and windows similar to vim, one of those Kitty windows has neovim running which has tabs and windows. Thats 3 levels of nesting, which is 3 separate sets of keybindings for navigation. 

Additionally on a big screen where I can have many windows tiled, the current state forces all neovim windows to be clumped into one rectangle, rather than freely interspersed with other terminals, documentation windows, other apps, etc. The 'every' window is a window paradigm would give TWM users more flexibility to fully utilize the TWM.

**Describe the solution you'd like**
What if we could get rid of all that? make every neovim window an os-level window and run terminals separate terminals (kitty and wezterm both have the ability to interact with it remotely similar to an embedded terminal). 

I think there could be a few levels:
- Every nvim window is always its own os-window : this actually may not be desirable because things like `vsplit, split` will get confusing, unless neovide integrates with the os TWM to keep those relations, at least at the point of creation
- Each tabpage gets its own window, this could be automatic for every tabpage or perhaps with the user manually "detaching" a tabpage. 

Floating windows that are relative to a win should be a floating window inside that window (as it is now) but floating windows relative to the editor could be given their own os window as well. 

**Describe alternatives you've considered**
Just deal with the status quo. Having this natively in neovim is (IIRC) planned as part of the whole decoupling TUI from core, but its a long way away. Maybe it could be done easier in neovide as you would not actually have multiple UIs attached, just one that splits it into windows  

**Additional context**
If this is something you would be interested in, I would be glad to contribute and do most of the legwork given a little bit of mentoring and guidance of where to start looking.

**Comment by IndianBoy42** [comment]
Prior art: https://github.com/glacambre/nwin

**Comment by Kethku** [comment]
As much as this sounds cool, there are a lot of things that make this hard to implement on our side. There has been talk about popping individual windows out into their own os window which may get implemented but thats not really what you are asking for. So unfortunately I think we have to close this issue as won't fix.

Would be fun to implement as a separate project though. I could imagine a fork of neovide that builds this out. Its just too much to maintain in neovide directly I think
