### ISSUE TITLE
Blurry text after #2500

### ISSUE THREAD

**Issue by agraven** [neovide/neovide#2548]
**Describe the bug**
Text is significantly blurrier after #2500 

**To Reproduce**
Launch neovide

**Expected behavior**

**Screenshots**
On the left is after fractional rendering, on the right is before

![image](https://github.com/neovide/neovide/assets/23525639/c5832f67-ada5-4e12-91d7-a2e00c34700f)

**Desktop (please complete the following information):**
 - OS: Fedora 40, Ubuntu 23.10
 - Neovide Version: 0153bdb5006d25a9c1262b5bb58736d48fa25ba0 and f5bab656b262e32df5acec653ad906a6b0643287
 - Neovim Version: Latest nightly as of 2024-05-15

**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**

**Additional context**
Font in the screenshot is Iosevka Term Slab, but this happens with all fonts

**Comment by fredizzimo** [comment]
There's already a fix for it here https://github.com/neovide/neovide/pull/2543. 

Before that is merged, you can manually set the hinting to `full`, like it was before.

**Comment by agraven** [comment]
Thanks for the swift response, that alleviates the issue a lot.
