### ISSUE TITLE
Neovide 0.13.0 on macOS launches behind other windows.

### ISSUE THREAD

**Issue by humblehacker** [neovide/neovide#2554]
**Describe the bug**
Neovide 0.13.0 on macOS launches behind other windows.

**To Reproduce**
1. Start your terminal (I'm using iTerm)
2. Install Neovide 0.13.0 from homebrew
    `brew install neovide`
3. Start Neovide
    `neovide`

**Expected behavior**
Neovide launches in the foreground.

**Desktop (please complete the following information):**
 - OS: macOS 14.4.1 (23E224)
 - Neovide Version: 0.13.0
 - Neovim Version: 0.10.0

**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**

[neovide_rCURRENT.log](https://github.com/neovide/neovide/files/15351407/neovide_rCURRENT.log)

**Additional context**
I tried launching both with `--fork` and `--no-fork`. Both options launched with the window in the background.

I also reinstalled Neovide 0.12.2 from homebrew `brew install --cask neovide`, and Neovide correctly launches in a foreground window.

**Comment by humblehacker** [comment]
Seems this might be an issue with the homebrew formula. I uninstalled (`brew uninstall neovide`), downloaded and installed from the dmg from the GitHub release page, and launched from the terminal using a symlink to the binary in the app bundle. It correctly launches in a foreground window (albeit with a strange opening animation that shows only the titlebar expanding to full screen, with the rest of the window appearing only when the animation is complete).

**Comment by humblehacker** [comment]
The homebrew issue may be a red herring. The problem seems intermittent. I've been able to reproduce the problem with both the homebrew binary and the one found here.

**Comment by fredizzimo** [comment]
This is opposite to this bug, which I think we also has seen in Neovide
* https://github.com/rust-windowing/winit/issues/2051

I expect both be fixed when we refactor our window creation to happen at a different place and move to winit 0.30, which should happen pretty soon.

**Comment by humblehacker** [comment]
Thanks for the info! I'll stop investigating and revert to 0.12.2 until that's ready.

**Comment by fredizzimo** [comment]
I have a potential fix for this here:
* https://github.com/neovide/neovide/issues/915

It would be good if someone could test it.

**Comment by bboles** [comment]
I am still experiencing this issue with neovide version 0.13.1.  I'm on MacOS 14.5 and neovim version 0.10.0.
