### ISSUE TITLE
Shorthand for disabling animations

### ISSUE THREAD

**Issue by sevenc-nanashi** [neovide/neovide#2565]
**Is your feature request related to a problem? Please describe.**
I get unneeded animations when I update neovide.
I like neovide because it launches quickly, but I don't need animations.

**Describe the solution you'd like**
`let g:neovide_disable_all_animations = 1` to disable all animations, for shorthand.

**Describe alternatives you've considered**
Provide snippet in wiki.

**Additional context**
How do I disable animation of resizing buffer?

**Comment by xzbdmw** [comment]
I think that's all
```lua
vim.g.neovide_position_animation_length = 0
vim.g.neovide_cursor_animation_length = 0.00
vim.g.neovide_cursor_trail_size = 0
vim.g.neovide_cursor_animate_in_insert_mode = false
vim.g.neovide_cursor_animate_command_line = false
vim.g.neovide_scroll_animation_far_lines = 0
vim.g.neovide_scroll_animation_length = 0.00
```

**Comment by Kethku** [comment]
I'm opting for the docs change instead. Thanks @xzbdmw adding your snippet to the faq page
