### ISSUE TITLE
Crash on launch in Linux

### ISSUE THREAD

**Issue by Munchotaur** [neovide/neovide#2568]
**Describe the bug**

**To Reproduce**
Launch neovide from the command line.

**Expected behavior**
Neovide should launch in all its beauty.

**Desktop (please complete the following information):**
 - OS: MX Linux 23.2 "Libretto" / Cinnamon
 - Neovide Version 0.13.0
 - Neovim  v0.10.0-dev-ebe489d

**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**

Log file was too long for the bug report! Please see this gist: https://gist.github.com/Munchotaur/63f4e545da13f24c84f7f1bdf082fd73

**Additional context**
Has only happened since update to v0.13.0 -- worked fine until then.

**Comment by Munchotaur** [comment]
Was over an ssh session. Works fine on the actual machine. Closing. :neutral_face:

**Comment by fredizzimo** [comment]
There are some issues with nvim over ssh inside tmux
* https://github.com/neovim/neovim/issues/28827
* https://gitlab.archlinux.org/archlinux/packaging/packages/neovim/-/issues/5
