### ISSUE TITLE
Why is Neovide always attached to the terminal, when ran from it?

### ISSUE THREAD

**Issue by vinoff** [neovide/neovide#2579]
```
❯ neovide --version
neovide 0.13.0

❯ uname -r
6.9.1-arch1-1
```

Why is neovide attached to the terminal, when ran from it? I think prior to version 0.13 this was not the case, was it?

I have it installed from [extra] on Arch Linux.

**Comment by fredizzimo** [comment]
The behaviour was indeed changed to default to `--no-fork` and is mentioned as a breaking change in the release notes.

The change was based on the discussions here, and we also kept the PR open for two weeks, without getting any feedback until it was merged.
* https://github.com/neovide/neovide/issues/2147
* https://github.com/neovide/neovide/pull/2512

Basically it was done to allow a saner terminal workflow and work like any other GUI application (I know two exceptions to this rule: VSCode and gvim)

You can change the defaults back to how it was before by defining the environment variable `NEOVIDE_FORK=1`, or start neovide with `neovide --fork`

**Comment by vinoff** [comment]
Ok, understood. I can just create an alias, no worries. Thank you!
