### ISSUE TITLE
Transparency doesn't make the tabline endings transparent

### ISSUE THREAD

**Issue by realhackcraft** [neovide/neovide#2582]
**Describe the bug**
the transparency option doesn't make the tabline endings transparent

**To Reproduce**
1. set `vim.g.neovide_transparency = 0.8`
2. get a tabline with an custom line ending (I use NvChad)
3. Reload neovide
4. See Error

**Expected behavior**
The ending of the tabline is like a chacter (i know its a powerline glyph) but I would expect it to be the same color as the background

**Screenshots**
<img width="1440" alt="Screenshot 2024-05-21 at 16 08 23" src="https://github.com/neovide/neovide/assets/65378120/269e5465-c5e3-4664-badd-66143e10b6f3">

**Desktop (please complete the following information):**
 - OS: macOS 14.5
 - Neovide Version 0.13.0
 - Neovim Version 0.10

**Comment by fredizzimo** [comment]
See these:
* https://github.com/neovide/neovide/issues/2275
* https://github.com/neovide/neovide/issues/2471
