### ISSUE TITLE
macOS: opening multiple files via the app ignored `tabs = false`

### ISSUE THREAD

**Issue by chrisgrieser** [neovide/neovide#2585]
**Describe the bug**
opening multiple files via the app/Finder (#2395) ignores `tabs = false`

**To Reproduce**
```toml
# config.toml
tabs = false
```

```bash
# run in terminal
open -a "Neovide" "foobar.txt"
open -a "Neovide" "helloworld.txt"
```

There are now two tabs open in Neovide.

**Expected behavior**
`tabs = false` should be respected, the commands above should not result in multiple tabs.

**Desktop (please complete the following information):**
```
NVIM v0.10.0
Build type: Release
LuaJIT 2.1.1713773202
macOS 14.4.1 (arm)
Neovide 0.13
```

**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**

[neovide_rCURRENT.log](https://github.com/neovide/neovide/files/15407086/neovide_rCURRENT.log)

**Comment by falcucci** [comment]
this has been fixed at https://github.com/neovide/neovide/pull/2692
