### ISSUE TITLE
Panick on XKBNotFound

### ISSUE THREAD

**Issue by DragosPetri** [neovide/neovide#2590]
Neovide won't start due to a panick.

1. Install neovide from source on WSL
2. Try to run neovide (every flag will panick)
3. Install neovide on Windows from release
4. Try to run with wsl flag

**Expected behavior**
Expected to work like VScode where it opens the GUI in Windows.

**Screenshots**
![image](https://github.com/neovide/neovide/assets/52441284/4f07d63c-5e0f-45f8-b73b-9319e500303e)

 - OS: Windows 10 with WSL:
          WSL version: 2.1.5.0
          Kernel version: 5.15.146.1-2
          WSLg version: 1.0.60
          MSRDC version: 1.2.5105
          Direct3D version: 1.611.1-81528511
          DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
          Windows version: 10.0.19044.4170
 - Neovide Version: 0.13.0
 - Neovim Version:
          NVIM v0.11.0-dev-77+gcf4723c09
          Build type: RelWithDebInfo
          LuaJIT 2.1.1713484068

**LOGS:**

2024-05-24 12:17:12 - Neovide panicked with the message 'called `Result::unwrap()` on an `Err` value: XKBNotFound'. (File: /home/dragos/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.29.15/src/platform_impl/linux/wayland/seat/keyboard/mod.rs; Line: 315, Column: 41)
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: <unknown>
  14: <unknown>
  15: __libc_start_call_main
             at ./csu/../sysdeps/nptl/libc_start_call_main.h:58:16
  16: __libc_start_main_impl
             at ./csu/../csu/libc-start.c:360:3
  17: <unknown>

**Comment by fredizzimo** [comment]
Running from within WSL is not supported by us, but you might get it to work if you have WSLg setup https://learn.microsoft.com/en-us/windows/wsl/tutorials/gui-apps, and XKB installed (missing in this case)

The native windows executable with `neovide --wsl` will give you much better performance. If you want to launch that from within WSL, you can make an alias `alias neovide="neovide.exe --wsl`, or launch `neovide.exe` instead of `neovide`

**Comment by DragosPetri** [comment]
Thank you for the reply and the tip.
Still, the windows version doesn't work either.
Here are the logs I've found:

2024-05-24 14:59:22 - Neovide panicked with the message 'Failed to create DXGI factory: Error { code: HRESULT(0x887A0001), message: "The application made a call that is invalid. Either the parameters of the call or the state of some object was incorrect.\r\nEnable the D3D debug layer in order to see details via debug messages." }'. (File: src\renderer\d3d.rs; Line: 112, Column: 59)
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: BaseThreadInitThunk
  14: RtlUserThreadStart
