### ISSUE TITLE
Add support for mapping ANSI color codes to custom colors

### ISSUE THREAD

**Issue by ekorchmar** [neovide/neovide#2591]
**Is your feature request related to a problem? Please describe.**
Currently, if something (e.g. ToggleTerm) wants to draw something inside a window using one of 16 ANSI colors, they fall back to default (and very ugly) values, that may have bad contrast with chosen Normal's bg. In the example below, Lazygit uses default ANSI blue color for frames and tab titles, and they are barely readable. Modern Terminal applications support overriding default ANSI colors for display, examples:
* [Windows Terminal](https://learn.microsoft.com/en-us/windows/terminal/customize-settings/color-schemes)
* [iTerm2](https://iterm2.com/documentation-preferences-profiles-colors.html)
* [WezTerm](https://wezfurlong.org/wezterm/colorschemes/index.html)
* Alacritty, Konsole, Gnome Terminal, any and all of them.

**Describe the solution you'd like**
Ability to map 16 ANSI color codes to custom colors.

**Describe alternatives you've considered**
Overriding colors inside the offending program (e.g. lazygit itself), but it is not always possible.

**Additional context**
![image](https://github.com/neovide/neovide/assets/32364416/653a0261-ca98-44d3-83cd-6bc675699e1a)

**Comment by fredizzimo** [comment]
That's already supported:
* https://neovide.dev/faq.html#the-terminal-displays-fallback-colorsterminal-does-not-show-my-colors
