### ISSUE TITLE
linespace pushes up the underline

### ISSUE THREAD

**Issue by cizmazia** [neovide/neovide#2600]
**Describe the bug**

There is a regression in  0.13.1 where the `linespace` configuration interferes with the position of the underline.

**To Reproduce**

`set linespace=0`

![Screenshot_2024-05-27_09-03-40](https://github.com/neovide/neovide/assets/440490/4d389741-a508-4794-95e1-c4c8b79e4f3f)

`set linespace=3`

![Screenshot_2024-05-27_09-04-55](https://github.com/neovide/neovide/assets/440490/1d4d2fd5-d51e-4564-a0e5-2cad3166d70b)

The underline is pushed upwards.

**Expected behavior**

The position of the underline should not be influenced by the `linespace` configuration.

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04.4 LTS
 - Neovide Version 0.13.1
 - Neovim Version 0.10.0

**Additional context**

Neovide Version 0.13.0 did not have this problem.

**Comment by VimWei** [comment]
- Neovide 0.13.1
- nvim 0.10
- win 10 pro

The underline is misplaced and has turned into a strikethrough. 

![image](https://github.com/neovide/neovide/assets/25874852/2d1b1176-86d5-4199-a0ef-ced0d5afbc83)

**Comment by fredizzimo** [comment]
@VimWei, the fix is not released yet, so you need to build from source or use the binaries from the CI.

This is the latest CI run on main. The artifacts are at the very bottom of the page https://github.com/neovide/neovide/actions/runs/9342246250

**Comment by AlvesJorge** [comment]
Hi! 
Is there an option to change the space between the underline and the characters? Even at linespace 0 it is still too close for me.

**Comment by fredizzimo** [comment]
Yes, it's still not correct. There was an attempt to make it adjustable here
* https://github.com/neovide/neovide/pull/2647

But during the review we found out that the spacing is wrong. I think I found the actual problem but I have been on a vaccation without access to a development machine. But I'm back now and should be able to start fixing issues again.
