### ISSUE TITLE
Certain keymaps dont work in the Neovide GUI - Macos 

### ISSUE THREAD

**Issue by Ajaymamtora** [neovide/neovide#2608]
**Describe the bug**
I have a binding on <A-n> which triggers fine through terminals, but in the gut it doesn't work.

I used screen key to view what the keypress is registered as and it's some other sequence.

Right Alt + N is registered as CTRL + N for some reason? And left alt + N is registered as this:
![image](https://github.com/neovide/neovide/assets/45173937/13aa17b3-32fc-4a92-a48f-91853e0cb930)

I have no idea what `<cb> <9c>` is. This mapping works fine through nvim in wezterm, Alacritty kitty etc.

**Expected behavior**
Alt + N should bind correctly.

**Desktop (please complete the following information):**
 - OS: macOS 14.5
 - Neovide Version neovide 0.13.1
 - Neovim Version (stable 0.10):
NVIM v0.10.0
Build type: Release
LuaJIT 2.1.1713484068
Run "nvim -V1 -v" for more info

**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**
[neovide_rCURRENT.log](https://github.com/neovide/neovide/files/15491038/neovide_rCURRENT.log)

**Comment by fredizzimo** [comment]
I'm re-opening this. The setting should be applied no matter where it's defined in the init file. 

I already found the bug and will make a fix soon.

**Comment by fredizzimo** [comment]
This should be fixed by
* #2619 

But I don't have a macOS computer to test it on myself.

**Comment by epheien** [comment]
same issue
temporary workaround:
```vim
function s:LazySetupNeovide(...)
    let g:neovide_input_macos_option_key_is_meta = 'only_left'
endfunc
call timer_start(200, 's:LazySetupNeovide')
```
wating for fix

**Comment by asabla** [comment]
@fredizzimo just tested it with pr #2619 and it seems not to be register it properly. Still need what was previously suggested in this issue.

```
if vim.g.neovide then
  vim.g.neovide_input_macos_option_key_is_meta = 'only_left'
end
```

This was tested on
OS: MacOS v14.5 (Sonoma)
CPU: M3 max
neovim version: v0.10.0
LuaJIT version: 2.1.1716656478
Cargo version: 1.77.1 (e52e36006 2024-03-26)

Let me know if there is anything I can do to help with further testing

**Comment by fredizzimo** [comment]
@asabla 

`vim.g.neovide_input_macos_option_key_is_meta = 'only_left'`, or `both`, will always be needed for Neovide to interpret the key press as `<M-n>`, otherwise it will be interpreted as the character macOS produces for that keypress. See the comment in code https://github.com/neovide/neovide/blob/1db63d93b18cc1eb5ac5b3e67b3ca63505f10800/src/window/keyboard_manager.rs#L315-L368 (Maybe we should exteact that to the actual documentation as well)

The issue and the fix is about the setting not working when set in the init file, because it was applied too early, therefore the workaround with the timer.

**Comment by asabla** [comment]
Oh, in that case @fredizzimo it's my misunderstanding and your fix works :) 

+1 on making this part more obvious for MacOS users in the documentation

**Comment by kuntau** [comment]
I have problem with detecting <kbd>Alt</kbd>+<kbd>`</kbd> in Neovide. I use it to toggle floating terminal, no problem in terminal (kity, wezterm, iterm).

Pressing <kbd>Ctrl</kbd>+<kbd>v</kbd> -> <kbd>Alt</kbd>+<kbd>`</kbd> in insert mode produce nothing, it usually shows whatever combination we press.

I'm not sure it's related to this issue or not.
