### ISSUE TITLE
error open file limit

### ISSUE THREAD

**Issue by erlangparasu** [neovide/neovide#2615]
**Describe the bug**
https://github.com/neovide/neovide/discussions/2604

**To Reproduce**
1. Open Neovide
2. Open some buffer
3. Switch buffer frequently

**Expected behavior**
1. Open Neovide
2. Open some buffer
3. Switch buffer frequently
4. Do not see error

**Screenshots**
.

**Desktop (please complete the following information):**
 - OS: macOS Ventura 13.6.7 (22G720)
 - Neovide Version: 13.6.7 (22G720)
 - Neovim Version: 0.10.0

**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**
.

**Additional context**
.

**Comment by fredizzimo** [comment]
I don't think this is a Neovide bug, it properly happens with the terminal mode Neovim as well. 

But it does look like a bug in `neo-tree  and should be reported there. One bug was fixed a long time ago, so if you run an old version of that it's also worth updating https://github.com/nvim-neo-tree/neo-tree.nvim/issues/997

**Comment by agraven** [comment]
If you haven't done so already, you'll probably want to increase the max number of open files, since MacOS's default is very low. You can find instructions for doing so in e.g. this stackoverflow thread: https://superuser.com/questions/1634286/how-do-i-increase-the-max-open-files-in-macos-big-sur

**Comment by fredizzimo** [comment]
I'm closing this due to no response and for not being a Neovide bug.
