### ISSUE TITLE
Shift+space produces ;2u in the terminal

### ISSUE THREAD

**Issue by glibg10b** [neovide/neovide#2617]
**Describe the bug**
In a terminal buffer, pressing space while holding shift produces `;2u`. This behaviour is not compatible with my typing habits.

**To Reproduce**
1. `:term`
2. Enter insert mode.
3. Type `+ `. Make sure to type the space *before* releasing shift.

**Expected behavior**
A space should be produced as in other buffers and in other terminal emulators.

**Desktop (please complete the following information):**
 - OS: Gentoo Linux
 - Neovide Version 0.12.2
 - Neovim Version v0.9.5

**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**

I can't:
> There was an error creating your Issue: body is too long, body is too long (maximum is 65536 characters).

**Additional context**
neovim-qt had the exact same behaviour: https://github.com/equalsraf/neovim-qt/issues/728

**Comment by sid-6581** [comment]
How about neovim in the terminal? I believe when I looked into this, this is all in neovim. You can remap shift-space and shift-enter (which has the same problem) in neovim itself:

```
vim.keymap.set("t", "<S-Enter>", "<Enter>", { desc = "Insert enter" })
vim.keymap.set("t", "<S-Space>", "<Space>", { desc = "Insert space" })
```

**Comment by fredizzimo** [comment]
Yes, this is a Neovim issue:
https://github.com/neovim/neovim/issues/24093

I believe it has also been brought up here a few times.

**Comment by glibg10b** [comment]
I can confirm that shift-enter has the same problem, but I can't reproduce the problem in Neovim -- at least not with kitty.

The workaround works. Thanks for both of yours' attention.
