### ISSUE TITLE
test_read_initial_values test is failing

### ISSUE THREAD

**Issue by kas2020-commits** [neovide/neovide#2618]
**Describe the bug**
post-build test fails, causing no install on Nix-unstable package

```
test settings::tests::test_read_initial_values ... FAILED
```

**To Reproduce**
Try installing Neovide 0.13.0 from nixpkgs-unstable branch. The json from my `flake.lock` is

```json
    "nixpkgs-unstable": {
      "locked": {
        "lastModified": 1716509168,
        "narHash": "sha256-4zSIhSRRIoEBwjbPm3YiGtbd8HDWzFxJjw5DYSDy1n8=",
        "owner": "nixos",
        "repo": "nixpkgs",
        "rev": "bfb7a882678e518398ce9a31a881538679f6f092",
        "type": "github"
      },
      "original": {
        "owner": "nixos",
        "ref": "nixos-unstable",
        "repo": "nixpkgs",
        "type": "github"
      }
    },
```

**Expected behavior**
I expected the build to succeed

**Screenshots**
<img width="804" alt="Capture d’écran, le 2024-05-31 à 15 35 15" src="https://github.com/neovide/neovide/assets/53112668/84750f4c-613f-46bd-9403-44339d983020">

**Desktop (please complete the following information):**
- MacOS Sonoma 14.5 (23F79)

**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**
N/A since neovide didn't install itself for me

**Additional context**

**Comment by fredizzimo** [comment]
I think this bug should be reported to the nixpgs. The tests are passing both locally and, in the CI, here https://github.com/neovide/neovide/actions/runs/9228784038/job/25393588056#step:9:641, and I have not seen a single failure before or after that either.

**Comment by kas2020-commits** [comment]
Just came back to this after the weekend and it seems it was already reported downstream: NixOS/nixpkgs/issues/314827
