### ISSUE TITLE
The program did not respond for a long time after sleep

### ISSUE THREAD

**Issue by zgpio** [neovide/neovide#2634]
**Describe the bug**

**To Reproduce**
1.  open a file with neovide 
2.  sleep computer
3.  activate  neovide window
4.  The program did not respond for a long time before returning to normal

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: windows10
 - Neovide Version 0.12.2
 - Neovim Version  latest

**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**

**Additional context**

**Comment by fredizzimo** [comment]
This was fixed in the 0.13.0 version of Neovide, so if you update to that or preferably to the newest 0.13.1, it should be fixed.
