### ISSUE TITLE
Neovide crashes after installation

### ISSUE THREAD

**Issue by mohan2406** [neovide/neovide#2645]
**Description of the bug**
I downloaded neovide "neovide-linux-x86_64.tar.gz" from the releases in the github. After I run neovide I get ERROR [neovide::error_handling]. 

**To Reproduce**
1. Go to 'terminal'
2. Go to the folder that has neovide exec
3. run neovide

**Expected behavior**
A new neovide gui window will open.

**Screenshots**
![neovide-bug](https://github.com/neovide/neovide/assets/99663059/385d8754-bc95-413e-a003-bd58f6c6ad38)

**Desktop**:
 - OS: [ Ubuntu 22.04]
 - Neovide Version [ 0.13.1]
 - Neovim Version [ 0.6.1]

neovide log isn't working I get the same error message when I run neovide --log

**Additional context**

**Comment by xzbdmw** [comment]
You should use nvim 0.10, otherwise newest version of neovim will crash

**Comment by mohan2406** [comment]
> You should use nvim 0.10, otherwise newest version of neovide will crash

Thank you this works.
