### ISSUE TITLE
lualine and bufferline not show correctly in fullscreen

### ISSUE THREAD

**Issue by dty2** [neovide/neovide#2646]
**Describe the bug**
In i3, I type "alt + space" to make the window full of screen
bufferline and lualine will not close to the right edge of screen
and between lualine and the bottom of screen has some free space too
(I use noice.nvim plugin and "set opt.showmode = false", so the free space should not exist)

**To Reproduce**
1. use i3 and set "bindsym $mod+space fullscreen toggle" in it's config file
2. use lualine and bufferline plugin
3. open neovide and you will see the error in screenshots

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. macOS 11.4]
 - Neovide Version [e.g. 0.6.0]
![notfullscreen](https://github.com/neovide/neovide/assets/118413413/0ece2ecd-1182-4bd7-99c5-8d774b637dbc)
![error](https://github.com/neovide/neovide/assets/118413413/11c627e1-9238-497f-aeca-c88e2f59de5a)

 - Neovim Version [e.g. 0.5.0]

**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**

**Additional context**

**Comment by xzbdmw** [comment]
You can try modify your font size, since neovim is grid based, if a line can’t fits in bottom space, it will leave the  line blank

**Comment by dty2** [comment]
> You can try modify your font size, since neovim is grid based, if a line can’t fits in bottom space, it will leave the line blank

thanks! I set 
`vim.o.guifont = "3270 Nerd Font,也字工厂曲奇体:h18:#e-subpixelantialias"`
and it works now!
