### ISSUE TITLE
Issue starting Neovide application with the `fish` shell. 

### ISSUE THREAD

**Issue by qTipTip** [neovide/neovide#2648]
Hello! First of all, thanks for a great piece of software! 🥳 

**Describe the bug**

I am running `fish` as my shell of choice. When running neovide from the terminal, I run into this error: 

```shell
ERROR [neovide::error_handling] Neovide just crashed :(
This is the error that caused the crash. In case you don't know what to do with this, please feel free to report this on https://github.com/neovide/neovide/issues!

ERROR: Unexpected output from neovim binary:
        /opt/homebrew/bin/nvim -v
stdout: This script is now using VK_ADD_LAYER_PATH instead of VK_LAYER_PATH
NVIM v0.10.0
Build type: Release
LuaJIT 2.1.1713773202
Run "nvim -V1 -v" for more info

stderr:


Please check your shell configuration.
$SHELL -lc '{bin} -v'
Neovide just crashed :(
This is the error that caused the crash. In case you don't know what to do with this, please feel free to report this on https://github.com/neovide/neovide/issues!

ERROR: Unexpected output from neovim binary:
        /opt/homebrew/bin/nvim -v
stdout: This script is now using VK_ADD_LAYER_PATH instead of VK_LAYER_PATH
NVIM v0.10.0
Build type: Release
LuaJIT 2.1.1713773202
Run "nvim -V1 -v" for more info

stderr:


Please check your shell configuration.
$SHELL -lc '{bin} -v'
```

I am circumventing this by running `neovide` through `bash`:

```
SHELL=/bin/bash neovide $argv 2> /dev/null &
```

However, how can I make a similar fix for the Neovide standalone application? 

**Screenshots**

![Screenshot 2024-06-11 at 11 03 12 AM](https://github.com/neovide/neovide/assets/11932512/a6dd7c37-1e68-403e-badb-c2c8c86a42f8)

**Desktop (please complete the following information):**
 - OS: [e.g. macOS 11.4] macOS Sonoma 14.5
 - Neovide Version [e.g. 0.6.0] 0.13.0
 - Neovim Version [e.g. 0.5.0] 0.10.0

**Comment by fredizzimo** [comment]
I'm not exactly sure where that message comes from. But the environment `VK_ADD_LAYER_PATH` and `VK_LAYER_PATH` comes from the Vulkan SDK.

You need to find the script that outputs "This script is now using VK_ADD_LAYER_PATH instead of VK_LAYER_PATH" when you start a non interactive shell and fix that. Nothing should be printed when the shell is started in a non-interactive mode.

**Comment by qTipTip** [comment]
Ah, thanks! Maybe I have something else conflicting then. I'll investigate and come back to you! :)

**Comment by qTipTip** [comment]
It was indeed an issue with my `fish`-config. I used `bass` (https://github.com/edc/bass) to source the Vulkan SDK environment variables from within fish:

```
bass source /Applications/vulkan/setup-env.sh
```

Uncommenting this solved the issue entirely. Not sure why it didn't manifest itself as an issue until I started using neovide, but it's all good now. Apologies for the noise here!

**Comment by galmeida** [comment]
For reference to help people facing similar issue, on MacOS, Neovide.app will try to evaluate any string produced by your shell configuration during startup, this will cause Neovide.app to crash if the output is not executable. See #2960.

To workaround the issue wrap the output generating configuration in your shell configuration with:

```
[...]
if [ -n "$TTY" ]; then
    <output generating config>
fi
[...]
```
