### ISSUE TITLE
Doesn't work on ubuntu 24.04 with hyprland

### ISSUE THREAD

**Issue by 88srzh** [neovide/neovide#2650]
When try to start neovide.

1. Installed neovide with snap.
2. I'm trying to run it in the console "neovide ".
3. See error "
[wayland-client error] Attempted to dispatch unknown opcode 0 for wl_shm, aborting."

 - OS: Ubuntu 24.04, DE: Hyprland, WM: Sway
 - Neovide 0.8.0
 - Nvim 0.10.0

When run "neovide --log" see error: "thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: GlobError { path: ".", error: Os { code: 13, kind: PermissionDenied, message: "Permission denied" } }', /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/ops/function.rs:150:5".

**Comment by fredizzimo** [comment]
The Snap is unfortunately very out of date, and can likely not be fixed, see
* https://github.com/neovide/neovide/issues/1149

Flatpak support is on the way
* https://github.com/neovide/neovide/pull/2413
* https://github.com/neovide/neovide/pull/2397

But until then I recommend the Appimage, which also has some minor issues
* https://github.com/neovide/neovide/issues/2477
Or the `tar.gz` binary downloaded from the github releases page, which should work

**Comment by 88srzh** [comment]
Thank you. AppImage works.
