### ISSUE TITLE
The font rendering is too wide

### ISSUE THREAD

**Issue by epheien** [neovide/neovide#2653]
<img width="798" alt="Xnip2024-06-13_11-33-20" src="https://github.com/neovide/neovide/assets/3406908/c9ea7517-f2b0-45dc-8bf1-d8a14a5ebf88">

macOS 12.7.5
Font: set guifont=SFMono\ Nerd\ Font:h12

The overall width of the other three neovim fonts after rendering is basically the same, but neovide rendering is too wide, which is unacceptable. This makes it difficult for users who are used to other neovim clients to switch to neovide because the display effect is too different.

**Comment by epheien** [comment]
> Can you provide the output from `neovide --log? I need to know what kind of metrics Neovide detects.

[neovide_rCURRENT.log](https://github.com/user-attachments/files/15816807/neovide_rCURRENT.log)

**Comment by epheien** [comment]
When I run `neovide --log`, I found another problem.
When I run `neovide`, it will create an empty file named `not`.
```
$ ls -l not
ls: cannot access 'not': No such file or directory
$ neovide
2024-06-13 17:19:58.961 neovide[9276:230673] TSM AdjustCapsLockLEDForKeyTransitionHandling - _ISSetPhysicalKeyboardCapsLockLED Inhibit
$ ls -l not
-rw-r--r-- 1 eph staff 6  6 13 17:19 not
```

**Comment by fredizzimo** [comment]
The creation of the `not` file probably has the same underlying cause as thus https://github.com/neovide/neovide/issues/2609. Someone with a mac needs to look at that issue.

And back to the font. When loading the font with https://fontdrop.info/ it shows an em size of 2048 and an average character width of 1266, which is also the same as the advance width for regular ascii characters, so the width multiplier is 0.618164. Which for a font size of 12 pixels and a scale factor of 2.0, that gives a character width of 24 * 0.618164 = 14.835937, the same as the logs show. This matches the width when measuring on the image you posted. For better accuracy, measure several characters and divide by the number of characters.

To me this looks correct, but the other editors/terminal emulators seem to round it down to 14 pixels, giving  a considerably narrower rendering. I guess we need to add an option to render "wrong" the same way. I only have an ipad available myself right now, so it's hard for me to do any comparisions. But can you also compare how the font looks in a proper word processor?

**Comment by epheien** [comment]
> To me this looks correct, but the other editors/terminal emulators seem to round it down to 14 pixels, giving a considerably narrower rendering. I guess we need to add an option to render "wrong" the same way. I only have an ipad available myself right now, so it's hard for me to do any comparisions. But can you also compare how the font looks in a proper word processor?

Sure, could you please explain the specific operating steps.

**Comment by fredizzimo** [comment]
Just the same kind of image comparison with a word processor using the same font and size. I don't know what's available on macOS, but something like Microsoft word or LibreOffice.

**Comment by epheien** [comment]
<img width="989" alt="Xnip2024-06-13_18-02-58" src="https://github.com/neovide/neovide/assets/3406908/30d9f7b4-2319-4cc8-b81f-50264d14818d">


It appears that the display of Neotide is consistent with the pages, but the display effect is not consistent with other popular terminals that have been popular for many years

I think this requires adding an option to maintain display consistency with other terminals

**Comment by fredizzimo** [comment]
Yes, I need an option if we want to do that. I don't think it should be the default since then the font will have more or less spacing depending on the size. I also think that Neovide and pages renders it correctly, but the terminals not due to history. I'm also not sure if this is different on macOS, or if terminals render the same on all platforms.

For now, you can experiment with the font width setting for example `set guifont=SFMono\ Nerd\ Font:h12:w-0.5`
> wX (available since 0.11.2) — Sets the width relative offset to be X points, while X can be again any number. Negative values shift characters closer together, positive values shift them further apart.

**Comment by epheien** [comment]
`set guifont=SFMono\ Nerd\ Font:h12:w-0.84`
After setting it up, the font display width is basically no different from other terminals.
Thanks.

**Comment by epheien** [comment]
set guifont=SFMono\ Nerd\ Font:h12:w-0.84
After setting it up, the font display width is basically no different from other terminals.
Thanks.
