### ISSUE TITLE
Quickly typing space after a symbol in the terminal triggers "delete to start of line"

### ISSUE THREAD

**Issue by dhleong** [neovide/neovide#2658]
**Describe the bug**

A bit strange, but say my `:term` shell input line looks like eg:

```
$ foo bar &|
```

with my cursor at the `|`. If I quickly type `&<space>` then the entire input line gets cleared and I'm at `$` (the prompt)

**To Reproduce**
1. `neovide -- -u NONE` to ensure it's not a plugin thing
2. `:term`
3. Type anything, followed by `&` (or `"` or probably others) then `<space>` in quick succession
4. See that the shell input line (within the shell, not nvim's buffer) has been cleared

**Expected behavior**

I would expect the symbol and a space to be inserted into the terminal input line

**Desktop (please complete the following information):**
 - OS: 14.5
 - Neovide Version: 0.13.1
 - Neovim Version: 0.10.0

**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**

[neovide_rCURRENT.log](https://github.com/user-attachments/files/15858030/neovide_rCURRENT.log)

**Additional context**

I'm using zsh, but I've also spawned bash from within the zsh shell and get the same effect. Feels like something about Neovide's input handling, perhaps? Odd that nothing about this seems to manifest outside of terminal mode, though.

**Comment by fredizzimo** [comment]
You are probably pressing shift+space by accident, and run into this Neovim issue
* https://github.com/neovim/neovim/issues/24093

**Comment by dhleong** [comment]
Hmm you're right! I thought I tried unsuccessfully to reproduce in normal
nvim, but I was able to just now. It does not reproduce in a different nvim
GUI I use (VimR) but they must integrate differently.

Sorry for the noise!
