### ISSUE TITLE
Transparent Background Issue in Neovide on win11

### ISSUE THREAD

**Issue by Minamoto25** [neovide/neovide#2661]
**Describe the bug**
I am experiencing an issue with Neovide where the entire background (except the status line) is transparent. I have tried several themes (tokyonight-dark/day/moon, gruvbox, etc.), but they have no effect on the background transparency. I also attempted to set vim.g.neovide_transparency = 1.0, but it only affects the transparency of the status line.

**To Reproduce**
1. Open Neovide.
2. Install a theme such as tokyonight or gruvbox. (optional)
3. Set vim.g.neovide_transparency = 1.0 in command mode.
4. Observe that the entire background remains transparent except for the status line.

**Expected behavior**
The entire Neovide background should be non-transparent when vim.g.neovide_transparency = 1.0 is set. But only the status line's transparency is affected by vim.g.neovide_transparency = 1.0. The rest of the background remains transparent.

**Screenshots**

![image](https://github.com/neovide/neovide/assets/74601121/33c863fc-7f62-4f3a-8914-0a3923f3ddd1)

![image](https://github.com/neovide/neovide/assets/74601121/76973f61-b7a6-4a61-921a-cfc24c1e121a)

**Desktop (please complete the following information):**
 - OS:  windows 11 23H2
 - Neovide Version: 0.13.1
 - Neovim Version 0.10.0

**Additional context**
This issue does not exist in Neovide version 0.12.0.

**Comment by fredizzimo** [comment]
This looks like almost the opposite of https://github.com/neovide/neovide/issues/2592

Does `neovide -- --clean` behave the same way?
Which graphics card do you have and do you have the latest drivers?

**Comment by Minamoto25** [comment]
> This looks like almost the opposite of #2592
> 
> Does `neovide -- --clean` behave the same way? Which graphics card do you have and do you have the latest drivers? Does `neovide --opengl` work?

When starting the window with neovide --opengl, there is no such issue. After entering neovide --clean, the neovide window does not start, and it outputs this backtrace:
[neovide_backtraces.log](https://github.com/user-attachments/files/15894722/neovide_backtraces.log)

The result of neovide --log is as follows:
[neovide_rCURRENT.log](https://github.com/user-attachments/files/15894723/neovide_rCURRENT.log)

**Comment by fredizzimo** [comment]
The command should be `neovide -- --clean`, notice the extra `--`

Also what is your graphics card, and do you have the latest drivers?

**Comment by Minamoto25** [comment]
> The command should be `neovide -- --clean`, notice the extra `--`
> 
> Also what is your graphics card, and do you have the latest drivers?

My graphics card is an integrated AMD card. After updating the driver, the issue was resolved, and the window launched using 'neovide -- --clean' is also working normally. Thank you for your attention to this issue!
