### ISSUE TITLE
<C-Space> does nothing

### ISSUE THREAD

**Issue by fredizzimo** [neovide/neovide#2669]
### Discussed in https://github.com/neovide/neovide/discussions/2668

<div type='discussions-op-text'>

<sup>Originally posted by **Geobert** June 25, 2024</sup>
Hi, 

I’m beginning my journey with nvim through neovide, on Windows (for now).

I’m using `kickstart` and it has `<C-Space>` mapped to trigger `cmp` but it doesn’t work.
I added another map to test the command and it works, so something is messing around with C-space and I can’t see what :-/
</div>

**Comment by fredizzimo** [comment]
The log shows that `<C-Space>` is received by winit, but for some reason not sent to Neovim

[neovide_rCURRENT.log](https://github.com/user-attachments/files/15987217/neovide_rCURRENT.4.log)

**Comment by fredizzimo** [comment]
I won't be able to fix this myself until earliest the end of next week, but I think the problem is this condition
https://github.com/neovide/neovide/blob/24fcfc94c30775a6ff08277e76d266d2a1bde62c/src/window/keyboard_manager.rs#L301-L308

`None` should also generate `space`, in addition to `" "`, while any other text should not.

**Comment by Geobert** [comment]
I’ll see what I can do as I’m a Rustacean myself :)
