### ISSUE TITLE
LSP on_attach never running in Neovide; runs perfectly with the same config in terminal Neovim

### ISSUE THREAD

**Issue by snoblenet** [neovide/neovide#2670]
**Describe the bug**
The LSP `on_attach` function never runs in Neovide.

It runs perfectly with the same config in terminal Neovim.

Possibly relevant is the fact that when I run `:checkhealth`, I see the following warnings in Neovide but not in terminal Neovim:

```
- WARNING npm: not available
  - ADVICE:
    - spawn: npm failed with exit code 127 and signal 0. env: node: No such file or directory
      
- WARNING node: not available
  - ADVICE:
    - spawn: node failed with exit code - and signal -. node is not executable
```

**To Reproduce**
1. Configure Neovim using LazyVim and the `mason.lua` file pasted below.
2. In Neovide, go to a file for which an LSP server is configured.
3. Using `:LspInfo`, confirm that no LSP server is attached to the buffer.
4. Using the same Neovim configuration and terminal Neovim, visit the same file.
5. Using `:LspInfo`, confirm that the expected LSP server is attached to the buffer.

**Expected behavior**
The expected LSP server attaches to the buffer, even when Neovim is run through Neovide.

Checkhealth results are identical in these two scenarios.

**Desktop (please complete the following information):**
 - Mac OS X 14.5
 - Neovide 0.13.1
 - Neovim v0.10.0

**Please run `neovide [Uploading neovide_rCURRENT.log…]() and paste the contents of the `.log` file created in the current directory here:**

Will attach as file, as Github is complaining about the length of the text in this field.

**Additional context**

mason.lua:
```
return {
  'williamboman/mason.nvim',
  dependencies = {
    'RubixDev/mason-update-all',
    'b0o/schemastore.nvim',
    'folke/which-key.nvim',
    'neovim/nvim-lspconfig',
    'williamboman/mason-lspconfig.nvim',
  },
  config = function()
    -- must call in this order
    require('mason-update-all').setup()
    require('mason').setup()
    require('mason-lspconfig').setup({
      automatic_installation = true,
      ensure_installed = {
        'bashls',
        'cssls',
        'diagnosticls',
        'docker_compose_language_service',
        'dockerls',
        -- 'eslint',
        'graphql',
        'html',
        'jsonls',
        'lemminx',
        'lua_ls',
        'marksman',
        'prismals',
        'rnix',
        'sqlls',
        'tailwindcss',
        'taplo',
        'terraformls',
        'tsserver',
        'yamlls',
      },
    })

    local on_attach = function(client, bufnr)
      -- FIXME: need to always return valid directory
      vim.api.nvim_set_current_dir(
        -- client.config.root_dir or '/Users/steven/code/'
        client.config.root_dir
      )
      client.server_capabilities.semanticTokensProvider = false

      vim.api.nvim_buf_set_option(bufnr, 'omnifunc', 'v:lua.vim.lsp.omnifunc')
      vim.cmd([[command! LspRename lua vim.lsp.buf.rename()]])
    end

    local capabilities = vim.lsp.protocol.make_client_capabilities()
    capabilities.textDocument.completion.completionItem.commitCharactersSupport
    = true
    capabilities.textDocument.completion.completionItem.deprecatedSupport = true
    capabilities.textDocument.completion.completionItem.insertReplaceSupport =
      true
    capabilities.textDocument.completion.completionItem.labelDetailsSupport =
      true
    capabilities.textDocument.completion.completionItem.preselectSupport = true
    capabilities.textDocument.completion.completionItem.tagSupport = {
      valueSet = { 1 },
    }

    capabilities.textDocument.completion.completionItem.documentationFormat =
      { 'markdown', 'plaintext' }

    capabilities.textDocument.completion.completionItem.resolveSupport = {
      properties = { 'additionalTextEdits', 'detail', 'documentation' },
    }

    capabilities.textDocument.semanticHighlighting = false

    capabilities = require('cmp_nvim_lsp').default_capabilities(capabilities)

    local flags = {
      allow_incremental_sync = true,
      debounce_text_changes = 150,
    }

    local orig_util_open_floating_preview = vim.lsp.util.open_floating_preview

    function vim.lsp.util.open_floating_preview(contents, syntax, opts, ...)
      opts = opts or {}
      opts.border = 'double'
      return orig_util_open_floating_preview(contents, syntax, opts, ...)
    end

    -- must be called after all the mason stuff
    local nvim_lsp = require('lspconfig')
    require('mason-lspconfig').setup_handlers({
      function(
      server_name -- default handler (optional)
      )
        nvim_lsp[server_name].setup({
          capabilities = capabilities,
          on_attach = on_attach,
          flags = flags,
        })
      end,
      jsonls = function()
        nvim_lsp.jsonls.setup({
          capabilities = capabilities,
          on_attach = on_attach,
          flags = flags,
          settings = {
            json = {
              schemas = require('schemastore').json.schemas(),
              validate = { enable = true },
            },
          },
        })
      end,
      lua_ls = function()
        nvim_lsp.lua_ls.setup({
          capabilities = capabilities,
          on_attach = on_attach,
          flags = flags,
          single_file_support = true,
          settings = {
            Lua = {
              workspace = {
                checkThirdParty = false,
                ignoreDir = '/Users/steven/code/dotfiles/nvim/local-share-nvim',
                maxPreload = 100000,
                preloadFileSize = 100000,
              },
              diagnostics = {
                globals = { 'bufnr', 'hs', 'use', 'vim' },
              },
            },
            ['$schema'] = 'https://raw.githubusercontent.com/sumneko/vscode-lua/master/setting/schema.json',
          },
        })
      end,
    })
  end,
}

```

**Comment by snoblenet** [comment]
I think the issue might have something do with me using `fnm` in my shell to manage node and NPM versions.

For which, `which node` may yield something like `/Users/steven/.local/state/fnm_multishells/53121_1719404461615/bin/node`.

I've tried adding `vim.env.PATH = "/opt/homebrew:" .. "/Users/steven/.local:" .. vim.env.PATH` to my `init.lua`, but it does not work.

I am looking for a way I can require Neovim.app to source my normal ZSH startup files regardless of how I start the app.

**Comment by fredizzimo** [comment]
The reason for this is that Neovide does not launch an interactive shell, which means that some of the shell configuration scripts are not sourced.

Given that you are on macOS, you are probably using zsh, and configure the path to node in `.zshrc`, which is only for interactive shells. To make it work with non interactive shells you can put the path configuration in `.zprofile`. `.zshenv` would be the best place, since it is meant for environment variables, but macOS does it's own thing https://apple.stackexchange.com/questions/432226/homebrew-path-set-in-zshenv-is-overridden...

We do have a faq entry for this, but I think it needs to be improved with a better explanation, and cover all shells https://neovide.dev/faq.html#neovide-is-not-picking-up-some-shell-configured-information

**Comment by snoblenet** [comment]
got it working by adding this to `/etc/zprofile`:

```
eval "$(/opt/homebrew/bin/fnm env)"
eval "$(/opt/homebrew/bin/brew shellenv)"
```

**Comment by snoblenet** [comment]
got it working by adding this to /etc/zprofile:

eval "$(/opt/homebrew/bin/fnm env)"
eval "$(/opt/homebrew/bin/brew shellenv)"

**Comment by fredizzimo** [comment]
It should be enough to modify your user `~/.zprofile`, but you might have to create the file if it doesn't exist.

If not, then something is probably still messed up with this 
* https://github.com/neovide/neovide/pull/2587
* https://github.com/neovide/neovide/issues/2407

It is supposed to login the user before starting the non-interactive shell, when launched from the finder, and that should source the correct file. This has went through many iterations of fixing, and unfortunately I dom't own a mac to help with debugging and fixing it properly.

**Comment by snoblenet** [comment]
I've pasted a working solution below that I think might be better?

Did you want to add it to the docs?

```
vim.api.nvim_create_autocmd(
  { 'VimEnter' },
  {
    callback = function()
      local handle = io.popen('eval "$(/opt/homebrew/bin/brew shellenv)"; eval "$(fnm env)"; env')
      if handle == nil then return end
      local env_vars = handle:read("*a")
      if env_vars == nil then return end
        
      for line in env_vars:gmatch("[^\r\n]+") do
        local key, value = line:match("([^=]+)=(.*)")
        if key == nil then return end
        if value == nil then return end
        vim.env[key] = value
      end

      handle:close()
    end
  }
)

```

**Comment by fredizzimo** [comment]
I think `~/.zprofile` is better and the correct fix, and if it does not work, we need to find a way to fix it. It also follows the advice you see in places like this https://unix.stackexchange.com/questions/71253/what-should-shouldnt-go-in-zshenv-zshrc-zlogin-zprofile-zlogout

zsh itself recommend `~/.zshenv`, but as mentioned before Apple did not read the documentation.

**Comment by fredizzimo** [comment]
Here's a detailed description of the macOS specific problem with `.zshenv` and `path-helper` https://gist.github.com/thiagoserra/9744e8637f4778e836d6eb60d7a33eb3

Note that `.zshrc` is always the wrong place to set environment variables on all platforms.

**Comment by Kethku** [comment]
Closing as I think a solution has been suggested. Feel free to reopen if you disagree
