### ISSUE TITLE
Loading environment variables

### ISSUE THREAD

**Issue by rakanalh** [neovide/neovide#2673]
**Describe the bug**
When launching neovide directly, neovide doesn't seem to load environment variables needed for specific use cases.

For example, using a GPG key for authenticating on Github (for use inside Neovim / Neovide with Neogit), `SSH_AUTH_SOCK` should be known inside NeoVide for Neogit to fetch repository updates. 

When launching Neovide from terminal (Where the environment variable `SSH_AUTH_SOCK` is set), there is no problem using Neogit for fetching upstream.

Is there a way to let Neovide read specific environment variables such as `SSH_AUTH_SOCK`?

**To Reproduce**
1. Launch neovide from your launcher (i use `rofi`)
2. Try to fetch origin using Neogit
3. See error

**Expected behavior**
Neovide should read `SSH_AUTH_SOCK` and make it available for neovim plugins.

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - neovide 0.13.1
 - NVIM v0.10.0

**Comment by fredizzimo** [comment]
This is essentially the same issue as another one that was opened very recently with an active discussion. But there has been many other ones as well. We need to do a better job with our FAQ.
* https://github.com/neovide/neovide/issues/2670

So, I'm closing this
