### ISSUE TITLE
cannot use <Ctrl-Shift-V> to paste in lazygit on windows

### ISSUE THREAD

**Issue by konosubakonoakua** [neovide/neovide#2680]
**Describe the bug**

**To Reproduce**
open neovide
open lazygit in term
paste something in lazygit prompt

**Expected behavior**
paste successfully

**Screenshots**

**Desktop (please complete the following information):**
 - OS: win
 - Neovide Version latest
 - Neovim Version 0.10.0

**Additional context**
https://github.com/jesseduffield/lazygit/issues/3381

**Comment by fredizzimo** [comment]
There's a similar issue for Astronvim, but as far as I know the bug only happens with remote connections.
* https://github.com/neovide/neovide/issues/2613

**Comment by konosubakonoakua** [comment]
> There's a similar issue for Astronvim, but as far as I know the bug only happens with remote connections.
> 
> * [System clipboard not work when using with Astronvim #2613](https://github.com/neovide/neovide/issues/2613)

neovide interacts well with system clipboard in buffer, I can paste by `p`, It goes wrong only when I open a floating window which running a term with lazygit

**Comment by fredizzimo** [comment]
In that case, it sounds like you are missing a key mapping. In the terminal, the terminal emulator maps ´<C-Shift-V>`, but neither Neovim or Neovide does it automatically.

Our dokumentation, is unfortunately incomplete in this regard, and I, don't have a computer to test with right now that it works, but I think we will end up recommending something like this

```lua
vim.keymap.set(
    {'n', 'v', 's', 'x', 'o', 'i', 'l', 'c', 't'},
    '<C-S-v>',
    function() vim.api.nvim_paste(vim.fn.getreg('+'), true, -1) end,
    { noremap = true, silent = true }
)```

Taken from this comment https://github.com/neovide/neovide/issues/1263#issuecomment-1972013043, and adapted for Windows. If that mapping does not work

Also check out https://github.com/neovide/neovide/pull/2101.

**Comment by konosubakonoakua** [comment]
works like a charm, thank you
