### ISSUE TITLE
add neovide's tabs (like wezterm)

### ISSUE THREAD

**Issue by erlangparasu** [neovide/neovide#2688]
**Is your feature request related to a problem? Please describe.**
add neovide's tabs (like wezterm)

**Describe the solution you'd like**
add neovide's tabs (like wezterm)

**Describe alternatives you've considered**
.

**Additional context**
.

**Comment by erlangparasu** [comment]
in wezterm, there is option to render Tabs as text

https://wezfurlong.org/wezterm/config/lua/config/use_fancy_tab_bar.html
set it to `false`

**Comment by erlangparasu** [comment]
https://github.com/neovide/neovide/issues/1623

**Comment by fredizzimo** [comment]
Yes, I'm closing this as a duplicate of:
* #1623
