### ISSUE TITLE
Nonsense: Cursor animation options for pacman

### ISSUE THREAD

**Issue by MultisampledNight** [neovide/neovide#2694]
**Is your feature request related to a problem? Please describe.**
I am frustrated when I cannot see pacman in my editor. (this line is a joke)

**Describe the solution you'd like**
Configuration options for introducing pacman into Neovide:

- A boolean option which lets backspace (or even delete movements in general?) turn the cursor into pacman and eat the last character.
- Additional cursor vfx mode where the path consisting out of dots is quickly faded in, with the cursor turning into pacman and quickly eating them all.

**Describe alternatives you've considered**
No pacman. Which would be completely fine but sad.

**Additional context**
Not sure if the naming "pacman" is too confusable with the package manager of [Arch Linux](https://archlinux.org)

**Comment by Kethku** [comment]
As amusing as this is, I don't think its really a serious issue that needs cycles. Would be fun as a plugin though
