### ISSUE TITLE
[macOS] version numbers broken in 13.2

### ISSUE THREAD

**Issue by core-code** [neovide/neovide#2712]
the latest version 13.2 identifies itself as being version 0.11.2 and as being built in september 2023 (yes 23).

both the CFBundleVersion and the CFBundleShortVersionString entries in the Info.plist file are broken/wrong.

<img width="658" alt="Screenshot 2024-07-14 at 20 37 59" src="https://github.com/user-attachments/assets/a36d3132-200c-48ef-a035-4c8a84e27b77">
<img width="267" alt="Screenshot 2024-07-14 at 20 37 47" src="https://github.com/user-attachments/assets/c150d6e8-a4d2-4725-b724-b1b6e7ec5c29">

**Comment by eelcocramer** [comment]
Code signature also does not match.

**Comment by eelcocramer** [comment]
If I checkout the source for this version and change the version string in the [Info.plist](https://github.com/neovide/neovide/blob/f56145238570e9e3134a8d7d43144690661f62d0/extra/osx/Neovide.app/Contents/Info.plist#L22) from `0.11.2` to `0.13.2` and then build and install it using the `macos-builder` script the application install fine and runs without the code signature error I'm getting when I'm installing using the homebrew tap (`brew install homebrew/cask/neovide`).

**Comment by fredizzimo** [comment]
This has been fixed in the latest 0.13.3 release. 

For signature error, see these:
* https://github.com/neovide/neovide/issues/1479
* https://github.com/neovide/neovide/issues/1373
* https://github.com/neovide/neovide/issues/1998

Basically, we need someone to buy or sponsor a macOS developer license and sign each release.

**Comment by eelcocramer** [comment]
Thanks.

Strangely the previous version was block bij MacOS based upon the signature but this version open without a problem even though it is un-notarised.
