### ISSUE TITLE
Neovide crashes instantly when I try to start Neovide and neovim together in debug mode

### ISSUE THREAD

**Issue by snoblenet** [neovide/neovide#2718]
**Describe the bug**
In an attempt to diagnose and fix frequent Neovide freezes that occur usually a few minutes after starting Neovide with `open -g -a Neovide`, I am trying to simultaneously start Neovide and nvim in debug mode. However, when I do this, Neovide crashes instantly.

**To Reproduce**
1. Open a ZSH shell
2. type `neovide --fork --log --no-vsync --no-multigrid --neovim-bin '/opt/homebrew/bin/nvim' -- -V20neovim.log`
3. See error shown in screenshots below
4. See two files written

```sh
$cat neovim.log
Executing: echo has('nvim-0.10.0')
1
Writing ShaDa file "/Users/steven/.local/state/nvim/shada/main.shada"
```

```s
$cat neovide_rCURRENT.log
TRACE [neovide] Neovide version: 0.13.3
DEBUG [neovide::settings::window_size] Loaded window settings: Maximized { grid_size: Some(260x35) }
DEBUG [neovide::bridge::command] Starting neovim with: Command { std: "/opt/homebrew/bin/nvim" "--embed" "-V20neovim.log", kill_on_drop: false }
ERROR [neovide::error_handling] Neovide just crashed :(
This is the error that caused the crash. In case you don't know what to do with this, please feel free to report this on https://github.com/neovide/neovide/issues!

Neovide requires nvim version 0.10.0 or higher. Download the latest version here https://github.com/neovim/neovim/wiki/Installing-Neovim

```

**Expected behavior**
I expect Neovide and neovim to both start.

(I am not fussy about the values for WSL, vsync, multi-grid, etc and will happily adopt whichever settings are most likely to stop Neovide from freezing.)

**Screenshots**
![image](https://github.com/user-attachments/assets/30b86304-36e4-46ee-bab1-2c4961e2475d)

![image](https://github.com/user-attachments/assets/dc380c3e-7820-448a-95e0-af4225f85396)

**Desktop (please complete the following information):**
 - Mac OS 14.5
 - nvim v0.10.0
 - neovide 0.13.3

**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**

File attached not pasted due to length: [neovide_rCURRENT.log](https://github.com/user-attachments/files/16295756/neovide_rCURRENT.log)

**Comment by fredizzimo** [comment]
This seems like a Neovim bug, I changed the code here https://github.com/neovide/neovide/blob/9f71253300ddcc55cee036c7663162bc65dbbc28/src/bridge/mod.rs#L83-L93

To this:

```rust
    match session
        .neovim
        .command_output(&format!("echo has('nvim-{NEOVIM_REQUIRED_VERSION}')"))
        .await
        .as_deref()
    {
        Ok("1") => {} // This is just a guard
        Ok("0") =>  bail!("Neovide requires nvim version {NEOVIM_REQUIRED_VERSION} or higher. Download the latest version here https://github.com/neovim/neovim/wiki/Installing-Neovim"),
        Ok(response) => bail!("Unexpected response from echo has('nvim-{NEOVIM_REQUIRED_VERSION}'): {response}"),
        Err(err) => bail!("Neovim returned an error {err}")
    }
```
And it prints
```
Unexpected response from echo has('nvim-0.10.0'): Executing: echo has('nvim-0.10.0')
1
```

So Neovim is adding an extra `Executing: echo has('nvim-0.10.0')` to the command output. This does not happen with the output inside Neovim itself.

The code could probably be changed to use a lua api call instead. But I don't have time to do it right now.

**Comment by fredizzimo** [comment]
There seems to be a problem with the filename of the log if you change it from `-V20neovim.log` to `-Vneovim.log` it works. 

I also found out that `nvim -V20neovim.log` does not write a log file at all, while `-Vneovim.log` does.

**Comment by fredizzimo** [comment]
`-V14neovim.log` is the highest one that works.

**Comment by snoblenet** [comment]
Thanks. Changing it 14 worked. All of which makes [this](https://neovim.io/doc/user/starting.html#:~:text=file%7D.%0A%09%09Example%3A-,nvim%20%2DV20vimlog,-%2DD) very strange indead.
