### ISSUE TITLE
OpenGL BadAttribute on startup

### ISSUE THREAD

**Issue by kentslaney** [neovide/neovide#2722]
**Describe the bug**
Neovide panics and crashes. I assume because the process can't create an OpenGL context when there's a Driver/library version mismatch. 

**To Reproduce**
1. Upgrade NVIDIA drivers
2. Procrastinate restarting machine
3. Attempt to open Neovide

**Expected behavior**
I suppose STDERR shouldn't tell me to report the bug given it's an upstream problem? Not sure there's a more graceful way to fail in this case. 

**Desktop (please complete the following information):**
 - OS: Arch on Linux `6.9.7-zen1-1-zen`
 - Neovide 0.13.3-2

**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**
```
2024-07-21 22:57:32 - Neovide panicked with the message 'Failed to create OpenGL context: Error { raw_code: Some(2), raw_os_message: Some("BadValue (integer parameter out of range for operation)"), kind: BadAttribute }'. (File: src/renderer/opengl.rs; Line: 99, Column: 14)
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: <unknown>
  14: __libc_start_main
  15: <unknown>
```

**Additional context**
```
$ nvidia-smi
Failed to initialize NVML: Driver/library version mismatch
NVML library version: 555.58
```

**Comment by Kethku** [comment]
Does this issue contain after restarting or w/e? I'm not sure theres a reasonable solution on our side here, but I will leave this open in case others run into it. Seems pretty infrequent to spend many cycles on

**Comment by kentslaney** [comment]
No issues after reboot, I think I was just surprised by the way it failed. I haven't experienced this issue since and looking back it does seem pretty minor.

**Comment by fredizzimo** [comment]
Unfortunately, the Glutin libary that we use provide very little information of what's going wrong.  There's not much we can do other than to report the line it failed on so that it can be debugged further. Usually with `glxinfo`, `eglinfo` or `nvidia-smi`.

So, closing this.
