### ISSUE TITLE
use neovide GUI a few hours later, neovide memory usage increased from around 200M to 4GB

### ISSUE THREAD

**Issue by sunchong-gogo** [neovide/neovide#2729]
I open a project used by neovide and I worked for few hours（many files in project）， I fond the neovide became very slowly（mouse move and cursor move very slowly）。
When I opened the windows resource manage and I find neovide used 4GB memory。

win11 professional edition 23H2
neovide version：0.13.2

**Comment by fredizzimo** [comment]
We do have a similar report on Linux in our discord channel. But personally, I have not seen it.

It's also unclear if it's the Neovide process itself or if it's some subprocess like a language server that's using the memory. Finally, there could be some plugin that's causing it, if that's the case the exact one needs to be identified.

It's for example possible that some plugin opens a lot of windows and leave them hidden. 

It's very hard to do anything more from my side, without further information and debugging by someone that can repeat the problem.

**Comment by Kethku** [comment]
Closing for lack of response

**Comment by Kethku** [comment]
Please reopen if you have more details, such as confirmation if the inner processes such as language servers or similar are the actual culprit or not
