### ISSUE TITLE
Jumping cursor in cmdline (noice.nvim plugin)

### ISSUE THREAD

**Issue by xbladesub** [neovide/neovide#2735]
I've updated from 0.11.2 to 0.13.3 - cursor is jumping. Is ther any way to fix?

https://github.com/user-attachments/assets/7d224ecb-2411-4068-ae68-1882019dad19

config: 

```lua
	-- g.neovide_profiver = true
	g.neovide_hide_mouse_when_typing = true
	g.neovide_refresh_rate = is_mac_mini and 60 or 120
	-- g.neovide_transparency = 0.99
	g.neovide_cursor_vfx_mode = "wireframe"
	g.neovide_cursor_antialiasing = true
	g.neovide_no_idle = true
	g.neovide_floating_blur = true
	g.neovide_floating_blur_amount_x = 3.0
	g.neovide_floating_blur_amount_y = 3.0
	g.neovide_cursor_trail_size = 0.75
	g.neovide_cursor_unfocused_outline_width = 0.125
	g.neovide_cursor_animate_in_insert_mode = true
	g.neovide_cursor_animate_command_line = true
	g.neovide_background_color = ""
```

neovide start script:

```bash
#!/bin/bash

NEOVIDE_SERVICE="Neovide"
BUILD_FROM_SOURCE_APP_PATH="/Users/nshv/Repos/neovide/neovide-main/target/release/bundle/osx/Neovide.app"
HOMEBREW_APP_PATH="/Applications/Neovide.app"

if pgrep -f "$NEOVIDE_SERVICE" >/dev/null
then
	open "$BUILD_FROM_SOURCE_APP_PATH"
	# open "$HOMEBREW_APP_PATH"
else
	export LUNARVIM_RUNTIME_DIR="${LUNARVIM_RUNTIME_DIR:-"$HOME/.local/share/lunarvim"}"
	export LUNARVIM_CONFIG_DIR="${LUNARVIM_CONFIG_DIR:-"$HOME/.config/lvim"}"
	export LUNARVIM_CACHE_DIR="${LUNARVIM_CACHE_DIR:-"$HOME/.cache/lvim"}"
	export LUNARVIM_BASE_DIR="${LUNARVIM_BASE_DIR:-"$HOME/.local/share/lunarvim/lvim"}"

	export NEOVIM_BIN="/Users/nshv/.local/share/bob/nvim-bin/nvim"
	export NEOVIDE_FRAME="none"
	export NEOVIDE_MULTIGRID="true"
	export NEOVIDE_VSYNC="false"
	# export NEOVIDE_IDLE="false"

	cd $HOME

	exec "$BUILD_FROM_SOURCE_APP_PATH/Contents/MacOS/neovide" --log -- -u "$LUNARVIM_BASE_DIR/init.lua" "$@"
	# exec "$HOMEBREW_APP_PATH/Contents/MacOS/neovide" -- -u "$LUNARVIM_RUNTIME_DIR/lvim/init.lua" "$@"
fi

```

**Comment by fredizzimo** [comment]
This bug should be reported to `noice.nvim`. This recent change https://github.com/folke/noice.nvim/commit/1698725a663aca56bcd07a0e405bc441a5f6613b, causes Neovim to send two cursor positions in quick succession. In terminal neovim that's not a problem, since the movement is so fast that the flicker might not even be noticeable. But for Neovide it's a problem.

Reverting Noice to 4.4.7 fixes the problem.

Here's the part of the Neovide log that demonstrates the problem, first it sends the cursor to grid 2, then flushes, which tells Neovide that state is valid, so we start animating the cursor there. Then we receive another cursor movement back to the command line.
```
TRACE [neovide::channel_utils] neovim_handler WindowViewport { grid: 18, top_line: 0.0, bottom_line: 1.0, current_line: 0.0, current_column: 4.0, line_count: Some(1.0), scroll_delta: Some(0.0) }
TRACE [neovide::channel_utils] neovim_handler CursorGoto { grid: 2, row: 0, column: 4 }
TRACE [neovide::channel_utils] neovim_handler Flush
TRACE [neovide::bridge::handler] Neovim notification: "redraw"
TRACE [neovide::channel_utils] neovim_handler CursorGoto { grid: 18, row: 0, column: 4 }
TRACE [neovide::channel_utils] neovim_handler Flush
```

**Comment by fredizzimo** [comment]
Probably this code
```lua
   vim.schedule_wrap(function()
      if not Util.is_search() then
        if vim.api.nvim__redraw then
          vim.api.nvim__redraw({ flush = true, cursor = true })
        else
          vim.cmd.redraw()
        end
      end
      Cmdline.fix_cursor()
    end)
```

Which looks like it will redraw with a flush and then fix the cursor, which causes the second flush.

**Comment by fredizzimo** [comment]
Even if this is a noice bug, I think, we could potentially fix this and some other spurious cursor movements on the Neovide side, if someone wants to work on it.

We could introduce debouncing as mentioned in this comment https://github.com/neovide/neovide/issues/2516#issuecomment-2084817481, that would replace our current hack which was introduced in https://github.com/neovide/neovide/pull/753, and only deals with sporadic jumps to the command line.

But there are also some Neovim work in progress PRs for that will remove some of that, so the debouncing might become obsolete almost immediately after implemented:
* https://github.com/neovim/neovim/pull/29446
* https://github.com/neovim/neovim/pull/29447

**Comment by xavier7179** [comment]
I think the bug is still happening. I have installed the following commit (with `lazy.nvim`) 0427460 and it is still behaving the way you describe it.
