### ISSUE TITLE
Having information in title bar to tell multiple instances appart

### ISSUE THREAD

**Issue by Geobert** [neovide/neovide#2736]
**Is your feature request related to a problem? Please describe.**
When having multiple instances of neovide, it’s hard to tell them appart to select the correct one

**Describe the solution you'd like**
Possibility to put infos like root dir, current file in the title bar would be usefull to identify different instances

**Describe alternatives you've considered**
None

**Comment by fredizzimo** [comment]
This is already possible and built-in Neovim:
https://neovim.io/doc/user/options.html#'titlestring'

**Comment by Geobert** [comment]
Oh indeed, thanks!
