### ISSUE TITLE
Neovide with WSL interferes with corporate proxy

### ISSUE THREAD

**Issue by IC3P3** [neovide/neovide#2748]
**Describe the bug**

When trying to use Neovim with Neovide behind a corporate proxy, it doesn't work or might not work the first time. This does not apply if you run Neovim through a terminal emulator. The tested plugins that failed when using them were Lazy.nvim and mason.nvim.

When running Lazy.nvim it sometimes fails while installing a plugin. However you can try installing it again and it might work. When using mason.nvim, it can't get the Github data at all. Both of these problem do not occur when just running Neovim in WSL without Neovide in Windows.

**To Reproduce**

1. Add Lazy.nvim and mason.nvim to the nvim config
2. Start Neovide using `neovide --wsl` behind a corporate proxy

**Expected behavior**

When running Neovide the behavior should match the one using only Neovim and install the plugins normally.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. macOS 11.4] Windows 11 Pro 23H2 with WSL 2.2.4.0 and Fedora 40
 - Neovide Version [e.g. 0.6.0]  0.13.3
 - Neovim Version [e.g. 0.5.0] 0.10.1

**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**

[neovide_rCURRENT.log](https://github.com/user-attachments/files/16492801/neovide_rCURRENT.log)

**Additional context**

**Comment by fredizzimo** [comment]
I'm using Neovide on Windows inside WSL behind a corporate proxy, so it's not a generic problem.

I guess your problem is that you define the proxy environment variables in the wrong configuration file. Neovide is run using a non-interactive login shell, which means that `.bashrc`, or `.zshrc` for example are not run. So instead, you should define the environment variables in `.bash_profile` or `.zprofile`

**Comment by fredizzimo** [comment]
Glad that it worked, but it's a bit strange that it didn't work from /etc/environment. I will check why that's the case at some point. Maybe WSL is doing something strange?
