### ISSUE TITLE
Compress release assets

### ISSUE THREAD

**Issue by adrian5** [neovide/neovide#275]
I think it would be nice to offer compressed release assets as seen e.g. with [neovim](https://github.com/neovim/neovim/releases) → Assets.

If it would suit your workflow, I could create a PR to add compression for Win (Zip), MacOS (Zip), Linux (XZ) to the CI pipeline. But I don't know how you currently handle releases – do you download the artifacts manually, and then upload them as release assets, or does GitHub allow you to reference them directly when creating a release?

Unlike release assets, CI artifacts get zipped automaticaly when downloaded (even if they're compressed already), which is a bit confusing.

**Comment by Kethku** [comment]
So I have been uncompressing the ci assets manually and uploading the uncompressed versions... I don't really know why I've been doing that other than just thats what I've always done.

Can you talk a bit about why you want them compressed? I figured that for most people the extra download size was worth the ability to just drop it wherever and run it right away

**Comment by adrian5** [comment]
I guess it's mostly inertia. When something offered for download can be compressed significantly, I always make sure to do that. But maybe that thinking is becoming outdated in the time of ubiquitous broadband and CDNs.

Personally, I would definitely do it in this case, but it's your call. The only other argument I can give is that the Linux executable would be easier to recognize then, instead of by exclusion (the one that isn't .app nor .exe).

---

On a related note: I take it a decision against stripping debug symbols was made to allow better feedback from users during development?

**Comment by Kethku** [comment]
I think that is the case, but I can't remember. We do have logging, and for most people it is easy enough to build from scratch if they have the wherewithal to actually use the debug symbols... I will think about it and probably make the change to remove the symbols in published builds. Thanks for the suggestion

**Comment by Kethku** [comment]
This is fixed
