### ISSUE TITLE
Neovide is transparent by default

### ISSUE THREAD

**Issue by sharpchen** [neovide/neovide#2752]
**Describe the bug**
Fresh installed neovide looks transparent.
If I set `vim.g.neovide_transparency` to less than 1, it gets more transparent.
So it seems transparency is working but didn't work as expexted. Did I miss any other neovim specific config?

**To Reproduce**
```lua
if vim.g.neovide then
  vim.o.guifont = 'JetBrainsMono Nerd Font'
  vim.opt.linespace = 0

  vim.g.neovide_padding_top = 0
  vim.g.neovide_padding_bottom = 0
  vim.g.neovide_padding_right = 0
  vim.g.neovide_padding_left = 0
  vim.g.neovide_transparency = 1
end
```

**Screenshots**
![image](https://github.com/user-attachments/assets/fd6d13dc-d6b4-4f56-8cf6-57d5425f2fab)

**Desktop (please complete the following information):**
 - OS: Windows10
 - Neovide: 0.13.3
 - Neovim: 0.10.0

**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**
[neovide_rCURRENT.log](https://github.com/user-attachments/files/16532468/neovide_rCURRENT.log)

**Comment by fredizzimo** [comment]
This has been reported before and was caused by outdated graphics drivers. Could you post your current graphics card spec and driver versions, so that we have some reference? And then update the drivers to see if it fixes the problem.

**Comment by sharpchen** [comment]
```
GPU - AMD Radeon(TM) Graphics - Primary/Integrated
Graphics Card Manufacturer - Powered by AMD
Graphics Chipset - AMD Radeon(TM) Graphics
OpenGL® API Version - 4.6
OpenCL™ API Version - 2.0
Software Version - 10.20.10028.0
Driver Version - 20.10.28.10-201119a-362226C-Lenovo
Provider - Advanced Micro Devices, Inc.
2D Driver Version - 8.1.1.1634
Direct3D® Version - 9.14.10.01443
OpenGL® Version - 26.20.11000.13596
AMD Audio Driver Version - 10.0.1.16
Vulkan™ Driver Version - 2.0.137
Vulkan™ API Version - 1.2.133
Windows Version - Windows 10 (64 bit)
```

Updating drivers did solve the problem, thanks!

**Comment by sharpchen** [comment]
Neovide now crashes when moving cursors for certain times after I updated the drivers.

```
APU - AMD Radeon(TM) Graphics - Primary/Integrated
Graphics - AMD Radeon(TM) Graphics
Graphics Manufacturer - Powered by AMD
APU - AMD Radeon(TM) Graphics - Primary/Integrated
VRAM - 512 MB - DDR4 1333 MHz
Driver Version - 23.19.16-240618a-405470C-AMD-Software-Adrenalin-Edition
AMD Windows Driver Version - 31.0.21916.2
Direct3D API Version - 12.1
Vulkan™ API Version - 1.3.260
OpenCL™ API Version - 2.0
OpenGL® API Version - 4.6
Direct3D® Driver Version - 9.14.10.01526
Vulkan™ Driver Version - 2.0.279
OpenCL® Driver Version - 31.0.21916.2
OpenGL® Driver Version - 24.06.230729_569461f
2D Driver Version - 8.1.1.1634
2D Driver File Path - /REGISTRY/MACHINE/SYSTEM/CurrentControlSet/Control/Class/{4d36e968-e325-11ce-bfc1-08002be10318}/0000
Driver Provider - Advanced Micro Devices, Inc.
Windows Edition - Windows 10 CoreCountrySpecific (64 bit)
Windows Version - 22H2
```
Should I open a new issue?

[neovide_rCURRENT.log](https://github.com/user-attachments/files/16566006/neovide_rCURRENT.log)

**Comment by fredizzimo** [comment]
Yes, open a new issue, and check if you have a neovide_backtrackes.log file.
