### ISSUE TITLE
Buffers are opened automatically when Neovide is launched

### ISSUE THREAD

**Issue by xbladesub** [neovide/neovide#2758]
I've updated to `0.13.3` from `0.11`

Build from source

I run neovide with following script:
```sh
#!/bin/bash

NEOVIDE_SERVICE="Neovide"
APP_PATH="/Users/nshv/Repos/neovide/neovide-main/target/release/bundle/osx/Neovide.app"

if pgrep -f "$NEOVIDE_SERVICE" >/dev/null
then
	open "$APP_PATH"
else
	export LUNARVIM_RUNTIME_DIR="${LUNARVIM_RUNTIME_DIR:-"$HOME/.local/share/lunarvim"}"
	export LUNARVIM_CONFIG_DIR="${LUNARVIM_CONFIG_DIR:-"$HOME/.config/lvim"}"
	export LUNARVIM_CACHE_DIR="${LUNARVIM_CACHE_DIR:-"$HOME/.cache/lvim"}"
	export LUNARVIM_BASE_DIR="${LUNARVIM_BASE_DIR:-"$HOME/.local/share/lunarvim/lvim"}"

	export NEOVIM_BIN="/Users/nshv/.local/share/bob/nvim-bin/nvim"
	export NEOVIDE_FRAME="none"
	export NEOVIDE_MULTIGRID="true"
	export NEOVIDE_VSYNC="false"
	# export NEOVIDE_IDLE="false"

	cd $HOME

	exec "$APP_PATH/Contents/MacOS/neovide" --log -- -u "$LUNARVIM_BASE_DIR/init.lua" "$@"
fi
```

When I launch Neovide it opens with 2 buffers in vertical split (terminal and my keymaps.lua, have no idea why does it happen and why these particular buffers). Before update I saw dashboard wtih my snippets. How to find exact issue why these 2 extra buffers are being opened?

**Comment by fredizzimo** [comment]
Is this on macOS.

The technical explanation why it happens can be found here https://github.com/neovide/neovide/issues/2609#issuecomment-2148227966. But someone on macOS needs to implement and test a workaround.

**Comment by xbladesub** [comment]
> Is this on macOS?
> 
> The technical explanation why it happens can be found here [#2609 (comment)](https://github.com/neovide/neovide/issues/2609#issuecomment-2148227966). But someone on macOS needs to implement and test a workaround.

yes, it's macos

**Comment by xbladesub** [comment]
I found the issue - it was related to broken autosession plugin. (But still had to add `--no-tabs` to prevent init.lua from being opened)
