### ISSUE TITLE
Cursor color is linked to the wrong ('Normal') highlight group

### ISSUE THREAD

**Issue by n00bmind** [neovide/neovide#2771]
**Describe the bug**
As explained in the title, the color of the cursor seems to be linked to the 'Normal' highlight group instead of 'Cursor', meaning I cannot have the cursor be a different color to the non-highlighted text.
I found this previous bug https://github.com/neovide/neovide/issues/1611 which, amazingly, was closed without an actual fix being provided.

**To Reproduce**
1. Set some highlight group for the cursor i.e. `hi Cursor guifg=#000000 guibg=#B80000`
2. Type `:hi Cursor` in the command line to check that the new highlight group values were applied correctly
3. Observe the cursor color hasn't changed
4. Repeat a similar change but for the 'Normal' highlight group
5. Observe the cursor color now does change

**Expected behavior**
The cursor color should be linked to its dedicated highlight group ('Cursor')

**Screenshots**
![image](https://github.com/user-attachments/assets/c83fc696-2c8b-4fa2-b3de-bbc6c1666998)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Neovide Version 0.12.2
 - Neovim Version 0.9.5

**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**
[neovide_rCURRENT.log](https://github.com/user-attachments/files/16719754/neovide_rCURRENT.log)

**Comment by fredizzimo** [comment]
If this is a bug, then it's a Neovim one, because this is the information it sends to us
```
TRACE [neovide::channel_utils] neovim_handler ModeInfoSet { cursor_modes: [CursorMode { shape: Some(Block), style_id: Some(0), cell_percentage: Some(0.0), blinkwait: Some(0), blinkon: Some(0), blinkoff: Some(0) }, CursorMode { shape: Some(Block), style_id: Some(0), cell_percentage: Some(0.0), blinkwait: Some(0), blinkon: Some(0), blinkoff: Some(0) }, CursorMode { shape: Some(Vertical), style_id: Some(0), cell_percentage: Some(0.25), blinkwait: Some(0), blinkon: Some(0), blinkoff: Some(0) }, CursorMode { shape: Some(Horizontal), style_id: Some(0), cell_percentage: Some(0.2), blinkwait: Some(0), blinkon: Some(0), blinkoff: Some(0) }, CursorMode { shape: Some(Block), style_id: Some(0), cell_percentage: Some(0.0), blinkwait: Some(0), blinkon: Some(0), blinkoff: Some(0) }, CursorMode { shape: Some(Vertical), style_id: Some(0), cell_percentage: Some(0.25), blinkwait: Some(0), blinkon: Some(0), blinkoff: Some(0) }, CursorMode { shape: Some(Horizontal), style_id: Some(0), cell_percentage: Some(0.2), blinkwait: Some(0), blinkon: Some(0), blinkoff: Some(0) }, CursorMode { shape: Some(Horizontal), style_id: Some(0), cell_percentage: Some(0.2), blinkwait: Some(0), blinkon: Some(0), blinkoff: Some(0) }, CursorMode { shape: Some(Vertical), style_id: Some(0), cell_percentage: Some(0.25), blinkwait: Some(0), blinkon: Some(0), blinkoff: Some(0) }, CursorMode { shape: None, style_id: None, cell_percentage: None, blinkwait: None, blinkon: None, blinkoff: None }, CursorMode { shape: None, style_id: None, cell_percentage: None, blinkwait: None, blinkon: None, blinkoff: None }, CursorMode { shape: None, style_id: None, cell_percentage: None, blinkwait: None, blinkon: None, blinkoff: None }, CursorMode { shape: None, style_id: None, cell_percentage: None, blinkwait: None, blinkon: None, blinkoff: None }, CursorMode { shape: None, style_id: None, cell_percentage: None, blinkwait: None, blinkon: None, blinkoff: None }, CursorMode { shape: None, style_id: None, cell_percentage: None, blinkwait: None, blinkon: None, blinkoff: None }, CursorMode { shape: None, style_id: None, cell_percentage: None, blinkwait: None, blinkon: None, blinkoff: None }, CursorMode { shape: Some(Block), style_id: Some(0), cell_percentage: Some(0.0), blinkwait: Some(0), blinkon: Some(0), blinkoff: Some(0) }] }
```
And this is the documentation for `mode_info_set` https://neovim.io/doc/user/ui.html#ui-global
> When attr_id is 0, the background and foreground colors should be swapped

The background and foreground colors refer to the default colors (Normal highlight) group here. At least that's how we interpret it, but it could technically refer to the inverse colors of the current cell, and for that we have an open feature request https://github.com/neovim/neovim/issues/24803

So that's the default that Neovim sends it, and I actually don't think it's a bug. The default `guicursor` is `n-v-c-sm:block,i-ci-ve:ver25,r-cr-o:hor20`, which does not specify any highlight groups , so you need to set it yourself, if you want to use some other highlight group, like `Cursor`, you can set it like this `n-v-c-sm:block-Cursor,i-ci-ve:ver25-Cursor,r-cr-o:hor20-Cursor`
https://neovim.io/doc/user/options.html#'guicursor'.

**Comment by n00bmind** [comment]
I see. Very interesting, based on your comment I just realised that Neovim decided to change the default for `guicursor`, but I couldnt see mention of this anywhere until I compared the documentation for that option in both Vim & Neovim:

Vim:
```
'guicursor' 'gcr'	string	(default "n-v-c:block-Cursor/lCursor,
					ve:ver35-Cursor,
					o:hor50-Cursor,
					i-ci:ver25-Cursor/lCursor,
					r-cr:hor20-Cursor/lCursor,
					sm:block-Cursor
					-blinkwait175-blinkoff150-blinkon175",
```

Neovim:
```
'guicursor' 'gcr'	string	(default "n-v-c-sm:block,i-ci-ve:ver25,r-cr-o:hor20")
```

I got to say that's one misleading default..

Anyway, I can confirm this works after setting the highlight group in `guicursor` again!

**Comment by fredizzimo** [comment]
That was done here https://github.com/neovim/neovim/pull/6588, based on this issue https://github.com/neovim/neovim/issues/6577
