### ISSUE TITLE
Can't drag files to OSX anymore

### ISSUE THREAD

**Issue by 9mm** [neovide/neovide#2776]
hey hey

I just pulled and built and I notice I can no longer drag files to OSX. I'm not sure if extra steps were required to do this now?

<img width="325" alt="image" src="https://github.com/user-attachments/assets/dfe3d97c-1f6d-4124-9f48-f7e19a6b38be">

**Comment by falcucci** [comment]
It's probably https://github.com/neovide/neovide/pull/2768

can you give more details to replicate?

**Comment by 9mm** [comment]
Sure, sorry I didnt do that originally was just right in middle of lots of stuff when it happened but didn't want to forget.

1. I run this command to install and bundle latest master:

```
  cd ~/Code/neovide \
    && cargo install --path . \
    && rm -rf ~/Code/neovide/target/aarch64-apple-darwin \
    && rm -rf ~/.cargo/bin/Neovide.app \
    && ./macos-builder/run aarch64-apple-darwin \
    && mv ~/Code/neovide/target/aarch64-apple-darwin/release/bundle/osx/Neovide.app ~/.cargo/bin/ \
    && open ~/.cargo/bin/
```

Then I drag Neovide.app into my dock. 

From there, I dragged an SVG icon into the icon and it gave the error.

However, I notice it really happens with any file type (even code source files)

I know when I originally added that feature I think it had to do with the plist fields, but I don't remember now

**Comment by 9mm** [comment]
```
NVIM v0.10.1
Build type: Release
LuaJIT 2.1.1724512491
Run "nvim -V1 -v" for more info
```

```
macOS 14.6.1 (23G93)
```

**Comment by falcucci** [comment]
Sure, thank you.

I'll try to simulate it later today and check what is the root

**Comment by fredizzimo** [comment]
Does the image produced by the CI work? https://github.com/neovide/neovide/actions/runs/10532240735

**Comment by 9mm** [comment]
Hmmm... that actually does appear to work. Is there some extra bundle step above that my script isnt doing properly?

Or actually... is there just a command that bundles directly? I know it used to be cargo bundle but i thought that crate got replaced so i started doing it manually

**Comment by fredizzimo** [comment]
I don't know, but the builder does this
https://github.com/neovide/neovide/blob/8ed544a54446a91747cdb1092d81216affcc0a3f/.github/workflows/build.yml#L173-L227

So 
```
cargo build --locked --release --target=aarch64-apple-darwin
./macos-builder/run aarch64-apple-darwin
```

**Comment by 9mm** [comment]
Hmm very interesting, so i run both those commands and it produces this:

<img width="432" alt="image" src="https://github.com/user-attachments/assets/8f782b39-b23c-401f-a9a4-894cb297d81f">

Ive tried both the floating .app that gets created, as well as the app inside the dmg, and both have the same error when attempting to drag a file in

**Comment by falcucci** [comment]
@9mm I can confirm that doing a rollback on https://github.com/neovide/neovide/pull/2768 it works as expected. I'll investigate a bit more but also consider a rollback.

**Comment by crupest** [comment]
@falcucci Thanks for informing me.

I'm sorry I didn't cover the test of this when I made the commit. And I didn't follow bugs here for a long time.

The problem is caused by I moved the place of registering `NSApplicationDelegate`. It is too late to set the delegate in my codes and it does not make effects then. I have reverted this part and fix it in #2782. Please have a review and a test again! Thanks very much. Sorry for the bug.

**Comment by falcucci** [comment]
@crupest all good! bug happens, 

I'll arrive soon at home and then I check and merge if everything is fine.

thank you for the quick fix

**Comment by 9mm** [comment]
Thanks @crupest and @falcucci !

**Comment by 9mm** [comment]
hey @crupest so i am 90% sure this didnt happen before, and now it does. I can double check later by rebuilding again, but just really quick... is this behavior something youd expect from your recent change?

when i open neovim from my project folder it opens 2 tabs, with one of them being named the folder name

<img width="376" alt="image" src="https://github.com/user-attachments/assets/f2afd4a1-45ba-40b6-8934-d0bc003573c5">

This is whats in my `n` binary, and shows how im usually opening things.

```
export NEOVIDE_FORK=1
export NEOVIDE_FRAME=buttonless
export NEOVIDE_TITLE_HIDDEN=1
export NEOVIDE_VSYNC=0

neovide_bin="/Users/zesty/.cargo/bin/neovide" # "/opt/homebrew/bin/neovide"

current_dir=$(pwd)

if [ -z "$1" ]; then
  if [ "$current_dir" = "$HOME" ]; then
    $neovide_bin -- -c ":cd ~/Desktop"
  else
    $neovide_bin -- -c ":cd $current_dir"
  fi
else
  if [ -d "$1" ]; then
    $neovide_bin -- -c ":cd $1"
  else
    $neovide_bin "$@"
  fi
fi
```

**Comment by 9mm** [comment]
Its this command basically:

```
neovide -- -c 'cd ~/Desktop'
```

it doesnt seem like its changing the current directory, its actually trying to open it or something?

**Comment by 9mm** [comment]
I just deleted all plugins, re-pulled from master and run this from terminal and its same thing

```
./target/release/neovide -- -c 'cd ~/Desktop'
```

<img width="292" alt="image" src="https://github.com/user-attachments/assets/c484d51a-e7a7-4050-9bd3-813d6101070b">

**Comment by 9mm** [comment]
ill do some more testing, give me a bit

**Comment by 9mm** [comment]
it looks like this changed long ago....... not sure when as its strange i just noticed it now. maybe it was some kind of neovim change or something 🤔  i definitely would have noticed this as its super annoying. i went back like 6 months and it still doesnt occur on neovide far back.

Is there a way i can open to a current working directory? 

this works:

```
nvim -c 'cd ~/Desktop'
```

but this does not:

```
neovide -- -c 'cd ~/Desktop'
```

**Comment by falcucci** [comment]
@9mm I think [this](https://github.com/neovide/neovide/discussions/2781#discussioncomment-10551290) can help you as a temporary fix and get involved about the root problem.
