### ISSUE TITLE
No `.desktop` file after installing with `cargo install --git`

### ISSUE THREAD

**Issue by Tompouce-onGit** [neovide/neovide#2783]
**Describe the bug**
When installing Neovide on Debian 12 with the command `cargo install --git https://github.com/neovide/neovide`, no `.desktop` file is available after the installation. I tried to add an item to XFCE's panel to launch Neovide, but was unable to.

**To Reproduce**
1. On Debian 12, install Neovide with `cargo install --git https://github.com/neovide/neovide`.
2. In a terminal, run the commands `sudo updatedb` and `locate neovide.desktop`.
3. `locate` only finds a desktop entry file under `~/.cargo/git/checkouts/`.

**Expected behavior**
I expected to find Neovide in my window manager's application launcher, and to be able to put a Neovide icon in the tray to launch it quickly.

**Screenshots**
![Screenshot_2024-09-07_19-10-18](https://github.com/user-attachments/assets/b1834920-f089-4548-9c79-1eb09f98ef00)
![Screenshot_2024-09-07_19-15-23](https://github.com/user-attachments/assets/f26e8b81-3dde-483e-a9dd-435ab3d25024)

**Desktop (please complete the following information):**
 - OS: Debian 12 (Bookworm)
 - Neovide Version: 0.13.3
 - Neovim Version: 0.10.1
 - Cargo Version: 1.81.0

**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**
I don't think this is applicable here.

**Additional context**
I used this installation method since Debian doesn't ship Neovide, and neither is Neovide available on Crates.io. Everything else works like a charm, and its only this minor issue which bugs me and puzzles me, since I can see that there is in fact a `neovide.desktop` file in the `assets` directory of the github repo.

**Comment by agraven** [comment]
`cargo install` only ever installs the binary of a crate. If you want to install neovide via cargo, you will have to do the rest of the setup yourself

**Comment by Tompouce-onGit** [comment]
Ah right, I didn't know that, but I suppose I suspected it given the situation. Thanks for the clarification.

**Comment by willwillsiii** [comment]
I've written a short script to handle this here: https://github.com/neovide/neovide/issues/1403#issuecomment-2418070752
