### ISSUE TITLE
Download for MacOS links to missing file

### ISSUE THREAD

**Issue by andreas-wilm** [neovide/neovide#2788]
The "Download for MacOS" button on the website links to a non-existing file

1. Go to https://neovide.dev/
2. Click on 'download for MacOS'

Results in 'not found

The link goes to https://github.com/neovide/neovide/releases/download/0.13.3/neovide.dmg.zip which doesn't exist. Should either link to `https://github.com/neovide/neovide/releases/download/0.13.3/Neovide-x86_64-apple-darwin.dmg` or just `https://github.com/neovide/neovide/releases/download/0.13.3/`

**Comment by Kethku** [comment]
I will address this

**Comment by Kethku** [comment]
Updated to point to the arm build. Thanks for the report
