### ISSUE TITLE
Neovide opening two unexpected buffers on startup after update to 0.13.3

### ISSUE THREAD

**Issue by xbladesub** [neovide/neovide#2793]
Hey! I’m running into a bit of a strange issue, and I’m not sure if it’s Neovide, Lunarvim, or something in between.

I use Neovide with Lunarvim, and after updating to 0.13.3, two random buffers automatically open up on startup for no clear reason. I can’t figure out what’s causing this, and it didn’t happen before the update (I was on the improve-render-loop branch before). Here’s a screenshot of what it looks like:

<img width="1512" alt="image" src="https://github.com/user-attachments/assets/0ea1e6f6-6112-44bb-bfd6-37cc28fa03de">

Here’s the shell script I’m using to run Neovide:

```sh
#!/bin/bash

NEOVIDE_SERVICE="Neovide"
APP_PATH="/Users/nshv/Repos/neovide/neovide-main/target/release/bundle/osx/Neovide.app"

if pgrep -f "$NEOVIDE_SERVICE" >/dev/null
then
	open "$APP_PATH"
else
	export LUNARVIM_RUNTIME_DIR="${LUNARVIM_RUNTIME_DIR:-"$HOME/.local/share/lunarvim"}"
	export LUNARVIM_CONFIG_DIR="${LUNARVIM_CONFIG_DIR:-"$HOME/.config/lvim"}"
	export LUNARVIM_CACHE_DIR="${LUNARVIM_CACHE_DIR:-"$HOME/.cache/lvim"}"
	export LUNARVIM_BASE_DIR="${LUNARVIM_BASE_DIR:-"$HOME/.local/share/lunarvim/lvim"}"

	export NEOVIM_BIN="/Users/nshv/.local/share/bob/nvim-bin/nvim"
	export NEOVIDE_FRAME="none"
	export NEOVIDE_MULTIGRID="true"
	export NEOVIDE_VSYNC="false"
	# export NEOVIDE_IDLE="false"

	cd $HOME

	exec "$APP_PATH/Contents/MacOS/neovide" --log -- -u "$LUNARVIM_BASE_DIR/init.lua" "$@"
```

Any idea what might be causing this? (Can't find anything useful in Neovide logs). It wasn’t an issue before I updated. Appreciate any help or suggestions!

**Comment by fredizzimo** [comment]
This is related to 
* https://github.com/neovide/neovide/issues/2609

I know that @crupest has been looking at some of these issues, so tagging here for awareness.
