### ISSUE TITLE
Mouse wheel scrolling not working

### ISSUE THREAD

**Issue by rubin55** [neovide/neovide#2801]
**Describe the bug**
When trying to scroll in for example Lazy's popup or Nvchads cheatsheet, it doesn't scroll. It works in regular nvim on terminal. It looks like the focus of scroll stays on the background.

**To Reproduce**
1. Do Lazy sync on terminal + nvim
2. Observe the Lazy popup window scrolls when pulling the mouse wheel
3. Do Lazy sync in neovide
4. See background scrolling, but not the Lazy popup

**Expected behavior**
I expect the popup window to scroll (to have focus?) Like it does on terminal.

**Videos**
[nvim-vs-neovide-scrolling.webm](https://github.com/user-attachments/assets/aa6cb356-6aef-4895-92d4-0388dd240730)

**Desktop (please complete the following information):**
 - OS: Arch Linux /w kernel 6.10.10
 - Neovide Version 0.13.3
 - Neovim Version 0.10.1

**Comment by fredizzimo** [comment]
That's a bit strange for me the mouse scrolls properly in the lazy window. Can you provide a log file from `neovide --log`?

But there are some rather big problems with the mouse handling, which unfortunately needs fixing on the Neovim side:
* https://github.com/neovide/neovide/issues/2226
* https://github.com/neovide/neovide/issues/2749
* https://github.com/neovim/neovim/issues/27181

**Comment by rubin55** [comment]
Hi @fredizzimo sure, here is the log. I made this log whilst doing exactly the actions you see in the video. By the way, If you would like to reproduce with my config, it's at https://github.com/rubin55/dotfiles/tree/master/.config/nvim (and https://github.com/rubin55/dotfiles/tree/master/.config/neovide)

Neovide log: [neovide.log](https://github.com/user-attachments/files/17083555/neovide.log)

**Comment by fredizzimo** [comment]
Thanks, now I see what's missing from the report, you are running with `--no-multigrid` in you `config.toml`. 

The bug will be simple to fix. We need to pass `grid_id: 0` when not using multigrid, like the documentation says https://neovim.io/doc/user/api.html#nvim_input_mouse(). 

This is done for the mouse click and movement, but for some reason, it's been left out from the scroll wheel events.

**Comment by fredizzimo** [comment]
* https://github.com/neovide/neovide/pull/2805 should fix the issue
