### ISSUE TITLE
Can't type Vietnamese in Neovide

### ISSUE THREAD

**Issue by DwcksDinh** [neovide/neovide#2809]
**Describe the bug**
I can't type Vietnamese in Neovide but i can paste and view Vietnamese in it.

**To Reproduce**
1. Go to neovide
2. Type Vietnamese in neovide
3. It doesn't show Vietnamese

**Expected behavior**
Can type Vietnamese

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Neovide:  0.13.3
 - Neovim: 0.10.1

**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**
[neovide_rCURRENT.log](https://github.com/user-attachments/files/17091550/neovide_rCURRENT.log)

**Comment by fredizzimo** [comment]
Are you using a the default vietnames keyboard layout or a third party IME?

Also make sure that you have IME enabled https://neovide.dev/configuration.html?highlight=ime#ime.

I'm not sure what the problem could be at the moment, other languages that need IME have been reported to work fine.

**Comment by DwcksDinh** [comment]
thank you so much i finally fix that

**Comment by fredizzimo** [comment]
Can you tell what you did, so that other people that finds this issue knows?

**Comment by DwcksDinh** [comment]
It's my fault man, i don't turn on IME on my neovide:

```
vim.g.neovide_input_ime = true
```
