### ISSUE TITLE
Dashboard not shown automatically when neovim loads

### ISSUE THREAD

**Issue by LittleHendrix** [neovide/neovide#2829]
**Describe the bug**
Starting neovim normally and expect to be greeted by dashboard. However, seeing the 'new' empty buffer. Checking in `:Lazy` indicates that `dashboard-nvim` is loaded. 

I have set up a fresh instance of neovim to test this in isolation without any other custom opts, plugins, .etc.  

**To Reproduce**
1. run `nvim` in terminal to initiate

**Expected behavior**
Dashboard loaded automatically

**Screenshots**
Empty buffer on first load
![image](https://github.com/user-attachments/assets/edf553da-9470-4d94-ab50-13410445376b)
Lazy UI indicates `dashboard-nvim` loaded successfully
![image](https://github.com/user-attachments/assets/6503d9a8-a673-49a2-aba0-129c97664cb4)
Dashboard appears _only_ after manually triggered via cmd e.g. `:Dashboard`
![image](https://github.com/user-attachments/assets/f2e3549a-02a0-4e05-b4f6-75a5d08d8c7b)
![image](https://github.com/user-attachments/assets/8f730222-67cf-402f-8a42-c457e25d7f06)
Project structure (root)
![image](https://github.com/user-attachments/assets/7f96552f-ab05-45be-88d4-fd4780f1eecf)
`init.lua`
![image](https://github.com/user-attachments/assets/ba1abf95-16df-4c5b-aff8-7d3e2846ad9d)
`config/lazy.lua` (no modification)
![image](https://github.com/user-attachments/assets/f7161abc-5adb-44d2-9941-978293c3d7f8)
`plugins/dashboard-nvim.lua` (_only_ set theme)
![image](https://github.com/user-attachments/assets/d4d8e420-7046-4cfc-8bc3-2917b897f1ed)

 

**Desktop (please complete the following information):**
 - OS: [e.g. macOS 14.6.1]
 - Neovide Version [e.g. 0.6.0]
 - Neovim Version [e.g. 0.10.2]

**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**

**Additional context**
`dashboard-nvim` is the _only_ plugin installed in a fresh neovim instance, isolated by NVIM_APPNAME i.e. `NVIM_APPNAME=my-nvim nvim`

**Comment by Kejoko** [comment]
I'm running into the same issue. Do you recall what you did to fix this?

**Comment by LittleHendrix** [comment]
@Kejoko Sorry, I can't recall exactly what I did, it's been so long. But I've since switched to Snacks.nvim, which also has a dashboard, and a bunch of other useful (small) plugins. Which does not have this issue.
