### ISSUE TITLE
AppImage not recognizing Ubuntu 24.04 neovim (snap package)

### ISSUE THREAD

**Issue by Rmano** [neovide/neovide#2842]
First of all, thanks for the nice software. I enjoy it on my home Manjaro system, but at work I can't use any rolling distro... 😐

In Ubuntu 24.04, `neovim` is offered as a snap. Seriously thinking about switching sistro for good, but...

It seems that the neovide AppImage is not able to cope with this.  (`nvim-qt` more or less can, apart from a weird error on startup).

**Steps to reproduce the behavior**

I installed `neovim` via Ubuntu software app (notice: the debian-packaged neovim is *way* out-of-date). Result: 

```bash
nvim --version
NVIM v0.10.2
Build type: RelWithDebInfo
LuaJIT 2.1.1713484068
Run "nvim -V1 -v" for more info
```

Downloaded the AppImage (today, v. 0.13.3). Made it executable, and then

```bash
./neovide.AppImage       
ERROR [neovide::error_handling] Neovide just crashed :(
This is the error that caused the crash. In case you don't know what to do with this, please feel free to report this on https://github.com/neovide/neovide/issues!

Neovide requires nvim version 0.10.0 or higher. Download the latest version here https://github.com/neovim/neovim/wiki/Installing-Neovim
Neovide just crashed :(
This is the error that caused the crash. In case you don't know what to do with this, please feel free to report this on https://github.com/neovide/neovide/issues!

Neovide requires nvim version 0.10.0 or higher. Download the latest version here https://github.com/neovim/neovim/wiki/Installing-Neovim
```

**Desktop**

 - OS: Ubuntu 24.40.1, Wayland & XWayland, gnome-shell 46.0 
 ```bash
% inxi -G   
Graphics:
  Device-1: Intel Raptor Lake-S GT1 [UHD Graphics 770] driver: i915 v: kernel
  Device-2: AMD Navi 24 [Radeon RX 6400/6500 XT/6500M] driver: amdgpu
    v: kernel
  Device-3: Logitech B525 HD Webcam driver: snd-usb-audio,uvcvideo type: USB
  Display: wayland server: X.Org v: 23.2.6 with: Xwayland v: 23.2.6
    compositor: gnome-shell v: 46.0 driver: dri: radeonsi gpu: amdgpu
    resolution: 1: 2560x1440~60Hz 2: 2560x1440~60Hz
  API: EGL v: 1.5 drivers: iris,radeonsi,swrast
    platforms: wayland,x11,surfaceless,device
  API: OpenGL v: 4.6 compat-v: 4.5 vendor: amd mesa v: 24.0.9-0ubuntu0.2
    renderer: AMD Radeon RX 6400 (radeonsi navi24 LLVM 17.0.6 DRM 3.57
    6.8.0-45-generic)
```

 - Neovide Version 0.13.3 (AppImage)
 - Neovim Version 0.10.2 (Snap'd)

**Log output**

```bash
% cat neovide_rCURRENT.log
TRACE [neovide] Neovide version: 0.13.3
DEBUG [neovide::bridge::command] Starting neovim with: Command { std: "/usr/bin/nvim" "--embed" "-p", kill_on_drop: false }
ERROR [neovide::error_handling] Neovide just crashed :(
This is the error that caused the crash. In case you don't know what to do with this, please feel free to report this on https://github.com/neovide/neovide/issues!

Neovide requires nvim version 0.10.0 or higher. Download the latest version here https://github.com/neovim/neovim/wiki/Installing-Neovim
```

I tried to run `nvim --embed -p` from the command line, it just sit there --- no errors.

**Comment by fredizzimo** [comment]
Hm.. the following works for me `./neovide.AppImage --neovim-bin /snap/bin/nvim` on Arch Linux. I also tried modifying the path to give priority to the `/snap/bin` and that worked too. I checked with `:checkhealth` that it indeed loaded the snap. 

I can see this in your log output
`DEBUG [neovide::bridge::command] Starting neovim with: Command { std: "/usr/bin/nvim" "--embed" "-p", kill_on_drop: false }`, which indicates that it finds the non snap version of nvim for some reason. Make sure that you path is configured correctly, or use `--neovim-bin`, like I did. You can also, configure it through the config file https://neovide.dev/config-file.html

**Comment by Rmano** [comment]
Ok --- using `./neovide.AppImage --neovim-bin /snap/bin/nvim` works!

The problem was that I had installed the `nvim-qt` package, and that pulled the packages `nvim`, which is old (NVIM v0.9.5). 

I am starting to feel a bit fed up with this move to snap packages... ;-) 

Thanks and sorry for the noise.

**Comment by Rmano** [comment]
> You can also, configure it through the config file https://neovide.dev/config-file.html

Additional question: is it possible to have conditional content (say, on hostname or checking for the existence of a binary) in the config file? I keep my configuration file shared across several machines, and that comes often handy....
