### ISSUE TITLE
Ctrl-; (Control-Semicolon)

### ISSUE THREAD

**Issue by highghlow** [neovide/neovide#2845]
**Is your feature request related to a problem? Please describe.**
As someone who uses `jkl;` instead of `jhkl` for navigation it's really important to have access to the `C-;` keybinding, which is not available in neovide (and most terminals). I was able to fix it in regular neovim by mapping Ctrl-; to `0x7777` in alacritty, but neovide doesn't provide similar functionality.

**Describe the solution you'd like**
Add support for the `C-;` keybinding.

**Describe alternatives you've considered**
Add a way to remap key-combos to ascii characters before they reach neovim.

**Additional context**
Here's the alacritty config responsible for my remapping:
```toml
[[keyboard.bindings]]
chars = "\u7777"
key = ";"
mods = "Control"
```

**Comment by fredizzimo** [comment]
You should be able to map <C-;> directly, on which platform does that not work?

**Comment by highghlow** [comment]
> You should be able to map <C-;> directly

Oh, for some reason I didn't check that
