### ISSUE TITLE
Float border on neovide disjointed

### ISSUE THREAD

**Issue by soullessness1611** [neovide/neovide#2848]
**Describe the bug**
float border on neovide disjointed

**To Reproduce**
1. Go to ' neovide --no-multigrid'
2. when popup float window  such as telescope or lsp completion popup includeing noice popup

**Expected behavior**
use telescope  or when popud float window'

**Screenshots**
Neovim
![ภาพ](https://github.com/user-attachments/assets/c7c911b0-3522-4a17-9ce2-ce8ff47ce0f6)
Neovide
![ภาพ](https://github.com/user-attachments/assets/b46e8f6e-3d6d-42e1-a577-81f1a5f2d4b8)

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Neovide Version 0.13.3
 - Neovim Version 0.10.2

**Comment by falcucci** [comment]
It seems you have a different linespace for neovide or the font line height is slightly lower in your terminal.

you can define it using this example to check 

```
set linespace=0
```

**Comment by soullessness1611** [comment]
> It seems you have a different linespace for neovide or the line height is slightly lower in your terminal.
> 
> you can define it using this example to check
> 
> ```
> set linespace=0
> ```

Thank you very much for support me.

Your solution it worked. I already fixed it.

![2024-10-26_16-20](https://github.com/user-attachments/assets/bebb800f-6ec5-4043-a54a-198374fbafd6)

**Comment by falcucci** [comment]
@soullessness1611 great to hear that, we are welcome :)
