### ISSUE TITLE
Never get any command line output

### ISSUE THREAD

**Issue by Drllap** [neovide/neovide#2849]
**Describe the bug**
I don't get expected output when running neovide from terminal.

**To Reproduce**
1. Open terminal
2. Run `neovide --help`
3. No output
4. Run `neovide --version`
5. No output

**Expected behavior**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Neovide Version 0.13.1 (I think)
 - Neovim Version v0.10.2

**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**
[neovide_rCURRENT.log](https://github.com/user-attachments/files/17476410/neovide_rCURRENT.log)

**Comment by fredizzimo** [comment]
This should be fixed in Neovide 0.13.2 and newer by
* https://github.com/neovide/neovide/pull/2621

**Comment by Drllap** [comment]
Can confirm, fixed in v0.13.3
