### ISSUE TITLE
Maintaining neovide snap

### ISSUE THREAD

**Issue by alex-ramanau** [neovide/neovide#2852]
Hey, dear `neovide` mainteiners!

Are you interested in maintaining [neovide snap ](https://snapcraft.io/neovide) ? 

`poscat` requested to transfer responsibility from `j4qfrost` on https://forum.snapcraft.io/t/request-for-taking-over-the-ownership-of-the-snap-neovide/43573, what do you think about this transfer?

Thank you!

**Comment by falcucci** [comment]
@alex-ramanau thank you for the heads up!

cc @fredizzimo since you are on linux as-well, I guess we could maintain it ourselves?

**Comment by fredizzimo** [comment]
I replied in the thread on snapcraft.io.
