### ISSUE TITLE
Neovide takes 10+ seconds to open a file from sshfs+sftp

### ISSUE THREAD

**Issue by nnra6864** [neovide/neovide#2885]
**Describe the bug**
When using neovide/neovim with the kickstarter config, it takes 10+ seconds to load a file from sshfs+sftp.
Using an empty config or vi/vim resolves the issue fully, but that's obviously not an option since I need the config for a smoother workflow.
My full nvim config can be found [here](https://github.com/nnra6864/kickstart.nvim/tree/d312bc57ecbc401d8d2354971c2d6025bf5b4569).
It's important to mention that nv is not the only thing struggling tho.
Fish shell is extremely unresponsive(takes 3+ seconds to od ls and then move onto the next command), dolphin loads files for ages etc.
It's also important to mention that bash and another editor, Zed, work flawlessly.
I am able to open the entire mounted directory with it and have a seamless working experience, like instantaneous opening of files, no lag and just smoothness ig.
Some people suggested that this is an issue with git status and stuff but I don't think so.
I disabled the only git related plugin I have in nvim and it made no difference whatsoever.
I also tried commenting out the entire lsp section which did help a lot(got from ~10s to ~3s), but still nowhere near the no config experience.
I would really appreciate your help and thanks in advance!

**To Reproduce**
1. Mount an sftp directory with sshfs, e.g. `sshfs -p 2022 qyccad8e.8a6d4158@ger-h67.vibegames.net:/ ~/sftp`
2. Try doing anything with it, be it nvim, `ls` with fish in like a 3rd sub dir, etc.

**Expected behavior**
I would expect it to work smoothly, as it does in bash/vim/zed.

**Screenshots**
I don't think a screenshot would do much here tbh.

**Desktop (please complete the following information):**
Arch+Hyprland with all the git packages.

**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**
I am not sure how I would log this, let me know and I'll update the post with a log.

**Additional context**
Just keep in mind that nvim/nv are not the only laggy things, that might help w debugging a bit.

**Comment by falcucci** [comment]
it was aligned with @nnra6864 that we are moving this issue to neovim or even fish itself since this still happens out of the neovide context.
