### ISSUE TITLE
Cursor blink settings not working as expected

### ISSUE THREAD

**Issue by theherk** [neovide/neovide#2898]
**Describe the bug**

Cursor blink settings don't seem to work. Other guicursor settings do, like shape, but not blinking.

**To Reproduce**

1. Open with `neovide -- -u NONE`
2. `set guicursor=n:block-blinkon100,i:ver25-blinkon100`.
3. `lua vim.g.neovide_cursor_smooth_blink = true`.

**Expected behavior**

I expect the cursor to be a block in normal mode and a pipe in visual mode. This works. I also expect the cursor to blink in both cases. This works in neovim, but not in neovide.

**Desktop (please complete the following information):**

 - OS: [macOS 15.2]
 - Neovide Version [0.13.3]
 - Neovim Version [0.10.2]

**Additional context**

I would attach the log as requested, but even this minimal interaction generation 16k lines, so github won't let me. If anybody would like to see it, where would you prefer I post it?

**Comment by fredizzimo** [comment]
It works if you set the full guicursor, like this
`set guicursor=n:block-blinkwait100-blinkon100-blinkoff100,i:ver25-blinkwait100-blinkon100-blinkoff100`

Actually, I think the terminal doesn't follow the specification, it clearly says that blinking should be disabled when one number is set to zero.
https://neovim.io/doc/user/options.html#'guicursor'

> Default is "block" for each mode. blinkwait{N}[cursor-blinking](https://neovim.io/doc/user/options.html#cursor-blinking)
blinkon{N} blinkoff{N} blink times for cursor: blinkwait is the delay before the cursor starts blinking, blinkon is the time that the cursor is shown and blinkoff is the time that the cursor is not shown. Times are in msec. **When one of the numbers is zero, there is no blinking**

In any case, it's unclear what the other values should be set to when only `blinkon` is set. The terminal, at least Alacritty does not seem to respect the numerical value at all.

I think we could open a Neovim issue about this, if you think that it should work with only `blinkon` set.

**Comment by theherk** [comment]
Super. Let's see what they say. Thank you for the follow up. I'll try this setting.

**Comment by theherk** [comment]
Actually, yes this does work. No problem. Thank you again.
