### ISSUE TITLE
Panic when using fzf to jump to older files after updating to the latest HEAD on MacOs

### ISSUE THREAD

**Issue by SergoGansta777** [neovide/neovide#2910]
**Describe the bug**
After updating LazyVim to the latest HEAD (most recent commits), I encountered a panic when trying to use the feature that allows me to jump to older files using fzf. This feature worked perfectly before the update. Strange but if I use other fzf funcitonal like go to file or search something in LazyVim it works/

In terminal after that i can see that:
```
2024-12-25 20:46:35.548 neovide[14660:67285] +[IMKClient subclass]: chose IMKClient_Modern
2024-12-25 20:46:35.548 neovide[14660:67285] +[IMKInputSession subclass]: chose IMKInputSession_Modern
2024-12-25 20:46:36.610 neovide[14660:67285] TSM AdjustCapsLockLEDForKeyTransitionHandling - _ISSetPhysicalKeyboardCapsLockLED Inhibit
Neovide panicked with the message 'attempt to calculate the remainder with a divisor of zero'. (File: src/utils/ring_buffer.rs; Line: 89, Column: 38)
This is a bug and we would love for it to be reported to https://github.com/neovide/neovide/issues
```

**To Reproduce**
	1.	Install the latest HEAD of neovide (latest commits).
	2.	Open LazyVim and use fzf to jump to an older file.
	3.	The panic occurs when trying to open the file.

**Expected behavior**
Float window opens like before

**Log**
[neovide_backtraces.log](https://github.com/user-attachments/files/18246852/neovide_backtraces.log)

**Additional context**
<img width="480" alt="Shottr 2024-12-25 20 56 01" src="https://github.com/user-attachments/assets/ba3641a8-8ce1-4e43-a702-b3ca2e22b3ac" />

Additionally, the statusline appears to be cut off or truncated. Both issues were not present before updating.

**Comment by fredizzimo** [comment]
This will be fixed by
* https://github.com/neovide/neovide/pull/2913
* https://github.com/neovide/neovide/pull/2912
