### ISSUE TITLE
Potentially add neovide AppImage to releases

### ISSUE THREAD

**Issue by binyomen** [neovide/neovide#294]
Packaging as an AppImage gives neovide in particular a few advantages:

* Updatability through tools like AppImageUpdate
* Desktop integration, including an icon, description, and screenshots (for app stores)
* We may be able to include libvulkan_intel.so, libvulkan_radeon.so, etc. binaries in the AppImage itself so user's don't have to manually install mesa-vulkan-drivers
* Signing the executable and having the signature validated on update

I'd be happy to look into implementing this.

**Comment by j4qfrost** [comment]
Sounds like a good idea. I would like these pull requests to be resolved before before this gets merged in https://github.com/Kethku/neovide/pull/277 (this provides some large quality of life changes for the developer) https://github.com/Kethku/neovide/pull/292 (this solves a build related issue, which may or may not affect your work).

@Kethku any other blockers?

**Comment by j4qfrost** [comment]
https://github.com/Kethku/neovide/issues/167 attaching a related issue.

**Comment by Kethku** [comment]
I think this has been attempted in the past via cargo-bundle. Unfortunately I'm very much not an expert, so I'd need someone else to do the investigation. Otherwise I will implement it eventually, it just might take a bit

**Comment by benweedon** [comment]
I'm in the process of working on it now. Hopefully next weekend I'll fork the repo and put a branch up.

**Comment by Kethku** [comment]
Very cool! Thanks a bunch. If its helpful, it looks like wezterm has a workable solution https://wezfurlong.org/wezterm/installation.html

**Comment by MultisampledNight** [comment]
Implemented in https://github.com/neovide/neovide/pull/1612 a bit ago.
