### ISSUE TITLE
Remap macOS Command key

### ISSUE THREAD

**Issue by theniceboy** [neovide/neovide#295]
With Iterm2, I had my `command` key remapped to `ctrl`. I wonder if this is achievable in neovide. I have used this layout for years, but I really appreciate the speed and the awesome appearance (especially that smooth cursor) that neovide provides. I'm sorry for the dup if there's already a solution, but I have not found one. Please help!

![](https://media1.giphy.com/media/kVag2hXLxG4cjFmdSM/giphy.gif)

**Comment by Kethku** [comment]
I'm not sure if I understand. Was this change done at the vim level or in some iterm2 config?

**Comment by theniceboy** [comment]
Yes, that was an Iterm2 settings
![Screen Shot 2020-05-18 at 12 17 43 PM](https://user-images.githubusercontent.com/8187501/82236073-9611fe00-9901-11ea-9f5e-235a1392f7fe.png)

**Comment by Kethku** [comment]
Hmmm. I'm not sure. I could probably add a remap setting... Might make life easier for some layout handling too...

**Comment by j4qfrost** [comment]
I had thought this was an issue that could be solved via neovim settings.

**Comment by Kethku** [comment]
It should be I think, but can't be done right now. I'll think about what the best option is

**Comment by Kethku** [comment]
@j4qfrost I feel like this is outside the scope of a neovim gui. What do you think? Seems like something autohotkey or karabiner would be used for.

**Comment by j4qfrost** [comment]
I would defer to someone with more experience in this. My intuition is that
we shouldn't support this, and it's not really a bug. We could possibly
expose the keybindings in the future, but I would still hold off until we
have stable support for winit. So I guess leave the issue open for now.

**Comment by iansinnott** [comment]
Does this mean it's not currently possible to map keys using `<D-`? I.e. `<D-j>`, `<D-k>`, etc?

**Comment by iansinnott** [comment]
> cmd can be remapped to ctrl in macOS Preferences > Keyboard.

By remapping the modifier keys?

Unfortunately this does not work for the particular use case I'm thinking of. If you remap Command to Control you can use the physical Command key just fine, but you lose a modifier key. I.e. you cannot have separate mappings for `<C-j>`  and `<D-j>`

**Comment by pluskid** [comment]
It seems vim defines `<D-` mappings for macos `cmd+` keys, but the GUI needs to capture those and send the corresponding events to vim. For example, MacVim support that. I wonder if similar things could be supported by neovide.

**Comment by lethanix** [comment]
> > cmd can be remapped to ctrl in macOS Preferences > Keyboard.
> 
> By remapping the modifier keys?
> 
> Unfortunately this does not work for the particular use case I'm thinking of. If you remap Command to Control you can use the physical Command key just fine, but you lose a modifier key. I.e. you cannot have separate mappings for `<C-j>` and `<D-j>`

You can remap Command to Control and Control to Command, you will still have both modifier keys.

**Comment by vbrinnel** [comment]
The following works well for me:

1) Install Karabiner (https://karabiner-elements.pqrs.org/)
2) Create vi ~/.config/karabiner/assets/complex_modifications/neovide-swap-cmd-ctrl.json
3) Customize the rule to your liking (note that only dedicated cmd-keys are mapped below since mapping left_command to left_control for every key impacts useful system shortcuts such as cmd-tab)
4) Add the rule in Karabiner (see https://karabiner-elements.pqrs.org/docs/manual/configuration/configure-complex-modifications/images/karabiner-elements-complex-modifications-1@2x.png)
```
{
  "title": "Swap Left Control/Command only in Neovide",
  "rules": [
    {
      "description": "Swap Left Command to Control in Neovide",
      "manipulators": [
        {
          "type": "basic",
          "from": {
            "key_code": "c",
            "modifiers": {"mandatory": ["left_command"]}
          },
          "to": {
            "key_code": "c",
            "modifiers": ["left_control"]
          },
          "conditions": [
            {
              "type": "frontmost_application_if",
              "bundle_identifiers": ["^com.neovide.neovide"]
            }
          ]
        },
        {
          "type": "basic",
          "from": {
            "key_code": "v",
            "modifiers": {"mandatory": ["left_command"]}
          },
          "to": {
            "key_code": "v",
            "modifiers": ["left_control"]
          },
          "conditions": [
            {
              "type": "frontmost_application_if",
              "bundle_identifiers": ["^com.neovide.neovide"]
            }
          ]
        }
      ]
    }
  ]
}
```

Hope this helps,
best.

**Comment by falcucci** [comment]
@vbrinnel thank you, I was going to suggest karabiner as a great candidate solution which I use for years.

Karabiner it's even better cuz it works globally independently of the app you are using to.

Indifferently about which key you map as command, you can handle it using neovide keymap `<D-` as @pluskid says.

closing it as we don't plan to add this feature on neovide's side and we have good alternatives to achieve the result.

**Comment by falcucci** [comment]
@vbrinnel thank you, I was going to suggest karabiner as a great candidate solution which I use for years.

Karabiner it's even better cuz it works globally independently of the app you are using to.

Indifferently about which key you map as command, you can handle it using neovide keymap `<D-` as @pluskid says.

closing it as we don't plan to add this feature on neovide's side and we have good alternatives to achieve the result.

**Comment by eugenesvk** [comment]
> Karabiner it's even better cuz it works globally independently of the app you are using to

That's what makes it worse because then the app is blind as to what karabiner is doing, so, e.g., can't display any help as to which keybinds are changed

Also Karabiner is blind as to what state the app is in, so, e.g., you can't rebind a key depending on what mode you're in. What if you want to differentiate between left Alt and right Alt as these are in a very convenient thumb location, but also only in a given mode (e.g., insert special symbols in insert mode and do motions in normal)?

Besides this means that on each OS you'd need to create separate rebindings with separate complexities instead of having it done once
