### ISSUE TITLE
under line be only red

### ISSUE THREAD

**Issue by findNextStep** [neovide/neovide#300]
I add setting make every member function and var with underline and the underline only show as red
![image](https://user-images.githubusercontent.com/26270464/82988276-7a0e0b00-a02b-11ea-9de1-8701c7d2f487.png)
I set underline like 
```
highlight LspCxxHlSymClassMethod gui=underline guifg=#e5b124
```
It show in terminal like 
![image](https://user-images.githubusercontent.com/26270464/82988423-b5a8d500-a02b-11ea-9526-4d9df8e3d4e2.png)

**Comment by j4qfrost** [comment]
I'm having some trouble understanding your issue. Is your problem that you want both colors to appear but for different cases or is one color showing when another should be?

**Comment by findNextStep** [comment]
I think the underline color set by `gui=underline`should be same as the font color

**Comment by j4qfrost** [comment]
Have you tried changing other settings? It could be applying the wrong configuration file. Also maybe try changing the color to #ffffff just to check and see that it's not some weird rendering issue.

**Comment by findNextStep** [comment]
it seem that it just happen 

![image](https://user-images.githubusercontent.com/26270464/82993585-6a92c000-a033-11ea-8805-beee7013d96b.png)
by the way i work on mac, compile with master branch

**Comment by j4qfrost** [comment]
I've found the cause of the behavior discrepancy. It looks like the behavior for neovim is to make it so underline would always be the foreground color, but neovide handles this with a "special" color which is set to red. I am a beginner with vim, so I'm not sure how to configure the special value. This looks like a design decision by @Kethku, so I would sit tight for a response from him.

I think it's a fairly nice feature to be able to change the color like this for the underlines to pop, but it's not in line with nvim design. Thanks for pointing it out, @findNextStep

**Comment by Kethku** [comment]
actually this is to spec. Neovim guis have the ability to set the underline color where terminals cannot. The special color is sent by neovim for this exact case.

You can change the underline or undercurl color by setting guisp for a given style

**Comment by j4qfrost** [comment]
Should guisp default to foreground instead of red then?

**Comment by Kethku** [comment]
That's an interesting point and I'm not sure. I'm sorta incline to look up what other guis do and emulate with the exception of neovim-qt which does it wrong

Thanks,
Keith
________________________________

**Comment by j4qfrost** [comment]
I like how it is now. I think this is more a feature than anything else. We could include a link to some vim configuration samples on the README. It would be a good way to explore quirks.

**Comment by svermeulen** [comment]
Why is nvim-qt wrong for using the foreground color for guisp?

**Comment by svermeulen** [comment]
I'm not sure what is technically correct according to nvim spec, but I definitely prefer foreground color for this.  I think hard coding it to red will not look right in certain color schemes

**Comment by Kethku** [comment]
nvim-qt doesn't pay attention to guisp (at least when I looked last) so its incorrect in the sense that it doesn't pay attention to the special color at all.

note that we don't hard code the underline to red. It is given to us by the style from the neovim process.

**Comment by Kethku** [comment]
In fact we default to grey not red. Vim is setting the special color to red not us. https://github.com/Kethku/neovide/blob/master/src/editor/mod.rs#L56

**Comment by last-partizan** [comment]
I'm gonna reopen this issue, and dig a little further.

https://github.com/neovide/neovide/blob/d2760e2d4562c4d7793444120be386d79bcdf57f/src/editor/style.rs#L57

Here is we're setting color for `special`, by using `special` color or `default special`.

I think, if we change this chain to `special or foreground or default special`, nobody will complain and i will be happy.

I'll make a PR with this change.

Look at this:

![image](https://user-images.githubusercontent.com/301015/132132442-40508cec-f381-48fa-82f8-d2d96ba56571.png)

![image](https://user-images.githubusercontent.com/301015/132132448-37ad596a-ecae-4099-9979-04f2ac73a48c.png)

This change still allows underline color to be customized, but default will be expected color and not red.
