### ISSUE TITLE
support custom icon 

### ISSUE THREAD

**Issue by aj3423** [neovide/neovide#305]
When open multiple different projects, they all shown as a white square in the task bar.
What about add a param like "neovide --icon /projectA.ico" ?

**Comment by Kethku** [comment]
What platform? On my machine it shows the neovim icon. Something may be wrong with the release build?

**Comment by aj3423** [comment]
On Kali Linux, the latest master(2020.5.31), looks like
![neovide icon](https://user-images.githubusercontent.com/4710875/83347016-49441380-a354-11ea-8a7d-d4168859ac5c.png)

**Comment by jamespotz** [comment]
@aj3423 
You can use menulibre, and just select an icon you want to use. That's what I did with Arch.

**Comment by aj3423** [comment]
@jamespotz Thanks, unfortunately:
![menulibre](https://user-images.githubusercontent.com/4710875/83359756-d916ab80-a3ae-11ea-8662-490515fd1f09.png)

**Comment by p00f** [comment]
why are you running menulibre as root?

**Comment by aj3423** [comment]
> why are you running menulibre as root?

Kali's default user is root, it's more convenient in most cases.

**Comment by p00f** [comment]
> > why are you running menulibre as root?
> 
> Kali's default user is root, it's more convenient in most cases.

makes sense, sorry
