### ISSUE TITLE
[request] GUI components

### ISSUE THREAD

**Issue by p00f** [neovide/neovide#324]
**I don't know if this is in scope**, but "external GUI" components would be nice, like completion popup, command pallete, tanline, error messages etc.

(I don't think this is related to #233 because a GUI popup would have a scrollbar)

**Comment by Kethku** [comment]
The struggle for me here is that its not obvious how to implement such features in a way that isn't just different for different sake. I'd be happy with such an improvement if it was demonstrably better, but I haven't seen external gui components that really achieve that.

I'd love to hear ideas though

**Comment by PitcherTear22** [comment]
An external command pallete/messages would not clear messages when you enter command mode

**Comment by PitcherTear22** [comment]
Also indent guides are super duper useful

**Comment by p00f** [comment]
Would you take a PR for this?
(I'll still try, even though I'm very sure I'm unqualified)

**Comment by Kethku** [comment]
Re gui components, I would take a PR for this, but as I mentioned above, it needs to be demonstrably better without feeling out of place. THats a pretty subjective criteria, but if effort is put forth I will definitely support in any way I can to try to get it to a place where we could merge.

One thing though is that implementing gui components often requires adjusting window sizes. This requires the multigrid work that I am currently working on finishing up so it may be better to wait a bit before starting on something like this.

Side note: Indent guides can be implemented in vim today I believe. https://github.com/nathanaelkane/vim-indent-guides

**Comment by p00f** [comment]
>Re gui components, I would take a PR for this, but as I mentioned above, it needs to be demonstrably better without feeling out of place. THats a pretty subjective criteria, but if effort is put forth I will definitely support in any way I can to try to get it to a place where we could merge.

Thanks !!

> One thing though is that implementing gui components often requires adjusting window sizes. This requires the multigrid work that I am currently working on finishing up so it may be better to wait a bit before starting on something like this.

Okay, I'll wait

> Side note: Indent guides can be implemented in vim today I believe. https://github.com/nathanaelkane/vim-indent-guides

https://github.com/Yggdroot/indentLine + https://github.com/lukas-reineke/indent-blankline.nvim is way better, it looks like a proper GUI's indent guides (like vscode)

**Comment by shaunsingh** [comment]
> The struggle for me here is that its not obvious how to implement such features in a way that isn't just different for different sake. I'd be happy with such an improvement if it was demonstrably better, but I haven't seen external gui components that really achieve that.
> 
> I'd love to hear ideas though

The biggest benefit for me would be larger windows within neovim. On emacs having my command palette/statusline/tabs/filetree a larger font makes it much easier on the eyes. There isn't really a need to make it "better" or "'different",  just having a plain scrollable rectangle looks much cleaner than telescope or fzf

**Comment by p00f** [comment]
Can this be closed in favour of #768  ?

**Comment by Zarainia** [comment]
A scrollbar would be really nice and exists in gVim. I've been faking it for the terminal, but it's really not the same.

**Comment by Kethku** [comment]
There are nvim extensions that do this pretty damn well. I use nvim satellite for instance to great effect. And further remaining gaps should be enabled in a vim centric way by exposing config options to get even closer. Closing for now
