### ISSUE TITLE
Investigate Exposing UI Extensions to Vimscript

### ISSUE THREAD

**Issue by Kethku** [neovide/neovide#36]
It would be interesting to support the message and command line extensions by rerouting them back to vimscript via events.

It would be awesome to let the user implement messages/commandline using libraries such as https://www.reddit.com/r/neovim/comments/dd8o0w/use_floating_windows_to_show_notifications_in/
or similar.
If I combine this with the ability to set text size on a per window basis it could be very powerful.

**Comment by clason** [comment]
+1, but I'd expose this through Lua instead. After all, This Is Neovim! :)

**Comment by Kethku** [comment]
This is supported in modern neovim. Closing
