### ISSUE TITLE
Add docs for guifont extension

### ISSUE THREAD

**Issue by Kethku** [neovide/neovide#382]
Lots of confusion from folks not knowing about the guifont feature.

Documentation would make this better as we could just point them to the doc explaining the font fallback system and why it exists

**Comment by keyboard-clacker** [comment]
@Kethku I'm happy to turn this into documentation! Though I'm actually not sure if I understand how to use guifont with neovide haha. I have `set guifont=Fira\ Code\ Retina\ Nerd\ Font\ Complete\ Mono:h18` in my init.vim, which does exactly what it's supposed to in MacVim, for example, but the font doesn't seem to be picked up in Neovide.

Also just to make sure my understanding correct of guifont-- I could do something like this right?
```vimscript
set guifont=Fira\ Code\ Retina\ Nerd\ Font\ Complete\ Mono:h18,Courier:h16
```
or replace `Courier` with whatever postscript font name you have installed and want

**Comment by keyboard-clacker** [comment]
Update on this, I had to use `fc-scan` to check the actual name of the font and found the right one. I'm now able to correctly use that font I was attempting to, but it looks like the fallback fonts aren't working appropriately

**Comment by Kethku** [comment]
fall back is done via a comma, but individual font sizes can not be used. So rather than set guifont=Fira\ Code\ Retina\ Nerd\ Font\ Complete\ Mono:h18,Courier:h16 it should be set guifont=Fira\ Code\ Retina\ Nerd\ Font\ Complete\ Mono,Courier:h16

**Comment by keyboard-clacker** [comment]
Ah hah! Fantastic, thank you I got mine to work with a fallback feature. Cool I'll try to write up some documentation tonight or this weekend and open a PR

**Comment by Galicarnax** [comment]
Hmmm... I've installed that font manually, but I still cannot get the italics in my terminal - it's not there, it's just a regular Fira Code. Is it a secret, after all, how Neovide manages to use nice italics with Fira Code? :)

**Comment by someoneinjd** [comment]
It's not *true italics* but *faux italics* ([difference between them](https://nvision-that.com/i-is-for-italic/)), and Fira Code doesn't provide a true italic font. Italics presented in Neovide is achieved by text shaping (using [swash](https://github.com/dfrg/swash)). And as far as I know, [foot](https://codeberg.org/dnkl/foot/) (a wayland terminal emulator) and some Qt applications (e.g. [neovim-qt](https://github.com/equalsraf/neovim-qt)) can also display faux italics using Fira Code.

**Comment by Galicarnax** [comment]
Oh, that's an insightful clarification. Many thanks.

**Comment by MultisampledNight** [comment]
Now viewable in the wiki under the newly created FAQ page, thank you!
