### ISSUE TITLE
High ram usage when chaning font size

### ISSUE THREAD

**Issue by ghost** [neovide/neovide#394]
Hi!
I just tried out neovide. I'm really liking it! :)
However, I am having a problem.. Whenever I change the font size, the RAM usage goes higher.
I am using the following to change font (from my `init.vim`):
```
let s:fontsize = 16
function! GuiFont()
  exe 'set guifont=FiraCode\ Nerd\ Font\ Mono:h' . s:fontsize
endfunction
function! AdjustFontSize(amount)
  let s:fontsize = s:fontsize+a:amount
  call GuiFont()
endfunction
call GuiFont()
noremap <silent> <C-=> :call AdjustFontSize(3)<CR>
noremap <silent> <C--> :call AdjustFontSize(-3)<CR>
```
I am using NeoVim `v0.5.0-812-gd17e50879` and neovide `0.6` (from this package in the [AUR](https://aur.archlinux.org/packages/neovide/).
Here is the RAM usage skyrocketing:
https://streamable.com/4of38r

-- EDIT --
Just tried on Neovim `0.4.4`, nothing changed. Problem persist even disabling all plugins!

**Comment by Kethku** [comment]
the version of neovim does not effect how the fonts are allocated. I'm guessing we are holding onto the fonts longer than necessary in our cache. This shouldn't be too difficult to fix...

**Comment by j4qfrost** [comment]
Are the fonts being rebaked? Are we not using something like vector graphics to render them?

**Comment by Kethku** [comment]
Font rendering is complicated. Different size fonts require different textures when rendered. I believe skia renders fonts into a texture atlas which it keeps stored in video memory for faster more efficient rendering. But I don't know for sure.

Counter intuitively I believe this is the "correct" way to draw text. But I couldn't answer any questions as to why that is the case.

**Comment by Kethku** [comment]
This is very old and related to the old font rendering. Closing
