### ISSUE TITLE
Keys pressing twice

### ISSUE THREAD

**Issue by rconnorjohnstone** [neovide/neovide#422]
Running Arch Linux, just installed neovide from the AUR. Everything seems to work well, but all of my letter-keys are being sent twice per keypress (not true for arrow keys, backspace, etc).

I'm not really sure where to begin with this one, so just let me know what info you'd like me to log and I can do that.

**Comment by Kethku** [comment]
Did you install the main build or the one from release? I recommend trying the main development build as the old builds are pretty old at this point and a lot has happened since. Its on my list to make a new release soon

**Comment by rconnorjohnstone** [comment]
I had been using the aur version. Just tried cloning master and building that. Still the same problem.

**Comment by Kethku** [comment]
I believe this has been fixed in main. Please reopen if problems persist.
