### ISSUE TITLE
[Animated Windows] Is it possible to show animation when new window is open/close ?

### ISSUE THREAD

**Issue by kiuKisas** [neovide/neovide#434]
Is it possible to have an animation when a new window is open ? (e.g: with `:sp` command)

**Comment by Kethku** [comment]
Interesting. I'm curious what your proposal for the animation would be? Would the windows animate in from a configurable direction? The closest edge? I had windows animating into place from the zero,zero top left position, but I found that experience to be annoying. Open to ideas though!

**Comment by kiuKisas** [comment]
Hum.. the closest edge seems the more "natural". Depending on the windows "orientation" (horizontal or vertical), it should be as if the window have a 0 width/height then grow.
Dunno if what I say make sense.. ^^

I imagine something like that, but the reverse (you can click on the element to delete):
http://jsfiddle.net/2gbPg/2/

Seeing this jsfiddle, it can be nice to have animation when we close a window also.

**Comment by kiuKisas** [comment]
@Kethku you seems to made some improvement about it, doesn't it ? :)

**Comment by Kethku** [comment]
Closing as this doesn't really feel good in practice.
