### ISSUE TITLE
Can't specify the font weight

### ISSUE THREAD

**Issue by tejasvi** [neovide/neovide#457]
I am using [Operator Mono](https://github.com/KayodeOgidan/Operator-Mono-Fonts/tree/master/Fonts/OMono) specified with `set guifont=Operator\ Mono:h16`. It defaults to *Light* font weight and I would instead prefer Medium. With `set guifont=Operator\ Mono\ Medium:h16` it falls back to some other default font. On nvim-qt and gVim setting the font with `set guifont=*` works perfectly and `guifont` is set to `Operator Mono Medium:h16` and `Operator_Mono_Medium:h16:W350:cANSI:qDRAFT`. It tried setting the same in neovide but it showed the fallback font instead. On a side note, the implementation of `set guifont=*` and better conformity to `:h guifont` would be useful.

**Comment by tejasvi** [comment]
I managed to show _Medium_ font weight by straight up removing the font files for _Light_, _Book_, and _Bold_ font weights. However, **bold** and *italics* highlighting still doesn't work. If possible, implementation of font selector would be godsend.

**Comment by xbladesub** [comment]
Hasn't this been implemented yet?

**Comment by fredizzimo** [comment]
The support was added here
* https://github.com/neovide/neovide/pull/2246

**Comment by luisiacc** [comment]
@fredizzimo is there a way to change the weight dynamically inside neovim? Or this only works with the font in the config file?

**Comment by fredizzimo** [comment]
@luisiacc, it's only the config file for now. But it should have hot reload.

It's still open how and if we should make this configurable from inside Neovim. The `guifont` variable is not really extensible, and we are already doing things out of the specification.

**Comment by luisiacc** [comment]
@fredizzimo ahh Ok, I'd imagine something like a global function like `neovide_set_font("FontName", {...opts})`
