### ISSUE TITLE
Limit window animations to scrolling only

### ISSUE THREAD

**Issue by svermeulen** [neovide/neovide#472]
I really love the smooth scroll offered by `--multiGrid`, but I don't like any of the other behaviour.  The auto-transparent windows sometimes cause foreground to be transparent, and the general window animations constantly trigger in cases where I wouldn't expect them to.  Are there settings to control the various features offered by `--multiGrid` or is it an all or nothing thing?  I did not see any in the wiki

**Comment by Kethku** [comment]
Window transparency is somewhat broken currently due to not picking up the native window transparency options. This work is ongoing.

In the meantime you should be able to turn off transparency/blur/window animations with this:

```
let neovide_window_position_animation_length = 0
let neovide_window_floating_opacity = 1.0
let neovide_window_floating_blur = v:false
```

**Comment by Kethku** [comment]
There are still some bugs with the multigrid renderer though. I'd really appreciate it if you could open issues for any weirdness you might find.

In particular, mouse input is broken with multigrid enabled. I believe this is an upstream issue (that I see you have seen given the reacts)

Also the renderer for multigrid is way less efficient about turning off than it was before. I think this is just an issue with the redraw handler, but I haven't found the time to track it down yet.

Lastly the completion menu for some completion plugins doesn't position itself the same as it does without multigrid enabled. I have no idea what this is, but I suspect it may be an upstream issue as well.

**Comment by Kethku** [comment]
Any other issues you might find would be greatly appreciated :)

**Comment by fredizzimo** [comment]
You can disable all the other behaviours https://neovide.dev/configuration.html. And there's no auto-transparency any more.

**Comment by 9mm** [comment]
@fredizzimo I've looked through there, and with `--multigrid` on I don't see any setting to disable whatever animation it is when using neotree (basically a side window opening/closing still animates). I tried this undocumented setting mentioned by @Kethku but I don't think that worked:

```
vim.g.neovide_window_position_animation_length = 0
```
