### ISSUE TITLE
Feature request: shift click on window to activate without moving vim cursor

### ISSUE THREAD

**Issue by lf-** [neovide/neovide#474]
In many terminals I've used, holding shift suppresses the mouse being sent to the program inside. This meant that I could shift click anywhere in the terminal window with a neovim in it to switch to it from my browser (for instance) without poking my selection or coming out of terminal mode accidentally.

I'd love if neovide could support this as well, as it makes it easier to switch windows without having to undo the resulting changes or precisely hit the menu bar with the mouse (in my experience, doing that also often causes it to come out of maximized mode and mess up my neovim window layout).

**Comment by Kethku** [comment]
Interesting. I'd never noticed that that was a consistent feature in terminals. I don't see why this would cause any issues though. I'll see what I can do.

**Comment by Kethku** [comment]
Unfortunately supporting this would break compatibility with neovim. I recently looked into it and mouse events are reported to neovim with modifiers, so overloading shift click to do something other than report the text would be a breaking change.
