### ISSUE TITLE
ScrollWheelUp and ScrollWheelDown maps don't seem to work

### ISSUE THREAD

**Issue by drzel** [neovide/neovide#496]
```vim
nnoremap <c-ScrollWheelUp> echo "foo"
nnoremap <c-ScrollWheelDown> echo "bar"
```

Hold ctrl and scroll mouse, nothing happens.

**Comment by Kethku** [comment]
interesting. Seems like control here is the missing bit. Does this work on other neovim uis?

**Comment by drzel** [comment]
Works in terminal. Not sure about other uis.

**Comment by Kethku** [comment]
https://github.com/neovide/neovide/pull/968 finally got around to looking into this. @drzel if you are still interested, I would appreciate a test of this PR
