### ISSUE TITLE
VimLeave and VimLeavePre not triggered when closing the window

### ISSUE THREAD

**Issue by tstsrt** [neovide/neovide#501]
The autocmd events `VimLeave` and `VimLeavePre` are triggered when exiting with `:q` but not when closing the window, say with Alt+F4.

Tested with this `init.vim`:
```
autocmd VimLeavePre * :call system("date >> ~/ts_vimleavepre.txt")
autocmd VimLeave * :call system("date >> ~/ts_vimleave.txt")
```

**Comment by cljoly** [comment]
If that helps and as another datapoint, when I can’t reproduce the issue with `sway` version 1.6.1 with Archlinux.
Specifically, after adding the following to my config:
```vim
autocmd VimLeavePre * :call system("date >> ~/ts_vimleavepre.txt")
autocmd VimLeave * :call system("date >> ~/ts_vimleave.txt")
```
closing the window using the standard sway message (`kill`) mapped on a shortcut outputs a timestamp, just like `:q` does.

**Comment by Kethku** [comment]
I cannot repro this. I did a slightly different setup with the following

```
autocmd VimLeavePre * :call system("dir > c:/test.txt")
```

Which dutifully created a test.txt file when I closed via `:q`, `:qall!`, clicked the close button, or pressed alt + f4. 
This has been fixed, but feel free to open again if the problem persists.

**Comment by tstsrt** [comment]
Yep, can confirm that the bug is fixed now. Thanks!

**Comment by zdog234** [comment]
I'm seeing this issue on macos (#1532)
