### ISSUE TITLE
Cubic-bezier animation

### ISSUE THREAD

**Issue by kiuKisas** [neovide/neovide#505]
A nice to have features for animations will be to implement a `cubic-bezier` for the timing.
Based on this, we can also  add the common used pattern like `ease-in-out`, etc..

It probably asks some work and is not a priority though.. 

Also, found this lib that can be helpfull (cubic-bezier implementation in safe-rust):

https://github.com/dorianprill/stroke-rs

**Comment by Kethku** [comment]
https://www.github.com/Kethku/neovide/tree/main/src%2Frenderer%2Fanimation_utils.rs

A library of animation utilities was contributed about a year ago. So in principle it shouldn't be hard to make the animation equation configurable, I just haven't gotten around to it yet

**Comment by Kethku** [comment]
Closing as we have much of this done already and have adjusted the cursor animation code.
