### ISSUE TITLE
Setting width for line number column

### ISSUE THREAD

**Issue by marcushwz** [neovide/neovide#525]
## Problem
- The left side column (I am not sure what this is called, basically the column where line numbers are shown) is not rendering properly.
- I am using a tiling window manager, and below are the comparisons between terminal neovim and neovide.
1. Neovim
![image](https://user-images.githubusercontent.com/40255418/114291661-d3ecb780-9abb-11eb-8234-925b875a7bcb.png)
![image](https://user-images.githubusercontent.com/40255418/114291672-dfd87980-9abb-11eb-8bc0-9e480662f7d5.png)

2. Neovide
![image](https://user-images.githubusercontent.com/40255418/114291682-ebc43b80-9abb-11eb-888f-011911e26f3f.png)
![image](https://user-images.githubusercontent.com/40255418/114291689-f7affd80-9abb-11eb-832e-d44be121360c.png)

- As shown in the picture, in neovide, the left column is cut out a little, is there any config that I can set to increase maybe some padding?

Great project by the way, enjoying the animation so far! Thank you to everyone contributing to this!

**Comment by Kethku** [comment]
Can you give me some details about the font you are using?

This feels like the tiling manager you are using is cutting the window off. I'm not sure that something that can be easily solved by neovide as its external. Does a similar program like alacritty show similar cutting off of the window border?

**Comment by marcushwz** [comment]
Thanks for the reply @Kethku.

I don't think it is related to the font or the tiling manager I am using, because it works fine in the terminal neovim.  Just for your info, I have changed my font to Fira Code and the tiling manager I am using is yabai. I will show you some example:

## Terminal Neovim (Iterm2)
![image](https://user-images.githubusercontent.com/40255418/114536363-963a8b00-9c83-11eb-8729-6edfdfc88062.png)
![image](https://user-images.githubusercontent.com/40255418/114536736-f16c7d80-9c83-11eb-9949-03e7ce6e8389.png)


## Neovide (before custom config)
![image](https://user-images.githubusercontent.com/40255418/114536483-b79b7700-9c83-11eb-9c15-21caa2f1c62f.png)
![image](https://user-images.githubusercontent.com/40255418/114536658-df8ada80-9c83-11eb-8efc-dd7ff1e2a71e.png)

## Neovide (after custom config in vimrc)
- I have added this line in my vimrc, and also added a space in front of the warning sign displays using `ale`
```bash
set nuw=5
```
- Things look perfect now for me, but yeah, not sure if this is a bug in neovide, and if you think you might have an idea on why is this happening, please let me know if I can contribute a PR. 
- Again thank you so much for this, I have been enjoying it. And for me, it is much smoother than the terminal neovim.

![image](https://user-images.githubusercontent.com/40255418/114537146-7061b600-9c84-11eb-89f8-710faa7fbf1f.png)

![image](https://user-images.githubusercontent.com/40255418/114537115-650e8a80-9c84-11eb-92fe-ec1f517661ec.png)

**Comment by Kethku** [comment]
I believe this is fixed in main. Please reopen if the issue persists.
