### ISSUE TITLE
Middle Click Paste Not Working

### ISSUE THREAD

**Issue by brokenax3** [neovide/neovide#534]
Middle click paste works everywhere on the system except on neovide. Highlighting text does actually put it into the clipboard as intended.

> :checkhealth

```
health#mkdp#check
========================================================================
  - INFO: Platform: linux
  - INFO: Nvim Version: NVIM v0.4.4
  - INFO: Pre build: /home/mark/.local/share/nvim/plugged/markdown-preview.nvim/app/bin/markdown-preview-linux
  - INFO: Pre build version: 0.0.9
  - OK: Using pre build

health#vimtex#check
========================================================================
## VimTeX
  - OK: Vim version should have full support!
  - OK: Zathura should work properly!
  - OK: Compiler should work!

health#nvim#check
========================================================================
## Configuration
  - OK: no issues found

## Performance
  - OK: Build type: Release

## Remote Plugins
  - OK: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=^H
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
  - INFO: $COLORTERM='truecolor'

health#provider#check
========================================================================
## Clipboard (optional)
  - OK: Clipboard tool found: xclip

## Python 2 provider (optional)
  - WARNING: No Python executable found that can `import neovim`. Using the first available executable for diagnostics.
  - ERROR: Python provider error:
    - ADVICE:
      - provider/pythonx: Could not load Python 2:
          python2 not found in search path or not executable.
          python2.7 not found in search path or not executable.
          python2.6 not found in search path or not executable.
          /usr/bin/python is Python 3.9 and cannot provide Python 2.
  - INFO: Executable: Not found

## Python 3 provider (optional)
  - INFO: `g:python3_host_prog` is not set.  Searching for python3 in the environment.
  - INFO: Multiple python3 executables found.  Set `g:python3_host_prog` to avoid surprises.
  - INFO: Executable: /usr/bin/python3
  - INFO: Other python executable: /bin/python3
  - INFO: Python version: 3.9.2
  - INFO: pynvim version: 0.4.3
  - OK: Latest pynvim is installed.

## Ruby provider (optional)
  - WARNING: `ruby` and `gem` must be in $PATH.
    - ADVICE:
      - Install Ruby and verify that `ruby` and `gem` commands work.

## Node.js provider (optional)
  - WARNING: `node` and `npm` (or `yarn`) must be in $PATH.
    - ADVICE:
      - Install Node.js and verify that `node` and `npm` (or `yarn`) commands work.
```

> export RUST_BACKTRACE=full
> neovide

```
Ignored client type property: "methods"
Ignored client type property: "attributes"
```

System: Arch Linux 5.11.12-arch1-1
Neovide Version: 0.7.0-1

Thank you!

**Comment by amiablechief** [comment]
I have this same issue. I'm on ArcoLinux (an Arch variant) on kernel 5.10.29-1-lts.

**Comment by Kethku** [comment]
Interesting so middle click pastes on other vim instances? Or do you expect this on your os specifically in other gui apps?

**Comment by amiablechief** [comment]
Yes, selecting text from say Geany, and then middle-clicking within **Neovim** pastes text as I have come to expect on Linux. Similar mechanic works elsewhere copy pasting text between applications. Just not on Neovide :)

**Comment by Kethku** [comment]
What about neovim-qt? I'm suspicious that this is something that should be solved in the vim config as middle mouse button is something that can be bound.

When you middle click neovim in a terminal app when not in insert mode, what happens? Not saying I wont address this, just trying to understand the bounds of the problem :)

**Comment by amiablechief** [comment]
Ofcourse, I understand :)

I didn't have Neovim-Qt installed, so I just installed it, selected some text from a browser I had open and middle-clicked in Nvim-Qt and it pasted the text in no problem. This is the exact same behavior as what I get with Neovim in the _terminal_ app. Neither Nvim-Qt nor Nvim terminal were in insert mode when I middle-clicked.

**Comment by Kethku** [comment]
Ok that says to me that neovide isn't reporting middle mouse button events properly to neovim. I think I can investigate

**Comment by brokenax3** [comment]
Thanks! Sorry for replying late. 

I've been daily driving nvim-qt before realising that neovide exists and middle clicking will paste anything that is in the Primary Clipboard. It works fine in the terminal and nvim-qt in normal mode and insert mode.

**Comment by JoseConseco** [comment]
+1 for this not working (I'm on manjaro). Actually I remapped all MMClick to none - because  paste is annoying. But I have set it up as fold-toogle command.  Way more usefull for my workflow (btw I just donated to u Kethku - u created great app)

**Comment by thecashewtrader** [comment]
Same, with Arch Linux + Neovide

**Comment by ZeusThundr** [comment]
I'm having the same issue Manjaro linux (gnome) middle click paste works fine on vim neovim and everything else I've tried except neovide.

**Comment by cizordj** [comment]
The same here, Debian bullseye. If I hit Ctrl+Shift+V it doesn't paste what is on my clipboard. It seems that neovide doesn't sync the clipboard with the operating system.

It happens both on Xorg and Wayland.

I'm using Gnome.

**Comment by Louis-Amas** [comment]
Same here.
Just for clarifying purpose middle click clipboard === X Clipboard

**Comment by WhyNotHugo** [comment]
Middle button (mouse2) usually pastes the PRIMARY selection. On regular neovim, terminals handle this (terminals paste on middle click, like pretty much all desktop apps).

Just to be clear, this _isn't_ the CLIPBOARD selection, which is the one that's copy and pasted via <kbd>Ctrl</kbd>+<kbd>C</kbd> and <kbd>Ctrl</kbd>+<kbd>V</kbd> respectively.

**Comment by ilveroluca** [comment]
Adding myself to the list of those experiencing this problem.  Middle click on neovim-qt and on neovim running in a terminal both work as expected.

**Comment by Kethku** [comment]
Thanks for the ping. I think this is fixed in main. Incidentally this also properly sends right clicks to neovim now. Not sure what that is used for, but it should work now as apposed to just doing nothing.

**Comment by Kethku** [comment]
Please reopen if issues persist

**Comment by ilveroluca** [comment]
Just pulled `main` and rebuilt.  It works!  Thank you.

**Comment by WhyNotHugo** [comment]
It works, thanks!

**Comment by cizordj** [comment]
@Kethku do you plan on making a point release for this feature?

**Comment by Kethku** [comment]
not in the immediate future. There are bugs that I would like to fix before we create a new release
