### ISSUE TITLE
No redraw after triggering cnoremap

### ISSUE THREAD

**Issue by tpict** [neovide/neovide#565]
After triggering a command-line mapping such as
```
cnoremap <silent> <D-v> HELLO<space>WORLD
```
the screen isn't refreshed until you hit another key. I built Neovide from the OpenGL branch on macOS Big Sur.

Thanks for building this, the animated cursor is addictive!

**Comment by Kethku** [comment]
That is almost certainly and upstream issue. But I will take a look soon to see if I can repro and dig in a bit.

**Comment by Kethku** [comment]
I believe this is mixed in main. Please reopen if the issue persists.
