### ISSUE TITLE
Blurry fonts

### ISSUE THREAD

**Issue by yuval256** [neovide/neovide#589]
Fonts appear blurry on macOS Big Sur.
on the right side is iTerm2, on the left is Neovide
<img width="585" alt="Screenshot 2021-04-25 at 15 03 53" src="https://user-images.githubusercontent.com/32190962/115995899-6bcec300-a5dd-11eb-8b1b-87c488dbaf90.png">

**Comment by JoseConseco** [comment]
I noticed this too. Its bit hard to work  with this blur.

**Comment by xuanvan229** [comment]
Same on me. Also the icon not working. 
<img width="244" alt="Screen Shot 2021-04-26 at 14 12 10" src="https://user-images.githubusercontent.com/22408713/116043118-751d6580-a699-11eb-82bd-d8b12e1a83b5.png">

**Comment by bfulop** [comment]
I have the same issue. It looks like there's more discussion here: https://github.com/Kethku/neovide/issues/455

**Comment by Kethku** [comment]
Wait, is that the same issue? The screen caps above look like a font hinting/subpixel rendering issue rather than a resolution problem.

**Comment by bfulop** [comment]
Ah sorry, it's my mistake then! I had the resolution issue (solved by switching to the OpenGL branch) not the font rendering issue.

**Comment by Kethku** [comment]
no problem :)

**Comment by JSchrtke** [comment]
Same issue here, Windows 10, Version 10.0.19042 Build 19042.

The top is neovim in Windows Terminal, bottom is Neovide

![neovide](https://user-images.githubusercontent.com/31078741/117143986-b3113c80-adb1-11eb-8493-f758207d049c.png)

**Comment by SenseiRalph** [comment]
I have exactly the same thing as @JSchrtke, 100% identical problem. However it appears only on some files while on others it's fine. Markdown files with a lot of text do it while something like init.vim does not.

I have Neovide 0.7.0 (built 6 days ago) on Windows 10 (20H2) build 19042.

**Comment by shaunsingh** [comment]
This is from the openGL build for macOS, I built it just a few minutes back 
![Screen Shot 2021-05-20 at 11 27 19 AM](https://user-images.githubusercontent.com/71196912/119006718-9999f400-b95e-11eb-8125-1ab40f00152c.png)
(neovide on the left) 

According to this issue: https://github.com/Kethku/neovide/pull/502, sub pixel was merged into openGL a while back but it still looks as it did earlier. Proper subpixel rendering (with thin strokes enabled) is on the right, theres a big difference

**Comment by Kethku** [comment]
@shaunsingh I've been fighting trying to fix this using the subpixel settings for a while now I believe subpixel font rendering is at least somewhat working, but the positioning of the rendered surface and or the thin stroke settings for the skia font rendering is still not quite there yet.

I'm planning on looking into this further after opengl and possibly font fallback solutions are merged.

**Comment by shaunsingh** [comment]
Nice to see! Font fallback is definitely higher priority, but its good to know the openGL branch is stable enough to replace the Vulkan build.

**Comment by Kethku** [comment]
Or at least it will be stable enough ;)

**Comment by gshpychka** [comment]
@Kethku why was this unpinned?

**Comment by Kethku** [comment]
It was unpinned in favor of more urgent fixes. Don't worry I haven't forgotten

**Comment by nikhgupta** [comment]
@Kethku - just FYI, I want to switch to `neovide` as an attempt to ditch VSCode, but this issue has been keeping me from using this.

**Comment by Kethku** [comment]
That's super helpful to know. Like I said though, I believe the current pinned issues are blocking more people. But I will come back to this

**Comment by gshpychka** [comment]
Same here, this issue is preventing me from using neovide.

**Comment by danielrparks** [comment]
I think this might be the same issue as #283.

**Comment by unrooot** [comment]
Was anyone else able to fix this? I'm still having the same problem that is visible in @shaunsingh's screenshot on Neovide 0.8.0 (on macOS 11.6), but I'm not able to build from the opengl branch since it was merged.

**Comment by Kethku** [comment]
Main is up to date for what we have right now. To my knowledge nobody has pushed this further. I'm focused on other higher priority things at the moment.

**Comment by Kethku** [comment]
I'd be happy to answer questions if you want to investigate further!

**Comment by unrooot** [comment]
I'd love to contribute to the project, but admittedly I don't know anything about Rust 😅

**Comment by bmulholland** [comment]
Since this was listed in #1061, wanted to mention for anyone looking into this that it may be related to #851 and I've posted a repro for that issue at https://github.com/neovide/neovide/issues/851#issuecomment-934101180

**Comment by fredizzimo** [comment]
Another possible cause is this https://github.com/neovide/neovide/issues/1143. Do you all with blurry fonts have DPI scaling enabled? 

Normal antialiasing instead of subpixel antialiasing also made the text slightly sharper for me, although I would call it sharp before too, but now it's sharper than most other programs on Windows. This was changed here https://github.com/neovide/neovide/commit/9cfac28ac8add0e03e2cab46a5be034c77a78a9d

**Comment by Kethku** [comment]
#1143 has now been fixed

**Comment by Kethku** [comment]
This is fixed in main. Both the greying of subsequent text, and defaulting to normal antialiasing. Closing now as I thiiink this is fixed.
