### ISSUE TITLE
Package for Nixpkgs

### ISSUE THREAD

**Issue by enderger** [neovide/neovide#612]
Hi,

I honestly would love to see this project in Nixpkgs, which is a package manager which runs on Linux and OSX. I'd be happy to help with the process, and know enough about the language to provide assistance with writing.

A similar issue is open in Nixpkgs [here](https://github.com/NixOS/nixpkgs/issues/111972), and collaboration between this issue and that one would be a good thing.

**Comment by j4qfrost** [comment]
Git issue searching is pretty bad, so I guess you didn't see this issue https://github.com/Kethku/neovide/issues/465

**Comment by enderger** [comment]
Hm, I'll see if I can get it working. The `rpath` is the "runtime path", by the way. I believe it is used to find dynamic libraries and such.

**Comment by Kethku** [comment]
I'm all for getting this working on nix. unfortunately I don't have a ton of mac or linux experience and do not have easy access to either. So it would have to be driven by somebody else. But I can absolutely be responsive and answer any questions if you want to drive it!

**Comment by enderger** [comment]
@Kethku Try using the Windows Subsystem for Linux, it gives you access to a Unix command line on Windows (Nix should work inside it). I’ll update the README when I have a bit.

**Comment by teto** [comment]
It got packaged in the linked PR. I am still not able to run it. Maybe after https://github.com/Kethku/neovide/pull/655

**Comment by fredizzimo** [comment]
The nixpkg has existed for some time
