### ISSUE TITLE
Remember Last Window Dimensions.

### ISSUE THREAD

**Issue by PyGamer0** [neovide/neovide#622]
Neovide should remember the last window dimension and open the new window with the same dimensions.
Could be a setting like `g:neovide_remember_dimensions`

**Comment by Kethku** [comment]
I think this is a reasonable request. I would be happy to take a PR for this.

**Comment by bbli** [comment]
I can try to take a stab at this. Any recommendations on what files to look at?

**Comment by PyGamer0** [comment]
@bbli Pretty sure this is the place neovide get its window dimensions. https://github.com/Kethku/neovide/blob/main/src/window/mod.rs#L63

**Comment by bbli** [comment]
@PyGamer0 thanks, that definitely pushed me in the right direction. @Kethku , I couldn't find in the codebase a "settings" file that is written to. If there is, can you point me to it, and if not, do you have any guidelines for where to write to in the user's filesystem?

**Comment by PyGamer0** [comment]
> settings" file that is written to

 @bbli do you mean neovide settings? They are stored in user's init.vim.

> where to write to in the user's filesystem

On windows there is an environment variable TEMP. Don't know about other OS.

**Comment by bbli** [comment]
> They are stored in user's init.vim.
Ohh no, I am not talking about setting the boolean g:neovide_remember_dimensions variable, but rather the window's width and height. Because my solution to having neovide remember the dimension is to write to a file upon exit, and on startup read from that file.

In any case, I probably will submit a pull request tomorrow, so perhaps looking over that code will clear things up, and we can take it from there.

**Comment by Pangoraw** [comment]
I had taken a try at this issue and by default, I stored the file in the `stdpath("data")` path return by neovim, this is where I have seen other package write to. See [the start of my implementation](https://github.com/Pangoraw/neovide/commit/890c4022596762eae373a8e80f5344e850a0dac6#diff-1b0002da06aecc299358a022e976fac801bb3db88b77817e1a1aee77dbc09f3eR281-R285).

**Comment by Kethku** [comment]
Oh very interesting. I didn't realize that was an standard place for this sort of data. Very cool!

I wonder if we should build a standard way for neovide to store data from run to run. Maybe use serde and serialize out a structure as json?

**Comment by bbli** [comment]
> stored the file in the `stdpath("data")` path
Ohh ok, thanks for letting me know! It causes some complications that I talk about in my pull request #665 .

> if we should build a standard way for neovide to store data from run to run
Yeah, I was wondering about that too, as I parse as if the only thing in the stored file is the last window size.

**Comment by last-partizan** [comment]
Closing this, averything is merged.
