### ISSUE TITLE
Font specification doesn't allow for overwriting of specific font types

### ISSUE THREAD

**Issue by katawful** [neovide/neovide#636]
While I know that this is a part of #444, there is a specific issue with this problem that I haven't seen brought up

I use FiraCode Nerd Font, and this font does not have _Italic_ and **_Bold Italic_** fonts. The font instead just defaults to non-italic. Normally I specify an italic and bold italic font in my terminal, but with Neovide (and GUI NeoVim in general), since FiraCode NF maps non-italic fonts to italic fonts, I can no longer see italics regardless if I also specify another font like so:
```vim
set guifont=FiraCode\ Nerd\ Font:h15,\ MesloLGS\ NF:h15,DejavuSans:h15
```

For kitty for instance (my terminal), the config for specific fonts per type is something like this:
```cfg
font_family FiraCode Nerd Font
bold_font auto
italic_font Meslo LG S NF Italic
bold_italic_font Meslo LG S NF Bold Italic
```
I wonder if this could be addressed with future updates to Neovide. I really like this GUI but this limitation hurts some of my usage

**Comment by Kethku** [comment]
I think this makes sense, but should land after the font fallback solution is finished. At the moment neovide is behind other guis. This solution would bring it up to the front of the pack, which is great! but we gotta get parity first.

**Comment by fredizzimo** [comment]
This is now supported by
* https://github.com/neovide/neovide/pull/2213
* https://github.com/neovide/neovide/pull/2246
