### ISSUE TITLE
can't run neovide in ubuntu 20.04

### ISSUE THREAD

**Issue by 88srzh** [neovide/neovide#643]
when i try to run neovide in ubuntu 20.04:
`thread main panicked at Failed to initialize any backend! Wayland status: NoCompositorListening X11 status: XOpenDisplayFailed, /root/.cargo/registry/s`

**Comment by Kethku** [comment]
Can you try the opengl branch?

**Comment by 88srzh** [comment]
i tried:
```
Ignored client type property: "methods"
Ignored client type property: "attributes"
thread 'main' panicked at 'Failed to initialize any backend! Wayland status: NoCompositorListening X11 status: XOpenDisplayFailed', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.24.0/src/platform_impl/linux/mod.rs:605:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by j4qfrost** [comment]
@Kethku if we can get the opengl branch working in Wayland, we could draft a big issue for glutin. @88srzh would be happy to work with you on trying to get this running with Wayland.

**Comment by 88srzh** [comment]
@Kethku would be happy to work with you too, in arch i have same error.
Unfortunately I lost ubuntu, but now i have installed to a new drive and try to run neovide and get the error: neovide command not found...

**Comment by j4qfrost** [comment]
Are you running x11 or wayland for the compositor?

**Comment by 88srzh** [comment]
wayland

**Comment by 88srzh** [comment]
in wayland i try to build at opengl branch:

[https://imageup.ru/img244/3742977/snimok-ekrana-ot-2021-05-17-21-09-14.png](url)

correct me if i'm doing something wrong

**Comment by scifi6546** [comment]
I have the same issue. Based on a backtrace it has something to do with winit. It does not work on both gnome and i3wm

**Comment by juliankay** [comment]
> I have the same issue. Based on a backtrace it has something to do with winit. It does not work on both gnome and i3wm

same here with i3

**Comment by scifi6546** [comment]
here is a backtrace: 
```
Ignored client type property: "methods"
Ignored client type property: "attributes"
   0: std::panicking::begin_panic
             at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/std/src/panicking.rs:519:12
   1: winit::platform_impl::platform::EventLoop<T>::new_any_thread
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.24.0/src/platform_impl/linux/mod.rs:605:9
   2: winit::platform_impl::platform::EventLoop<T>::new
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.24.0/src/platform_impl/linux/mod.rs:556:9
   3: winit::event_loop::EventLoop<T>::with_user_event
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.24.0/src/event_loop.rs:134:25
   4: winit::event_loop::EventLoop<()>::new
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.24.0/src/event_loop.rs:120:9
   5: neovide::window::window_wrapper::start_loop
             at /root/parts/neovide/build/src/window/window_wrapper/mod.rs:413:22
   6: neovide::window::create_window
             at /root/parts/neovide/build/src/window/mod.rs:106:5
   7: neovide::main
             at /root/parts/neovide/build/src/main.rs:179:5
   8: core::ops::function::FnOnce::call_once
             at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by MitraKumar** [comment]
I faced the same issue in Ubuntu 18.04 as well.

**Comment by j4qfrost** [comment]
@MitraKumar @88srzh try the snap `snap install neovide --channel=latest/beta` and tell me if it works for you.

**Comment by 88srzh** [comment]
@j4qfrost 
`Ignored client type property: "methods"
Ignored client type property: "attributes"
thread 'main' panicked at 'Failed to initialize any backend! Wayland status: NoCompositorListening X11 status: XOpenDisplayFailed', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.24.0/src/platform_impl/linux/mod.rs:605:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace`

**Comment by belozerskiy** [comment]
@j4qfrost
```
michael@demon:~$ uname -a
Linux demon 5.8.0-55-generic #62~20.04.1-Ubuntu SMP Wed Jun 2 08:55:04 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
michael@demon:~$ snap install neovide --channel=latest/beta
neovide (beta) 0.7.1+git from Jack Frost (j4qfrost) installed
michael@demon:~$ neovide
Ignored client type property: "methods"
Ignored client type property: "attributes"
thread 'main' panicked at 'Failed to initialize any backend! Wayland status: NoCompositorListening X11 status: XOpenDisplayFailed', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.24.0/src/platform_impl/linux/mod.rs:605:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by j4qfrost** [comment]
@88srzh @belozerskiy Sorry for the late response. Are you two using wayland? What does this env variable say `WINIT_UNIX_BACKEND`? You may find more information upstream in winit https://github.com/rust-windowing/winit/search?q=XOpenDisplayFailed&type=issues. I can't reproduce the problem myself.

**Comment by 88srzh** [comment]
@j4qfrost  no, it's not in wayland. in fedora work fine

**Comment by nevalsar** [comment]
@j4qfrost I have this exact issue with the neovide binary installed with `--beta` flag from Snap store in Ubuntu 20.04 LTS. I am running  X11 (not Wayland) and `WINIT_UNIX_BACKEND` is not set.
```
❯ echo $WINIT_UNIX_BACKEND


❯ echo $DISPLAY
:0

❯ /snap/bin/neovide --version
Neovide 0.7.0

❯ RUST_BACKTRACE=1 /snap/bin/neovide
thread 'main' panicked at 'Failed to initialize any backend! Wayland status: NoCompositorListening X11 status: XOpenDisplayFailed', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.24.0/src/platform_impl/linux/mod.rs:605:9
stack backtrace:
Ignored client type property: "methods"
Ignored client type property: "attributes"
0: std::panicking::begin_panic
at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:519:12
1: winit::platform_impl::platform::EventLoop<T>::new_any_thread
at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.24.0/src/platform_impl/linux/mod.rs:605:9
2: winit::platform_impl::platform::EventLoop<T>::new
at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.24.0/src/platform_impl/linux/mod.rs:556:9
3: winit::event_loop::EventLoop<T>::with_user_event
at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.24.0/src/event_loop.rs:134:25
4: winit::event_loop::EventLoop<()>::new
at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.24.0/src/event_loop.rs:120:9
5: neovide::window::window_wrapper::start_loop
at /root/parts/neovide/build/src/window/window_wrapper/mod.rs:434:22
6: neovide::window::create_window
at /root/parts/neovide/build/src/window/mod.rs:106:5
7: neovide::main
at /root/parts/neovide/build/src/main.rs:201:5
8: core::ops::function::FnOnce::call_once
at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```
Please let me know what other information you need.

**Comment by xmers** [comment]
I'm running into the same issue. 

```
neovide
thread 'main' panicked at 'Failed to initialize any backend! Wayland status: NoCompositorListening X11 status: XOpenDisplayFailed', /root/.cargo/git/checkouts/winit-cdba476763ae8f28/3b5462e/src/platform_impl/linux/mod.rs:626:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
```
$ neovide --version
Neovide 0.7.0
$ RUST_BACKTRACE=1 neovide 
thread 'main' panicked at 'Failed to initialize any backend! Wayland status: NoCompositorListening X11 status: XOpenDisplayFailed', /root/.cargo/git/checkouts/winit-cdba476763ae8f28/3b5462e/src/platform_impl/linux/mod.rs:626:9
stack backtrace:
Ignored client type property: "methods"
Ignored client type property: "attributes"
   0: rust_begin_unwind
             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:493:5
   1: std::panicking::begin_panic_fmt
             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:435:5
   2: winit::platform_impl::platform::EventLoop<T>::new_any_thread
             at /root/.cargo/git/checkouts/winit-cdba476763ae8f28/3b5462e/src/platform_impl/linux/mod.rs:626:9
   3: winit::platform_impl::platform::EventLoop<T>::new
             at /root/.cargo/git/checkouts/winit-cdba476763ae8f28/3b5462e/src/platform_impl/linux/mod.rs:581:9
   4: winit::event_loop::EventLoop<T>::with_user_event
             at /root/.cargo/git/checkouts/winit-cdba476763ae8f28/3b5462e/src/event_loop.rs:134:25
   5: winit::event_loop::EventLoop<()>::new
             at /root/.cargo/git/checkouts/winit-cdba476763ae8f28/3b5462e/src/event_loop.rs:120:9
   6: neovide::window::window_wrapper::start_loop
             at /root/parts/neovide/build/src/window/window_wrapper/mod.rs:204:22
   7: neovide::window::create_window
             at /root/parts/neovide/build/src/window/mod.rs:50:5
   8: neovide::main
             at /root/parts/neovide/build/src/main.rs:198:5
   9: core::ops::function::FnOnce::call_once
             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```
Running on Ubuntu 21.04

**Comment by 88srzh** [comment]
Ubuntu 20.04 with Wayland
`srzh@srzhVM ~ (master)> RUST_BACKTRACE=1 neovide
thread 'main' panicked at 'Failed to initialize any backend! Wayland status: NoCompositorListening X11 status: XOpenDisplayFailed', /root/.cargo/git/checkouts/winit-cdba476763ae8f28/3b5462e/src/platform_impl/linux/mod.rs:626:9
stack backtrace:
Ignored client type property: "methods"
Ignored client type property: "attributes"
   0: rust_begin_unwind
             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:493:5
   1: std::panicking::begin_panic_fmt
             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:435:5
   2: winit::platform_impl::platform::EventLoop<T>::new_any_thread
             at /root/.cargo/git/checkouts/winit-cdba476763ae8f28/3b5462e/src/platform_impl/linux/mod.rs:626:9
   3: winit::platform_impl::platform::EventLoop<T>::new
             at /root/.cargo/git/checkouts/winit-cdba476763ae8f28/3b5462e/src/platform_impl/linux/mod.rs:581:9
   4: winit::event_loop::EventLoop<T>::with_user_event
             at /root/.cargo/git/checkouts/winit-cdba476763ae8f28/3b5462e/src/event_loop.rs:134:25
   5: winit::event_loop::EventLoop<()>::new
             at /root/.cargo/git/checkouts/winit-cdba476763ae8f28/3b5462e/src/event_loop.rs:120:9
   6: neovide::window::window_wrapper::start_loop
             at /root/parts/neovide/build/src/window/window_wrapper/mod.rs:204:22
   7: neovide::window::create_window
             at /root/parts/neovide/build/src/window/mod.rs:50:5
   8: neovide::main
             at /root/parts/neovide/build/src/main.rs:198:5
   9: core::ops::function::FnOnce::call_once
             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.`

**Comment by dhelbegor** [comment]
Anyone found a solution for this error?
I'm getting the following error on Linux Mint 20 Cinnamon.

`thread 'main' panicked at 'Failed to initialize any backend! Wayland status: NoCompositorListening X11 status: XOpenDisplayFailed', /root/.cargo/git/checkouts/winit-cdba476763ae8f28/3b5462e/src/platform_impl/linux/mod.rs:626:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace`

**Comment by ayhon** [comment]
Same issue on Ubuntu Budgie 21.04, under X11

**Comment by kaustubhbabar5** [comment]
I was facing the same issue on Ubuntu 18.04, but managed to run it by building from main branch.

**Comment by Vikram-Hegde** [comment]
Same issue on Pop!_OS 21.04 on Wayland. 
I tried with ```snap install neovide``` only

**Comment by codeRSH** [comment]
Facing same issue on Manjaro 21.1.0. Running X11 server.

**Comment by aelobdog** [comment]
Works on Ubuntu 20.04 if you follow the build instructions and from source (main branch)

**Comment by 88srzh** [comment]
> Works on Ubuntu 20.04 if you follow the build instructions and from source (main branch)

srzh@srzhik:~/neovide/target/release$ RUST_BACKTRACE=1 neovide
srzh@srzhik:~/neovide/target/release$ xkbcommon: ERROR: /snap/neovide/132/usr/share/X11/locale/ru_RU.UTF-8/Compose:46:9: failed to open included Compose file "/usr/share/X11/locale/en_US.UTF-8/Compose": No such file or directory
xkbcommon: ERROR: /snap/neovide/132/usr/share/X11/locale/ru_RU.UTF-8/Compose:46:9: failed to parse file
libEGL warning: DRI2: failed to authenticate
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: CreationErrors([NoAvailablePixelFormat, OsError("Couldn't find any available vsync extension")])', src/window/window_wrapper/mod.rs:287:10
stack backtrace:
   0: rust_begin_unwind
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:517:5
   1: core::panicking::panic_fmt
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/panicking.rs:101:14
   2: core::result::unwrap_failed
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/result.rs:1617:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/result.rs:1299:23
   4: neovide::window::window_wrapper::create_window
             at /root/parts/neovide/build/src/window/window_wrapper/mod.rs:280:28
   5: neovide::main
             at /root/parts/neovide/build/src/main.rs:171:5
   6: core::ops::function::FnOnce::call_once
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

**Comment by MultisampledNight** [comment]
@88srzh That snap thing seems quite like #1248 by the way, not like the originally reported issue.

**Comment by Kethku** [comment]
Closing as this is stale and likely works now

**Comment by RegBl** [comment]
I just ran into the same issue installing from snap. I'm on Ubuntu 22.04.

**Comment by MeBadDev** [comment]
I ran into the same issue too, I'm on Zorin OS 16.3 (x86-64)

**Comment by fredizzimo** [comment]
@MeBadDev 

The snap package is very out of date and broken, there's also very little chance of fixing it without help https://forum.snapcraft.io/t/need-help-with-the-snap-for-neovide/35978, so we should probably take it down.

I suggest, that you use the appimage, from the releases instead.
