### ISSUE TITLE
Cannot double click to open files with Neovide.app on macOS

### ISSUE THREAD

**Issue by grantyap** [neovide/neovide#644]
Opening files whose default app is set to Neovide.app (from `cargo bundle --release`) does not work on macOS.

For example, I might have a `file.txt`. I can right click -> Get Info, which lets me set Neovide.app as the default app. However, when I double click `file.txt`, Neovide opens a blank document as if I double clicked Neovide.app itself.

Using the `e` command and clicking and dragging work still as expected.

**Comment by Kethku** [comment]
Thanks for doing the investigation! I agree.

**Comment by shaunsingh** [comment]
If you don't mind the off-topic question, how did you get neovide to launch on double click? It still crashes for me on start

**Comment by FrankOu2001** [comment]
When will this issue be solved? I can open a file by dragging it to Neovide's window, but double click the file Neovide still opens a blank document.

**Comment by kabouzeid** [comment]
I can't even open a file by dragging it onto Neovide

**Comment by shaunsingh** [comment]
> When will this issue be solved? I can open a file by dragging it to Neovide's window, but double click the file Neovide still opens a blank document.

Until https://github.com/rust-windowing/winit/pull/1759 we can't really make progress on this issue, as the double-click event isn't implemented in winit yet. Once thats merged, its fairly straightforward to tell neovide what to do

**Comment by MultisampledNight** [comment]
(provided that we can backport the patch to our branch, of course)

**Comment by xbladesub** [comment]
Open new buffer on file click - maybe we can achieve it with applescript? Not sure how to do it exactly, but I suppose with automator app referencing to neovide executable you can take path from the clicked file and pass it to neovide. (clicked file by default should be opened with automator app which has reference to neovide executable).

**Comment by ryancsh** [comment]
Probably related to this, but on Windows.

Double clicking on a file does not open the actual file. Instead, neovide opens a blank file with escaped name instead. E.g. say I double click on file with path `C:\folder\file.txt`, Neovide opens a blank `C:\\folder\\file.txt`.

Drag and drop into Neovide window works correctly.

(Tried building with commit 56916b50a573845ddae59daac83f3c3cb4060269.)

**Comment by fredizzimo** [comment]
This was fixed by:
* https://github.com/neovide/neovide/pull/2395
