### ISSUE TITLE
Scroll doesn't work with floaterm

### ISSUE THREAD

**Issue by luisiacc** [neovide/neovide#646]
When using floaterm, scroll doesn't work inside the floaterm window, it only scrolls the code behind(the code itself)

**Comment by Kethku** [comment]
Thats very strange. Do you have multigrid enabled? An admittedly old version of floaterm works in my config just fine.

**Comment by luisiacc** [comment]
Whats is multigrid?

**Comment by Kethku** [comment]
https://github.com/Kethku/neovide/wiki/Configuration#multiGrid

**Comment by luisiacc** [comment]
I just tried with that option, it doesn't work either, and also the fonts is very blurry.
![image](https://user-images.githubusercontent.com/31720261/118232891-350efe80-b45f-11eb-9673-37995170d79d.png)

**Comment by Kethku** [comment]
That issue is a repeat of https://github.com/Kethku/neovide/issues/720

**Comment by Kethku** [comment]
This is fixed in main. (note: you will need a recent version of neovim)
