### ISSUE TITLE
Neovide panics when bitmap font is used

### ISSUE THREAD

**Issue by DavidHusicka** [neovide/neovide#656]
I tried to use Terminus and Cozette fonts. Neither of them worked and both of them caused Neovide to panic. Both are bitmap fonts so there is most likely and issue with bitmap fonts. Vector fonts seem to work.

```
Ignored client type property: "methods"
Ignored client type property: "attributes"
Ignored style attribute: "standout"
thread 'main' panicked at 'Could not create surface', src/renderer/rendered_window.rs:40:6
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

I tried following settings in my `init.vim` file
```
set guifont=Terminus:h12
set guifont=Terminus
set guifont=Cozette
```

**Comment by Kethku** [comment]
@DavidHusicka could not create surface is a graphics issue not a font issue. Can you try the opengl branch?

**Comment by DavidHusicka** [comment]
The opengl branch works but the font rendering looks horrible. 

Neovide:
![image](https://user-images.githubusercontent.com/25853767/118397414-158cf700-b654-11eb-893a-43bd0720d992.png)

Alacritty:
![2021-05-16-143612_491x243_scrot](https://user-images.githubusercontent.com/25853767/118397424-2178b900-b654-11eb-9c86-f941e8a0f660.png)

I'd like to mention that this is not an issue with my hardware since it supports fairly new graphics APIs and I never had any issues running any sort of graphically intensive tool or game. One of my acquaintance, who recommended me neovide, managed to reproduce this panic by using the same font. The panic does not occur when I don't change the font.

**Comment by Kethku** [comment]
The font rendering issue should be fixable on the opengl branch. Seems like it might be rendering at the wrong resolution. Or possibly the surface is being rendered at a subpixel position and is interpolating.

**Comment by Kethku** [comment]
I have reproed the issue on my side. Its very possible that skia doesn't support bitmap fonts. We'll see.

**Comment by Kethku** [comment]
Font rendering has changed significantly. This likely works now
