### ISSUE TITLE
Neovide fails to start

### ISSUE THREAD

**Issue by SunJukebox** [neovide/neovide#688]
I cannot get neovide to run on my arch linux machine without aborting. I followed the [instructions](https://github.com/Kethku/neovide/blob/main/README.md#with-non-default-branch) for compiling neovide ("opengl" branch) and had no issues compiling. I have already tried the "main" vulkan branch, but my hardware isn't supported by the  [vulkan drivers for Intel](https://archlinux.org/packages/extra/x86_64/vulkan-intel/). Starting neovide produces the following error message:

> Ignored client type property: "methods"
Ignored client type property: "attributes"
WARN [neovide::editor] editor resize 1
WARN [neovide::editor] viewport event received before window initialized
[xcb] Unknown sequence number while processing queue
[xcb] Most likely this is a multi-threaded client and XInitThreads has not been called
[xcb] Aborting, sorry about that.
neovide: xcb_io.c:269: poll_for_event: Assertion `!xcb_xlib_threads_sequence_lost' failed.
Aborted (core dumped)

**Comment by Kethku** [comment]
Thats wild. @j4qfrost do you have any ideas? Seems like an X issue

**Comment by j4qfrost** [comment]
@sunjukebox are you using Wayland?

**Comment by SunJukebox** [comment]
@j4qfrost No, I'm using X11.

**Comment by j4qfrost** [comment]
How do you start neovide? With cargo run?

**Comment by SunJukebox** [comment]
No, I have only tried running neovide from dmenu and in the terminal (as in "$ neovide"). That error message was returned when I ran neovide from the terminal.

**Comment by worldpe** [comment]
I have this same issue as well.

**Comment by j4qfrost** [comment]
Were either of you able to run neovide successfully in any case?

**Comment by worldpe** [comment]
No, I was not.

**Comment by j4qfrost** [comment]
Are you using mesa drivers? This might be what you're running into https://github.com/rust-windowing/glutin/issues/1034

**Comment by Kethku** [comment]
The opengl branch has been merged into main.

**Comment by Avimitin** [comment]
Got the same error too:

```text
Ignored client type property: "methods"
Ignored client type property: "attributes"
[xcb] Unknown sequence number while processing queue
[xcb] Most likely this is a multi-threaded client and XInitThreads has not been called
[xcb] Aborting, sorry about that.
neovide: xcb_io.c:269: poll_for_event: Assertion
`!xcb_xlib_threads_sequence_lost' failed.
fish: Job 1, 'neovide' terminated by signal SIGABRT (Abort)
```

**Comment by wesleyjrz** [comment]
It was working the first time I installed using AUR, but I got this error after reboot my PC.

```
[xcb] Unknown sequence number while processing queue
[xcb] Most likely this is a multi-threaded client and XInitThreads has not been called
[xcb] Aborting, sorry about that.
neovide: xcb_io.c:269: poll_for_event: Assertion `!xcb_xlib_threads_sequence_lost' failed.
```

**Comment by wesleyjrz** [comment]
It works for me every time I install it (from AUR), but after reboot my PC it suddenly starts to fail.

When installed:
![Screenshot_20210911_154807](https://user-images.githubusercontent.com/60184588/132958955-e6c6c9fc-6b29-48f8-8ac0-2b98cb14db02.png)

After reboot:
![Screenshot_20210911_161528](https://user-images.githubusercontent.com/60184588/132959036-06941f85-1b86-4e83-b935-ce25a5a57a6e.png)

**Comment by Kethku** [comment]
I have no idea or knowledge about the graphics stack on linux. So I'm unlikely to be of any help here. If anybody else who has more experience with linux would be willing to pitch in, that would be great

**Comment by grx6741** [comment]
I too have the same problem, im on arch if I run neovide on i3 I get the error, but if I run it on gnome then no problem occurs

**Comment by hathawayANdRX105** [comment]
I also have the same err message when using terminal to start up neovide in i3 , but it can be start up by rofi

**Comment by luiz00martins** [comment]
Same error as wesley, on Arch KDE.

However, it only happens sometimes, seemingly at random (about 50/50), the other times it starts up normally.

**Comment by Kethku** [comment]
I have a suspicion that this may be a winit/glutin issue. Its possible this has already been fixed, and we just need to update the winit/glutin fork to take advantage of the new fix

**Comment by Kethku** [comment]
Closing as this is stale and likely works now
