### ISSUE TITLE
Latency on M1 MacBook Pro with a 4K display

### ISSUE THREAD

**Issue by jamesgecko** [neovide/neovide#690]
I'm using Neovide's `opengl` branch on an M1 MacBook Pro. I tried connecting to a 4K display (Dell P2715Q) at my office using one of the smaller macOS scaling options.
<img width="780" alt="Screen Shot 2021-05-27 at 2 44 05 PM" src="https://user-images.githubusercontent.com/44252/119880246-0cc0de80-befa-11eb-97ab-f4d7da8fd4ca.png">

When using a full screen window with three vertical splits and the `guifont` setting `JetBrains\ Mono:h13`, Neovide is _really_ laggy. It's a little noticeable moving between splits, and borderline unusable when typing text, with what feels like a half second pause before typed characters appear on the screen. I can improve performance by setting a larger `guifont` size or a larger macOS scaling option.

I do not have noticeable latency when connecting to my 1440p display at native resolution at home.

Maybe this is a really demanding edge case? Gvim and Neovim in iTerm2 handle this fine.

**Comment by Kethku** [comment]
Did you build and run in release mode? I use a 4k monitor on windows constantly without issue. This should work

**Comment by shaunsingh** [comment]
I run both a 1440p and 4k monitor with my m1 MacBook as well. OpenGL branch runs smoothly, with 4 splits and nvim-tree open

**Comment by jamesgecko** [comment]
I did build in release mode. I’m not sure; maybe some of my plugins are interfering? I’ll upload my dotfiles presently. I don’t have regular access to the display; is there any info I could collect next time I’m in the office to help pin this down?

**Comment by shaunsingh** [comment]
> is there any info I could collect next time I’m in the office to help pin this down?

I'm not sure about neovide itself, but vim has several profiling tools built in, Maybe try them out to make sure the issues are with neovide and not your configuration? 

You can also try neovide out with a clean init.vim

**Comment by last-partizan** [comment]
Can you check this now?

We're merged some scaling refactoring, which may have fixed issue.

**Comment by bmulholland** [comment]
FYI I am on a new 16" MBP with M1 Pro and just tried out neovide on my 4k monitor with scaled text. It's speedy and works great.

**Comment by Kethku** [comment]
In that case I'm going to close this and focus on perf issues over here: https://github.com/neovide/neovide/issues/740
