### ISSUE TITLE
Feature request: Suppport app argument to open files or folders when we drag drop them

### ISSUE THREAD

**Issue by h4kbas** [neovide/neovide#696]
As far as I observed there is no way to open my files by simply dragging them into the app like Vs code. Can you handle the incoming app  arguments to open folders or files if we send a parameter on cmd or drag them into the app?

**Comment by PyGamer0** [comment]
Does it already do that?

**Comment by h4kbas** [comment]
Nope it does not care the files, i have to open the app and use :e to edit a new file

**Comment by h4kbas** [comment]
Version 0.6.0 (2021041315)
MacOS BIg Sur 11.0.1 

Oh, I don't know but it doesn't work for me, interesing

**Comment by PyGamer0** [comment]
@h4kbas try building neovide or get an executable from [here(https://github.com/Kethku/neovide/actions/runs/984701889)

**Comment by fredizzimo** [comment]
This was fixed for macOS in
* https://github.com/neovide/neovide/pull/2395
