### ISSUE TITLE
[Feat] Add Homebrew support for macOS

### ISSUE THREAD

**Issue by shaunsingh** [neovide/neovide#713]
As someone who has to switch between Macs often, its a pain to manually download neovide every time. 

There are two options with homebrew, a [Formula](https://docs.brew.sh/Formula-Cookbook), or a [Cask](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md)

Formulas are used to install executables. The benefits with a formula would be 
1. You have the option to build from source 
2. If you add it as a [Tap](https://docs.brew.sh/Taps), we can store the formula in this repository, and we can allow users to build with options (e.g. --openGL)
The drawback is that we can't ship full .app binaries, and its harder to make than a cask 

Casks on the other hand are used to install prebuilt .app binaries. The benefits would be
1. Its much easier to make
2. We can ship the .app builds GitHub actions generates, 

Personally I believe casks are the way to go (something like `brew install --cask neovide`). The only issue we would need to solve is https://github.com/Kethku/neovide/issues/447. After the app works as expected (double click to open) it should be fairly straightforward grabbing the latest release.

Keep in mind 
1. With a cask you can't have separate versions (Vulcan and openGL). I think its best to wait until the openGL branch is merged into main 
2. We need a static URL to pull the releases from. Personally I think we should have actions grab the latest build from a workflow and publish it under releases. Manually creating a new "stable" release might be another option 
3. The Cask has to be pull-requested to Homebrew's repo. Unlike taps, we don't have as much control over it 

If its fine with you, I'll get started on it

**Comment by Kethku** [comment]
Absolutely fine with me. I'm sending you a contributor invite as you've been pretty involved.

Some thoughts:
- Vulkan vs Opengl is going to become a non issue in the not too distant future as I'm really pushing to get the opengl branch merged soon. Then we will have one build anyway.
- As for the cask vs formula issue, I think a cask is the way to go as well. Building neovide can be painful, so if we can make a prebuilt binary, then I'm down. One question I have: how does it interact with m1 vs x86 macs? Do we have to build a binary with both m1 and x86 support?
- Releases: Is it possible to have a unstable and stable version of a homebrew app? We could have two urls one for the latest release (which once opengl merges I'm planning on making) and another for the current ci build.

I agree that we probably have to solve #447. But I personally don't have a mac. @j4qfrost might be able to make headway at some point, but I think they're busy working on m1 build support. Do you have any ideas what might be going wrong there?

**Comment by j4qfrost** [comment]
@Kethku I'll look this weekend. The work with M1 is pretty much done, since I confirmed that a valid arm binary was created and passes the tests.

**Comment by shaunsingh** [comment]
> As for the cask vs formula issue, I think a cask is the way to go as well. Building neovide can be painful, so if we can make a prebuilt binary, then I'm down. One question I have: how does it interact with m1 vs x86 macs? Do we have to build a binary with both m1 and x86 support?

You can publish separate binaries for intel and Apple Silicon Macs, and then homebrew can detect the architecture and download the correct one ([example](https://github.com/Homebrew/homebrew-cask/blob/1f61e750be062d0c14ed2f6986da6af66b84996d/Casks/intellij-idea.rb#L4))

> Releases: Is it possible to have a unstable and stable version of a homebrew app? We could have two urls one for the latest release (which once opengl merges I'm planning on making) and another for the current ci build.

You can do this via [homebrew-casks-versions](https://github.com/Homebrew/homebrew-cask-versions). The cask submitted to the main repo would be the stable one. We can then submit a nightly build (the one that comes from the ci) to homebrew-casks-versions, and install it via `brew install neovide-nightly`

**Comment by j4qfrost** [comment]
It might be prudent to wait until opengl is merged, then it would be a bit less crazy to make releases on github, which will give us URLs we can link in cask.

**Comment by Kethku** [comment]
I'm finishing up some last issues with opengl. I'm hoping to get it merged sometime today

**Comment by shaunsingh** [comment]
> It might be prudent to wait until opengl is merged, then it would be a bit less crazy to make releases on github, which will give us URLs we can link in cask.

I have the rest of the cask setup now, just need to add the link. Would you prefer having the CI automatically release any artifacts produced from the `main` branch, or would you prefer to manually release a stable build from time to time?

In my opinion, the "nightly" build is always stable enough so it shouldn't be an issue, but let me know if you prefer to keep stable and nightly separate

**Comment by Kethku** [comment]
I'm somewhat torn personally. I've observed that lots of folks use the release as the latest known stable which in the past has worked well, but then once we get close to another release I end up telling people to just go use the main branch as its fixed a lot of things since last cut.

I wonder if a "both and" would be better. I like the model some projects use where they cut releases manually as a way to highlight and explain features, but then also have a nightly build for those are feeling spicy.

**Comment by shaunsingh** [comment]
This is a sample cask for the 0.5.0 release 

```ruby
cask "neovide" do
  version "0.5.0"
  sha256 "6efe7d83309b5f389f5faa4f70a59ea093ae7dac0d6099aee76faef158c4a68a"

  url "https://github.com/Kethku/neovide/releases/download/latest/static/link/to/download"
  name "neovide"
  desc "No Nonsense Neovim Client in Rust"
  homepage "https://github.com/Kethku/neovide"

  app  "Neovide.app"
end
```

We can also make it version agnostic by removing the checksum e.g. 
```ruby
cask "neovide" do
  version "(next major version)"
  sha256 :no_check

  url "https://github.com/Kethku/neovide/releases/download/static/link/to/download"
  name "neovide"
  desc "No Nonsense Neovim Client in Rust"
  homepage "https://github.com/Kethku/neovide"

  app  "Neovide.app"
end
```

**Comment by nustiueudinastea** [comment]
Hey folks, is this work able to proceed or the opengl dependency is still not fixed?

Thanks for this nice project and work!

**Comment by Kethku** [comment]
I have not pushed this forward myself. I know that a metal backend is possible but I don't have a mac device so I can't push it myself.

**Comment by Kethku** [comment]
I'm happy to assist anybody if somebody wants to take it on! Its a great way to get into rust if anybody is interested.

**Comment by shaunsingh** [comment]
I don't think opengl should be an issue with homebrew, its included with the system after all. I can also specify dependencies if nessecary 

BTW @Kethku, sorry for my inactivity on the the project lately (studies picked up again). Do you think neovide is stable enough for packaging now, or should I wait for the 0.8.0 release? I saw that nixpkgs added a package a while back

**Comment by MitchellMarkGeorge** [comment]
Any update on this? Would really like to use this.

**Comment by shaunsingh** [comment]
Originally I was waiting for the v0.8 release, which isn't going to happen for a while. I'll create a homebrew package neovide based on this commit: https://github.com/neovide/neovide/commit/2689bccbb947c7d098f5e8843b26401ee4672168 for now. 

ETA about a week or so, I'm thinking of making it a formula instead of a cask to make it easier for dev purposes.

**Comment by nustiueudinastea** [comment]
hey @shaunsingh, are you still planning on doing this? otherwise I might give it a shot.

**Comment by shaunsingh** [comment]
Soon, exams finish up next week so I can start working more on projects. If you want to tackle it earlier then you can go ahead, the basic cask code is here already: https://github.com/neovide/neovide/issues/713#issuecomment-860284842, and making a formula for a rust project is fairly straightforward.

**Comment by nustiueudinastea** [comment]
Thanks for the update @shaunsingh. I will wait. Good luck on those exams!

**Comment by shaunsingh** [comment]
Just an update on this, I've written the homebrew files, but homebrew requires you follow some sort of release structure, so I can't just lock it to a commit. Soon however we should hopefully have a new stable release of neovide. After which I can PR the cask code to homebrew. 

Hang in there, just another week or two (hopefully)

**Comment by shaunsingh** [comment]
Safe to say its been a bit longer than a week or two, but finally a new release! I'll get Homebrew sorted out

**Comment by danielo515** [comment]
Today I installed neovide on an M1 apple macbook pro. Many thanks! I guess this issue can be closed?

**Comment by bmulholland** [comment]
I just switched my install to homebrew, too :). I did have to do the "right-click > open" workaround because "Apple couldn't verify the developer," though.

**Comment by danielo515** [comment]
> I just switched my install to homebrew, too :). I did have to do the "right-click > open" workaround because "Apple couldn't verify the developer," though.

yes, also had to so this, a classic between osx users

**Comment by shaunsingh** [comment]
Yup, enjoy everyone!

> I just switched my install to homebrew, too :). I did have to do the "right-click > open" workaround because "Apple couldn't verify the developer," though.

I think this is to do with how Homebrew installs things, sorry we can't fix that on our end.
