### ISSUE TITLE
Document new settings and commandline options

### ISSUE THREAD

**Issue by Kethku** [neovide/neovide#721]
I've neglected to document in the wiki all the new settings and commandline options. This needs updated to make sure things are in sync.

**Comment by shaunsingh** [comment]
I'll get started on it. I believe the only Command-line option not document is --frameless, correct?

**Comment by Kethku** [comment]
Note to self: I removed some of the existing settings that weren't working. So those should be removed as well

**Comment by Jesspu** [comment]
I think --frameless is now named --frame, but the docs (README.md) still say --frameless. 

Running neovide 0.8.0 on windows. 

`Neovide 0.8.0
keith <keith@the-simmons.net>
Neovide: No Nonsense Neovim Gui

USAGE:
    neovide [FLAGS] [OPTIONS] [files_to_open]... [-- <neovim_args>...]

FLAGS:
    -h, --help         Prints help information
        --log          Log to a file
        --maximized    Maximize the window
        --multigrid    Enable Multigrid
        --nofork       Do not detach process from terminal
        --noidle       Render every frame. Takes more power and cpu time but possibly fixes animation issues
        --nosrgb       Do not use standard color space to initialize the window. Swapping this variable sometimes fixes
                       issues on startup
    -V, --version      Prints version information
        --wsl          Run in WSL

OPTIONS:
        --frame <frame>                      Configure the window frame. NOTE: Window might not be resizable if setting
                                             is None.
        --geometry <geometry>                Specify the Geometry of the window
        --neovim-bin <neovim_bin>            Specify path to neovim
        --remote-tcp <remote_tcp>            Connect to Remote TCP
        --wayland-app-id <wayland_app_id>    Specify an App ID for Wayland
        --x11-wm-class <x11_wm_class>        Specify an X11 WM class

ARGS:
    <files_to_open>...    Files to open
    <neovim_args>...      Specify Arguments to pass down to neovim
neovide ----frame`

**Comment by Kethku** [comment]
This is finished with the website and command line processing
