### ISSUE TITLE
Latest release is still built on the Vulcan backend 

### ISSUE THREAD

**Issue by shaunsingh** [neovide/neovide#726]
As Neovide has had a fair share of general improvements over the past 2-3 months, as well as a big jump to using openGL as a backend, is it possible to create a new stable release?

**Comment by Kethku** [comment]
Yes. But I think we should resolve the linux keyboard issue first either by using scancodes or by pulling the in progress PRs into a fork and building on top of that.

I have started the second option, but it may take some time.

**Comment by Kethku** [comment]
https://github.com/Kethku/neovide/issues/445 Keyboard handling
https://github.com/Kethku/neovide/issues/720 Floating window transparency issues
https://github.com/Kethku/neovide/issues/740 Winit framerate

I think these are the current blocking issues for a new release

**Comment by Kethku** [comment]
Addressed
