### ISSUE TITLE
Iosevka ligatures messed up

### ISSUE THREAD

**Issue by Kethku** [neovide/neovide#742]
![image](https://user-images.githubusercontent.com/3323631/122976130-e6e7f780-d348-11eb-8bf2-2d351df2661d.png)

Looks like our handling of iosevka is wrong.

1. Determine if this issue is upstream using the swash testing app
2. Do some investigation about how ligatures are formed with iosevka
3. Take this learning and adjust the glyph positioning system to handle this edge case

**Comment by PyGamer0** [comment]
https://github.com/be5invis/Iosevka/issues/1007#issuecomment-842871090

Pretty sure this would be of help

**Comment by mjoork** [comment]
Iosevka **Term** TTF [v7.2.4](https://github.com/be5invis/Iosevka/releases/tag/v7.2.4) ligatures display perfectly on my machine.

![Iosevka Term ligatures in Neovide](https://user-images.githubusercontent.com/20644474/124353251-1d0d5d00-dc0e-11eb-98f1-edaadbf37090.png)

**Comment by mjoork** [comment]
On the other hand, I am having a different kind of problem with Iosevka **Super TTC** variants.
All apps on Windows see Iosevka properly, except for Neovide. Neovide uses the super-light weight. It is understandable, because the first font in the TTC is the lightest one.

![Iosevka Super TTC](https://user-images.githubusercontent.com/20644474/124353530-b38e4e00-dc0f-11eb-9901-dcac073d9064.png)

![Iosevka Term Super TTC](https://user-images.githubusercontent.com/20644474/124353539-c30d9700-dc0f-11eb-9a2c-4e6afaba4deb.png)

Perhaps this is because of the way underlying lib handles fonts? It doesn't yet understand TTC?

**Comment by PyGamer0** [comment]
maybe the problem is i am using a custom build?

**Comment by PyGamer0** [comment]
@mjoork is that the latest version???

**Comment by mjoork** [comment]
@PyGamer0 Why yes, Iosevka [7.2.4](https://github.com/be5invis/Iosevka/releases/tag/v7.2.4) and Neovide [0.5.0](https://github.com/Kethku/neovide/releases/tag/0.5.0). Perhaps I wasn't clear enough... latest _release_.

**Comment by mjoork** [comment]
Downloaded pre-release [0.7.0](https://github.com/Kethku/neovide/releases/tag/0.7.0) just now and here's how it looks like. Renders perfect ligatures.

![Iosevka ligs in neovide 0.7.0](https://user-images.githubusercontent.com/20644474/124392579-29251780-dcff-11eb-9278-fa672ed110fa.png)

The only thing that bothers me is the missing Windows logo. This is not a big deal, but why would it suddenly disappear?

![side-by-side neovide 0.7.0 & 0.5.0](https://user-images.githubusercontent.com/20644474/124392876-66d67000-dd00-11eb-98cc-03a3ae1318df.png)

**Comment by PyGamer0** [comment]
@mjoork That release is old; neovide has updated a lot since then, try getting a build from [here](https://github.com/Kethku/neovide/actions/runs/999114845)

**Comment by Kethku** [comment]
We're working on newer releases but there's some bugs that should be fixed first

**Comment by mjoork** [comment]
@Kethku, @PyGamer0, I see, I will try it. Thank you for being nice to me btw 😊

**Comment by mjoork** [comment]
Fira Code ligatures display fine
![image](https://user-images.githubusercontent.com/20644474/124427372-fb2dea80-dd73-11eb-9740-f0d77c2b3e20.png)

Cascadia Code ligatures display fine too
![image](https://user-images.githubusercontent.com/20644474/124427655-56f87380-dd74-11eb-87c6-b876926179f3.png)

Iosevka ligatures don't display at all, is there some kind of guard added to not display them for now?
![image](https://user-images.githubusercontent.com/20644474/124427516-26183e80-dd74-11eb-973b-ee9964b76f0b.png)
![image](https://user-images.githubusercontent.com/20644474/124429553-b48dbf80-dd76-11eb-9b6c-cea9545999c2.png)

**Comment by PyGamer0** [comment]
![image](https://user-images.githubusercontent.com/64531844/127269426-e4084430-4fdf-49fc-b415-9df659daf987.png)

I figured out it was upstream

**Comment by Kethku** [comment]
Awesome. I created an upstream issue here: https://github.com/dfrg/swash/issues/15

**Comment by dfrg** [comment]
Apologies all. This one's on me. I pushed a fix that seems to address it.

![iosevka](https://user-images.githubusercontent.com/420008/127316041-2ddaa60f-fac6-4203-8268-48cad2be0259.png)

**Comment by Kethku** [comment]
I will update the swash version shortly

**Comment by Kethku** [comment]
Done. Iosevka should be fixed

**Comment by Kethku** [comment]
Looks like the glyphs are selected correctly now, but there is some rendering weirdness...
![image](https://user-images.githubusercontent.com/3323631/127371263-eaf35ad5-fee3-4ca0-8bca-f88ca63d6d43.png)
![image](https://user-images.githubusercontent.com/3323631/127371279-1f6839e8-9261-4923-87e5-5ac8037c7781.png)
![image](https://user-images.githubusercontent.com/3323631/127371319-a52d88b0-e0f5-4308-a77e-3262c0abfe2d.png)

I think whats going on is that the anti aliasing is being done per glyph and these longer ligatures are made up of multiple glyphs. This means that the line of pixels at the edge of the glyph are rendered strangely.

Some possible solutions:
- When we detect that a string of characters is being positioned off of the normal grid, take the suggested positioning rather than rounding to the nearest grid position
- Expose a setting for turning off the anti aliasing (this is a bandaid)
- Think harder about how to render on a grid without accumulating pixel errors over the course of a line...

**Comment by dfrg** [comment]
And extended ligatures should now be working in Fira Code...
![fira_code](https://user-images.githubusercontent.com/420008/127464092-9f1dd5c6-482e-4c91-9ab5-d7a1ae3d1e32.png)

**Comment by Kethku** [comment]
Closing as this is fixed on my machine. Thanks again @dfrg
