### ISSUE TITLE
Lua configuration toggle not working 

### ISSUE THREAD

**Issue by yoramdelangen** [neovide/neovide#745]
**Describe the bug**
Toggle fullscreen does not work with lua configuration (`vim.g.neovide_fullscreen`). When set `vim.g.neovide_fullscreen` to true and start neovide its working like expected. I have tested it with transparency as well but its not working either.

**To Reproduce**
I made a very simple toggle function in Lua:
```lua
vim.api.nvim_set_keymap('n', '<leader><S-f>', "<cmd>lua require'v-gui/neovide'.toggleFullscreen()<cr>")

M = {}
function M.toggleFullscreen()
  vim.g.neovide_fullscreen = not vim.g.neovide_fullscreen 
  -- trigger via CMD works!!
  -- vim.cmd('let g:neovide_fullscreen=! g:neovide_fullscreen')
  print('toggle fullscreen to '.. tostring(vim.g.neovide_fullscreen))
end
return M
```
Print statement "toggle fullscreen to ..." works fine.

Manually trigger:
```
:lua vim.g.neovide_fullscreen = not vim.g.neovide_fullscreen
```
or 
```
:lua vim.g.neovide_fullscreen = true -- or false of course
```

**Expected behavior**
Should work exactly as `let g:neovide_fullscreen=! g:neovide_fullscreen` or manually set on true. When using `vim.cmd` to run the command its working as expected.

**Screenshots/clip**
EDIT: Tried to show a clip of the situation, how it didn't but via vimscript it does. https://imgur.com/a/7InOTqM

**Desktop (please complete the following information):**
 - OS: 11.2.3 (20D91)
 - Neovide Version: Neovide 0.7.0 (build from source commit: 113a3f421cc4aa36aa2bea7dfe8b8926f41ba2d6)
 - Neovim Version: NVIM v0.5.0-dev+1429-gb585f723b -- LuaJIT 2.1.0-beta3

**Log**
It's the entire log file (but a little truncated for first time copy-pasta) but from the point I thought was useful until `:q`. If necessary i can make one for the working version as well (using vim.cmd and let g:neovide_fullscreen).

[neovide_rCURRENT.log](https://github.com/Kethku/neovide/files/6700903/neovide_rCURRENT.log)

**Comment by PyGamer0** [comment]
Does it work in vimscript?

**Comment by yoramdelangen** [comment]
@PyGamer0 yes it does. cmd version:
![Screenshot 2021-06-23 at 15 17 00](https://user-images.githubusercontent.com/1531885/123103295-23dde800-d436-11eb-8786-4cf307e362ee.png)

**Comment by Kethku** [comment]
This is a gnarly issue and likely an upstream problem. We get variable change notifications using dictwatcheradd. If I'm following your issue correctly it seems like dictwatcheradd doesn't properly notify when the variable is modified by lua. I will verify that this is an issue and raise it upstream.

**Comment by clason** [comment]
Just to make sure: be aware of the different truthiness rules of vimscript and Lua: https://github.com/nanotee/nvim-lua-guide#caveats-3

**Comment by Kethku** [comment]
This is indeed an upstream issue with a fix tracked here https://github.com/neovim/neovim/pull/15373

**Comment by MultisampledNight** [comment]
Upstream PR was merged, you'll need to run a development version of neovim or wait for a new neovim release to use it.
