### ISSUE TITLE
Enable customization of the undercurl

### ISSUE THREAD

**Issue by Shatur** [neovide/neovide#764]
**Describe the bug**

Undercurl looks like a dotted line:

![изображение](https://user-images.githubusercontent.com/22453358/123540561-4b8bc380-d748-11eb-9cd3-98a37b6c18b8.png)

**To Reproduce**
1. `hi SpellBad gui=undercurl guisp=Red`
2. `hi SpellBad`

**Expected behavior**
![изображение](https://user-images.githubusercontent.com/22453358/123540635-b50bd200-d748-11eb-9a2f-9f962cd69610.png)

**Current behavior**
![изображение](https://user-images.githubusercontent.com/22453358/123540748-424f2680-d749-11eb-85e0-f7af11dbdf52.png)

**Desktop (please complete the following information):**
 - OS: Linux
 - Neovide Version: 82b745c92bb6dab1402aef70b9c8e07a02979a41 (latest commit at the time of writing)
 - Neovim Version: bdf3df4027a5389a46b4c9a75b50aff5c0ecb351 (latest commit at the time of writing)

**Please run `neovide --log` and paste the contents of the `.log` file here:**

[neovide_rCURRENT.log](https://github.com/Kethku/neovide/files/6721384/neovide_rCURRENT.log)

**Comment by Kethku** [comment]
I would argue this is a nitpick rather than a bug. Is there a big benefit to doing undercurls as a wavy line? The dashed line was done just because its the simplest to implement, but in using it I've actually grown to like it.

Maybe a better request here is to give a way to customize the underline graphic. Maybe underline, dashed, wave, other??

**Comment by Shatur** [comment]
> Maybe a better request here is to give a way to customize the underline graphic. Maybe underline, dashed, wave, other??

I would render this as undercurl. This is how it implemented in all editors (not even just all Neovim clients). I even thought that this is a bug :)

**Comment by Kethku** [comment]
Note: this isn't strictly true. There are some neovim guis which render it as an underline.

I think I'm gonna swap this to an enhancement and label it "add customization of undercurl rendering". But honestly there are some bigger fish to fry atm. I will get back to this, but it may be a bit

**Comment by Shatur** [comment]
> Note: this isn't strictly true. There are some neovim guis which render it as an underline.

Did not know.
I used Neovim Qt, Gonvim, firenvim and oni2 - all of them renders undercurl as undercurl (expected). Also GVim behaves the same.

> I think I'm gonna swap this to an enhancement and label it "add customization of undercurl rendering". But honestly there are some bigger fish to fry atm. I will get back to this, but it may be a bit

You may find this PR useful for the algorithm of the implementation: https://github.com/equalsraf/neovim-qt/pull/803

**Comment by clason** [comment]
Are you sure that this is not in fact an undercurl that is just clipped to much (so it cuts off the lower part of the curl, leaving a dotted line)?

I've noticed a similar off-center cut-off where the _top_ of lines is cropped too much (most visible in floats):
<img width="450" alt="Screenshot 2021-06-28 at 10 19 40" src="https://user-images.githubusercontent.com/2361214/123603616-5acb4980-d7fa-11eb-951f-cbbd40fe729e.png">
(Note how the top of the parentheses touches the float boundary, while there is ample space at the bottom.)

**Comment by calops** [comment]
> I would argue this is a nitpick rather than a bug. Is there a big benefit to doing undercurls as a wavy line?

I don't know if it was like that at the time of this question, but there's a very simple reason now: neovim supports multiple "underlining" style, including `undercurl`, `underdotted` and `underdashed`. It seems pretty straightforward to me that these should all be supported (and look different by default) by neovide.

**Comment by calops** [comment]
I'll add another point: currently in neovide, `undercurl` is "supported" (as a weird, uneven dashed line), while `underdotted` and  `underdashed` aren't (nothing is displayed).
