### ISSUE TITLE
Same font is displayed differently between latest and vulkan release version

### ISSUE THREAD

**Issue by dineshKumar777** [neovide/neovide#772]
I am using Hack font in neovim. When opening same file in both version of neovide noticing fonts are displayed little bit different (compiled and downloaded from releases)
OS: windows 10
Note: Please edit the title correctly.
Hack sample img from official site: https://sourcefoundry.org/hack/assets/img/mockup/js-source-specimen.png

![hackfontdiff](https://user-images.githubusercontent.com/21097695/123835905-b7c41e00-d926-11eb-8544-5103a7548fdc.png)

it seems space between character is less now in latest. Notice spaces in SKIP_INDEXES
Verify with other fonts and increase default space betw characters.

![init](https://user-images.githubusercontent.com/21097695/122704305-0e6b9100-d271-11eb-878b-dfde5d5aba2b.png)

**Comment by Kethku** [comment]
This is expected. Previously the system used the font shaper to position glyphs. For normal text editors this is desirable but for editors that operate on a grid, it causes more problems than its worth. Now glyphs are positioned based on a heuristic that determines the grid size.

I think the solution here is similar to https://github.com/Kethku/neovide/issues/481. A configuration option should be provided for those who wish to tweak the grid size as I'm not convinced there is a valid solution for the general case to make it more like the shaped text positioning.

What do you think?

**Comment by dineshKumar777** [comment]
Configuration option would be great.

**Comment by dineshKumar777** [comment]
@Kethku as per our previous discussion for Hack font difference are minimal.
Today when I tried [Monoflow font](https://finaltype.de/en/projects/monoflow) it looks like a different font compared to others. Working correctly in vulkan app, alacritty and sublime text. what could be the issue here?

![image](https://user-images.githubusercontent.com/21097695/126592040-6ef7fe9a-e3e0-4edc-939b-2371806ba010.png)


os: Windows 10
[neovide_rCURRENT.log](https://github.com/Kethku/neovide/files/6860077/neovide_rCURRENT.log)

**Comment by Kethku** [comment]
that is super weird... I have no idea what could be causing this

**Comment by Kethku** [comment]
@dineshKumar777 does this issue still happen in main? Please reopen if so.
