### ISSUE TITLE
Improve font selection experience

### ISSUE THREAD

**Issue by Hubro** [neovide/neovide#776]
Currently switching fonts is a huge pain. Font names have to be very particularly formatted, and though Neovide no longer crashes when a font name is improperly formatted, it still locks up and becomes almost completely unresponsive. For me, the quickest way to try again is still to kill Neovide through `htop` and restart it.

GVim has the ability to bring up a font selector dialog if you write `:set guifont=*`. Would it be possible to do something similar in Neovide?

Alternatively, would it be possible to set up tab completion with properly formatted font names for all fonts on the system?

---

Specifically, my current issue is that I'm not able to select "Droid Sans Mono" as my font:

```
➜ fc-list | grep -i droid | grep DroidSansMono
/usr/share/fonts/droid/DroidSansMono.ttf: Droid Sans Mono:style=Regular
```

If I `:set guifont=Droid\ Sans\ Mono:h14`, the window locks up in much the same way as if I had written `:set guifont=florpglorp`, so I assume it's not formatted to swash/skia font finder's standards.

**Comment by Kethku** [comment]
Something like this should be possible. The only difficulty is figuring out how to populate such a completion list. Despite spending so much time building this neovim gui, I don't actually know all that much about writing neovim plugins. If somebody has any insight for how they might provide a completion list using neovim apis, that would go a long way toward solving this issue.

**Comment by Kethku** [comment]
This is implemented!
