### ISSUE TITLE
Neovide accepts wm keybindings as input

### ISSUE THREAD

**Issue by vinicius507** [neovide/neovide#777]
**Describe the bug**
Neovide inputs window manager keybindings as if they were nvim commands/text input.

**To Reproduce**
1. Run AwesomeWM
2. Run Neovide
3. Try to run a global keybinding while in input mode
4. It will print a keycode e.g `<D-1>`

**Expected behavior**
Ignore keybindings, as nvim running in the terminal does.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Neovide Version 0.7.0
 - Neovim Version 0.5.0-dev+1455-gf83c25942

**Comment by PyGamer0** [comment]
Are you getting neovide from releases or from actions?

**Comment by vinicius507** [comment]
> Are you getting neovide from releases or from actions?
> If from releases try building from the main branch.

AUR neovide-git package.

**Comment by jsosulski** [comment]
I noticed the same behaviour, I built from main branch this morning. For what its worth I am using neovide in KDE Plasma, i.e. with KWin.

**Comment by MR-TLL** [comment]
Hey just have the same issue in dwm on Arch , whenever i use the keybindings to change the workspace weird <D-1><D-2> comes in neovide when in insert mode , i use the latest neovide-git from aur.

**Comment by smolck** [comment]
Any chance someone could `git bisect` to see where this issue was introduced? I have a feeling it was one of the recent keyboard-related fixes, and knowing which one/ones would be quite helpful.

**Comment by jjhayes84** [comment]
I have the same issue with Qtile wm on Arch (AUR git package).

**Comment by vinicius507** [comment]
No news on this issue? I'd love to help but I have 0 knowledge of Rust :/

**Comment by vinicius507** [comment]
Just built from master again and the bug is not happening anymore. Closing.
