### ISSUE TITLE
Can't override init.vim with -u option on mac osx

### ISSUE THREAD

**Issue by svermeulen** [neovide/neovide#787]
**Describe the bug**
I am building neovide with:

```
cargo build --release
cargo bundle --release
```

This produces a `.app` folder at `/target/release/bundle/osx/Neovide.app`

I'd like to then execute `Neovide.app` and override the default init.vim being used, but can't seem to figure out how to do this

**To Reproduce**

Things I've tried:

This works and correctly opens neovide with the given file:

`open -n -a [path to Neovide.app] --args [path to file]`

However this does not open neovide at all:

`open -n -a [path to Neovide.app] --args [path to file] -u [path to init.vim]`

Same with this:

`open -n -a [path to Neovide.app] --args [path to file] -- -u [path to init.vim]`

**Expected behavior**

It should be possible to override the default `init.vim` on mac osx

**Desktop (please complete the following information):**
 - OS: macOS Big Sur 11.4
 - Neovide Version: current master HEAD (0d8311f)
 - Neovim Version: 0.5.0

**Please run `neovide --log` and paste the contents of the `.log` file here:**

Tried adding `--log` to the arguments to `Neovide.app` but did not see any log produces

**Additional context**

**Comment by shaunsingh** [comment]
You might be able to launch the neovide executable itself (show app contents, it should be inside neovide somewhere)

**Comment by svermeulen** [comment]
Ok I tried executing that directly instead.  I can execute `Neovide.app/Contents/MacOS/neovide --help` and I see:

```
Neovide 0.7.0
keith <keith@the-simmons.net>
A simple GUI for Neovim.

USAGE:
    neovide [FLAGS] [OPTIONS] [files]... [-- <neovim_args>...]
```

I can also execute `Neovide.app/Contents/MacOS/neovide --log` and I do get the log output to the current directory.

However, I am still unable to pass any neovim arguments.  Any time I add `--` as suggested above, it just fails to open and also does not produce a log file.  For example: `Neovide.app/Contents/MacOS/neovide --log -- -c "echom 5"`

**Comment by svermeulen** [comment]
Ok so I just tried this again with the latest version and it seems to be working now
