### ISSUE TITLE
Swap to an Org

### ISSUE THREAD

**Issue by Kethku** [neovide/neovide#788]
Recently with the attempts to have an M1 mac as a build machine, the influx of contributors, and interest in porting Neovide's renderer to other editors, there has been a call to move Neovide to its own organization. I'm interested in peoples thoughts, so here are the pros and cons that I know of.

Pros:
- We can more easily extract parts of Neovide into subrepos if needed. In particular I'm thinking about a website for the project, maybe a terminal-esque renderer crate or similar.
- More control for access permissions. As far as I can understand it, GitHub only lets me add contributors to a project, and doesn't give much more in the way of permissions granularity. We've run into this with the M1 github action runner.
- The project can become less dependent on me. This is a big deal imho. I have been driving the project but I don't think it should have to be that way. I'm not planning on going anywhere, but I would like for others to be able to feel ownership of the project just as much or more than me.

Cons:
- Sponsorship becomes more muddy. Currently it sorta makes sense (for some definition of sense) that sponsorships would go to me. I'm trying to funnel sponsorship and kofi donations back into the project through purchasing of hardware and sponsoring related projects, but maybe that changes with an org structure? I'm interested in peoples thoughts or if folks know of other models they have worked with that seemed to work well
- Swapping to an org may break existing links. I am pretty sure this would modify where the project lives in GitHub. I could definitely swap it to an org and create a dummy repository on my account which links to the new location, but it would definitely break existing links to the project. This may extend to package managers as well so we'd probably have to go track down current maintainers of them and get them to update.

I'm sure I've missed both pros and cons. I'm new to this, so I'm very much looking for advice either way :)

**Comment by shaunsingh** [comment]
> Sponsorship becomes more muddy. 

Even though there are several contributors to the project, you have contributed the most to this project. I'm only speaking for myself, but I believe its fair to continue with the current method (i.e. let you decide what to do with the donations).

> Swapping to an org may break existing links. 

Luckily I believe any links of the old repo automatically redirect to newer ones, so this should be a non-issue. More info here: https://docs.github.com/en/github/administering-a-repository/managing-repository-settings/transferring-a-repository#whats-transferred-with-a-repository

**Comment by kilpkonn** [comment]
For the links I think you can also recreate "personal" neovide repo with existing code and add a big disclaimer that repo has moved and then you can also archive repo. Therefore if someone has external link to repo that is not updated he can still find up to date code. 
I'd say archiving is needed as otherwise there will be some issues at the wrong repo and that's pain to manage and also uncomfortable for others.

**Comment by Kethku** [comment]
Done. Github handles redirects automatically, so I just ran with it. I have sent organization invites to all current contributors

**Comment by j4qfrost** [comment]
I keep forgetting to boot up the Mac. Will start setting up the runner. Sorry I've been busy.

**Comment by Kethku** [comment]
No worries whatsoever

**Comment by j4qfrost** [comment]
I'll need higher privileges to set up the runner for the org.
