### ISSUE TITLE
Too many files open issue

### ISSUE THREAD

**Issue by smit2909** [neovide/neovide#797]
**Describe the bug**
After a working on a project..for a sufficiently long time, i'd say 15 minutes or more, too many files open issue starts popping up. I dont get this issue while using neovim in terminal. 

**To Reproduce**
1. Open neovide, I opened a django project, only 3 active buffers. ( I reckon more buffers will help reproduce this issue)
2. Then after some editing, this issue will pop

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.10
 - Neovide Version: Branch 755-scale-artifacts from the fork of last-partizan, but the issue was persistent in the master branch of this repo as well
 - Neovim Version 0.5

**Please run `neovide --log` and paste the contents of the `.log` file here:**
xkbcommon: ERROR: /usr/share/X11/locale/iso8859-1/Compose:39:34: string literal is not a valid UTF-8 string
xkbcommon: ERROR: /usr/share/X11/locale/iso8859-1/Compose:40:29: string literal is not a valid UTF-8 string
xkbcommon: ERROR: /usr/share/X11/locale/iso8859-1/Compose:41:29: string literal is not a valid UTF-8 string
xkbcommon: ERROR: /usr/share/X11/locale/iso8859-1/Compose:42:29: string literal is not a valid UTF-8 string
xkbcommon: ERROR: /usr/share/X11/locale/iso8859-1/Compose:43:29: string literal is not a valid UTF-8 string
xkbcommon: ERROR: /usr/share/X11/locale/iso8859-1/Compose:44:27: string literal is not a valid UTF-8 string
xkbcommon: ERROR: /usr/share/X11/locale/iso8859-1/Compose:45:27: string literal is not a valid UTF-8 string
xkbcommon: ERROR: /usr/share/X11/locale/iso8859-1/Compose:46:27: string literal is not a valid UTF-8 string
xkbcommon: ERROR: /usr/share/X11/locale/iso8859-1/Compose:47:27: string literal is not a valid UTF-8 string
xkbcommon: ERROR: /usr/share/X11/locale/iso8859-1/Compose:48:29: string literal is not a valid UTF-8 string
xkbcommon: ERROR: /usr/share/X11/locale/iso8859-1/Compose:49:29: string literal is not a valid UTF-8 string
xkbcommon: ERROR: /usr/share/X11/locale/iso8859-1/Compose:49:29: too many errors
xkbcommon: ERROR: /usr/share/X11/locale/iso8859-1/Compose:49:29: failed to parse file
Ignored client type property: "methods"
Ignored client type property: "attributes"
thread 'tokio-runtime-worker' panicked at 'Focus Gained Failed: NeovimError(Some(0), "Vim(call):E903: Process failed to start: too many open files: \"/usr/bin/sh\"")', src/bridge/ui_commands.rs:114:18
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Additional context**

1. After this issue, write process becomes unbearably slow. On a small file of mere 100 lines, it takes about 2-3 to write.
2. I am using autoformatter for formatting python files on save. I tried disabling it, it does not help. This is issue does occur when neovide is freshly started. after sometime it starts giving this too many files open error and becomes sluggish
3. Keep a buffer open for longer times and then observe the write times. It increases if the buffer is old.
4. I will test this and keep adding logs and screenshots as i encounter this. I have been facing this issue since i started using neovide.

![error1](https://user-images.githubusercontent.com/79797111/124549980-98108680-de4d-11eb-9b1a-a55c6fc2888f.png)
![error2](https://user-images.githubusercontent.com/79797111/124549985-9cd53a80-de4d-11eb-85c3-611e268cc48c.png)

After pressing enter, the error dissappears, and if try to write using :w after it, error popups up again..more severly
![error3](https://user-images.githubusercontent.com/79797111/124550433-41f01300-de4e-11eb-9c56-ed3a016c2daa.png)

![error4](https://user-images.githubusercontent.com/79797111/124569740-d749d200-de63-11eb-80e2-151cec7c7b62.png)

**Comment by Kethku** [comment]
This seems like an upstream issue. But theres some things that would help to isolate it:

1. I'm guessing you tried, but does this repro in terminal vim?
2. Could you try to repro with another multigrid enabled gui such as https://github.com/akiyosi/goneovim (great project btw :D)
3. What about without your vim config. Does it happen then?

**Comment by PyGamer0** [comment]
Can you remove gitgutter and see if you can reproduce the issue??df

**Comment by smit2909** [comment]
> Can you remove gitgutter and see if you can reproduce the issue??

I tried removing git gutter, but the same kind of error pops up for a different plugin. I will remove git gutter for the day and try to reproduce the issue.

@Kethku 
1. I tried in terminal vim, never encountered this error.
2. I haven't tried goneovim though..i will test using that and keep you updated. If this issue is solved i cant see myself going back to terminal vim, Kudos to all contributors!
3. Without vim config,..do you mean i should try it vanilla neovim and no plugins?

**Comment by Kethku** [comment]
1. That figures. I think it has to do with multgrid somehow
2. That would be a good thing to try as goneovim has a good multigrid implementation. To my knowledge not many of the other guis do it correctly
3. Yes. Please try with `neovide -- --clean`

**Comment by smit2909** [comment]
1. I tried with no git gutter plugin today. Did not get that error but found consistent crashing of neovide with below error. Will keep testing without the plugin for another day and then I will jump to goneovim then and try using that with gitgutter. I did use it briefly, did not throw me any errors, but i would like to verify it by using it for a full day of work with git gutter.

xkbcommon: ERROR: /usr/share/X11/locale/iso8859-1/Compose:39:34: string literal is not a valid UTF-8 string
xkbcommon: ERROR: /usr/share/X11/locale/iso8859-1/Compose:40:29: string literal is not a valid UTF-8 string
xkbcommon: ERROR: /usr/share/X11/locale/iso8859-1/Compose:41:29: string literal is not a valid UTF-8 string
xkbcommon: ERROR: /usr/share/X11/locale/iso8859-1/Compose:42:29: string literal is not a valid UTF-8 string
xkbcommon: ERROR: /usr/share/X11/locale/iso8859-1/Compose:43:29: string literal is not a valid UTF-8 string
xkbcommon: ERROR: /usr/share/X11/locale/iso8859-1/Compose:44:27: string literal is not a valid UTF-8 string
xkbcommon: ERROR: /usr/share/X11/locale/iso8859-1/Compose:45:27: string literal is not a valid UTF-8 string
xkbcommon: ERROR: /usr/share/X11/locale/iso8859-1/Compose:46:27: string literal is not a valid UTF-8 string
xkbcommon: ERROR: /usr/share/X11/locale/iso8859-1/Compose:47:27: string literal is not a valid UTF-8 string
xkbcommon: ERROR: /usr/share/X11/locale/iso8859-1/Compose:48:29: string literal is not a valid UTF-8 string
xkbcommon: ERROR: /usr/share/X11/locale/iso8859-1/Compose:49:29: string literal is not a valid UTF-8 string
xkbcommon: ERROR: /usr/share/X11/locale/iso8859-1/Compose:49:29: too many errors
xkbcommon: ERROR: /usr/share/X11/locale/iso8859-1/Compose:49:29: failed to parse file
Ignored client type property: "methods"
Ignored client type property: "attributes"
ko^[^[fish: Job 1, “/home/smit/neovide_source/neovi…” terminated by signal SIGSEGV (Address boundary error)

**Comment by smit2909** [comment]
@Kethku 

- I could not get the gitgutter like too many files open issue, but just like yesterday, it consistently kept crashing on me. I ran neovide with --logs args and found below logs. I tried with different shells, terminals, etc. It is consistently reproducible. Just crashes after a some time of use or idle.

Ignored client type property: "methods"
Ignored client type property: "attributes"
Ignored style attribute: "fg_indexed"
Ignored style attribute: "fg_indexed"
Ignored style attribute: "fg_indexed"
Ignored style attribute: "fg_indexed"
Ignored style attribute: "fg_indexed"
Ignored style attribute: "fg_indexed"
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 4, kind: Interrupted, message: "Interrupted system call" }', /home/smit/.cargo/git/checkouts/winit-cdba476763ae8f28/3b5462e/src/platform_impl/linux/x11/mod.rs:396:54
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by smit2909** [comment]
@Kethku 
I added RUST_BACKTRACE as 1 to my config.fish, below are logs when it crash, after ~30 mins of editing a file.

xkbcommon: ERROR: /usr/share/X11/locale/iso8859-1/Compose:39:34: string literal is not a valid UTF-8 string
xkbcommon: ERROR: /usr/share/X11/locale/iso8859-1/Compose:40:29: string literal is not a valid UTF-8 string
xkbcommon: ERROR: /usr/share/X11/locale/iso8859-1/Compose:41:29: string literal is not a valid UTF-8 string
xkbcommon: ERROR: /usr/share/X11/locale/iso8859-1/Compose:42:29: string literal is not a valid UTF-8 string
xkbcommon: ERROR: /usr/share/X11/locale/iso8859-1/Compose:43:29: string literal is not a valid UTF-8 string
xkbcommon: ERROR: /usr/share/X11/locale/iso8859-1/Compose:44:27: string literal is not a valid UTF-8 string
xkbcommon: ERROR: /usr/share/X11/locale/iso8859-1/Compose:45:27: string literal is not a valid UTF-8 string
xkbcommon: ERROR: /usr/share/X11/locale/iso8859-1/Compose:46:27: string literal is not a valid UTF-8 string
xkbcommon: ERROR: /usr/share/X11/locale/iso8859-1/Compose:47:27: string literal is not a valid UTF-8 string
xkbcommon: ERROR: /usr/share/X11/locale/iso8859-1/Compose:48:29: string literal is not a valid UTF-8 string
xkbcommon: ERROR: /usr/share/X11/locale/iso8859-1/Compose:49:29: string literal is not a valid UTF-8 string
xkbcommon: ERROR: /usr/share/X11/locale/iso8859-1/Compose:49:29: too many errors
xkbcommon: ERROR: /usr/share/X11/locale/iso8859-1/Compose:49:29: failed to parse file
Ignored client type property: "methods"
Ignored client type property: "attributes"
memory allocation of 250880 bytes failed
fish: Job 1, “/home/smit/neovide_source/neovi…” terminated by signal SIGABRT (Abort)

**Comment by Kethku** [comment]
Uhh am I seeing that right that it's an out of memory error?

**Comment by smit2909** [comment]
> Uhh am I seeing that right that it's an out of memory error?

yeah..felt strange to me as well, I have 16 gigs of ram and only slack and datagrip were open, I am not exactly able to pinpoint why. I can very positively say that i would have atleast 5-6 gigs of free ram when it crashed! 

There is always some SIG*** in the error, in previous error messages, it was SIGSEGV (Address boundary error). Got this one now. Are these two errors related by any way?

I dont know anything about rust at all, I have been using neovide since 3 days, without gitgutter, and consistently crashes, i tried fish shell, bash shell. I also switched my desktop environments (xmonad and gnome-desktop), but happens all the same!

**Comment by smit2909** [comment]
@Kethku 
I recently got the below error, does this help in pinpointing the issue?

Ignored client type property: "methods"
Ignored client type property: "attributes"
fatal runtime error: Rust cannot catch foreign exceptions
fish: Job 1, “/home/smit/neovide_source/neovi…” terminated by signal SIGABRT (Abort)

**Comment by smit2909** [comment]
@Kethku 
Rust backtrace upon crash today. This mod.rs also popped up in some error above:

Ignored client type property: "methods"
Ignored client type property: "attributes"
thread 'main' panicked at 'RwLock reader count overflow', /home/smit/.cargo/registry/src/github.com-1ecc6299db9ec823/parking_lot-0.10.2/src/raw_rwlock.rs:691:30
stack backtrace:
   0: rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::option::expect_failed
   3: core::option::Option<T>::expect
             at /tmp/rust-20210622-7429-1rifwd/rustc-1.53.0-src/library/core/src/option.rs:349:21
   4: parking_lot::raw_rwlock::RawRwLock::lock_shared_slow::{{closure}}
             at /home/smit/.cargo/registry/src/github.com-1ecc6299db9ec823/parking_lot-0.10.2/src/raw_rwlock.rs:689:25
   5: parking_lot::raw_rwlock::RawRwLock::lock_common
             at /home/smit/.cargo/registry/src/github.com-1ecc6299db9ec823/parking_lot-0.10.2/src/raw_rwlock.rs:1061:16
   6: parking_lot::raw_rwlock::RawRwLock::lock_shared_slow
             at /home/smit/.cargo/registry/src/github.com-1ecc6299db9ec823/parking_lot-0.10.2/src/raw_rwlock.rs:707:9
   7: <parking_lot::raw_rwlock::RawRwLock as lock_api::rwlock::RawRwLock>::lock_shared
             at /home/smit/.cargo/registry/src/github.com-1ecc6299db9ec823/parking_lot-0.10.2/src/raw_rwlock.rs:109:26
   8: lock_api::rwlock::RwLock<R,T>::read
             at /home/smit/.cargo/registry/src/github.com-1ecc6299db9ec823/lock_api-0.3.4/src/rwlock.rs:352:9
   9: neovide::settings::Settings::get
             at /home/smit/neovide_source/neovide/src/settings/mod.rs:74:25
  10: neovide::window::window_wrapper::GlutinWindowWrapper::synchronize_settings
             at /home/smit/neovide_source/neovide/src/window/window_wrapper/mod.rs:68:28
  11: neovide::window::window_wrapper::start_loop::{{closure}}
             at /home/smit/neovide_source/neovide/src/window/window_wrapper/mod.rs:265:9
  12: winit::platform_impl::platform::sticky_exit_callback
             at /home/smit/.cargo/git/checkouts/winit-cdba476763ae8f28/3b5462e/src/platform_impl/linux/mod.rs:760:5
  13: winit::platform_impl::platform::x11::EventLoop<T>::run_return
             at /home/smit/.cargo/git/checkouts/winit-cdba476763ae8f28/3b5462e/src/platform_impl/linux/x11/mod.rs:326:17
  14: winit::platform_impl::platform::x11::EventLoop<T>::run
             at /home/smit/.cargo/git/checkouts/winit-cdba476763ae8f28/3b5462e/src/platform_impl/linux/x11/mod.rs:421:9
  15: winit::platform_impl::platform::EventLoop<T>::run
             at /home/smit/.cargo/git/checkouts/winit-cdba476763ae8f28/3b5462e/src/platform_impl/linux/mod.rs:676:56
  16: winit::event_loop::EventLoop<T>::run
             at /home/smit/.cargo/git/checkouts/winit-cdba476763ae8f28/3b5462e/src/event_loop.rs:154:9
  17: neovide::window::window_wrapper::start_loop
             at /home/smit/neovide_source/neovide/src/window/window_wrapper/mod.rs:257:5
  18: neovide::window::create_window
             at /home/smit/neovide_source/neovide/src/window/mod.rs:94:5
  19: neovide::main
             at /home/smit/neovide_source/neovide/src/main.rs:200:5
  20: core::ops::function::FnOnce::call_once
             at /tmp/rust-20210622-7429-1rifwd/rustc-1.53.0-src/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

**Comment by Kethku** [comment]
Honestly I'm at an absolute loss. These crashes are in seemingly random parts of the app. I can't help but feel that its something specific to your system since I haven't seen crash reports similar to this before...

**Comment by Kethku** [comment]
Shot in the dark: please try with current main as many things have changed between then and now. Please reopen if you find issues persist.
