### ISSUE TITLE
neovide won't show if set up for git mergetool

### ISSUE THREAD

**Issue by artkpv** [neovide/neovide#805]
Neovide doesn't show up if set up for git mergetool. How to setup it for mergetool? 

Steps:
1. .gitconfig:

```
[core]
	editor = \"neovide\"
# ...
[merge]
	tool = neovide
# ..
[mergetool "neovide"]
  cmd = neovide -f -c \"Gdiffsplit!\" \"$MERGED\"

```
2. Run `git merge`. Then `git mergetool`

Result: neovide window opens and instantly closes. 

Expected: neovide window stays.

**Desktop**
 - OS Name:                   MS Windows 10 Pro
 - OS Version:                10.0.19042 N/A Build 19042
 - Neovide Version 0.7.0
 - Neovim Version v0.4.4

**Please run `neovide --log` and paste the contents of the `.log` file here:**

Nothing. No files opens. No command output.

**Additional context**
If I run it random parameter (neovide --anythinghere) it flushes and instantaneously closes.

**Comment by Kethku** [comment]
I think you might need to use `neovide -- -f -c \"Gdiffsplit!\" \"$MERGED\"`

**Comment by Kethku** [comment]
Specifically the -- indicates following arguments should be passed to neovim directly

**Comment by artkpv** [comment]
Doesn't work. The same flash of a window and instant closing. 

BTW. It works for nvim, it opens it in the same terminal (i want the neovide thought because of colors, etc.). Here is the config:
```
[merge]
	tool = nvim

[mergetool "nvim"]
  cmd = nvim -f -c \"Gdiffsplit!\" \"$MERGED\"

```

**Comment by fredizzimo** [comment]
`--no-fork` is the default in Neovim 0.13.0 so this should now work out of the box.
