### ISSUE TITLE
Smeary-cursor issues with Terminal mode

### ISSUE THREAD

**Issue by shaunsingh** [neovide/neovide#809]
**Describe the bug**
The cool "smeary" cursor sometimes does not work in terminal mode (`:term` or `:terminal`). 

**To Reproduce**
1. Open neovide 
2. type :term
3. type/run anything in terminal
4. The cursor will act like a typical non-smeary cursor 
5. scroll or click around with the mouse 
6. the cursor will work as expected

You can also 
1. Open neovide 
2. type :term
3. type/run any tuis in there terminal (tested with `emacs -nw` and `vim`)
4. The cursor will act like a typical non-smeary cursor, even after clicking around 

**Expected behavior**
The smeary cursor should always work in terminal mode. I like the smeary effect and it would be nice if I could use it for emacs and other terminal applications as well. 

**Screenshots**

https://user-images.githubusercontent.com/71196912/124965678-64219680-dff0-11eb-92cd-2776eb5b3b17.mov

**Desktop (please complete the following information):**
 - OS: MacOS 12.0b2
 - Neovide version: Latest commit from git, built manually (0.7.0)
 - Neovim version: 
```zsh
NVIM v0.6.0-dev+1489-gdf33f30e8
Build type: Release
LuaJIT 2.1.0-beta3
```

**Additional context**
Not exactly related to the issue, but if you notice in non-smeary mode, the cursor color matches the text its on. Is this something you might be interested in adding to the smeary-cursor as well?

**Comment by Kethku** [comment]
This is an upstream bug. Terminal in neovim fakes a cursor by using highlights rather than actually sending cursor movement. This isn't something we can fix on our side.

**Comment by Kethku** [comment]
Closing as this isn't an issue with neovide but rather the rendering of upstream neovim
