### ISSUE TITLE
When guifont is set Neovide becomes slow and unstable

### ISSUE THREAD

**Issue by 21eleven** [neovide/neovide#818]
**Describe the bug**
If I don't set `guifont` in my `init.lua` then the text in neovide is too small. After reading #3, I added  `vim.opt.guifont = 'Consolas:h32'` to my `init.lua`. This however causes Neovide to become very slow and occasionally crash.

**To Reproduce**
1. Be on archlinux running the sway window manager
2. Install neovide like so `paru -S neovide-git`
3. Add  `vim.opt.guifont = 'Consolas:h32'` to the `init.lua`
4. Open neovide
5. Experience slowness, maybe even a crash, lack of visual effects

**Expected behavior**
Normal neovide speed and visuals but with a larger font

**Screen record**
[normal good performance](https://imgur.com/a/QCfSJH2) without `guifont` set
[guifont set, degraded performance, crashes randomly](https://imgur.com/a/AGR24Wh)

**Desktop details**
 - OS: Arch Linux 5.12.14-arch1-1
 - Window Manager: [Sway](https://github.com/swaywm/sway) 1.6.1
 - Neovide Version: 0.7.0
 - Neovim Version: v0.5.0-dev+1434-g24e0c16fd
 - GPU: Radeon RX 5700 XT

`neovide --log` output:
```
Ignored client type property: "methods"
Ignored client type property: "attributes"
```

**Comment by PyGamer0** [comment]
Do you have Consolas installed? (if i am right its only available on win10). Which version of neovide?

**Comment by last-partizan** [comment]
I have seen similar bug before.

I was able to reproduce bug this way:

1. Start neovide with my default font (`JetBrainsMono Nerd Font:h11`)
2. Switch to Fira: `:set guifont=Fira\ Code:h11`.

**Comment by verajosemanuel** [comment]
this very same procedure makes my neovide crash
