### ISSUE TITLE
Neovide crashes after start

### ISSUE THREAD

**Issue by shift-d** [neovide/neovide#825]
**Describe the bug**
If i try to launch neovide.exe downloaded from github actions' last build (a527c0e) it crashes right after starting.

**To Reproduce**
1. Go to Github Actions
2. Download build a527c0e
3. Launch neovide
4. See how it crashes

**Expected behavior**
It should not crash..?

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Neovide Version a527c0e build
 - Neovim Version 0.5.0

**Please run `neovide --log` and paste the contents of the `.log` file here:**
INFO [neovide::window::window_wrapper] icon created
INFO [neovide::bridge] Starting neovim with: Command { std: "C:\\Users\\shift\\scoop\\shims\\nvim.EXE" "--embed", kill_on_drop: false }

**Additional context**
Neovim was downloaded using scoop.
Executable builded manually from source crashes too.
Executable downloaded from github releases works.

**Comment by Kethku** [comment]
Does the executable built manually give any additional crash details? What happens when you run without a vim config (neovide -- --clean)?

**Comment by shift-d** [comment]
1. no, it does not
2. same behaviour

**Comment by shift-d** [comment]
After trying out 334c2d7, same issue.
(I need to use latest builds because latest published prerelease has bug with displaying autocomplete)
Sadly, have to use stable build

**Comment by shift-d** [comment]
Issue is still present on 5991117

**Comment by shift-d** [comment]
same behaviour on f6a8ffc

**Comment by shift-d** [comment]
After running with RUST_BACKTRACE=full:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: NoAvailablePixelFormat', src\window\window_wrapper\mod.rs:239:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by Kethku** [comment]
There is more investigation here: https://github.com/neovide/neovide/issues/907 closing in favor of that more detailed issue.
