### ISSUE TITLE
Font Ligatures don't render with PragmataPro font

### ISSUE THREAD

**Issue by dustinroepsch** [neovide/neovide#827]
**Describe the bug**
Font Ligatures aren't being rendered, (or maybe they are being rendered the same color as the background color)

**To Reproduce**
1. Compile the main branch with `cargo --build Release` on MacOS Big Sur (x86_64 CPU)
2. Set your guifont to PragmataPro Mono Liga
3. Open neovide and type text that should produce ligatures

**Expected behavior**
The ligature should render

**Screenshots**
![image](https://user-images.githubusercontent.com/5170924/125714973-87325dd5-562b-4dee-b850-909ca155e1a8.png)
In this photo, the -> between state and the other variables isn't being displayed. It should look like 
```c
state->memory
state->v
```
When I move the cursor on top of the ligature, the part under the cursor renders though:
![image](https://user-images.githubusercontent.com/5170924/125715153-f44c54b3-450d-40fd-8311-e79a51d37e04.png)

**Desktop (please complete the following information):**
 - OS: Reproduced on MacOS  (11.4) and  Linux (Pop!_OS)
 - Neovide Version: main:latest (commit cacde9ec9d00f932ec4f6ba78d59d0b235008cd8 as of writing)
 - Neovim Version: 0.5.0

**Please run `neovide --log` and paste the contents of the `.log` file here:**
Ignored client type property: "methods"
Ignored client type property: "attributes"
Ignored style attribute: "fg_indexed"

**Additional context**
Here's the relevant parts of my init.vim

```
" Insert spaces whenever tab key is pressed
set tabstop=4 shiftwidth=4 expandtab

set relativenumber
set nowrap

nnoremap <silent> <C-p> :GFiles<cr>
nnoremap <C-t> :NERDTreeToggle<CR>

call plug#begin('~/.vim/plugged')

Plug 'tpope/vim-surround'
Plug 'tpope/vim-commentary'
Plug 'tpope/vim-fugitive'
Plug 'tpope/vim-abolish'
Plug 'dracula/vim', { 'as': 'dracula' }
Plug 'NLKNguyen/papercolor-theme'
Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
Plug 'junegunn/fzf.vim'
Plug 'neoclide/coc.nvim', {'branch': 'release'}
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'gruvbox-community/gruvbox'
Plug 'preservim/nerdtree'
Plug 'sheerun/vim-polyglot'
Plug 'lifepillar/vim-solarized8'
Plug 'justinmk/vim-sneak'

call plug#end()

set background=dark
colorscheme gruvbox
" Set the font for NeoVide
" https://github.com/Kethku/neovide
set guifont=PragmataPro\ Mono\ Liga:h15
```

**Comment by shaunsingh** [comment]
Working for me with FiraCode: 
<img width="846" alt="image" src="https://user-images.githubusercontent.com/71196912/125719224-2e69be4b-3c99-4924-9bbd-d40916a0b6e0.png">

Latest commit, M1

**Comment by shaunsingh** [comment]
Can you quickly try disabling the theme and running it again? I doubt the theme is the issue but just in case

**Comment by dustinroepsch** [comment]
Disabling the theme did not help unfortunately

Surprisingly, deleting my neovim config did fix the issue though.
Trying to figure out what part of my config is the issue now

**Comment by dustinroepsch** [comment]
My config works fine with ligatures in Kitty terminal though, so I still think this is a bug with Neovide

**Comment by dustinroepsch** [comment]
Oh man I'm really tired

Deleting my config only worked because it switched the font, looks like other fonts with ligatures work fine (like the default font), but PragmataPro has issues for some reason

**Comment by dustinroepsch** [comment]
One possibility: 
Does neovide change the weight of the font when producing ligatures? 
I only own PragmataPro Mono Liga Regular, so maybe that's the issue. 
In that case, a fallback font should be used though right?

(sorry for the spam)

**Comment by PyGamer0** [comment]
this might be *somehow* related to #742

**Comment by Kethku** [comment]
I really need to extract the renderer component so it can be easier to make small one off test apps :l

**Comment by dustinroepsch** [comment]
Let me know if there's any sort of info I can give you about the font to help!

**Comment by dustinroepsch** [comment]
Also I gave neovide a try on my linux machine and I have the same issure there (PragmataPro  ligatures don't work but FiraCode is fine) 

The PragmataPro font is an OTF instead of a TTF if that makes a difference

**Comment by dustinroepsch** [comment]
I tried this with the TTF version of PragmataPro, as well as a nerdfonts patched version of PragmataPro, all 3 have the same issue

**Comment by dustinroepsch** [comment]
If I wanted to take a look at this myself, any pointers on where to start? 
I'm not familiar with debugging rust code, so any useful tools would be helpful as well.

**Comment by nerdo** [comment]
I run into a similar issue with FiraCode on Linux. Some of the glyphs shows up, but other glyphs show as ? (see my airline in the screenshot below)

![Screenshot](https://imgur.com/UJjYer0.png)

I prefer to use Dank Mono, but my results with that are even worse.

**Comment by clason** [comment]
I see something similar with Fira Code on macOS (specifically the `↪` character). It would be good to have an idea which characters are affected -- could you try opening a full glyph list in neovide and see if there's a pattern?

**Comment by Kethku** [comment]
@dustinroepsch could you try running https://github.com/dfrg/swash_demo with your font configured?

**Comment by dustinroepsch** [comment]
It looks to me like the swash demo has the same issues

<img width="1136" alt="Screen Shot 2021-07-28 at 11 56 27 AM" src="https://user-images.githubusercontent.com/5170924/127380233-920c7db4-3290-4193-8e98-ab4f9a902bb8.png">

To make this screenshot, I just modified the build_document function as follows (I just appended to the end of what was already there)

None of the ligatures I added are being rendered (!=, <=, ==, etc)

```rust

fn build_document() -> doc::Document {
    use layout::*;
    let mut db = doc::Document::builder();

    use SpanStyle as S;

    let underline = &[
        S::Underline(true),
        S::UnderlineOffset(Some(-1.)),
        S::UnderlineSize(Some(1.)),
    ];

    db.enter_span(&[
        S::family_list("times, georgia, serif"),
        S::Size(18.),
        S::features(&[("dlig", 1).into(), ("hlig", 1).into()][..]),
    ]);
    db.enter_span(&[S::LineSpacing(1.2)]);
    db.enter_span(&[S::family_list("baskerville, calibri, serif"), S::Size(22.)]);
    db.add_text("According to Wikipedia, the foremost expert on any subject,\n\n");
    db.leave_span();
    db.enter_span(&[S::Weight(Weight::BOLD)]);
    db.add_text("Typography");
    db.leave_span();
    db.add_text(" is the ");
    db.enter_span(&[S::Style(Style::Italic)]);
    db.add_text("art and technique");
    db.leave_span();
    db.add_text(" of arranging type to make ");
    db.enter_span(underline);
    db.add_text("written language");
    db.leave_span();
    db.add_text(" ");
    db.enter_span(underline);
    db.add_text("legible");
    db.leave_span();
    db.add_text(", ");
    db.enter_span(underline);
    db.add_text("readable");
    db.leave_span();
    db.add_text(" and ");
    db.enter_span(underline);
    db.add_text("appealing");
    db.leave_span();
    db.add_text(WIKI_TYPOGRAPHY_REST);
    db.enter_span(&[S::LineSpacing(1.)]);
    db.add_text(" Furthermore, العربية نص جميل. द क्विक ब्राउन फ़ॉक्स jumps over the lazy 🐕.\n\n");
    db.leave_span();
    db.enter_span(&[S::family_list("verdana, sans-serif"), S::LineSpacing(1.)]);
    db.add_text("A true ");
    db.enter_span(&[S::Size(48.)]);
    db.add_text("🕵🏽‍♀️");
    db.leave_span();
    db.add_text(" will spot the tricky selection in this BiDi text: ");
    db.enter_span(&[S::Size(22.)]);
    db.add_text("ניפגש ב09:35 בחוף הים");
    db.leave_span();
    db.enter_span(&[S::family_list("PragmataProMonoLiga Nerd Font"), S::LineSpacing(1.)]);
    db.add_text("This test is PragmataProMonoLiga Nerd Font -> != <= == ==>");

    db.build()
}

```

**Comment by dustinroepsch** [comment]
Note that in that example I am used a version of PragmataPro patched with NerdFonts, but I tried both the original pragmatapro and the patched version, both have the same issues

**Comment by clason** [comment]
Just a comment that my issue is fixed on latest main.

**Comment by dustinroepsch** [comment]
PragmataPro ligatures are working on latest main now, yay !

However, now the spacing for the font is vary wide. Here is a screenshot:
Neovide is on the Left while neovim running on kitty is on the right
<img width="1920" alt="Screen Shot 2021-07-29 at 3 22 12 PM" src="https://user-images.githubusercontent.com/5170924/127573217-f21655c9-94bf-46aa-b168-f2d9b94de2e4.png">

Is there a setting I'm missing to set the font width properly?
Thanks

**Comment by Kethku** [comment]
@dustinroepsch has the font width issue shown up recently? Or was it an issue before the recent ligature fixes?

**Comment by dustinroepsch** [comment]
It's new after I pulled and did a cargo update, I have a screenshot of the old spacing in my original post (the first post in this issue)

**Comment by dustinroepsch** [comment]
Also do you have a patreon or anything I could donate to?

**Comment by Kethku** [comment]
Github sponsorship is the best way atm :)

Interesting that the spacing changed. I'll ask upstream...

**Comment by Kethku** [comment]
I've created a new issue asking about this and proposing some options https://github.com/dfrg/swash/issues/16

**Comment by dustinroepsch** [comment]
Awesome!
I tried to sponsor you last night, but for some reason my payment was declined and my github account was "locked for payments" until the 3rd next month :/

I'll try again then, hopefully it works next time!

**Comment by dustinroepsch** [comment]
I saw on the other issue he mentioned it might be a scaling factor issue. When I compile I get do get this warning:

```
warning: unused variable: `points_per_inch`
  --> src/renderer/fonts/font_options.rs:94:9
   |
94 |     let points_per_inch = 72.0;
   |         ^^^^^^^^^^^^^^^ help: if this is intentional, prefix it with an underscore: `_points_per_inch`
   |
   = note: `#[warn(unused_variables)]` on by default
```

Maybe a recent change accidentally got rid of the code that scales by ppi?

**Comment by Kethku** [comment]
Ok I think this issue was fixed upstream, but I'm not sure. Have you tried on a recent build?

**Comment by dustinroepsch** [comment]
Yeah it was! Thanks!
