### ISSUE TITLE
something wrong with colorschemes

### ISSUE THREAD

**Issue by adsick** [neovide/neovide#829]
**Describe the bug**
Look at the screenshot

**To Reproduce**
I use nvim 0.6 and neovide 0.7

Os: Pop!_OS 21.04 

**Screenshots**

![image](https://user-images.githubusercontent.com/24528839/125850075-908f6568-d562-4d4f-87c7-c497e40df2a7.png)

**Comment by shaunsingh** [comment]
I believe this is an issue with your colorscheme. The background or some highlight likely isn't defined, and so its rendering those lines as black. Do you mind linking what theme you're using?

I think neovide should have an option to set the background color, for transparent colorschemes like this. In the meantime, I recommend either 
1. Asking the author of the theme to implement the missing highlights/bg
2. fork the theme and modify it yourself 
3. (recommended) As you're using Neovim, grab a lua/treesitter supported theme here: https://github.com/rockerBOO/awesome-neovim#treesitter-supported-colorschemes to take full benefit of its features

**Comment by adsick** [comment]
the colorscheme is called 'desert' and it comes preinstalled. some other non-black-background schemes do it too e.g. 'evening', 'morning' etc... looks bad.

I'll try 3, but this issue definitely needs to be fixed.
look:
![image](https://user-images.githubusercontent.com/24528839/125853284-1c98316b-acd0-4554-9ea8-06ca0c8a805b.png)
![image](https://user-images.githubusercontent.com/24528839/125853343-0e42ec52-c7a3-41b4-bbd0-21aa8dc7c3a9.png)

**Comment by Kethku** [comment]
Can you try your system with another gui such as fvim, goneovim, neovim-qt? I think your theme doesn't play well with the gui protocol, so it is likely nothing we can fix. Seeing if the other guis show the same issue would give some better indication of whether this is on our side or not.

**Comment by adsick** [comment]
> Can you try your system with another gui such as fvim, goneovim, neovim-qt? 
neovim-qt:
![image](https://user-images.githubusercontent.com/24528839/125925695-4958d14e-e03b-497e-bab5-85c5eae40a46.png)

**Comment by Kethku** [comment]
Interesting. I will investigate to see if I can reproduce

**Comment by PyGamer0** [comment]
@adsick Have you set termguicolors?

**Comment by adsick** [comment]
Nope, what is it?

**Comment by PyGamer0** [comment]
> Nope, what is it?

@adsick in the init.vim do you have this line:
```viml
set termguicolors
```
Please add that line and try again to see if you can reproduce.

**Comment by adsick** [comment]
I've set it and it is the same.
![image](https://user-images.githubusercontent.com/24528839/126033603-543577e8-ebfe-4947-a8cb-b657c0b134fa.png)

**Comment by PyGamer0** [comment]
@adsick what is your config?

**Comment by adsick** [comment]
> @adsick what is your config?

Default

**Comment by brokenax3** [comment]
It works fine on my end. 
![image](https://user-images.githubusercontent.com/53488602/129506519-ba2df0cb-c0d5-4079-9c52-8ce8bb39d137.png)

![image](https://user-images.githubusercontent.com/53488602/129507000-81e635bd-5e41-493c-aff6-8e75da0d8be6.png)

**Comment by adsick** [comment]
so I've finally found out that the issue disappears when you perform a scroll action (like Ctrl+U) then everything seems fine.
