### ISSUE TITLE
Cannot exit :term insert mode with Ctrl-\ Ctrl-N

### ISSUE THREAD

**Issue by baileyn** [neovide/neovide#832]
**Describe the bug**
On Windows, I am unable to exit insert mode in the terminal (`:term`) by using `<C-\><C-n>`. Instead, the literal characters `^N` are added as input.

**To Reproduce**
1. Open `neovide`
2. Type `:term`
3. Enter insert mode: `i`
4. Unable to exit with `<C-\><C-n>`

**Expected behavior**
Should be able to exit terminal mode. This is the functionality in `nvim-qt` and `nvim` in console.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Neovide Version: v0.7.0
 - Neovim Version: v0.5.0

**Neovide Log**
https://gist.github.com/baileyn/91358aa4602a6d3d6af8fc7ae2bdeff2

**Additional Information**
It seems that remapping the keys via something like `:tnoremap <Esc> <C-\>C-n>` works. So it's a work around.

**Comment by mjoork** [comment]
Wasn't able to reproduce. Tried both, 0.7.0 preview in Releases (`neovide7-prev` in the video) and latest commit that compiled in CI (`neovide`). I am using the built-in terminal quite often and never got anything like that.

https://user-images.githubusercontent.com/20644474/126058084-89d97389-f1d8-43f9-bc93-aa74e1882260.mp4

# Logs

[neovide_rCURRENT.log](https://github.com/Kethku/neovide/files/6835767/neovide_rCURRENT.log)
[neovide7-prev_rCURRENT.log](https://github.com/Kethku/neovide/files/6835768/neovide7-prev_rCURRENT.log)

**Comment by mjoork** [comment]
If one just presses `<C-n>` it does indeed give just the `^N`, but that's by neovim's design. I am not sure, but maybe something's wrong with the `<C-\>` on your setup? Try doing `tnoremap <Esc> <C-\><C-n>` and hitting ESC in the terminal mode.

**Comment by baileyn** [comment]
Hmm it's weird this behavior seems to only happen in Neovide on my machine. I have since mapped <Esc> to `<C-\><C-n>`. I just thought it was an issue so I figured I would bring it up.

I suppose if it's not able to be reproduced it must be something on my end; a bit strange.

**Comment by mjoork** [comment]
Keep it here anyway, maybe someone else will have a problem like that.

**Comment by Vistavleal** [comment]
Try to add this to you init.vim
`tnoremap <Esc> <C-\><C-n>`

**Comment by Kethku** [comment]
Very old. Current keyboard handling is very different
