### ISSUE TITLE
Wrong ligatures

### ISSUE THREAD

**Issue by uninhm** [neovide/neovide#838]
I get wrong ligatures for: `=<<`, `>>=` and `<=>`

Expected (FiraCode example, any other ligature would be acceptable):
![image](https://user-images.githubusercontent.com/62044675/126875189-32a7e378-e903-4bcc-9304-b53fc2b408e2.png)

Behavior:
![image](https://user-images.githubusercontent.com/62044675/126875203-5ea3efcf-916c-4446-b76b-27027947df29.png)

The last one is the worst, because it's really confusing

**Desktop:**
 - OS: Void Linux
 - Neovide Version [0.7.0]
 - Neovim Version [0.5.0]

**Comment by PyGamer0** [comment]
related to #827 #742

**Comment by uninhm** [comment]
> related to #827 #742

I didn't set `guifont` though

**Comment by uninhm** [comment]
I have the same issue with `<--`, `-->`, `<==` and `==>` BTW
It's clearly an issue with (length > 2) ligatures

**Comment by Kethku** [comment]
This is likely an issue in swash... I haven't had the time to dig into it and make a minimal repro

**Comment by PyGamer0** [comment]
![image](https://user-images.githubusercontent.com/64531844/127269974-60d17c71-a300-45cd-8dda-fe56abfb412f.png)

Upstream

**Comment by PyGamer0** [comment]
@uninhm can you try building from main?

**Comment by PyGamer0** [comment]
This is fixed on main. Please reopen if it is still not resolved for you.

**Comment by PyGamer0** [comment]
For reference: https://github.com/neovide/neovide/issues/742#issuecomment-888941251
