### ISSUE TITLE
Not running on my computer

### ISSUE THREAD

**Issue by duytrung** [neovide/neovide#841]
**Describe the bug**
I tried to run the neovide.exe but no use.

**To Reproduce**
Double click on the neovide for the a few time but nothing happened.

**Expected behavior**
Neovide should run as it should be.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Neovide Version :
 Neovide version: 0.7.0
dpi fix applied
thread 'main' panicked at 'Failed to create window: SdlError("Failed loading vulkan-1.dll: The specified module could not be found.\r\n")', src\window\sdl2\mod.rs:442:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

 - Neovim Version [e.g. 0.5.0]
NVIM v0.6.0-dev+73-g192adfe99

**Please run `neovide --log` and paste the contents of the `.log` file here:**
WARN [neovide::renderer::fonts::font_loader] Tried to load Extra Symbols.otf from assets but build didn't include embed-fonts feature
WARN [neovide::renderer::fonts::font_loader] Tried to load Missing Glyphs.otf from assets but build didn't include embed-fonts feature
WARN [neovide::renderer::fonts::font_loader] Tried to load Extra Symbols.otf from assets but build didn't include embed-fonts feature
WARN [neovide::renderer::fonts::font_loader] Tried to load Missing Glyphs.otf from assets but build didn't include embed-fonts feature
WARN [neovide::renderer::fonts::font_loader] Tried to load Extra Symbols.otf from assets but build didn't include embed-fonts feature
WARN [neovide::renderer::fonts::font_loader] Tried to load Missing Glyphs.otf from assets but build didn't include embed-fonts feature

**Additional context**

**Comment by PyGamer0** [comment]
Can you try building from the main branch

**Comment by Kethku** [comment]
Closing as this is a vulkan issue
