### ISSUE TITLE
let font "preferred styles" take precedece over "styles"

### ISSUE THREAD

**Issue by realToadtoad** [neovide/neovide#844]
**Describe the bug**
Some fonts with both Oblique and Italic styles will use the "Preferred Styles" tag in order to distinguish the two styles, though both of them are marked as "Italic" under "Styles". [(Why this is done)](https://github.com/fontforge/designwithfontforge.com/blob/gh-pages/en-US/Font_Info_%26_Metadata.md#family-naming) An example of a font that does this is [Victor Mono](https://github.com/rubjo/victor-mono). This leads to the Oblique variant often being used over the italic variant, despite other programs like VSCode and Neovim-qt handling this properly.

**To Reproduce**
1. Install [Victor Mono](https://github.com/rubjo/victor-mono) with all styles.
2. Set guifont to Victor Mono
3. Install a theme that supports italics, such as [tokyonight.nvim](https://github.com/folke/tokyonight.nvim)
4. Write a comment, which should be italic.

**Expected behavior**
Comments appear as italic font (which in Victor Mono is partially cursive).

**Screenshots**
Current State
![Screenshot_20210727_100327](https://user-images.githubusercontent.com/35282290/127197301-14c25943-d951-4810-9cce-8212cef6010e.png)

Expected Behavior (simulated in Neovide by deleting oblique fonts. issue still applies with the full Nerd Font version)
![Screenshot_20210727_100754](https://user-images.githubusercontent.com/35282290/127197671-784c0aca-5fc3-4492-b876-f55c4d7fe0b6.png)

Neovim-qt
![Screenshot_20210727_101001](https://user-images.githubusercontent.com/35282290/127197954-8aaa4c40-e47a-443e-a3aa-f1e6ca87449f.png)

VSCode
![Screenshot_20210727_101133](https://user-images.githubusercontent.com/35282290/127198137-6173da77-bbb4-4b15-8991-5b467a49be43.png)

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Neovide Version: 0.7.0
 - Neovim Version: 0.5.0

**Please run `neovide --log` and paste the contents of the `.log` file here:**
[neovide_rCURRENT.log](https://github.com/neovide/neovide/files/6887470/neovide_rCURRENT.log)

**Additional context**
A problem both with the current state and fixing the bug as stated above is that there's, as far as I know, no way to set which font to use for the italic font. Including this will help with other fonts that have multiple slanted styles and users that have preferences of the font (such as cursive vs. non-cursive).

**Comment by lucas-miranda** [comment]
Could you retry with main branch, please?
Because I just followed your instructions, using Victor Mono with all styles installed and expected behavior is working right now, just to let you know that it's using cursive as italics, maybe something else in the last days has fixed it already

And using a specific font to some text styles, such as italic or bold, could be done I think, and maybe can be very interesting to see, I'll tackle that

**Comment by last-partizan** [comment]
@realToadtoad please, install `neovide-git` and check if it works. It should be working as expected.

**Comment by realToadtoad** [comment]
Just built from source, and it worked as expected. Thanks!

**Comment by ray-x** [comment]
I am having trouble with Italic as well
`set guifont=VictorMono\ Nerd\ Font:h18`
But I can not see italic shown in today's main branch.
