### ISSUE TITLE
SFMono Nerd Font (with ligatures) doesn't show symbols correctly 

### ISSUE THREAD

**Issue by shaunsingh** [neovide/neovide#846]
**Describe the bug**
Using this version of the SF Mono font that I patched (https://github.com/shaunsingh/SFMono-Nerd-Font-Ligaturized), several nerd font icons in my statusline are missing

**To Reproduce**
1. Download the font
2. Install the font
3. Set the font to using `guifont
4. See missing glyphs 

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/71196912/127585203-6fe2fc3d-bf89-48cb-b5ca-8c4598112d1f.png">
(kitty on the left, neovide on the right)

**Expected behavior**
The font icons should work as they do in kitty

**Desktop (please complete the following information):**
 - OS: MacOS 12 
 - Neovide Version Latest (built from source)
 - Neovim Version 0.6.0 dev

**Additional context**
The ligatures are Fira code ligatures, they display fine. Not sure if that makes a difference

**Comment by lucas-miranda** [comment]
Could you provide a sample text containing some of the symbols that aren't showing up?
A log would be nice too (using `neovide --log`)

I tried to reproduce it myself, but everything seems fine to me when I using your font version as:

```vimscript
set guifont=Liga\ SFMono\ Nerd\ Font:h11
```

**Comment by shaunsingh** [comment]
One character with the issue is 
Other characters with the same issue are 
```lua
gls.left[11] = {
    DiagnosticError = {
        provider = 'DiagnosticError',
        icon = '  ',
        highlight = {colors.red,colors.bg}
    }
}
gls.left[12] = {
    DiagnosticWarn = {
        provider = 'DiagnosticWarn',
        icon = '  ',
        highlight = {colors.yellow,colors.bg},
    }
}
gls.left[13] = {
    DiagnosticHint = {
        provider = 'DiagnosticHint',
        icon = '  ',
        highlight = {colors.cyan,colors.bg},
    }
}
gls.left[14] = {
    DiagnosticInfo = {
        provider = 'DiagnosticInfo',
        icon = '  ',
        highlight = {colors.blue,colors.bg},
    }
```
(GitHub can't show the characters so they may be blank)
In neovide it shows like this 
<img width="489" alt="image" src="https://user-images.githubusercontent.com/71196912/128586467-6e4d7ed1-0fcc-451d-86c6-a635631c63e7.png">
In both alacritty and kitty it looks like this: 
<img width="478" alt="image" src="https://user-images.githubusercontent.com/71196912/128586501-79d8aa43-8cdb-4c66-aa2f-601c1166fc16.png">
For reference, another text editor (emacs) displays the characters correctly as well
<img width="519" alt="image" src="https://user-images.githubusercontent.com/71196912/128586569-53967186-427e-4af1-ba1d-c59689443a6f.png">

Some characters are even weirder, for example the box with a dot character shows as 柳 in neovide.

The majority of symbols display fine (e.g. folder and file icons in nvim-tree), so I think the font is set and working just fine

**Comment by lucas-miranda** [comment]
Understood, but can you provide me a simple log, just to see if I can get a hint about what is happening

Because even if font isn't set properly, the symbols should be able to display using fallback fonts, so probably is a deeper problem affecting specifically MacOS, as I've seen other issues about wrong font displaying at MacOS

**Comment by Kethku** [comment]
@shaunsingh is this issue still happening on your machine? Is it possible the font name is wrong and or the glyphs aren't actually in the font you expect but rather a fallback font?

**Comment by shaunsingh** [comment]
Nope, I messed up the font name. Fixed now
