### ISSUE TITLE
Is there any flag can be checked, in order to apply some settings on to neovide?

### ISSUE THREAD

**Issue by vlaw** [neovide/neovide#859]
I have tried something like `has('gui_neovide')`, no good 😢 
So is there any global variable or flag, any clue? Thanks~

**Comment by dineshKumar777** [comment]
You can use neovide specific settings as follows.
```lua
if vim.g.neovide then
  vim.opt.guifont = "Source Code Pro:h12"
  vim.g.neovide_cursor_animation_length = 0.05
  vim.g.neovide_cursor_trail_size = 0.2
  vim.api.nvim_set_keymap('n', '<F11>', ":let g:neovide_fullscreen = !g:neovide_fullscreen<CR>", {})
end
```

**Comment by wookayin** [comment]
Why not has('gui_neovide')? Relying on `g:` variable is not reliable.

**Comment by fredizzimo** [comment]
@wookayin, I think that needs a new feature request from `neovim`. At least I can't see any way to add new "features"

Other than the fact that you can overwrite the flag yourself, I don't think it's unreliable. We set it before any init files are loaded.

Neovim 0.9.2 just added `gui_running` https://github.com/neovim/neovim/pull/22382, which can be used, but it also returns true for other GUIs, so you need to combine it with `lua print(vim.api.nvim_get_chan_info(1).client.name)`, which should return "neovide". Provided that neovide is running on channel 1, which might not be the case if multiple GUIs are running.
