### ISSUE TITLE
Devicons don't load or render, despite font having them available

### ISSUE THREAD

**Issue by dartacao** [neovide/neovide#868]
**Describe the bug**
Devicons don't render even though the font supports it.

**To Reproduce**
Font is Fira Code, h16. Other font sizes don't work either

**Expected behavior**
Web devicons and similar should render properly. See goneovim, on the left; neovide on the right.

**Screenshots**
![image](https://user-images.githubusercontent.com/2131630/128687521-b0e7632b-0683-4e53-90ea-2949bc8a177b.png)

**Desktop (please complete the following information):**
 - OS: W10
 - Neovide Version 0.7.0
 - Neovim Version: NVIM v0.6.0-dev+65-g46009499a

**Please run `neovide --log` and paste the contents of the `.log` file here:**
Tried to paste log contents, github didn't like newline characters. For brevity, full log here: 
[neovide_rCURRENT.log](https://github.com/neovide/neovide/files/6953462/neovide_rCURRENT.log)

**Comment by PyGamer0** [comment]
Can you please try the main branch.

**Comment by dartacao** [comment]
@PyGamer0 is 0.7.0 not on main branch? And if you mean regarding neovim dev vs main, the issue is not seen on goneovim, on the exact same init.lua, exact same plugins and exact same config...

**Comment by dartacao** [comment]
Okay, so it seems this issue was resolved in 0.5.0 then 0.6+ made it worse... Disregard it I suppose? In any case, I don't see why it's not working as intended in 0.6+...

**Comment by Kethku** [comment]
If the issue is still occurring in neovide main then it isn't fixed. Can you try building from source or downloading from the github actions?

**Comment by dartacao** [comment]
I did try to, as one of the first things. I usually use latest/nightly versions anyway... couldn't get it to load, only a completely black app that immediately closes. I can post whatever logs I get when I get home, but I think that's a different topic... I just assumed there was something not working on the automated builds side...

**Comment by Kethku** [comment]
Can you run the main branch with --log and upload the contents? A black screen usually means that neovide couldn't find the neovim executable.

**Comment by dartacao** [comment]
Will do, as soon as I am by my PC, ill tag you then. Thanks for the help!

**Comment by dartacao** [comment]
@Kethku It's a white screen, not a black one (and it successfully attached a white screen, so it's not that either). Other than that, it's all the same... downloaded the artifact neovide-windows from commit "725f12c" (https://github.com/neovide/neovide/runs/3274802810), doesn't load. Logs don't seem to help me much here, maybe they can provide some insight?
log: [neovide_rCURRENT.log](https://github.com/neovide/neovide/files/6957972/neovide_rCURRENT.log)

**Comment by Kethku** [comment]
what happens if you run with neovide -- --clean?

**Comment by dartacao** [comment]
.\neovide.exe -- --clean has the same exact result... Cannot get it to log, tried --logs -- --clean, -- --logs --clean and -- --clean --logs. I'm pretty sure it has to be finding an executable for nvim though, since nvim on the same exact folder starts neovim on a terminal.

**Comment by dartacao** [comment]
Ok, so another tidbit of weirdness: It cannot run on my tower, but it does on my laptop? PC is some 10 years old, running on an AMD piledriver processor (FX-8350) and a new-ish AMD RX480; laptop is an intel i5 integrated graphics, no gpu. Could it be that that's the issue? AMD piledrivers don't have integrated graphics, is that why it's not able to run at all?

**Comment by dartacao** [comment]
@Kethku 
Ok I believe I got the issue sorted out... In 0.7.0, for some reason, when neovide cannot find the font it's looking for, it just gives up and crashes. In 0.5.0, that doesn't happen. I got confused because powerline icons were present, but not the devicons. Some hours of conflicts and crap later, I got it working with 0.7.0 AND 0.5.0. Main branch still crashes horribly though.

**Comment by Kethku** [comment]
@dartacao were you encountering a build error in the main branch? I accidentally broke the build late yesterday, so that might be contributing to the confusion

**Comment by dartacao** [comment]
@Kethku Nah, neovide was crashing on startup for builds that were some 5-10 days old so I don't think it was the same thing!

**Comment by dartacao** [comment]
It seems, once again, that I am an idiot 🤦 
Got neovide to --log -- --clean, it seems --logs is not the correct argument... Does this help? @Kethku 
[neovide_rCURRENT.log](https://github.com/neovide/neovide/files/6984769/neovide_rCURRENT.log)
Using this action, though others are similar: https://github.com/neovide/neovide/actions/runs/1120617821

**Comment by yetone** [comment]
Have encountered the same problem, any progress please?

**Comment by Kethku** [comment]
Can you post screen shots of what you expect (using terminal or other gui) VS what actually happens? There are lots of moving parts and dev icons do work on my machine so some more details might help

**Comment by dartacao** [comment]
> Have encountered the same problem, any progress please?

@yetone 
For me it was just my own incorrect specifications of the font. Id suggest the following first:

1. Get the latest neovide from actions.
2. Do "set guifont=*
A buffer should appear with all the fonts that neovide can discover in your system. Find your font (should be appended with NF (for example "Fira Code NF"), and press Return with your cursor on it.
If it works, set the guifont variable to that string. Note that spaces should be escaped in vimscript (I.e. "set guifont=Fira\ Code\ NF", or 'vim.g.guifont = "Fira Code NF" ' in lua).

**Comment by fredizzimo** [comment]
Hah, I was just going to post this...
>At least in the case of @dartacao, in the original post and logs it looks like a non-patched FiraCode font was used, at least it doesn't have the 'NF' or 'Nerd Font' postfix. @yetone are you using a patched or nerd font, like the instructions say https://github.com/ryanoasis/vim-devicons

**Comment by dartacao** [comment]
> Hah, I was just going to post this...
> 
> > At least in the case of @dartacao, in the original post and logs it looks like a non-patched FiraCode font was used, at least it doesn't have the 'NF' or 'Nerd Font' postfix. @yetone are you using a patched or nerd font, like the instructions say https://github.com/ryanoasis/vim-devicons

**Comment by Kethku** [comment]
Love that `set guifont=*` is already useful :)

**Comment by Kethku** [comment]
@dartacao sounds like the problem is fixed. Please reopen if I've misunderstood.
