### ISSUE TITLE
Prompt for save on exit with window X button

### ISSUE THREAD

**Issue by willhansen** [neovide/neovide#874]
It's easy to lose work with neovide in cases where that work would not be lost in GVim, simply because neovide has no save prompt when exiting with the window's X button

Ideally we would have a save prompt similar to GVim: 

![Question_312](https://user-images.githubusercontent.com/2918280/128937940-83da1946-04e1-41c1-a6aa-070009daa55e.png)

As mentioned in the discussion [here](https://github.com/neovide/neovide/discussions/871), switching the exit command from `:qall!` to `:qall` would fix the core issue, though it wouldn't be as smooth a workflow as a save dialogue.

Honestly, I am baffled how any text editor is missing such a basic safeguard against lost work, and more, how I can't find anyone else mentioning this.

**Comment by howdev** [comment]
I am surprised myself, when closing the window, it just closed. There are several other neovim clients have this issue, especially the clients that doesn't use ginit.vim. nvim-qt works properly.
I do not consider this as an enhancement. This is basic function of a GUI.

**Comment by fredizzimo** [comment]
I agree that there should be an optional prompt. 

However, remember that at least on Windows the operating system would still close it without any prompts when it updates itself and automatically restarts when it updates itself. Or you could have a power outage, a crash or anything, so it's not really a good safe guard.

But don't worry. vim has a much more useful safe-guard built in, called swap files, type `:help swap-file`. So if you have swap files enabled, which is the default, and you accidentally close Neovide, nothing should be lost.

There also exist at least on plugin for automatic session management, which would open all files that you had open automatically, but I haven't tried it so I don't know how well it works, and if it even works the way I describe.
