### ISSUE TITLE
latest commit(working swap to upstream nvim-rs) broke neovide

### ISSUE THREAD

**Issue by dineshKumar777** [neovide/neovide#877]
Neovide is opening like in popup mode and navigation keys are not working correctly (j,k). Took latest code now and built.
![neovide_latest](https://user-images.githubusercontent.com/21097695/128957186-3acfd95a-ef93-429c-a883-31ff5dc51db1.png)

Reverting back to old commit resolves the issue
git reset --hard 725f12c
OS: Arch linux [sway wayland]
[neovide_rCURRENT.log](https://github.com/neovide/neovide/files/6965370/neovide_rCURRENT.log)

**Comment by Kethku** [comment]
@jsosulski your issue is fixed now. It was my bad. @dineshKumar777 I still don't fully understand what issue you are running into. Are you saying that neovide isn't responding to your key presses?

**Comment by dineshKumar777** [comment]
@Kethku Sorry I created this bug without analyzing properly. It seems key presses are working fine. But cursor is hiding on key presses which caused this confusion for me. 

**Two issues i am facing with latest commit:**
1. Neovide window is not filling in WM split (opening like a popup)
- If i revert back to commit 132f9936991d1b681f1510ddd30f8f375eae2b49 split is working as intended

2. Cursor hiding randomly or not behaving correctly upon keypress. Cursor is locked on to status line.
- this is resolved if i revert back to commit 725f12cafd4a26babd0d6bbcbca9a99c181991ac

Please let me know if you need more info.


https://user-images.githubusercontent.com/21097695/129068866-ede37c59-319d-4061-8f41-cac3c878ef8a.mp4


https://user-images.githubusercontent.com/21097695/129068887-82023f7d-ca02-4775-9ca6-0f7edf4250c6.mp4

**Comment by dineshKumar777** [comment]
@Kethku 
Cursor jumping to status line is resolved when turning off lazyredraw as mentioned in https://github.com/neovide/neovide/issues/890
- Lazyredraw setting didn't caused any issue with older commits but why this happening now?

Still not sure about window splitting issue. Also works well with old commits.

**Comment by dineshKumar777** [comment]
55179e4 commit resolved window splitting size issue.

#890 tracks cursor jumping issue.
Closing this.
