### ISSUE TITLE
Neovide does not compile on macOS Big Sur

### ISSUE THREAD

**Issue by ModdedGamers** [neovide/neovide#879]
**Describe the bug**
When building from git main, commit 1e1bd45, the build does not work.

**To Reproduce**
1. Clone git main on macOS
2. without doing anything else, run `cargo build --release`.
3. The build should eventually error with the error
`error[E0599]: no method named `get_global` found for struct `settings::SETTINGS` in the current scope`

**Expected behavior**
I expected the build to succeed

**Desktop (please complete the following information):**
 - OS: macOS Big Sur, 11.4
 - Neovide Version: git main
 - Neovim Version: 0.5.0

**Additional context**
I have installed the necessary dependencies for building. I am building because the latest release(0.7.0), does not work on macOS because it errors out with the same sdlerror as seen here: https://github.com/neovide/neovide/issues/564#issuecomment-821091334
The backtrace for the 0.7.0 crash:
<details>
<summary>Backtrace</summary>
<pre>
Ignored client type property: "methods"
Ignored client type property: "attributes"
thread 'main' panicked at 'Failed to create window: SdlError("Vulkan support is either not configured in SDL or not available in current SDL video driver (cocoa) or platform")', src/window/sdl2/mod.rs:442:10
stack backtrace:
   0:        0x10cb35073 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h34f76b2ca42fab41
   1:        0x10ca5053d - core::fmt::write::h8f13d857463c51c1
   2:        0x10cb34916 - std::io::Write::write_fmt::h0a6214ccb1a8468b
   3:        0x10cb34269 - std::panicking::default_hook::{{closure}}::hb14d90e928578cc7
   4:        0x10cb3395e - std::panicking::rust_panic_with_hook::h28bf9d6c3916221e
   5:        0x10cb5767a - std::panicking::begin_panic_handler::{{closure}}::h99569328be4adae9
   6:        0x10cb575e8 - std::sys_common::backtrace::__rust_end_short_backtrace::h9a7e5cc6475b496b
   7:        0x10cb57590 - _rust_begin_unwind
   8:        0x10d0c16bf - core::panicking::panic_fmt::h65997884a2662b8c
   9:        0x10d0c1cb5 - core::option::expect_none_failed::h5e793a721927d8b0
  10:        0x10c9d6117 - neovide::window::window_wrapper::start_loop::h4d3a5a6a93d1c0ab
  11:        0x10c98882f - neovide::main::h65f045dc9dbdd661
  12:        0x10c9c964a - std::sys_common::backtrace::__rust_begin_short_backtrace::h57f90e4e686f5085
  13:        0x10c983bb4 - _main
</pre>
</details>

**Comment by clason** [comment]
Replace `get_global` with `get`.

**Comment by ModdedGamers** [comment]
In what file?

**Comment by clason** [comment]
In the file where the error is reported (it's also obvious from the commit you linked).

**Comment by ModdedGamers** [comment]
Thanks! I'm re-running the build now.

**Comment by ModdedGamers** [comment]
H

**Comment by Kethku** [comment]
This was my bad, should be fixed now
