### ISSUE TITLE
--listen for nvim doesnt' work

### ISSUE THREAD

**Issue by manfredlotz** [neovide/neovide#880]
This is Ubuntu 20.04,  newest `neovide` 0.7.0 built from git repository and  `nvim` is v0.4.3

Calling `neovide` like follows: `neovide -- '--listen /tmp/nvimsocket'` gives

```
ERROR [neovide::bridge] Cannot get neovim api info, either neovide is launched with an unknown 
command line option or neovim version not supported! 
```

Instead, if I invoke nvim like this:`nvim --listen /tmp/nvimsocket` all is fine.

**Comment by mforsb** [comment]
The quotes are making nvim treat `--listen /tmp/nvimsocket` as a single argument. Remove them and it should work.

**Comment by manfredlotz** [comment]
Yep, you are right. Thanks.
