### ISSUE TITLE
--multiGrid instantly exits [windows]

### ISSUE THREAD

**Issue by dustinroepsch** [neovide/neovide#881]
**Describe the bug**
After updating neovide today, I can no longer launch with the --multiGrid flag. The process just closes and no neovide window appears.

**To Reproduce**
checkout neovide main:latest
cargo build --release
run neovide with --multiGrid

**Expected behavior**
Neovide should open 

**Screenshots**
![neovide crash](https://user-images.githubusercontent.com/5170924/129101155-dee26822-428c-41cc-a22f-6f7115ebf077.gif)

**Desktop (please complete the following information):**
- OS: windows 10
- Neovim Version: 0.5.0
- Neovide version: Latest commit

**Please run `neovide --log` and paste the contents of the `.log` file here:**
No log file is created when I use --multiGrid and --log together

**Comment by clason** [comment]
The option was renamed to `--multigrid` (note lowercase).

**Comment by dustinroepsch** [comment]
oh my bad, thanks!

**Comment by clason** [comment]
Also, note the spelling mu**lt**igrid, not mu**tl**igrid (otherwise you'd have gotten a helpful error message...)

**Comment by dustinroepsch** [comment]
oh my bad, though I don't get a helpful error message with the correct spelling either

**Comment by clason** [comment]
```
~/b/neovide ❯❯❯ ./target/release/neovide --multiGrid                                                 (main|✓)
error: Found argument '--multiGrid' which wasn't expected, or isn't valid in this context
	Did you mean --multigrid?
```

**Comment by clason** [comment]
(might be fish magic, tho)
