### ISSUE TITLE
Cursor disappearing (jumping to tabline/statusline)

### ISSUE THREAD

**Issue by m8dotpie** [neovide/neovide#890]
A cursor after searching text/writing/changing buffer jumps to status line or tabline

**Minimal config to reproduce:**
`set title`

**Expected behaviour:**
Cursor stays wherever it was

**Actual behaviour:**
Cursor stays on tabline/statusline

 **Setup:**
MacOS 11.5.1
Neovide 0.7.0
Neovim 0.5.0

Afaik problem is the same as it was with lazyredraw #98  and still unresolved on [Neovim](https://github.com/neovim/neovim/issues/11806) side.

**Comment by Kethku** [comment]
I think this may have been at least made better in main. Could you try there?

**Comment by m8dotpie** [comment]
> I think this may have been at least made better in main. Could you try there?

Sorry, but 'main' what? Im on main neovide and master Neovim

**Comment by Kethku** [comment]
Ah I see. Yes I meant main branch. My bad.

Its interesting that this happens so frequently. I wonder if there is a plugin or setting that causes it more in your config...

**Comment by comiluv** [comment]
I'm having probably the same problem. It happense when ```set lazyredraw``` is on. It seems ```set title``` has no affect on the bug on my side.
![GIF 2021-08-15 오후 4-12-11](https://user-images.githubusercontent.com/19642705/129470303-44336b3e-8daa-44ff-bbc6-835162f8267b.gif)

**Comment by Kethku** [comment]
Note: this lazyredraw is a known upstream issue and is not supported currently until the upstream problem is fixed.

**Comment by Kethku** [comment]
I haven't seen this in a long time. Closing
