### ISSUE TITLE
Disowned flag does not exist

### ISSUE THREAD

**Issue by m8dotpie** [neovide/neovide#891]
**The bug**
Configuration wiki page states that it is possible to use `--disowned` flag to disown it from session. Neovide says that such a flag does not exist and moreover `neovide --help` does not contain such a flag

**Desktop**
 - MacOS 11.5.1
 - Neovide 0.7.0
 - Neovim 0.5.0

**Comment by last-partizan** [comment]
Yeah, that option was removed.

Actually, it was opposite `--disowned` means - do not disown process, as it is already disowned. We replaced it with more appropriate `--nofork`.

Updated wiki page, thanks for reporting.
