### ISSUE TITLE
Lines get mispositioned when browsing up and down

### ISSUE THREAD

**Issue by comiluv** [neovide/neovide#894]
**Describe the bug**
A line of text is put out of its normal alignment in the row when the user inputs series of js and ks to scroll up and down a document, leaving artifacts and malformed text behind.

**To Reproduce**
1. Open a text file
2. Scroll up and down contiguously using j and k keys

**Expected behavior**
The user can scroll up and down without breaking visual appearance of the text file

**Screenshots**
Screenshot of myself browsing through my .vimrc file
![GIF 2021-08-15 오전 7-23-55](https://user-images.githubusercontent.com/19642705/129461774-9361e608-e53e-4329-b7b6-5373687f244b.gif)

**Desktop (please complete the following information):**
 - OS: Windows 10 21H1 19043.1165
 - Neovide Version 0.7.0 installed from chocolatey ```choco install neovide```
 - Neovim Version NVIM v0.6.0-dev+116-g35041432b

**Please run `neovide --log` and paste the contents of the `.log` file here:**
https://drive.google.com/file/d/1j_yPamPiBiJ8c9S2RUaNoK0ZUAT1S2So/view?usp=sharing

**Additional context**
Fresh install with no additional configuration other than my usual init.vim which sources .vimrc

**Comment by Kethku** [comment]
This is fixed in main. Please build from source
