### ISSUE TITLE
Fonts becomes ugly when LSP kicks in

### ISSUE THREAD

**Issue by dprydehawking** [neovide/neovide#899]
**Describe the bug**
I'm using nvim-lspconfig as my lsp plugin for neovim. As you can see in picture 1,
this is Hacker Nerd Font, which is rendered correctly at first. However, when LSP finished loading, the fonts becomes uglier. I already tried different fonts: FiraCode Nerd Font, FiraMono Nerd Font. But this strange behavior still happens.

**To Reproduce**
1. Config nvim-lspconfig for rust correctly
2. Open Rust file
3. Wait for LSP finished loading

**Expected behavior**
Fonts rendering should not be changed when LSP kicks in

**Screenshots**
![Default, Clone,](https://user-images.githubusercontent.com/51309932/129513552-5bc1b8b8-1726-4b6b-9c06-e466eb4162bf.png)
![currency rs](https://user-images.githubusercontent.com/51309932/129513537-01a2b58d-51f6-47d1-9a5d-c3fda685876d.png)

**Desktop (please complete the following information):**
 - OS: MacOS 11.4
 - Neovide Version Commit `726539fbae34b693949d2fa08a6dba786a65a8b9`
 - Neovim Version 0.5.0 

**Please run `neovide --log` and paste the contents of the `.log` file here:**
[neovide_rCURRENT.log](https://github.com/neovide/neovide/files/6989930/neovide_rCURRENT.log)

**Comment by lucas-miranda** [comment]
Maybe this is a duplicate issue from #851?
Both are about virtual text greying out text rendering

**Comment by Kethku** [comment]
Agreed. This is a duplicate.

**Comment by dprydehawking** [comment]
> Maybe this is a duplicate issue from #851?
> Both are about virtual text greying out text rendering

Thanks for your comment. I closed this issue.
