### ISSUE TITLE
Cursor disappears after pressing ctrl-L and doing a search

### ISSUE THREAD

**Issue by comiluv** [neovide/neovide#904]
**Describe the bug**
When a user presses Ctrl-L, which is typically used to [redraw screen](https://neovim.io/doc/user/various.html), the cursor disappears after doing a search through the buffer.

**To Reproduce**
1. Press Ctrl-L
2. press / and search for a text in the buffer

**Expected behavior**
Cursor doesn't disappear

**Screenshots**
![GIF 2021-08-17 오전 10-47-17](https://user-images.githubusercontent.com/19642705/129650892-ab84dc5f-f83e-4872-b6ac-d3207ef45c9a.gif)

**Desktop (please complete the following information):**
 - OS: Windows 10/21H1 19043.1165
 - Neovide Version Neovide version: 0.8.0
 - Neovim Version NVIM v0.6.0-dev+116-g35041432b

**Please run `neovide --log` and paste the contents of the `.log` file here:**
https://drive.google.com/file/d/1D3YrdN6JguH4wTEjQM4uCrEKg7qvR-wn/view?usp=sharing

**Additional context**

**Comment by jceb** [comment]
I observed the same behavior when I press `<Esc>` or `<C-c>` while typing the search pattern.

Workaround to make the cursor visible again: start the search again with `/` and complete the pattern with `<CR>`.

**Comment by Kethku** [comment]
I believe this is fixed in main. Please reopen if the issue persists.
