### ISSUE TITLE
set wildmode=list:full breaks completion

### ISSUE THREAD

**Issue by comiluv** [neovide/neovide#905]
**Describe the bug**
set wildmode=list:full makes display of selected completion option to be written in a line below its correct placement.

**To Reproduce**
1. set nocp
2. set wildmode=list:full
3. :e
4. Ctrl-D
5. press tab keys to see the error

**Expected behavior**
Completion is displayed and highlighted on the same row

**Screenshots**
![GIF 2021-08-17 오전 11-06-11](https://user-images.githubusercontent.com/19642705/129652603-f2b26d3f-7d9d-45fa-99b5-1df9e8f520c1.gif)

**Desktop (please complete the following information):**
 - OS: Windows 10/21H1 19043.1165
 - Neovide Version Neovide version: 0.8.0
 - Neovim Version NVIM v0.6.0-dev+116-g35041432b

**Please run `neovide --log` and paste the contents of the `.log` file here:**
https://drive.google.com/file/d/16zCz-EpDsyZGk1aXUozv36JfB_hx_-lc/view?usp=sharing

**Additional context**

**Comment by Kethku** [comment]
This seems like something odd from nvim 0.6.0. Could you try in 0.5?

**Comment by comiluv** [comment]
Also happens with 0.5.0
![GIF 2021-08-17 오후 12-30-32](https://user-images.githubusercontent.com/19642705/129659385-8a370179-fb7e-436d-b7f4-33c90bf591c9.gif)
log file: https://drive.google.com/file/d/16xvMF1JHohrKx-TJElJW93FAeAp2VGdc/view?usp=sharing

**Comment by last-partizan** [comment]
This was fixed recently by updating nvim-rs (https://github.com/neovide/neovide/commit/d2760e2d4562c4d7793444120be386d79bcdf57f), please try again.

I wasn't able to reproduce issue with latest build.
