### ISSUE TITLE
Font Rendering is screwed up on macOS

### ISSUE THREAD

**Issue by ModdedGamers** [neovide/neovide#908]
**Describe the bug**
When I set `guifont` to `Fira\ Code:h18` in neovide, all the characters overlap eachother and are squished together.

**To Reproduce**
1. Make sure you have the Fira Code Nerd Font installed on your system.
1. Open Neovide
2. Run `:set guifont=Fira\ Code:h18`
3. See weird font rendering

**Expected behavior**
I expected to have a nice monospace font with ligatures

**Screenshots**
![Strange Font Rendering Screenshot](https://user-images.githubusercontent.com/35778371/130326753-ab4190bd-bbec-4b3f-9364-f89252680778.png)

**Desktop (please complete the following information):**
 - OS: macOS 11.4
 - Neovide Version 0.7.0, built from commit `55179e43`.
 - Neovim Version 0.5.0

**Please run `neovide --log` and paste the contents of the `.log` file here:**

[Neovide Log](https://github.com/neovide/neovide/files/7025741/neovide_rCURRENT.log)
I attached the log as it's too big to put into a comment.

**Additional context**
The default font that loads, Monaco, included with macOS, works.

**Comment by PyGamer0** [comment]
> Make sure you have the Fira Code Nerd Font installed on your system.
Open Neovide
Run :set guifont=Fira\ Code:h18
See weird font rendering

You are setting the font to `Fira Code` and not to `Fira Code Nerd Font`. Can you try setting the guifont to the name of the font family you installed? (Pretty sure the family name is `Fira Code Nerd Font`)

**Comment by ModdedGamers** [comment]
I figured it out. I had to set it to `FiraCode\ Nerd\ Font\ Mono`, which is weird, because Fira Code is a monospaced font by default. But thank you so much for the help!

**Comment by PyGamer0** [comment]
> , because Fira Code is a monospaced font by default

the family name is `FisaCode Nerd Font Mono`.
