### ISSUE TITLE
Fonts appear squished

### ISSUE THREAD

**Issue by riza-khan** [neovide/neovide#913]
**Describe the bug**
Just downloaded the repo and started it up.

But the fonts are all squished and not legible

**To Reproduce**

**Expected behavior**

**Screenshots**
![2021-08-23_18-25-23](https://user-images.githubusercontent.com/86204577/130527315-a3a91c8b-6e22-4ec0-b30e-1626dd947d72.png)
**Desktop (please complete the following information):**
 - OS: macOS
 - Neovide Version: latest
 - Neovim Version: 0.4.4

**Please run `neovide --log` and paste the contents of the `.log` file here:**

Running the above gives me this error:
<img width="693" alt="2021-08-23_18-29-43" src="https://user-images.githubusercontent.com/86204577/130527654-02eb7252-d18d-47eb-83d8-4b64c82c0496.png">

**Additional context**

**Comment by leon332157** [comment]
Try using neovim 0.5.0 or higher.

**Comment by riza-khan** [comment]
I upgraded my Neovim to 0.5 and that didn't help either.

**Comment by PyGamer0** [comment]
Can you set the `guifont` to something? Like `set guifont=<fontname>:h<fontsize>`

**Comment by 17Swagat** [comment]
I think this link might help you. I also faced a similar problem -> https://github.com/neovide/neovide/issues/883

**Comment by riza-khan** [comment]
> Can you set the `guifont` to something? Like `set guifont=<fontname>:h<fontsize>`

Tried this a few times and it didn't do anything :(

**Comment by riza-khan** [comment]
> I think this link might help you. I also faced a similar problem -> #883

@17Swagat Are you saying try downloading it using different methods?

**Comment by PyGamer0** [comment]
> > Can you set the `guifont` to something? Like `set guifont=<fontname>:h<fontsize>`
> 
> Tried this a few times and it didn't do anything :(

Which fonts did you set it to?

**Comment by riza-khan** [comment]
> > > Can you set the `guifont` to something? Like `set guifont=<fontname>:h<fontsize>`
> > 
> > 
> > Tried this a few times and it didn't do anything :(
> 
> Which fonts did you set it to?

I tried `set guifont=FiraCode\ NF:h16` which I got from this post here: https://github.com/neovide/neovide/issues/468

I think that font (whatever it is) should be available for me to use?

**Comment by PyGamer0** [comment]
> I think that font (whatever it is) should be available for me to use?

Ah you have to download the font. Try a font that is already available on MacOS

**Comment by riza-khan** [comment]
@PyGamer0 
This is my settings in my `vimrc`. The font listed is available on the machine. 

Sadly no changes to the appear still.

![2021-08-24_09-27-10](https://user-images.githubusercontent.com/86204577/130624808-6cd1fcf6-e258-43e5-8a46-8ce14eca01e6.png)

**Comment by 17Swagat** [comment]
> 
> 
> > I think this link might help you. I also faced a similar problem -> #883
> 
> @17Swagat Are you saying try downloading it using different methods?

Yeah. Try using Scoop for downloading neovide. It worked for me

**Comment by ModdedGamers** [comment]
> > > > Can you set the `guifont` to something? Like `set guifont=<fontname>:h<fontsize>`
> > > 
> > > 
> > > Tried this a few times and it didn't do anything :(
> > 
> > 
> > Which fonts did you set it to?
> 
> I tried `set guifont=FiraCode\ NF:h16` which I got from this post here: #468
> 
> I think that font (whatever it is) should be available for me to use?

I had this same problem. Try setting `guifont` to `FiraCode\ Nerd\ Font\ Mono:h18`. That worked for me.

**Comment by PyGamer0** [comment]
> Try using Scoop for downloading neovide

@17Swagat  @riza-khan is on MacOS and scoop is only for windows

**Comment by fredizzimo** [comment]
I believe this is fixed by https://github.com/neovide/neovide/pull/1116. Also check that the actual font name with the new `set guifont=*`

**Comment by Liverm0r** [comment]
I tried several fonts (jetbrains mono, font-hack-nerd) – only [fira](https://github.com/ryanoasis/nerd-fonts/tree/master/patched-fonts/FiraCode/Retina/complete) worked:
```fennel
(set vim.o.guifont "FiraCode Nerd Font Mono:h14")
```

**Comment by MultisampledNight** [comment]
@Liverm0r You can try out with `:set guifont=*` which fonts are available to Neovide, they may be named differently from what you expect.
