### ISSUE TITLE
Neovim does not display properly on i3 on ubuntu 20.04.

### ISSUE THREAD

**Issue by Ktedon** [neovide/neovide#916]
**Describe the bug**
A new line break is not being created when at the end of the line.

**To Reproduce**
1. Install on a vm ubuntu 20.04
2. install i3 and open the manager
3. compile neovide from the main branch
4. zoom via the command "xrandr --output eDP-1 --scale 0.55x0.55"
5. open neovide.

**Expected behavior**
When I get to the end of the visible line it does not move to the cursor to the new line unless it hit the key a few more times and print a few more characters off screen. The expected behavior is a new line break.

**Screenshots**

**Desktop (please complete the following information):**
 - Ubuntu: [e.g. Ubuntu 20.04]
 - Neovide Version [e.g. Neovide 0.8.0]
 - Neovim Version [e.g. NVIM v0.4.3]

**Please run `neovide --log` and paste the contents of the `.log` file here:**

Just opens neovide

**Additional context**

**Comment by last-partizan** [comment]
Two days ago was merged fix that can address this issue. Please check again, does it works?

**Comment by fredizzimo** [comment]
This issue is very old, and no new comments, so very likely fixed.
