### ISSUE TITLE
Incorrect window size at start up or after font change

### ISSUE THREAD

**Issue by unclechu** [neovide/neovide#918]
**Describe the bug**

After I just start the Neovide it exceeds available size for its window. If I change window size post-factum (switch i3 tiling layout back and forth) it then automatically resizes to the correct size, to fit the window.

**To Reproduce**
1. Reproducible build of Neovim and Neovide using Nix (pin of *nixpkgs* is from *nixos-unstable* channel, one that is older from stable channel has older Neovide that just fails to start):
 
   ``` sh
   nix-shell --pure -I nixpkgs=https://github.com/NixOS/nixpkgs/archive/5bc8b980b9178ef9a4bb622320cf34e59ea2ea10.tar.gz -p neovim -p neovide --run neovide
   ```

2. Either

   1. Just start the Neovide
   2. Change font family and/or size via `set guifont=...`

   _N.B. I use i3 window manager so it automatically tiles Neovide’s window.
   Maybe without a tiling window manager Neovide just creates a window with the size it wants and it stays the same
   while a tiling window manager forces it to resize and Neovide doesn’t expect that._

3. See that the Neovim window exceeds or less than window size

**Expected behavior**

1. After startup Neovide fits its window side *(when a tiling window manager is used)*, it doesn’t exceed it and doesn’t take less than available space of its window
2. When font is changed Neovide automatically resizes its contents according current window size (if it’s a tiling window manager window’s size stays the same)

**Screenshots**

![2021-08-26 20-06-01](https://user-images.githubusercontent.com/799353/131005617-b2aba50d-2b3e-44e4-bdd3-107c85dc4237.png)

Then if I change the window’s size it fits:

![2021-08-26 20-07-39](https://user-images.githubusercontent.com/799353/131005805-b4ed2163-ad36-41de-8b01-0f53f502e2fe.png)

Before font change:

![2021-08-26 20-10-20](https://user-images.githubusercontent.com/799353/131006138-42631757-1a87-425a-b0d6-6836e881b069.png)

After font change:

![2021-08-26 20-11-02](https://user-images.githubusercontent.com/799353/131006223-7bbabf03-7fe2-459b-b334-84ee77aad4f5.png)

**Desktop (please complete the following information):**
 - OS: NixOS 21.05
 
   ``` console
   $ nixos-version
   21.05.2717.bc1a0f56812 (Okapi)
   ```

 - Neovide Version [e.g. 0.5.0]
 
   ``` console
   $ nix repl -I nixpkgs=https://github.com/NixOS/nixpkgs/archive/5bc8b980b9178ef9a4bb622320cf34e59ea2ea10.tar.gz <<< '(import <nixpkgs> {}).neovide.version'
   Welcome to Nix version 2.3.15. Type :? for help.
   
   "unstable-2021-08-08"
   ```

   Pin from this commit: 725f12cafd4a26babd0d6bbcbca9a99c181991ac

   https://github.com/NixOS/nixpkgs/blob/5bc8b980b9178ef9a4bb622320cf34e59ea2ea10/pkgs/applications/editors/neovim/neovide/default.nix#L30

 - Neovim Version [e.g. 0.5.0]
   ``` console
   $ nix repl -I nixpkgs=https://github.com/NixOS/nixpkgs/archive/5bc8b980b9178ef9a4bb622320cf34e59ea2ea10.tar.gz <<< '(import <nixpkgs> {}).neovim-unwrapped.version'
   Welcome to Nix version 2.3.15. Type :? for help.
   
   "0.5.0"
   ```

**Please run `neovide --log` and paste the contents of the `.log` file here:**

``` console
$ nix-shell --pure -I nixpkgs=https://github.com/NixOS/nixpkgs/archive/5bc8b980b9178ef9a4bb622320cf34e59ea2ea10.tar.gz -p neovim -p neovide --run 'neovide --log'
Ignored client type property: "methods"
Ignored client type property: "attributes"
```

**Comment by last-partizan** [comment]
@unclechu could you please check again that branch, be2d8dc9d25b0aa15ab89ae593a3f6ab4f1e8135 ?

Now it should resize grid for tiling WM, while preserving startup screen for normal WM.

**Comment by unclechu** [comment]
@last-partizan be2d8dc9d25b0aa15ab89ae593a3f6ab4f1e8135 seems to work fine as well

``` diff
diff --git a/pkgs/applications/editors/neovim/neovide/default.nix b/pkgs/applications/editors/neovim/neovide/default.nix
index 75d20a12a0d..da25472829e 100644
--- a/pkgs/applications/editors/neovim/neovide/default.nix
+++ b/pkgs/applications/editors/neovim/neovide/default.nix
@@ -27,11 +27,11 @@ rustPlatform.buildRustPackage rec {
   src = fetchFromGitHub {
     owner = "Kethku";
     repo = "neovide";
-    rev = "725f12cafd4a26babd0d6bbcbca9a99c181991ac";
-    sha256 = "sha256-ThMobWKe3wHhR15TmmKrI6Gp1wvGVfJ52MzibK0ubkc=";
+    rev = "be2d8dc9d25b0aa15ab89ae593a3f6ab4f1e8135";
+    sha256 = "0p9fccfzgrnxka5nvvbhiwymq35ll55lc43xk0hwxmydbq7ydn2l";
   };
 
-  cargoSha256 = "sha256-5lOGncnyA8DwetY5bU6k2KXNClFgp+xIBEeA0/iwGF0=";
+  cargoSha256 = "1msx8nkabd75hrzm88s9x17ifd4n9fsdgy2nxaqaw5xkp2iwgvs0";
 
   SKIA_SOURCE_DIR =
     let
```

**Comment by last-partizan** [comment]
Fix merged.
