### ISSUE TITLE
'Alt+Tab' exits to normal mode

### ISSUE THREAD

**Issue by luiz00martins** [neovide/neovide#920]
**Describe the bug**
While in *Command*, *Insert*, or *Visual* mode, switching to a different window with <kbd>Alt</kbd>+<kbd>Tab</kbd> automatically switches to *Normal* mode. The behaviour seems random, but consistent (it happens at least once every 5 presses).

**To Reproduce**
1. Open Neovide
2. Open a different window
3. In Neovide, switch to *Command*/*Insert*/*Visual* mode
4. Switch to a different window with <kbd>Alt</kbd>+<kbd>Tab</kbd>

**Expected behavior**
Maintain the current mode when switching windows.

**Screenshots**
The left window is a terminal, and the right one is Neovide. The behaviour presented below on *Command* mode also happens with *Insert* and *Visual* modes.

*Note: There's a lag spike in the beginning of the clip.*
![Peek 2021-08-28 10-38](https://user-images.githubusercontent.com/43142209/131222590-33044d36-0351-49f9-98b0-e176b3495b53.gif)

**Desktop**
 - POP OS 21.04
 - NVIM v0.6.0-dev+155-g15b736d6e
 - Neovide 0.7.0

**Please run `neovide --log` and paste the contents of the `.log` file here:**
None (`neovide --log` does not open a file).

**Additional context**
 - As seen by the gif, this behaviour does not happen with the terminal.
 - It doesn't seem to happen with other methods of switching windows, such as <kbd>Win</kbd>+<kbd>Tab</kbd> or the mouse. It only happens with <kbd>Alt</kbd>+<kbd>Tab</kbd>.
 - I've tested with all of my mappings and pluggins disabled, and the behaviour still persists.

**Comment by aj3423** [comment]
Don't know if this is the same problem, it goes from insert mode to normal mode every time when "Alt + any key".  I globally mapped "Alt + j / k" by AutoKey to choose the popup items in insert mode, it works fine with Nvim console or Nvim-qt, but not work in Neovide because it goes to normal mode.

Environment: Linux + Nvim v0.6.0 + Neovide 0.8.0

**Comment by luiz00martins** [comment]
I found out the reason. 

By looking at the output of `maybe_get_keybinding` in `keyboard_manager.rs`, one can see that `<M-Tab>` is registered by Neovide. This is not the case for (some, or maybe most) terminals.

You can confirm this by pressing <kbd>Ctrl</kbd>+<kbd>v</kbd> <kbd>Alt</kbd>+<kbd>Tab</kbd> in your terminal neovim, and it'll most likely not output "`<M-Tab>`", meaning that it is ignored. This is most likely because of the terminal, not neovim. Neovide on the other hand, properly outputs "`<M-Tab>`" when you press <kbd>Ctrl</kbd>+<kbd>v</kbd> <kbd>Alt</kbd>+<kbd>Tab</kbd>, which means that it's registering the key. For some reason, `<M-Tab>` leaves the mode.

Therefore, the solution is to remap `<M-Tab>` or `<A-Tab>` to `<nop>` in the modes that you want it to be ignored (in my case, all of them):
```lua
vim.api.nvim_set_keymap('', '<A-Tab>', '')
vim.api.nvim_set_keymap('!', '<A-Tab>', '')
```

*Note to @aj3423: This may not solve your problem. If that's the case, you may want to open another issue specific to your case.*

---

In my opinion this is not a bug per se, but more like a feature, since it means that Neovide is capable of handling some keybindings that your average terminal can't.

  On the other hand, the behaviour is still somewhat weird. As an example: Simply pressing <kbd>Alt</kbd>+<kbd>Tab</kbd> goes to *Normal*, presumably because it is implicitly pressing `<M-Tab>`. However, remapping some other key to `<M-Tab>` directly and pressing it does not exit the mode (it has some wacky behaviour for sure, but it differs from simply pressing <kbd>Alt</kbd>+<kbd>Tab</kbd>). So this "exiting mode" response may be specific to Neovide. I can't test this theory however, since the terminal doesn't even register <kbd>Alt</kbd>+<kbd>Tab</kbd> in the first place.

Nonetheless, it seems like remapping solves any unexpected behaviour, so I'll close with this comment. If any contributor still considers this a bug however, feel free to reopen.
