### ISSUE TITLE
Freezes on startup until being resized

### ISSUE THREAD

**Issue by aj3423** [neovide/neovide#922]
**Describe the bug**
When it launches, the window is not responding to any keyboard clicking, the command bar is black (abnormal color).  Everything becomes normal after resizing the window. And there is also a 20% chance that it works all fine on startup.

**To Reproduce**
1. Launch Neovide
2. Click "i", or any key, nothing happens
3. Resize the window
4. Click "i", it goes to insert mode correctly

**Expected behavior**
Works when it launches.

**Screenshots**
![neovide](https://user-images.githubusercontent.com/4710875/131252122-121a81ff-860a-4bc6-8f52-9d94e0ba62b3.gif)

**Desktop (please complete the following information):**
 - Kali Linux 2021.2 with everything up-to-date
 - Neovide v0.8.0
 - Neovim v0.6.0-dev

**Please run `neovide --log` and paste the contents of the `.log` file here:**
[neovide_rCURRENT.log](https://github.com/neovide/neovide/files/7072244/neovide_rCURRENT.log)

**Additional context**

**Comment by Kethku** [comment]
I think this may be fixed in main. Please reopen if not.

**Comment by aj3423** [comment]
Just tried the main branch, which shows version v0.8.0, problem still exists.

**Comment by fredizzimo** [comment]
This looks very similar to this https://github.com/neovide/neovide/issues/960, but that one is reported fixed, and the inputs starts to work when clicking the window, so no actual resize is needed.

**Comment by aj3423** [comment]
This problem still exists in verion 0.9.0.

**Comment by MultisampledNight** [comment]
The freeze referred to a case where configuration locks were mishandled, not this issue, sorry. I'm not sure how to debug this, too.

**Comment by aj3423** [comment]
This seems fixed, thank you guys.

**Comment by aj3423** [comment]
It still happens,  but much less likely to happen.

**Comment by kirillrdy** [comment]
It stopped happening to me on start up, but still consistently  happens if i resize using  Win+{Left,Right} ( Gnome )

**Comment by fredizzimo** [comment]
This should be fixed in Neovide 0.11.0

**Comment by meisme-dev** [comment]
This still happens for me on Gnome if I resize or move the window, cannot reproduce on any other desktop

> It stopped happening to me on start up, but still consistently happens if i resize using Win+{Left,Right} ( Gnome )
