### ISSUE TITLE
Fullscreen toggle

### ISSUE THREAD

**Issue by kishikaisei** [neovide/neovide#923]
**Is your feature request related to a problem? Please describe.**
I would like to have the same mapping for going fullscreen and back without having to create a function in init.lua

**Describe the solution you'd like**
A command like :NeovideFullscreenToggle (Same as the `nvui` commands)

**Describe alternatives you've considered**
Different mappings for fullscreen and un-fullscreen

**Comment by last-partizan** [comment]
You could just use

```
command -nargs=0 NeovideToggleFullscreen :let g:neovide_fullscreen = !g:neovide_fullscreen
```

**Comment by kishikaisei** [comment]
Very nice, that works like a charm, I guess this feature is not really needed anymore?
Although I still think exposing the commands is a cool feature.

**Comment by wcascades** [comment]
How is this done in lua? For instance:
`local M = {}

function M.toggle_neovide_fullscreen()
  if vim.g.neovide_fullscreen then
    print("Debugging: neovide_fullscreen was true")
    vim.g.neovide_fullscreen = false
  else
    print("Debugging: neovide_fullscreen was false")
    vim.g.neovide_fullscreen = true
  end
end

return M
`
I can see the debugging prints working as expected. The value is being flipped, but the fullscreen is not being toggled.

**Comment by Actual-Voron** [comment]
@wcascades, here's what you can use
fullscreen is toggled via Ctrl-F11
```lua
M.general = {
  n = {
    ["<C-F11>"] = {
      function()
        vim.g.neovide_fullscreen = not vim.g.neovide_fullscreen
      end,
      "Toggle Fullscreen"
    },
  },
}
```
