### ISSUE TITLE
Fallback font is not used

### ISSUE THREAD

**Issue by WhyNotHugo** [neovide/neovide#925]
**Describe the bug**

A fallback font doesn't get picked up as expected. I've tried two different mechanisms, so I'll describe both here.

**To Reproduce**

1. Using `set guifont=Operator\ Mono\ Book:h11` renders everything in Operator Mono, but glyphs that are missing don't use the system-wide fallback. This fallback is configured via fontconfig, and does get picked up by others (e.g.: alacritty, firefox, etc):

```xml
<?xml version="1.0"?>
<!DOCTYPE fontconfig SYSTEM "fonts.dtd">
<fontconfig>
  <alias>
    <family>OperatorMono</family>
    <prefer><family>Symbols Nerd Font</family></prefer>
  </alias>
</fontconfig>
```

![image](https://user-images.githubusercontent.com/730811/131501712-3b61649c-c52c-4088-acaa-f6dc880074b7.png)
_Note the missing nerd icons on the status bar_

2. Using  `set guifont=Symbols\ Nerd\ Font:h11` renders glyphs from nerds fonts correctly, but does renders all regular letters with very weird spacing. This setting is not really expected to work, but I've just tested it to confirm that `Symbols\ Nerd\ Font:h11` is a value that's handled correctly by itself.

![image](https://user-images.githubusercontent.com/730811/131501759-dd568d62-a5ff-4b79-a356-1ce6ec9d52f9.png)
_Note that nerd icons on the status bar do look okay_

3. Using `set guifont=Operator\ Mono\ Book:h11,Symbols\ Nerd\ Font:h11`, everything renders the same as the first case, however, this setup should render glyphs using Nerd Fonts as expected.

![image](https://user-images.githubusercontent.com/730811/131501875-9a4e376b-1803-40f6-aef9-de9e4004e025.png)
_Same as (1)_

**Extra notes**

An extra note here: even though the font and font size is the same as my terminal font, it's rendered dramatically different.

![2021-08-31T14:24:42,619829442+02:00](https://user-images.githubusercontent.com/730811/131502044-788f6fe2-0b32-45f8-b93c-cf4f4dd86917.png)

On the left is neovide, and on the right is alacritty.

**Expected behavior**

Glyphs from the fallback fonts should render correctly in both scenarios (1) and (3).

** Actual behaviour**

Neither of both scenarios render Nerd Symbols correctly.

**Desktop (please complete the following information):**
 - OS: ArchLinux
 - Neovide Version [e.g. 0.5.0]: current master
 - Neovim Version [e.g. 0.5.0]: current master

**Please run `neovide --log` and paste the contents of the `.log` file here:**

[neovide_rCURRENT.log](https://github.com/neovide/neovide/files/7083894/neovide_rCURRENT.log)

**Additional context**

I looked through font-related issues and didn't find another that was the same scenario or close enough. Hopefully I didn't miss anything that was on-point.

**Comment by PyGamer0** [comment]
Note: You can't provide separate sizes for every font you specify in the list.

So you would do:
`set guifont=Operator\ Mono\ Book,Symbols\ Nerd\ Font:h11`

Closing, please reopen if your problem is note fixed.

**Comment by PyGamer0** [comment]
@WhyNotHugo so you want neovide to detect your fontconfig? Is there any other neovim gui that does it?

**Comment by WhyNotHugo** [comment]
Just to be clear, by fontconfig I mean [the library by that name](https://www.freedesktop.org/wiki/Software/fontconfig/).

Most other desktop applications follow its configuration; it's via `fontconfig` that font precendence/overrides/fallback are defined, as well as things like anti-aliasing and alike. Emoji fonts work due to being configured through it, and in my case, Nerd Symbols too  (the `Nerd Symbols` font is set to be preferred when using `Operator Mono`, so its glyphs are used when possible, and `Operator Mono` otherwise).

As I say this, I'm wondering if that's why neovide's font rendering is so _different_ (eg: a lot thinner and somewhat harder to read), maybe there's something not picking up native rendering there?

I don't know of any other neovim gui, since I haven't actually tried any other. I've only used neovim-native via  [alacritty](https://github.com/alacritty/alacritty) which is also Rust+winit, and uses [crossfont](https://crates.io/crates/crossfont), so that might have some useful reference.
