### ISSUE TITLE
Emoji always have a black background

### ISSUE THREAD

**Issue by WhyNotHugo** [neovide/neovide#926]
**Describe the bug**

All emoji glyphs are rendered with a black background.

neovide:

![image](https://user-images.githubusercontent.com/730811/131511707-cbe8072f-e0bf-4ea3-b286-15978a8354d6.png)

neovim on alacritty, for referrence:

![image](https://user-images.githubusercontent.com/730811/131511719-c820f35c-27b4-438f-8bc1-58905a12a8ad.png)

**To Reproduce**

Insert any emoji. The background of where they're rendered should be non-black.

**Expected behavior**

Emoji should have the same background as other glyphs.

**Desktop (please complete the following information):**
 - OS: ArchLinux 
 - Neovide Version: current master
 - Neovim Version: current master

**Additional context**

-

**Comment by PyGamer0** [comment]
Can you try a different colorscheme?

**Comment by WhyNotHugo** [comment]
Yup, this is the default colorscheme:

neovide:
![image](https://user-images.githubusercontent.com/730811/131521167-6829abec-6772-4c88-9fde-48ef119b6666.png)

nvim on alacritty
![image](https://user-images.githubusercontent.com/730811/131521219-e5f196a0-7885-40b3-aab4-989d52bc7d44.png)

**Comment by Kethku** [comment]
This is dependent on what fonts you have installed. I don't see this on my machine

**Comment by Kethku** [comment]
I'm not sure why it would render with black backgrounds... If others encounter this I would appreciate the heads up

**Comment by WhyNotHugo** [comment]
I currently suspect that this is due to the font library that's being used to render text. However, it might be something entirely different; I'll try and make a self-contained reproducible example, and maybe that'll help testing with other fonts or platforms.

**Comment by codeinabox** [comment]
I am experiencing this issue as well

**Comment by Kethku** [comment]
Closing for lack of response. Please reopen if you encounter this on current main

**Comment by WhyNotHugo** [comment]
Neovide crashes at startup (see #1356) since around a year ago, so I haven't been able to reproduce the issue nor confirm whether it's been fixed.
