### ISSUE TITLE
Window does not redraw upon workspace change in i3

### ISSUE THREAD

**Issue by Firobe** [neovide/neovide#928]
Hi, 
Thanks for the software, it's been a pleasure to use!

**Describe the bug**
When using i3, switching to another workspace and then back to the workspace where Neovide is running, the window does not redraw until it is focused or hovered.

**To Reproduce**
Using i3:

1. Launch Neovide on Workspace 1
2. Switch to Workspace 2
3. Switch back to Workspace 1
4. The Neovide window is not drawn

**Expected behavior**
The window should be drawn when switching back to the workspace.

**Screenshots**

https://user-images.githubusercontent.com/5913585/131661667-42de5b3e-ce41-4a99-9f32-a289066da229.mp4

**Desktop (please complete the following information):**
 - OS: Manjaro i3 (Linux)
 - Neovide Version 0.8.0
 - Neovim Version 0.5.0

**Please run `neovide --log` and paste the contents of the `.log` file here:**
See attached: [neovide_rCURRENT.log](https://github.com/neovide/neovide/files/7090662/neovide_rCURRENT.log)

**Comment by Kethku** [comment]
Thanks for the fix <3

**Comment by Firobe** [comment]
Can confirm it works, thank you @rhoot!

**Comment by Kethku** [comment]
Agreed. Big thanks!
