### ISSUE TITLE
"Alt + any key" goes to normal mode from insert mode.

### ISSUE THREAD

**Issue by aj3423** [neovide/neovide#930]
**Describe the bug**
In insert mode, press Alt + any key goes to normal mode.  I globally mapped "Alt + j / k" by AutoKey to choose the popup items in insert mode, it works fine with Nvim console and Nvim-qt, but not work in Neovide because it goes to normal mode. 

**To Reproduce**
1. Press "i", go to insert mode
2. Press Alt + i
3. it goes to normal mode

**Expected behavior**
Still in insert mode

**Screenshots**
![alt](https://user-images.githubusercontent.com/4710875/131805223-59cbe907-26f2-4cdb-ba70-ac71d4cfa94b.gif)

**Desktop (please complete the following information):**
- Kali Linux 2021.2 with everything up-to-date
- Neovide v0.8.0
- Neovim v0.6.0-dev

**Please run `neovide --log` and paste the contents of the `.log` file here:**
[press_alt_j.log](https://github.com/neovide/neovide/files/7097110/press_alt_j.log)

**Additional context**

**Comment by dariogoetz** [comment]
I have the same issue. This is particularly nasty as I use a German keyboard layout, where square and curly brackets are on the "Alt" layer, effectively preventing me from programming in neovide :(

**Comment by dariogoetz** [comment]
The issue seems resolved for me with 0.8.0

**Comment by MultisampledNight** [comment]
I cannot reproduce the issue either. Should this be closed?

**Comment by GNUqb114514** [comment]
Unfortuanally, now it's a issue in Neovim and it's INTENDED (see `:h i_META` or [the online document](https://neovim.io/doc/user/insert.html#i_META)).
Because I'm using a customized keyboard layout that have some keys on the Alt layer
so it also prevented me from coding :(
