### ISSUE TITLE
font size is constantly smaller than I want

### ISSUE THREAD

**Issue by Oreolek** [neovide/neovide#932]
font size from `guifont` setting is set much smaller than in other applications.

![Screenshot](https://user-images.githubusercontent.com/308627/131861941-1fdc666d-baf2-4083-a264-403e8c58369a.png)

Screenshotted, from left to right:
- kitty, font size 16
- neovide, guifont `h16`
- goneovim, same `vimrc`, guifont `h16`

I also think #913 is relevant here.

I'm on 0.7.0, Ubuntu 20.04.

**Comment by PyGamer0** [comment]
can you run a build from main branch??

**Comment by Oreolek** [comment]
huh, the latest *is* good on that

**Comment by PyGamer0** [comment]
> huh, the latest _is_ good on that

so is it fixed?

**Comment by Kethku** [comment]
I think the answer is yes. Closing
