### ISSUE TITLE
[Feature Request] Hiding Mouse Cursor While Typing

### ISSUE THREAD

**Issue by p0da** [neovide/neovide#935]
Many terminal emulators like Alacritty or Kitty have the option to hide the mouse cursor as soon as the user starts typing, would it be possible to implement a similar feature in neovide? Thanks for considering.

**Comment by PyGamer0** [comment]
Why would you want this? (just asking)

**Comment by dineshKumar777** [comment]
> Why would you want this? (just asking)

To vim users, mouse interactions are very low since it's a keyboard centric app. When editing in full screen, it would be awesome to have an option to hide mouse cursor like in other terminal apps.

Nice to have like cursor animations and all.

**Comment by jsosulski** [comment]
Hi @p0da,
if you want you can check out if  #1032 works for you. You just need to build neovide from that PR and have `let g:neovide_hide_mouse_when_typing = 1` set in your nvim.init / vimrc

**Comment by zhaogangang** [comment]
when i set g:neovide_hide_mou_when_typing = 1, it work goods, but i mouve the mouse, and key the keyboard, the mouse cursor not hide again

**Comment by zhaogangang** [comment]
nvim:0.7.0

**Comment by zhaogangang** [comment]
i set g:neovide_hide_mou_when_typing = 1, it work goods just use keyboard, but click the mouse, then key the keyboard, the mouse cursor not hide again, i think should hide mouse cursor when i key the keyboard anytime, just like in neovim

os version:ubuntu 20.1
nvim version:0.7.0
neovide version:0.10.1

**Comment by zhaogangang** [comment]
i have record video,but it not show the mouse cursor, so i am here explain more detail.
when i open neovide, mouse cursor is hide, and just use  keyboard only, it work goods, when move the mouse, and click it(must click, only move, it goods), this mouse cursor is show, then key the keyboard again, this mouse cursor not hide again.  if i use alt-tab switch chrome, and alt-tab back neovide, this mouse cursor hide again.

**Comment by jsosulski** [comment]
I cannot reproduce your bug on my machine. In any case, clicking the mouse without moving it, does not make the cursor visible on my end, so this is also different.

Still, I would suggest opening a new issue for your problem :)
