### ISSUE TITLE
<ScrollWheel*> mappings do not work

### ISSUE THREAD

**Issue by IndianBoy42** [neovide/neovide#936]
**Describe the bug**
Currently my bindings that are mapped to `<ScrollWheelUp>` (or any of the related `<*-ScrollWheel*>` do not fire when running in neovide

**To Reproduce**
1. Have the following lines in your init.lua
```
  vim.api.nvim_set_keymap("n", "<C-ScrollWheelUp>", "<C-a>", {})
  vim.api.nvim_set_keymap("n", "<C-ScrollWheelDown>", "<C-x>", {})
```
2. Try to hold Ctrl and scroll while the cursor is over a number

**Expected behavior**
The number should be incremented/decremented, Instead the screen just scrolls

**Desktop (please complete the following information):**
 - OS: PopOS 21.04
 - Neovide 0.8.0
 - NVIM v0.6.0-dev+111-gf22326ef0

**Comment by Kethku** [comment]
This is fixed in main.
