### ISSUE TITLE
Reload nvim/init.lua

### ISSUE THREAD

**Issue by IndianBoy42** [neovide/neovide#937]
I think it would be good to have a way to reload the inner neovim instance, without closing and reopening neovide itself (so that carefully constructed window layouts don't get broken). basically an equivalent of 

```
:qa # In nvim
nvim $original_cli_args # In terminal
```

There are already other plugins that do automatic session management, so probably that doesn't have to be handled, just launch nvim again with the same arguments

**Comment by PyGamer0** [comment]
> There are already other plugins 

There is: https://github.com/famiu/nvim-reload

Also is there any other gui that does it?

**Comment by IndianBoy42** [comment]
That one is archived and never worked for me anyway. The only reliable way I've found is closing neovim and reopening it. With auto-session i don't lose any setup

I don't know if any other GUI does, but doesn't mean neovide can't

**Comment by last-partizan** [comment]
I think this is should better be implemented at neovim level.

Sure, we can just relaunch nvim instance, but i don't think this is good idea.

What do you mean by "carefully constructed window layouts"? are you using tiling wm? maybe it can handle restoring window layout.

Neovide can already save window size, and there is another request to save window position, so maybe this is better target to follow.

**Comment by Kethku** [comment]
I agree with @last-partizan we don't control window location, so any solution here would require nvim side control. I'm closing this as out of scope
