### ISSUE TITLE
NeoVide captures keybindings modified by the Super key

### ISSUE THREAD

**Issue by milse113** [neovide/neovide#938]
**Describe the bug**
NeoVide captures the unmodified version of keybindings which use the super key. For example, Super-i enters insert mode, and Super-3 (a binding for my de actually), executes the next command 3 times, etc.

**To Reproduce**
1. Type Super-\<some vim binding>
2. See NeoVide execute the vim binding

**Expected behavior**
NeoVide should treat input modified by Super as distinct from that which is not

**Desktop (please complete the following information):**
 - OS: Arch Linux (5.13.10-arch1-1)
 - Neovide Version: 0.7.0
 - Neovim Version:. 0.6.0-dev, but I experienced this issue with 0.5.0 too

**Please run `neovide --log` and paste the contents of the `.log` file here:**
This command did not open a file nor print the contents of one

**Comment by PyGamer0** [comment]
> This command did not open a file nor print the contents of one

It should create a `.log` file in the same directory

**Comment by rti** [comment]
The super/logo/meta key is disabled by default. Could changing this setting be of any help?

https://github.com/neovide/neovide/wiki/Configuration#use-logo-key

**Comment by milse113** [comment]
That does not fix it no

**Comment by rti** [comment]
Could you try to check out the main branch? As I understand it, keyboard input was being worked on in the recent months.

**Comment by milse113** [comment]
I'm using the main branch build no?

**Comment by rti** [comment]
You wrote you are using 0.7.0. This is the last release and not the current development branch "main". Did you build the main branch and still have the issue?

**Comment by dineshKumar777** [comment]
@milse113 Did you got the chance to try with main branch!!

**Comment by fredizzimo** [comment]
This should be fixed by #1899, it would be great if you can test that.
