### ISSUE TITLE
Incompatible with nvim-notify plugin

### ISSUE THREAD

**Issue by IndianBoy42** [neovide/neovide#939]
**Describe the bug**
[nvim-notify](https://github.com/rcarriga/nvim-notify) is a plugin that gives animated popup notifications with an api compatible with `vim.notify`.  Unfortunately it doesn't work correctly 

**To Reproduce**
1. Install the plugin using the instructions in their README.md (`use "rcarriga/nvim-notify"`)
2. Send a notification using `:lua require'notify'("Hello World")`
3. Every frame of the animation is interrupted by some text printed in the cmdline window, we have to click enter to proceed frame by frame

**Expected behavior**/**Screenshots**
[This drive folder](https://drive.google.com/drive/folders/1898pr5w2h80ZmuqNK-AjjIvdP2VV8ENn?usp=sharing) has examples from neovide and alacritty 

**Desktop (please complete the following information):**
 - OS: PopOS 20.10
 - Neovide Version 0.8.0
 - https://drive.google.com/drive/folders/1898pr5w2h80ZmuqNK-AjjIvdP2VV8ENn?usp=sharing

**Comment by dineshKumar777** [comment]
@IndianBoy42  you can directly upload in github issue itself. Why uploading in drive.. Its asking for access

**Comment by IndianBoy42** [comment]
Github doesn't support webm apparently, I have opened access to the drive folder

**Comment by dineshKumar777** [comment]
> Github doesn't support webm apparently, I have opened access to the drive folder

Yeah.. I faced that issue before. Please grant public access to that folder, so that anybody can view.

Or record in MP4 or other format and you can directly attach it in github itself. Thanks

**Comment by IndianBoy42** [comment]
It should be public now?

**Comment by danielnehrig** [comment]
i think it be better to implement such behavior into the graphic logic of neovide
or just push notify over terminal and use something like dunst to display it

**Comment by IndianBoy42** [comment]
That sounds good too, if you make a function with the API of vim.notify, then mostly everyone will be automatically compatible. That's what nvim_notify does

**Comment by dineshKumar777** [comment]
This is resolved now. Tested with and without multigrid.
Please take latest and give it a try

**Comment by dineshKumar777** [comment]
This is working now. Closing. 
Please reopen if you still face this issue.
