### ISSUE TITLE
Adjust floating window position when the window is broader than main window

### ISSUE THREAD

**Issue by crowdigit** [neovide/neovide#941]
**Describe the bug**
If I try open a floating window that is broader than main window, the opened window is off-centered and I can't see its contents.

**To Reproduce**
In my case I used Neovim's LSP hover information.

1. Setup Neovim LSP with LspConfig
2. Write a code that is documented long enough. I used Rust's `std::env::current_dir`
3. Open code 'hover information' (with default keymap 'K').

**Expected behavior**
It should appear like this (it's from my terminal Neovim)
![neovim](https://user-images.githubusercontent.com/87285844/132167272-2778e0da-2ac7-47c4-bdcb-c36181a40b80.png)

**Screenshots**
Instead, it appears this way
![neovide](https://user-images.githubusercontent.com/87285844/132167317-6e8eaea2-2828-4521-af7e-ba8e362d3487.png)

**Desktop (please complete the following information):**
 - OS: Archlinux
 - Neovide Version 0.8.0
 - Neovim Version 0.5.0

**Please run `neovide --log` and paste the contents of the `.log` file here:**

[neovide_rCURRENT.log](https://github.com/neovide/neovide/files/7113682/neovide_rCURRENT.log)

**Comment by crowdigit** [comment]
Closing due to it's not Neovide's bug but Neovim's.

**Comment by crowdigit** [comment]
Closing due to it's not Neovide's bug but Neovim's.

**Comment by dineshKumar777** [comment]
#1070 - duplicate
PR #1078 resolved this issue. Please reopen if you face this issue.
