### ISSUE TITLE
add basic support for touch screen

### ISSUE THREAD

**Issue by prabirshrestha** [neovide/neovide#95]
Sometime I just like scrolling on touch screen :). Just basic scroll up and scroll down would be good similar to how windows cmd works.

**Comment by Kethku** [comment]
This seems reasonable to add. I agree it should be good to be able to touch on the screen and jump the cursor or scroll a buffer.

**Comment by tim-harding** [comment]
I'd give this a shot.

**Comment by Kethku** [comment]
This is for sure up for grabs! I believe this problem cropped up when we swapped to sdl2 from winit. There is hope that we will move back to winit in the not too distant future, but it may be a ways out yet still.

**Comment by JakubKoralewski** [comment]
Support for touchpad scrolling, and mousewheel scrolling are in the same scope as this issue or should I open a new one for those?

**Comment by p00f** [comment]
Touchpad and mousepad scrolling can be done by mapping scrollwheel up/down to C-e/C-y, no?

**Comment by shaunsingh** [comment]
Touchpad scrolling (and by extent touchscreen scrolling) should work on the openGL branch. Ill look into how to implement cursor support with the touchscreen
