### ISSUE TITLE
PATH is not being set

### ISSUE THREAD

**Issue by vinicius507** [neovide/neovide#957]
**Describe the bug**
Neovide stopped setting up PATH.

**To Reproduce**
1. Open Neovide
2. Run the command `lua print(vim.env.PATH)`

**Expected behavior**
Show the default entries to PATH set by xorg.

**Desktop (please complete the following information):**
 - OS: `Linux myriad 5.14.3-arch1-1 #1 SMP PREEMPT Sun, 12 Sep 2021 20:51:34 +0000 x86_64 GNU/Linux`
 - Neovide Version 0.8.0 (`neovide-git` at AUR)
 - Neovim Version 0.5.0

**Comment by Kethku** [comment]
I don't understand. vim.env.PATH is the system path. As far as I know neovide is not responsible for setting up the path and has never done that in the past.

Maybe I'm misunderstanding something

**Comment by vinicius507** [comment]
I might have misunderstood how it worked then. Before this week vim.env.PATH showed the system PATH correctly. Now it is empty for some reason. It *might* be the way I'm launching neovim as a server(altough I haven't changed it since then). 

I'll investigate further tomorrow, closing for now.

Thanks, though.

**Comment by Kethku** [comment]
Only thing I can think of is related to process disowning. https://github.com/neovide/neovide/blob/main/src/main.rs#L203 Recently (as in a month or so ago) there was a change which made neovide disown the process by default rather than requiring a flag

**Comment by vinicius507** [comment]
It seems as if Neovide wasn't running with the flag `--remote-tcp`. Because of this, it was starting a `nvim --embed` session with xorg and connecting to it. For some reason it suddenly started connecting and everything went haywire. Thanks for the help, though.

**Comment by Kethku** [comment]
I'm happy to help debug more if you want. Feel free to reopen this issue or create a new one at any time
