### ISSUE TITLE
Emojis appear no-colored 

### ISSUE THREAD

**Issue by A-Siam** [neovide/neovide#959]
**Describe the bug**
When copying a colored emoji it falls back to the no color one 

**To Reproduce**
1. Install neovide-git on ArchLinux (NOTE: neovide without git doesn't add emojis at all)
2. set `vim.opt.guifont= "JetBrainsMono Nerd Font:h" .. font_size .. ", Noto Color Emoji:h" .. font_size;`

**Expected behavior**
Having noto colored emojis to appear when using emojis

**Screenshots**
![Emojis screeshot](https://user-images.githubusercontent.com/34966791/133635885-819670f9-f606-414a-bca8-f3d6675a0c56.png)

**Desktop (please complete the following information):**
 - OS: Arch linux
 - Neovide Version 0.8.0
 - Neovim Version 0.5.0

**Please run `neovide --log` and paste the contents of the `.log` file here:**
No output

**Comment by A-Siam** [comment]
A workaround was to remove that fullback font then noto emojis appeared as expected

**Comment by PyGamer0** [comment]
Try a different colorscheme? Try it in a terminal?

**Comment by A-Siam** [comment]
In terminal it depends whether or not it does support colored emojis, for example, vte based terminals do support colored emojis so they appear normally other terminals may not support that.

**Comment by Kethku** [comment]
I believe this is dependent on the system emoji font. We depend on skia to do font fallback and select where to render a given glyph from.

However you can effect the font selection process by adding an emoji font to the guifont config. You can specify 1 or more manual font fallback options by separating the font names by commas. For example my guifont setting looks like this:

```
Cascadia Code PL,Delugia Nerd Font,Segoe UI Emoji:h11
```

Which renders fine on windows. 

![image](https://user-images.githubusercontent.com/3323631/133905133-ea4aa7c5-c767-487e-894f-d5c3794688ff.png)

I'm going to close this as I believe its a user config issue. However if you have further problems feel free to reopen.
