### ISSUE TITLE
Floaterm is slow

### ISSUE THREAD

**Issue by hgup** [neovide/neovide#963]
**Describe the bug**
The [floaterm plugin](https://github.com/voldikss/vim-floaterm) is lagging so much that each keypress takes almost a second to register.

**Expected behavior**
I have compared it with neovim running on my windows terminal and the experience was smooth. Neovide in general is also running smoothly, but floaterm in Neovide is 💀 .

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Neovide Version v0.5.0 (built from source)
 - Neovim Version v0.5.0

**Comment by PyGamer0** [comment]
> Neovide Version v0.5.0 (built from source)

The latest version is 0.8.0

**Comment by hgup** [comment]
Okay, but I built the latest stable version. Please confirm if any bugs related to floaterm were fixed in the beta versions.

**Comment by hgup** [comment]
Alright, I think I got the issue. My PC isn't capable of handling the transparency effects of floaterm. Even though, its strange how its not optimized.
I realized this by running floaterm without the `--multigrid` parameter.

One request, please provide a wiki to all the global variables of Neovide. I want to disable *only* the translucent effects for floating windows whilst enjoying the animations of `--multigrid`  flag.
