### ISSUE TITLE
Line number isnt seperated from the text

### ISSUE THREAD

**Issue by MarcelskyXD** [neovide/neovide#965]
So i've been using neovide as my neovim client and noticed one issue, the line number isnt seperated from the text
![obraz](https://user-images.githubusercontent.com/62389326/133893841-ba7990da-a577-49b1-9d9e-5f777844e892.png)
Does anyone know  how to fix this?

**Comment by Kethku** [comment]
Please give information about versions and os you are using. Ideally follow the issue template

**Comment by MarcelskyXD** [comment]
> 
> 
> Please give information about versions and os you are using. Ideally follow the issue template

Windows 10, latest neovide version (as of 18.09.2021)

**Comment by Kethku** [comment]
Where did you download that neovide version? From releases? built from scratch?

**Comment by MarcelskyXD** [comment]
> 
> 
> Where did you download that neovide version? From releases? built from scratch?

releases

**Comment by Kethku** [comment]
I believe this is fixed in main. Please build from the main branch or download from a release here https://github.com/neovide/neovide/actions. There has been some formatting issues, so you may have to go back a bit but the issue has been fixed for a while
