### ISSUE TITLE
Font width

### ISSUE THREAD

**Issue by distek** [neovide/neovide#966]
**Is your feature request related to a problem? Please describe.**
No? It appears to just be a missing option.
I looked through src/renderer/fonts/font_options.rs, but didn't see anything related.

**Describe the solution you'd like**
Be able to set the font character width via the `guifont` option.

**Describe alternatives you've considered**
n/a

**Additional context**
From the help docs:
```
	For the Win32 GUI					*E244* *E245*
	- takes these options in the font name:
		hXX - height is XX (points, can be floating-point)
		wXX - width is XX (points, can be floating-point)
		b   - bold
		i   - italic
		u   - underline
		s   - strikeout
		cXX - character set XX.  Valid charsets are: ANSI, ARABIC,
		      BALTIC, CHINESEBIG5, DEFAULT, EASTEUROPE, GB2312, GREEK,
		      HANGEUL, HEBREW, JOHAB, MAC, OEM, RUSSIAN, SHIFTJIS,
		      SYMBOL, THAI, TURKISH, VIETNAMESE ANSI and BALTIC.
		      Normally you would use "cDEFAULT".

	  Use a ':' to separate the options.
	- A '_' can be used in the place of a space, so you don't need to use
	  backslashes to escape the spaces.
	- Examples: >
	    :set guifont=courier_new:h12:w5:b:cRUSSIAN
	    :set guifont=Andale_Mono:h7.5:w4.5
```

I am not using Windows here, but I think this would be a nice option.

**Even more context**
This is why this would be handy in my usecase (Neovide on left, alacritty on right):
![swappy-20210918_155553](https://user-images.githubusercontent.com/49327592/133910597-c3bba4e1-6f5c-45a2-9b87-90b7b1084ced.png)

**Comment by last-partizan** [comment]
@distek did you set font width for Alacritty?

Maybe this is not about missing option for font width, but about bad rendering of this specific font?
How does it work in other neovim GUI? or gvim?

**Comment by Kethku** [comment]
I believe this may now be fixed. @distek can you try with current main?

**Comment by Kethku** [comment]
Please reopen if the issue still persists.
