### ISSUE TITLE
Change of screen causes change in rendered font size.

### ISSUE THREAD

**Issue by ilveroluca** [neovide/neovide#970]
**Describe the bug**

Font rendering changes when I change display.  I have configured a font size that suits me fine on my external monitor; when I move the neovide window to my laptop screen (which has a smaller size and resolution) the size of the characters on the screen changes and becomes too big.

**To Reproduce**
1. Connect two different displays to you computer -- e.g., laptop screen and external monitor.
2. Open a neovide windows on one of the screens.
3. Move the window to the other screen
4. The size of the characters should change.

**Expected behavior**
The size of the rendered characters should be constant.

**Screenshots**
![Screenshot_external](https://user-images.githubusercontent.com/1502936/134479727-08507f5e-f2d2-44a3-957f-9477530f4080.png)
![Screenshot_laptop](https://user-images.githubusercontent.com/1502936/134479739-569d92e8-9c8f-454a-aa13-c9b65cc62373.png)

**Desktop (please complete the following information):**
 - OS: Kubuntu 20.04.3 LTS, Linux kernel 5.11.0, X.Org X Server 1.20.11
 - Neovide Version: compiled from source, main branch, commit 18f9ae5da
 - Neovim Version: 0.4.3

**Please run `neovide --log` and paste the contents of the `.log` file here:**
[neovide_rCURRENT.log](https://github.com/neovide/neovide/files/7216226/neovide_rCURRENT.log)

**Additional context**

**Comment by jonvaldes** [comment]
This looks like a HiDPI setting issue. Have you configured HiDPI settings on your system, perhaps?

See: https://wiki.archlinux.org/title/HiDPI

It is still possible that there's indeed a Neovide bug here, but would be good to confirm

**Comment by jonvaldes** [comment]
By the way, to get around font size issues like this (or simply to increase the font size when my eyes are tired, I use this code snippet. It also allows for changing the font itself, but the font size changing is what I use the most :)

https://gist.github.com/jonvaldes/6729602ad7f79957cae984208b30f670

**Comment by ilveroluca** [comment]
I have not configured HiDPI settings.  By the sounds of it, my problem may indeed be rooted here.  I'm using Xorg (default on Ubuntu 20) and, from what I understand, it uses a global DPI scaling factor for all monitors.  This seems to be confirmed from what I see with `xdpyinfo`.  I guess I can try the tweaks explained in the Arch wiki to which you linked, or try Wayland.  Still, I don't see these problems with other software.

Thanks for the font changing snippet.  I'll try it out!

**Comment by Kethku** [comment]
I think this works on current main. Closing as stale
