### ISSUE TITLE
Neovide hangs and eventually stops responding on windows/Radeon 480 GPU

### ISSUE THREAD

**Issue by dartacao** [neovide/neovide#971]
**Describe the bug**
Neovide doesn't respond after opening, black screen and cursor does not move. I'm on Win 10, with a Radeon 480 GPU, AMD-FX8350. This seems to be a different issue but maybe related to #907, but is a different behavior at least.

**To Reproduce**
1. Open neovide (with or without --clean)
2. neovide hangs for a while, on black screen with a white cursor. Nothing happens, doesn't respond.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Win10 Home 21H1 - 19043.1237
 - Neovide Version - 0.8.0
 - Neovim Version - NVIM v0.6.0-dev+132-g7d2233fad

**Please run `neovide --log` and paste the contents of the `.log` file here:**

> TRACE [neovide] Neovide version: 0.8.0
> INFO [neovide::bridge] Starting neovim with: Command { std: "C:\\Users\\Henrique Santos\\Desktop\\nvim\\nvim\\bin\\nvim.EXE" "--embed" "--clean", kill_on_drop: false }
> INFO [neovide::bridge] Close watcher started
> DEBUG [neovide::bridge::events] Ignored client type property: "methods"
> DEBUG [neovide::bridge::events] Ignored client type property: "attributes"
> INFO [neovide::bridge] Neovide registered to nvim with channel id 1
> ERROR [neovide::error_handling] Could not attach ui to neovim process: Error processing request: 1 - 'Expected width > 0 and height > 0')
> INFO [neovide:: window::window_wrapper] window created (scale_factor: 1.0000, font_dimensions: Dimensions { width: 11, height: 23 })
> TRACE [neovide::redraw_scheduler] Next frame queued
> TRACE [neovide::redraw_scheduler] Next frame queued
> TRACE [neovide::redraw_scheduler] Next frame queued
> TRACE [neovide::renderer::fonts::caching_shaper] Shaping text:  

(Next frame queued repeats ad nauseum...)

**Comment by leon332157** [comment]
Same here, its not consistent. Sometimes it freezes sometimes it works.

**Comment by srs-ch** [comment]
I am having the same issue on windows with Nvidia Quadro RTX 3000

> TRACE [neovide] Neovide version: 0.8.0
INFO [neovide::bridge] Starting neovim with: Command { std: "C:\\Users\\<userid>\\scoop\\shims\\nvim.EXE" "--embed", kill_on_drop: false }
INFO [neovide::bridge] Close watcher started
DEBUG [neovide::bridge::events] Ignored client type property: "methods"
DEBUG [neovide::bridge::events] Ignored client type property: "attributes"
INFO [neovide::bridge] Neovide registered to nvim with channel id 1
ERROR [neovide::error_handling] Could not attach ui to neovim process: Error processing request: 1 - 'Expected width > 0 and height > 0')
INFO [neovide::window::window_wrapper] window created (scale_factor: 2.2500, font_dimensions: Dimensions { width: 26, height: 52 })
TRACE [neovide::redraw_scheduler] Next frame queued
TRACE [neovide::renderer::fonts::caching_shaper] Shaping text:  
TRACE [neovide::redraw_scheduler] Next frame queued
TRACE [neovide::redraw_scheduler] Next frame queued
TRACE [neovide::redraw_scheduler] Next frame queued
TRACE [neovide::redraw_scheduler] Next frame queued
TRACE [neovide::redraw_scheduler] Next frame queued
TRACE [neovide::redraw_scheduler] Next frame queued
TRACE [neovide::redraw_scheduler] Next frame queued
TRACE [neovide::redraw_scheduler] Next frame queued
TRACE [neovide::redraw_scheduler] Next frame queued
TRACE [neovide::channel_utils] ui_command FocusLost
TRACE [neovide::redraw_scheduler] Next frame queued
TRACE [neovide::channel_utils] ui_command FocusGained
TRACE [neovide::redraw_scheduler] Next frame queued
TRACE [neovide::redraw_scheduler] Next frame queued
TRACE [neovide::channel_utils] ui_command Quit

**Comment by grififth** [comment]
Same issue, just installed neovide today for that smooth cursor. I'm using Windows 11 and running it with --wsl. Logs aren't showing anything useful unfortunately. Hopefully this gets fixed soon as sometimes it works and sometimes it doesn't.

**Comment by Kethku** [comment]
Very interesting. The Expected width seems like the problem. I will look into it

**Comment by Kethku** [comment]
I made a change which ensures that the window size loaded from file is not zero. I think this may fix the parent issue here
