### ISSUE TITLE
Neovide crashes when computer goes to sleep

### ISSUE THREAD

**Issue by ilveroluca** [neovide/neovide#972]
**Describe the bug**
Neovide crashes when computer goes to sleep.

**To Reproduce**
1. Open neovide
2. Put computer to sleep
3. Wake up computer

**Expected behavior**
Neovide should not crash (ever :-) )

**Screenshots**
None

**Desktop (please complete the following information):**
 - OS: Kubuntu 20.04.3 LTS, Linux kernel 5.11.0, X.Org X Server 1.20.11
 - Neovide Version: 0.8.0+, compiled from source, main branch, commit 18f9ae5
 - Neovim Version: 0.4.3

**Please run `neovide --log` and paste the contents of the `.log` file here:**
[neovide_rCURRENT.log](https://github.com/neovide/neovide/files/7217115/neovide_rCURRENT.log)

**Additional context**
Backtrace:
```
[pireddu@baba ~] RUST_BACKTRACE=1 gnvim --log
[pireddu@baba ~] thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 4, kind: Interrupted, message: "Interrupted system call" }', /home/pireddu/.cargo/git/checkouts/winit-cdba476763ae8f28/3b5462e/src/platform_impl/linux/x11/mod.rs:396:54
stack backtrace:
   0: rust_begin_unwind
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:515:5
   1: core::panicking::panic_fmt
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/panicking.rs:92:14
   2: core::result::unwrap_failed
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/result.rs:1599:5
   3: winit::platform_impl::platform::x11::EventLoop<T>::run
   4: winit::platform_impl::platform::EventLoop<T>::run
             at ./.cargo/git/checkouts/winit-cdba476763ae8f28/3b5462e/src/platform_impl/linux/mod.rs:676:56
   5: winit::event_loop::EventLoop<T>::run
   6: neovide::window::window_wrapper::create_window
             at ./Programs/neovide/src/window/window_wrapper/mod.rs:301:5
   7: neovide::main
             at ./Programs/neovide/src/main.rs:171:5
   8: core::ops::function::FnOnce::call_once
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/ops/function.rs:227:5
```

**Comment by Kethku** [comment]
This is an upstream issue https://github.com/rust-windowing/winit/pull/1952

**Comment by enderger** [comment]
Looks fixed in <https://github.com/rust-windowing/winit/pull/1952> and probably can be merged from upstream.

**Comment by Kethku** [comment]
I believe this is fixed in main

**Comment by xarthurx** [comment]
I'm encounter this issue again with `v0.11.1`
