### ISSUE TITLE
Italic fonts are clipped

### ISSUE THREAD

**Issue by kishikaisei** [neovide/neovide#973]
**Describe the bug**
When using a colorschemes that sets some text to italic, part of the text is clipped.

**To Reproduce**
1. Use a colorscheme that have use of italics (Kosmikoa)
2. Open a file that has a list
    ❌ Witness clipping
    ✔ No clipping and the font is shown in full

**Screenshots**
Neovide right now (the pink items):
![image](https://user-images.githubusercontent.com/1894123/134511878-9dc461d4-3626-461b-b914-8408fbc273ad.png)
Nvy, desired behaviour:
![image](https://user-images.githubusercontent.com/1894123/134511924-78730b0c-cc10-4e5b-965f-a4d9c461733f.png)

**Desktop (please complete the following information):**
 - OS: Win 10
 - Neovim Version 0.6.0
 - Neovide Version 0.8.0

**Comment by Kethku** [comment]
Can you try https://github.com/neovide/neovide/pull/974 I think it fixes this issue.

**Comment by dineshKumar777** [comment]
#974 resolved this issue for me. 

![image](https://user-images.githubusercontent.com/21097695/134619501-6ba27104-5a80-4d69-a57b-aaca76a8eacd.png)

**Comment by Kethku** [comment]
Thanks for testing! Fixed.
