### ISSUE TITLE
Keystrokes arrive out of order under load

### ISSUE THREAD

**Issue by Resonious** [neovide/neovide#975]
**Describe the bug**
If my environment stresses out nvim/neovide enough, my keystrokes start arriving out of order.

**To Reproduce**
Unfortunately, the way I produce this is pretty specific to my environment right now. I don't know of a simple way to make this happen on any machine.

1. Use Wayland on GNOME 3, 2560x1440 display, 1.5x scaling.
1. Set a pretty small guifont size in init.vim (13 or lower).
2. Launch Neovide with multigrid, maximized.
3. Navigate to a very large project (Neovide itself is too small to trigger this!)
3. Use FZF's `:Rg` command to ripgrep through files.
4. Type some text.

**Expected behavior**
My 7th gen Thinkpad starts to chug from the high resolution and large project. In older versions of Neovide, my text would come in at a delay, but with no problems. In newer versions, my text comes in at a delay and out of order!

**Screenshots**

https://user-images.githubusercontent.com/2793160/134611181-710e4ee9-d905-4216-bfe0-317768c5b2bf.mp4

Actual text typed: "okay here is some text"

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Neovide main
 - Neovim 0.5.0

**Additional context**
I ran a git bisect and this behavior was introduced in fec2711b90b49ad3acaeeccf4c41746e01cf7fc7. I have some spare time today so I'll try to find a good solution myself, but if anyone knows off the top of their head how to solve it then feel free to beat me to it :wink:

**Comment by Kethku** [comment]
This has bothered me for a while. As an added wrinkle, I only ever encounter this in a terminal window. I believe fzf uses a terminal window to build its functionality so this checks out. This leads me to believe that something strange is happening upstream but I haven't been able to track this down

**Comment by Resonious** [comment]
Fixed by #996
