### ISSUE TITLE
Some characters don't display in full width

### ISSUE THREAD

**Issue by TunkShif** [neovide/neovide#977]
**Describe the bug**
Some characters (like NerdFont icons, emoji and some other unicode characters...) do not always show in full width

As shown below, the icons in the right-side symbol outline in Neovide didn't show in full, though it shows properly in alcratty.
![20210924-15-42-26](https://user-images.githubusercontent.com/10807119/134637861-744510a7-086d-4f67-a2d2-87e2f211a5ff.png)

Besides, the `─` character used in floating window border didn't show in full width, either.
The following first picture shows a floating window in Neovide and the next one shows it in alacratty.

![20210924-15-44-36](https://user-images.githubusercontent.com/10807119/134639037-797a5f56-3d0e-441b-bae3-b1ea6acf6416.png)
![20210924-15-45-06](https://user-images.githubusercontent.com/10807119/134639241-8fb2ce69-6200-4b32-8b66-43206192b6d1.png)

And weird enough though, even in the same buffer, icons can be displayed differently

![20210924-15-46-13](https://user-images.githubusercontent.com/10807119/134639485-67345056-a3cc-406d-a0e1-0873a0336d13.png)

**To Reproduce**
1. try using any NerdFont, in my case I'm using FiraCode NerdFont
2. have `set guifont=FiraCode\ Nerd\ Font:h9` set in `init.vim`

**Desktop (please complete the following information):**
 - OS: ArchLinux
 - Neovide Version 0.8.0
 - Neovim Version 0.5.0

**Please run `neovide --log` and paste the contents of the `.log` file here:**
[neovide_rCURRENT.log](https://github.com/neovide/neovide/files/7224121/neovide_rCURRENT.log)

**Comment by PyGamer0** [comment]
Which commit is this?

**Comment by dineshKumar777** [comment]
@TunkShif Try with latest commit. #974 resolved some of these issues for me.

before vs after #974
![image](https://user-images.githubusercontent.com/21097695/134652315-3afe2476-088c-4bc0-afc0-9d471728ae96.png)

**Comment by TunkShif** [comment]
> @TunkShif Try with latest commit. #974 resolved some of these issues for me.
> 
> before vs after #974
> ![image](https://user-images.githubusercontent.com/21097695/134652315-3afe2476-088c-4bc0-afc0-9d471728ae96.png)

Thx! Tried the latest commit and it works!

**Comment by TunkShif** [comment]
> Which commit is this?

I've switched to the latest commit and now the icon problems are gone. Though the horizontal borderline of floating windows still displays in discontinuous lines.

**Comment by dineshKumar777** [comment]
> > Which commit is this?
> 
> I've switched to the latest commit and now the icon problems are gone. Though the horizontal borderline of floating windows still displays in discontinuous lines.

can you share your firacode nerd font download link. I am using following firacode nerd version and horizontal line is working fine.
https://github.com/ryanoasis/nerd-fonts/blob/master/patched-fonts/FiraCode/Regular/complete/Fira%20Code%20Regular%20Nerd%20Font%20Complete%20Windows%20Compatible.ttf

![image](https://user-images.githubusercontent.com/21097695/134665237-8c6e4cac-7e06-4b9c-9e15-cf5a0edfd538.png)

**Comment by TunkShif** [comment]
> > > Which commit is this?
> > 
> > 
> > I've switched to the latest commit and now the icon problems are gone. Though the horizontal borderline of floating windows still displays in discontinuous lines.
> 
> can you share your firacode nerd font download link. I am using following firacode nerd version and horizontal line is working fine.
> https://github.com/ryanoasis/nerd-fonts/blob/master/patched-fonts/FiraCode/Regular/complete/Fira%20Code%20Regular%20Nerd%20Font%20Complete%20Windows%20Compatible.ttf
> 
> ![image](https://user-images.githubusercontent.com/21097695/134665237-8c6e4cac-7e06-4b9c-9e15-cf5a0edfd538.png)

Just downloaded from nerdfonts.com. And I have tried other fonts. but still got the same.
Anyway, it's not quite a big problem for me. Thanks again for you help.

**Comment by PyGamer0** [comment]
Think this is fixed. Closing.
