### ISSUE TITLE
Neovide fails to read linux environment variables when launched with --wsl

### ISSUE THREAD

**Issue by HawkinsT** [neovide/neovide#983]
**Describe the bug**
When launching Neovide from Windows with --wsl it doesn't read in all environment variables from .profile (or .bashrc etc.), only $PATH (so far as I can tell) which leads to inconsistent behaviour. For example, executing commands via `:!` will act differently to executing them from `:term` (which does read in environment variables). In order to get around this I am (for now) having to specifically set the environment variables I require in my init.vim.

**To Reproduce**
1. Set $TEST to some value in .profile
2. In neovide enter `:!echo $TEST`
3. In neovide enter `:term echo $TEST`
4. See difference in output.

**Expected behavior**
Neovide --wsl should behave the same as nvim (when nvim is launched from within a wsl2 shell); that is, it should read in all environment variables since many vim scripts and packages can depend on these.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Neovide Version main compiled by me (reported as 0.8.0 in Windows properties menu)
 - Neovim Version v0.6.0-dev

**Comment by HawkinsT** [comment]
Addendum: It seems most environment variables are actually being set correctly. One I have had issues with though is `$DISPLAY`, which always seems to be null if not set within init.vim.

**Comment by HawkinsT** [comment]
Hmm, I'm using main (compiled two days ago).

**Comment by HawkinsT** [comment]
I'll try to test later, but I think at least part of the issue is Neovide using `$SHELL` blindly in https://github.com/neovide/neovide/blob/main/src/bridge/mod.rs and assuming POSIX compliance.

I've been using bash as my default shell until now with fish called at the end of my .bashrc but had issues with `$DISPLAY` not being set when in Neovide. Instead of calling fish from bash, if I make fish my default shell I've discovered that Neovide completley craps out and can't find anything on `$PATH` (e.g. I get a bunch of errors when launching Neovide and `:checkhealth` finds almost nothing, despite `:echo $PATH` and e.g. `:!which python3`, working correctly and being specified explicitly in config.fish as well as .profile and .bashrc), even though neovim within wsl has no issues. Changing `$SHELL` to `/bin/bash` in either my init.vim or config.fish files fixes this and the `$DISPLAY` issue.

If shell POSIX compliance is going to be assumed by Neovide, then perhaps `$SHELL` should be replaced with just invoking bash directly within mod.rs, or at least first looking for bash and using if found?

**Comment by fredizzimo** [comment]
I created a pull request that should fix the issue https://github.com/neovide/neovide/pull/1118

**Comment by fredizzimo** [comment]
I merged #1118. But see the comments there, there might be unexpected problems, so open a new issue if you find any.
