### ISSUE TITLE
neovide cuts off dashboard ascii image

### ISSUE THREAD

**Issue by LollipopFt** [neovide/neovide#987]
![image](https://user-images.githubusercontent.com/62802897/135294216-3a792e09-9984-4ff6-86ed-4b9637df41ce.png)
compared to original neovim:
![image](https://user-images.githubusercontent.com/62802897/135294335-b7345eaa-3788-4bc9-b7df-8a3334a87790.png)
and nvy:
![image](https://user-images.githubusercontent.com/62802897/135294389-a46069dc-6cf8-425c-a9ca-10eb0aa12c1d.png)

**Comment by Kethku** [comment]
Can you give details about how that dashboard image was created? Given that nothing else is cut off I think its specific to your configuration

**Comment by PyGamer0** [comment]
How about trying a different font?

**Comment by LollipopFt** [comment]
i have tried using a different font, neovide version: 0.5.0
dashboard image:
```lua
vim.g.dashboard_custom_header={
    '',
    ' ⣇⣿⠘⣿⣿⣿⡿⡿⣟⣟⢟⢟⢝⠵⡝⣿⡿⢂⣼⣿⣷⣌⠩⡫⡻⣝⠹⢿⣿⣷ ',
    ' ⡆⣿⣆⠱⣝⡵⣝⢅⠙⣿⢕⢕⢕⢕⢝⣥⢒⠅⣿⣿⣿⡿⣳⣌⠪⡪⣡⢑⢝⣇ ',
    ' ⡆⣿⣿⣦⠹⣳⣳⣕⢅⠈⢗⢕⢕⢕⢕⢕⢈⢆⠟⠋⠉⠁⠉⠉⠁⠈⠼⢐⢕⢽ ',
    ' ⡗⢰⣶⣶⣦⣝⢝⢕⢕⠅⡆⢕⢕⢕⢕⢕⣴⠏⣠⡶⠛⡉⡉⡛⢶⣦⡀⠐⣕⢕ ',
    ' ⡝⡄⢻⢟⣿⣿⣷⣕⣕⣅⣿⣔⣕⣵⣵⣿⣿⢠⣿⢠⣮⡈⣌⠨⠅⠹⣷⡀⢱⢕ ',
    ' ⡝⡵⠟⠈⢀⣀⣀⡀⠉⢿⣿⣿⣿⣿⣿⣿⣿⣼⣿⢈⡋⠴⢿⡟⣡⡇⣿⡇⡀⢕ ',
    ' ⡝⠁⣠⣾⠟⡉⡉⡉⠻⣦⣻⣿⣿⣿⣿⣿⣿⣿⣿⣧⠸⣿⣦⣥⣿⡇⡿⣰⢗⢄ ',
    ' ⠁⢰⣿⡏⣴⣌⠈⣌⠡⠈⢻⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣬⣉⣉⣁⣄⢖⢕⢕⢕ ',
    ' ⡀⢻⣿⡇⢙⠁⠴⢿⡟⣡⡆⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣷⣵⣵⣿ ',
    ' ⡻⣄⣻⣿⣌⠘⢿⣷⣥⣿⠇⣿⣿⣿⣿⣿⣿⠛⠻⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿ ',
    ' ⣷⢄⠻⣿⣟⠿⠦⠍⠉⣡⣾⣿⣿⣿⣿⣿⣿⢸⣿⣦⠙⣿⣿⣿⣿⣿⣿⣿⣿⠟ ',
    ' ⡕⡑⣑⣈⣻⢗⢟⢞⢝⣻⣿⣿⣿⣿⣿⣿⣿⠸⣿⠿⠃⣿⣿⣿⣿⣿⣿⡿⠁⣠ ',
    ' ⡝⡵⡈⢟⢕⢕⢕⢕⣵⣿⣿⣿⣿⣿⣿⣿⣿⣿⣶⣶⣿⣿⣿⣿⣿⠿⠋⣀⣈⠙ ',
    ' ⡝⡵⡕⡀⠑⠳⠿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠿⠛⢉⡠⡲⡫⡪⡪⡣ ',
    '',
}
```
funnily enough, even when trying to edit the source file, neovide displays the image as cut:
![image](https://user-images.githubusercontent.com/62802897/135491381-74f5f01a-e474-4789-b114-eaea92622e18.png)

**Comment by Kethku** [comment]
Which version of neovide are you using? Can you try from main?

**Comment by LollipopFt** [comment]
> 
> 
> Which version of neovide are you using? Can you try from main?

> neovide version: 0.5.0

what do you mean by _trying from main_?

**Comment by dineshKumar777** [comment]
> > Which version of neovide are you using? Can you try from main?
> 
> > neovide version: 0.5.0
> 
> what do you mean by _trying from main_?
Latest neovide version is 0.8.0. he is asking to build from source https://github.com/neovide/neovide#from-source

or you can directly download binary from github actions artifact. Following is the latest
https://github.com/neovide/neovide/actions/runs/1268541922

**Comment by LollipopFt** [comment]
> or you can directly download executable from github actions artifact. Following is the latest https://github.com/neovide/neovide/actions/runs/1268541922

in this version, the dashboard is fixed for me! however, it seems as if nerdfont icons don't work when using fallback font, when in 0.5.0 it did...
vim config:
```lua
vim.o.guifont='Fira Code Retina:h11:b:Medium, FiraCode NF Retina:h11:b:Medium'
```
![image](https://user-images.githubusercontent.com/62802897/135608881-cedb344d-7427-4738-bee6-bc590a7f5281.png)
normal:
![image](https://user-images.githubusercontent.com/62802897/135608946-928aedb2-d549-4d10-bb7e-68fa5556082f.png)
notice the icons next to ```Nvim Tree``` and the statusline.
i also realised that italics was not implemented, seen in ```Have fun with neovim```
_just realised i'm playing spot the difference_

**Comment by dineshKumar777** [comment]
for font fallback try as per this comment.
https://github.com/neovide/neovide/issues/925#issuecomment-909225009

**Comment by LollipopFt** [comment]
> 
> 
> for font fallback try as mentioned in this comment. [#925 (comment)](https://github.com/neovide/neovide/issues/925#issuecomment-909225009)

![image](https://user-images.githubusercontent.com/62802897/135611522-d0a9a743-1cdb-4713-94da-4be8dd56fca9.png)
new font config:
```lua
vim.o.guifont='Fira Code Retina:b:Medium, FiraCode NF Retina:b:Medium:h11'
```
could it be because of my ```b:Medium```?


also discovered another thing.
from above image compared to terminal:
![image](https://user-images.githubusercontent.com/62802897/135611784-9e837aef-04c4-49aa-8e5f-e6d72d26f6bc.png)
and goneovim:
![image](https://user-images.githubusercontent.com/62802897/135611837-a9b94e04-67ef-497d-895a-e05b5d627316.png)
notice that neovide scales up the font size for some reason. first noticed it when i was also using 0.5.0. should i open a new issue for this?

**Comment by PyGamer0** [comment]
Neovide uses points now, not pixels maybe thats why.

**Comment by dty2** [comment]
hey guys, I try to open or get this https://github.com/neovide/neovide/actions/runs/1268541922, but it 404

**Comment by LollipopFt** [comment]
> hey guys, I try to open or get this https://github.com/neovide/neovide/actions/runs/1268541922, but it 404

uh, are you sure this is the right issue?

**Comment by LollipopFt** [comment]
@dty2 i think old runs are removed after while, here is the latest run: https://github.com/neovide/neovide/actions/runs/10741396806#artifacts

**Comment by dty2** [comment]
@LollipopFt 
I'm grateful for you reply, and I try this " https://github.com/neovide/neovide/actions/runs/10741396806#artifacts"
I install neovide-linux-x86_64.tar.gz in it
![try](https://github.com/user-attachments/assets/082e66b4-a52c-4b0c-8dbf-c6b2a664050b)
but it not work... the problem of render the Braille is not solved...

**Comment by LollipopFt** [comment]
i think you can open a new issue stating the problem then.
