### ISSUE TITLE
Potential rendering issue with unicode characters -- Braille Pattern Dots

### ISSUE THREAD

**Issue by daephx** [neovide/neovide#990]
**Describe the bug**
I see a few open issues regarding font rendering and I'm here to add to the pot.
I'm currently using this lua plugin [neovim-dashboard](https://github.com/glepnir/dashboard-nvim) and there is a discrepancy without how the text is rendered in both the dashboard output and the config file.

I do not see the issue on other text art that are composed in ASCII and don't use unicode characters.

**To Reproduce**
1. Copy the text art image below
2. Paste it into your neovide
3. Do you get the same error?

**Expected behavior**
Render the text as expected

**Screenshots**
The dashboard: rendered in neovim under windows terminal
![WindowsTerminal_6049mNJw59](https://user-images.githubusercontent.com/36192863/135405876-0fae05fd-d2e6-4b9f-8ee9-efc192dba366.png)

The lua list for the art: Also in neovim under windows terminal
![WindowsTerminal_b3V0ZLBgSG](https://user-images.githubusercontent.com/36192863/135406001-8f286508-e391-447b-b715-be223d242f1b.png)

the lua list rendered in neovide: including custom configs
![image](https://user-images.githubusercontent.com/36192863/135411951-1ec259a6-ea85-446e-82f9-7bb9446c1a66.png)

the lua list rendered in neovide: without init file or plugins
![WindowsTerminal_jSSrXwKqRb](https://user-images.githubusercontent.com/36192863/135406113-fbf172f4-ffde-44cc-ba1b-2f123693e3df.png)

And finally, the text for that image
```lua
local ascii_theme_super_meatboy = {
  "    ⣀⣀⣤⣤⣦⣶⢶⣶⣿⣿⣿⣿⣿⣿⣿⣷⣶⣶⡄       ",
  "    ⣿⣿⣿⠿⣿⣿⣾⣿⣿⣿⣿⣿⣿⠟⠛⠛⢿⣿⡇       ",
  "    ⣿⡟⠡⠂ ⢹⣿⣿⣿⣿⣿⣿⡇⠘⠁  ⣿⡇ ⢠⣄    ",
  "    ⢸⣗⢴⣶⣷⣷⣿⣿⣿⣿⣿⣿⣷⣤⣤⣤⣴⣿⣗⣄⣼⣷⣶⡄  ",
  "   ⢀⣾⣿⡅⠐⣶⣦⣶ ⢰⣶⣴⣦⣦⣶⠴ ⢠⣿⣿⣿⣿⣼⣿⡇  ",
  "  ⢀⣾⣿⣿⣷⣬⡛⠷⣿⣿⣿⣿⣿⣿⣿⠿⠿⣠⣿⣿⣿⣿⣿⠿⠛⠃  ",
  "  ⢸⣿⣿⣿⣿⣿⣿⣿⣶⣦⣭⣭⣥⣭⣵⣶⣿⣿⣿⣿⣟⠉      ",
  "   ⠙⠇⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡟       ",
  "     ⣿⣿⣿⣿⣿⣛⠛⠛⠛⠛⠛⢛⣿⣿⣿⣿⣿⡇       ",
  "     ⠿⣿⣿⣿⠿⠿     ⠸⣿⣿⣿⣿⠿⠇       ",
  "                              ",
  "                              ",
  "         И Ǝ 0 V I M          ",
}
```

Admittedly, it's a bit wack how it's rendered on github or in notepad++
But in neovim, windows terminal and vscode all the spacing is aligned.

I'm using CaskaydiaCove Nerd Font and I assume it's monospace on those editors.
But that doesn't explain how it doesn't render the close quotes in neovide.

**Desktop (please complete the following information):**
 - OS: Windows 10 21H1 build 19043.1237
 - Neovide Version 0.7.0
 - Neovim Version 0.5.0

**Please run `neovide --log` and paste the contents of the `.log` file here:**
[neovide_rCURRENT.log](https://github.com/neovide/neovide/files/7257642/neovide_rCURRENT.log)

I took a minute to realize where it was,
maybe state where it's located or echo the path in the log command

**Comment by PyGamer0** [comment]
Can you build on main? Closing as dup of #987

**Comment by daephx** [comment]
Oh wow, my bad. I searched for issues regarding font issues and overlooked that one!
I attempted to compile main but ran into an issue so I am unable to verify if the issue still exists.
```
error: failed to run custom build command for `skia-bindings v0.40.2`

Caused by:
  process didn't exit successfully: `C:\Users\<USERNAME>\AppData\Local\Temp\neovide\target\release\build\skia-bindings-e1813e1054da2e9e\build-script-build` (exit code: 101)
  --- stdout
  cargo:rerun-if-env-changed=SKIA_DEBUG

  --- stderr
  thread 'main' panicked at 'unsupported target: Target { architecture: "x86_64", vendor: "pc", system: "windows", abi: Some("gnu") }', C:\Users\<USERNAME>\.cargo\registry\src\github.com-1ecc6299db9ec823\skia-bindings-0.40.2\build_support\binaries_config.rs:106:18
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by PyGamer0** [comment]
@daephx Grab an executable from here: https://github.com/neovide/neovide/actions/runs/1299683663

**Comment by daephx** [comment]
@PyGamer0 Nice! thanks. I can confirm that the issue for #987 is no longer present on my end with this build!
