### ISSUE TITLE
Gltichy cursor render

### ISSUE THREAD

**Issue by AlexW00** [neovide/neovide#997]
**Describe the bug**
Cursor animation glitches out

**To Reproduce**
Use macOS version, move cursor

**Screenshots**

https://user-images.githubusercontent.com/55558407/135886141-ca9a339f-1ce9-4c4f-9d15-bcf70c749b24.mp4

**Desktop (please complete the following information):**
 - OS: macOS 11.6 (20G165)
 - Neovide Version 0.6
 - Neovim Version 0.5.0

**Comment by Kethku** [comment]
That is very wild. Please try running from main

**Comment by AlexW00** [comment]
> That is very wild. Please try running from main

Main branch doesn't work on my machine (crash on startup as described in #995

**Comment by Kethku** [comment]
I see. Was that downloaded from the actions? That error looks like its specific to how the app is packaged and likely wouldn't happen when built from cargo.

But to be honest I know very little about macos builds so I'm not sure

**Comment by AlexW00** [comment]
When I try to build this version from source it crashes on start

**Comment by Kethku** [comment]
May be some opengl weirdness. Im a little out of my depth when it comes to skia internals so I'm not sure what's going on here. If I were you I'd try fiddling with settings on the paint object in the cursor renderer. I can send line numbers and links to the docs when I get back to my computer if you're interested in trying some things

**Comment by Kethku** [comment]
Closing as this is likely old. Please reopen if this persists.
