### ISSUE TITLE
Stop <C-[> from sending <Esc>

### ISSUE THREAD

**Issue by arafatamim** [neovide/neovide#999]
I know it is the default behaviour in many terminal emulators but would it be possible to opt out of it in Neovide? Because I map `Ctr+[` to switch buffers, and accidental presses of the Escape key triggers the behaviour.

**Comment by Kethku** [comment]
This is handled on the vim side not neovide. Not something we can fix to my knowledge. Feel free to correct me if I'm wrong. Would be happy to fix it if possible.
